### ISSUE TITLE
Timeline visualization

### ISSUE THREAD

**Issue by lucasbento** [wix/react-native-calendars#1]
Hey, thank you for this, it is an awesome project!

I was wondering if there would be a possibility to add something like Google Calendar's timeline visualization:

![timeline visualization](http://3x1g0rormh519xc7a20btynk.wpengine.netdna-cdn.com/wp-content/uploads/2013/09/google-calendar-schedule-640x456.jpg)

**Comment by tautvilas** [comment]
Hi @lucasbento , currently you can simulate something similar to this timeline view using `<Agenda />` component. You can specify item rendering function with `renderItem`. So you can render custom item height depending of time span for that item, but you would have to do height calculation yourself. Something like this:

renderItem={(item) => {return (<View style={{height: calculateHeightAccordingToTimespan(item)}} ><Text>{item.from} - {item.to}</Text></View>);}}

**Comment by lucasbento** [comment]
@tautvilas: interesting, will try to do so.

Would you consider it a good addition to the project? perhaps I can work on a PR in a few days.

**Comment by joshyhargreaves** [comment]
@tautvilas @lucasbento I actually worked on something similar to this over the weekend, without actually knowing this project existed! @lucasbento I'm not sure if this is what you envisioned, but would be happy to work on this with anybody.  

https://expo.io/@joshyhargreaves/react-native-event-calendar
https://giphy.com/gifs/3o7bubDIifNZMqXEIM

**Comment by tautvilas** [comment]
Hey, in version `1.2.5` I added new param for `Agenda`: `renderDay`. So now you can customise both the left side and right side of the rendered listing. I think there are some options that you can explore with custom rendering approach.

However we are not planning to include time related mapping and calculations any time soon to this library. We want to keep the scope of it more related to day-based calendars. However you could use freely use this lib as building block for your time-based agenda solution.

**Comment by lucasbento** [comment]
Hey @joshyhargreaves, that work is really awesome, exactly what I'm looking for, where can I see the source code?

@tautvilas: thanks for answering back, will take a look at it. ;)

**Comment by sibelius** [comment]
@joshyhargreaves any changes to open source https://expo.io/@joshyhargreaves/react-native-event-calendar?

**Comment by joshyhargreaves** [comment]
@sibelius @lucasbento thanks for the interest :). I'm looking to open source in the next few days! It's pretty raw currently, and rough around the edges, but I don't think open sourcing at this point can hurt.

**Comment by joshyhargreaves** [comment]
@lucasbento sorry for the delay: https://github.com/joshyhargreaves/react-native-event-calendar

It's a WIP currently, I need to rework the API in lots of ways, but it's a start none-the-less. 
Will be more than happy to talk discuss APIs and features :).

**Comment by saiemsaeed** [comment]
@tautvilas any progress on this feature?
