### ISSUE TITLE
Modernizing React-Native-Calendars

### ISSUE THREAD

**Issue by MartynHenderson** [wix/react-native-calendars#1007]
Would contributors of this project be willing to consider reworking it to use the more modern code formatting techniques such as arrow functions and hooks? 

It might be worth the time because a lot of use cases for calendars pull events from other parts of the app, which in my case is all structured using hooks and context api.

I have a feed of posted events and the calendar acts as a saved events feed. It would certainly be easier to work with a calendar api that integrates a more modern javascript approach.

Just some food for thought! It could strategically help with the library's relevance and longevity in 2020 and beyond. Thanks again for all the hard work you guys put into maintaining this library!

**Comment by nathsimpson** [comment]
Great idea Martyn!
It's definitely worth doing, however I don't believe this library is currently maintained as much as it probably should be (The wix team are looking for maintainers). That would probably have to change before a re-write would be considered :(

**Comment by chenei** [comment]
We definitely looking forward to refactor the code 🙌🏻 stay tuned.
