### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by AmroShohoud** [wix/react-native-calendars#1008]
## Description

Update react native expo to SDK 35.0.0. Calendar throws a warning.

## Expected Behavior

No warning.

## Observed Behavior

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Calendar, CalendarList
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.214.0 
* `npm ls react-native`: react-native@0.61.4

Also specify:

1. Phone/emulator/simulator & version: iPhone 8, iOS 12.2

## Reproducible Demo

Just update to newest version of react-native (0.61) and expo (SDK 35.0.0) [if expo is used]. Then simply import CalendarList and render it, and warning will be shown.

**Comment by dvester** [comment]
I am also experiencing this, I know this package is looking for maintainers, any news on that front? Trying to get an idea for when this can be fixed.

**Comment by stephanikoykoy** [comment]
Experiencing this too. Not only for Calendar by also for Agenda, 2 warnings are thrown - componentWillMount and componentWillReceiveProps

<img width="1420" alt="Screenshot 2019-12-16 at 01 10 31" src="https://user-images.githubusercontent.com/32569739/70866150-0e664300-1fa1-11ea-832f-b39cc6b3f89a.png">
<img width="1420" alt="Screenshot 2019-12-16 at 01 10 55" src="https://user-images.githubusercontent.com/32569739/70866152-11f9ca00-1fa1-11ea-89cd-fb50d265970d.png">

**Comment by PavlezT** [comment]
This is very annoying issue. I don`t think that this will take much time to solve this problem, so please update it asap.

**Comment by kogodabra** [comment]
I've caught the same warning
react-native-calendars@1.220.0 
react-native@0.61.4 
please update it

**Comment by eclatsujan** [comment]
I am also having same issue. If maintainer could change that those code into this one.

static getDerivedStateFromProps(nextProps, prevState){
    const current = parseDate(nextProps.current);
    if (current && current.toString('yyyy MM') !== prevState.currentMonth.toString('yyyy MM')) {
      return {
        currentMonth:current.clone()
      }
    }
    return prevState;
  }

**Comment by Inbal-Tish** [comment]
@AmroShohoud We're on it, there PRs in this matter that we're reviewing.

**Comment by Itayp1** [comment]
i am having the same issue

**Comment by jet2go** [comment]
Same here!

**Comment by Inbal-Tish** [comment]
@Itayp1 @jet2go Do you get this warning with versions later than 1.226.0?

**Comment by jet2go** [comment]
I'm using react-native-modal-datetime-picker but getting the same error shown above.

**Comment by Inbal-Tish** [comment]
@jet2go What is `react-native-modal-datetime-picker` has to do with this issue? The two libraries are not related. I was asking about react-native-calendars' version as we renamed these methods on version 1.226.0.

**Comment by niketanmoon** [comment]
> @Itayp1 @jet2go Do you get this warning with versions later than 1.226.0?

I m getting error in 1.261.0

**Comment by nathsimpson** [comment]
Same here ☝️

**Comment by Inbal-Tish** [comment]
I can't reproduce the issue. We renamed all of these methods... Can someone please send me a screenshot of the full warning?

**Comment by webmasterdragon** [comment]
Same issue with latest version.
`"react-native-calendars": "^1.264.0",`
Any update?

**Comment by chenei** [comment]
We renamed all our lifecycles, please reinstall your modules.
