### ISSUE TITLE
how to make  backgroundColor for weekend?

### ISSUE THREAD

**Issue by saidhappy010** [wix/react-native-calendars#1009]
I would like to make a background color for all days the weekend (Saturday, Sunday). like this image
![SsrLJDo](https://user-images.githubusercontent.com/46774272/70900759-bd366d80-1ff9-11ea-8696-8f19f8ba7938.png)

Please. How can we do that?.
Thnks.

**Comment by Inbal-Tish** [comment]
@saidhappy010 Use `markingType={'custom'}` and in your `markedDates` add all the weekend dates a `customStyle`. Something like this:
`
'2017-04-01': {
              customStyles: {
                container: {
                  backgroundColor: 'orange',
                  borderRadius: 0
                }
              }
            }
`
