### ISSUE TITLE
Knob hiding the days

### ISSUE THREAD

**Issue by kleytonlopes** [wix/react-native-calendars#101]
![calendar](https://user-images.githubusercontent.com/4513935/28252110-35082640-6a63-11e7-8675-ce720bfc42ff.png)

I find this problem in the android Lenovo K10a40 (1280x720).
I tried to solve by changing the background color of the knob to transparent, but its is equals to background color of the calendar. 
What is the best solution?

**Comment by overengineered** [comment]
This issue likely got introduced in 1.5.0, you may try using 1.4.1 as a workaround.

**Comment by tautvilas** [comment]
hello, please clarify the issue title that it states the problem

**Comment by tautvilas** [comment]
Please try if this is fixed in 1.5.4 @kleytonlopes
