### ISSUE TITLE
Calandar show wrong date information

### ISSUE THREAD

**Issue by jaiminp-nimblechapps** [wix/react-native-calendars#1010]
![Screenshot 2019-12-17 at 11 37 35 AM](https://user-images.githubusercontent.com/30400442/70969435-a52a2100-20c1-11ea-8b4d-8dd4175866aa.png)

Hello Guys

My date is showing wrong actually 1st date is sunday but my calendars start from monday

Please help me

Thanks in advance

**Comment by saifmattias** [comment]
I am also getting this problem, any solution for this problem? Thanks?

**Comment by tnghia944** [comment]
hi @jaiminp why did you close issue ?

**Comment by jaiminp-nimblechapps** [comment]
Because i have got the solution

**Comment by yugin21** [comment]
hi @jaiminp-nimblechapps can you share the solution please?

**Comment by jaiminp-nimblechapps** [comment]
Please check this stackoverflow link
 

https://stackoverflow.com/questions/64609833/react-native-calendars-moved-1-day-forward/64763243#64763243

**Comment by yugin21** [comment]
thank you! @jaiminp-nimblechapps

**Comment by gonca-gul** [comment]
You don't need to intervene in the package directly. Make sure Sunday is at the top of the list of days you provide and firstDay={1}.
