### ISSUE TITLE
Date header displayed is incorrect and arrangement of date in days is incorrect.

### ISSUE THREAD

**Issue by fctmolina1135** [wix/react-native-calendars#1012]
## Description
The problem is that I passed 2020-01-01 as the current date of calendar. But the calendar is displaying December 2019.

## Expected Behaviour

The calendar should show the correct Date header and the Arrangement of date in days columns should be correct

## Observed Behaviour

After passing `current={'2020-01-01'}` to Calendar. The calendar displayed is for December 2019.

I am getting this
![Screen Shot 2019-12-19 at 12 06 27 PM](https://user-images.githubusercontent.com/22470020/71144391-dc7f0600-2258-11ea-98d9-7f1003d79f2c.png)

When the correct calendar arrangement should be this
![Screen Shot 2019-12-19 at 12 06 38 PM](https://user-images.githubusercontent.com/22470020/71144404-e6086e00-2258-11ea-946b-4b22c2b9d28d.png)

## Environment

* react-native-calendars@1.214.0
* react-native@0.59.10 

Also specify:

1. Phone/emulator/simulator & version: iPhone 8 simulator and iPad Air(3rd Generation) Simulator

**Comment by Inbal-Tish** [comment]
@fctmolina1135 Hi. I can't reproduce the issue. Is it related to an iOS version?

**Comment by fctmolina1135** [comment]
@Inbal-Tish It happened when the current date was Dec 19, 2019 and I was trying to display the calendar for January 2020

**Comment by Inbal-Tish** [comment]
@fctmolina1135 Does it happens still? It didn't happen to me...
