### ISSUE TITLE
Calendar doesn't render

### ISSUE THREAD

**Issue by juanapp** [wix/react-native-calendars#1013]
Hi all,

I'm using this awesome calendar for React-Native but I'm having an issue that it's pretty annoying. The calendar doesn't render at all unless I scroll it or expand it(I start it with the minimized view). 

I tried all kind of solutions with timeouts and so like proposed in other issues, but it's just not working.
Any tip?

**Comment by bart-kneepkens** [comment]
+1

**Comment by Inbal-Tish** [comment]
@juanapp Hi. If this is a bug report please follow the instructions [here](https://github.com/wix/react-native-calendars/blob/master/ISSUE_TEMPLATE.md) so we can investigate.

**Comment by rdewolff** [comment]
I have the same issue
