### ISSUE TITLE
Past months empty on CalendarList

### ISSUE THREAD

**Issue by QQizi** [wix/react-native-calendars#1017]
## Description

Past months empty on `CalendarList` horizontal & vertical

## Observed Behavior

No error message whatsoever

## Environment
react-native-calendars@1.217.0
react-native@0.59.10 

[calendar.mov.zip](https://github.com/wix/react-native-calendars/files/3995445/calendar.mov.zip)

**Comment by Inbal-Tish** [comment]
@QQizi Hi. I need you to elaborate. please follow the instructions [here](https://github.com/wix/react-native-calendars/blob/master/ISSUE_TEMPLATE.md) so we can investigate.

**Comment by guanyuan** [comment]
In my case, android is ok.
But iphone8 has the same issue.
