### ISSUE TITLE
when i use <Calendar /> ,i set the style ,but the style "height" does not work

### ISSUE THREAD

**Issue by Jiujiale** [wix/react-native-calendars#102]
<Calendar
                    minDate={'1900-01-01'}
                    maxDate={'2199-12-30'}
                    theme={{
                        calendarBackground: 'white',
                        textSectionTitleColor: gColors.primary,
                        selectedDayBackgroundColor: gColors.primary,
                        selectedDayTextColor: 'white',
                        todayTextColor: 'red',
                        dayTextColor: '#2d4150',
                        textDisabledColor: '#d9e1e8',
                        dotColor: '#00adf5',
                        selectedDotColor: 'white',
                        arrowColor: gColors.primary,
                        monthTextColor: gColors.primary,
                        textDayFontSize: gSizes.text_normal,
                        textMonthFontSize: gSizes.text_normal,
                        textDayHeaderFontSize: gSizes.text_normal
                    }}
                    onDayPress={(day) => {
                        console.log(day);
                    }}
                    monthFormat={'MMMM'}
                    onMonthChange={(month) => {console.log('month changed', month)}}
                    hideArrows={false}
                    hideExtraDays={false}
                    disableMonthChange={false}
                    firstDay={7}
                    displayLoadingIndicator={false}
                    pastScrollRange={50}
                    futureScrollRange={50}
                    scrollEnabled={false}
                    style={{
        marginTop: 40,
        height: 350,
        width: gSizes.screen_width,
        borderWidth: 1,
        borderColor: gSizes.page_gray,}}
                    markedDates={this.state.selectedDay}
                />

![image](https://user-images.githubusercontent.com/15116421/28259328-58292c1e-6b08-11e7-8c3d-4fc33ee0681a.png)

any help I would appreciate

**Comment by Jiujiale** [comment]
<ScrollView style={styles.container}
                scrollEnabled={false}>
                    <Calendar
                        onDayPress={this.onDayPress}
                        style={styles.calendar}
                        hideExtraDays
                        markedDates={{[this.state.selected]: {selected: true}}}
                    />
                </ScrollView>

it work . but why  <View style={styles.container}
                scrollEnabled={false}>
                    <Calendar
                        onDayPress={this.onDayPress}
                        style={styles.calendar}
                        hideExtraDays
                        markedDates={{[this.state.selected]: {selected: true}}}
                    />
                </View> 
does not work ???

**Comment by marcelogdeandrade** [comment]
Did you solve this problem?

**Comment by austincline09** [comment]
Putting my calendar within a ScrollView instead of a View fixed my calendar height/flex issue. Not sure why but I'm assuming they're related

**Comment by pencilcheck** [comment]
@austincline09 how did you do it? I put it under a scrollview and it doesn't show up at all.
