### ISSUE TITLE
Range of days - only two selection

### ISSUE THREAD

**Issue by estevanpedro** [wix/react-native-calendars#1022]
I am trying to create a range of days with the a start day and an end day variable, but i can't find a wiki or any other info explaining how to use this calendar.

Here a example how i want to do: 

![calendar](https://user-images.githubusercontent.com/34717111/71771970-fa6b8c80-2f21-11ea-9921-8209e6bc953f.gif)

I'm using react-native 60.5, with hooks and typescript.

this is my code:
```
          <Calendar
            markingType={'period'}
            hideExtraDays={true}
            style={{
              height: 350,
              width: '86%',
            }}
            onDayPress={(day) => {
              setActive_id(null);
              setOpenStyle(false);
              onDateChange(day);
              setSelectedDay(day.dateString);
            }}
            markedDates={{ [selectedDay]: { selected: true, marked: true, selectedColor: '#148CDB' } }}
          />
```

**Comment by Inbal-Tish** [comment]
@estevanpedro Checkout the 'Period marking' section in the README.

**Comment by rukmanary** [comment]
Did you solved it @estevanpedro ? How?

**Comment by sebastianjung** [comment]
@Inbal-Tish 
There is no perio marking example inside the readme, right?

Any other sources on how to accomplish such behaviour?
