### ISSUE TITLE
fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync

### ISSUE THREAD

**Issue by tigpalmas** [wix/react-native-calendars#1025]
I tried to add this lib in my expo project but through me this error: fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync.  But my App.js have the method : 

_loadResourcesAsync = async () => {
        return Promise.all([
            Asset.loadAsync([
                require('./assets/images/no_image.png'),
                require('./assets/images/splash.png'),
                require('./assets/images/logo.png'),

            ]),
            Font.loadAsync({
                // This is the font that we are using for our tab bar
                ...Ionicons.font,
                // We include SpaceMono because we use it in HomeScreen.js. Feel free
                // to remove this if you are not using it in your app
                'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf'),
                'nunito-bold': require('./assets/fonts/Nunito-ExtraBold.ttf'),
                'nunito-regular': require('./assets/fonts/Nunito-Regular.ttf'),
            }),
        ]);

**Comment by esteban199** [comment]
sdk: 36.0.1

Hello people, the only way i fix it was: 

1. `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c`

2. I use async/await with componentDidMount() to wait until the font is loaded, like the expo doc https://docs.expo.io/versions/latest/guides/using-custom-fonts/: 

```
componentDidMount = async () => {
    await Font.loadAsync({
      'neohellenic-regular': require('../../assets/fonts/GFSNeohellenic-Regular.ttf'),
    });
    this.setState({ loading: false })
  }
```

**Comment by MatiasEsp** [comment]
Tengo poca practica. Pero vi este link. Sirve?

https://blog.bam.tech/developer-news/add-a-custom-font-to-your-react-native-app
