### ISSUE TITLE
Add Line on under current day

### ISSUE THREAD

**Issue by Parthhyperlink** [wix/react-native-calendars#1026]
## Description

I want to add bottom line in the days header, for example today sunday then line shows below sunday, monday then line shows below sunday and so on... so how can i achieve this. 

![image](https://user-images.githubusercontent.com/21080990/71869536-6a536000-3138-11ea-9b32-faa7d2dd10ba.png)

Thanks in advance.

**Comment by Inbal-Tish** [comment]
@Parthhyperlink There is no actual way to achieve it. It's a feature request. You're welcome to submit a PR.
