### ISSUE TITLE
Show only first character of day of the week

### ISSUE THREAD

**Issue by chashmeetsingh** [wix/react-native-calendars#1027]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I am looking for a way to display only the first character of the week instead of the first three characters.

**Comment by azizhk** [comment]
You can override `dayNamesShort`

```js
import {LocaleConfig} from 'react-native-calendars';

LocaleConfig.locales[LocaleConfig.defaultLocale].dayNamesShort = ['S','M','T','W','T','F','S'];
```

Though I don't see how to do this specifically for individual calendars. If you have multiple calendars in your app or multiple date functions depending on xdate, it might cause an issue.

**Comment by chashmeetsingh** [comment]
Yea, I had this in mind but was wondering if there was a better way or override you achieve this. 
Thanks btw.

**Comment by imamabdulazis** [comment]
Why is an issue closed? since I was facing the same issue.
When I try to update with a single letter showing this error

<img width=240 src="https://user-images.githubusercontent.com/39134128/224888254-6d69a190-e126-4ad2-8c42-f479771d7267.png"/>
