### ISSUE TITLE
Scrolling & UI Issue in Expandable Calendar vertically and Agenda List

### ISSUE THREAD

**Issue by pragyawebvillee** [wix/react-native-calendars#1029]
## Description
When i am using Expandable calendar vertically, there is glitch in scrolling and when the calendar list is opened, days are overlapping. Attaching image
![device-2020-01-09-132244](https://user-images.githubusercontent.com/40159461/72050118-69f8c780-32e6-11ea-8bd9-ebced81dadfd.png)

Check the behaviour of days.

Also when i drag the knob it open the calendar in full screen and hiding tabs and Header as well.
And some days of feb month are cutting from below. (This is the SS when i first drag the knob )
![device-2020-01-09-132417](https://user-images.githubusercontent.com/40159461/72050311-d5429980-32e6-11ea-8e0d-a7409f3968cf.png)

Now, when i scroll to check other days of any month (Feb in this condition), it scrolls full feb month and shows me march month view only. Check Screenshot. (in this SS feb month is not visible after scroll.)
![device-2020-01-09-132454](https://user-images.githubusercontent.com/40159461/72050492-4c782d80-32e7-11ea-93b1-ce854de66fa8.png)

## Environment
Android
Devices : 
1. MI Y2, Pie
2. Moto G, Nougat

## Reproducible Demo
This issue exist in your demo as well.

Also, is there any way to change the Agenda's Section Title. I want to add image in this section. Please help me to achieve this.
![Screenshot](https://user-images.githubusercontent.com/40159461/72051074-87c72c00-32e8-11ea-82d3-7d0fbcf4fac3.png)

Thanks! in advance

**Comment by Inbal-Tish** [comment]
@pragyawebvillee Is the duplication you refer to is due to the header being animated up? If so this is not a bug.

**Comment by pragyawebvillee** [comment]
@Inbal-Tish No, it occurs when i am dragging the knob down to scroll calendar. Check Screenshot

![image](https://user-images.githubusercontent.com/40159461/73171740-8048b500-4127-11ea-82fa-bcf4c6a3efc5.png)

**Comment by Inbal-Tish** [comment]
@pragyawebvillee Can you please add a video, I need to see the flow
