### ISSUE TITLE
Can we show only years in calendar along with existing feature where mode = year

### ISSUE THREAD

**Issue by mitulshah96** [wix/react-native-calendars#1030]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request
Able to select only year 
## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior
List of year should be visible and maxyear and min year need to displayed.

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by Inbal-Tish** [comment]
@mitulshah96 Hi. Sorry, I don't understand your request. Please elaborate and add some screenshots if possible

**Comment by mitulshah96** [comment]
I Need a calendar which displays only year. Where the component take a prod of type mode and display the calendar basedn on that. I am attaching the screenshot for the same. @Inbal-Tish  

<img width="420" alt="Screenshot 2020-01-24 at 12 03 32 PM" src="https://user-images.githubusercontent.com/29948589/73049149-9cd3bb80-3ea1-11ea-847a-6cebee9b89b2.png">

**Comment by Inbal-Tish** [comment]
@mitulshah96 Hi. I don't see how this view can serve other users and I don't see much "calendar" attributes to it. I think it is a component you can easily implement for yourself. Thank you though!
