### ISSUE TITLE
Calendar Agenda wrong position

### ISSUE THREAD

**Issue by ilya-raevskiy** [wix/react-native-calendars#1031]
<img width="335" alt="Снимок экрана 2020-01-10 в 14 31 16" src="https://user-images.githubusercontent.com/1379392/72142357-4d2bc500-33b6-11ea-9adf-787c3d676e52.png">
<img width="335" alt="Снимок экрана 2020-01-10 в 14 31 29" src="https://user-images.githubusercontent.com/1379392/72142363-50bf4c00-33b6-11ea-942a-07f11d34cab0.png">

When open a screen with a calendar, sometimes the position of the selected date does not correctly stand.

**Comment by StanislavSoftermii** [comment]
After some research I figured out that SafeAreaView caused the problem. It fired onLayout event where it was unnecessary, so I just removed one and it works well now. (in my case react-navigation handles safe area automatically)

If that does not help - try to look in src/agenda/index.js, there is calendarOffset function, I added my own offset prop there to fix same problem on iPhone 8 plus.

**Comment by Inbal-Tish** [comment]
@ilya-raevskiy Hi. If this is a bug report please add the following so we can investigate: 
Description
Expected Behavior
Observed Behavior
Environment
Platform, Device, and OS
Steps to reproduce

**Comment by teamhide** [comment]
Is there any fix version here?

**Comment by moonlight96** [comment]
> 经过研究，我发现是SafeAreaView引起了问题。它在不需要的情况下触发了onLayout事件，因此我刚刚删除了一个事件，现在效果很好。（在我的情况下，反应导航会自动处理安全区域）
> 
> 如果那没有帮助-尝试查看src / agenda / index.js，有calendarOffset函数，我在那里添加了自己的偏移量道具，以解决iPhone 8 plus上的相同问题。



> After some research I figured out that SafeAreaView caused the problem. It fired onLayout event where it was unnecessary, so I just removed one and it works well now. (in my case react-navigation handles safe area automatically)
> 
> If that does not help - try to look in src/agenda/index.js, there is calendarOffset function, I added my own offset prop there to fix same problem on iPhone 8 plus.


Hello,Could you show me your code about this problem?

**Comment by devctgp1002** [comment]
Hi @moonlight96  
I'm getting the same issue with you now. Can you please share the code patch for it?
