### ISSUE TITLE
Edit Agenda List

### ISSUE THREAD

**Issue by uendar** [wix/react-native-calendars#1032]
How can we edit the list of agenda items. For example in case of day with items text shown and other days below,  we show only the selected day  items based on hours  ? 
![20200110_115503](https://user-images.githubusercontent.com/13899301/72148050-2d89a200-33a0-11ea-8347-8a0901017757.png)

**Comment by erickBMO2017** [comment]
hello I would also like to have an answer on this point

**Comment by aik117** [comment]
+1 for the question however I need to remove the day and date on the left so that the item takes full width of the screen.

**Comment by Inbal-Tish** [comment]
@uendar You want to see only the selected day items in the agenda list? If so, it is not supported at the moment, but there are PRs for this feature. 
In the meantime, you can control the items you send the agenda through onDayPress event.

**Comment by merko30** [comment]
You can comment out `this.renderDate(date, reservation)` in reservation component. I'm not only sure whether it's allowed to do that, it's just temporarily.

**Comment by soumenmt** [comment]
i am trying to edit/delete agenda items but no success calendar view is not refreshing. Please find my expo link below..
https://snack.expo.dev/@soumenmt/restless-edamame
