### ISSUE TITLE
Agenda object not working properly on expo web - but works in Android

### ISSUE THREAD

**Issue by ghost** [wix/react-native-calendars#1034]
[18.218.90.101-1579173959588.log](https://github.com/wix/react-native-calendars/files/4070917/18.218.90.101-1579173959588.log)
## Description

I have implemented correctly the Agenda object according to the example provided. Tested it, and it works wonderfully on Android, using expo. However, when I enable the web (hit "w" key) version, it has problems. It does not present any error message, but it shows the headers of the Agenda (the week days) frozen. It does not let me choose which day I want to show.

The only specific thing I am using, which I think shouldn't impact on anything, is the React-Native-Paper UI.

This is such a great feature that I would like to use it both in Android and on the Web versions of my product.

## Expected Behavior

On the web version, the days should be clickable, exactly like in the Android version.

## Observed Behavior

The header dates are not clickable. They remain kind of "grayed out" and do not interact if you click them.

```
Apparently these are the faulty messages on the console:

PanGestureHandler is not yet supported on web.

bundle.js:101161 Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`. More info: https://github.com/facebook/react-native/issues/11094#issuecomment-263240420


WebSocket connection to 'ws://18.218.90.101:19006/sockjs-node/075/tpu5dsu2/websocket' failed: Error during WebSocket handshake: Unexpected response code: 403
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

/home/ubuntu/environment
└── react-native-calendars@1.220.0 
/home/ubuntu/environment
└── react-native@0.59.8 

Runing on expo web version (hit "w" key)

 Expo CLI 3.11.5 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.5

## Reproducible Demo

The example Agenda App can be used.

Updated error log, with the error messages:
![Capturar](https://user-images.githubusercontent.com/13082760/72256883-0e318580-35e9-11ea-97ff-72019a82ba65.PNG)

**Comment by ArshAgarwal28** [comment]
any fix????
