### ISSUE TITLE
Does "shouldComponentUpdate" work in custom dayComponent?

### ISSUE THREAD

**Issue by nikbelikov** [wix/react-native-calendars#1045]
Hi!

I'm trying to use shouldComponentUpdate method in custom dayComponent but it does not work.

p.s. the State in the CalendarList above changed and it starts updating ALL my day components but I don't want that. I want to decide what day needed to be updated and which one is not.

https://github.com/wix/react-native-calendars#overriding-day-component

> Don't forget to implement shouldComponentUpdate() for your custom day component to make the calendar perform better

**Comment by Inbal-Tish** [comment]
Pass 'state' only to the day component you want to update. It's your component so you control to which you pass what.
Regarding the 'shouldComponentUpdate' not working, I need more information. Please open a full bug report with all the required details by using the issue template [https://github.com/wix/react-native-calendars/blob/master/ISSUE_TEMPLATE.md](url)

**Comment by GR34SE** [comment]
I've encountered same problem. While passing custom day component wrapped with React.memo, I had performance issues

**Comment by davidbiller** [comment]
try this:   
dayComponent={Day} 

instead of 

dayComponent={({...})=><Day ...
