### ISSUE TITLE
Background Image for Agenda

### ISSUE THREAD

**Issue by chashmeetsingh** [wix/react-native-calendars#1046]
## Description

I was hoping to know if it's possible to add a background image to the agenda, as in the view where the dates are listed.

**Comment by fairhat** [comment]
simplified:
`
<ImageBackground source={require("...")}>
    <Agenda style={{ backgroundColor: "rgba(0,0,0,0)" }} />
</ImageBackground>
`

should work

**Comment by 99Jannis99** [comment]
No that did not solve the problem

**Comment by 99Jannis99** [comment]
Does anyone have a working solution
