### ISSUE TITLE
Date order change

### ISSUE THREAD

**Issue by sommeshEwall** [wix/react-native-calendars#1047]
I'm trying to change the calendar view start day. By default, it's starting with **Sunday**. But I would like to start the day from **MONDAY** instead of **SUNDAY**.
On detailed check I have found that changing the `function weekDayNames(firstDayOfWeek = 0) {}`
to 
`function weekDayNames(firstDayOfWeek = 1) {}` in [dateutils.js](https://github.com/wix/react-native-calendars/blob/cf154e511550a7f5bd07f20dc0cd854ab0fb676f/src/dateutils.js#L43) file made the magic.
Now my calendar is starting from **MONDAY** instead of **SUNDAY**.
But I could not change the date order.
Kindly help me in changing the date order.

Correct date for March - Monday (2-3-2020) : https://prnt.sc/qtg0h1
After changing the WeekDayNames function I'm getting the below output
Screenshot: https://prnt.sc/qtg2ud

Any help would be helpful. Thanks in advance.

**Comment by lawrence-pun** [comment]
Just simply change the `function page(xd, firstDayOfWeek) {` to `function page(xd, firstDayOfWeek = 1) {` which is the next function of weekDayNames on same file.

**Comment by Inbal-Tish** [comment]
Just pass Calendar component `firstDay={1}`

**Comment by kumaramit32788** [comment]
Just add this line 
`<Calendar
 firstDay={1} // this line
/>`

**Comment by amel-selmane** [comment]
Thank you, It also works for Agenda :)

**Comment by cwtaras** [comment]
I've came across with the same problem in Agenda component. I've added firstDay=1, and didn't change the order of othe short day names. But now, date of days are incorrect. Today is 1st of September Thursday but It looks like Friday in week view. How can i solve this?

**Comment by amel-selmane** [comment]
Hi @cwtaras, to solve this issue (and mine, thanks for the information), you can use firstDay={7} and it'll be okay.

**Comment by cwtaras** [comment]
Hi @amel-selmane thanks for the answer. I want the week to start from Monday. firstDay={7} makes it start from Sunday again.

**Comment by amel-selmane** [comment]
Maybe you can try to use another numbers and see if you can solve it.

**Comment by Inbal-Tish** [comment]
This is the default:
![Agenda-firstDay-default](https://user-images.githubusercontent.com/33805983/190983393-0e4c1fd2-b3f9-450a-8587-e0c428028232.png)

This is when passing `firstDay={1}`:
![Agenda-firstDay-1](https://user-images.githubusercontent.com/33805983/190983510-3b3ab8af-6590-4de3-8637-68b675868c25.png)

I don't see an issue with the UI or the data. 
Can someone add a code snippet for the Agenda component where the bug reproduces? Video can be great as well.
