### ISSUE TITLE
CalendarProvider with ExpandableCalendar

### ISSUE THREAD

**Issue by dagan-arbox** [wix/react-native-calendars#1049]
Using CalendarProvider with ExpandableCalendar I have a few problems

1. ExpandableCalendar onDayPress is not returning a function - so I cant act on that change.
2. on CalendarProvider onDateChanged={this.onDayPress} works, but it acts on any date change, meaning when moving between weeks, api calls are made.
3.markedDates={{...calendarEvents}} refuse to render! even if I use const calendarEvents = JSON.parse(JSON.stringify(this.state.markedDates)); 
4. on week change, always there is day selected marked on bar,but why..no click event.

Code example : ` <CalendarProvider
                                date={current}
                                onDateChanged={this.onDayPress}
                                onMonthChange={this.monthChanged}
                                key={current}
                            >
                                <ExpandableCalendar
                                    firstDay={1}
                                    current={current}
                                    horizontal={true}
                                    markedDates={{...calendarEvents}}
                                    disablePan={true} //we need this
                                    disableWeekScroll={false}
                                />
                            </CalendarProvider>`

**Comment by Inbal-Tish** [comment]
1. Use CalendarProvider's onDateChange() prop that returns the date and the updateSource (updateSource is one of 'calendarInit', 'todayPress', 'listDrag', 'dayPress', 'pageScroll', 'weekScroll', 'propUpdate').
2. UpdateSource 'dayPress' is the one you need for day press callback.
3. 'markedDates' is an object, an example is found in the README file. I can't tell from your code the structure of your json object, so I can't know what is not working for you.

**Comment by dagan-arbox** [comment]
UpdateSource is perfect! thank you.

**Comment by kousiclattala** [comment]
How to set UpdateSource on OnDateChange prop in CalendarProvider, please show via example

**Comment by kousiclattala** [comment]
> How to set UpdateSource on OnDateChange prop in CalendarProvider, please show via example

@Inbal-Tish

**Comment by Inbal-Tish** [comment]
@kousiclattala You don't set the UpdateSource, you get it in order to know how to react to updates from different sources.
