### ISSUE TITLE
Different calendar sizes on Agenda

### ISSUE THREAD

**Issue by matwii** [wix/react-native-calendars#105]
My Agenda is working perfectly on my Android phone, but on my iPad the calendar view over the agenda is really big. Is there any way I can shrink this? I'm using flexbox so I don't understand how it gets bigger than my flexbox. Here are two images, one from the android phone where it works perfectly and one from the ipad where the calendar view of the weeks are to big. I want to show one week at the time on both phone and ipad.
![screenshot_20170719-162604](https://user-images.githubusercontent.com/8501876/28372322-afd90ec8-6c9f-11e7-8494-55a333139464.png)
![img_0001](https://user-images.githubusercontent.com/8501876/28372330-b304c59c-6c9f-11e7-9fb1-1d8705f21600.PNG)

**Comment by tautvilas** [comment]
looks like it's related to #97 bug @overengineered

**Comment by overengineered** [comment]
Here is a simple problem, will fix it tomorrow. #97 I don't understand, probably will remain when this is fixed.

**Comment by matwii** [comment]
@overengineered You know how to fix this?

**Comment by overengineered** [comment]
Yes, `overflow:'hidden'` is missing in style in one of the subviews in Agenda. Adding it to Agenda style could be a workaround.

**Comment by matwii** [comment]
@overengineered Yeah adding overflow: 'hidden' in the style object for Agenda worked perfectly. I think that either you need to add it in the documentation or fix it :)

**Comment by tautvilas** [comment]
@matwii your PR with fix also welcome :)
