### ISSUE TITLE
I need to add padding bottom for Agenda, Is it have container style ?

### ISSUE THREAD

**Issue by zoom2009** [wix/react-native-calendars#1050]
At bottom right corner => My `edit`, `remove` button is behind `Add button` 
I need to add padding for agenda container (whole of agenda item) for scrollable 

![image](https://user-images.githubusercontent.com/33366155/73485471-b612c580-43d5-11ea-9b36-e6df5e5fca20.png)

thank you

**Comment by gigigimay** [comment]
I'm having the same issue. :(

**Comment by Nemferno** [comment]
Try this: to access the bottom container of the agenda, you will need to do the following appendage to your theme property for `Agenda`.

`theme={{ 'stylesheet.agenda.list': { container: { paddingBottom: 10 } } }}`

`stylesheet.agenda.list` gives you access to the reservation list styling in the `Agenda` component.

**Comment by rabiaah** [comment]
Still have the same issue in the new version.
Can you please share a working example, the previous one damaging the whole design with the container one.

**Comment by deema304** [comment]
Also I noticed that its necessary to add ` flexDirection: "row"` because we override container styles.

`'stylesheet.agenda.list': {
            container:
            {
                flexDirection: "row",
                paddingBottom: 12
            }
        }`
