### ISSUE TITLE
Invariant Violation: when using sample example files

### ISSUE THREAD

**Issue by jainmnsh** [wix/react-native-calendars#1052]
Hello, I am trying to use example files posted in repo - so I created a new project using "react-native init "

1. copied screens and img folder into my project
2. update my index.js = import App from './app'
3. update my app.js

import {Navigation} from 'react-native-navigation';
import {registerScreens} from './screens';

  registerScreens();

  Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
      root: {
        stack: {
          children: [
            {
              component: {
                name: 'Menu',
                options: {
                  topBar: {
                    title: {
                      text: 'Wix RN Calendars'
                    }
                  }
                }
              }
            }
          ]
        }
      }
    });
  });

## Description

when I run the application then i get below error

Invariant Violation: "jssevent" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

runApplication
    AppRegistry.js:189:6
callFunctionReturnFlushedQueue
    [native code]:0

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.259.0 
* `npm ls react-native`: 0.61.5

Also specify:

1. Phone/emulator/simulator & version: IOS Simulator 11

## Reproducible Demo

getting above error.

**Comment by Inbal-Tish** [comment]
It looks like a question to 'react-native-navigation' guys.
