### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by jordangrant** [wix/react-native-calendars#1053]
<img width="422" alt="Screen Shot 2020-02-03 at 10 13 56 AM" src="https://user-images.githubusercontent.com/7986493/73664964-4ff49f80-466e-11ea-8a1a-5a7830caeffc.png">

**Comment by Inbal-Tish** [comment]
There is not enough information here for me to help you (xcode version, simulator type and version etc.). Did you `npm install`? `cd ios && pod install`?
