### ISSUE TITLE
pull-to-refresh in Agenda

### ISSUE THREAD

**Issue by fontanamichele** [wix/react-native-calendars#1054]
does anyone know how to make pull-to-refresh work?

` onRefresh={(day)=>
        this.setState({ refreshing: true },
         function() { console.log("refreshing...");
          this.setState({items:{}});
          this.loadItems.bind(this);
         this.setState({ refreshing: false }) })
            }`
I tried to reset the value of items and to call the loadItems function in this way and the agenda updates, but does not return anything.

now i tried this way but the list is not updated: here is the code:

` export default class ProfileScreen extends React.Component {  
    constructor(props) {
      var currentDate = new Date().getDate(); //Current Date
        super(props);
        this.state = {
        items:{}
          }
        };
      
    

      componentDidMount() {
       

        return fetch('url')
      .then((response) => response.json())
      .then((responseJson) => {
            
        this.setState({
        
          items: responseJson,
         
        }, function(){
          
        });

      })
      .catch((error) =>{
        console.error(error);
      });
  }
      

    loadItems(day) {
        setTimeout(() => {
          for (let i = -15; i < 85; i++) {
            const time = day.timestamp + i * 24 * 60 * 60 * 1000;
            const strTime = this.timeToString(time)
            if (!this.state.items[strTime]) {
              this.state.items[strTime] = [];
            }
          }
          console.log(this.state.items);
          const newItems = {};
          Object.keys(this.state.items).forEach(key => {newItems[key] = this.state.items[key];});
          this.setState({
            items: newItems
          });
        }, 1000);
        console.log(`Load Items for ${day.year}-${day.month}`);

      }
    
      renderItem(item) {
          if(item.name==''){
              return(
              <View style={[styles.noItem, {height: item.height,flexDirection:'row', justifyContent:'space-between'}]}>
                <View style={{width:'60%'}}>
                 <Text style={[styles.itemTitle]}>nessun contenuto</Text>
                </View>
                <View style={{width:'35%'}}>
                  <TouchableOpacity style={styles.noItemButton}><Text style={styles.itemButtonText}>Aggiungi</Text></TouchableOpacity>
                </View>
             </View>
              )
          }
        return (
        <View style={[styles.item, {height: item.height,flexDirection:'row', justifyContent:'space-between'}]}>
             
           <View style={{width:'60%'}}>
           <Text style={[styles.itemTitle]}>{item.name}</Text>
           <Text style={[styles.itemDescription]}>{item.description}</Text>
           </View>
           <View style={{width:'35%'}}>
            <TouchableOpacity style={styles.itemButton}><Text style={styles.itemButtonText}>Modifica</Text></TouchableOpacity>
            </View>
        </View>
        );}
      
    
      renderEmptyDate() {
        return (
          <View style={[styles.empty]} />
        );
      }
    
      rowHasChanged(r1, r2) {
        return r1 !== r2;
      }
    
      timeToString(time) {
        const date = new Date(time);
        return date.toISOString().split('T')[0];
      }
     

  render() {  
    return (  
      <Agenda
      // The list of items that have to be displayed in agenda. If you want to render item as empty date
      // the value of date key has to be an empty array []. If there exists no value for date key it is
      // considered that the date in question is not yet loaded
      items={        this.state.items   }
      // Callback that gets called when items for a certain month should be loaded (month became visible)
      loadItemsForMonth={this.loadItems.bind(this)}
      // Callback that fires when the calendar is opened or closed
      onCalendarToggled={(calendarOpened) => {console.log(calendarOpened)}}
      // Callback that gets called on day press
      onDayPress={(day)=>{console.log('day pressed')}}
      // Callback that gets called when day changes while scrolling agenda list
      onDayChange={(day)=>{console.log('day changed')}}
      // Initially selected day
      selected={this.state.currentDate}
      // Max amount of months allowed to scroll to the past. Default = 50
      pastScrollRange={50}
      // Max amount of months allowed to scroll to the future. Default = 50
      futureScrollRange={50}
      // Specify how each item should be rendered in agenda
      renderItem={this.renderItem.bind(this)}
      // Specify how each date should be rendered. day can be undefined if the item is not first in that day.
      //renderDay={(day, item) => {return (<View><Text>{this.state.day}</Text></View>);}}
      // Specify how empty date content with no items should be rendered
      renderEmptyDate={this.renderEmptyDate.bind(this)}
      // Specify how agenda knob should look like
    renderKnob={() => {return(<View style={{backgroundColor:'black',width:60,height:5,borderRadius:20,marginTop:8,opacity:.1}}></View>);}}
      // Specify what should be rendered instead of ActivityIndicator
     // renderEmptyData = {() => {return (<View><Text>nessun upload sul giorno selezionato</Text></View>);}}
      // Specify your item comparison function for increased performance
      rowHasChanged={this.rowHasChanged.bind(this)}
      // By default, agenda dates are marked if they have at least one item, but you can override this if needed
      //markedDates={{  }}
      // If disabledByDefault={true} dates flagged as not disabled will be enabled. Default = false
      disabledByDefault={true}
      // If provided, a standard RefreshControl will be added for "Pull to Refresh" functionality. Make sure to also set the refreshing prop correctly.
      onRefresh={() => {
        this.setState({ refreshing: true });
        setTimeout(() => { this.setState({ refreshing: false }) }, 5000);
     }}
      // Set this true while waiting for new data from a refresh
      refreshing={this.state.refreshing}
      // Add a custom RefreshControl component, used to provide pull-to-refresh functionality for the ScrollView.
      //refreshControl={null}
      // Agenda theme
      theme={{
        ...calendarTheme,
      }}
      // Agenda container style
      style={{}}
    />
    );  
  }  
}  `

**Comment by Nemferno** [comment]
It appears to me that your code isn't executing your refresh function.

`onRefresh={
    (day) => this.setState({ refreshing: true },
    // use anonymous functions, otherwise the **this** keyword will bind to this
    // function, not the enclosing component. To avoid confusion :)
    () => {
        this.setState({ items: {} });
        this.loadItems(day); // no .bind(this) invocation
        this.setState({ refreshing: false })
    })
}`

Try this for your first comment. For your second comment, for onRefresh, you never called your refresh function, loadItems. All the refresh is doing is flagging the refreshing state, and after 5 seconds, turning off the flag; thus, your list is not updated.

Let me know if it works for you 👍

**Comment by fontanamichele** [comment]
thanks for the quick answer @Nemferno, I tried your solution and it seems to work, the only problem is that now it gives me the error "TypeError:undefined is not an object (evaluating 'day.year')", 
as if the 'day' data is not in the correct format i think. Can you help me on this?

**Comment by Nemferno** [comment]
It means that `day === undefined`. I found out why. `onRefresh` does not include a `day` argument (my bad); hence, the object is undefined. You will need to find a way to store the day you are currently on. I suggest creating a state variable: `currentDay` so that whenever you refresh your agenda, you can use that to replace it. The new code should be something like:

> // Assuming you have "this.state.currentDay"
> onRefresh={ () => this.setState({ refreshing: true },
> () => {
> this.setState({ items: {} });
> this.loadItems(this.state.currentDay);
> this.setState({ refreshing: false })
> }) }

**Comment by fontanamichele** [comment]
@Nemferno sorry for the delay in the response.
I begin by thanking you in advance for the time you are dedicating to me and my project;
I tried your solution and it seems to work! Data are refreshed but unfortunately with another small problem: the function does not recognize the date I pass it! 
I first tried passing a react native 'date' variable:
` var currentDate =new Date().getDate();
.
.
.
this.loadItems(currentDate); `
and gave me the error: 'error: invalid date'
then I tried to create a 'data' variable by building it myself:
` var date = new Date().getDay(); //Current Date
    var month = new Date().getMonth() + 1; //Current Month
    var year = new Date().getFullYear(); //Current Year
    var currentDate =   year + '-' + month + '-' + date ;
.
.
.
this.loadItems(currentDate); `

and gave me the same error.

the strange thing is that in my function 'loadItems' I print this log:
` console.log(`Load Items for ${day.year}-${day.month}`);`
and when I refresh what it prints is "Load Items for undefined-undefined".
would you know what is the right syntax to pass in the variable 'currentDate'?
