### ISSUE TITLE
is there a way to pass testId to the default dayComponent in Calendar.

### ISSUE THREAD

**Issue by Adnan48** [wix/react-native-calendars#1056]
Hello guys;
I am not that familiar with this library, I want to have a test of CalendarList item but found that it doesn't expose any 'testId' props. How can I have a detox test around it?

**Comment by chenei** [comment]
Hi,
We currently not providing an option to pass _testID_.
You can take a look here to see the `testID` structure:
https://github.com/wix/react-native-calendars/blob/master/src/calendar/index.js#L186

e.g: `native.calendar.SELECT_DATE_SLOT-2020-07-04`
