### ISSUE TITLE
Change year color and set ' apostrophe before year

### ISSUE THREAD

**Issue by adriatikgashi** [wix/react-native-calendars#1057]
## Description

I want to set 'apostrophe' before the year for example for " Mar 20' " I want to set " Mar '20 "

iOS/Android

## Reproducible Demo

Just scroll on the vertical agenda!

**Comment by ko100v** [comment]
I'm having the same problem. 
![ddf3e913-a11d-40c6-b982-bf6934d725f7](https://user-images.githubusercontent.com/7877844/74340276-4b3a9480-4dae-11ea-9039-12387541e395.png)
