### ISSUE TITLE
onScrollDone callback?

### ISSUE THREAD

**Issue by guanw** [wix/react-native-calendars#1061]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Is there a onScrollDone callback which gets fired when user finishes scrolling? I need to fire some action when detecting user has just finished scrolling with <Agenda> component. Or is there anyway around to detect this kind of event?

## Update:
BTW, are users encouraged to use ref on `<Agenda />` and directly call out its method like `chooseDay`, I want to use it for programmatically firing ui changes but not sure if this is the best way.

**Comment by Inbal-Tish** [comment]
There is no 'onScrollDone' callback.
You are welcome to use Agenda's methods if that works for you, the same as using any RN component's methods.

**Comment by HenryGorner** [comment]
@guanw  Added a pull request for capturing the scroll events of the agenda  #list  #1063

**Comment by Inbal-Tish** [comment]
@guanw Added on version 1.262.0. Thank you @HenryGorner !
