### ISSUE TITLE
marked dates on init

### ISSUE THREAD

**Issue by dagan-arbox** [wix/react-native-calendars#1062]
I'm using Calendar Provider And ExpandableCalendar.
Description: 

on component init, markedDates not showing up, on week change or any date change, markedDates showing up.
Code Example:
` <CalendarProvider
                                date={current}
                                onDateChanged={this.onDayPress}
                                onMonthChange={this.monthChanged}
                                key={current}
                            >
                                <ExpandableCalendar
                                    current={current}
                                    horizontal={true}
                                    markedDates={{...this.state.markedDates}}
                                    disablePan={true} //we need this
                                    disableWeekScroll={false}
                                />
                            </CalendarProvider>`

```
 getMarkedDates = () => {
        const marked = {};
        this.props.weekly.forEach(item => {
            marked[item] = {marked: true, dotColor: Colors.green};
        });
        InteractionManager.runAfterInteractions(() => {
            this.setState({markedDates: JSON.parse(JSON.stringify(marked))})
        });
    };

```
getMarkedDates is triggered properly on componentDidUpdate.
as you can see JSON.parse(JSON.stringify(marked) and InteractionManager is involved aswell.

**Comment by Inbal-Tish** [comment]
componentDidUpdate() will be triggered only after update, mening you need to make sure your object is initialized in the init. Try setting your 'this.state.markedDates' in the constructor with your this.getMarkedDates()

**Comment by dagan-arbox** [comment]
Thank you, if someone tackles this issue, resolved by:
the only difference that previous init state was {} object and not the function getMakredDates
I didn't understand out why, but it is works great.

on constructor:
`constructor(props) {
        super(props);
        this.state = {
            markedDates: this.getMarkedDates(),
    }` 
on Calendar:
`  <ExpandableCalendar
                                    current={current}
                                    horizontal={true}
                                    markedDates={this.getMarkedDates()}
                                    disablePan={true} //we need this
                                    disableWeekScroll={false}
                                    renderArrow={this.renderArrow}
                                />`
getMarkedDates function: 
`  getMarkedDates = () => {
        const marked = {};
        this.props.weekly.forEach(item => {
            marked[item] = {marked: true, dotColor: Colors.green};
        });
        return JSON.parse(JSON.stringify(marked));
    };`

**Comment by Inbal-Tish** [comment]
The reason it works is that you need to pass the calendar component your 'markedDates' so it will make them on its init. If you pass an empty object it doesn't set anything. Only on component update you are setting the 'markedDates' so the calendar component receives them only then.
