### ISSUE TITLE
Anyway to not make Agenda week start from Sunday?

### ISSUE THREAD

**Issue by guanw** [wix/react-native-calendars#1064]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I'm trying to customize Agenda component and wonder if there's anyway to pass the start date for the week row in Agenda. Currently it always starts from Sunday. But in our case  we want it to be able to start on arbitrary day.

Example we have:
![image](https://user-images.githubusercontent.com/7311035/74771123-9ac00b00-525b-11ea-82e9-d9b825138eb8.png)

## Expected Behavior
The week row could start from any other day (e.g Monday, Tuesday, etc)

**Comment by shabnam701** [comment]
Try `firstDay`,  If firstDay=1 week starts from Monday. Note that dayNames and dayNamesShort should still start from Sunday. 

 `   firstDay: PropTypes.number`

**Comment by guanw** [comment]
@shabnam701 IC. I guess the readme is kind of outdated then. I will try that out. Thx.
