### ISSUE TITLE
Set disabled prop on TouchableOpacity for disabled days

### ISSUE THREAD

**Issue by antpuleo2586** [wix/react-native-calendars#1066]
## Description

This feature has been requested before and was actually merged, but there has been some regression, it seems, as the feature was then removed.

See: 
https://github.com/wix/react-native-calendars/commit/902938b077cda72b90fbac528ba3ee27404e7c9b#diff-cd9b288cf1005bb23ab789131c434607L94

## Expected Behavior

When I click on a disabled day, I expect no touch feedback. Furthermore, when I assert that the day should be disabled in my tests, I expect the `disabled` prop to be set on the `TouchableOpacity`.

i.e. set
```
disabled={marking.disableTouchEvent || isDisabled}
```
on the `TouchableOpacity`

## Observed Behavior

When you select a disabled day, there is touch feedback and when I select the day element in my tests i.e.
```
getByTestId(`native.calendar.SELECT_DATE_SLOT-${day}`)
```
they fail when trying to assert that the `disabled` prop is set.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.263.0
* `npm ls react-native`: 0.61.5

Also specify:

1. Phone/emulator/simulator & version:

iOS Simulator (11 Pro) iOS 13.3

**Comment by chenei** [comment]
Hi,
Please take a look at the following PR:
https://github.com/wix/react-native-calendars/pull/1161/files

You can now use `disableAllTouchEventsForDisabledDays`.
You can still override the behavior with `markedDates`. so for example, you can pass `disableTouchEvent: false` explicitly on `markedDates` to specific date and it will override `disableAllTouchEventsForDisabledDays`.
