### ISSUE TITLE
Setting Calendars ref break React Navigation v5

### ISSUE THREAD

**Issue by Kalcode** [wix/react-native-calendars#1071]
When setting a ref on the calendar React Navigation or React Navigation breaks the app.

```ts
<Calendar
      ref={ref => console.log('ref ', ref)} // <---- this causes the error
      dayComponent={Day as (dayProps: DayComponentProps) => JSX.Element}
      disableArrowLeft={disableLeftArrow}
      disableArrowRight={disableRightArrow}
      firstDay={0}
      hideArrows={false}
      hideDayNames={false}
      hideExtraDays={true}
      markedDates={markedDates}
      maxDate={maxDate}
      minDate={minDate}
      monthFormat="MMMM yyyy"
      onPressArrowLeft={updateArrows('subtract')}
      onPressArrowRight={updateArrows('add')}
      style={styles.container}
      theme={calendarTheme}
      onDayPress={day => {
        onChangeDate(day.dateString);
      }}
      renderArrow={direction => {
        const colorDisabled =
          (direction === 'left' && disableLeftArrow) ||
          (direction === 'right' && disableRightArrow);

        const color = colorDisabled ? colors.greyMedium : colors.primary;

        return (
          <View style={styles.arrow}>
            <Icon name={direction} size={scale(16)} color={color} />
          </View>
        );
      }}
    />
```

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

That i'd get a ref back for the Calendar component.

## Observed Behavior

![image](https://user-images.githubusercontent.com/13425721/75557472-afdc2d00-5a05-11ea-9e42-6177c342ee9a.png)

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error: Couldn't find a navigation connect. Have you wrapped your app with 'Navigation Container'?
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.263.0
* `npm ls react-native`: react-native@0.61.5

Also specify:

1. Mojave (OSX), 
2. xCode 11
3. iOS simulator - iphone 11

**Comment by chenei** [comment]
Hi,
It's not breaking my example app.
Can you please try to reinstall the library? We did some improvements these days.

We use in our example app `react-native-navigation` and everything is working fine.
