### ISSUE TITLE
Add bottom padding parameter to CalendarList

### ISSUE THREAD

**Issue by ryanmagoon** [wix/react-native-calendars#1076]
## Description

currently there's no way to expose the `contentContainerStyle` of the `FlatList` inside of `CalendarList` for modification. I propose either allowing a passthrough in the stylesheet called `contentContainer` that allows those modifications or a straight prop called `bottom` or `bottomPadding` to allow space at the bottom of the calendar after the last month. Happy to implement if you assign to me.

## Expected Behavior

Ability to add bottom padding to the content container of the FlatList for CalendarList

## Observed Behavior

no such ability.

**Comment by chenei** [comment]
Hi,
I personally prefer a more robust solution like `contentContainer`.

@ethanshar what do you think?

If you can implement it will be great.

**Comment by ethanshar** [comment]
@chenei 
100% `contentContainer` (:

**Comment by pfcodes** [comment]
Was this ever implemented? Need a way to add bottom padding to the calendar list

**Comment by ItsFlash10** [comment]
@Inbal-Tish can we have this passed to the CalendatList?? Its much needed.

**Comment by SulaimanAlbulaihy** [comment]
any news?
Was it implemented to calendar list ?

**Comment by ryanmagoon** [comment]
Resolved by #2523
