### ISSUE TITLE
Different calendars than Gregorian?

### ISSUE THREAD

**Issue by bbeckkk** [wix/react-native-calendars#1085]
Is there a way to show calendar dates other than gregorian? What does it take to display the calendar in Vikram Sambat, Hebrew, Persian calendar? Any help is appreciated.

Regards

**Comment by chenei** [comment]
Please check locale configuration:
https://github.com/wix/react-native-calendars#usage

You can also integrate i18.

**Comment by farzanm14** [comment]
Locale configuration only changes titles, I need to change the calendar system. Could you please recommend a proper choice? Or add this feature
