### ISSUE TITLE
Agenda performance: VirtualizedList: You have a large list that is slow to update

### ISSUE THREAD

**Issue by emflomed17** [wix/react-native-calendars#1088]
## Description
Hi, I'm trying to use the Agenda component. I took the example from the repo [Agenda Example](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js) in order to see how the Agenda works.

Thing that you have to know: 
1- I refactored the code a bit in order to use Functional Components instead Class Components.
2- The example creates the calendar items randomly. In my case I'm not doing this way, I created an object with a few items instead.

Agenda component is not working correctly

## Expected Behavior

If I click on a date that has items, it should display the list view panel of the selected day like the following gif example
![expected behavior](https://user-images.githubusercontent.com/25670760/76363505-c8dbbc80-62e8-11ea-84a9-ff24c428c046.gif)

## Observed Behavior

The problem is that when I click on a date, it takes a long time to display the list view panel or, sometimes, it doesn't even open the panel. 

I'm not getting any errors, only the following message in console:

```
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. Object {
  "contentLength": 36360,
  "dt": 9346,
  "prevDt": 967,
}
```

## Code
```
import React, { useState, useEffect } from "react";
import { View, TouchableOpacity, Alert, Text } from "react-native";
import { Agenda } from "react-native-calendars";
import styles from "./styles";
import { FloatingButton } from "../../common/atoms";
import { EventsIcon } from "../../../res";

const EventsScreen = () => {

  const [items, setItems] = useState({
    "2017-05-16": [{ name: "item 1 - any js object" }],
    "2017-05-23": [{ name: "item 2 - any js object", height: 80 }],
    "2017-05-24": [],
    "2017-05-25": [{ name: "item 3 - any js object" }, { name: "any js object" }]
  });

  const renderItem = item => (
    <TouchableOpacity
      style={[styles.item, { height: item.height }]}
      onPress={() => Alert.alert(item.name)}
    >
      <Text>{item.name}</Text>
    </TouchableOpacity>
  );

  const renderEmptyDate = () => {
    return (
      <View style={styles.emptyDate}>
        <Text>This is empty date!</Text>
      </View>
    );
  };

  const rowHasChanged = (r1, r2) => r1.name !== r2.name;

  return (
    <View style={styles.safeArea}>
      <Agenda
        items={items}
        selected="2017-05-16"
        renderItem={renderItem}
        renderEmptyDate={renderEmptyDate}
        rowHasChanged={rowHasChanged}
      />
    </View>
  );
};

export default EventsScreen;
```

## Environment
`"expo": "^36.0.1"`
`"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",`
`"react-native-calendars": "^1.264.0",`

**Comment by emmanuel-cbqa** [comment]
> ## Description
> Hi, I'm trying to use the Agenda component. I took the example from the repo [Agenda Example](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js) in order to see how the Agenda works.
> 
> Thing that you have to know:
> 1- I refactored the code a bit in order to use Functional Components instead Class Components.
> 2- The example creates the calendar items randomly. In my case I'm not doing this way, I created an object with a few items instead.
> 
> Agenda component is not working correctly
> 
> ## Expected Behavior
> If I click on a date that has items, it should display the list view panel of the selected day like the following gif example
> ![expected behavior](https://user-images.githubusercontent.com/25670760/76363505-c8dbbc80-62e8-11ea-84a9-ff24c428c046.gif)
> 
> ## Observed Behavior
> The problem is that when I click on a date, it takes a long time to display the list view panel or, sometimes, it doesn't even open the panel.
> 
> I'm not getting any errors, only the following message in console:
> 
> ```
> VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. Object {
>   "contentLength": 36360,
>   "dt": 9346,
>   "prevDt": 967,
> }
> ```
> 
> ## Code
> ```
> import React, { useState, useEffect } from "react";
> import { View, TouchableOpacity, Alert, Text } from "react-native";
> import { Agenda } from "react-native-calendars";
> import styles from "./styles";
> import { FloatingButton } from "../../common/atoms";
> import { EventsIcon } from "../../../res";
> 
> const EventsScreen = () => {
> 
>   const [items, setItems] = useState({
>     "2017-05-16": [{ name: "item 1 - any js object" }],
>     "2017-05-23": [{ name: "item 2 - any js object", height: 80 }],
>     "2017-05-24": [],
>     "2017-05-25": [{ name: "item 3 - any js object" }, { name: "any js object" }]
>   });
> 
>   const renderItem = item => (
>     <TouchableOpacity
>       style={[styles.item, { height: item.height }]}
>       onPress={() => Alert.alert(item.name)}
>     >
>       <Text>{item.name}</Text>
>     </TouchableOpacity>
>   );
> 
>   const renderEmptyDate = () => {
>     return (
>       <View style={styles.emptyDate}>
>         <Text>This is empty date!</Text>
>       </View>
>     );
>   };
> 
>   const rowHasChanged = (r1, r2) => r1.name !== r2.name;
> 
>   return (
>     <View style={styles.safeArea}>
>       <Agenda
>         items={items}
>         selected="2017-05-16"
>         renderItem={renderItem}
>         renderEmptyDate={renderEmptyDate}
>         rowHasChanged={rowHasChanged}
>       />
>     </View>
>   );
> };
> 
> export default EventsScreen;
> ```
> 
> ## Environment
> `"expo": "^36.0.1"`
> `"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",`
> `"react-native-calendars": "^1.264.0",`

UPDATE!
I tested it using an iPhone and it works perfectly there. I think the problem will be fixed once I generate the SDK for Android. I read somewhere that Expo could work slowly sometimes when the app is running in "test mode". But anyway, If someone might help me with the CONSOLE MESSAGE that would be awesome. 
Thanks, folks.

**Comment by kusaasira** [comment]
@emflomed17 , how was it once you generated the apk for Android? Any good news? Just confirming for future users who experience the same,

**Comment by emflomed17** [comment]
@kusaasira unfortunately I'm not participating in the project where the agenda was used anymore. So I did not generate the APK and could confirm if it was an expo-android performance issue.

**Comment by mleister97** [comment]
Still really slow on android for me using expo 40.
I will generate an apk and let you know.

**Comment by GabrielDvt** [comment]
I'm having this problem right now, any solutions?

**Comment by GabrielDvt** [comment]
> will generate an apk and let you know.

I'm having this problem right now, any solutions?

**Comment by mleister97** [comment]
@GabrielDvt APK was a little bit faster but still very slow.
Seems like the library is really really bad in performance.

**Comment by mleister97** [comment]
You also may see https://github.com/wix/react-native-calendars/issues/1453

**Comment by agustinchiarotto** [comment]
Hi everyone, I'm facing the same issue. Did someone find a solution?

**Comment by alew140** [comment]
ISSUE LIVE RE-OPEN THIS ISSUE

**Comment by stormbreaker1206** [comment]
Hi i'm facing the same issue was this solved?

**Comment by qbunia** [comment]
Same problem for me. Having issues.

**Comment by pycraft114** [comment]
Slow on Andorid, any news about this?

**Comment by KrisLau** [comment]
@emilisb Is there a way for this to be marked open or active again? It seems to be a problem for many people still and me as well

**Comment by DiogoRio** [comment]
Hello, this is still definitely happening. To me it happens at least on Agenda and ExpandableCalendar. Im using a list with only four days and rendering simple atomic components on Agenda for example. For ExpandableCalendar,  having this: 
`<CalendarProvider date="2022-03-24" firstDay={1}>
      <ExpandableCalendar
      />
    </CalendarProvider>`
    The Calendar is already very laggy with nothing in it. Also i do keep getting the virtualizedList log in both. Definetly still a problem.

**Comment by geniusmonir** [comment]
Facing the same problem. Any Solution???

**Comment by masayahingpuno** [comment]
does anyone have a solution? it so slow just by changing the date in agenda. using usememo removes the the error but still very slowwwww

**Comment by adrienclay36** [comment]
Two years old and no fix?

This component is awesome but it slows down every aspect of my app. Refresh controls that fetch and update state variables run fast and smooth until I open the tab that has this calendar. Subsequent action becomes unbelievably slow.

I hope there's a fix for this at some point.

**Comment by lucamagni** [comment]
Hi! I have a similar problem when tap on day in Agenda.. sometimes onPress event not works, sometimes works but with poor performance.
I don't know why, probably a bug with my react native version library, but if I comment "onLongPress" props of TouchableOpacity component inside src/calendar/day/basic/index.js, in this case works as expected with no performance problems

**Comment by TingaAB** [comment]
issue still remains

**Comment by paudyaln** [comment]
Same Issue:
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 39665.453125, "dt": 1070, "prevDt": 4954}

**Comment by pfcodes** [comment]
Have this issue when using `CalendarList` -- especially inside of a stack navigator

**Comment by rhenaldkarrel** [comment]
I'm facing this issue too. I have explored other libraries but nothing has this library's functionality that I need. I hope it'll be fixed soon.

**Comment by pencilcheck** [comment]
Please switch to flashlist. Thanks. Getting this issue on CalendarList.

**Comment by maxsl89** [comment]
Any updates? 
**CalendarProvider**
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 39390, "dt": 7256, "prevDt": 28516}

**Comment by zkteco-home** [comment]
LOG  VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 5348.5712890625, "dt": 1547, "prevDt": 5531}

**Comment by AryanTiwari6** [comment]
I'm facing the same issue as well

**Comment by hemath1001** [comment]
same issue as well

**Comment by zkteco-home** [comment]
ExpandableCalendar is very slow when click someday

**Comment by jelsiis** [comment]
Having the same issues...

**Comment by murad-sh** [comment]
Same here!!

**Comment by Elue-dev** [comment]
very slow on android, performance is very okay for iOS, any luck from anyone??

**Comment by maxsl89** [comment]
> very slow on android, performance is very okay for iOS, any luck from anyone??

I left it as is, it seems like it works faster after the build

**Comment by Elue-dev** [comment]
> > very slow on android, performance is very okay for iOS, any luck from anyone??
> 
> I left it as is, it seems like it works faster after the build

running an APK build, still pretty slow

**Comment by AndreyBernardoni** [comment]
same here, any temporary solution?

**Comment by JestemTrzcinska** [comment]
same here. when using static data from example it's working okay, but when I try to fetch data with every month change I get `VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 4875, "dt": 54919, "prevDt": 11171}`

**Comment by Anis-Ghliss** [comment]
Any updates ?? the app is very slow when changing selected dates in the ExpandableCalendar component ? the error popups up each time I change the selected date.
