### ISSUE TITLE
Impossibile to upgrade to react-native-web 0.12.x

### ISSUE THREAD

**Issue by anija** [wix/react-native-calendars#1092]
##  Description

React-native-web 0.12.x removed prop types exports as these are deprecated in React Native.
Release notes: https://github.com/necolas/react-native-web/releases/tag/0.12.0

## Expected Behavior

Not rely on deprecated functionalities.

## Observed Behavior

Version v1.264.0 still require exports/ViewPropTypes.
```
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in '/Users/silviarosa/Work/runcard/runcard-app/node_modules/react-native-calendars/src/calendar'
```

**Comment by nathsimpson** [comment]
I have a PR for this, but it's still waiting review :( https://github.com/wix/react-native-calendars/pull/1089

**Comment by chenei** [comment]
Thanks @nathsimpson
