### ISSUE TITLE
How to disable days

### ISSUE THREAD

**Issue by zhangmengying** [wix/react-native-calendars#11]
For example, disabled 4th, 7th, 22th in May.

**Comment by tautvilas** [comment]
Added a way to change textColor when using intercative marking:

```javascript
<Calendar 
  // Collection of dates that have to be colored in a special way. Default = {}
   markedDates={{'2012-05-20': [{textColor: 'gray'}]}}
  // Date marking style [simple/interactive]. Default = 'simple'
  markingType={'interactive'}
/>
```

This way you can gray-out disabled days and then just simply not perform any action when `onDayPress` is triggered for these days. Does this solve your usecase?
