### ISSUE TITLE
Disable all dates unless predicate is true

### ISSUE THREAD

**Issue by siyavash4812** [wix/react-native-calendars#1101]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I want just few days per month to be selectable/available to user. Currently the only way to do this is to set all the dates that are not selectable to disabled in the state. 
There should be a function like isDisabled that gets called for every day and checks if the component should be disabled or not. 

## Expected Behavior
If I want the date 12/02/2020 to be selectable then I should be able to do 
isDisabled = (date) => date !==  '12/02/2020'

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by chenei** [comment]
We have `disabledByDefault` which disable all the days in the calendar.
We can override this prop by pass `selectable: true` through `markedDates`.
What do you think?

@ethanshar @siyavash4812

**Comment by chenei** [comment]
Hi @siyavash4812,
You can use `disabledByDefault` to disable all the dates in the calendar.
Using `markedDates` you can simply pass `disabled: false` and it will enable the specific date.
