### ISSUE TITLE
ExpandableCalendar

### ISSUE THREAD

**Issue by farhansamu21** [wix/react-native-calendars#1102]
Hello, does ExpandableCalendar support all Calendar props? onDayPress seems doesnt work.

**Comment by dagan-arbox** [comment]
You can use 
```
 <CalendarProvider
                            date={current}
                            onDateChanged={this.onDateChange}
                            onMonthChange={this.monthChanged}
                            key={current}
                            style={[{flex: 0}]}
                        >
```
then on the function can catch updated source
` onDateChange(date, updateSource) {
        console.log(updateSource, ' NOTE UPDATE SOURCE');
        if (updateSource !== 'dayPress') {
            return true;
        }
        if (this._isMounted) {
            this.setState({calendarDate: moment.utc(date)}, () => {
                this.init();
            });
        }

    }`

**Comment by chenei** [comment]
@farhansamu21 
`ExpandableCalendar` should support `onDayPress`.
If it doesn't work, please open a bug and upload your code.

**Comment by farhansamu21** [comment]
> You can use
> 
> ```
>  <CalendarProvider
>                             date={current}
>                             onDateChanged={this.onDateChange}
>                             onMonthChange={this.monthChanged}
>                             key={current}
>                             style={[{flex: 0}]}
>  >
> ```
> 
> then on the function can catch updated source
> ` onDateChange(date, updateSource) { console.log(updateSource, ' NOTE UPDATE SOURCE'); }`

Thanks man, this works actually.

**Comment by FatemeMirzaeii** [comment]
> 
> 
> @farhansamu21
> `ExpandableCalendar` supports `onDayPress`.
> If it doesn't work, please open a bug and upload your code.
> 
> https://github.com/wix/react-native-calendars/blob/master/src/expandableCalendar/index.js#L48
> https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.js#L28
> https://github.com/wix/react-native-calendars/blob/master/src/calendar/index.js#L55

onDayPress Wont respond when we wrap ExpandableCalendar with CalendarProvider component.
