### ISSUE TITLE
How to show the previous and next month?

### ISSUE THREAD

**Issue by shahrajk** [wix/react-native-calendars#1105]
How to show the previous and next month? same as image

![Screenshot 2020-04-04 at 4 11 46 PM](https://user-images.githubusercontent.com/45192049/78424998-008f1780-768f-11ea-86f5-44cb932bd4d8.png)

**Comment by maeschli** [comment]
@shahrajk try Calendar `renderArrow` prop for rendering custom arrow

```
// Replace default arrows with custom ones (direction can be 'left' or 'right')
  renderArrow={(direction) => (<Arrow/>)}
```

**Comment by chenei** [comment]
Thanks @maeschli
