### ISSUE TITLE
Warning message after upgrade to React Native v0.62.1

### ISSUE THREAD

**Issue by douglasjunior** [wix/react-native-calendars#1106]
## Description

Warning message after upgrade to React Native 0.62.1.

## Observed Behavior

When `AgendView` is rendered I receive this warning message:

> Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. 

![image](https://user-images.githubusercontent.com/1512341/78464659-6779f400-76c2-11ea-9e54-26ac70fc107f.png)

I believe it happens because some [Animated methods have been deprecated](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0620).

## Expected Behavior

Remove the `getNode()` call of all `react-native-calendars` components.

## Environment

* `npm ls react-native-calendars`:
```
$ npm ls react-native-calendars
govfacil-gabinete-app@0.0.1 C:\projetos\ReactNative\govfacil-gabinete-app
`-- react-native-calendars@1.265.0 
```

* `npm ls react-native`: 
```
$ npm ls react-native
govfacil-gabinete-app@0.0.1 C:\projetos\ReactNative\govfacil-gabinete-app
`-- (empty)
```

## Reproducible Demo

I don't think it's necessary.

**Comment by francaddo** [comment]
Any update on this issue

**Comment by Trazmor** [comment]
In node_modules/react-native-calendars/src/agenda/index.js : 
At line 138 change : `this.scrollPad.getNode().scrollTo({x: 0, y, animated});`
with : `this.scrollPad.scrollTo({x: 0, y, animated});`

Fix it

**Comment by WynWinz** [comment]
> In node_modules/react-native-calendars/src/agenda/index.js :
> At line 138 change : `this.scrollPad.getNode().scrollTo({x: 0, y, animated});`
> with : `this.scrollPad.scrollTo({x: 0, y, animated});`
> 
> Fix it

This fixed my issue. The agenda was breaking with the following error: `undefined this.scrollPad._component.scrollTo`

Were you only getting a warning or was it causing the component to fail as well? I'm on react-native v0.62.2.

**Comment by douglasjunior** [comment]
> In node_modules/react-native-calendars/src/agenda/index.js :
> At line 138 change : this.scrollPad.getNode().scrollTo({x: 0, y, animated});
> with : this.scrollPad.scrollTo({x: 0, y, animated});
> 
> Fix it

Change code inside `node_modules` is a workaround, not a solution.

The warning is just a reminder message, it does not cause the app to crash for me.

**Comment by WynWinz** [comment]
@douglasjunior agreed it's not a solution. I was saying the app component is no longer broken for me after making this change. Any idea why it would be an error for me?

![Screenshot_20200430-155431](https://user-images.githubusercontent.com/11076956/80980356-8a4d1480-8df6-11ea-94d1-df2444ac7048.png)

**Comment by douglasjunior** [comment]
I think you should to create a new issue to report that.

**Comment by chenei** [comment]
Resolved.
