### ISSUE TITLE
Marked Dates Styling become line-through

### ISSUE THREAD

**Issue by ivanyufen** [wix/react-native-calendars#1109]
Hi, is it possible to make marking-type="period" styling for markedDates become line-through? 

This is my expected result:

![messageImage_1586265928810](https://user-images.githubusercontent.com/25142502/78675232-f24f2e80-790e-11ea-98fe-3228ddc60d68.jpg)

thank you

**Comment by maeschli** [comment]
Hi @ivanyufen! This is not possible at the moment

**Comment by ivishalsingh1986** [comment]
@ivanyufen / @maeschli 
Can we add strike through on Text / textDecorationLine.

Something similar to this.

<img width="345" alt="Screenshot 2021-02-28 at 9 47 11 AM" src="https://user-images.githubusercontent.com/38453675/109405564-ad136f80-79ac-11eb-833d-ca87c133eec5.png">
