### ISSUE TITLE
Agenda - Datepicker without Scrollview?

### ISSUE THREAD

**Issue by maks-io** [wix/react-native-calendars#1113]
## Description

Is it possible to only use the "header" (date picker) of the `Agenda` component?

## Expected Behavior

The component should only show the date picking section (like [here](https://user-images.githubusercontent.com/498393/33800569-2c1a1e5e-dd21-11e7-8893-35fe809c3c62.jpeg)).
The agenda itself / the vertical scroll list should be hidden.

Thanks in advance!

**Comment by josefleventon** [comment]
Bumping this.

**Comment by chenei** [comment]
Do you mean something like this?
https://ibb.co/bHvKpfY

**Comment by chenei** [comment]
@josefleventon I just removed the `<AgendaList/>` from the example. 
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js#L184

Not sure what is the use case.

**Comment by maks-io** [comment]
@chenei What i would need is something, like it is shown in your Agenda gif, but only the "header part" of it:

![Screenshot from 2020-06-02 12-09-34](https://user-images.githubusercontent.com/48987577/83508356-1885ea80-a4ca-11ea-8c5d-a3fb0417e797.png)

In other words, i would like to have my app's header display a date picker that only shows one entire week at a time, and when you click on it (or pull down) it would then show entire months, also like in your gif.
What I don't need in my use case however, is the agenda/scroll list itself.

**Comment by chenei** [comment]
This code is taken from our example file (this is how it looks - https://ibb.co/6vxT7XM):
```
<CalendarProvider
        date={ITEMS[0].title}
        onDateChanged={this.onDateChanged}
        onMonthChange={this.onMonthChange}
        disabledOpacity={0.6}
        // theme={{
        //   todayButtonTextColor: themeColor
        // }}
        // todayBottomMargin={16}
      >
        <ExpandableCalendar
          testID={testIDs.expandableCalendar.CONTAINER}
          // horizontal={false}
          // hideArrows
          // disablePan
          // hideKnob
          // initialPosition={ExpandableCalendar.positions.OPEN}
          // calendarStyle={styles.calendar}
          // headerStyle={styles.calendar} // for horizontal only
          // disableWeekScroll
          // theme={this.getTheme()}
          firstDay={1}
          markedDates={this.getMarkedDates()}
          leftArrowImageSource={require('../img/previous.png')}
          rightArrowImageSource={require('../img/next.png')}
        />
        <View style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          flex: 1
        }}>
          <Text style={{fontSize: 30}}>Anything you want</Text>
        </View>
      </CalendarProvider>
```

You can use `hideKnob` to disable viewing all month. I hope it helps.

**Comment by KristineTrona** [comment]
I think you should include the ExpandableCalendar in your Readme, it is exactly the feature I was looking for and took so long to find it, I am sure there are others having the same problem :)
