### ISSUE TITLE
ExpendableCalendar is not expended on iOS.

### ISSUE THREAD

**Issue by sharma-archu** [wix/react-native-calendars#1117]
I have integrated ExpendableCalendar and it's expended and close properly on android but not working on iOS. It's not scrolling up or down on iOs.
This is the code I have added::

```
<ExpandableCalendar
	testID={testIDs.expandableCalendar.CONTAINER}
	initialPosition={ExpandableCalendar.positions.OPEN}
	theme={{
		selectedDayTextColor: colors.grey,
		selectedDayBackgroundColor: '#d1e8ff',
	}}
	firstDay={1}
	markingType={'multi-dot'}
	markedDates={this.state.markedDates}
	leftArrowImageSource={require('./img/previous.png')}
	rightArrowImageSource={require('./img/next.png')}
	minDate={this.props.minDate ? this.props.minDate : ''}
	customKnob={true}
	renderCustomKnob={(isOpen) => {
		return (
			<View style={styles.knobContainer}>
				<Text style={styles.knobStyle}>{isOpen ? 'Pull Up' : 'Pull Down'}</Text>
			</View>
		);
	}}
/>
```

Please check once, and tell me what I am doing wrong here. This expended calendar feature is not working on iOS.

**Comment by maeschli** [comment]
`ExpandableCalendar` doesn't have `customKnob` and `renderCustomKnob` props. I've checked on iOS, it's expandable and horizontally scrollable :)

**Comment by chenei** [comment]
I also can't reproduce.
As @maeschli wrote, we don't support `customKnob`. you might have a problem with your implementation.

If you still have a problem with the default knob, please open an issue again.
