### ISSUE TITLE
Show Day name as first letter instead of 3 letters? 

### ISSUE THREAD

**Issue by rikinshah23** [wix/react-native-calendars#1119]
Thanks for this beautiful package. very very useful. 

Could anyone help me if there is a way to show Day name as first letter instead of 3 letters?
Example: 
"Sun" --> "S"
"Mon" --> "M" 

Thanks

**Comment by maeschli** [comment]
@rikinshah23 the only way to use one-letter day names instead of three-letter names for now is to override a `LocaleConfig` object like in example below:

```
import {LocaleConfig} from 'react-native-calendars';

LocaleConfig.locales['fr'] = {
  monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  monthNamesShort: ['Janv.','Févr.','Mars','Avril','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
  dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
  dayNamesShort: ['Dim.','Lun.','Mar.','Mer.','Jeu.','Ven.','Sam.'],
  today: 'Aujourd\'hui'
};
LocaleConfig.defaultLocale = 'fr';
```

Where `dayNamesShort: ['D','L','M','M','J','V','S']`

**Comment by chenei** [comment]
As @maeschli said, this is the only solution right now.

If you still don't find it suitable, please open a feature request.

**Comment by glushkina1** [comment]
does it work with custom header prop? I'm having trouble connecting with custom header
