### ISSUE TITLE
Cannot run your repo on iOS simulator.

### ISSUE THREAD

**Issue by azuxx** [wix/react-native-calendars#1120]
Hello,
I cloned your repo to try your library but I got this error on iOS simulator:

<img width="400" alt="Screenshot 2020-04-20 at 13 32 02" src="https://user-images.githubusercontent.com/16132913/79747149-7f30b980-830b-11ea-9cb8-8de3b37bf072.png">

I have just followed your instructions:
```
git clone git@github.com:wix/react-native-calendars.git
npm install
react-native run-ios
```

also I added pod install before launching npx react-native run-ios.

Could you help me please?
I have to decide if I can adopt your library for a client project or write a custom calendar/agent from scratch.

Thank you,
Andrea

**Comment by narender2031** [comment]
please run command `npm start`

**Comment by azuxx** [comment]
ok it worked, thank you

> please run command `npm start`
