### ISSUE TITLE
Agenda: How to set the max height of the calendar list when expanded

### ISSUE THREAD

**Issue by arelstone** [wix/react-native-calendars#1122]
I'd like to set the max height of the calendar list on the Agenda when the calendar list is expanded?

How should I go about this?

**Comment by chenei** [comment]
@arelstone 
Hi,
If you check our demo app, you can check the two examples there `Agenda` and `Expandable Calendar`.

`Agenda` will give you a full height expandable calendar while `Expandable Calendar` will give you be default only month scrolling.

`Expandable Calendar` is having `CalendarHeight` but I don't think it's working well right now.

If you still don't find it suitable, please open a more informative feature request, maybe including a design.
