### ISSUE TITLE
How can I make my own component for dayNames?

### ISSUE THREAD

**Issue by micheladrion** [wix/react-native-calendars#1125]
![Annotation 2020-04-26 152902](https://user-images.githubusercontent.com/11159589/80299853-ae936a80-87d2-11ea-8058-efe2d928e574.png)

**Comment by chenei** [comment]
Are you asking about weekdays titles? or the days in the calendar?

If it's the latter, please refer to:
https://github.com/wix/react-native-calendars#overriding-day-component

**Comment by glushkina1** [comment]
@chenei hi, could you help how to customize weekdays title, if I have custom header prop?
