### ISSUE TITLE
addMonths in calendar index

### ISSUE THREAD

**Issue by gheydari** [wix/react-native-calendars#1127]
hi
what is addMonths in calendar/index.js? where is the function? 
line 158: this.updateMonth(this.state.currentMonth.clone().addMonths(count, true));

I want to change the logic to work with different calendars like Hijri and Jalalli (currentMonth should change to get exact date for them)

**Comment by chenei** [comment]
Hi,
We are using _XDate_.

Please refer to:
http://documentation.metacommunications.com/display/MSG/XDate.addMonths
