### ISSUE TITLE
Multi mark and multi markingType

### ISSUE THREAD

**Issue by muslimmuda15** [wix/react-native-calendars#1128]
Hi,
Can I make my calendar like this :
![calendar](https://user-images.githubusercontent.com/26782958/80560496-52fff180-8a0b-11ea-8cf0-fcb7d74475d3.png)

how do I make my calendar have different of `date marking style`?

**Comment by chenei** [comment]
Hi,
Please check the last **NEW!** section here:
https://github.com/wix/react-native-calendars#date-marking
