### ISSUE TITLE
Memory leak with Agenda component

### ISSUE THREAD

**Issue by dansokol** [wix/react-native-calendars#1132]
## Description

Memory leak when using the Agenda component.  After leaving a screen that has the Agenda component, not all memory is released that was created from the Agenda component.

The cause appears to be in src/agenda/index.js, in the constructor a listener is added to scrollY, i.e. line 126: this.state.scrollY.addListener(...) and this listener is never removed.

I confirmed memory leak and resolution by adding "this.state.scrollY.removeAllListeners();" in componentWillUnmount and memory issue went away.

## Expected Behavior

Memory usage should go back to what it was before using Agenda component, i.e. after navigating back from a screen that has the component, memory usage should revert to what it was before viewing that screen.

## Observed Behavior

Memory usage before going to screen with Agenda component: 122
Memory usage after going to screen with Agenda component: 125
Memory usage after navigating back: 122
Memory usage after going to screen with Agenda component: 135
Memory usage after navigating back: 129
Memory usage after going to screen with Agenda component: 143
Memory usage after navigating back: 138
Memory usage after going to screen with Agenda component: 151
Memory usage after navigating back: 145
...

## Reproducible Demo

I can make a demo if you wish, though I think the cause is obvious and I verified the solution of removing the scrollY listeners in componentWillUnmount.

I can create a PR with fix as well if you'd like.

Thank you and just want to say that this library is awesome!  Much appreciation to everyone who has contributed and supported this project.

**Comment by chenei** [comment]
@dansokol thanks for this great observation.
Please create a PR and assign me as a reviewer.

**Comment by chenei** [comment]
@dansokol since it's a performance issue, I pushed a fix right away.
I credited you in the PR. thanks again.
