### ISSUE TITLE
Is it possible to show a horizontal view of all events for just the current day?

### ISSUE THREAD

**Issue by nats12** [wix/react-native-calendars#1135]
I'd like to have a compact horizontal view of all events for the present day. E.g. below photo:

<img width="584" alt="Screenshot 2020-05-04 at 22 16 58" src="https://user-images.githubusercontent.com/15801768/81014651-26a60400-8e55-11ea-9663-aac888bcf54b.png">

Is this possible to achieve at the moment?

Thanks :)

**Comment by chenei** [comment]
Sorry, it's not achievable.
