### ISSUE TITLE
textTransform & knob style

### ISSUE THREAD

**Issue by dabhitapan** [wix/react-native-calendars#1136]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

text transform for calendar header on expandableCalendar & knob style

## Expected Behavior

Allow to modify(text transform) the names of the month and years & knob style

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by chenei** [comment]
Hi @dabhitapan,
Currently, we don’t provide an option to customize the knob.

You can customize the Month and Year color. see this example:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L79
