### ISSUE TITLE
How do i set the current day to always be displayed in the middle of the calendar (week)

### ISSUE THREAD

**Issue by Vasault** [wix/react-native-calendars#1138]
i'm not entirely sure if this is possible natively, but since i've been testing several ways to do so, i guess is not possible but, my point is, what i want to do is to show the calendar week, but set the current day, in this case today, to be displayed in the middle of the week

![33800569-2c1a1e5e-dd21-11e7-8893-35fe809c3c62](https://user-images.githubusercontent.com/15862547/81208634-5d873180-8f9d-11ea-9386-dc2f251934f1.jpeg)

the idea is to whenever i sit in a day like sunday, that day will be displayed in the middle

**Comment by chenei** [comment]
Hi,
Did you check `firstDay` prop?
You can do some logic to make this happen.

**Comment by Vasault** [comment]
> Hi,
> Did you check `firstDay` prop?
> You can do some logic to make this happen.

sorry, this was already on this post https://github.com/BugiDev/react-native-calendar-strip/issues/179#event-3330361838 and there is no firstDay prop

**Comment by chenei** [comment]
We do have `firstDay` prop:
https://github.com/wix/react-native-calendars/blob/c2b9b5d291b98355fb706de07f0a17f8d6c1d117/src/calendar/index.js#L45
