### ISSUE TITLE
Set timezone for calendar

### ISSUE THREAD

**Issue by AshokICreate** [wix/react-native-calendars#114]
I would like to set timeZone for the calendar component and i want to display it based on their timezone format.

How to do that?

**Comment by tautvilas** [comment]
Hi, currently there is not time zone parameter, but you can set `monthFormat`, localize month/weekday names and set first day of the week manually.

**Comment by AshokICreate** [comment]
**Thanks for the quick reply.**

_I have different use case._

**_1. i want force calendar component to use specific timeZone instead of local timeZone._**

**Comment by tautvilas** [comment]
what do you need the timeZone for? Since we are not dealing with times but only with dates?

**Comment by AshokICreate** [comment]
My app is for particular region(United States).

My Use case is if he is in other country also it should take US date.

**Comment by andrerfneves** [comment]
@AshokICreate you should be able to just hardcode that date format in instead of depending on the user's local time/date.

**Comment by AshokICreate** [comment]
hardCoding values will help you to show the currentDate but onClick of date it's giving me date based on localTimeZone which is not use full in my case.

what i am expecting is set `timeZone: 'America/Los_Angeles',`   `onDayPress` Get me the date and time based on timeZone which i have set.

**Comment by tautvilas** [comment]
onDayPress is giving selected day info. If you are talking about timestamp property - it is UTC timestamp representing the day selected. Could you elaborate why do you need to set timezone? What is the exact usecase?

**Comment by Dipak26** [comment]
I also want to set TimeZone on calendar Agenda component. How I do that?

**Comment by T-moz** [comment]
@ashokrse2020 did you find a solution ? I have the same issue

**Comment by Alexva397** [comment]
Was there a solution to this? Do I need to specify the first second of the current date put in for selected? That way it recognizes that the day starts here and will therefore load the rest of the dates based on the timezone (offeset specified) in the selected?

**Comment by slevental** [comment]
> onDayPress is giving selected day info. If you are talking about timestamp property - it is UTC timestamp representing the day selected. Could you elaborate why do you need to set timezone? What is the exact usecase?

When you press a date, it will generate timestamp of this date in GMT timezone, not in the given timezone; For instance if I want to choose today's date, e.g. `1 June` I will get unix corresponding timestamp: 1654041600000 - but if I then transform it to the current timezone of the user - it will become 31 May; 

I agree that it's a good practice for logging and server side events to use UTC, but in some cases we want to use the same time zone that user had used - to not transform back and forth their dates

**Comment by mehdi-developer** [comment]
How can we change the date timezone locale to another country like turkey ? I know there is not a feature like this but If I may ask , How can I hardcode it ?

**Comment by samthui** [comment]
I have same need. Here's how I made it work.
I'm using v`1.1293.0`. The selected date's dateString & timestamp are in UTC time. So we can use the other properties {year, month, day} to archive what we want

**Comment by ViraliVasa** [comment]
I also want to set manual timezone in AgendaList but library automatically sets local device time zone and _CalendarProvider's onDateChanged_ is fired and date changed to local time zone.There is no prop to set timezone.

Can anyone help?

**Comment by mdparveen578** [comment]
is there any update on this ?? the callback response dates are in utc eventhough when i defined the timeZone prop
