### ISSUE TITLE
Multiple mark style period with multi dots

### ISSUE THREAD

**Issue by harshalkd** [wix/react-native-calendars#1140]
Hello guys, I want to achieve below image custom calendar so can i achieve this
 [Calendar Image](https://drive.google.com/file/d/1bN6TkMHXcy5laltQY2h53zDxMMbXZ--J/view?usp=sharing)

## Description

I want to make Calendar UI with with period and multi dots combination as above image so can i make it with this library?

**Comment by chenei** [comment]
Hi,
Currently, we can't achieve this design.
Please refer to the docs to see what you can achieve:
https://github.com/wix/react-native-calendars#date-marking

We do consider to add more flexibility for Date Marking.

**Comment by chenei** [comment]
@harshalkd ,
Please see the last section here https://github.com/wix/react-native-calendars#date-marking
We introduce a new way to combine period with simple dot.

If you still don't find it suitable, please open a feature request.
