### ISSUE TITLE
ActivityIndicator - Agenda 

### ISSUE THREAD

**Issue by OriHayun** [wix/react-native-calendars#1143]
Hello
I have a problem with ActivityIndicator. When i use the component even if i have an item and they render fine the ActivityIndicator still run.
if i move to other page in my navigator and back the ActivityIndicator desapire.

thanks

**Comment by chenei** [comment]
Hi,
I can't reproduce in our example app.
Can you please upload video and code snippet so I can better understand the problem.

**Comment by OriHayun** [comment]
Hey,  thanks for your answer

Can i upload a video of this to this Email?

בתאריך יום ב׳, 1 ביוני 2020, 14:51, מאת Chen Eilat ‏<
notifications@github.com>:

**Comment by chenei** [comment]
You can upload the video to any cloud you find suitable (e.g Google Drive) and paste the link here.

**Comment by OriHayun** [comment]
http://proj.ruppin.ac.il/igroup4/prod/uploadImages/calendar.mp4

[image: image.png]
[image: image.png]

I mention the problem is that the Activity Indicator continues to work even
when there are items

You can notice towards the end of the video that if I move the tab
navigator to another tab and return then the Activity Indicator disappears


Thank you !!!


‫בתאריך יום ג׳, 2 ביוני 2020 ב-13:08 מאת ‪Chen Eilat‬‏ <‪
notifications@github.com‬‏>:‬
