### ISSUE TITLE
How to hide agenda details and show calendar list by default?

### ISSUE THREAD

**Issue by Hareramrai** [wix/react-native-calendars#1144]
## Description

I am trying to agenda component but unable to figure out a few things which are listed below. 

1. How to show only calendar list by default for agenda?
2. How to change the color of dot for the events list on calendar list and also multiple dot for multiple events on same day?

## Environment
 "react-native-calendars": "^1.265.0"

**Comment by chenei** [comment]
Hi @Hareramrai,
Did you check all the examples in the README file? it sounds like we covered all your questions there.
https://github.com/wix/react-native-calendars
You can also run the example app and see all the examples.

If you trying to achieve a specific use case, please upload the design with the question.
