### ISSUE TITLE
Updating Agenda after Updating/Adding/Removing an Item

### ISSUE THREAD

**Issue by AndiPandy** [wix/react-native-calendars#1145]
## Description

I tried so hard so far but as I'm new to RN I don't seem able to find a solution to properly update the Agenda upon Item Modification. The code below only has a fraction of the code used, but I believe it's everything needed to help me :) I'm thankful for every little help!

## Expected Behavior

When I press on delete, I expect the item to disappear from the view, preferably with a subtle animation. The delete buttons appears through the swipeable component (not that it matters), pictures at the end of the issue. 

## Observed Behavior

The View doesn't update correctly as it should

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.265.0
react-native@0.61.4

On my Android Phone

#######################################
## Reproducible Demo

my items object look as follows:

2020-05-17 [
... ,
Object {... , "key": "-M7TaNvUVcRiZCWKUsTg", "date": "17-05-2020", ... ,}
... ,
]
2020-05-17 [...]

```
constructor(props) {
    super(props);

    this.state = {
      items: {},
      allAgendaItems: {},
    };
  }

componentDidMount() {
//to populate my temporary object with the firebase items, this works fine
    firebaseFetchByDate(this.state.allAgendaItems);
  }

onItemDelete = (item) => {
//to delete it from firebase, this works fine
    firebaseDeleteItem(item);
//which steps are else to take?
 };

renderItem(item) {
      return(
         <View>
              <AgendaCardEntry item={item} onRightPress={() => this.onItemDelete(item)} />
          </View>
       )
 }

//to fill the items with the temporary object 
 loadItems(day) {
    setTimeout(() => {

      this.fillItems(day, this.state.items, this.state.allAgendaItems);
    }, 1000);
  }

  rowHasChanged(r1, r2) {
    return r1 == r2;
  }

render() {
return (
        <Agenda
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          renderItem={this.renderItem.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
        />


)}
```
#######################################
What I tried

```
//get the index of the object that has to be removed from items and remove it with slice
//but it didnt really work. The view immediately updated, but it was always the last
//object of that date that got removed from the view. even though the correct item was
//removed from items (confirmed by logging the items). The View adapted after
//another stateChange was invoked.

onItemDelete = (item) => {
    firebaseDeleteItem(item);
    var date = moment(item.date, "DD-MM-YYYY").format("YYYY-MM-DD");
    var toRemoveFromItems = this.state.items[date].findIndex(
      (object) => object.key == item.key
    );
    this.state.items[date].slice(toRemoveFromItems, 1);
    this.forceUpdate();
  };
```

#######################################
My temporary solution until someone helps me with a real fix

```
//delete in firebase for real, but mark them as deleted, force an update
 onItemDelete = (item) => {
    firebaseDeleteItem(item);
    var date = moment(item.date, "DD-MM-YYYY").format("YYYY-MM-DD");
    var toRemoveFromItems = this.state.items[date].findIndex(
      (object) => object.key == item.key
    );
    this.state.items[date][toRemoveFromItems].deleted = true;
    this.forceUpdate();
  };

//if the item is marked as delete, dont return anything here
renderItem(item) {
if (!item["deleted"]) {
      return(
         <View>
              <AgendaCardEntry item={item} onRightPress={() => this.onItemDelete(item)} />
          </View>
       )
 }
```

![Screenshot_20200518-041915](https://user-images.githubusercontent.com/44343656/82170430-afe12000-98c4-11ea-9021-30499ef0ce9a.jpg)
![Screenshot_20200518-041922](https://user-images.githubusercontent.com/44343656/82170431-b1124d00-98c4-11ea-9f46-918d7a13a512.jpg)

**Comment by pdunfy** [comment]
I would change the rowHasChanged() from **==** to **!===**.

rowHasChanged(r1, r2) {
    return r1 !== r2;
  }
