### ISSUE TITLE
Selected day does not change the color

### ISSUE THREAD

**Issue by Eduardo-Maia98** [wix/react-native-calendars#1150]
Hello, I used the same configuration and theme (which is in the repository) for <Calendar /> and, when I select a day, it does not change the color when clicking. OnDayPress returns the date correctly, but basically the problem is that the day is not being selected.

**Comment by nadun94** [comment]
Here is my code, and it works for me.
`export const CalenderComp: FC = () => {
  const [selectedDate, setSelectedDate] = useState<string | any>(
    new Date().toISOString().split('T')[0],
  );
  return (
    <Calendar
      onDayPress={(day) => setSelectedDate({[day.dateString]:{selected: true, selectedColor: '#FD8282'}})}
      current={new Date().toISOString().split('T')[0]}
      markedDates={selectedDate}
      theme={{
        backgroundColor: '#ffffff',
        calendarBackground: '#ffffff',
        textSectionTitleColor: '#b6c1cd',
        // selectedDayBackgroundColor: '#FD8282',
        selectedDayTextColor: 'red',
        todayTextColor: '#00adf5',
        dayTextColor: '#FD8282',
        textDisabledColor: '#979797',
      }}
    />
  );
};`
![image](https://user-images.githubusercontent.com/27319447/82880109-93e01d00-9f5b-11ea-9310-1f8f6d7909b0.png)

**Comment by luvnish19** [comment]
@nadun94 
Please mention setSelectedDate method.
It is showing me Can't find variable setSelectedDate.

Thanks in advance

![Simulator Screen Shot - iPhone Xs Max - 2020-05-26 at 15 26 49](https://user-images.githubusercontent.com/15010312/82887322-7912a600-9f65-11ea-9b09-c2475154dd08.png)

**Comment by luvnish19** [comment]
@Eduardo-Maia98 I am also facing this same issue. Is there way out?

**Comment by Eduardo-Maia98** [comment]
> @Eduardo-Maia98 I am also facing this same issue. Is there way out?

Yes this work for me.
Const [markedDates,setMarkedDates]  = useState("")
![FB_IMG_1590494017567](https://user-images.githubusercontent.com/49003509/82897758-82cce700-9f2e-11ea-8a33-1ec8ec8d1a4d.jpg)

**Comment by Yandamuri** [comment]
@nadun94 @Eduardo-Maia98 In old version of package, date is getting highlighted with out setting it as marked date. Is it necessary to set the `selectedDate `as `markedDate `to make it highlighted?
