### ISSUE TITLE
How to change day text color in Multi Dot Marking?

### ISSUE THREAD

**Issue by luvnish19** [wix/react-native-calendars#1152]
Given image in documentation assumes that  in multi dot marking, day text color can be customized but there is no such parameter which can change text color.
Please answer if I am missing something

![marking4](https://user-images.githubusercontent.com/15010312/83251838-ddcd3b00-a1c7-11ea-8970-8c40f467bcb8.png)

**Comment by chenei** [comment]
Hi,
I added an option to change the text color. I also update the example file.

Please check this commit:
https://github.com/wix/react-native-calendars/commit/74ad27544f324aaf246c851279cab73f0baf52d7

New prop on _markedDates_ called _selectedTextColor_.
