### ISSUE TITLE
Disable weekend in calender (Sunday and Saturday)

### ISSUE THREAD

**Issue by jawwad22** [wix/react-native-calendars#1153]
Hi, I need to disable saturday and sunday in calendar or apply styling this two days in every month, anyone know how can i acheive it
thank you

**Comment by chenei** [comment]
@jawwad22 
Please look at the example in the readme file:
https://github.com/wix/react-native-calendars#customize-days-titles-with-disabled-styling

you can also take a look at the full example here:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L120
