### ISSUE TITLE
How to add a button which jumps to current date/month

### ISSUE THREAD

**Issue by take** [wix/react-native-calendars#1175]
Hi thanks for the awesome library :D 

Currently I'm using the simple `Calendar` but I want to add a button which jumps to the current date/month 🤔 

Is it recommended to use `ExpandableCalendar` for these kind of things? :eyes:

**Comment by chenei** [comment]
Yeah, I guess you can use `ExpandableCalendar` which his a build-in Today button.
Let me know if you have any problems.

**Comment by take** [comment]
@chenei thanks for the quick reply! 😄 

Is there a minimal code which `ExpandableCalendar` works? 🤔 

I saw the [example code](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js) but looks like the code is pretty long, or is this the minimal version? :eyes:

**Comment by chenei** [comment]
Frankly, I don't think it's that long.
If you look at the render function and remove all the unused props, it's not that long.

It's a good head start.

**Comment by take** [comment]
aha k thanks I'll try it out 👍

**Comment by take** [comment]
Hi @chenei , can you tell me how to launch the example app? :eyes: looks like the entry point file is inside src although app.json is in the directory above app.js 🤔

**Comment by take** [comment]
aha nvm entry point file was at the top directory, index.ios.js 😉
