### ISSUE TITLE
iOS Horizontal CalendarList move on tap between days 

### ISSUE THREAD

**Issue by sebastianor** [wix/react-native-calendars#1184]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

In iOS platform when You tap between days, the calendar will move. When You again tap on date it will back to the normal. On Android device it works fine  Here You can see this sample 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11159141/84200313-ce42d180-aaa6-11ea-95c9-d9a99c5b99f7.gif)

## Expected Behavior

When tap between dates nothing should happen like in Android 

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.290.0 
react-native@0.62.0 

Also specify:

1. Phone/emulator/simulator & version: iPhone XI & iOS 13.5

## Reproducible Demo

```
<View style={{ borderRadius: 10,  width: Dimensions.get("window").width * 0.95, backgroundColor:"#fff", overflow:"hidden", height:320}}>
      <CalendarList
       markedDates={this.state.marked}
      current={this.state.selectedDate}
       onDayPress={(day) => {
        this.setNewDaySelected(day.dateString)
      }}    
        calendarWidth={Dimensions.get("window").width*0.95}
        style={{   width: Dimensions.get("window").width*0.95, height:300}}
        pastScrollRange={24}
        futureScrollRange={24}
        horizontal
        pagingEnabled
     
      />
  </View>
```

And this is function for select 
```
  setNewDaySelected(date){
    var obj = Object.assign({})
    obj[date] = {selected: true, selectedColor: "red", marked: false}
    this.setState({selectedDate: date, marked: obj })
       
  }
```

**Comment by chenei** [comment]
Hi @sebastianor ,
I ran your code and it seems to be there is an issue in those lines:
```
        calendarWidth={Dimensions.get("window").width*0.95}
        style={{   width: Dimensions.get("window").width*0.95, height:300}}
```

I also update the example:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/horizontalCalendarList.js

**Comment by sebastianor** [comment]
Hi @chenei 
Thank you for your response.
I just checked and it works fine with the width set to: 
```
calendarWidth={Dimensions.get("window").width}
        style={{   width: Dimensions.get("window").width, height:300}}
```
it works fine

So CalendarList must be on the whole screen width?

**Comment by chenei** [comment]
It looks like :)
