### ISSUE TITLE
WeekCalendar markedDates not refresh correctly

### ISSUE THREAD

**Issue by choukat** [wix/react-native-calendars#1188]
## Description

I have expandable Calendar and weekCalendar with some markedDays from props. (example come from this repo)

## Expected Behavior

When props is changing, the new dot under days must be there in WeekCalendar and in ExpandableCalendar.

## Observed Behavior

Only month view (from expandableCalendar) is refreshed when props are changing. Week Calendar is refresh only if I pull the view to expandable Calendar. 

This is the code of the components : the props is this.props.monthsEvents, when i am in months view everything works fine. But with weekCalendar it never refresh. I put a log at the begin of the render() function and the general view refresh correctly i can see the new values. 

`render() {
    console.log('this.props.monthsEvents', this.props.monthsEvents)
    const moment = require('moment');

    LocaleConfig.locales['fr'] = {
      monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
      monthNamesShort: ['Janv.','Févr.','Mars','Avril','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
      dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
      dayNamesShort: ['D','L','M','M','J','V','S'],
      today: 'Aujourd\'hui'
    };
    LocaleConfig.defaultLocale = 'fr';

    return (
      <CalendarProvider
        date={new moment().format('YYYY-MM-DD')}
        onDateChanged={this.onDateChanged}
        onMonthChange={this.onMonthChange}
        disabledOpacity={0.6}
        markedDates={this.props.monthsEvents}
      >
        {this.props.weekView ?
          <WeekCalendar
            firstDay={1}
            markedDates={this.props.monthsEvents}
          /> :
          <ExpandableCalendar
            theme={this.getTheme()}
            firstDay={1}
            markedDates={this.props.monthsEvents}
            leftArrowImageSource={require('./img/previous.png')}
            rightArrowImageSource={require('./img/next.png')}
          />
        }
        <FlatList
          extraData={this.state}
          renderItem={this._renderItem}
          data={this.props.events}
          onEndReached={() => {
            if(this.props.events.length > 9) {
              this.props.getEventsByDate(null, null)
            }
          }}
          ListFooterComponent={this._renderLoading}
        />
      </CalendarProvider>
    );
  }`

I saw there is some problems with markedDate props, but it's weird that is working with ExpandableCalendar component and not with WeekCalendar. 

If someone has some ideas. 

Thx. 

After lot of analysis I found that the problem come only when I press next to go to next week and we are changing month. If i press a day in the new week, everything is ok again. The weird thing is that when I go to previous week and change month it works well.

**Comment by jonasgroendahl** [comment]
also a problem for me.
