### ISSUE TITLE
Can't resolve ./platform-style on react-native-web

### ISSUE THREAD

**Issue by hugogrochau** [wix/react-native-calendars#119]
I'm getting a:
`Module not found: Can't resolve './platform-style' in 'node_modules/react-native-calendars/src/agenda'`
error when using the Calendar with `react-native-web`.

Is this because there's a missing `platform-style.js` fallback for the `.ios.js` and `.android.js` files or am I doing something wrong?

Awesome project by the way!

**Comment by overengineered** [comment]
Yes, that would be the cause of it. Would you be able to determine the style settings needed for web?

**Comment by tautvilas** [comment]
I am not sure anyone has tried to use agenda with react-native-web before. So there might be other issues too.

**Comment by hugogrochau** [comment]
@overengineered @tautvilas 
I was using the Calendar, not the Agenda. I guess babel/webpack was traversing through that directory also.

I copied `platform-style.android.js` to `platform-style.js` and it worked fine for me.

**Comment by tautvilas** [comment]
thx for info, we will add fallback

**Comment by tautvilas** [comment]
added android style as fallback style
