### ISSUE TITLE
calendar background is transoarent - not able to change it

### ISSUE THREAD

**Issue by praveens-gogst** [wix/react-native-calendars#1190]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I am using the calendar inside a TouchableOpacity. showing it on click of an icon.
When calendar shown, its background is having some opacity. 
tried changing the theme: {{calendarBackgroundColor:'red'}} but the opacity remains same.
Also, not able to select any date, i.e. onDayPress is not working/calling.

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
- background should be opaque.
- onDayPress should be working.

What action did you perform, and what did you expect to happen?
- Using Position: absolute, TouchableOpacity, zIndex:9999

## Observed Behavior
- opacity, date not selectable

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: UNMET DEPENDENCY react-native-calendars@1.289.0 
* `npm ls react-native`: UNMET DEPENDENCY react-native@0.61.5 

Also specify:

1. Phone/emulator/simulator & version:
- iOS simulator
## Reproducible Demo
```
{state.showCalendar && (<TouchableOpacity style={{position: 'absolute', right: 0, top:40, zIndex: 999}}>
                 <Calendar 
                            style = {{zIndex: 999}}
                            theme={{
                                backgroundColor: '#ffffff',
                                calendarBackground: '#ffffff',
                            }}
                            onDayPress={(day) => {
                                reactotron.log("day, type", day, typeof day);
                            }}
                        />
                    </TouchableOpacity>)}
```
Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by praveens-gogst** [comment]
it can be in view as well, not an issue, just to position it. even its not there, its behaving the same way

**Comment by chenei** [comment]
We have a working example here:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L91

Did you check it?

**Comment by praveens-gogst** [comment]
yes it works with that but if i am using `position: absolute` , its failing. 
```
<Calendar 
                            style = {{position: 'absolute', right: 0, top:40, }}
                        />
```

can reproduce with the above code.
