### ISSUE TITLE
ExpandableCalendar jitters when it's dragged

### ISSUE THREAD

**Issue by krakz999** [wix/react-native-calendars#1192]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

ExpandableCalendar jitters when it's being dragged up or down (closing/opening the calendar).

Video: https://drive.google.com/file/d/1tcjp4S24Prb16oN3Qz1fBRJJqYPE1YAZ/view?usp=sharing

## Expected Behavior

Smooth transition.

**Comment by chenei** [comment]
We do need to improve the animation. 
Currently we are not using native driver
