### ISSUE TITLE
TypeError:this.scrollPad.scrollTo is not a function 

### ISSUE THREAD

**Issue by TeamDlxx** [wix/react-native-calendars#1193]
## Description

getting the above error while using Agenda in react native calenders

## Expected Behavior

it should show a calender with dats highlighted and agenda against them
## Observed Behavior

i just copied the agenda part and pasted into my app and it throws this error
If there's an error message, please paste the *full terminal output and error message* in this code block:

```
![image](https://user-images.githubusercontent.com/52232678/84469393-6523af80-ac9a-11ea-864a-e3b2254b972e.png)



## Environment


react-native version 0.61
react-native-calenders version : "^1.282.0"
android phone version 8.1
also faced same in xcode simulator

**Comment by chenei** [comment]
Please upgrade the library to the latest, we fixed the issue.
Tell me if it’s still consistent.

**Comment by TeamDlxx** [comment]
okay i try , thank you so much

**Comment by TeamDlxx** [comment]
yes the issue is fixed , thanks

**Comment by moonlight96** [comment]
> 是的，问题已解决，谢谢

Could you tell me how to solve,please?
