### ISSUE TITLE
Multi-dots limiting solution

### ISSUE THREAD

**Issue by favger** [wix/react-native-calendars#1194]
![1](https://user-images.githubusercontent.com/25633595/84487148-01ec4a00-aca7-11ea-9b53-83ad5ddfa6a6.png)

node_modules/react-native-calendars/src/calendar/day/multi-dot/index.js line 91

![2](https://user-images.githubusercontent.com/25633595/84487150-0284e080-aca7-11ea-9ce9-f436637bbeb3.png)

![3](https://user-images.githubusercontent.com/25633595/84487156-03b60d80-aca7-11ea-8ee8-109f9133e81f.png)

**Comment by chenei** [comment]
Is it a feature request?

**Comment by favger** [comment]
@chenei Yes. Sorry for missing information...

**Comment by belgamo** [comment]
Can I open a PR for this @favger?

**Comment by favger** [comment]
@belgamo Yes, please, may work for someone else...

**Comment by belgamo** [comment]
Ok, I will work on it. Thank you!
