### ISSUE TITLE
Question: How to jump to a specific month

### ISSUE THREAD

**Issue by take** [wix/react-native-calendars#1196]
Hi thanks for the awesome library :) 
This is just a question so please feel free to close this issue if it's impossible in the current state of this library.

Is there a way to scroll/jump the library page to a specific month?

Thanks,

**Comment by emilisb** [comment]
Do you mean to jump to a specific month after the calendar is already visible (for example, after pressing a button), or to open the month initially?

**Comment by take** [comment]
@emilisb hi thanks for the response, I mean the first :)

**Comment by jzheng1994** [comment]
@take I had this same question and dug through the code a bit.

```
  // Create ref for calendar 
  const calendarRef = useRef(null);

  // Attach ref to calendar component 
  <CalendarList
        ref={calendarRef} 
   />

   // Pass in date that you want to scroll to in the first argument
  calendarRef.current.scrollToDay(new Date(), undefined, true);
```

The source code for the scrollToDay function is located [here](https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.js)

**Comment by take** [comment]
oooo thanks! 🎉 @jzheng1994

**Comment by knif147** [comment]
Hi @jzheng1994, I don't see function scrollToDay in ref of the calendar. So I can't execute this. Can you give me some help?

**Comment by benni2108** [comment]
> @take I had this same question and dug through the code a bit.
> 
> ```
>   // Create ref for calendar 
>   const calendarRef = useRef(null);
> 
>   // Attach ref to calendar component 
>   <CalendarList
>         ref={calendarRef} 
>    />
> 
>    // Pass in date that you want to scroll to in the first argument
>   calendarRef.current.scrollToDay(new Date(), undefined, true);
> ```
> 
> The source code for the scrollToDay function is located [here](https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.js)

What is the correct implementation of that code.
I am always getting an "invalid hook call" error

**Comment by KurtMar** [comment]
@benni2108 
I got createRef to work. Here's an example of propagating the month change from one calendar to another.

**TypeScript:**
```typescript
import React from 'react'
import { createRef, RefObject } from 'react'
import XDate from 'xdate'
import { View } from 'react-native'
import { Calendar } from 'react-native-calendars'

interface CalendarRefCurrent {
  updateMonth: (day: XDate, doNotTriggerListeners: boolean) => void
}

const MyCalendars = () => {
  const myRef1 = createRef<any>()
  const myRef2 = createRef<any>()

  const propagateMonthChange = (refTarget: RefObject<CalendarRefCurrent>, date: DateObject) => {
    refTarget.current.updateMonth(new XDate(date.year, date.month - 1, date.day), true)
  }

  return (
    <View style={{flex: 1}}>
      <Calendar ref={myRef1} onMonthChange={(date) => propagateMonthChange(myRef2, date)} />
      <Calendar ref={myRef2} onMonthChange={(date) => propagateMonthChange(myRef1, date)} />
    </View>
  )
}

export default MyCalendars
```

**JavaScript:**
```typescript
import React from 'react'
import { createRef, RefObject } from 'react'
import XDate from 'xdate'
import { View } from 'react-native'
import { Calendar } from 'react-native-calendars'

const MyCalendars = () => {
  const myRef1 = createRef()
  const myRef2 = createRef()

  const propagateMonthChange = (refTarget, date) => {
    refTarget.current.updateMonth(new XDate(date.year, date.month - 1, date.day), true)
  }

  return (
    <View style={{flex: 1}}>
      <Calendar ref={myRef1} onMonthChange={(date) => propagateMonthChange(myRef2, date)} />
      <Calendar ref={myRef2} onMonthChange={(date) => propagateMonthChange(myRef1, date)} />
    </View>
  )
}

export default MyCalendars
```

**Comment by filipearena** [comment]
> @take I had this same question and dug through the code a bit.
> 
> ```
>   // Create ref for calendar 
>   const calendarRef = useRef(null);
> 
>   // Attach ref to calendar component 
>   <CalendarList
>         ref={calendarRef} 
>    />
> 
>    // Pass in date that you want to scroll to in the first argument
>   calendarRef.current.scrollToDay(new Date(), undefined, true);
> ```
> 
> The source code for the scrollToDay function is located [here](https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.js)

This made my day. Thank you kind sir, you are the real MVP.

**Comment by emilisb** [comment]
Please have in mind that this solution is not documented and it depends on the internals of the component. If we rename the method, this solution will stop working. We will try to not introduce breaking changes though, I will make sure we document this behaviour properly :)

**Comment by nandorojo** [comment]
@emilisb this would be a great thing to have documented!

**Comment by nandorojo** [comment]
> ```ts
> .updateMonth(new XDate(date.year, date.month - 1, date.day), true)
> ```

You are a hero for this one. I couldn't get it to work with `Calendar` (on web) until I used `XDate`. Thanks!

**Comment by nandorojo** [comment]
The approaches mentioned above actually don't fully work for `CalendarList`. If you call `calendarRef.current.updateMonth(...)`, it only works if you're moving a few months over. However, if you move from something like March 2020 to January 2021, calling this function makes the calendar scroll to a placeholder month.

Here is a video example:

https://user-images.githubusercontent.com/13172299/115279379-ab486b80-a114-11eb-856f-486ffab324e1.mp4

Notice that, when I click "Jump to Today", everything works fine. **However, if I scroll far away from today, and then call "Jump to Today"**, it just shows a blank "April 2021" card. 

Once I scroll again it works fine. My best guess is that the library is showing an empty placeholder if `viewableItems` is far from the current index, and `updateMonth` doesn't seem to trigger the `viewableItemsChanged` callback from FlatList. Or, perhaps there's some sort of `onScroll` call that isn't working.

Once I manually scroll a little, it works again. You'll see in the video.

**Comment by vladiRozen** [comment]
much easier solution is to use
`calendarRef.current.addMonth(1) or calendarRef.current.addMonth(-1);`
this is the implementation in the library.

**Comment by ZeeshanAhmadKhalil** [comment]
TypeError: calendarRef.current.scrollToDay is not a function

**Comment by mohity777** [comment]
calendarRef.current.addMonth, calendarRef.current.updateMonth, calendarRef.current.scrollToDay are not working

**Comment by mohity777** [comment]
calendarRef.current.scrollToDay, calendarRef.current.addMonth, calendarRef.current.updateMonth does not work with Expandable Calenders.

**Comment by FaizanMostafa** [comment]
@mohity777 Did you find any solution for ExpandableCalendar component?
