### ISSUE TITLE
Custom Container

### ISSUE THREAD

**Issue by wcardosodev** [wix/react-native-calendars#1199]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
This may already be possible but I'm unsure how it is done. I'm trying to create a custom dayComponent, which would allow you to have more than one background color in the dayComponent. Would this be possible to currently do? 

## Expected Behavior
A dayComponent would have 3 column views, each with their own background color.

What action did you perform, and what did you expect to happen?
dayComponent={({date, state}) => {
                return (
                    <View style={{flex: 1, flexDirection: 'row'}}>
                        <View style={{flex: 1, backgroundColor: 'purple'}}></View>
                        <View style={{flex: 1, backgroundColor: 'red'}}><Text>Day Text Here</Text></View>
                        <View style={{flex: 1, backgroundColor: 'blue'}}></View>
                    </View>
                );
            }}

## Observed Behavior

What actually happened when you performed the above actions?
The columns worked a bit, however the backgroundColor wasn't applied.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

**Comment by chenei** [comment]
Can you please upload the design you want to achieve? or maybe a sketch?

**Comment by willaay96** [comment]
![date](https://user-images.githubusercontent.com/17492466/84638684-3b16fb00-aeef-11ea-8578-3a41c1913329.png)

I want it to look something like this, but without the text on the left and right columns, only on the middle column would be the day.
