### ISSUE TITLE
There is an unexpected behavior on changing months

### ISSUE THREAD

**Issue by gatherheart** [wix/react-native-calendars#1202]
## Description

Environment: Expo 

Page changes when gesture is detected, and the index of page of FlatList changes when paging is applied.
That is, page index changes twice when swiping.

`
import React, { useEffect, useState } from "react";
import { ScrollView, View, Text, TouchableOpacity } from "react-native";
import { Calendar, CalendarList } from "react-native-calendars";

export default ({ navigation }) => {
  return (
    <CalendarList
      //testID={testIDs.calendarList.CONTAINER}
      //current={'2020-06-10'}
      style={{backgroundColor: "white" }}
      pastScrollRange={12}
      futureScrollRange={12}
      **horizontal**={true}
      **pagingEnabled**={true}
      onMonthChange={(month) => {
        console.log("month changed", month);
      }}
      onVisibleMonthChange={(month) => {
        console.log("month changed", month);
      }}
      onDayPress={(day) => {
        console.log("selected day", day);
      }}
      renderHeader={(date) => {
        const header = date.toString("MMMM yyyy");
        const [month, year] = header.split(" ");
        const textStyle = {
          fontSize: 18,
          fontWeight: "bold",
          paddingTop: 10,
          paddingBottom: 10,
          color: "#5E60CE",
          paddingRight: 5,
        };

        return (
          <View
            style={{
              flexDirection: "row",
              width: "100%",
              justifyContent: "space-between",
              marginTop: 10,
              marginBottom: 10,
            }}
          >
            <Text style={{ marginLeft: 5, ...textStyle }}>{`${month}`}</Text>
            <Text style={{ marginRight: 5, ...textStyle }}>{year}</Text>
          </View>
        );
      }}
      theme={{
        "stylesheet.calendar.header": {
          dayHeader: {
            fontWeight: "600",
            color: "#48BFE3",
          },
        },
        "stylesheet.day.basic": {
          today: {
            borderColor: "#48BFE3",
            borderWidth: 0.8,
          },
          todayText: {
            color: "#5390D9",
            fontWeight: "800",
          },
        },
      }}
    />
  );
};

`

## Expected Behavior

After swiping page, the next month should appear. However, the month after the next month appears.

## Observed Behavior

Before swiping

![image](https://user-images.githubusercontent.com/40990613/84740614-ae506800-afe8-11ea-96f2-8c9158f54719.png)

After swiping

![image](https://user-images.githubusercontent.com/40990613/84740679-c627ec00-afe8-11ea-80fc-ee4da81ac8f0.png)

Works oddly from e2a96901d53b0b0abcddc08da0c322222f4b3df3
Works fine with ebf2ea75d545f1f0cca85e53de5ef919246f26e2

**Comment by chenei** [comment]
Hi,
From version 1.298.0 we disabled the swipe by default. you can enable it by passing enableSwipeMonths.

I will open separate feature request to improve the swipe.

**Comment by Norcy** [comment]
same issue for me. Swipe experience is oddly
