### ISSUE TITLE
How to disable swipe right/left for changing months on Calendar.

### ISSUE THREAD

**Issue by TaraSinghDanu** [wix/react-native-calendars#1203]

**Comment by chenei** [comment]
Hi,
From version `1.298.0` we disabled the swipe by default. you can enable it by passing `enableSwipeMonths`.

**Comment by TaraSinghDanu** [comment]
I achieved this by

<GestureRecognizer
                    config={{
                        velocityThreshold: 0,
                        directionalOffsetThreshold: 0
                    }}>
                    <Calendar/>
</GestureRecognizer>

**Comment by imamabdulazis** [comment]
@TaraSinghDanu Where do you pass those components?

**Comment by LOGANLEEE** [comment]
still same what is wrong? doc does not match
