### ISSUE TITLE
Agenda calendar strip is not scrollable after upgrade.

### ISSUE THREAD

**Issue by Josh2941** [wix/react-native-calendars#1205]
## Description
The Calendar strip in the Agenda was scrollable vertically previously. But, after I upgraded React Native to 0.62.2 and react-native-calendars to 1.264.0, it stopped working.

![agenda](https://user-images.githubusercontent.com/34862136/85038130-da641880-b1a3-11ea-9455-a307455f0be5.PNG)

## Expected Behavior
The agenda calendar strip scroll should work as before.

## Observed Behavior
The agenda calendar strip scroll is not scrollable..

## Environment
react-native-calendars@1.264.0
react-native@0.62.2

**Comment by shamilovtim** [comment]
What you're describing was a bug. It wasn't supposed to scroll vertically and interfered with the downward swipe interaction.

**Comment by Josh2941** [comment]
Oh ok. Actually we got used to it by using it since it was very handy to scroll through next and previous weeks without opening the calendar. But if you plan to do this, it would be better if it stands correctly to the week when we scroll instead of scroll stopping randomly.
