### ISSUE TITLE
onDayPress incorrect timestamp

### ISSUE THREAD

**Issue by emmanuelfrancis** [wix/react-native-calendars#1206]
When I select a date using onDayPress I get below day object:
{"year":2020,"month":6,"day":19,"timestamp":1592524800000,"dateString":"2020-06-19"}

I used below code to create date object. I am on GMT-4 timezone
selectedDate = new Date(day.timestamp);
The date created is of 06/18. It looks like timestamp is returned of GMT time 12:00:00 AM
Instead of local timestamp.

**Comment by emilisb** [comment]
I cannot understand the issue here. Timestamps are always in UTC (GMT+00) timezone.

The timestamp results in `June 19, 2020 12:00:00 AM`, which is correct according to your object.

**Comment by eramudeep** [comment]
i am also facing something similar issue.
i  selected a previous date.
but it returns me the currnt month date 

Example :
i selected a date 5 from December 2020 
and it return me 5th of March 2022

**Unable to find the cause**
