### ISSUE TITLE
Advanced styling theme not changing when react-native-paper theme provider is changed

### ISSUE THREAD

**Issue by willaay96** [wix/react-native-calendars#1209]
## Description
I'm using react native paper themes, so the user can change between dark and normal color theme, however the theme prop only seems to get updated to the new colors after a full refresh. How can I get round this?

## Expected Behavior
Changed between light and dark themes, expected the calendars theme to change also.

## Observed Behavior
The calendar stays the same color and doesn't change to the new theme.

If there's an error message, please paste the *full terminal output and error message* in this code block:

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: `-- react-native-calendars@1.294.0
* `npm ls react-native`: `-- react-native@0.61.4

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

My calendar's code below, the 'colors' object is from react-native-paper.  When the theme is changed in react-native-paper it should update the colors here but doesn't until refreshed.

`const { colors } = useTheme();`

``` 
<Calendars.Calendar
            style={{
                height: '100%'
            }}
            theme={{
                indicatorColor: 'white',
                textDayFontSize: 16,
                textDayHeaderFontSize: 16,
                'stylesheet.calendar.header': {
                    header: {
                        backgroundColor: colors.primary,
                        flexDirection: 'row',
                        justifyContent: 'space-between',
                        paddingVertical: 35,
                        paddingLeft: 10,
                        paddingRight: 10,
                        marginTop: 6,
                        alignItems: 'center',
                        // borderRadius: 4
                    },
                    headerContainer: {
                        flexDirection: 'row',
                    },
                    monthText: {
                        fontSize: 24,
                        fontFamily: 'raleway-medium',
                        fontWeight: 'normal',
                        color: 'white',
                        margin: 10
                    },
                    dayContainer: {
                        backgroundColor: 'red'
                    },
                    dayHeader: {
                        marginTop: 10,
                        marginBottom: 15,
                        width: 33,
                        textAlign: 'center',
                        fontSize: 14.5,
                        fontFamily: 'raleway',
                        fontWeight: 'normal',
                        color: 'black',
                    },
                    arrowImage: {
                        tintColor: 'white'
                    }
                },
                'stylesheet.calendar.main': {
                    container: {
                        paddingHorizontal: 5,
                        backgroundColor: colors.background,
                    },
                    monthView: {
                        backgroundColor: colors.calendarMonthGrid,
                    },
                    week: {
                        marginTop: 20,
                        marginBottom: 20,
                        flexDirection: 'row',
                        justifyContent: 'space-around'
                    },
                },
                'stylesheet.day.single': {
                    today: {
                        backgroundColor: colors.accent
                    },
                    todayText: {
                        color: 'white',
                        fontWeight: 'bold',
                        fontSize: 19
                    },
                }
            }}
            current={currentMonth}
            onDayPress={day => viewDate(day)}
            monthFormat={'MMMM yyyy'}
            onMonthChange={month => changeMonth(month)}
            hideExtraDays={true}
            firstDay={1}
            markedDates={array}
            markingType={'custom'}
            displayLoadingIndicator={true}
        />
```

**Comment by emilisb** [comment]
Related to #982.

`theme` prop is more of "initial theme" prop. You can pass `key` prop to re-render the calendar. We will work on a better solution, but for now `key` prop looks like the only way.

**Comment by willaay96** [comment]
@emilisb is there any documentation I can read on the key prop and how to use it?

**Comment by emilisb** [comment]
@willaay96 `key` prop is a special React prop. It is mostly used in lists, but in the context of your issue, changing the `key` prop causes a force re-render of your component. It means that by changing `key` prop the calendar will use your new theme style :)

This comment includes an example: https://github.com/wix/react-native-calendars/issues/982#issuecomment-582526267

**Comment by willaay96** [comment]
@emilisb Perfect that has done it for me thank you!

**Comment by barbaragrinop** [comment]
> Related to #982.
> 
> `theme` prop is more of "initial theme" prop. You can pass `key` prop to re-render the calendar. We will work on a better solution, but for now `key` prop looks like the only way.

Worked for me. Thanksss

**Comment by barbaragrinop** [comment]
> @willaay96 `key` prop is a special React prop. It is mostly used in lists, but in the context of your issue, changing the `key` prop causes a force re-render of your component. It means that by changing `key` prop the calendar will use your new theme style :)
> 
> This comment includes an example: [#982 (comment)](https://github.com/wix/react-native-calendars/issues/982#issuecomment-582526267)

worked for me! thank you
