### ISSUE TITLE
Expandable calendar shows two rows when i remove header from calendar.

### ISSUE THREAD

**Issue by afanchamp** [wix/react-native-calendars#1211]
## Description

1-2 Expandable calendar shows two rows after collapsing, while header (including month name, arrows) are hidden.
![untitled](https://user-images.githubusercontent.com/44059218/85617955-7f399680-b679-11ea-9e5e-35082186c294.gif)

 Also i want to display dates like this in week view when calendar is collapsed, is it possible ? 
<img width="136" alt="Screenshot 2020-06-25 at 00 13 04" src="https://user-images.githubusercontent.com/44059218/85618064-a85a2700-b679-11ea-8f69-31e4f81f5c84.png">

This is the code i'm using 

 <CalendarProvider
                    date={ITEMS[0].title}
                    onDateChanged={this.onDateChanged}
                    onMonthChange={this.onMonthChange}
                    showTodayButton={false}
                    disabledOpacity={0.6}
                  
                    current={this.state.today}
             
                    
                >
                        <ExpandableCalendar
                            theme={{
                                'stylesheet.calendar.header': {
                                  header: {
                                    height: 0
                                  },
                                  
                                }
                              }}
                            selected={this.state.today}
                            hideArrows={true}
                            hideExtraDays={true}
                            hideDayNames={false}
                            showWeekNumbers={false}
                            hideKnob
                            initialPosition={ExpandableCalendar.positions.OPEN}
                               markedDates={this.getMarkedDates()} // {'2019-06-01': {marked: true}, '2019-06-02': {marked: true}, '2019-06-03': {marked: true}};

                        />
                    {/ } /}
                    <View style={styles.notesContainer}>
                    </View>
                  
                </CalendarProvider>

**Comment by skhizerabass** [comment]
Facing the similar issue in expandable view . Applied Height :0 to my header because i want to design my own header and now it shows two rows  the upper one doesn't even scroll it is fixed.
Need some help to resolve this issue

**Comment by frankA10019** [comment]
hello, any update?
