### ISSUE TITLE
is there a way to move month title to the left and use single letter on days?

### ISSUE THREAD

**Issue by johhansantana** [wix/react-native-calendars#1217]
Hello, I'm trying to achieve moving the months title in `CalendarList` to the left and making the days be a single letter instead of 3. Is there a way to achieve this using the calendar API?

**EDIT**
I was able to use a custom component in the months header using `renderHeader` but I can't seem to find something similar for the days.

**Comment by KristineTrona** [comment]
@johhansantana You can overwrite it with LocaleConfig:

```
  LocaleConfig.locales[''] = {
    ...LocaleConfig.locales[''],
    dayNamesShort: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  };
```

**Comment by Yandamuri** [comment]
@KristineTrona This is awesome. This resolved my issue. I tried to give locale as per documentation like this

        LocaleConfig.locales['default'] = {
               dayNamesShort: ['SUN','MON','TUE','WED','THU','FRI','SAT']
        };
       LocaleConfig.defaultLocale = 'default'; 

But it gave following error

[Cannot convert undefined value to an object #1418](https://github.com/wix/react-native-calendars/issues/1418)

May I know what's wrong with my code?
