### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by anabahena** [wix/react-native-calendars#1220]
Ya agregue el localeConfig y aún así no se soluciona.

    LocaleConfig.locales['mx'] = {
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado',],
        dayNamesShort: ['DOM', 'LUN', 'MAR', 'MIÉ', 'JUE', 'VIE', 'SAB'],
        today: 'Hoy'
    };
    LocaleConfig.defaultLocale = 'mx';

![WhatsApp Image 2020-07-03 at 2 06 12 PM](https://user-images.githubusercontent.com/51386392/86493264-7f4f2b80-bd36-11ea-8073-e1a78233bcfb.jpeg)

**Comment by chenei** [comment]
I think that you must declare `monthNamesShort`.
