### ISSUE TITLE
How to reduce spacing between arrows in <Calendar  />  ?

### ISSUE THREAD

**Issue by luvnish19** [wix/react-native-calendars#1221]
<img width="264" alt="Screenshot 2020-07-06 at 3 07 35 PM" src="https://user-images.githubusercontent.com/15010312/86579089-7363a380-bf9a-11ea-8190-a1a3b988909a.png">

Requirement is to reduce space. Which prop we will use for this?
I will be very grateful if someone answer this asap

**Comment by luvnish19** [comment]
Is there any fix for this?

**Comment by chenei** [comment]
The **Calendar** component can receive `theme` prop. you can pass the follow:

` theme={{
            'stylesheet.calendar.header': {
              header: {
                flexDirection: 'row',
                justifyContent: 'space-between',
                paddingLeft: 100,
                paddingRight: 100,
                marginTop: 6,
                alignItems: 'center'
              }
            }
          }}`
