### ISSUE TITLE
Adding shadow in header

### ISSUE THREAD

**Issue by archansel** [wix/react-native-calendars#1227]
## Description

I'm looking for a way to add shadow in header

## Expected Behavior
![Screen Shot 2020-07-12 at 15 30 44](https://user-images.githubusercontent.com/816817/87242206-bdde9780-c454-11ea-93ee-b81bbceb5578.png)

## Observed Behavior

I tried adding shadow to knobContainer but it being cut by `overflow: hidden' in header style

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.300.0
* `npm ls react-native`: 0.61.5

Also specify:

1. iOS Simulator & version: iPhone 11 iOS 13.5

**Comment by ruswerner** [comment]
I tried to hack around and get this to work but it's challenging because that header is actually a `<CalendarList/>` component that is obscured and absolutely positioned in realtime. The overflow is hidden because the full calendar list would show if it wasn't. Let me know if you figure it out!

**Comment by chenei** [comment]
We have shadow on the expandable calendar component.
If you like to have it on the Agenda itself, you can contribute. for now i don't see a solution on how to add it.
