### ISSUE TITLE
Expandable calendar knob can be pulled further than the calendar height

### ISSUE THREAD

**Issue by KristineTrona** [wix/react-native-calendars#1230]
## Description

When pulling down the expandable calendar the knob gets separated from the calendar view:

<img width="264" alt="Screenshot 2020-07-14 at 15 24 43" src="https://user-images.githubusercontent.com/39855778/87431417-e5fe0000-c5e6-11ea-9ebf-be276eb90174.png">

## Expected Behavior

To not see whitespace seperating the knob from the calendar.

**Comment by chenei** [comment]
Hi @KristineTrona,
I can't reproduce the issue. can you please provide library version and steps to reproduce?

**Comment by chenei** [comment]
By the way, your build on the PR is failing.

**Comment by KristineTrona** [comment]
@chenei 

I've just tested it and the issue still persists. I've created a fresh project with:
 - react-native: v0.63.2
- react-native-calendars: v1.301.0

Code:

```
import React from 'react';
import {SafeAreaView} from 'react-native';
import {ExpandableCalendar, CalendarProvider} from 'react-native-calendars';

const App = () => {
  return (
    <SafeAreaView style={{backgroundColor: 'pink', flexGrow: 1}}>
      <CalendarProvider date={'2020-07-31'} onDateChanged={() => {}}>
        <ExpandableCalendar hideArrows firstDay={1} allowShadow={false} />
      </CalendarProvider>
    </SafeAreaView>
  );
};

export default App;

```

**Comment by KristineTrona** [comment]
My PR was not entirely fixing the issue, so a better solution needs to be found.

**Comment by wanxue0804** [comment]
> Hi @KristineTrona,
> I can't reproduce the issue. can you please provide library version and steps to reproduce?

IOS

**Comment by frankA10019** [comment]
same issue on iOS.
