### ISSUE TITLE
ExpandableCalendar disable date not working

### ISSUE THREAD

**Issue by tamdao** [wix/react-native-calendars#1232]
I have tried to you use `ExpandableCalendar` with minDate and `markedDates` with `{disabled: true }` and `disableAllTouchEventsForDisabledDays`. But it not working, I still can select the date

**Comment by RazaShehryar** [comment]
I am having a similar issue where minDate and maxDate isn't working on Week View. When the calendar is expanded, it is working fine.

**Comment by chenei** [comment]
You right!

pushed a fix - https://github.com/wix/react-native-calendars/commit/3f4170335e7f725b0b46c950be7a300984bce6f4

**Comment by tamdao** [comment]
@chenei I found another issue. When I change the week by prev/next button, the select date will be select the first date of week, but the date is disabled

**Comment by tamdao** [comment]
@chenei Your fix is not working. I still can select the disabled date

**Comment by chenei** [comment]
please remove your node modules and reinstall again.
check that you installed the latest version, 1.301.0.

**Comment by tamdao** [comment]
@chenei Yes, I have installed v1.301.0

Here my code:

```
<ExpandableCalendar
          key={uiStore.resolvedTheme}
          date={props.date}
          disablePan
          hideKnob={props.hideKnob}
          allowShadow={false}
          theme={uiStore.resolvedTheme === "dark" ? DARK_CALENDAR : LIGHT_CALENDAR}
          markedDates={props.markedDates}
          markingType={"multi-dot"}
          minDate={new Date()}
          disableAllTouchEventsForDisabledDays
        />
```

**Comment by chenei** [comment]
I am not sure what to say, I can't reproduce it locally.

I run our example with ExpandableCalendar, and I can't click on disabled dates.

**Comment by tamdao** [comment]
@chenei Thanks for you response. How about the prev week btn?

**Comment by chenei** [comment]
I think someone just opened an issue about it.
https://github.com/wix/react-native-calendars/issues/1247

we need to take into consideration the `minDate`.

**Comment by gerahrios** [comment]
Is it possible to block the expansion of the calendar and only show the weekly view?

**Comment by aleksandarbos** [comment]
> Is it possible to block the expansion of the calendar and only show the weekly view?

consider using `WeekCalendar` component
