### ISSUE TITLE
How to pass holiday data to calendar and change background/date color for holidays?

### ISSUE THREAD

**Issue by sagarhspl** [wix/react-native-calendars#1237]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I have a  array of holidays based on year and actually need to shown in calendar along with event data.

Is there any option or solution to pass the holidays data to calendar and change the dates number color change ?

## Expected Behavior

Need to pass Holiday array to calendar along with event data and change calendar dates color change for particular holidays date.

Thanks in advance.

**Comment by belgamo** [comment]
I think you can use custom marks. Check [this section](https://github.com/wix/react-native-calendars#date-marking).

**Comment by chenei** [comment]
Thanks @belgamo 

@sagarhspl please go over the docs. you also can go over the examples.
If something still isn't clear, please let us know.
