### ISSUE TITLE
How do I get the selected day background to center on the date?

### ISSUE THREAD

**Issue by ryanvanderpol** [wix/react-native-calendars#124]
See this screenshot:

<img width="559" alt="screenshot 2017-08-01 19 19 56" src="https://user-images.githubusercontent.com/1936460/28851110-836365b0-76ee-11e7-9aeb-d95646874ed7.png">

The selected date background is circular, but it is offset from the date.  I assume this is because when a day is "marked" the dot appears under the number and then the selected background state is centered around the whole thing, but when I'm not using that, how do I get it to center properly?

**Comment by tautvilas** [comment]
Currently there is no way to center, but this might be fixed later.

**Comment by tautvilas** [comment]
Currently you can hack this with advanced styling options:
```
theme={{
  'stylesheet.day.basic': {
    text: {
      marginTop: 4, // specify the margin you want
      ...otherTextStyles
    }
  }
}}
```

**Comment by nkov** [comment]
This fix doesn't work anymore, I assume the only way is to render a custom day component.

**Comment by bekatd** [comment]
@Inbal-Tish why is there no way to center it?
