### ISSUE TITLE
Programatically change month?

### ISSUE THREAD

**Issue by Stas-Buzunko** [wix/react-native-calendars#1245]
## Description

Changing current prop doesn't trigger month change. Is there any other way to change month programatically?

* `npm ls react-native-calendars`: react-native-calendars@1.300.0
* `npm ls react-native`: react-native@0.60.5

**Comment by Stas-Buzunko** [comment]
https://github.com/wix/react-native-calendars/issues/1196#issuecomment-652636444

**Comment by JeffAbney** [comment]
@Stas-Buzunko This solution doesn't work for <Calendar/>, only for <CalendarList/>. Anyone know how to programmatically jump to a month in <Calendar/>? Setting the current prop doesn't trigger a re-render.

**Comment by glushkina1** [comment]
Same issue.
How to jump to a month if I have a new Date ?

**Comment by glushkina1** [comment]
@JeffAbney @Stas-Buzunko @RushitaBacancy 
Have you found out how to solve this issue? Thanks!
