### ISSUE TITLE
Question: CalendarList scroll week only

### ISSUE THREAD

**Issue by TheTalonHughes** [wix/react-native-calendars#1249]
## Description
I wanted to know if it was possible to have a `<CalendarList />` that displays only 1 week but that week is scrollable horizontally (scrolling only changes the week and not the whole month) and also have the month/year like the `<Calendar />` at the top so when the arrows are pressed, they go to the first week of the next month.

I currently have a very simple `<CalenderList />` implemented like so:

```
<CalendarList
  horizontal
  pagingEnabled
  hideArrows={false}
  calendarWidth={calendarWidth}
  theme={CALENDAR_THEME}
/>
```

**Comment by maartenvandillen** [comment]
Also looking for this. Did you find any solution?

**Comment by sn4f** [comment]
Me too

**Comment by DonOzOn** [comment]
<CalendarProvider
                                date={this.state.selectedDate.dateString}
                                onDateChanged={this.onDateChanged}
                                markedDates={{
                                    ...this.state.markedDates,
                                    [this.state.selectedDate.dateString]: {
                                        selected: true,
                                    },
                                }}
                            >
                                <WeekCalendar
                                    hideDayNames={true}
                                    firstDay={1}
                                    dayComponent={this.renderDateWeek}
                                    theme={calendarThemes}
                                    calendarWidth={screenWidth}
                                    allowShadow={false}
                                    markedDates={{
                                        ...this.state.markedDates,
                                        [this.state.selectedDate.dateString]: {
                                            selected: true,
                                        },
                                    }}
                                    pastScrollRange={(new Date().getFullYear() - 1900) * 12}
                                    futureScrollRange={(2099 - new Date().getFullYear()) * 12}
                                    style={[styles.calendar, { paddingBottom: 20, paddingLeft: 0, paddingRight: 0 }]}
                                />
