### ISSUE TITLE
 How to place items in React-Native-Calendars?

### ISSUE THREAD

**Issue by gerahrios** [wix/react-native-calendars#1252]
## Description

I try to place my items but it only shows me the numbers in blue on the left side

Also specify:

1. Emulador iphone xs-Max 12.1

## Reproducible Demo

`const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
            <View style={styles.sectionContainer}>
            <Agenda
              markedDates={{
                '2020-08-04': {
                  periods: [
                    {startingDay: false, endingDay: true, color: '#5f9ea0'},
                  ]
                },
                '2020-08-05': {
                  periods: [
                    {startingDay: true, endingDay: false, color: '#ffa500'},
                    {color: 'transparent'},
                  ]
                }
              }}
              // Date marking style [simple/period/multi-dot/custom]. Default = 'simple'
              markingType='multi-period'
              // the list of items that have to be displayed in agenda. If you want to render item as empty date
              // the value of date key kas to be an empty array []. If there exists no value for date key it is
              // considered that the date in question is not yet loaded
              items={
                {'2020-08-04': [{text: 'item 1 - any js object'}],
                 '2020-08-05': [{text: 'item 2 - any js object'}],
                 '2020-08-06': [{text: 'item 3 - any js object'}],
                 '2020-08-07': [{text: 'item 4 - any js object'}],
                 '2020-08-08': [{text: 'item 5 - any js object'},{text: 'any js object 2'}],
                }}
              // callback that gets called when items for a certain month should be loaded (month became visible)
              loadItemsForMonth={(month) => {console.log('trigger items loading')}}
              // callback that gets called on day press
              onDayPress={(day)=>{console.log('day pressed')}}
              // callback that gets called when day changes while scrolling agenda list
              onDayChange={(day)=>{console.log('day changed')}}
              /*theme = {{
                ...agenda,
                agendaDayTextColor = 'yellow',
                agendaDayNumColor = 'green',
                agendaTodayColor = 'red'
              }}*/
              // agenda container style
              style = {{}}
              theme={{
                  backgroundColor: '#ffffff',
                  calendarBackground: '#ffffff',
                  textSectionTitleColor: '#0a8f50',
                  textSectionTitleDisabledColor: '#d9e1e8',
                  selectedDayBackgroundColor: '#0a8f50',
                  selectedDayTextColor: '#ffffff',
                  todayTextColor: '#000',
                  dayTextColor: '#2d4150',
                  textDisabledColor: '#d9e1e8',
                  dotColor: '#00adf5',
                  selectedDotColor: '#000',
                  arrowColor: 'orange',
                  disabledArrowColor: '#d9e1e8',
                  monthTextColor: '#0a8f50',
                  indicatorColor: '#028c4b',
                  /*textDayFontFamily: 'monospace',
                  textMonthFontFamily: 'monospace',
                  textDayHeaderFontFamily: 'monospace',*/
                  textDayFontWeight: '300',
                  textMonthFontWeight: 'bold',
                  textDayHeaderFontWeight: '300',
                  textDayFontSize: 16,
                  textMonthFontSize: 16,
                  textDayHeaderFontSize: 16,
                  height: 800
                }}
            />         
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};`
![Captura de pantalla 2020-08-05 a la(s) 09 25 10](https://user-images.githubusercontent.com/43283646/89432104-f42ed000-d6fd-11ea-8482-293bb5ce5bee.png)

**Comment by emilisb** [comment]
Please read Agenda docs here: https://github.com/wix/react-native-calendars#agenda

Example usage: https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js
