### ISSUE TITLE
Using a redux store value for markedDates not working

### ISSUE THREAD

**Issue by AvneeshD** [wix/react-native-calendars#1257]
This is my store

![Screenshot 2020-08-07 at 16 54 00](https://user-images.githubusercontent.com/51121821/89641233-df556680-d8ce-11ea-8caa-4911a416e5bb.png)

this is my code

![Screenshot 2020-08-07 at 16 57 16](https://user-images.githubusercontent.com/51121821/89641336-13c92280-d8cf-11ea-8b29-c71a6b3a3289.png)

no dates are getting marked

**Comment by AvneeshD** [comment]
Guys, can anyone help me with this?

**Comment by belgamo** [comment]
We need to know what the error you are getting... Update the issue description.

**Comment by AvneeshD** [comment]
> We need to know what the error you are getting... Update the issue description please.

I have opened a new issue with more comprehensive info https://github.com/wix/react-native-calendars/issues/1271#issue-679974215 I will close this issue please help me with the issue there @belgamo
