### ISSUE TITLE
What's the update condition?

### ISSUE THREAD

**Issue by sduqlsc** [wix/react-native-calendars#127]
First, it's an awesome project!

I found that the control not always update as state changed, but it would update selected status if changing month, so what's the update condition or is there any method to force updating control?

if comment `this.shouldComponentUpdate = shouldComponentUpdate;` in the `calendar\index.js`, it would update if component state changes.

anyway, i want to know why override `shouldcomponentupdate`  method?

**Comment by tautvilas** [comment]
Hi, shouldComponentUpdate is implemented in order to minimize rerenders and make calendar more performant. Can you give me example code snippet so that I could reproduce your problem easily?

**Comment by sduqlsc** [comment]
@tautvilas wait a min....

**Comment by sduqlsc** [comment]
BTW,  `console.log(shouldUpdate.field, shouldUpdate.update);` outputs `undefined false` in the second state update. @tautvilas

**Comment by tautvilas** [comment]
You are not treating `markedDates` as immutable. Since the reference of `markedDates` does not change update condition is not triggered. Use this whenever you change `markedDates`:

`this.viewData.markedDates = Object.assign({}, this.viewData.markedDates);`

**Comment by sduqlsc** [comment]
@tautvilas thanks for the solution, i think it's better to point out in the wiki.

**Comment by tautvilas** [comment]
Yes, I added to Readme, thx

**Comment by mharrisweb** [comment]
Hi, 

I have the same problem I am updating my `markedDates`:


    loadItems(dates) {
        const { events } = this.props;

        const startDate = new Date(dates[0].year, dates[0].day, dates[0].month),
            endDate = new Date(dates[2].year, dates[2].day, dates[2].month),
          

        const newEvents = events.filter(date => { 
            moment()
                .range(startDate, endDate)
                .contains(date);
        });

        this.setState({
            markedDates: { ...newEvents, this.state.markedDates }
        });
    }

```
 return (
            <CalendarList
                style={styles.calendar}
                markingType={"multi-dot"}
                onVisibleMonthsChange={this.loadItems}
                onDayPress={this.onDayPress}
                maxDate={"2019-12-19"}
                markedDates={this.state.markedDates}
                pastScrollRange={-1}
                futureScrollRange={12}
                scrollEnabled={true}
                showScrollIndicator={true}
            />
        );
```

@tautvilas Any ideas how I can get it to update?
