### ISSUE TITLE
Calendar dates not getting marked

### ISSUE THREAD

**Issue by AvneeshD** [wix/react-native-calendars#1271]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I want to render marked dates sent from the backend

## Expected Behavior

I used the markedDates prop to assign the object returning from the backend

## Observed Behavior

There is no error, just that the dates aren't getting marked

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.244.0 
* `npm ls react-native`: react-native@0.62.2 

Also specify:

1. Phone/emulator/simulator & version: iPhone 11 simulator and pixel 3a, doesn't work on any simulators I have tried

## Reproducible Demo

![Screenshot 2020-08-17 at 11 41 03](https://user-images.githubusercontent.com/51121821/90363279-09054f00-e080-11ea-82d8-2b0d9095e419.png)

This is the screenshot of the object returned from the backend

![Screenshot 2020-08-17 at 11 41 32](https://user-images.githubusercontent.com/51121821/90363333-289c7780-e080-11ea-9a52-9b16e13a3f19.png)

and this is the code to render the calendar

**Comment by Nehal-29** [comment]
@AvneeshD were you able to update marked dates?
In this library it is mentioned 
**Disclaimer: Make sure that markedDates param is immutable. If you change markedDates object content but the reference to it does not change calendar update will not be triggered.**

I want to update calendar object,
How can I do that?

**Comment by abhilashdhone** [comment]
> @AvneeshD were you able to update marked dates?
> In this library it is mentioned
> **Disclaimer: Make sure that markedDates param is immutable. If you change markedDates object content but the reference to it does not change calendar update will not be triggered.**
> 
> I want to update calendar object,
> How can I do that?

was you able to work it, i am trying so hard and yes i read that statement. i am not able to change initial marked dates once they r set
