### ISSUE TITLE
Support for Arabic numerals when localizing the Calendar

### ISSUE THREAD

**Issue by ilyagru** [wix/react-native-calendars#1272]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Is there a way to localize numbers as well without e.g. reimplementing the whole day component? Arabic has non-latin numbers: `٠١٢٣٤٥٦٧٨٩`, month and day names work great. Maybe you have some workarounds in mind?

## Expected Behavior

Localize the Calendar to Arabic.

## Observed Behavior

Numeric values are not localized.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.302.0 
* `npm ls react-native`: react-native-calendars@0.63.2

Also specify:

1. Phone/emulator/simulator & version: iPhone 11, iOS Simulator, iOS 13.6.

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

![unlocalized-numerics](https://user-images.githubusercontent.com/18074511/90506499-aaf66b80-e154-11ea-8f2f-f1f51a36d5b2.png)

```tsx
// Using moment locale data for the config
['en', 'ar'].forEach((locale) => {
  RNCalendarsLocaleConfig.locales[locale] = {
    monthNames: moment.localeData(locale).months(),
    monthNamesShort: moment.localeData(locale).monthsShort(),
    dayNames: moment.localeData(locale).weekdays(),
    dayNamesShort: moment.localeData(locale).weekdaysMin(),
  }
})

<Calendar
  firstDay={6}
  minDate={moment().format(MomentFormat.SystemDate)}
  current={date}
  onDayPress={this.onPressDay}
   onDayLongPress={this.onPressDay}
  markedDates={{
    [date]: { selected: true },
  }}
  theme={calendarTheme}
/>
```

**Comment by DanielMalak** [comment]
this is a needed feature

**Comment by Haseeba393** [comment]
I have tried the same thing but nothing is showing me in Arabic language.

**Comment by Hatta-Food-Hub** [comment]
for me, the calendar is not showing
![Screenshot_1724147181](https://github.com/user-attachments/assets/48dc9045-9cba-44f4-8882-291ed6c7e3ff)
