### ISSUE TITLE
Header agenda not rendering properly after screen orientation changes

### ISSUE THREAD

**Issue by JamesHawken** [wix/react-native-calendars#1278]
Hello,
 thank you for this great library! I've been making an application thanks to the Agenda component. It really works great except for 1 problem: Whenever I switch from portrait to landscape (or vice versa), the calendar header(above the knob) is no longer rendered correctly. It seems to go out of sync for some reason. If you have any ideas, it would be greatly appreciated, thank you.
PS: If I put the Agenda component in a View component where I set a fixed height manually, the problem dissapears, however I can't make the app responsive by doing so 

I made a screen and rendered the Agenda component as follows. This agenda is in a bottom tab navigator which is in a stack navigator.

  <Agenda
        //style={styles.agenda}
     
        //hideExtraDays={true}
        showWeekNumbers={true}
        firstDay={1} //Commencer la semaine lundi plutôt que dimanche
        keyExtractor={(item, index) => index.toString()}
        items={this.state.items}
        //  selected={formatDate(new Date())}
        renderItem={this.renderItem.bind(this)}
        renderEmptyDate={this.renderEmptyDate.bind(this)}
        rowHasChanged={this.rowHasChanged.bind(this)}
      />

## Environment
React native 0.63, Windows 7, Android 10 on a Oneplus 6

Thank you again,

James

**Comment by diegomichell** [comment]
I have the same problem, but even without changing orientation, sometimes the header is cut up, just renders to the middle,  it only happens to me on iOS and randomly.

**Comment by diegomichell** [comment]
Any updates?

**Comment by JamesHawken** [comment]
> Any updates?

For the problem I encountered, there was a hacky fix that sorted it. If I remember correctly, it was to change the behaviour of a listener and force it to load the day properly. I'm afraid I don't have Access to the code anymore.

But I think our bug might be different because the bug I have happens on Android

**Comment by chismadalina** [comment]
Any update on this?
