### ISSUE TITLE
Starting day and ending day do not render correctly when month changes

### ISSUE THREAD

**Issue by iamacoderguy** [wix/react-native-calendars#1279]
## Description

The codes are as simple as the following.
The starting day and ending day are rendered correctly for 22 Oct and 23 Oct. 
However, when I press the right arrow to go to November, the day 22nd, 23rd in November are rendered without any border-radius.

When I changed the current to November. The November days rendered correctly, but again, the October days didn't render the border-radius.

```
<Calendar
     current={new Date(2020, 9, 1)}
     markedDates={{
          '2020-10-22': { startingDay: true, color: 'green' },
          '2020-10-23': { endingDay: true, color: 'green' },
          '2020-11-22': { startingDay: true, color: 'green' },
          '2020-11-23': { endingDay: true, color: 'green' },
     }}
     markingType={'period'}
/>
```

## Expected Behavior

![Image 1](https://drive.google.com/uc?export=view&id=15f-1GyOYS7lRg7Pw1hOkkgQElsAS2Rbt)
https://drive.google.com/uc?export=view&id=15f-1GyOYS7lRg7Pw1hOkkgQElsAS2Rbt

## Observed Behavior

![Image 2](https://drive.google.com/uc?export=view&id=1j5I3HCxq7Oi2OhG3HVsXEo9c9ajPFFHN)
https://drive.google.com/uc?export=view&id=1j5I3HCxq7Oi2OhG3HVsXEo9c9ajPFFHN

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.315.0
* `npm ls react-native`: react-native@0.62.2

Also specify:

1. Phone/emulator/simulator & version: Emulator Pixel_2_API_23 Android 6.0, API 23

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by pcnascimento** [comment]
Same problem here

**Comment by ajota-admios** [comment]
+1

**Comment by MichaelKim39** [comment]
+1

**Comment by rishabh1608** [comment]
+1
