### ISSUE TITLE
Add button to bottom left corner to close agenda instead of just depending on selection of date.

### ISSUE THREAD

**Issue by s-shiva1995** [wix/react-native-calendars#128]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

I want to add a button to agenda which closes it instead of just selecting a date.

## Expected Behavior

What action did you perform, and what did you expect to happen?

I wanted to close agenda without selecting a new date.

## Observed Behavior

What actually happened when you performed the above actions?

No error there is no option as such

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by tautvilas** [comment]
hi, please create issue according to template
