### ISSUE TITLE
Jump to Month in Calendar

### ISSUE THREAD

**Issue by benni2108** [wix/react-native-calendars#1280]
Hello.
In Calendar-List there is the function scrollToDay which I can use to swipe to a specific month with the program.
Is there a similar function for Calendar or what is the best way to provide this action?
Yours

**Comment by canerkaynar** [comment]
I spent lots of time solve that but the month does not move. Misfire!

**Comment by AhmedRazaVerge** [comment]
you can use [current] props. what ever month you pass it move to this month. you can pass a state in current props.and when you want to change the month just change month in state it auto move to that month.

**Comment by canerkaynar** [comment]
In my scenario, I choose a date from CalendarList, When I press the date, the app comes back to Calendar. The position of the day is correct, the month is not. It is still September, expecting it moves to October. If I change it manually, there is the day I want to select. The opposite scenario works well, from Calendar to CalenderList. 👍  It starts from the correct month and day 💯

**Comment by Usamaliaquat123** [comment]
@canerkaynar @benni2108  use **current** prop to move 2012-03-01 on the **march** example 

`current={'2018-04-01'}`

or you can use **moment**  if its un formated

**Comment by orlovcs** [comment]
@Usamaliaquat123 

The documentation for that prop states: 
```javascript
<Calendar
  // Initially visible month. Default = Date()
  current={'2012-03-01'}
/>
``` 
In my scenario, setting a hard coded date for this prop does successfully display the correct month for this date however the component does not respond when this value changes hereafter.

**Comment by badwolf1686** [comment]
@orlovcs 

I got the same problem when implementing 'Today' button. With RN Debugger, I found that only **props.current** changes accordingly but **state.currentDate** does not. I think that's why there is no re-rendering of the component.

I found this issue can be a solution #764 using **ref** and **Calendar.addMonth()**. Just need to keep track of the on-screen date/month to calculate the month difference for **Calendar.addMonth()**.

**Comment by imcvsingh** [comment]
I got the same problem as I am not able to load a particular month on the button press. Does somebody have any solution?

**Comment by orlovcs** [comment]
> @orlovcs
> 
> I got the same problem when implementing 'Today' button. With RN Debugger, I found that only **props.current** changes accordingly but **state.currentDate** does not. I think that's why there is no re-rendering of the component.
> 
> I found this issue can be a solution #764 using **ref** and **Calendar.addMonth()**. Just need to keep track of the on-screen date/month to calculate the month difference for **Calendar.addMonth()**.

That sounds great, thanks @badwolf1686

**Comment by sanyamk30** [comment]
> you can use [current] props. what ever month you pass it move to this month. you can pass a state in current props.and when you want to change the month just change month in state it auto move to that month.
> like
> state=2012-03-01
> it show the 3rd moth of 2012
> when you change state=2018-04-01 it show the 4th month of 2018

It's not happening. When i change the value of current, the calendar doesn't re render, it doesn't change.

**Comment by oregev** [comment]
Any updates on this issue?
Can't seem to implement a change in the current prop.

**Comment by oregev** [comment]
SOLVED: 
1. Download [XDate](https://arshaw.com/xdate/) and add it to the project.
2. import to the file where you use the calendar with `import xdate from 'src/packages/xdate';`
3. Set a ref to the calendar component.
     `<Calendar ref={calendarRef} ... />`
4. Update **GoToToday** with:
`caledarRef.current?.updateMonth(XDate(), true);`
5. Enjoy jump to current date.

**Comment by AngelGayoung** [comment]
It's not in the github property description in the body, but when you open the calendar index file there is an initialDate property. Changing that value will change the calendar to the changed date! (The calendar moves)

**Comment by Mahdi-Farahani** [comment]
Hi guys I fixed it and I change the current month with this approach 👍   

` 
let calendarDate = moment();

 const onPressArrowLeft = () => {
    calendarDate = calendarDate.add(-1, 'month');
    setCurrentDate(calendarDate.format('YYYY-MM-DD'));
  };

  const onPressArrowRight = () => {
    calendarDate = calendarDate.add(1, 'month');
    setCurrentDate(calendarDate.format('YYYY-MM-DD'));
  };


<Calendar
          initialDate={currentDate}
/>
`

just you should put the current date state on initialDate Props

**Comment by gerwim** [comment]
@Mahdi-Farahani Thanks! This works.

Descriptions of each field:

`current`: Initially visible month
`initialDate`: Initially visible month. If changed will initialize the calendar to this value

So I'd expect the `initialDate` doing the exact opposite and so should `current` :).

**Comment by Ajmal0197** [comment]
Custom Header code:
 ```
 import React, { useState } from 'react';
import {
  SafeAreaView,
  StyleSheet,
  View,
  Modal,
  Button,
  Text,
  TouchableOpacity,
} from 'react-native';
import { Calendar } from 'react-native-calendars';
import moment from 'moment';
import { ChevronLeft, ChevronMMYY, ChevronRight, TopThreenLines } from '../../assets/svg';
import { fontSize } from '../../helpers/fonts';
import { hitSlop } from '../../helpers/helper';

// REF: https://morioh.com/a/026cbeaeb2a3/various-customizable-react-native-calendar-components
// https://medium.com/vectoscalar/setup-calendar-in-a-react-native-project-e0316341ec29
function DatePicker({ visible, onDateSelected }) {
  const [currentDate, setCurrentDate] = useState(moment());

  const goPrevMonth = () => {
    setCurrentDate((prev) => moment(prev).subtract(1, 'month').format('YYYY-MM-DD'));
  };

  const goNextMonth = () => {
    setCurrentDate((prev) => moment(prev).add(1, 'month').format('YYYY-MM-DD'));
  };

  const renderHeader = (date) => (
    <View style={styles.calenderHeaderWrapper}>
      <View style={styles.monthYearTextView}>
        <Text style={{ fontSize: fontSize.font16 }}>{moment(currentDate).format('MMMM YYYY')}</Text>
        <ChevronMMYY />
      </View>

      <View style={styles.chevrons}>
        <TouchableOpacity hitSlop={hitSlop} onPress={goPrevMonth}>
          <ChevronLeft />
        </TouchableOpacity>
        <TouchableOpacity hitSlop={hitSlop} onPress={goNextMonth}>
          <ChevronRight />
        </TouchableOpacity>
      </View>
    </View>
  );

  const onMonthChange = (date) => {
    setCurrentDate((prev) => moment(date?.dateString) || prev);
  };

  return (
    <Modal visible={visible} transparent animationType="fade">
      <View style={styles.overlay}>
        <View style={styles.modalWrapper}>
          <View style={styles.threeLinesTop}>
            <TopThreenLines />
          </View>
          <Calendar
            initialDate={moment(currentDate).format('YYYY-MM-DD')}
            onDayPress={onDateSelected}
            enableSwipeMonths
            hideArrows
            renderHeader={renderHeader}
            onMonthChange={onMonthChange}
          />
        </View>
      </View>
    </Modal>
  );
}

function DigitalId() {
  const [modalVisible, setModalVisible] = useState(false);

  return (
    <SafeAreaView style={styles.container}>
      <Button title="Show Modal" onPress={() => setModalVisible(true)} />
      <DatePicker visible={modalVisible} onDateSelected={(e) => console.log(JSON.stringify(e))} />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  overlay: {
    flex: 1,
    justifyContent: 'center',
    padding: 40,
    backgroundColor: 'rgba(100, 100, 100, 0.6)',
  },
  calenderHeaderWrapper: {
    backgroundColor: 'pink',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  monthYearTextView: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  chevrons: {
    flexDirection: 'row',
    gap: 20,
  },
  modalWrapper: { backgroundColor: 'white', paddingVertical: 20, borderRadius: 20 },
  threeLinesTop: { zIndex: 1, position: 'absolute', right: 20 },
});

export default DigitalId;

 ```
