### ISSUE TITLE
What is going on with these releases? Changelog?

### ISSUE THREAD

**Issue by juanjsebgarcia** [wix/react-native-calendars#1285]
**59** _PATCH_ releases in the past 24 hours? No changelog? I get this is OSS, but you're making it very difficult to use this package.

Can we please slow down with the releases, and get an actual changelog?

**Comment by juanjsebgarcia** [comment]
Not stale - issue persists

**Comment by pnthach95** [comment]
All new releases have same commit ID. Looks like automatic release task is broken.
