### ISSUE TITLE
Agenda View Broken

### ISSUE THREAD

**Issue by devchris** [wix/react-native-calendars#1292]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When passing in the items with the following format (according to the documentation this is how you should do it) it breaks:
```
{ '2020-09-20': [{ start: dateObject, end: dateObject, name: 'test', other: 'test' }] }
```
<img width="474" alt="Screen Shot 2020-09-20 at 11 20 26 AM" src="https://user-images.githubusercontent.com/15280263/93708018-4a7f9300-fb33-11ea-8c57-8765f95ce88b.png">

## Expected Behavior

Not to return that error message. When hitting the dismiss button, everything works as expected but this is an incredible annoying development process.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
JSON value '(
)' of type NSMutableArray cannot be converted to NSString

+[RCTConvert NSString:]
    RCTConvert.m:59
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.101
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.102
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2
RCTPerformBlockWithLogFunction
RCTPerformBlockWithLogPrefix
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke
__37-[RCTComponentData setProps:forView:]_block_invoke
__NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
-[RCTComponentData setProps:forView:]
__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.423
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.489
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: ^1.403.0
* `npm ls react-native`:0.63.2

Also specify:

1. Phone/emulator/simulator & version: iPhone 11 / xcode simulator

## Reproducible Demo
Just create an Agenda Calendar and pass in items in the format the documentation provides it:
```
{ '2020-09-20': [{ start: dateObject, end: dateObject', name: 'test', other: 'test' }] }
```

**Comment by freshedgarT** [comment]
`...start: dateObject, end: dateObject', ...`
seems like typo. you have a `'` behinde `end: dateObject'`

**Comment by devchris** [comment]
@freshedgarT that was just a typo in here. It also errors out with a valid date object

**Comment by appinteractive** [comment]
Different message but also broken after Update to React Native 0.63

<img width="900" alt="grafik" src="https://user-images.githubusercontent.com/432828/94926147-9a117780-04c0-11eb-9184-a4a7f34f08b7.png">

**Comment by appinteractive** [comment]
Seems there was an issue with other packages that caused this. Had to run 'expo upgrade' again and it was fixed.
