### ISSUE TITLE
unable to select marked date

### ISSUE THREAD

**Issue by KevinVladG** [wix/react-native-calendars#1294]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

I'm struggling trying to show a marked date that's selected. I have figured out how to update the selected date with a marked date immutable variable. however when I set newly marked variables when selected do not set the selected property to true. is this possible? if not could this be a new feature or already be implemented some way?

## Expected Behavior

What action did you perform, and what did you expect to happen?
when selecting a marked date it should also activate the selected property variable.

## Observed Behavior

What actually happened when you performed the above actions?
marked date is tapped and shows to be selected but no selection color is set.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.403.0
* `npm ls react-native`: react-native@0.63.2

Also specify:

1. Phone/emulator/simulator & version: iPhone 11/simulator/IOS 14 

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

outside render:
const [selectedDate, setSelectedDate] = useState('');

inside calendar list render component:
markingType = {'simple'}

markedDates={{
[selectedDate]:{
   selected: true,
   marked: true,
},
'2020-09-24':{
   selected: [(selectedDate == '2020-09-24')? true : false],
   marked: true,
}
}}

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by himanshuvats1996** [comment]
> Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.
> ## Description
> 
> 1-2 sentences describing the problem you're having or the feature you'd like to request
> 
> I'm struggling trying to show a marked date that's selected. I have figured out how to update the selected date with a marked date immutable variable. however when I set newly marked variables when selected do not set the selected property to true. is this possible? if not could this be a new feature or already be implemented some way?
> ## Expected Behavior
> 
> What action did you perform, and what did you expect to happen?
> when selecting a marked date it should also activate the selected property variable.
> ## Observed Behavior
> 
> What actually happened when you performed the above actions?
> marked date is tapped and shows to be selected but no selection color is set.
> 
> If there's an error message, please paste the _full terminal output and error message_ in this code block:
> 
> ```
> Error text goes here!
> ```
> 
> ## Environment
> 
> Please run these commands in the project folder and fill in their results:
> 
>     * `npm ls react-native-calendars`: react-native-calendars@1.403.0
> 
>     * `npm ls react-native`: react-native@0.63.2
> 
> 
> Also specify:
> 
>     1. Phone/emulator/simulator & version: iPhone 11/simulator/IOS 14
> 
> 
> ## Reproducible Demo
> 
> Please provide a minimized reproducible demonstration of the problem you're reporting.
> 
> outside render:
> const [selectedDate, setSelectedDate] = useState('');
> 
> inside calendar list render component:
> markingType = {'simple'}
> 
> markedDates={{
> [selectedDate]:{
> selected: true,
> marked: true,
> },
> '2020-09-24':{
> selected: [(selectedDate == '2020-09-24')? true : false],
> marked: true,
> }
> }}
> 
> Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

Thanks it solved my problem 
want to add a small points to it . 
set selectedDate as current date 

selectedDate:new Date();

now it will select the current date as default .
