### ISSUE TITLE
Previous/next month buttons do not show on iOS 14

### ISSUE THREAD

**Issue by willyp63** [wix/react-native-calendars#1295]
## Description

Previous/next month buttons do not show on devices running the latest iOS (iOS 14). However, the area is still clickable and functions as expected.

## Expected Behavior

Expected to see left/right arrow icons where the user needs to tap to switch between months

## Observed Behavior

Did not see left/right arrow icons where the user need to tap

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.403.0 
* `npm ls react-native`: 0.62.2

Also specify:

1. Phone/emulator/simulator & version: iOS 14 any device

## Reproducible Demo

Add the basic calendar component (`import { Calendar } from 'react-native-calendars';`) to a page and open the app on a device running iOS 14

<img width="376" alt="Screen Shot 2020-09-25 at 11 14 45 AM" src="https://user-images.githubusercontent.com/15879255/94297217-6616df00-ff21-11ea-9470-771054138685.png">

**Comment by renedeanda** [comment]
@willyp63 Did you find a fix / workaround for this issue? I am trying to upgrade to the latest up from 1.289.0 and on RN 0.62.2 with the same error. Maybe I'm overlooking a new prop?

**Comment by stephenhoult** [comment]
@willyp63 Same as above. Did you find a workaround?

**Comment by willyp63** [comment]
@renedeanda @stephenhoult we originally thought the issue was with react-native-calendar, but for us it was actually an issue with images in general on ios14. None of our images across the app would show on ios14. 

We were able to fix the issue by updating react-native to 0.63, I believe. Hope this help 🙏

**Comment by renedeanda** [comment]
> @renedeanda @stephenhoult we originally thought the issue was with react-native-calendar, but for us it was actually an issue with images in general on ios14. None of our images across the app would show on ios14. 
> 
> We were able to fix the issue by updating react-native to 0.63, I believe. Hope this help 🙏 

Ok cool good to know! Will try moving to 0.63 to fix this. Thanks!

**Comment by stephenhoult** [comment]
> @renedeanda @stephenhoult we originally thought the issue was with react-native-calendar, but for us it was actually an issue with images in general on ios14. None of our images across the app would show on ios14.
> 
> We were able to fix the issue by updating react-native to 0.63, I believe. Hope this help 🙏

Thanks @willyp63 

Upgrading to 0.63.3 fixes the issue for me. (In my case it required a tweak to the pod file too due to the upgrade - https://stackoverflow.com/a/62836205)

**Comment by penchef** [comment]
For reference: this is the original issue [Fix image cannot show in iOS 14 #29420](https://github.com/facebook/react-native/pull/29420)
