### ISSUE TITLE
Missing type in type declaration file

### ISSUE THREAD

**Issue by aneeskodappana** [wix/react-native-calendars#1297]
## Description

in dayComponent prop there is `({date, state, marking})` args are available for the custom view. but the definition of marking shows `false | Marking[];`.  if there is a markedDates props and the selected has set to true like this
```js
 markedDates={{
        '2020-09-27': {
          selected: true,
          selectedColor: '#999999',
          textColor: '#BDBDBD',
        },
        '2020-09-28': {
          selected: true,
          selectedColor: '#999999',
          textColor: '#BDBDBD',
        },
      }}
```
The `marking.selected` property actually works for comparing and rendering custom view accordingly. but the declaration is wrong or misleading. I've actually seen `marking.selected` somewhere else.
## Expected Behavior
`marking.selected` in declaration file
What action did you perform, and what did you expect to happen?
Followed declaration file
## Observed Behavior
```
export interface DayComponentProps {
    date: DateObject;
    marking: false | Marking[];
    onPress: (date: DateObject) => any;
    onLongPress: (date: DateObject) => any;
    state: '' | 'selected' | 'disabled' | 'today';
    theme: CalendarTheme;
}
export type Marking =
    CustomMarking | DotMarking |
    MultiDotMarking | MultiPeriodMarking |
    PeriodMarking;
```
What actually happened when you performed the above actions?
There is no actual functionality missing, only the declaration file is missing
If there's an error message, please paste the *full terminal output and error message* in this code block:

```

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: `-- react-native-calendars@1.403.0
* `npm ls react-native`: `-- react-native@0.63.2

Also specify:

1. Phone/emulator/simulator & version:
Latest 
## Reproducible Demo
Not needed

**Comment by emilisb** [comment]
I'm sorry but we do not own neither maintain `@types/react-native-calendars` package.

The repository for the package is here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-calendars
