### ISSUE TITLE
Marker Style

### ISSUE THREAD

**Issue by Omarkojak** [wix/react-native-calendars#130]
My code is [here](http://ideone.com/oNp4DB)

Idk if i am using the marker thing wrong or not but not all the dates got marked look at the ones from 24 to 31.

<img width="1280" alt="screen shot 2017-08-04 at 1 13 59 am" src="https://user-images.githubusercontent.com/15948451/28947826-37f7f030-78b2-11e7-8dc7-376be5fdb9a0.png">

**Comment by tautvilas** [comment]
hi please check the code of calendars examples, if it does not work please provide us with some code to reproduce your problem. thanks

**Comment by Omarkojak** [comment]
The code u will find it in the issue in the word here
it's here 
http://ideone.com/oNp4DB

**Comment by tautvilas** [comment]
Hi, you have to specify marking for each day. There is no auto marking from start to stop.

```
'2015-05-21': [{ startingDay: true, color: 'blue' }],
'2015-05-22': [{ endingDay: true, color: 'gray' }],
'2015-05-24': [{ startingDay: true, color: 'gray' }],
'2015-05-25': [{ color: 'gray' }],
'2015-05-26': [{ color: 'gray' }],
'2015-05-27': [{ color: 'gray' }],
'2015-05-28': [{ color: 'gray' }],
'2015-05-29': [{ color: 'gray' }],
'2015-05-30': [{ color: 'gray' }],
'2015-05-31': [{ endingDay: true, color: 'gray' }] 
```

This is how it should be
