### ISSUE TITLE
Remove/block all the months before minDate and after maxDate

### ISSUE THREAD

**Issue by luhahaha** [wix/react-native-calendars#1301]
I can't find a way to block or remove all the months before the minDate and after maxDate. I'm using the CalendarList with the horizontal settings.

Is it possible to show the calendar with the months that are in the rage minDate maxDate? any workaround?

**Comment by Arwantys** [comment]
Hi, add pastScrollRange={0} or/and futureScrollRange={0}

**Comment by Gheeroppa** [comment]
For pastScrollRange it works, but for **futureScrollRange** sometimes, also if the view is not scrolling, the scroll listener seems to capture the gesture and call addMonth anyway.

**Comment by elie-chaaban** [comment]
how did you fix this? 

whenever i swipe to last month, the first day in week is selected
