### ISSUE TITLE
Agenda refresh when keyboard shows

### ISSUE THREAD

**Issue by ezekel** [wix/react-native-calendars#1308]
I used the Agenda, the problem is that when my dialog show and I have textInput when I tapped on the textInput the keyboard show and the Agenda will refresh and display nothing, when my dialog disappears the agenda refresh again it displays nothing. I just wondering why it refreshes.

![calendarerror](https://user-images.githubusercontent.com/6830057/95744959-da45d680-0cc6-11eb-912a-b63b43479f8a.png)

"react-native-calendars@1.403.0"
"react-native@0.63.2"

```
<Agenda

                horizontal={true}
                pagingEnabled={true}
                onDayPress={(day) => {
                   setselDate(day.dateString)
                }}
                 items={ncal}
                 renderItem={(item, firstItemInDay)=>{
                     return(
                          <View style={styles.item}>
                             <Text>{item.name}</Text>
                         </View>
                     )
                 }}

               

            ></Agenda>```

Thanks

**Comment by JImumu** [comment]
Did you know how to fix this?

**Comment by yuguanthor** [comment]
same issues here.
when keyboard is popup, the agenda calendar will become two line of week name only

**Comment by yuguanthor** [comment]
found a solution for this.

may refer to this
https://github.com/wix/react-native-calendars/issues/309#issuecomment-398414442

how it work ?

```
  constructor(props) {
    super(props);
    this.agendaRef = React.createRef();
  }
```
add an agenda ref.

```
//use below function to re-render calendar after input keyboard hide 
static toggleCalendar() {
    let agendaRef = this.agendaRef
    if (agendaRef.state.calendarScrollable) {
        //this is show week calendar
        agendaRef.setScrollPadPosition(agendaRef.initialScrollPadPosition(), true);
        agendaRef.setState({ calendarScrollable: false })
        agendaRef.calendar.scrollToDay(agendaRef.state.selectedDay.clone(), agendaRef.calendarOffset(), true);
    } else {
        //this is show month calendar
        agendaRef.setScrollPadPosition(0, true);
        agendaRef.enableCalendarScrolling();
    }
}
```

you need to at some listener to your input. such as when input is onblur, call toggleCalendar function to re-render calendar.

**Comment by ItsNoHax** [comment]
Can we re-open this issue? Still happening in latest version. Any keyboard in my Android will make the Agenda's calendar shift up and down with it.

**Comment by pawlone** [comment]
I have the same problem on iOS. I've tried every solution I could find, but it still doesn't work properly.

**Comment by opvishu2** [comment]
just a quick fix, use conditional rendering after keyboard dismiss, e.g.


{showAgenda && <Agenda
        firstDay={1}
        theme={{
          selectedDayBackgroundColor: colors.primary,
          dotColor: colors.primary,
          agendaTodayColor: colors.primary,
          contentStyle: { flex: 1 },
          textDayHeaderFontSize: 14,
          textDayHeaderColor: 'red',
          textSectionTitleColor: colors.pureBlack,
        }}
        onDayPress={dateData => {
          const dateObj = dateData;
          setDate(dateObj.dateString);
          
          setYear((dateObj?.year)*1 ?? new Date().getFullYear())
          setMonth((dateObj?.month*1-1)*1 ?? new Date().getMonth())
        }}
       onDayChange={(dateObj) => {
        if(moment(dateObj.dateString, DATE_FORMAT_FOR_API_PAYLOAD).isAfter(moment(date, DATE_FORMAT_FOR_API_PAYLOAD).endOf('week'))){
          setDate(dateObj.dateString)
        }
       }}
        items={items}
        rowHasChanged={(r1, r2) => {
          return true
        }}
        selected={date}
        // selected={moment().format(DATE_FORMAT_FOR_API_PAYLOAD)}
        showClosingKnob={true}
        refreshing={refreshing}
        onRefresh={handleRefresh}
        keyExtractor={(item, i) => item.id + '' + i}
        renderItem={(item, index) => renderItem(item, index)}
        renderEmptyData={() => {
          return shifts?.length == 0 && !isLoading ? (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
              <Text>{'No Shifts Found'}</Text>
            </View>
          ) : (
            <View />
          );
        }}
      />}
