### ISSUE TITLE
I need your support. i can't run this project on Android studio. Gradel error is coming. please, help me to resolve this matter... 

### ISSUE THREAD

**Issue by krish1221** [wix/react-native-calendars#131]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by tautvilas** [comment]
hi please fill bug report according to the template, thanks

**Comment by krish1221** [comment]
i need to run react-native-calendars on android studio. i used only "android" folder available inside the example folder. when i start to"open an existing android studio project" it will be given gradel error.

Error:(5, 0) Could not read script 'G:\Android\AndroidStudioProjects\node_modules\react-native\react.gradle' as it does not exist.
<a href="openFile:G:\Android\AndroidStudioProjects\androidddd\app\build.gradle">Open File</a>

so help me to resolve this please...

**Comment by krish1221** [comment]
Krishantha@Krishantha-PC MINGW64 ~/Desktop
$ npm ls react-native-calendars:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ls" "react-native-calendars:"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: react-native-calendars:
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Krishantha\Desktop\npm-debug.log

**Comment by krish1221** [comment]
Krishantha@Krishantha-PC MINGW64 ~/Desktop
$ npm ls react-native:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ls" "react-native:"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: react-native:
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Krishantha\Desktop\npm-debug.log
