### ISSUE TITLE
expandable calendar shows extra number when background is transparent

### ISSUE THREAD

**Issue by FatemeMirzaeii** [wix/react-native-calendars#1310]
## Description

Hi!
I'm using expandable calendar and I need to make its background transparent.
but it shows some extra weekdays in the background!
why?
and what should I do to fix this?

![Screenshot_1603207](https://user-images.githubusercontent.com/33895649/96451047-ddd7e100-1223-11eb-923c-12eb956a71b9.png)

**Comment by FatemeMirzaeii** [comment]
unfortunately no.
I have used WeekCalendar Component instead. it's not the same, but better than this mess.

> Hi!
> I'm having the same Issue, did you find any solution yet?

**Comment by keith88kwok** [comment]
any updates :(

**Comment by guiolmar** [comment]
Any updates?
