### ISSUE TITLE
Android: onDayPress works verrrry slow ((((((

### ISSUE THREAD

**Issue by Azarians** [wix/react-native-calendars#1311]

**Comment by nfjones87** [comment]
i see you closed this 5 days after you opened it... did you discover the cause or solution @Azarians ?

**Comment by meliodev** [comment]
Same problem for me.. I am using firestore as a database from where I fetch tasks to show on Agenda.

**Comment by JKancel** [comment]
Still present for me too, any workaround ?

**Comment by almeidaalajoel** [comment]
It is pretty slow for me - about a half second delay. No API calls or anything.

**Comment by MensurRasic** [comment]
Same here, very slow on android devices but doing fine on apple ones. Any updates on this?

**Comment by Pedrosousa2005** [comment]
Same issue here, anyone knows how to solve?

**Comment by andre-fong** [comment]
Encountering this issue too on Android with Expo 52 and react-native-calendars 1.1307.0
