### ISSUE TITLE
How to disable "lazy load" in CalendarList

### ISSUE THREAD

**Issue by ggittt** [wix/react-native-calendars#1314]
I want to see all months at once

![11](https://user-images.githubusercontent.com/66523983/97084849-596dcf80-1622-11eb-98ec-609a68572642.gif)

**Comment by ggittt** [comment]
https://github.com/wix/react-native-calendars/issues/152 similar problem

**Comment by nelsonchen5** [comment]
+1

**Comment by apoorva-techie** [comment]
is there any solution to it?

**Comment by emilisb** [comment]
We are currently working on performance improvements, we will look into this.

**Comment by DonOzOn** [comment]
+1

**Comment by Laxnring** [comment]
Has this been fixed?

**Comment by alicanso** [comment]
+1

**Comment by humandeep916** [comment]
+1
