### ISSUE TITLE
react-native-calendars moved 1 day forward

### ISSUE THREAD

**Issue by mparkhomenko** [wix/react-native-calendars#1319]
At the time of creating the post, it was Friday 30th. For some reason, my calendar displays this day as Saturday:

`          <Calendar
            style={{width: Dimensions.get('screen').width - 10}}
            theme={{
              selectedDayBackgroundColor: '#00adf5',
              selectedDayTextColor: '#ffffff',
              dotColor: '#00adf5',
            }}
            onDayPress={this.onDaySelect}
            markedDates={this.state.markedDates}
            markingType="single"
            minDate={minDate}
            maxDate={maxDate}
            disableAllTouchEventsForDisabledDays={true}
          />`

<img width="358" alt="Screen Shot 2020-10-30 at 16 59 43" src="https://user-images.githubusercontent.com/47244665/97719444-2327c880-1ad8-11eb-852c-63e9ba368c9d.png">

**Comment by lostchopstik** [comment]
This is likely a UTC issue where you're local time is now "tomorrow" in UTC. You should set the `current` property to today's date string.  In my own, I use it like this:

``` js
const date = new Date();

<Calendar 
    current={date.toLocaleDateString()}
    ... // other props
/>
```

**Comment by mparkhomenko** [comment]
@lostchopstik Thank you for your help, but It doesn't work for me :(
`console.log(new Date().toLocaleDateString());` shows 10/31/2020 (current date). `console.log(new Date());` also shows current date (Sat Oct 31 2020 10:41:14 GMT+0300 (Moscow Standard Time)), but in calendar I also see incorrect variant.

<img width="353" alt="Screen Shot 2020-10-31 at 10 46 21" src="https://user-images.githubusercontent.com/47244665/97774113-5153e980-1b66-11eb-8318-8a79e56e2430.png">

**Comment by jaiminp-nimblechapps** [comment]
I have faced same issues. Please help me

**Comment by jaiminp-nimblechapps** [comment]
@mparkhomenko Please added  parameters **firstDay={6}**.

**Comment by mparkhomenko** [comment]
@jaiminp-nimblechapps It didn't help :(
Do you have other variants?

**Comment by jaiminp-nimblechapps** [comment]
@mparkhomenko 
 Go to this file location and changed 
**let weekDaysNames = weekDayNames(this.props.firstDay);**  
to 
**let weekDaysNames = weekDayNames(6);**
`react-native-calenders -> src -> calendar -> header -> index.js`

**Comment by mparkhomenko** [comment]
@jaiminp-nimblechapps thank you!!!

**Comment by jaiminp-nimblechapps** [comment]
@mparkhomenko Glad to help!!!!

**Comment by zaferatli** [comment]
this solution make sunday first day of week. Its not suitable for me and i try to read typescript
Add this:

firstDay={1} with https://github.com/wix/react-native-calendars/issues/1319#issuecomment-723943875

After this first day of week is monday and day forward fixed.

**Comment by cwtaras** [comment]
I've came across with the same problem in Agenda component. I've added firstDay=1, and didn't change the order of the short day names. But now, date of days are incorrect. Today is 1st of September Thursday but It looks like Friday in weekly view. How can i solve this?

**Comment by alperkilickaya** [comment]
> I've came across with the same problem in Agenda component. I've added firstDay=1, and didn't change the order of the short day names. But now, date of days are incorrect. Today is 1st of September Thursday but It looks like Friday in weekly view. How can i solve this?

I think I have same issue in Turkish. 
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-05 at 13 57 01](https://user-images.githubusercontent.com/48261006/210764792-a9e384a1-78aa-442b-b144-7fca8a38f5de.png)

**Comment by alperkilickaya** [comment]
@ cwtaras I think I found a solution for Agenda wrong day issue with locale config for @1.1293.0 version.

Go to;
node_modules->react-native-calendars->src->agenda->reservation-list->reservation.js 

Change;
{dayNames ? dayNames[date.getDay()] : undefined} (should be line 64)
to
{dayNames ? dayNames[date.getDay()-1] : undefined} 

Also apply same approach for agenda as mentioned above for calendar;
Go to;
node_modules->react-native-calendars->src->agenda->index.js

Change;
return (<WeekDaysNames firstDay={this.props.firstDay} style={this.style.dayHeader}/>);
to
return (<WeekDaysNames firstDay={6} style={this.style.dayHeader}/>);

**Comment by fherrera7850** [comment]
> let weekDaysNames = weekDayNames(this.props.firstDay);

why 6?

**Comment by agruenb** [comment]
I had the same issue and it turns out it is due to the way the .getDay() function is defined. For some reason it is not **Mon-Sun** but **Sun-Sat**. So Sunday is 0 and Saturday is 6, this makes it seem like there is an issue with a timeshift if you expect Monday to be 0 and Sunday 6. See the docs:
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay)

**Comment by PedroW21** [comment]
> @ cwtaras I think I found a solution for Agenda wrong day issue with locale config for @1.1293.0 version.
> 
> Go to; node_modules->react-native-calendars->src->agenda->reservation-list->reservation.js
> 
> Change; `{dayNames ? dayNames[date.getDay()] : undefined}` (should be line 64) to `{dayNames ? dayNames[date.getDay()-1] : undefined} `
> 
> Also apply same approach for agenda as mentioned above for calendar; Go to; node_modules->react-native-calendars->src->agenda->index.js
> 
> Change; `<WeekDaysNames firstDay={this.props.firstDay} style={this.style.dayHeader}/>` to `<WeekDaysNames firstDay={6} style={this.style.dayHeader}/>`

Tried this solution on @1.1305.0 version, and didn't work.

But logging around shows me that for some reason, at first moment the day is right , and suddenly it re-renders and stay on future date.

![image](https://github.com/user-attachments/assets/87c11768-02c4-4191-ad53-d5417a473747)

![image](https://github.com/user-attachments/assets/fe448724-6281-4475-bb58-9ef7e2a30099)

![image](https://github.com/user-attachments/assets/e826d097-7cff-4ade-b543-b71c95cb9286)

Anyone had more luck on finding an alternative solution? :/

**Comment by gonca-gul** [comment]
You don't need to intervene directly in the package. Start the day list you provide from Sunday and let firstDay={1}. This solved my problem.
