### ISSUE TITLE
ExpandableCalendar unresponsive on Android

### ISSUE THREAD

**Issue by USVDH** [wix/react-native-calendars#1320]
## Description

The component works perfectly fine on iOS, but when on Android it doesn't respond to any touch inputs.

## Expected Behavior

Calendar should respond to touch inputs

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.403.0 
* `npm ls react-native`: (empty)

Also specify:

1. Phone/emulator/simulator & version: Google Pixel 2 & 3, Android 10 & 11 

## Reproducible Demo

```
import React from 'react';
import {View} from 'react-native';
import {
  ExpandableCalendar,
  CalendarProvider,
  LocaleConfig,
} from 'react-native-calendars';

export interface WeekCalendarProps {
  bookingData;
  onDateChanged;
}

const WeekCalendar: React.SFC<WeekCalendarProps> = ({
  bookingData;
  onDateChanged,
}) => {
  const getMarkedDates = () => {
    const marked = {};
    bookingData.forEach((item) => {
      if (item.date) {
        marked[item.date] = {marked: true};
      } else {
        marked[item.date] = {disabled: true};
      }
    });
    return marked;
  };

  return (
    <View>
      <CalendarProvider disabledOpacity={0.6} onDateChanged={onDateChanged}>
        <ExpandableCalendar
          disablePan
          hideKnob
          disableAllTouchEventsForDisabledDays
          firstDay={1}
          theme={calendarTheme()}
          markedDates={getMarkedDates()}
        />
      </CalendarProvider>
    </View>
  );
};

export default WeekCalendar;
```

**Comment by Ayman-Alqaq** [comment]
You will need to encapsulate your view container. 

See issue https://github.com/wix/react-native-calendars/issues/335

**Comment by USVDH** [comment]
Sorry for the late reply. This fixed it for me, thanks!
