### ISSUE TITLE
IOS - the screen does not update

### ISSUE THREAD

**Issue by eugenioduarte** [wix/react-native-calendars#1329]
Hello devs!
I have a very weird problem, the package works perfect on android, when I click on the chevrons the month change is instantly and automatically updates the screen, but on ios this does not happen, even after updating the state value the month remains the same, the screen simply does not update, I tried to use hooks, useeffect and nothing. Can anyone who's been through this give me a hand?

"react": "16.11.0",
"react-native": "^0.62.2",
"react-native-calendars": "^1.403.0",

**Comment by tintujacob** [comment]
I'm having same issue. 
EXPO SDK39
"react-native-calendars": "^1.403.0",
