### ISSUE TITLE
set starting week #

### ISSUE THREAD

**Issue by nicencina** [wix/react-native-calendars#1331]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Is there a way of setting the starting week number in the CalendarList? By default it counts starting on January 1, but if I want to use this in a scenario where an activity starts on a specific date and week counting matters then it would be great to set the starting week -- particularly if I have set a "minDate" and/or a "maxDate". As an example, consider pregnancy: There's a starting point, and a rough ending point (40weeks), and milestones are counted in both trimesters and weeks from the start.

## Expected Behavior

I set the minDate, and searched online for instructions/examples on how to set the week count but found nothing

## Observed Behavior

Week counting begins on Jan 1

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
N/A
```

## Environment

Please run these commands in the project folder and fill in their results:

N/A

## Reproducible Demo

N/A

**Comment by coolvasanth** [comment]
@nicencina  did you get to know how to do it ??
