### ISSUE TITLE
Collapse calendar

### ISSUE THREAD

**Issue by lmz2k** [wix/react-native-calendars#1339]
Is it possible to collapse the Calendar to show only week, like on Agenda, but using the calendar component?

Or. Is it possible, that, when expand the week to show the calendar, show only the current month days, like images below, without rendering the default renderItem that Agenda provide us on body?

like this!
![Screenshot from 2020-11-30 16-51-06](https://user-images.githubusercontent.com/26030388/100657032-6a4de700-332c-11eb-845b-475146c192a6.png)
![Screenshot from 2020-11-30 16-51-13](https://user-images.githubusercontent.com/26030388/100657035-6ae67d80-332c-11eb-8e57-1f077e30f9ab.png)

I want to use only the Calendar/Agenda, that slide the months in horizontal and not in  vertical when expanded.

**Comment by chenqiaoen521** [comment]
I'm looking for the same feature

**Comment by harshchhabra** [comment]
Any updates on this feature

**Comment by SashaGoncharov19** [comment]
We want this
