### ISSUE TITLE
Agenda - set calendar list as initial view

### ISSUE THREAD

**Issue by georgetroughton** [wix/react-native-calendars#134]
Question -  is it possible for the calendar list to be the initial view on agenda?

**Comment by tautvilas** [comment]
hey, currently this is not possible

**Comment by georgetroughton** [comment]
Hi - thanks - just wanted to double check.

**Comment by habeebrahmanpt** [comment]
Question - is it now possible for the calendar list to be the initial view on agenda?

**Comment by SmirnovM91** [comment]
+1
