### ISSUE TITLE
Setting markingType multi-period breaks text alignment

### ISSUE THREAD

**Issue by darron1217** [wix/react-native-calendars#1341]
## Description

Setting markingType multi-period breaks text alignment

## Expected Behavior

Date text should maintain position at center.

## Observed Behavior
Before
![image](https://user-images.githubusercontent.com/8064923/100736348-ef60fb00-3415-11eb-8ff1-3d2b6b6c2b75.png)

After
![image](https://user-images.githubusercontent.com/8064923/100736299-e3753900-3415-11eb-8766-b9d780fa9981.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
```
└── react-native-calendars@1.505.0
```
* `npm ls react-native`:
```
└── react-native@0.63.3
```

Also specify:

1. Phone/emulator/simulator & version:
Android API 29 emulator

**Comment by darron1217** [comment]
It was really simple style bug.
I've created PR to added missing style on `multi-period` type.

**Comment by darron1217** [comment]
@emilisb I created another PR to apply your suggestion.
The solution worked perfectly. please check

**Comment by emilisb** [comment]
I merged the fix, thanks for reporting and fixing this.

**Comment by auguyon** [comment]
I got the same error with the version 1.315.0 and actually, I can't use the latest version 1.1249.0 about this -> #1394

**Comment by darron1217** [comment]
@auguyon I'm currently using version `1.567.0` and it works well.
You can install specific version.

**Comment by auguyon** [comment]
Same problem with the 1.567.0. The dates are not align with the days.
