### ISSUE TITLE
Next month days are disabled

### ISSUE THREAD

**Issue by samuelpetroline** [wix/react-native-calendars#1343]
## Description

The problem is quite simple: [any days different from the current month are considered disabled](https://github.com/wix/react-native-calendars/blob/718a840c1e83c05d4dc4df0a0e8f1f794b50d936/src/calendar/index.js#L196). This is a problem in my case, where I allow the user to select a day from some pre-defined options. Since they are disabled, they cannot be chosen.

Is there any way to work around this issue? 
## Expected Behavior

The days should not be disabled

## Observed Behavior

![image](https://user-images.githubusercontent.com/22039767/100656334-4c33b700-332b-11eb-8246-57b4922a35bb.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.403.0
* `npm ls react-native`: react-native@0.63.0

**Comment by samuelpetroline** [comment]
For anyone interested in a quick solution, all you got to do is:

- Install [patch-package](https://github.com/ds300/patch-package) as dev dependency (check their set-up documentation)
- Create a `patches` folder in root directory
- Create a file named `react-native-calendars+1.403.0.patch`
- Paste this into the file:

```
diff --git a/node_modules/react-native-calendars/src/calendar/index.js b/node_modules/react-native-calendars/src/calendar/index.js
index 92d5bd5..f3dac15 100644
--- a/node_modules/react-native-calendars/src/calendar/index.js
+++ b/node_modules/react-native-calendars/src/calendar/index.js
@@ -193,8 +193,8 @@ class Calendar extends Component {
       state = 'disabled';
     } else if (this.isDateNotInTheRange(minDate, maxDate, day)) {
       state = 'disabled';
-    } else if (!dateutils.sameMonth(day, this.state.currentMonth)) {
-      state = 'disabled';
+    // } else if (!dateutils.sameMonth(day, this.state.currentMonth)) {
+    //   state = 'disabled';
     } else if (dateutils.sameDate(day, XDate())) {
       state = 'today';
     }
```

**Comment by benomatis** [comment]
@samuelpetroline I think this is great, except the patch may need to be modified depending on which version someone is using, however, wouldn't this be best as a PR?

@emilisb I too was looking for a solution for this, I think it should at least be made optional, no? I honestly see no reason why otherwise allowed dates would be disabled only because they're in a different month.

**Comment by samuelpetroline** [comment]
@benomatis I agree a PR would be best but I couldn't wait for it. And since @emilisb assigned the task I thought it would be handled. I don't know why this is the default behaviours but it sure is weird.

I'll be doing a PR as soon as I can

**Comment by benomatis** [comment]
sure thing, @samuelpetroline, I understand that entirely, and I hope I didn't come across as wanting to tell you what you should or shouldn't do, I'm not even a maintainer of this project or anything. I think your above patch is already a great contribution, I'm using it myself! :)

**Comment by TarikDervisevicVisiot** [comment]
In the latest version as of writing this post (1.1294), the file structure has changed and you will need to apply this patch instead:
`diff --git a/node_modules/react-native-calendars/src/day-state-manager.js b/node_modules/react-native-calendars/src/day-state-manager.js
index 514e854..737055d 100644
--- a/node_modules/react-native-calendars/src/day-state-manager.js
+++ b/node_modules/react-native-calendars/src/day-state-manager.js
@@ -15,8 +15,8 @@ export function getState(day, current, props, disableDaySelection) {
     else if (isDateNotInRange(day, minDate, maxDate)) {
         state = 'disabled';
     }
-    else if (!sameMonth(day, current)) {
-        state = 'disabled';
-    }
+    // else if (!sameMonth(day, current)) {
+    //     state = 'disabled';
+    // }
     return state;
 }
`

**Comment by benomatis** [comment]
@TarikDervisevicVisiot indeed, I updated my patch exactly like this as well.
