### ISSUE TITLE
ExpandableCalendar resize after change month

### ISSUE THREAD

**Issue by sn4f** [wix/react-native-calendars#1349]
## Description

If I select day on ExpandableCalendar and scroll to other months, calendar wont to resize height.

## Expected Behavior
Resize height on change month everytime

## Reproducible Demo
https://streamable.com/4oioel

**Comment by borasumer** [comment]
I actually know the issue, trying to solve it, might create a PR, but it seems it is gonna take some time. So while changing the month by swiping the calendar left to right, it takes the date from context and calculate the number of the weeks based on this date. But when you select a date by pressing on it, you set the date in the context, and after you continue swiping, you use this selectedDate from the context. So if it is selected on the previous month lets say February which has 4 weeks, when you swipe back to March for example, it still calculates the number of the weeks based on the month of February, because the selected date coming from the context props is still February.

**Comment by borasumer** [comment]
This is the change you need to in the module expandableCalendar index file. You can fork the library and made the change. 
`  onVisibleMonthsChange = (value) => {
    if (this.visibleMonth !== _.first(value).month) {
      this.visibleMonth = _.first(value).month; // equivalent to this.getMonth(value[0].dateString)
      parseDate(this.props.context.date)
      // current date on the calendar
      const currentDate = parseDate(value[0].dateString)

      // for horizontal scroll
      const {date, updateSource} = this.props.context;
      
      if (this.visibleMonth !== this.getMonth(date) && updateSource !== UPDATE_SOURCES.DAY_PRESS) {
        const next = this.isLaterDate(_.first(value), date);
        this.scrollPage(next);
      }
      // updating openHeight
      setTimeout(() => { // to wait for setDate() call in horizontal scroll (this.scrollPage())
        const numberOfWeeks = this.getNumberOfWeeksInMonth(parseDate(currentDate));
        if (numberOfWeeks !== this.numberOfWeeks) {
          this.numberOfWeeks = numberOfWeeks;
          console.log('numberOfWeeks:', numberOfWeeks)
          this.openHeight = this.getOpenHeight();
          if (this.state.position === POSITIONS.OPEN) {
            this.bounceToPosition(this.openHeight);
          }
        }
      }, 0);
    }
  }`

**Comment by borasumer** [comment]
No body is maintaining this library anymore so I am just pasting the code I update in the node_modules/expandableCalendar/index.js file to solve that issue. 
` onVisibleMonthsChange = (value) => {
    if (this.visibleMonth !== _.first(value).month) {
      this.visibleMonth = _.first(value).month; // equivalent to this.getMonth(value[0].dateString)
      parseDate(this.props.context.date);

      // current date on the calendar
      const currentDate = parseDate(value[0].dateString);

      // for horizontal scroll
      const {date, updateSource} = this.props.context;
      
      if (this.visibleMonth !== this.getMonth(date) && updateSource !== UPDATE_SOURCES.DAY_PRESS) {
        const next = this.isLaterDate(_.first(value), date);
        this.scrollPage(next);
      }

      // updating openHeight
      setTimeout(() => { // to wait for setDate() call in horizontal scroll (this.scrollPage())
        const numberOfWeeks = this.getNumberOfWeeksInMonth(parseDate(currentDate));
        if (numberOfWeeks !== this.numberOfWeeks) {
          this.numberOfWeeks = numberOfWeeks;
          this.openHeight = this.getOpenHeight();
          if (this.state.position === POSITIONS.OPEN) {
            this.bounceToPosition(this.openHeight);
          }
        }
      }, 0);
    }
  }`

**Comment by sn4f** [comment]
@borasumer thank you!
