### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by getadapt** [wix/react-native-calendars#1355]
Yo the changelog is missing most of the 190ish updates to the package that happened in the last week or so... 

Love the fact this package is catching up with pull requests, but maybe a note acknowledging what's up in the changelog somewhere?

I'm over here wondering whether to update this package on my app while watching a new release come out every 15 minutes like 👁👄👁

**Comment by emilisb** [comment]
We have a bug in Wix CI which causes too many unnecessary automatic releases. We are looking into it.
