### ISSUE TITLE
Render the day's date before all events in specific day in the Agenda view

### ISSUE THREAD

**Issue by AbdallaMohamed** [wix/react-native-calendars#136]
## Description

I've been trying to customize the Agenda view to render the full day's date as a row before all the events in that specific day. But in the flexDirection is a row. I tried working around it with a `position: 'absolute'`, but it didn't work. The `renderDay` method only works for specific events in the events.

## Expected Behavior

What I want to achieve is something like that.

![image](https://user-images.githubusercontent.com/10912145/29241638-ec895238-7f7d-11e7-9eb3-96b4d1305730.png)

Can you guys point me in the right direction?

**Comment by AbdallaMohamed** [comment]
I'd also like to achieve a **sticky header** like what's shown in that gif. I can start to try to implement it if it's a possible addition to the library.
 
![aug-12-2017 16-50-30](https://user-images.githubusercontent.com/10912145/29241706-0eba3c68-7f7f-11e7-8b80-c884b65cdfbc.gif)

**Comment by tautvilas** [comment]
Hi, this is very different from what we have now so unfortunatelly there will not be an easy way to implement it by modifying current agenda.
