### ISSUE TITLE
Navigator is deprecated and has been removed from this package.

### ISSUE THREAD

**Issue by aranion1** [wix/react-native-calendars#1361]
Navigator is deprecated and has been removed from this package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html

Object.get Navigator [as Navigator]
    react-native-implementation.js:124:4
_interopRequireWildcard
    <unknown file>:0
<unknown>
    <unknown file>:0
loadModuleImplementation
    require.js:191:4
guardedLoadModule
    require.js:138:11
_require
    require.js:118:2
<unknown>
    Record.js:6
loadModuleImplementation
    require.js:191:4
guardedLoadModule
    require.js:138:11

**Comment by emilisb** [comment]
Sorry, this is not related to this library.
