### ISSUE TITLE
Incorrect days

### ISSUE THREAD

**Issue by ksielyov** [wix/react-native-calendars#1368]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Incorrect date https://prnt.sc/vzpl1r
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
`-- react-native-calendars@1.835.0

* `npm ls react-native`:
`-- react-native@0.63.3

Also specify:

1. Phone/emulator/simulator & version:
Default android studio simulator
Android version - 10

`import React, {Component} from 'react';
import {View, Text, StyleSheet, TouchableOpacity, ImageBackground, StatusBar, Image} from 'react-native';

import {Calendar, CalendarList, Agenda, LocaleConfig} from 'react-native-calendars';

import CloseIcon from '../Image/close.svg';
import Polygon from '../Image/Polygon.svg';

LocaleConfig.locales['ru'] = {
    monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    monthNamesShort: ['Янв', 'Фев', 'Март', 'Апр', 'Май', 'Июнь', 'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Декаб'],
    dayNames: ['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'],
    dayNamesShort: ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],
    today: 'Сегодня'
};
LocaleConfig.defaultLocale = 'ru';

class ChooseDate extends Component {
    constructor(props) {
        super(props);

        this.state = {
            currentDay: new Date().getDate(),
            currentMonth: 'Декабрь',
            currentYear: String(new Date().getFullYear()),
            monthPickerAct: false,
        };
    }

    render() {
        const styles = StyleSheet.create({
            globalContainer: {
                width: '100%',
                height: '100%',
                zIndex: 4,
                position: 'absolute',
                alignItems: 'center',
                justifyContent: 'center',
                backgroundColor: '#F5F7FA',
                opacity: 0.96,
                // paddingTop: 108,
            },

            container: {
                width: 289,
                height: 419,
                backgroundColor: '#fff',
                opacity: 1.0,
                borderRadius: 5,
                elevation: 2,
                alignItems: 'center',
                shadowColor: 'rgba(38, 38, 188, 0.25)',
                shadowOffset: {
                    width: 4,
                    height: 4,
                },
                shadowOpacity: 1,
            },

            dateHeader: {
                backgroundColor: '#8276F4',
                borderRadius: 5,
                width: '100%',
                height: 58,
                padding: 10,
                marginBottom: 14,
            },

            closeContainer: {
                width: '100%',
                justifyContent: 'space-between',
                flexDirection: 'row',
            },

            content: {
                flex: 1,
                width: '100%',
                paddingLeft: 8,
                paddingBottom: 11,
                lineHeight: 18,
            },

            chosenDateText: {
                color: '#2F2D2D',
                fontSize: 12,
                marginRight: 8,
            },

            daysName: {
                color: '#2F2D2D',
                fontSize: 11,
                lineHeight: 13,
                fontWeight: '500',
            },

            daysContainer: {
                width: '100%',
                flexDirection: 'row',
                flexWrap: 'wrap',
                marginBottom: 31,
            },

            dayContainer: {
                width: 37.92,
                height: 39,
                // backgroundColor: '#8276F4',
                borderRadius: 100,
                justifyContent: 'center',
                alignItems: 'center',
                marginRight: 1,
            },

            day: {
                color: '#2F2D2D',
                fontSize: 14,
                lineHeight: 17,
                fontWeight: '500',
                // marginBottom: 23,
                flexDirection: 'row',
                // paddingLeft: 6,
                // textAlign: 'center',
                // paddingLeft: 6,
                // paddingRight: 6
            },

            btn: {
                width: 138,
                height: 38,
                backgroundColor: '#E3DEFD',
                borderRadius: 5,
                alignItems: 'center',
                justifyContent: 'center',
            },

            monthPicker: {
                width: 180,
                height: 300,
                backgroundColor: '#fff',
                elevation: 3,
                shadowColor: 'rgba(130, 118, 244, 0.15)',
                shadowOpacity: 1,
                shadowOffset: {
                    width: 4,
                    height: 4,
                },
                zIndex: 5,
                position: 'absolute',
                marginTop: 20,
                marginLeft: 8,
                borderRadius: 10,
                opacity: 1.0,
                padding: 10,
            },

            yearPicker: {
                width: 180,
                height: 90,
                backgroundColor: '#fff',
                elevation: 3,
                shadowColor: 'rgba(130, 118, 244, 0.15)',
                shadowOpacity: 1,
                shadowOffset: {
                    width: 4,
                    height: 4,
                },
                zIndex: 5,
                position: 'absolute',
                marginTop: 20,
                marginLeft: 8,
                borderRadius: 10,
                opacity: 1.0,
                padding: 10,
            },
        });

        return (
            <View style={styles.globalContainer}>
                <StatusBar hidden={true}/>
                <Calendar
                    current={new Date()}
                    enableSwipeMonths={true}
                />
            </View>
        );
    }
}

export default ChooseDate;
`

**Comment by ksielyov** [comment]
https://prnt.sc/vzpl1r

**Comment by AndrewLosseff** [comment]
Please, add

`firstDay={1} `

to the Calendar component.

If firstDay=1 week starts from Monday. Note that dayNames and dayNamesShort should still start from Sunday.

```
dayNames: ['Воскресенье', 'Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],
dayNamesShort: ['Вс', 'Пн','Вт','Ср','Чт','Пт','Сб'],
```
It should help.
