### ISSUE TITLE
Multi-mark day marking type

### ISSUE THREAD

**Issue by xuho** [wix/react-native-calendars#137]
Hi.
I want to make an calendar like this:
![image](https://user-images.githubusercontent.com/13913140/29277720-aa5850c4-813c-11e7-82a3-823a490585cf.png)
It's possible? How can I do that?
Thank.

**Comment by tautvilas** [comment]
Hi, it is not currently possible, but you could implement it as a custom day marking style and create a PR for that

https://github.com/wix/react-native-calendars/tree/master/src/calendar/day

**Comment by xuho** [comment]
thank you so much

**Comment by JosKar** [comment]
Is someone working on this?

**Comment by jeveloper** [comment]
Curious if anyone had actually added dot marking, i know its there for a single dot, but mulitple would be interesting

**Comment by jaruyot** [comment]
@jeveloper I've created a pull request for this enhancement: #212

**Comment by jeveloper** [comment]
you rock @jaruyot thank you
