### ISSUE TITLE
How to get selected date after press event on date (ExpandableCalendar) in CalendarProvider

### ISSUE THREAD

**Issue by usamadanish22** [wix/react-native-calendars#1370]
have tried a lot with many many events. i.e onChangeDay(), onDateChange() etc etc to get onPress event at any date. but all in vein can you please help me out with right event.

**Comment by usman733** [comment]
+1

**Comment by borasumer** [comment]
Are you trying to get the date or the event ?

**Comment by xbenjii** [comment]
@borasumer I assume the event, I've been trying to do the same with no luck.

**Comment by xbenjii** [comment]
Looks like a duplicate of https://github.com/wix/react-native-calendars/issues/1102
