### ISSUE TITLE
Knob is knock over the last days of the expandable calendar

### ISSUE THREAD

**Issue by kamo93** [wix/react-native-calendars#1371]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Using expandable calendar the knob is knock over the last days of the calendar.
![image](https://user-images.githubusercontent.com/18643841/102031322-9f722480-3d83-11eb-91c2-52b2a0e499e5.png)

## Expected Behavior
The knob appers bottom the last days.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.343.0 

* `npm ls react-native`: react-native@0.63.3

Thanks.

**Comment by sn4f** [comment]
same problem here https://github.com/wix/react-native-calendars/issues/1349

**Comment by kamo93** [comment]
> same problem here #1349

I think it is not quite the same, in my case show over the days without change the month.

**Comment by scblason** [comment]
@kamo93 It's not exactly a fix, but I had the same problem and I use theme styling to try to make it better. I change the size of the knob container:

`
...
theme={{
            'stylesheet.expandable.main': {
              // this styles helps fix a styling bug in the lib when the latest week of
              // the month is selected and theh calendar is expanded
              knobContainer: {
                position: 'absolute',
                left: 0,
                right: 0,
                height: 15,
                bottom: 0,
                alignItems: 'center',
                justifyContent: 'center',
                backgroundColor: COLOR.WHITE,
              },
            },
          }}`
