### ISSUE TITLE
Custom day component zIndex

### ISSUE THREAD

**Issue by sn4f** [wix/react-native-calendars#1376]
## Description

I added border of the whole element to my own component of the day, but when setting the value, e.g.
`  selectedDay: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: 'black',
    right: -2,
    left: -2,
    top: -2,
    bottom: -2
  },`
the element is covered by the next one despite using zIndex, did anyone have a similar problem? if so how to fix it.
![Zrzut ekranu 2020-12-19 o 10 31 10](https://user-images.githubusercontent.com/8761149/102686065-643d7e80-41e5-11eb-871a-c3d9a0acfe5a.png)

## Expected Behavior

I wish other days would not cover this with zIndex

**Comment by Apetrou** [comment]
@sn4f were you able to solve this?

**Comment by ShivamBarot2602** [comment]
@sn4f @Apetrou I am facing the same issue what fix have you applied for this....???

I need to show the period with a different color and the start date and end date with different color but the period color seems to overlay the start date.

<img width="309" alt="image" src="https://github.com/wix/react-native-calendars/assets/74816448/e44fd878-794b-4dd7-a27f-e64447ea62d0">

**Comment by sn4f** [comment]
@Apetrou @ShivamBarot2602 
Hi guys, I haven't been working on this project for a while, and to be honest, I don't remember how I solved this problem because it was two years ago. If I recall, I'll let you know.

**Comment by Apetrou** [comment]
@ShivamBarot2602 I ended up solving the issue by editing the library source code and then patching it. See below the diff:

`diff --git a/node_modules/react-native-calendars/src/calendar/index.js b/node_modules/react-native-calendars/src/calendar/index.js
index 6f46e8a..b71013b 100644
--- a/node_modules/react-native-calendars/src/calendar/index.js
+++ b/node_modules/react-native-calendars/src/calendar/index.js
@@ -103,7 +103,10 @@ const Calendar = (props) => {
         }
         const dateString = toMarkingFormat(day);
         const isControlled = isEmpty(props.context);
-        return (<View style={style.current.dayContainer} key={id}>
+
+        const customContainerStyle = markedDates ? markedDates[dateString]?.customContainerStyle : {};
+
+        return (<View style={[style.current.dayContainer, customContainerStyle]} key={id}>
         <Day {...dayProps} testID={`${testID}.day_${dateString}`} date={dateString} state={getState(day, currentMonth, props, isControlled)} marking={markedDates?.[dateString]} onPress={_onDayPress} onLongPress={onLongPressDay}/>
       </View>);
     };`

I created a new property called 'customContainerStyle' that is passed in with the markedDates object. If populated, it will override the styling of the dayContainer allowing me to set the ZIndex
