### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by maeschli** [wix/react-native-calendars#1379]
- Add About section
- Add installation guide
- Add contribution guide
- Add Timeline example
- Divide component examples into different files

**Comment by AndrewLosseff** [comment]
Should I remove links for:

General info
Basic parameters
Date marking
Styling

And put these sections in the README file?

**Comment by maeschli** [comment]
> Should I remove links for:
> 
> General info
> Basic parameters
> Date marking
> Styling
> 
> And put these sections in the README file?

yes, due to comment above only component examples to different files

**Comment by AndrewLosseff** [comment]
Done
All info except components is in the README.
