### ISSUE TITLE
ExpandableCalendar problem when rotating / change orientation

### ISSUE THREAD

**Issue by scblason** [wix/react-native-calendars#1380]
## Description

ExpandableCalendar has problem when rotating / change orientation the device (iPad, didin't tested on Android). 

## Expected Behavior

When a change on orientation occurs, the ExpandableCalendar should redraw with the correct layout of months / days.

## Observed Behavior

When I rotate the device, the week component of the calendar shows the name days not align with the number days. The name days seems correct (showing from Sun to Sat), but the count of days showed are incorrect (more than 7 days if I rotate to a bigger widht, less than 7 days if I rotate to a smaller screen). I manage to fix this behavior disabling the scroll on the expandable calendar when collpased (week view). Seems that is an issue with WeekCalendar, since when horizontal scroll is disable in week view, it uses a different component (Week).
If the calendar is expanded and I rotate the device, there is no workaround founded yet and the calendar shows in the wrong format.

## Environment

react-native-calendars@1.403.0 
ract-native@0.61.5

Also specify:

1. Phone/emulator/simulator & version: simulator iPad Air (3rd generation) 13.7

## Reproducible Demo

See attached pictures

Portrait (initial render)
<img width="630" alt="Screen Shot 2020-12-22 at 16 46 29" src="https://user-images.githubusercontent.com/13370132/102927982-bba64d80-4476-11eb-9b7d-9f47ba36c3a1.png">

Landscape (when rotating)
<img width="848" alt="Screen Shot 2020-12-22 at 16 46 41" src="https://user-images.githubusercontent.com/13370132/102927990-be08a780-4476-11eb-9e56-d3ba6bbbfc64.png">

**Comment by scblason** [comment]
Still experiencing the issue. Nobody has any input about this behavior? Thanks

**Comment by KrisLau** [comment]
I'm having the same issue

**Comment by on29-dev** [comment]
I'm having the same issue.
KrisLau's article is not helpful, because it is still happened in lastest version `1.1264.0`

저도 이 증상 겪고 있는데, KrisLau님 글은 별 도움이 안됩니다. 최신버전에서도 여전히 해당 증상 나타나거든요.

**Comment by RajamanickamDev** [comment]
I'm still facing this issue in both android and ios

**Comment by hariharank6** [comment]
I'm facing it as well

**Comment by keerthisaivel** [comment]
<img width="1225" alt="Screenshot 2024-01-29 at 11 44 56 AM" src="https://github.com/wix/react-native-calendars/assets/49042132/3a81e489-22f4-4e86-a3c2-9486b2561aa0">

I still have the same issue, I rotate into landscape mode in android and the alignment is not properly aligned. I don't have this problem in iOS

**Comment by Julio-de-Leon** [comment]
No solution yet?
