### ISSUE TITLE
Unable to resolve module './day/multi-dot' from 'node_modules\react-native-calendars\src\calendar\index.js'

### ISSUE THREAD

**Issue by Clemweb** [wix/react-native-calendars#1382]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When I update from 1.807 to 1.1128 and run android emulator, React Native says 

Unable to resolve module './day/multi-dot' from 'node_modules\react-native-calendars\src\calendar\index.js'

Version 1.807 working fine....

**Comment by Clemweb** [comment]
OK found : wrong right on my directory

For windows users : be carefull, the rights sometime gone wrong ! i need to change permission on dir

**Comment by akhil-geekyants** [comment]
Same issue.

**Comment by fxricky** [comment]
I'm also facing this issue too, any solutions?

**Comment by Clemweb** [comment]
Just change the rights and permissions on your react project directory. Force to administrator group on all sub directory (specially node_modules).
And re run (react-native run-android or run-ios).
Sometimes when I add somme dependancies I need to do this...

**Comment by Ranseth** [comment]
This doesn't really do anything for me... it's getting problematic.
