### ISSUE TITLE
Can't style Agenda component

### ISSUE THREAD

**Issue by randomprogramming** [wix/react-native-calendars#1383]
Hello, I am trying to style the Agenda component and the background color of it. 
![image](https://user-images.githubusercontent.com/48063901/103173056-8627a880-4858-11eb-8103-bcb415bbe6b6.png)

As you can see, I managed to get the top bar styled, but I can't change the style of the rest of the component..

I managed to change the color of the top bar piece by directly injecting my own code through the `theme` prop:

```
<Agenda
        selected={new Date().toISOString().split('T')[0]}
        items={{
          '2020-12-28': [{name: 'item 1 - any js object'}],
        }}
        hideKnob={true}
        theme={{
          backgroundColor: palette.backgroundDark,
          'stylesheet.agenda.main': {
            weekdays: {
              position: 'absolute',
              left: 0,
              right: 0,
              top: 0,
              flexDirection: 'row',
              justifyContent: 'space-around',
              marginLeft: 15,
              marginRight: 15,
              paddingTop: 15,
              paddingBottom: 7,
              backgroundColor: 'darkblue',
            },
          },
        }}
      />
```

I tried using the theme prop, the style prop and a whole lot of other solutions but nothing works... I looked through the source code and I can see that it might be possible by injecting more styles into the CalendarList component, but I can't figure out how the `extractComponentProps` function works in order to make this happen..

Small update:
The bottom bar can also be styled easily by injecting styles, the middle flat list is the only issue now..

```
'stylesheet.agenda.main': {
            knobContainer: {
              flex: 1,
              position: 'absolute',
              left: 0,
              right: 0,
              height: 24,
              bottom: 0,
              alignItems: 'center',
              backgroundColor: 'darkblue',
            },
```

**Comment by nicencina** [comment]
Did you ever find a solution to this? I can't figure out how to style the dates/marks/dots/etc in the main container. I noticed that even the documented examples have that section commented out:

https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js

**Comment by randomprogramming** [comment]
@nicencina Sorry for the delayed response, I ended up using a different library: https://github.com/BugiDev/react-native-calendar-strip

I managed to get all the styling I needed to work just fine in that library. YMMV

**Comment by Riqardos** [comment]
I found solution by playing with styles variables in theme attribute,  just play with these color variables
`    <Agenda
    theme={{ 
      calendarBackground: colors.background, //agenda background
      agendaKnobColor: colors.primary, // knob color
      backgroundColor: colors.background, // background color below agenda
      agendaDayTextColor: colors.primary, // day name
      agendaDayNumColor: colors.primary, // day number
      agendaTodayColor: colors.primary, // today in list
      monthTextColor: colors.primary, // name in calendar
      textDefaultColor: "red",
      todayBackgroundColor: colors.primary,
      textSectionTitleColor: colors.primary,
      selectedDayBackgroundColor: colors.primary, // calendar sel date
      dayTextColor: colors.primary, // calendar day
      dotColor: "white", // dots
      textDisabledColor: "red"
    }}
    />
  );`

**Comment by dirtbag-ctrl** [comment]
Did anyone find a solution? because the problem still exists. It does not change dynamically.

**Comment by raybelisle** [comment]
I can seem to style everything else, but not the date strip. The style variables don't seem to do anything for me. Has anyone else been able to get this to work? Have examples of how to do it?

**Comment by gatienc** [comment]
to change the background color of the event View (seems to be called reservations by the dev),
I found in the library code (src/agenda/style.js)

            backgroundColor: appStyle.reservationsBackgroundColor || appStyle.backgroundColor //TODO: remove 2nd in V2
            
but neither worked for me so i did it brutally with :
'stylesheet.agenda.main': {
          reservations: {
          backgroundColor: mycolor,

          flex: 1,
          marginTop: 104

}

**Comment by AliAmjadHassan** [comment]
For those who are struggling to change background color of container that contain events/items this worked for me:
`<Agenda
       //other props
        theme={{
          "stylesheet.agenda.main": {
            reservations: {
              backgroundColor: YOUR_COLOR_WILL_COME_HERE,
            },
          },
          //Other customization will go here like this
          calendarBackground: colors.backgroundColor,
          agendaKnobColor: colors.mid,
          backgroundColor: colors.mid,
          agendaDayTextColor: colors.backgroundColor,
          agendaDayNumColor: colors.backgroundColor,
          agendaTodayColor: colors.primary,
          monthTextColor: colors.primary,
          textDefaultColor: colors.primary,
          todayBackgroundColor: colors.light,
          textSectionTitleColor: colors.dark,
          selectedDayBackgroundColor: colors.dark,
          dayTextColor: colors.dark,
          dotColor: colors.primary,
          textDisabledColor: colors.dark,
          todayDotColor: colors.mid,
        }}
      />`

**Comment by drkuster** [comment]
> https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js

Best solution at the moment as this is how they're styling it in their source code [here](https://github.com/wix/react-native-calendars/blob/master/src/agenda/style.ts)

**Comment by drkuster** [comment]
> to change the background color of the event View (seems to be called reservations by the dev), I found in the library code (src/agenda/style.js)
> 
> ```
>         backgroundColor: appStyle.reservationsBackgroundColor || appStyle.backgroundColor //TODO: remove 2nd in V2
> ```
> 
> but neither worked for me so i did it brutally with :
> 
> 'stylesheet.agenda.main': { reservations: { backgroundColor: mycolor, flex: 1, marginTop: 104 }

Best current solution, reflects how they are styling it in the [source code](https://github.com/wix/react-native-calendars/blob/master/src/agenda/style.ts)

**Comment by chrisdev3001** [comment]
This is my custom styles, I hope it could be usefull for someone 👍 

```typescript
export const Agenda = (props: ICalendarProps) => {
  const {
    size = SizesAppEnum.sm,
    lang = '',
    minDate,
    selectedDayBackground = true,
    selectedDay,
    disabledDays,
    bookedDays,
    freeDays,
    style,
    onDayPress
  } = props

  if (lang) {
    LocaleConfig.locales[lang] = DatesLocales[lang]
  }

  LocaleConfig.defaultLocale = lang
  const { theme } = useTheme()

  return (
    <RNAgenda
      items={[]}
      pastScrollRange={1}
      futureScrollRange={2}
      minDate={minDate}
      selected={selectedDay}
      style={{ borderRadius: 16, }}
      showClosingKnob={true}
      showOnlySelectedDayItems
      hideExtraDays
      renderItem={(item) => <Text>Hola</Text>}
      onDayPress={day => { onDayPress(day.dateString) }}
      markedDates={{
        [selectedDay]: { selected: selectedDayBackground, disableTouchEvent: true, selectedColor: theme.colors.primary },
        ...disabledDays,
        ...bookedDays,
        ...freeDays
      }}      
      theme={{
        'stylesheet.agenda.main': {          
          weekdays: {
            position: PositionStylesEnum.absolute,
            left: 0,
            right: 0,
            top: 0,
            flexDirection: FlexStylesEnum.row,
            justifyContent: FlexStylesEnum.spaceAround,
            backgroundColor: theme.colors.white,
            padding: 12,
          },
          knobContainer: {
            flex: 1,
            position: PositionStylesEnum.absolute,
            left: 0,
            right: 0,
            height: 18,
            bottom: 0,
            borderBottomLeftRadius: 16, 
            borderBottomRightRadius: 16,
            alignItems: AlignStylesEnum.center,
            backgroundColor: theme.colors.white,
          },
          reservations: {
            backgroundColor: theme.colors.white,
            flex: 1,
            marginTop: 64
          }
        },
        arrowColor: theme.colors.primary,
        monthTextColor: theme.colors.primary,
        textMonthFontFamily: FontFamily.NunitoBold,
        textMonthFontSize: scale(20, size),
        textDayHeaderFontSize: scale(16, size),
        todayTextColor: theme.colors.primary,
        textDisabledColor: theme.colors.grey2,
        textSectionTitleDisabledColor: theme.colors.grey2,
        textSectionTitleColor: theme.colors.black,
        textDayFontFamily: FontFamily.OpenSansRegular,
        textDayHeaderFontFamily: FontFamily.OpenSansRegular,
        textDayFontSize: scale(16, size),
        selectedDayBackgroundColor: theme.colors.primary,
        selectedDotColor: theme.colors.primary,
        calendarBackground: theme.colors.white
      } as Record<string, any>
      }
    />
  )
}
