### ISSUE TITLE
Timeline scrollToFirst don't work

### ISSUE THREAD

**Issue by IsmetGlumcevic** [wix/react-native-calendars#1385]
I follow demo example https://github.com/wix/react-native-calendars/blob/master/example/src/screens/timelineCalendar.js

Try to style timeline items, func renderItem don't work, scrollToFirst={true} don't work.

func renderItem like same renderItem in AgendaList from https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js, style is deferent on timeline.

react-native-calendars@1.929.0 
react-native@0.63.4 
emulator: iPhone 12

**Comment by IsmetGlumcevic** [comment]
scrollToFirst work only for today, other days doesn’t work

**Comment by priyankagupta23pg** [comment]
> scrollToFirst work only for today, other days doesn’t work

it is not working even for today

**Comment by inkCrazy** [comment]
+1,
scrollToNow work, scrollToFirst. doesn't work
