### ISSUE TITLE
How to change programmatically the current day ?

### ISSUE THREAD

**Issue by Clemweb** [wix/react-native-calendars#1386]
## Description

I try to change the current day from a bouton (in a modal).
So I use a state var like this :

<Agenda
    items={this.state.items}
    loadItemsForMonth={this._getItemsFromApi.bind(this)}
    onCalendarToggled={(calendarOpened) => {}}
    onDayPress={(day)=>{this.currentDay = day;this._getItemsFromApi(this.currentDay)}}
    onDayChange={(day)=>{this.currentDay = day;this._getItemsFromApi(this.currentDay)}}
    selected={this.state.selectedDate}
    current={this.state.selectedDate}
    ... another props
/>

## Expected Behavior

I change the selectedDate with  setState({selectedDate:'2021-01-15'})
The call seems to be good (render is call correctly)

## Observed Behavior

The calendar current day doesn't change. It stay on initial day

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.1129.0
* `npm ls react-native`: npm ls react-native

Also specify:

Android Studio emulator

Is it a bug or need I do something else ?

**Comment by KurtMar** [comment]
Based on some other issues I found it seems you may need utilize the ref-property. Please see the issues and maybe they will guide you to the solution:
https://github.com/wix/react-native-calendars/issues/1196#issuecomment-652636444
https://github.com/wix/react-native-calendars/issues/1325
