### ISSUE TITLE
Agenda scroll breaks when there are missing dates.

### ISSUE THREAD

**Issue by hariks789** [wix/react-native-calendars#1387]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

While scrolling through agenda, it jumps too fast to the end of the agenda even if its 7-8 months away(with events on every weekday). There will be no keys for weekend days in the items. I am not pushing empty dates 

## Expected Behavior

Scroll through events normally without jumping fast to end.

## Observed Behavior

https://user-images.githubusercontent.com/22391855/104003941-240c6300-51c9-11eb-9193-a3e61b5aefe9.mov

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
` react-native-calendars@1.973.0
`* `npm ls react-native`:
`└── react-native@0.63.3
`
Also specify:

1. Phone/emulator/simulator & version:

iPhone 11 Simulator 

## Reproducible Demo

Add events to 5-6 months with some missing dates(like weekends) and scroll agenda. Agenda jumps to end

**Comment by sawndur** [comment]
You need to add empty objects for days that dont have an event. Run a loop through your items to add it. I'm not sure if there's a more efficient way of achieving this but that's what I did.
