### ISSUE TITLE
currentMonth doesn't change when scrolling

### ISSUE THREAD

**Issue by Gheeroppa** [wix/react-native-calendars#1392]
## Description 

Hello!

I am using CalendarList with custom arrows to change months. 

If I change the months via the arrows, in the shouldComponentUpdate I have the correct **currentMonth**, inside the reference of the calendar.

If I scroll, instead, the view is changing but not the **state**.

```
shouldComponentUpdate(nextProps: Readonly<P>, nextState: Readonly<S>, nextContext: any): boolean {
    console.log(this.calendar.state.currentMonth);
}

<CalendarList 
      ...
      renderHeader={(date) => {
          return (
              <View style={styles.header}>
                  <Button transparent
                          onPress={() => this.calendar.addMonth(-1)}
                  >
                      <Icon name="arrow-back"/>
                  </Button>
                  <Text
                      light>{moment(date.toString(), 'DD MMM YYYY').format('MMMM YYYY')}</Text>
                  <Button transparent
                          onPress={() => this.calendar.addMonth(1)}
                  >
                      <Icon name="arrow-forward"/>
                  </Button>
              </View>
          );
      }}

    ref={ref => this.calendar = ref}
/>
```

## Environment

* `npm ls react-native-calendars`: 1.1129.0
* `npm ls react-native`: 0.61.5

**Comment by Vincenttbk** [comment]
Im facing the same issue, any fix for the issue?

**Comment by hassamarifdev** [comment]
I'm facing same problem after using **customHeader** and **dayComponent**.  @Gheeroppa  if you know how to solve this problem please let me know. Thank you
