### ISSUE TITLE
 Error: Unable to resolve module `./day/multi-dot` from react-native-calendars

### ISSUE THREAD

**Issue by ManiruzzamanAkash** [wix/react-native-calendars#1394]
Hello,
I'm facing issue to use react-native calendars.

It's getting me this error -
 ```bash
Error: Unable to resolve module `./day/multi-dot` from `node_modules\react-native-calendars\src\calendar\index.js`:
 ```

#### React-native-calendars Version - `^1.1129.0`

How to solve this issue, Anyone please help.

**Comment by aminosman** [comment]
Version `1.315.0` works for me, so something happened between 315 and 1129

**Comment by castalonirenz** [comment]
Same issue with me

**Comment by auguyon** [comment]
Same issue with me. I fixed it with the version 1.315.0 but with this version I got a problem with the multi-period -> #1341 .

**Comment by jrmccann2** [comment]
`npm start -- --reset-cache` should resolve this error in most cases.

**Comment by VigneshReact** [comment]
I tried above work around. I seems to be the exact same issue. kindly help us to move forward
