### ISSUE TITLE
How to make pull to refresh work on empty days (agenda) ?

### ISSUE THREAD

**Issue by keomalima** [wix/react-native-calendars#1396]
## Description

I would like to know if there's a way to pull to refresh when the day of the agenda is empty. I made it work where there's data available, but not when there's empty days. 

## Expected Behavior

Pull to refresh on empty days

## Observed Behavior

```
<Agenda
        items={items}
        selected={date}
        onRefresh={loadTasks}
        pastScrollRange={10}
        futureScrollRange={12}
        renderEmptyData={emptyDays}
        renderItem={renderItem}
        theme={{
          agendaKnobColor: 'rgba(37, 123, 253, .2)',
        }}
      />
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1128.0 
* `npm ls react-native`: react-native@0.63.2 

Also specify:

1. Phone/emulator/simulator & version: Android/Expo

**Comment by alew140** [comment]
live issue

**Comment by starkiedev** [comment]
I'm late to this but I had the same problem and found a solution, in case it's helpful to anyone. Essentially you need to create a custom refresh control component that is rendered when the agenda is empty:

```js
import { View, Text, RefreshControl, ScrollView } from 'react-native';

...

renderEmptyData = () => {
    return (
        <ScrollView
            refreshControl={
                <RefreshControl refreshing={isRefreshing} onRefresh={this.onRefresh} />
            }
        >
            <View>
                <Text>
                    No data to display. Pull down to refresh.
                </Text>
            </View>
        </ScrollView>
    );
};
```

Then assign it to the `renderEmptyData` prop on `<Agenda>`:

```js
<Agenda
    ...
    renderEmptyData={this.renderEmptyData}
/>
```
