### ISSUE TITLE
markedDays overlap

### ISSUE THREAD

**Issue by stefan0s** [wix/react-native-calendars#14]
Hello,

Is there an option to display 2 markedDays group for ex:

(1/5/2017 - 10/5/2017) AND (10/5/2017 - 15/5/2017). How can i do that? The 10/5/2017 is end date for the first group and start date for the second. Also is there an option to have a Thumbnail on the start days??

**Comment by tautvilas** [comment]
Hi, currently there is no support for overlap or thumbnail. These are marking styles that are supported:
![screen shot 2017-05-17 at 11 00 42](https://cloud.githubusercontent.com/assets/1044090/26144355/279b7a6c-3af1-11e7-9798-88c1b99e34bd.png)

**Comment by phl25** [comment]
Is there a way by now to achieve overlapping marked periods e.g. that the overlapping day is transparent or with a dashed border?
