### ISSUE TITLE
Custom day component state is undefined 

### ISSUE THREAD

**Issue by dennisbouwpas** [wix/react-native-calendars#1408]
## Description

I get undefined when trying to implement custom day component 

## Expected Behavior

dayComponent={({date, state}) => {
    return (
      <View>
        <Text style={{textAlign: 'center', color: state === 'disabled' ? 'gray' : 'black'}}>
          {date.day}
        </Text>
      </View>
    );
  }}

## Observed Behavior

state === undefined

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.1249.0
* `npm ls react-native` : 0.63.4

**Comment by adamsolomon1986** [comment]
+1

**Comment by mhaussai** [comment]
Hi I have the same problem, marking props is also undefined.

**Comment by debold-tech** [comment]
same issue as in #1393
The patch in #1407 fixed it for me too

**Comment by johnjoshuadablo** [comment]
+1

**Comment by JamesKindyHub** [comment]
+1
