### ISSUE TITLE
Is it possible to have fixed weekday header on CalendarList?

### ISSUE THREAD

**Issue by bojans1005** [wix/react-native-calendars#1409]
## Description

Currently `CalendarList` shows week days on each month, is it possible to have this fixed at the top?

## Expected Behavior

Have an option to have fixed week days at the top or bottom.

## Observed Behavior

Week days header is shown on each month
![image](https://user-images.githubusercontent.com/67975929/107540252-92ea3b00-6c11-11eb-9b56-b08e8e339830.png)

## Environment

* `npm ls react-native-calendars`: 1.1249.0
* `npm ls react-native`: 0.62.2

**Comment by yiheinchai** [comment]
I have the same question, any solutions so far?

**Comment by MursiDirect** [comment]
I have the same problem, too. Any help, please?
