### ISSUE TITLE
Agenda | How to show month view default instead of the week view.

### ISSUE THREAD

**Issue by vijaydadhich09** [wix/react-native-calendars#1410]
I am using Agenda component. I want to show a whole month in the header instead of the week with horizontal next previous arrow icons. The header always is in an open state and in month view should be horizontal with arrow buttons. Any solution.

**Comment by IKTANIM** [comment]
I also need the month view instead of the week view while showing the agenda. Do you find any solution? @vijaydadhich09 

> I am using Agenda component. I want to show a whole month in the header instead of the week with horizontal next previous arrow icons. The header always is in an open state and in month view should be horizontal with arrow buttons. Any solution.
