### ISSUE TITLE
Error: Unable to resolve module `./day/multi-dot` from react-native-calendars

### ISSUE THREAD

**Issue by prateekuttreja2020** [wix/react-native-calendars#1411]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

react-native-calendars: "1.1249.0"
react-native: "0.63.2"

## Expected Behavior

It should be working

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
error: Error: Unable to resolve module `./day/multi-dot` from `node_modules/react-native-calendars/src/calendar/index.js`: 

None of these files exist:
  * node_modules/react-native-calendars/src/calendar/day/multi-dot(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native-calendars/src/calendar/day/multi-dot/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:"1.1249.0"
* `npm ls react-native`:"0.63.2"

Also specify:

1. Phone/emulator/simulator & version: iphone 6plus

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by meliodev** [comment]
Yeah same problem for me under version 1.1249.0.
I get the following error:
```
Error: Unable to resolve module `./day/multi-dot` from `node_modules\react-native-calendars\src\calendar\index.js`:
None of these files exist:
  * node_modules\react-native-calendars\src\calendar\day\multi-dot(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-calendars\src\calendar\day\multi-dot\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

**Comment by lmerilees** [comment]
Having the same problem.
react-native-calendars:"1.1247.0"
react-native:"0.63.4"

Getting the error: 

`error: Error: Unable to resolve module `./day/multi-dot` from `node_modules\react-native-calendars\src\calendar\index.js`:

None of these files exist:
  * node_modules\react-native-calendars\src\calendar\day\multi-dot(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)       
  * node_modules\react-native-calendars\src\calendar\day\multi-dot\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx) `

**Comment by ravishankar1308** [comment]
It's work for me with

`react-native link`
