### ISSUE TITLE
CalendarList is not evenly spaced vertically

### ISSUE THREAD

**Issue by stefaniesatna** [wix/react-native-calendars#1412]
## Description

When rendering a CalendarList component in a vertical configuration, the individual calendars are not spaced evenly. Depending on the number of week rows in the calendar the space between it and the subsequent calendar will vary.

This appears to be an issue with the way `getItemLayout` in the CalendarList class calculates the position of the calendars based on a fixed height.

This issue does not appear to be present in the example images / gif in the README.

## Expected Behavior

Calendars to be laid out evenly regardless of week row count

## Observed Behavior

Calendars are variably spaced depending on rendered week rows as a result of the `getItemLayout` method on the `CalendarList` class

## Environment

```
└── react-native-calendars@1.1249.0 
└── react-native@0.63.2
```

iPhone 8 (iOS 14.3)

## Reproducible Demo

Behaviour is the same in the included CalendarList example of this repo

**Comment by yiheinchai** [comment]
I have the same issue, any solutions so far?

**Comment by stefaniesatna** [comment]
Hey @yiheinchai, no good news here, I've decided to just live with it in the end. Let me know if you find one though!
