### ISSUE TITLE
Calendar doesn't respect its height

### ISSUE THREAD

**Issue by sperardt** [wix/react-native-calendars#1415]
Hi There,
I am using the calendar in my app, I am setting the height on its style as the doc shows, but it doesn't seem to get it applied. 

## Expected Behavior

_What action did you perform, and what did you expect to happen?_
I set Calendar height, border and etc on 'style' prop. I expected that when playing with height on style prop, it would affect numbers container and fit them into the previous height.

_What actually happened when you performed the above actions?_
It doesn't respect the defined height on smaller resolution, such as iphone SE. Have changed the height multiple times, it changes the height of the are with gray border, but the numbers container doesn't have its height affected. (see on attached screenshot)

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.1249.0
* `npm ls react-native`: react-native@0.63.4

Also specify:

1. Phone/emulator/simulator & version: iphone SE (2nd generation), nexus One and Pixel_3a.

## Reproducible Demo

```
<SafeAreaView>
            <Calendar
                // Specify style for calendar container element. Default = {}
                style={{
                    borderWidth: 5,
                    borderColor: 'gray',
                    height: 100
                }}
                // Specify theme properties to override specific styles for calendar parts. Default = {}
                theme={{
                    backgroundColor: '#ffffff',
                    calendarBackground: '#ffffff',
                    textSectionTitleColor: '#b6c1cd',
                    textSectionTitleDisabledColor: '#d9e1e8',
                    selectedDayBackgroundColor: '#00adf5',
                    selectedDayTextColor: '#ffffff',
                    todayTextColor: '#00adf5',
                    dayTextColor: '#2d4150',
                    textDisabledColor: '#d9e1e8',
                    dotColor: '#00adf5',
                    selectedDotColor: '#ffffff',
                    arrowColor: 'orange',
                    disabledArrowColor: '#d9e1e8',
                    monthTextColor: 'blue',
                    indicatorColor: 'blue',
                    textDayFontFamily: 'Montserrat-Bold',
                    textMonthFontFamily: 'Montserrat-Bold',
                    textDayHeaderFontFamily: 'Montserrat-Bold',
                    textDayFontWeight: '300',
                    textMonthFontWeight: 'bold',
                    textDayHeaderFontWeight: '300',
                    textDayFontSize: 16,
                    textMonthFontSize: 16,
                    textDayHeaderFontSize: 16
                }}
                />
        </SafeAreaView>
```
<img width="1321" alt="Screen Shot 2021-02-18 at 11 36 49 AM" src="https://user-images.githubusercontent.com/25747543/108446043-51115400-7212-11eb-8900-185377c0309c.png">

**Comment by sperardt** [comment]
Found the solution.

I needed to override a couple of styles on the following files: https://github.com/wix/react-native-calendars/blob/master/src/calendar/day/period/style.js

https://github.com/wix/react-native-calendars/blob/master/src/calendar/header/style.js

Basically, on header needed to reduce the font size. If using period, you also will need to play with fontSizes and period height because it is hardcoded on 34.

**Comment by srivastavaanurag79** [comment]
still getting this issue

**Comment by DavidInojosa** [comment]
same issue here

**Comment by zhellDarwin** [comment]
Any one found solution??

**Comment by DavidInojosa** [comment]
My solution was to make height dynamic with ternary operator inside style, like this:
{
height: needMoreSpace ? 200 : 100
}

and setting a margin bottom will help too, if u need.
