### ISSUE TITLE
Set the default Agenda view to dragged state

### ISSUE THREAD

**Issue by Dan547** [wix/react-native-calendars#142]
I was wondering if there is a way to set the default agenda few to the dragged state rather than being opened on todays date?

Any help with this would be very appreciated!

**Comment by tautvilas** [comment]
hey, unfortunately currently there is no such feature

**Comment by dseawel** [comment]
It's kind of a hack, but this should do the trick...

`import React from 'react';
import { CalendarList, Agenda } from 'react-native-calendars';

class MyCalendar extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      dateSelected: null,
    }
  }

  render() {
    const CalendarComponent = this.state.dateSelected ? Agenda : CalendarList;
    return (
      <CalendarComponent
        onDayPress={(dateSelected) => this.setState({dateSelected})}
      />
    );
  }
}

export default MyCalendar;
`
