### ISSUE TITLE
renderHeader={(date) => {/*Return JSX*/}} -- this function receives date which is always ahead of selected month

### ISSUE THREAD

**Issue by Yandamuri** [wix/react-native-calendars#1423]
## Description
    
This is my calendar implementation with `renderHeader` prop,

        <CalendarList
                    current={currentDate}
                    firstDay={1}
                    ref={ref => this.myCalendarRef = ref}
                    horizontal={true}
                    pagingEnabled={true}
                    onVisibleMonthsChange={months => this.onSwipeMonths(months)}
                    renderHeader={(date) => this.renderCalendarHeader(date)}
		    onDayPress={(day) => this.getActivities(day)}
        />

This is custom header implementation where I logged `date`

       renderCalendarHeader(date) {
            console.log(date);
       }

here is the out put when the calendar is rendered first time,

      Wed, 24 Feb 2021 00:00:00 GMT
      Wed, 24 Mar 2021 00:00:00 GMT
      Sun, 24 Jan 2021 00:00:00 GMT
     (Assume I open calendar on 24 Feb 2021)

From next time onwards when ever month is changed the date parameter passed to the function is always one month ahead to the selected month like follows

     Sat, 24 Apr 2021 00:00:00 GMT (in this case I have changed calendar to next month that is March)

## Expected Behavior

when the month is changed through swipe or arrow press that selected month to be passed to custom header function

## Observed Behavior

But always passed date is one month ahead to the selected month

## Environment

* `react-native-calendars`: **1.1252.0**
* ` react-native`: **"0.63.2"**

Also specify:

1. Phone/emulator/simulator & version: Pixel_4_API_29

Later I noticed that same thing is happening with `dayComponent={({date, state, marking }) => this.renderDayComponent(date, state, marking)}` which is also passing wrong date as described above

**Comment by theneekz** [comment]
I had to do some string manipulation to get this to work.
`    const dateStr = date.toISOString();
    const endIndex = dateStr.indexOf("T");

    const title = moment(dateStr.slice(0, endIndex)).format("MMMM YYYY");`
