### ISSUE TITLE
How to avoid highlight today in calendar.

### ISSUE THREAD

**Issue by DarkPonyBee** [wix/react-native-calendars#1425]
Hi, Team.
This library is awesome. 
But calendar highlights today's date by default.
I want to ignore highlighting today but I couldn't find a solution.
Is it impossible?

**Comment by vuon0029** [comment]
Hi, try remove
`todayTextColor: "red",`
in your theme prop

**Comment by kamarajFinancePeer** [comment]
Is there any props available to avoid highlight today in calendar.
