### ISSUE TITLE
There's no indicator of date selected.

### ISSUE THREAD

**Issue by earnestware** [wix/react-native-calendars#1426]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Component doesn't honor the theme setting (background color). There's no indicator of date selected.

## Expected Behavior
By default, the selected date should show with background color - circled.
What action did you perform, and what did you expect to happen?
npm install --save react-native-calendars
put a Calendar component in a screen
## Observed Behavior

What actually happened when you performed the above actions?
Doesn't show the circled highlight for selected date in simulator 

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1254.0 
* `npm ls react-native`: react-native@0.63.4 

Also specify:

1. Phone/emulator/simulator & version:
12.3 (940.20)
## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by ddikodroid** [comment]
Yes, same here, when I press day, the circle did not appear as in the preview

**Comment by ddikodroid** [comment]
OK, I found the solution
I'm using useState
`
let today = new Date().toISOString().slice(0,10)
const [selectedDate, setSelectedDate] = useState(today)

<Calendar
...otherProps
markedDates={{
[selectedDate] : {selected: true}
}}
/>
`
