### ISSUE TITLE
Year View 

### ISSUE THREAD

**Issue by RUIFERNANDE5** [wix/react-native-calendars#143]
Hey,
first I'd like to thank you all this great component.

I'd suggest you guys, in conjunction with the horizontal swippable agenda (which was already requested by a couple people) add a Year view, where you would be able to swipe the year and show on a customizable number of columns for the 12 months.

I'm currently able to achieve this using [react-native-snap-carousel](https://github.com/archriss/react-native-snap-carousel) in conjunction with a cycle of 12 numbers and setting the min and max Date allowed dynamically (although I'm not sure if the component works if I set 31 on maxDate and the month only has 30 or less days?) 

**Edit:** The component automatically knows the end of the month, thats not a problem.

Thanks in advance.

**Comment by RUIFERNANDE5** [comment]
Did anyone implement multiple calendar components in the same view without a very slow initial rendering?

**Comment by madhubalan** [comment]
Hi,
Still this slow initial rendering problem exist while implement multiple calendar any solution for this.

**Comment by iosfitness** [comment]
@RUIFERNANDE5 Any inputs on how I can show a year view something like this 


<img width="457" alt="screen shot 2018-05-30 at 12 56 32 pm" src="https://user-images.githubusercontent.com/18075005/40708258-a259a302-6410-11e8-9b5e-d4ccd8150c17.png">

**Comment by yashwantgarad495** [comment]
@iosfitness did you done with this year view implemetation ? if yes, can you please share the idea how you did

**Comment by 000xuandu** [comment]
@iosfitness 
I also need to display all months of the year (12 months). It is welcome if you give me a solution.

**Comment by christinayiebiyo** [comment]
@RUIFERNANDE5 Can you please share how you were able to implement the calendar yearly view using react-native-snap-carousel? I'm a new react native developer and haven't been able to implement a calendar with yearly view.

**Comment by hdrabs** [comment]
Is anyone here able to make a year view with any library? Please help!

**Comment by pohsiu** [comment]
+1

**Comment by TalhaKhanNiazii** [comment]
I need to view all 12 months on a single screen. I am currently using react-native-calendars, can anyone help me with this?
