### ISSUE TITLE
| Calendar | "Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?"

### ISSUE THREAD

**Issue by longb1997** [wix/react-native-calendars#1435]
Hi There,
I am using the calendar in my app, it's working but got this error.

```
ExceptionsManager.js:179 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Calendar`.
```

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.1254.0
"react-native": "0.63.4",

**Comment by lenhatminh0528** [comment]
i'm facing the same error...

**Comment by sajorahasan** [comment]
facing the same issue with latest version 1.1280.0 and react-native 0.68.0

**Comment by yiheinchai** [comment]
same issue here
