### ISSUE TITLE
How to style extra days separately?

### ISSUE THREAD

**Issue by Sunhat** [wix/react-native-calendars#1436]
Hi, firstly thank you for the great calendar, it's been a extremely helpful for my app to get started!

## Description
I've been using `CalendarList` like this:

```
<CalendarList
    hideExtraDays={false}
    dayComponent={dayComponent}
/>
```

I'm applying a custom format & style to the dayComponent to make this a full-screen calendar for displaying events. For this, I'd like to display `extra days`, but style them with a low opacity to indicate they're not of this current calendar month. 

I'm unable to for any typings for styling extra days in your `index.d.ts` and was hoping there's a solution to this and if not, I'm requesting it be one as it would be very useful for myself and I think others too :) Thanks!

**Comment by vakhoElis** [comment]
Same problem here

**Comment by Sunhat** [comment]
@wixmobile

**Comment by paskalov-aris** [comment]
Same

**Comment by OHHAKO** [comment]
same

**Comment by willashley23** [comment]
same
