### ISSUE TITLE
Month scrolling problem using arrows

### ISSUE THREAD

**Issue by sn4f** [wix/react-native-calendars#1438]
## Description
HI,

I have a problem with scrolling the month. By using the arrows everything is fine until I start scrolling the month through the slide. Look at video

any ideas how I can fix it?

## Environment
Latest react-native-calendars package without custom features

## Reproducible Demo
[Link to video](https://streamable.com/g2i0ev)

**Comment by jtalz** [comment]
did you try uninstalling and reinstalling the package?

**Comment by sn4f** [comment]
@jtalz yes and same problem

**Comment by jtalz** [comment]
is this calendar or calendarlist?

**Comment by jtalz** [comment]
maybe you're missing some properties like this: 
`// Handler which gets executed when press arrow icon left. It receive a callback can go back month
  onPressArrowLeft={subtractMonth => subtractMonth()}
  // Handler which gets executed when press arrow icon right. It receive a callback can go next month
  onPressArrowRight={addMonth => addMonth()}`

**Comment by jodrescher** [comment]
We had the same problem. I submitted an [PR](https://github.com/wix/react-native-calendars/pull/1451). This fixed it for us.

**Comment by jtalz** [comment]
there u go

**Comment by Inbal-Tish** [comment]
@sn4f See PR #1451
