### ISSUE TITLE
ExpandableCalendar: Pan not very sensitive

### ISSUE THREAD

**Issue by dpmika** [wix/react-native-calendars#1442]
## Description

I am using the ExpandableCalendar component and When I try to close the calendar with the gesture, it stays open. This is because the gesture must go to the end (top) of the calendar. This makes the closing not very sensitive

## Expected Behavior

I saw that there is a parameter that is calculated to understand if the swipe has been done up to the other or not 

**const threshold = this.openHeight / 1.75;**

 is it possible to make this parameter dynamic by passing it as a prop to the component?

Thank you

**Comment by lidord-wix** [comment]
Released in version 1.1259.0
