### ISSUE TITLE
Gray out past days but keep them selectable.

### ISSUE THREAD

**Issue by lolo-io** [wix/react-native-calendars#1452]
## Description

Hi, I'd like to render the past days a different way than the future days. The only solution I found is disabling them, but it removes the callback to get the press event in onDayPressed.
I need to render past days a different way but still be able to click and select them.
Is there a way to acheive this ? 

## Expected Behavior

Enable onDayPressed on disabled days.

**Comment by remotenode** [comment]
> Did you find a way to make it? 🙏

You can create your own day component and while rendering decide how it should look like and etc.

Juse like [here](https://github.com/wix/react-native-calendars#overriding-day-component)
