### ISSUE TITLE
CalendarList rerender

### ISSUE THREAD

**Issue by dejawho** [wix/react-native-calendars#1457]
Hi, I'm using a CalendarList to render a list of calendars. I use the dayComponent props to define a custom appearance for the days and pass the data using markedDates, everything work and my calendars render correctly.
Now I want to tap a day and highlight it, so I added in my dayComponent a touchableopacity that detect the touch and store the current date in the state of the component that contains the calendar.
I can force a rerender by cloning the markedDates, but doing this the clander slowdown for a couple of sencods, is there a better way to do this? 
I've tried using the property "selected" but it doesn't seem to do anything.

I'm using the version 1.1255.0

**Comment by mleister97** [comment]
Hey, I am also facing performance issues. You can see this Issue https://github.com/wix/react-native-calendars/issues/1453
Unfortunately I have not received an answer yet.

**Comment by LeeJunhui** [comment]
same question,any workaround here?

**Comment by dejawho** [comment]
In the end I overrrided calendarlist, calendar and day to be able to access the shouldComponmentUpdate of each one and provide my own logic

**Comment by LeeJunhui** [comment]
> In the end I overrrided calendarlist, calendar and day to be able to access the shouldComponmentUpdate of each one and provide my own logic

Soga, I've just add a console.log in the day/index.js render method, and when I press a day on the screen, the console only output the day I pressed.But if I provide my custom day component, almost three months will be rerendered. I will try your solution soon.

**Comment by LeeJunhui** [comment]
> In the end I overrrided calendarlist, calendar and day to be able to access the shouldComponmentUpdate of each one and provide my own logic

I've solved my problem of the Calendar custom day component rerender once I update the marked dates prop.My plan is to make day component function memorized and change the state inside the function once the marking object changed which is deconstructured from dayProp.

**Comment by mleister97** [comment]
I guess this issue is also performance related right?
I am also facing huge performance issues with this library.
https://github.com/wix/react-native-calendars/issues/1453

**Comment by Dassine** [comment]
@leejunhui were you able to memorize the day component? It doesn't seem to work on my side.
Any solution?

**Comment by leejunhui** [comment]
@Dassine Hi, it's been a year ago since I forked this repo.You can check my forked repo to find some pieces of code which can help you.

**Comment by AdamGerthel** [comment]
@Dassine I'm having the same issue with memoizing custom day components. I've had some success using `useCallback`, see https://snack.expo.dev/@insats/rn-calendar-day-re-render however, I haven't been able to pass custom data without re-rendering all of the days.
