### ISSUE TITLE
Agenda - Sample data not the same as in the gif, instructions unclear

### ISSUE THREAD

**Issue by bfarrgaynor** [wix/react-native-calendars#1459]
It's unclear how to achieve the results of the demo in the Agenda demo gif.
https://github.com/wix-private/wix-react-native-calendar/blob/master/demo/agenda.gif?raw=true

... passing in anything into render day doesn't actually pass the date in for the value of 'day' and the default date list item only shows the date on the left side and not the actual title of the event like it does in the gif.

**Comment by bfarrgaynor** [comment]
I see this is a duplicate of this:
https://github.com/wix/react-native-calendars/issues/388

Generally this needs documentation help. I still can't get it to render using the examples.

**Comment by rvk7895** [comment]
> I see this is a duplicate of this:
> #388
> 
> Generally this needs documentation help. I still can't get it to render using the examples.

Have u able to find a suitable way to recreate the GIF examples?
