### ISSUE TITLE
Interval marking

### ISSUE THREAD

**Issue by stefan0s** [wix/react-native-calendars#146]
Hello,

I would like to have Interval marking but having endingDay AND startingDay true for the same day.

markedDates={
    {'2012-05-20': [{textColor: 'green'}],
     '2012-05-22': [{startingDay: true, color: 'green'}],
     '2012-05-23': [{{startingDay: true, endingDay: true, color: 'green', textColor: 'gray'}],
     '2012-05-24': [{endingDay: true, color: 'green'}]
    }}

That means the the 23rd will be split into the two groups [22/5 - 23/5] and [23/5 - 24/5] and colored half and half. Is something like that supported? I suppose this is very easy to implement. no?

**Comment by stefan0s** [comment]
@tautvilas the following code on calendar/day/interactive/index.js support same start/end day for groups ex. [22/9 - 23/9] and [23/9 - 29/9]

the code bellow breaks if you have single day with startingDay: true and endingDay: true so in that case you must have an extra property like single: true.


else if (flags.endingDay && flags.startingDay) {
        rightFillerStyle = {
          backgroundColor: flags.startingDay.color,
          borderBottomLeftRadius: 17,
          borderTopLeftRadius: 17
        };
        leftFillerStyle = {
          backgroundColor: flags.endingDay.color,
          borderBottomRightRadius: 17,
          borderTopRightRadius: 17
        };
        containerStyle.push({
          backgroundColor: 'transparent'
        });
      }

**Comment by tautvilas** [comment]
Hi, did you check the example? In the bottom calendar there is marking of single day that is both starting day and ending day.

**Comment by overengineered** [comment]
What do you expect to be rendered visually, when a day participates in 2 ranges? Would this be ok?

![2ranges](https://user-images.githubusercontent.com/2990253/30431658-f79ef61a-9967-11e7-9879-64676d675b72.jpeg)

**Comment by stefan0s** [comment]
I was expecting something like this. 2 seperate events that the first finish and the second start on the same day. I have seen similar functionality on AirBnb calendar.


![screenshot_20170914-162310](https://user-images.githubusercontent.com/13720159/30432123-5e65909c-9969-11e7-84f2-9c580e268790.png)
