### ISSUE TITLE
dayComponent prop state doesn't exist

### ISSUE THREAD

**Issue by Sunhat** [wix/react-native-calendars#1461]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

dayComponent prop state doesn't exist

## Expected Behavior

props.state to exist

## Observed Behavior
props.state is undefined

## Environment

Android 10, React Native latest

Also specify:

Android 10, React Native latest

## Reproducible Demo

None, it's simple though

**Comment by suhailaleryani** [comment]
Hi
I am having the same problem and in my case i do not have the marking prop.
This is the log of the props in :

```
dayComponent={(props) => console.log(props).........}

{"date":{"year":2021,"month":4,"day":24,"timestamp":1619222400000,"dateString":"2021-04-24"},"testID":"native.calendar.SELECT_DATE_SLOT-2021-04-24","accessibilityLabel":" Saturday 24 April 2021 ","children":24}
```
No marking no state

Thank you very much

**Comment by Inbal-Tish** [comment]
@Sunhat  @suhailaleryani Please follow PR #1407
