### ISSUE TITLE
Disable / Hide the Calendar Banner in Agenda Component

### ISSUE THREAD

**Issue by JosephVasse** [wix/react-native-calendars#1462]
## This is a feature request. 

I hope this hasn't been asked yet or this isn't doable yet.
If it is let me know and i'll delete this and go back in my cave

## Description

I believe it would be usefull to have an agenda Component that would jsut be a scrollable list without any interactions on a calendar. 
I'm aware that this is doable whithout this package but i believe this would be appreciated. 

## Expected Behavior

Have a prop or another component that would allow the developper to show/or not the "calendar" banner on the top of the agenda.

**Comment by lolo-io** [comment]
I'd like that too :)
