### ISSUE TITLE
The Android release build crash on render the component <Calendar />

### ISSUE THREAD

**Issue by erbud** [wix/react-native-calendars#1470]
## Description

In the development version works fine but, when building the release version on Android, the <Calendar /> component (even without passing any properties to it) causes an error, I doubt if from JS or Native. I don't know how to debug it. Can it be a problem minimizing the code for the release version?

If I don't render the <Calendar /> component in the release version, the error is not reproduced in the app.

## Expected Behavior

Don't trigger the JS or Native error.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1258.0
* `npm ls react-native`: react-native@0.63.2
* `expo diagnostics`:

```
Expo CLI 4.4.3 environment info:
  System:
    OS: macOS 11.2.3
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    npm: 6.9.0 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    @expo/webpack-config: ^0.12.58 => 0.12.63 
    expo: ^40.0.0 => 40.0.1 
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
    react-native-web: ^0.14.13 => 0.14.13 
  npmGlobalPackages:
    expo-cli: 4.4.3
  Expo Workflow: managed
```

Also specify:

1. Phone/emulator/simulator & version: Phone, Samsung Galaxy A8 / Android 9

## Reproducible Demo

```
import { Calendar } from 'react-native-calendars';

class CalendarContainer extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (<Calendar />);
  }
}
```

**Comment by erbud** [comment]
Debugging I see that XDate is the culprit. I will try to use Moment instead of XDate to fix the problem.

If I get any progress, I comment.

Regards,

**Comment by mehthabux** [comment]
im also facing the same issue

**Comment by erbud** [comment]
Sorry for bothering you. It was my mistake. The language (null) didn't reach him in some cases…
