### ISSUE TITLE
Timeline calendar events height issue

### ISSUE THREAD

**Issue by KristinaHus** [wix/react-native-calendars#1486]
## Description

I've copied an example code from /example/srs/screens/timelineCalendar.js. It shows the event calendar as expected, but it does not render the events int's-self. When I looked into events it generates, I saw the negative values for `top` and `height`

## Expected Behavior

Expected to see the list of events

## Environment

Please run these commands in the project folder and fill in their results:

* `react-native-calendars@1.1259.0`:
* `expo@40.0.1`:

Reproduced this behavior on both IOS simulator and Android device.

## Reproducible Demo

Example code from /example/srs/screens/timelineCalendar.js

**Comment by huy312100** [comment]
I have the same problem. Can anyone have any solutions?
