### ISSUE TITLE
Disabled days => disable onPress?

### ISSUE THREAD

**Issue by slorber** [wix/react-native-calendars#149]
Currently when a calendar item is marked as disabled, it's still possible to press on it.

Is it a mistake or intended behavior?

If it is intended, can we permit to disable press as well?

**Comment by tautvilas** [comment]
Handling on press depends on client. By disable press you mean remove touchable effect?

**Comment by slorber** [comment]
@tautvilas my usecase is to provide custom marked dates with the agenda, and to disable all dates of the past. Disabling dates is possible thanks to my other PR but after being disabled they still can be clicked in the agenda

**Comment by nathanloisel** [comment]
This is my code for ignoring onDayPress on disabled dates :
`_onDayPress = (day) => {
    const { disabledDates } = this.props;
    const value = new Date(day.dateString);
    if (disabledDates.some(date => moment(date).format('YYYY-MM-DD') === day.dateString)) {
      return;
    }
    this.setState({ value }, () => {
      this.props.onChange(value);
      this._closeCalendar();
    });
  };`

**Comment by slorber** [comment]
@nathanloisel I'm using the Agenda, and I can't override the `onDayPress`, there's only a callback that is called but I can't prevent day press from this callback:

```

  _chooseDayFromCalendar(d) {
    this.chooseDay(d, !this.state.calendarScrollable);
  }

  chooseDay(d, optimisticScroll) {
    const day = parseDate(d);
    this.setState({
      calendarScrollable: false,
      selectedDay: day.clone()
    });
    if (!optimisticScroll) {
      this.setState({
        topDay: day.clone()
      });
    }
    this.setScrollPadPosition(this.initialScrollPadPosition(), true);
    this.calendar.scrollToDay(day, this.calendarOffset(), true);
    if (this.props.loadItemsForMonth) {
      this.props.loadItemsForMonth(xdateToData(day));
    }
    if (this.props.onDayPress) {
      this.props.onDayPress(xdateToData(day));
    }
  }
```

Also, your code probably works but shouldn't it be made easier by the lib?

I think it's a decent behavior to expect disabled dates to not be pressable no?

**Comment by slorber** [comment]
@tautvilas if you don't want to make disabled dates unpressable (which imho you should), would you accept a PR with a solution like this:

```javascript
chooseDay(d, optimisticScroll) {
    const day = parseDate(d);

    if (this.props.onDayPress) {
      const onDayPressReturn = this.props.onDayPress(xdateToData(day));
      if ( onDayPressReturn === false ) {
        return; // Ignore day press
      }
    }
    // ... Update state
  }
``` 

I don't like this solution but can't see any other option

**Comment by MyGuySi** [comment]
I feel as though disabled dates should be unpressable as the touch effect is misleading, why would you disable a date but still want it to be allowed to be pressed?

The alternative is to add a prop to switch that behaviour on or off like so:

```
<CalendarList
  allowDisabledSelection={false}
  ...
/>
```

**Comment by slorber** [comment]
this would cover my usecase as well. I can make a PR if @tautvilas agrees

**Comment by MyGuySi** [comment]
Not quite sure on the best way to approach it though. `TouchableOpacity` is rendered in the Day components so to remove the effect that component shouldn't be rendered. I've got a quick and dirty solution working but it's probably not the best way to do it:

```js
if (typeof marking.disabled !== 'undefined' ? marking.disabled : this.props.state === 'disabled') {
  return (
    <View style={containerStyle}>
      <Text style={textStyle}>{String(this.props.children)}</Text>
      {dot}
    </View>
  )
}
```

**Comment by MyGuySi** [comment]
Ignore that last comment... I forgot that `TouchableOpacity` has a `disabled` prop, could use that instead?

```js
// calendar/day/basic/index.js

render() {
  ...

  return (
    <TouchableOpacity
      style={containerStyle}
      onPress={this.onDayPress}
      disabled={
        typeof marking.disabled !== "undefined"
          ? marking.disabled
          : this.props.state === "disabled"
      }
    >
      <Text style={textStyle}>{String(this.props.children)}</Text>
      {dot}
    </TouchableOpacity>
  );
}
```

**Comment by MyGuySi** [comment]
Made the changes in my fork, happy to submit as a PR if it's suitable: https://github.com/MyGuySi/react-native-calendars/commit/be2914fbea3faa886ee39e98df4bd70a304d65b2

**Comment by MyGuySi** [comment]
I've kicked off a PR https://github.com/wix/react-native-calendars/pull/255 with my suggested solution but probably better to discuss it there. Could take a while before it's merged

**Comment by tautvilas** [comment]
Merged the PR, just keep in mind that it only solves the problem for basic day

**Comment by MyGuySi** [comment]
Thanks, if I get time I’ll add it for other days too

**Comment by slorber** [comment]
thanks :)

**Comment by tautvilas** [comment]
Hey, I changed implementation again. Apparently the merge of PR introduced regression that you can not click on disabled days of previous month to switch to that month in <Calendar /> view. #317 

Now I added explicit properties that you can add to basic marking https://github.com/wix/react-native-calendars#date-marking

Now you can specify activeOpacity to specify touch effect or disableTouchEvent to completely ignore touch events for that day. What do you think?

**Comment by slorber** [comment]
hi @tautvilas that's great news because I was just about to report that bug :)

When we are the 29 of january and the agenda's calendar was folded, it was impossible to click on other month's day. Will try the new release soon.

**Comment by Liqiankun** [comment]
```
<TouchableOpacity
        testID={this.props.testID}
        style={containerStyle}
        onPress={this.onDayPress}
        onLongPress={this.onDayLongPress}
        activeOpacity={marking.activeOpacity}
        disabled={marking.disableTouchEvent || isDisabled}
      >
        <Text allowFontScaling={false} style={textStyle}>{String(this.props.children)}</Text>
        {dot}
      </TouchableOpacity>
```
`disabled={marking.disableTouchEvent || isDisabled}`

**Comment by bluenex** [comment]
I am on react-native-calendars `1.403.0` and still see this problem. 

I use `Agenda` component with several props like this:

```js
<Agenda
  items={{
      '2020-11-03': [...],
      '2020-11-06': [...],
      '2020-11-14': [...],
  }}
  ...
  markedDates={{
      '2020-11-03': { disabled: false, marked: true },
      '2020-11-06': { disabled: false, marked: true },
      '2020-11-14': { disabled: false, marked: true },
  }}
  disabledByDefault
>
```

Even though all the days are disabled and grey out, they are still pressable and received touch event. Anyway, to overcome this? I have followed the related issues and PRs but found no clue on this.

**Comment by Antlitz** [comment]
for those, who's still have this trouble "react-native-calendars": "^1.1129.0"
```js
<Agenda
  items={{
    '2020-11-03': [...],
    '2020-11-06': [...],
    '2020-11-14': [...],
  }}
  ...
  markedDates={{
    '2020-11-03': { disabled: false, marked: true },
    '2020-11-06': { disabled: false, marked: true },
    '2020-11-14': { disabled: false, marked: true },
  }}
  disableAllTouchEventsForDisabledDays //add this prop
>
```
