### ISSUE TITLE
DayComponent does not work properly

### ISSUE THREAD

**Issue by in4core** [wix/react-native-calendars#1493]
dayComponent - always returns state as undefined , cant get  is that selected / disabled and so on

**Comment by davidbiller** [comment]
same here.

**Comment by tnghia944** [comment]
same here.

**Comment by tnghia944** [comment]
hi @davidbiller  @in4core  any solution ?

**Comment by AmitHBhagat** [comment]
I am also facing the same issue.

"dayComponent" is passing following props for the "selected" & "disabled" dates respectively :

{"accessibilityLabel": " Sunday 16 May 2021 selected You have no entries for this day ", "children": 16, "date": {"dateString": "2021-05-16", "day": 16, "month": 5, "timestamp": 1621123200000, "year": 2021}, "testID": "native.calendar.SELECT_DATE_SLOT-2021-05-16"}

{"accessibilityLabel": " Wednesday 19 May 2021 disabled ", "children": 19, "date": {"dateString": "2021-05-19", "day": 19, "month": 5, "timestamp": 1621382400000, "year": 2021}, "testID": "native.calendar.SELECT_DATE_SLOT-2021-05-19"}

"state" & "marking" are missing above.

Someone please suggest a viable solution?

**Comment by in4core** [comment]
Solution is in hands - in dayComponent - change Component line to Day - 

const Component = this.getDayComponent();
        const dayProps = extractComponentProps(Day, this.props);
        
        this lines

**Comment by AmitHBhagat** [comment]
Thank you @in4core, it served the purpose.
I have made the above change in the "..\node_modules\react-native-calendars\src\calendar\day\index.js" file.
Although, if there is some solution that could be applied from outside the node_modules, then please let me know.

**Comment by SatyamBansal** [comment]
> extractComponentProps
@AmitHBhagat @in4core can you please suggest exactly what you did to fix this. I also need marking prop for custom day component. I did above mentioned changes in "..\node_modules\react-native-calendars\src\calendar\day\index.js", but there is no function named "extractComponentProps" therefore its throwing error 

![image](https://user-images.githubusercontent.com/19202937/121513671-bb8c1100-ca08-11eb-88c9-2c4c4ccfecaa.png)

**Comment by hkbok** [comment]
same here.
