### ISSUE TITLE
ArrowRight not scrolling to the right month when date day is 31

### ISSUE THREAD

**Issue by anthoninCL** [wix/react-native-calendars#1496]
## Description

When the date day is 31 (for example 2021-05-31), if you click on the arrow right in order to swipe to next month, it's going to skip every month having less than 31 days.

## Expected Behavior

Being the 2021-05-31 and clicking on the arrow right, I want to see the next month, being June.

## Observed Behavior

Being the 2021-05-31 and clicking on the arrow right, it is showing me July.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* react-native-calendars@1.265.0 
* `npm ls react-native`:
* react-native@0.61.2

Also specify:

1. Phone/emulator/simulator & version: I made this test on a Samsung Galaxy A70 with the new Android 11.

## Reproducible Demo

I can't show a demo because this is for profesional purpose... I found a quick fix for now, by changing some lines in the node_modules/react-native-calendars/src/calendar-list/item.js by just cloning the month, adding one to it and scrolling to it.

**Comment by pqminh** [comment]
XDate('2021-05-31', true).addMonths(1) was wrong.
