### ISSUE TITLE
Custom markings: Icons/Image

### ISSUE THREAD

**Issue by NitinSidhu** [wix/react-native-calendars#1507]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I want to have the markings as Image/icons. instead of dots only.

## Expected Behavior

For my case i want to have icons as markings instead or the dots as marking. so is it possible to achieve this

**Comment by goxr3plus** [comment]
Did you solve? I have the same issue :)

**Comment by godswillokokon** [comment]
was this fixed? [NitinSidhu](https://github.com/NitinSidhu)
