### ISSUE TITLE
ExpandableCalendar issue with orientation

### ISSUE THREAD

**Issue by KrisLau** [wix/react-native-calendars#1516]
## Description
The Week Calendar in the Expandable Calendar is having trouble when the orientation is changed. I tried to fix it with stylings but it didn't seem to affect it. The problem seems to be similar to this one: #606 

## Expected Behavior
I changed the orientation to landscape

## Observed Behavior
![image](https://user-images.githubusercontent.com/46275463/119564109-043b9d00-bd6e-11eb-814b-f41e9a4f2968.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1260.0
* `npm ls react-native`:
```
* +-- @react-native-clipboard/clipboard@1.7.0
| `-- react-native@0.64.1 deduped
+-- @react-native-community/geolocation@2.0.2
| `-- react-native@0.64.1 deduped
+-- @react-native-community/masked-view@0.1.11
| `-- react-native@0.64.1 deduped
+-- @react-native-picker/picker@1.16.0
| `-- react-native@0.64.1 deduped
+-- @react-navigation/native@5.9.4
| `-- react-native@0.64.1 deduped
+-- @react-navigation/stack@5.14.5
| +-- react-native-iphone-x-helper@1.3.1
| | `-- react-native@0.64.1 deduped
| `-- react-native@0.64.1 deduped
+-- @storybook/addon-ondevice-actions@5.3.23
| `-- react-native@0.64.1 deduped
+-- @storybook/addon-ondevice-knobs@5.3.25
| +-- @emotion/native@10.0.27
| | `-- react-native@0.64.1 deduped
| +-- react-native-modal-datetime-picker@7.6.1
| | `-- react-native-modal@11.10.0
| |   `-- react-native@0.64.1 deduped
| `-- react-native@0.64.1 deduped
+-- @storybook/react-native@5.3.25
| `-- react-native@0.64.1 deduped
+-- react-native-dev-menu@4.0.2
| `-- react-native@0.64.1 deduped
+-- react-native-draggable-flatlist@2.6.2
| `-- react-native@0.64.1 deduped
+-- react-native-elements@3.4.1
| +-- react-native-ratings@7.6.1
| | `-- react-native@0.64.1 deduped
| `-- react-native-size-matters@0.3.1
|   `-- react-native@0.64.1 deduped
+-- react-native-google-places-autocomplete@2.2.0
| `-- react-native@0.64.1 deduped
+-- react-native-keyboard-aware-scroll-view@0.9.4
| `-- react-native@0.64.1 deduped
+-- react-native-linear-gradient@2.5.6
| `-- react-native@0.64.1 deduped
+-- react-native-maps@0.28.0
| `-- react-native@0.64.1 deduped
+-- react-native-pager-view@5.1.8
| `-- react-native@0.64.1 deduped
+-- react-native-reanimated@2.1.0
| `-- react-native@0.64.1 deduped
+-- react-native-safe-area-context@3.2.0
| `-- react-native@0.64.1 deduped
+-- react-native-screens@3.2.0
| `-- react-native@0.64.1 deduped
+-- react-native-swipeable-item@1.5.7
| `-- react-native@0.64.1 deduped invalid
+-- react-native-tab-view@2.16.0
| `-- react-native@0.64.1 deduped
+-- react-native-track-player@1.2.7
| `-- react-native@0.64.1 deduped
+-- react-native-webview@11.4.5
| `-- react-native@0.64.1 deduped
`-- react-native@0.64.1
  `-- @react-native-community/cli@5.0.1-alpha.2
    `-- react-native@0.64.1 deduped
```

Also specify:

1. Phone/emulator/simulator & version: Pixel 3a API 30 (Android 11)

## Reproducible Demo
https://snack.expo.io/@kris_lau/schedule

**Comment by KrisLau** [comment]
Added a reproducible demo. Any help would be greatly appreciated!

**Comment by scblason** [comment]
I would add that is not just orientation issues. I have a tablet app with views like list and detail format (list at the left, detail of a selected element at right). I put an expandable calendar as a header of the list and when I expand it, it shows the calendar's days format as it would be the entire width of the screen. There is a calculation there that assumes that is always shown in the entire width of the device I think, that breaks the component

**Comment by KrisLau** [comment]
Seems to be resolved in `1.1264.0`. Thank you!
![image](https://user-images.githubusercontent.com/46275463/125685864-b609efa8-468e-4523-bed8-5c73c530f952.png)

**Comment by on29-dev** [comment]
ENGLISH

@KrisLau, Didn't you run the emulator horizontally from the beginning? Running it in portrait and then turning it back to landscape still didn't work. See the demo images belows.

![Screenshot_1628149128](https://user-images.githubusercontent.com/11909001/128314008-7c854bbb-1a86-46f4-9871-abd16f8f72ff.png)  
Portrait

![Screenshot_1628149092](https://user-images.githubusercontent.com/11909001/128313969-a6dadea6-6fa4-4903-af34-3214e5552f6d.png)  
Landscape (it was portrait just before.)

It seems not to be resolved in`1.1264.0` like your first images. 

===
KOREAN

KrisLau님, 처음부터 가로로 에뮬레이터를 실행한 거 아닌가요? 세로로 실행 후 가로로 돌려보면 여전히 해결되지 않았습니다. 

![Screenshot_1628149128](https://user-images.githubusercontent.com/11909001/128314008-7c854bbb-1a86-46f4-9871-abd16f8f72ff.png)  
세로모드

![Screenshot_1628149092](https://user-images.githubusercontent.com/11909001/128313969-a6dadea6-6fa4-4903-af34-3214e5552f6d.png)  
가로모드

`1.1264.0` 버전에서도 여전히 첫 이미지대로 회전시 달력에서 요일과 일자가 제대로 맞지 않습니다.

**Comment by KrisLau** [comment]
@on29-dev Hmmm this is so weird... I ran mine in portrait then rotated it to get that screenshot but I tried it again today and it's once again not working
![image](https://user-images.githubusercontent.com/46275463/128355421-41cc4f12-4c20-4c07-8e55-28717233f7d6.png)

**Comment by vhvm** [comment]
` const {width: screenWidth} = useWindowDimensions();

<CalendarProvider
        key={screenWidth}
        ...
>
    <WeekCalendar
          calendarWidth={screenWidth}
          ....
     />
</CalendarProvider>`

That worked for me I hope it helps 😃

**Comment by TusharKrSoniTKS** [comment]
Adding theme and manipulating marginVertical, marginLeft and marginRight worked for me
<ExpandableCalendar
                theme={{
                  'stylesheet.calendar.main': {
                    week: {
                      marginVertical: 13, // Adjust vertical spacing between rows
                      flexDirection: 'row',
                      justifyContent: 'space-between', // Spread columns evenly
                      paddingHorizontal: 20, // Add padding to the left and right of the row
                      marginRight: 23,
                      marginLeft: -18,
                    },
                  },
                  dayContainer: {
                    marginHorizontal: 0, // Adjust gap between individual columns
                  },
                  dayTextStyle: {
                    fontSize: 16, // Text size
                  },
               }}
  
              />

**Comment by on29-dev** [comment]
some component with props `~~width` like WeekCalendar is working well, but others still not working like Timeline.

WeekCalendar처럼 width를 직접 지정할 수 있는 몇몇 컴포넌트는 잘 되는데, Timeline같은 것들은 여전히 안되네요 ㅠ
