### ISSUE TITLE
renderArrow and clickable area

### ISSUE THREAD

**Issue by temuccio** [wix/react-native-calendars#1517]
## Description

I have add renderArrow but click area don't match with arrow

## Expected Behavior

I have add this code at ```<Calendar />```:
```
renderArrow={(direction) => {
  if (direction == "left")
    return (
      <IconButton icon="arrow-left-bold-circle-outline" color='#291D89' size={30} />
    );
  if (direction == "right")
    return (
      <IconButton icon="arrow-right-bold-circle-outline" color='#291D89' size={30} />
    );
}}
```

## Observed Behavior

![immagine](https://user-images.githubusercontent.com/571582/119665788-0583cd00-be35-11eb-8b29-ca6145a2409d.png)
Red is clickable area...
If I click on arrow, the month doesn't change

## Environment

* `react-native-calendars`: 1.1260.0
* `react-native`: 0.64.1

I use expo web to try it

**Comment by ahmad6242** [comment]
This issue is still there ! anyone got something on it!

**Comment by temuccio** [comment]
> 
> 
> This issue is still there ! anyone got something on it!
> 
> EDITED:
> at first i was using the touchableopactity on top of Icon.
> But then i realized it does not needed it. then i removed it. now its working fine.

Ok, I upgrade at @latest version and I feedback you.

**Comment by temuccio** [comment]
> This issue is still there ! anyone got something on it!
> 
> EDITED: at first i was using the touchableopactity on top of Icon. But then i realized it does not needed it. then i removed it. now its working fine.

Hi @ahmad6242 , I have try 1.1277.0 and I still have this problem.

**Comment by temuccio** [comment]
Hello, I have upgrate to 1.1293.0 but the problem persists

**Comment by abdulrehman1996** [comment]
Remove the Pressable or touchableOpacity and wrap with the view then it works fine
