### ISSUE TITLE
Webpack incompatibility when running a calendar with react native web. Seemingly simple solution.

### ISSUE THREAD

**Issue by jaquinocode** [wix/react-native-calendars#1518]
## Description

I'm trying to run my simple one-page project which uses CalendarList in Expo's react native web, but webpack gives an error & my project can't run.

## Source of Issue & Proposed Solution

I've figured out that the source of the issue seems to be that you can't mix `import` & `module.exports` in the same file or otherwise webpack will not work. [Stated here](https://github.com/webpack/webpack/issues/4039#issuecomment-273804003) & [very helpful info here](https://github.com/webpack/webpack/issues/4039#issuecomment-273979302). You guys mix them in the `.../src/dateutils` & `.../src/day-state-manager` files for example.

Mixing them seems like really bad practice anyway so might as well fix the mixing of CommonJS & ES Modules so that way webpack will play nice with your files!

For example, you can change `module.exports =` in your `dateutils` file to `export default` & that would fix the problem for that one file. Then you do the same for all the other files that have this.

## Expected Behavior

Run `expo r -c` to run my project which uses CalendarList. Expected the project to start as normal.

## Observed Behavior

Project didn't run & showed an error page.

Error:
```
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
Module.<anonymous>
node_modules/react-native-calendars/src/dateutils.js:145
  142 |   }
  143 | }
  144 | 
> 145 | module.exports = {
  146 |   weekDayNames,
  147 |   sameMonth,
  148 |   sameWeek,
```

Here's a screenshot of the error:
![Screen Shot 2021-05-26 at 9 47 19 PM](https://user-images.githubusercontent.com/28276675/119767673-17cd2d80-be6c-11eb-80b6-dc819fce8628.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
calendar-sample@ /Users/ja/code/react-native/scratch/calendar-sample
└── react-native-calendars@1.1262.0
* `npm ls react-native`:
calendar-sample@ /Users/ja/code/react-native/scratch/calendar-sample
├─┬ react-native-safe-area-context@3.2.0
│ └── react-native@0.63.2 deduped
└─┬ react-native@0.63.2
  └─┬ @react-native-community/cli@4.14.0
    └── react-native@0.63.2 deduped

1. Phone/emulator/simulator & version: This was run using react native web 0.13.18.

## Reproducible Demo

Make sure you're using react-native-calendars version 1.1262.0. Install that exact version. An older version of 1.1260.0 & some other older versions didn't seem to have this issue.

Then try to use this component for the web through react native web or through Expo (which uses react native web). They'll use webpack & should give an error.

**Comment by pratheekhegde** [comment]
Facing the same issue. 😞

**Comment by jaquinocode** [comment]
So this error came from an entirely different project actually. It happened when using webpack version 4.46.0 and trying to compile. You can see that the error is the same as in my original post, just worded a little differently.

It's basically saying that webpack can't understand `module.exports` in the dateutils file. And so the export default is not found.
```
WARNING in ./node_modules/react-native-calendars/src/calendar/day/index.js 139:20-29
"export 'default' (imported as 'dateutils') was not found in '../../dateutils'
  @ ./node_modules/react-native-calendars/src/calendar/index.js
  @ ./node_modules/react-native-calendars/src/index.js
  @ ./src/components/StreakCalendar/index.js
  @ ./index.js
  @ ./dist/input/runtime.js
```
As an experiment, I changed `module.exports = ` to `export default` in the `dateutils` file mentioned in the error and that error no longer showed up the next time I compiled! So this does seem like the right solution.

I'm too busy to do a pull request but hopefully there's someone out there willing to change these exports statements.

**Comment by jaquinocode** [comment]
Okay I've found the commit that caused this error (at least I assume it's the only one). Shown here: https://github.com/wix/react-native-calendars/commit/0935f264fda37c8f9c981cec6dbe74ba9a584504#diff-1d40ebcd327b41bdde667344b86f5497207fc67c406f24a32a519b9fead6509cR2

The problem came when the import statements were added to files that had a `module.exports` inside them. This then causes webpack to freak out.

**Comment by jaquinocode** [comment]
Version 1.1260.0 doesn't seem to have this issue.

**Comment by jaquinocode** [comment]
So therefore the fix for any users here is to just install version 1.1260.0 exactly.

You can do this by editing your package.json so that the version string for react-native-calendars is `"1.1260.0"`. And then later when they fix it you can add the  ^ or other semver symbol back in.

**Comment by jaquinocode** [comment]
> Facing the same issue. 😞

Let me know if my solution (last comment) fixed your issue!

**Comment by foloinfo** [comment]
I had a same issue and it seems like reverting to `1.1260.0` works.

However the recent version did not apply `selectedDayTextColor` correctly on the web, it was always black.
So I ended up reverting way back to  `1.403.0`.

**Comment by jayb967** [comment]
Is there a fix for this? I temporarily patched the files in the meantime but this should definitely be fixed!

**Comment by hungvu193** [comment]
I have the same issse :(

**Comment by klazbaba** [comment]
This PR has a fix for this issue. https://github.com/wix/react-native-calendars/pull/1548

**Comment by Moe-kanan** [comment]
I openned a very light PR to solve this issue https://github.com/wix/react-native-calendars/pull/1553

I tested it locally on web and mobile in a react-native/expo project

**Comment by smppandi1998** [comment]
> Facing the same issue. 😞

any one fixig this bug plz help me

**Comment by klazbaba** [comment]
> > Facing the same issue. 😞
> 
> any one fixig this bug plz help me

You can use this #1548 for now, pending when it gets merged in.
