### ISSUE TITLE
Custom Days Name Header

### ISSUE THREAD

**Issue by lucaszdev** [wix/react-native-calendars#1534]
Have how to custom Days Name Header???
A Background Color and Name Colors??

Like in this picture for example:

![image](https://user-images.githubusercontent.com/53530532/121917154-33a94e00-cd0b-11eb-89c8-24af941917ed.png)

**Comment by yansena** [comment]
Hello friend, in this case you looked this part of documentation when explaining customization in head?
https://github.com/wix/react-native-calendars#individual-day-header-styling

**Comment by lucaszdev** [comment]
@yansena 

Oh fuck, I not see, but there is a problem, where have a list with valid props to use? I only see two in the documentation - dayAtIndex0 and dayAtIndex6.

the intelisense not show me the props valids of stylesheet.calendar.header, you can help me with that?

**Comment by rewdt** [comment]
@lucaszdev  Any luck with this?

**Comment by hanifmhd** [comment]
in latest version not working at all

**Comment by Mark-Putter** [comment]
> @yansena
> 
> Oh fuck, I not see, but there is a problem, where have a list with valid props to use? I only see two in the documentation - dayAtIndex0 and dayAtIndex6.
> 
> the intelisense not show me the props valids of stylesheet.calendar.header, you can help me with that?

You can see all the valid props by navigating into day and header folders from this link:
https://github.com/wix/react-native-calendars/tree/master/src/calendar

for example click 'Header' then 'styles.ts'
