### ISSUE TITLE
Month change is auto selecting the first day of every month in ExpandableCalendar

### ISSUE THREAD

**Issue by joseortiz9** [wix/react-native-calendars#1537]
## Description
As the title says, using the ExpandableCalendar every time that the gesture of changing the month or with the arrows the selectedDate is being set automatically to the first day of every month, same thing happens in the weekCalendar view when changing of week, it selects the first day of the week.

## Expected Behavior
Not change automatically the selectedDate and let the last selected of the previous month.

## Environment

* `react-native-calendars`: react-native-calendars@1.1263.0
* `react-native`: react-native@0.63.2 

Also specify:

1. Phone/emulator/simulator & version:
Phone: Galaxy A9 (2018)
Android: 10

## Code
```
<CalendarProvider
    date={selectedDate}
    onDateChanged={(date) => setSelectedDate(date)}
    onMonthChange={({month, year}) => setMonth({month, year})}
>
    <ExpandableCalendar
      firstDay={1}
      //current={selectedDate}
      markedDates={{}}
      displayLoadingIndicator
      showScrollIndicator
      horizontal
      pagingEnabled
      hideExtraDays={false}
      hideArrows={false}

      initialPosition={ExpandableCalendar.positions.OPEN}
      disableWeekScroll={true}

      pastScrollRange={20}
      futureScrollRange={20}
      theme={{}}
  />
</CalendarProvider>
```

## Reproducible Demo
I created an snack to prove it, it works okay on web, but on ios and android it happens the issue. 
https://snack.expo.io/@joseortiz09/bug-expandablecalendar-on-month-change

https://user-images.githubusercontent.com/26872450/122513025-684d2c00-cfcf-11eb-9ecd-b0295eb0897f.mp4

Please help me out!, your library is amazing but need more work :(

**Comment by Inbal-Tish** [comment]
@joseortiz9 Hi. This is not a bug. It's is the intended behaviour. If you wish to toggle the feature you're welcome to submit a feature request or a PR.

**Comment by joseortiz9** [comment]
how come this is an intended behavior? the selectedDay is supposed to change on every month? so what is the purpose of selecting it (?)

**Comment by wikramdas** [comment]
Having the same issue. Whenever I changed the month first date of every month has been auto selected.
Any solution?

**Comment by joseortiz9** [comment]
@wikramdas they keep saying that is 'intended behaviour'. But it only happens on phone version, on web or other components it doesnt happen, is weird, I dont understand their logic, soon I will make a PR because it seems they will not correct it :( pretty sad...

**Comment by vingrad** [comment]
@joseortiz9 sorry, but did you submit the PR for this case?

**Comment by joseortiz9** [comment]
@vingrad nah, the company I was working for closed that project, so it was meaningless((

**Comment by inkCrazy** [comment]
同样的问题，ExpandableCalendar切换周的时候，为什么要自动选中第一天，而且没有对应的回调事件，也没有取消选中？
![image](https://github.com/user-attachments/assets/38cabe78-e889-4f3e-ac2a-cf0e4366d2f6)
