### ISSUE TITLE
calendarBackground style not working in theme in android

### ISSUE THREAD

**Issue by 16ntu1120** [wix/react-native-calendars#1543]
I wanted to change the default color of background of calendar but this prop is not working anyone faced this problem how can I change the color of calendar? Need help.

**Comment by joseortiz9** [comment]
hey, right here:
```
<Calendar
...
theme={{
    backgroundColor: '#F6F6F4',
    calendarBackground: '#F6F6F4',
}} />
```

**Comment by joseortiz9** [comment]
please check the available styles variables for the component :)

**Comment by RemyMachado** [comment]
> hey, right here:
> 
> ```
> <Calendar
> ...
> theme={{
>     backgroundColor: '#F6F6F4',
>     calendarBackground: '#F6F6F4',
> }} />
> ```

I didn't succeed to change the color with these two props...

![image](https://user-images.githubusercontent.com/30229752/134804611-071023f4-3fb6-419c-822a-a8662ff3f393.png)

How do I get rid of this green header?
