### ISSUE TITLE
Calendar dots sometimes not showing in agenda

### ISSUE THREAD

**Issue by yamila-fraiman** [wix/react-native-calendars#1563]
## Description

After loading events I can't see calendar dots until I tap on a date.

## Expected Behavior

Load dots the first time after fetching events

## Environment

* `npm ls react-native-calendars`: 1.1264.0
* `npm ls react-native`: 0.64

**Comment by schteff** [comment]
Same here. The dots in the Agenda are not displayed initially until either scrolling so another date is "selected" or tapping a date in the calendar. 

It seems the dots are not re-drawn until any of the above happens, and since the initial markedDates is {} they don't show up.
