### ISSUE TITLE
Cant scroll CalendarList inside BottomSheet in Android

### ISSUE THREAD

**Issue by haluhaluhalu99** [wix/react-native-calendars#1565]
![Screenshot_1625545325](https://user-images.githubusercontent.com/43717603/124541842-7531a280-de4c-11eb-8924-f4998e28d8c4.png)

## Description

Hi, I'm using a CalendarList inside BottomSheet , but i can't scroll calendarsList in android because it using flatList from 'react-native'.

## Expected Behavior

I was trying to import  FlatList form  'react-native-gesture-handler' in CalendarList . It's was worked

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by abhidatta0** [comment]
Same issue
