### ISSUE TITLE
How to increase the dot size of  markingType="multi-dot"

### ISSUE THREAD

**Issue by Sneha1231** [wix/react-native-calendars#1568]
## Description

I want o increase the dot size for the markingType="multi-dot". How to do it. Currently I Am passing dots as  "dots": [{"color": "red", "key": "selected"}]}. Please suggest me a solution.

**Comment by alexfov** [comment]
```js
<Calendar theme={{
     dotStyle: { width: 8, height: 8 },
}}/>
```
