### ISSUE TITLE
React native calendars are not rendering as expected  with web build especially the custom day Component passed

### ISSUE THREAD

**Issue by manpreet-02** [wix/react-native-calendars#1570]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I am using react-native-calendars for mobile & web app.When  i start project on web its working as expected but when we create  build  its  not showing any style
web::
<img width="1092" alt="Screenshot 2021-07-09 at 11 12 39 AM" src="https://user-images.githubusercontent.com/67887222/125029194-e8365580-e0a6-11eb-9e00-b6df6a95fdd6.png">

web build::

react-app-rewired build

<img width="1031" alt="Screenshot 2021-07-09 at 11 16 11 AM" src="https://user-images.githubusercontent.com/67887222/125029323-13b94000-e0a7-11eb-8e1c-7b2449d223a7.png">

Have  already updated the config-overide file:
```
  babelInclude([
    path.resolve(__dirname, 'node_modules/react-native-calendars'),
    path.resolve(__dirname, 'node_modules/react-native-swipe-gestures'),
    path.resolve(__dirname, 'src'),
  ])
```,

&& 
```
  ...addBabelPlugins(
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-transform-modules-commonjs',
  ),
```

**Comment by sulaigor** [comment]
Hi,

I have similar problem with styles of calendar and with firstDay property in build. I need to have Monday as first day of the week.

I am using next as builder.

Any update or suggestion?

Thanks.

**Comment by sulaigor** [comment]
Version: 1.1264.0
Builder: NextJS

Hi,

I investigated this issue in package source code and I find issue with **extractComponentProps** (src/component-updater.js) function which is used in **Calendar component** (src/calendar/index.js) in **renderHeader** and **renderDay** methods.

The **extractComponentProps** function **return empty object** while component's (first argument) **propTypes are undefined**. This empty object is distributed to Day or Header component's properties so it not set up anything like theme, firstDay etc.

I fix like this for my build:
`
function extractComponentProps(component, props, ignoreProps) {
  const componentPropTypes = component.propTypes;
  if (componentPropTypes) {
    const keys = Object.keys(componentPropTypes);
    const componentProps = _.chain(props)
      .pickBy((_value, key) => _.includes(keys, key))
      .omit(ignoreProps)
      .value();
    return componentProps;
  }
  return {...props};
}
`

I'd rather return copy of props than empty object in my case.

I hope this will help to fix the issue for web building.

Thanks.

**Comment by manpreet-02** [comment]
yes it solved the first day problem... Thanks @sulaigor  .

**Comment by sulaigor** [comment]
In my case, this solution works also for custom styles (for theme property) of Calendar component.

I think it should resolve the problem with dayComponent property because this property is also passing through the extractComponentProps function to Day component.

But I am not using custom dayComponent property in my project so problem may be in Day component (src/calendar/day/index.js)... 

Try debug Day component - there is getDayComponent method - try if dayComponent property here is not falsy.

Thanks.

**Comment by manpreet-02** [comment]
Yes @sulaigor , this has fixed our dayComponent issue too...
Thanks for solution!

**Comment by jamespb97** [comment]
This also worked for me, also using NextJS to build web version of our project.
@sulaigor I'd suggest you make a PR with this code as a fix for this issue 👍
