### ISSUE TITLE
OnDayPress doesn't respond

### ISSUE THREAD

**Issue by chaedirdwiantara** [wix/react-native-calendars#1573]
## Description

OnDayPress didnt respond to some devices

## Expected Behavior

i'm expectiing this function works fine like always

## Observed Behavior

Last week i tried run my project on new device, it works fine for few days n then it didn't give any respond when i clicked the date (OnDayPress), i'd try to console.log but still no effect (it still give me animation like pressed but no effect at all). Anyway it still works fine in another device n emulator on that day, but this morning i found that the other device starting to not respond too.
Firstly i thought it was expo version but when i checked these two devices has different version of expo (2.21.5 and 2.19.6), now the emulator still works fine (expo ver 2.19.6) but the problem is i'm developing expo push notification and it wont work on emulator.

here's my code:
<Calendar
        onDayPress={(day) => {
          // console.log(day, "ini harinya");
          setSelectedDay(day.dateString); //to mark the selected day
          setShowModal(!showModal);
          setDayFilter(
            day.day < 10 && day.month < 10
              ? `0${day.day}/0${day.month}/${day.year}`
              : day.day < 10 && day.month >= 10
              ? `0${day.day}/${day.month}/${day.year}`
              : day.day >= 10 && day.month < 10
              ? `${day.day}/0${day.month}/${day.year}`
              : day.day >= 10 && day.month >= 10
              ? `${day.day}/${day.month}/${day.year}`
              : null
          );
          setHariIni(day.day);
        }}
        minDate={format(new Date(), "yyyy-MM-dd")}
        maxDate={addMonths(new Date(), 1)}
        disableAllTouchEventsForDisabledDays={true}
        markingType={"custom"}
        markedDates={mergeMark}
    />

## Environment

Please run these commands in the project folder and fill in their results:

* `yarn list react-native-calendars`: react-native-calendars@1.1264.0
* `yarn list react-native`: react-native@0.63.2

Also specify:

1. Device & OS version: Poco F3, Android 11
2. Device & OS version: ASUS_X008DA (Zenfone series), Android 7.0

## Screenshots

the issue :
https://user-images.githubusercontent.com/64129000/125367753-f20bd180-e3a2-11eb-8762-a69ba8d91b9b.mp4

expected behavior: 
https://user-images.githubusercontent.com/64129000/125368157-d94feb80-e3a3-11eb-8f21-020b9842b613.mp4

**Comment by sharanrprasad** [comment]
Experiencing same behaviour while running on Samsung Galaxy s8 as well.

**Comment by jordansoltman** [comment]
On Android you should also implement `onLongDayPress`. For some reason that gets fired more often than `onDayPress` even if it feels like a short press.

https://github.com/wix/react-native-calendars/issues/571

**Comment by Atomico001** [comment]
I have the same problem in debug mode, while work nice if debug is disabled.

**Comment by kylanhurt** [comment]
Having the same issue. Even if I turn off debug mode it only registers the first couple of presses / taps.

This library is very poorly done. Not sure how Wix is able to use it for their purposes... not sure how anyone can use it TBH. I think I am gonna migrate to a different library.

**Comment by aydil45** [comment]
Not working, does anyone have the solution?

**Comment by RaghvendraIndigo** [comment]
I am still facing this issue Is there any solution? onDayPress not working

**Comment by sadiacha** [comment]
I am facing the same issue on iOS.
