### ISSUE TITLE
Agenda cannot scroll up

### ISSUE THREAD

**Issue by taitran2512** [wix/react-native-calendars#1586]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Agenda cannot scroll up to past date
Select date is 28 and I want scroll to date 27 but it cannot scroll
"react-native-calendars": "^1.1264.0",

![image](https://user-images.githubusercontent.com/65691647/127305408-cd76dc69-81ff-4bbe-9064-e5aadfeab862.png)

**Comment by johnpanos** [comment]
I also have this issue

**Comment by monizb** [comment]
Same here, 4 years since this issue was first reported and no fix yet...

**Comment by monizb** [comment]
Possible workaround to this: https://github.com/wix/react-native-calendars/issues/979

**Comment by taitran2512** [comment]
Hi everyone, I had just found an example in this library, that is named ExpandableCalendar + AngendaList (using SectionList RN), maybe it will support you something.
You just have to do this and it can scroll to a past date
<CalendarProvider
        date={ your day you want to begin format yyyy-mm-dd}

https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.tsx

**Comment by Deepindera** [comment]
> Same here, 4 years since this issue was first reported and no fix yet...

DO you have empty date for the previous date.   I saw somewhere that you need have all dates (even the ones without data) like 2022-01-01: []   .,2022-01-02: {my data}.   So now it should scroll back to date 01.
