### ISSUE TITLE
Agenda: How to get renderDay to be above renderItem(s) instead of alongside (left)

### ISSUE THREAD

**Issue by pauljakobwhite** [wix/react-native-calendars#1588]
## Description
This may turn into a feature request, but could also be an oversight on my part... I can't seem to figure out how to render the day **above** any of the items belonging to that day. No matter what I do to override the styles the day is rendered to the left of the items. Is this not possible, or am I overlooking a simple solution?

E.g.: 
July 1, 2021
 1. Event
 2. Event

July 2, 2021
 1. Event
 
... etc.

**Comment by pauljakobwhite** [comment]
Guess I solved this by getting rid of the renderDay entirely and leveraging the firstItemInDay on the renderItem to render a custom date header on top of the items. Seems hacky and unnecessary though.

**Comment by rmethaniya** [comment]
![Screenshot 2021-08-18 at 4 34 22 PM](https://user-images.githubusercontent.com/36511541/129887905-60cc1723-2e1a-441e-b9de-f096de4386b2.png)

It will be great if you provide one prop for change container style in the reservation.js file
