### ISSUE TITLE
Agenda Component: It doesn't re-render after updating data

### ISSUE THREAD

**Issue by bilalahmad-greelogix** [wix/react-native-calendars#1589]
## Description

Agenda does not re-render calendar events after updating one of those events. In our application, we want to remove an event whenever it is clicked. After clicking on an event, the complete agenda disappears (except header).

## Expected Behavior

I clicked on an event and called an API to remove that event from the dates lis. It should remove that event and re-render other events.

## Observed Behavior

The complete Agenda (except header disappeared.

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.1264.0
* `npm ls react-native`: react-native@0.63.2

Also specify:

## Screenshots
Before booking an event:
![ss1](https://user-images.githubusercontent.com/84312528/127883840-3dd0dabf-ed91-481a-b5d7-fa14b5825fa2.jpg)

After booking an event:
![ss2](https://user-images.githubusercontent.com/84312528/127883888-3ce9c257-9b96-49ef-a275-75df109d124a.jpg)

**Comment by AlexandreMouyen** [comment]
I have the same trouble, the Calendar does not re-render on data change.

**Comment by abiespinal04** [comment]
https://github.com/wix/react-native-calendars/issues/463#issuecomment-444246279

**Comment by abiespinal04** [comment]
This worked for me, techinically I had to setState twice :

``` handleStatus = async (item, status) => {
    const {updateAppointmentStatus} = this.props;
    const {id} = item || {};
    const res = await updateAppointmentStatus(id, status);
    const {upcoming} = res || {};

    if (!res) return;

    this.setState({items: {}});
    this.setState({items: upcoming});
  };
  ```

**Comment by abiespinal04** [comment]
Also, inside of `node_modules/react-native-calendars/src/agenda/reservation-list/reservation.js`
there is a `shouldComponentUpdate` method. Removing it or commenting it out, lets you update the agenda on updates to the view.

**Comment by AlexandreMouyen** [comment]
> Also, inside of `node_modules/react-native-calendars/src/agenda/reservation-list/reservation.js` there is a `shouldComponentUpdate` method. Removing it or commenting it out, lets you update the agenda on updates to the view.
> 
> I recommend this one from the workaround above. This solution lets you persist the layout position on the list without restarting the list and taking you all the way to the top.
> 
> You can apply the change and then patch the package until is fixed I guess. Here's a link on how to patch a package: https://www.youtube.com/watch?v=2AVs-Yh1bS8&t=108s
> 
> Hope it helps future readers :)

Thanks for the workaround. :)

**Comment by lohenyumnam** [comment]
Is anyone working on this??

**Comment by wilav-dev** [comment]
Same issue, use @abiespinal04 workaround. Any other solution?

**Comment by themissingCRAM** [comment]
Same here, this is problematic.

**Comment by francesco-clementi-92** [comment]
> Also, inside of `node_modules/react-native-calendars/src/agenda/reservation-list/reservation.js` there is a `shouldComponentUpdate` method. Removing it or commenting it out, lets you update the agenda on updates to the view.
> 
> I recommend this one from the workaround above. This solution lets you persist the layout position on the list without restarting the list and taking you all the way to the top.
> 
> You can apply the change and then patch the package until is fixed I guess. Here's a link on how to patch a package: https://www.youtube.com/watch?v=2AVs-Yh1bS8&t=108s
> 
> Hope it helps future readers :)

This workaround causes too many rerenders

**Comment by Saad-Bashar** [comment]
Trying my luck here, any proper fix on this yet? Thanks!

**Comment by francesco-clementi-92** [comment]
@Saad-Bashar try to ping this issue #1855

**Comment by nine-9-nine** [comment]
How is this not fixed yet? Completely breaking the usage

The agenda day view does not update at all (unless the change of data is occuring on the first item of the day)

**Comment by francesco-clementi-92** [comment]
@nine-9-nine ping the issue #1855 as this one is closed.

**Comment by argoescobar** [comment]
I found a workaround but have re-render entire agenda screen. 

`
import { useFocusEffect } from "@react-navigation/native";
import React, { useEffect, useState, useCallback } from "react";

const HandleCalendar = () => {
  const [key, setKey] = useState(0);
  const { todos } = useFirebase();

  useFocusEffect(
    React.useCallback(() => {
      setKey((prevKey) => prevKey + 1);

      return () => {
        // Do something when the screen is unfocused
      };
    }, [todos])
  );

  return <AgendaScreen key={key} />;
};
`

works for me

**Comment by deema304** [comment]
Hello!

Faced the same problem. 
I've fixed that issue almost in the same way as @AlexandreMouyen proposed,
but instead of removing all comparisons I modified it a little, and apply a patch.

Here is what I did.

In _node_modules/react-native-calendars/src/agenda/reservation-list/reservation.js_
First **IF** statement, always returns false if there is no dates.

`if (!d1 && !d2) {
       changed = false;
  }
`

so I added comparison for my particular part of data.
I just check if elements _id are same also.

`r1._id === r2._id`

Full example below. Yeah, it hardcode a little :-) but May be help for someone.

    if (!d1 && !d2 && r1._id === r2._id) {
        changed = false;
    } else if (d1 && d2) {
        if (d1.getTime() !== d2.getTime()) {
            changed = true;
        } else if (!r1 && !r2) {
            changed = false;
        } else if (r1 && r2) {
            if ((!d1 && !d2) || (d1 && d2)) {
                if (isFunction(this.props.rowHasChanged)) {
                    changed = this.props.rowHasChanged(r1, r2);
                }
            }
        }
    }
    return changed;

**Comment by hughyyyy** [comment]
> Hello!
> 
> Faced the same problem. I've fixed that issue almost in the same way as @AlexandreMouyen proposed, but instead of removing all comparisons I modified it a little, and apply a patch.
> 
> Here is what I did.
> 
> In _node_modules/react-native-calendars/src/agenda/reservation-list/reservation.js_ First **IF** statement, always returns false if there is no dates.
> 
> `if (!d1 && !d2) { changed = false; } `
> 
> so I added comparison for my particular part of data. I just check if elements _id are same also.
> 
> `r1._id === r2._id`
> 
> Full example below. Yeah, it hardcode a little :-) but May be help for someone.
> 
> ```
> if (!d1 && !d2 && r1._id === r2._id) {
>     changed = false;
> } else if (d1 && d2) {
>     if (d1.getTime() !== d2.getTime()) {
>         changed = true;
>     } else if (!r1 && !r2) {
>         changed = false;
>     } else if (r1 && r2) {
>         if ((!d1 && !d2) || (d1 && d2)) {
>             if (isFunction(this.props.rowHasChanged)) {
>                 changed = this.props.rowHasChanged(r1, r2);
>             }
>         }
>     }
> }
> return changed;
> ```

Applying changes to your node_modules won't affect productions. Is anyone fixing this? It has been many years and this bug makes the calendar unusable.
