### ISSUE TITLE
[bug] when click to change day in Agenda with more than a few items per day

### ISSUE THREAD

**Issue by rturk** [wix/react-native-calendars#159]
## Description

If you add more than 2 items per day and switch between days the Agenda will incorrectly handle the change and will occasionally duplicate items

## Expected Behavior

Show correct number of items per day

## Observed Behavior

Items are duplicated if change days

## Environment

Please run these commands in the project folder and fill in their results:

 "react-native-calendars": "^1.5.4",
 IOS & Android

## Our fix

We're able to fix this by setting forcing `rowHasChanged` to true

```
  rowHasChanged = (r1, r2) => {
    return true;
  };
```

**Comment by tautvilas** [comment]
Hi, thx for report. Are you treating your items object as immutable?
