### ISSUE TITLE
[Help needed] How to add an arabic calendar with friday and saturday as weekend holidays

### ISSUE THREAD

**Issue by aravicubet** [wix/react-native-calendars#1591]
## Description

I would like to implement a calendar with friday and saturday as weekend holidays instead of manually providing individual dates and highlighting it.

## Expected Behavior

<img width="282" alt="Screenshot 2021-08-05 at 12 44 52 AM" src="https://user-images.githubusercontent.com/82430019/128241427-8112f16a-2f75-4f8f-9857-e8456266abd7.png">

## Observed Behavior
Normal Calendar with Saturday and Sunday as weekend off!
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1264.0
* `npm ls react-native`: react-native@0.64.2

Also specify:

1. Device/emulator/simulator & OS version: android & ios/simulator & device

**Comment by n0mer** [comment]
@aravicubet were you able to resolve your issue?
