### ISSUE TITLE
Agenda but want to start with Calender View

### ISSUE THREAD

**Issue by fwidtmann** [wix/react-native-calendars#1599]
hi,

Im using Agenda and its great, but i want to start with the normal Calender (month) view. 
At first visit its displaying always the agenda with the current day, but i want the current month view.

**Comment by sushilbansal** [comment]
Hi @fwidtmann, how did you solve the issue?

**Comment by fwidtmann** [comment]
@sushilbansal no.
we removed the month feature, we only show now week + timeline and week + agendalist

**Comment by sushilbansal** [comment]
got it. Thanks.
