### ISSUE TITLE
CalendarList not interactive?

### ISSUE THREAD

**Issue by getnashty** [wix/react-native-calendars#16]
I'm trying to use an interactive CalendarList, but it doesn't seem to work?

```
 <CalendarList
     onDayPress={(day) => { console.log('selected day', day); }}
     pastScrollRange={0}
     futureScrollRange={12}
     scrollEnabled
     markingType={'interactive'}
     />

```

This is all of my code. When I tap a day, it logs properly but nothing in the UI changes. Any ideas?

**Comment by mogarick** [comment]
@getnashty did you solve the problem? I'm facing the same one but I don't know how to solve it. Is it something missing or is it a possible bug?

**Comment by tautvilas** [comment]
Hi, you have to pass and construct `markedDates` yourself. There is no built-in way to auto-mark days on day press. That means you have to construct this object in `onDayPress` handler and pass it to Calendar. check the code in examples.
