### ISSUE TITLE
CalendarList does not automatically render prior calendars when pastScrollRange prop is updated

### ISSUE THREAD

**Issue by danvee** [wix/react-native-calendars#1600]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When adding items to our calendar list we update the state prop bound to pastScrollRange on the CalendarList to ensure
that we render the correct number of past months to reflect our data.

## Expected Behavior

The CalendarList should  immediately render the correct number of previous months and these should be able to be scrolled to.

## Observed Behavior

The CalendarList does not immediately render the previous months. Previous months are however rendered when the view is scrolled down and back up again.

## Environment

* react-native-calendars@1.1264.0

* react-native@0.63.4

 Device/emulator/simulator & OS version: iPhone 11,  iOS 13.1

**Comment by haveamission** [comment]
Did anyone find a solution to this?
