### ISSUE TITLE
auto jumping months after doing the swipe

### ISSUE THREAD

**Issue by Karol52** [wix/react-native-calendars#1601]
auto jumping months after doing the swipe
## Description

after a few quick swipe there is a problem, sometimes also on ios

## Environment

npm ls react-native-calendars: react-native-calendars@1.1264.0
npm ls react-native: react-native@0.64.2

https://user-images.githubusercontent.com/77123365/129460034-1f835388-9568-484a-a0d3-bbef0d40a1a1.mp4

Result  - Android 10

**Comment by learnForeverr** [comment]
Hey did you find any solution for this issue?

**Comment by thespacemanatee** [comment]
Hey, I have the exact same issue as well! Why was this closed @Karol52?

**Comment by vigneshlakshminarayananbayer** [comment]
Was this ever solved?
