### ISSUE TITLE
Agenda doesn't render when placed inside a View

### ISSUE THREAD

**Issue by sankomil** [wix/react-native-calendars#1602]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When Agenda is placed inside View tags nothing is returned on the screen, nor do I get any warnings or errors.

## Expected Behavior

Expected the Agenda to load as it is with no changes

## Observed Behavior

Nothing happens, I only get a blank screen.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1264.0 
* `npm ls react-native`: react-native@0.64.2 

Also specify:

1. Device/emulator/simulator & OS version: Pixel 3a XL API 29

## Reproducible Demo

- Add Agenda to a react-native app created using ignite template. 
- Use Storybook to create a new story.
- Put it inside `View`

Code can be found in this [Expo Snack](https://snack.expo.dev/@booya/agenda-error-recreation)

## Screenshots

![image](https://user-images.githubusercontent.com/43489998/129655895-8e75f69f-3d49-4fdc-aff1-4d43809a3a90.png)

**Comment by Maaaxiii** [comment]
See: #388
