### ISSUE TITLE
[Q] custom dayComponent receives standard margin?

### ISSUE THREAD

**Issue by pimJNGNL** [wix/react-native-calendars#1603]
Rendering a custom `dayComponent` for my `<CalendarList/>`where my root `<View/>` container doesn't take any margins. Trying to find an answer to that in any `stylesheet.day.[markingType]:{...}` to overwrite. Would love to change this margin between the rows of weeks here, any hints? Seems like it receives some `...basicProps` somehow.
![Schermafbeelding 2021-08-19 om 10 01 40](https://user-images.githubusercontent.com/6142639/130031194-c0420c76-f109-4d68-9976-f63e63f7ea0f.png)

**Comment by alexfov** [comment]
Try to set `width: "100%"` to day container
![screencap-2021-08-19T213036 806Z](https://user-images.githubusercontent.com/39302602/130147169-d45538f4-42f4-422f-9a2a-72b55a53cd99.png)

**Comment by pimJNGNL** [comment]
ah, no I ment the margin between the rows here, I want to adjust that :)

**Comment by alexfov** [comment]
Ok, then:
<CalendarList
          theme={{
            'stylesheet.calendar.main': {
              week: {
                borderWidth: 1,
                flexDirection: 'row',
                justifyContent: 'space-around',
                marginTop: 0,
                marginBottom: 0,
              },
            },
          }}
        />

**Comment by pimJNGNL** [comment]
Thanks a lot!
