### ISSUE TITLE
Multiple minDate maxDate possible? noob question

### ISSUE THREAD

**Issue by Penguin2412** [wix/react-native-calendars#1604]
Hi I am making an app for a vacation apartment booking. I have to gray out dates (and make them therefore unselectable) that are already booked. What's the best way to achieve that? I would like to do that with multiple minDate & maxDate, is that possible? if yes/no are there better ways to achieve that?

kind regards

**Comment by alexfov** [comment]
From doc:
```js
<Calendar
  markedDates={{
    '2012-05-19': {disabled: true, disableTouchEvent: true}
  }}
/>
```

**Comment by Penguin2412** [comment]
> From doc:
> 
> ```js
> <Calendar
>   markedDates={{
>     '2012-05-19': {disabled: true, disableTouchEvent: true}
>   }}
> />
> ```

@alexfov but ain't it a pain in the ass, bad approach, to do it "manully" like this 150 times? 

anyway, thanks in advance!

**Comment by alexfov** [comment]
Why manually? How do you define these unselectable  days?

**Comment by Penguin2412** [comment]
> Why manually? How do you define these unselectable days?

unselected days are days where someone already booked the vacation flat.
With manually, I mean that I feel it's performance abusive (it must be some kind of waste, Performance killer) passing 9999 days like this:

`<Calendar
  markedDates={{
    '2012-05-19': {disabled: true, disableTouchEvent: true}
  }}

markedDates={{
    '2012-05-20': {disabled: true, disableTouchEvent: true}
  }}

markedDates={{
    '2012-05-21': {disabled: true, disableTouchEvent: true}
  }}

markedDates={{
    '2012-05-22': {disabled: true, disableTouchEvent: true}
  }}

markedDates={{
    '2012-05-23': {disabled: true, disableTouchEvent: true}
  }}
// and so on
//.......
/>
`

I want it to be like
markedDates={{
    ['2012-05-19', 'until', '2012-05-30']: {disabled: true, disableTouchEvent: true}
  }}

**Comment by alexfov** [comment]
@Penguin2412 not like this.
```js
<Calendar
  markedDates={{
    '2012-05-19': {disabled: true, disableTouchEvent: true},
    '2012-05-20': {disabled: true, disableTouchEvent: true},
    ...
  }}
/>
```
It is how this library works. You can't pass ranges. There is no performance difference how you pass marked days, as a list or as a list of ranges.

**Comment by Penguin2412** [comment]
> @Penguin2412 not like this.
> 
> ```js
> <Calendar
>   markedDates={{
>     '2012-05-19': {disabled: true, disableTouchEvent: true},
>     '2012-05-20': {disabled: true, disableTouchEvent: true},
>     ...
>   }}
> />
> ```
> 
> It is how this library works. You can't pass ranges. There is no performance difference how you pass marked days, as a list or as a list of ranges.

okay thanks a lot!!!!! thanks man!!
