### ISSUE TITLE
Instalation problems - Error

### ISSUE THREAD

**Issue by mvmcorrea** [wix/react-native-calendars#1607]
When I run yarn-clean / yarn command show that error

Error: Cannot find module '/Users/xxx/Documents/test_app/node_modules/react-native-calendars/scripts/postinstall.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {

Somebody can help with that ?

**Comment by kevex91** [comment]
@Inbal-Tish issue with the latest release

**Comment by kevex91** [comment]
```
> react-native-calendars@1.1265.0 postinstall /Users/x/x/x/x/x/src/node_modules/react-native-calendars
> node ./scripts/postinstall.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/x/x/x/x/x/src/node_modules/react-native-calendars/scripts/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by imsheng** [comment]
+1

**Comment by uellpalma** [comment]
Same problem

**Comment by victorlpgazolli** [comment]
+1

**Comment by caiopratali** [comment]
+1

**Comment by hungtnb** [comment]
Remove `^` in `**"react-native-calendars": "^1.1261.0"**` is working for me

**Comment by mvmcorrea** [comment]
this version is working for me: "react-native-calendars": "1.1264.0",

**Comment by kevex91** [comment]
Need the `module.exports = {` > `export {` fix that was going to be in the latest release.

Otherwise babel + webpack gives you:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by chuyvad** [comment]
+1

**Comment by GustavoContreiras-Feegow** [comment]
solution `yarn add react-native-calendars@1.1264.0`

**Comment by benayadt** [comment]
+1

**Comment by edritech93** [comment]
same for me

**Comment by dongdyang** [comment]
same here

**Comment by dongdyang** [comment]
@Inbal-Tish please help to fix and thanks!!

**Comment by Inbal-Tish** [comment]
Thank you for reporting, I'm checking the issue and I'll update.

**Comment by Inbal-Tish** [comment]
Hi all. We had an issue with detox so we disabled it temporarily. Please use the new version - **version 1.1266.0** to solve the issue. Thanks again for reporting!
