### ISSUE TITLE
Install always failed when executing postinstall script in 1.1265.0

### ISSUE THREAD

**Issue by jeffryang24** [wix/react-native-calendars#1610]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Probably, this issue is a regression since there is no `postinstall` script in 1.1264.0 (https://github.com/wix/react-native-calendars/compare/1.1264.0...1.1265.0). Also, the `scripts` directory does not exist inside the node_modules package directory (see the image below).

Step to reproduce:

- `yarn add react-native-calendars`

## Expected Behavior

It should install the package successfully.

## Observed Behavior

What actually happened when you performed the above actions?

- Error while executing the postinstall script for react-native-calendars

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
error /home/jeffryangtoni/sources/company/github/district-bcd/packages/apps/shared/node_modules/react-native-calendars: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.js
Arguments:
Directory: /home/jeffryangtoni/sources/company/github/district-bcd/packages/apps/shared/node_modules/react-native-calendars
Output:
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/jeffryangtoni/sources/company/github/district-bcd/packages/apps/shared/node_modules/react-native-calendars/scripts/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'shared'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:

```
@company/district-bcd@ /home/jeffryangtoni/sources/company/github/district-bcd
└── (empty)
```

* `npm ls react-native`:

```
@company/district-bcd@ /home/jeffryangtoni/sources/company/github/district-bcd
└── (empty)
```

Also specify:

1. Device/emulator/simulator & OS version:

Samsung S9+ & Android 10

## Reproducible Demo

Should be clear since it just only installing the npm package.

## Screenshots

![node_modules__react-native-calendars](https://user-images.githubusercontent.com/8284757/130578855-573cc6d0-4862-43e4-85b4-0a0445de66e0.png)

`scripts` directory does not exist.

**Comment by jeffryang24** [comment]
I think we need to add the `scripts` directory inside the `package.json`'s `files` field, so it will also be included when running `npm pack`.

**Comment by iamdainv** [comment]
Remove ^ in "react-native-calendars": "^1.1261.0" is working for me (reason version lastest)

**Comment by jeffryang24** [comment]
@iamdainv , I think for your case is it will stick to version `1.1261.0`. But, currently I will stick to `1.1264.0` for a while. :bow:

**Comment by TomCorvus** [comment]
https://github.com/wix/react-native-calendars/issues/1607

**Comment by jeffryang24** [comment]
I see... seems it has been reported before.. I will close this issue and will refer to the main issue. Thank you... :bow:
