### ISSUE TITLE
How to render custom dates

### ISSUE THREAD

**Issue by ebatgerel** [wix/react-native-calendars#1616]
How to render custom dates ? Below image shows what i exactly want

![image](https://user-images.githubusercontent.com/16677052/131303696-4b880842-11d7-4b26-9c4f-9a8241eb6b9b.png)

**Comment by Tony1027-yu** [comment]
I had a similar problem. Did you solve it？

**Comment by arifhendraween** [comment]
I can't use ondaypress when using custom component

**Comment by ebatgerel** [comment]
@Tony1027-yu i am still on this :(

**Comment by Tony1027-yu** [comment]
> I can't use ondaypress when using custom component

Wow ， Do you mean to say that you have implemented the custom date component, can you tell me how to define it?

**Comment by alexfov** [comment]
```js
<Calendar
  style={[styles.calendar, {height: 300}]}
  dayComponent={({date, state}) => {
    return (
      <View>
        <Text style={{textAlign: 'center', color: state === 'disabled' ? 'gray' : 'black'}}>
          {date.day}
        </Text>
      </View>
    );
  }}
/>
```

**Comment by arifhendraween** [comment]
solved guys, i used touchableopacity and change the value of calendar
