### ISSUE TITLE
Disable Previous/Past dates

### ISSUE THREAD

**Issue by anishtr4** [wix/react-native-calendars#162]
I just want to disable the previous/past dates. I have gone through the doc but ihave not seen any option to disable Past/Previous dates dates

**Comment by AishwaryaSurana** [comment]
Firstly get today's date by,
````
import moment from 'moment';
..
class Mycal extends component
{..
const today = moment().format("YYYY-MM-DD");
..
}
```

Within Component Calendar you can add minDate prop as,
     ```
<Calendar
      ..
      minDate={today}
      />      
```

**Comment by tautvilas** [comment]
Yes, use the `minDate` property.

**Comment by emidsnithin** [comment]
@anishtr4 - It's Not working I Wonder why people tell its working...
![image](https://user-images.githubusercontent.com/43128902/76204232-01629400-621e-11ea-921e-44b5964e8a95.png)


Below the code :
render() {
    const today = moment().format("DD-MM-YYYY");
 <div className="form-group pl-4 pr-4">
                  <label for="startDate">Start Date </label>
                  <input
                    onClick={this.dateSelect}
                    id="datePicker"
                    type="date"
                    name="startDate"
                    className={`form-control ${
                      formErrors.startDate ? "is-invalid" : ""
                    }`}
                    required
                    pattern="\d{2}-\d{2}-\d{4}"
                    minDate={today}
                    max="2020-12-31"
                    onKeyPress={this.deTyped}
                    onChange={this.handleChange}
                    value={formValues.startDate}
                  />
                  <div className="invalid-feedback">{formErrors.startDate}</div>
                </div>
}
