### ISSUE TITLE
Can't overlap events on timeline?

### ISSUE THREAD

**Issue by droplessjake** [wix/react-native-calendars#1620]
## Description

I'm trying to create a current time indicator on the timeline, and have managed to somewhat "hack" it in by rendering a custom styled event element on the timeline with a start/end time of the current time. This actually works quite well for the most part, except for when it comes to overlapping one of my actual timeline elements, in which case it will then place it within a new column and be alongside it. I would ideally like to be able to have the current time marker always on top.

## Expected Behavior

It would good if we could either provide a property in the event object that prevents it from being added to a new column, or even specify the number of columns and allow overlap.
Or the ideal solution would be if we could specify a custom render element for a "current time indicator" that is always rendered above everything else and at the current time.

## Screenshots

See below what I mean by this current time indicator, and how it then wraps to its own column.
![Screenshot 2021-08-31 at 16 23 27](https://user-images.githubusercontent.com/83917938/131530563-4be62a83-e2cf-44dc-acf3-2d70f0f92da5.png)
![Screenshot 2021-08-31 at 16 23 21](https://user-images.githubusercontent.com/83917938/131530585-63764638-9806-46c5-8bcd-296f2f2353f1.png)

**Comment by fwidtmann** [comment]
something like https://github.com/wix/react-native-calendars/pull/1322 ?
