### ISSUE TITLE
Swiping bugs in ExpandableCalendar and WeeklyCalendar

### ISSUE THREAD

**Issue by ireyhanoglu** [wix/react-native-calendars#1626]
## Description

Swiping twice in one direction on ExpandedCalendar in closed position and on WeeklyCalendar causes the calendar to reset to the original week after the second swipe.

## Expected Behavior

Swipe left twice, or right twice. You should now see the week that is 2 weeks previous/after from the week that you originally swiped from. 

## Observed Behavior

You quickly see the week that is 2 weeks previous/after from the week that you originally swiped from, but then the calendar refresh to the original week that you started from

Note: This doesn't happen when you tap on the left/right header arrows. This only happens when swiping.

https://user-images.githubusercontent.com/19961146/132799524-c7d6aae5-810c-4f02-b675-321a891f15fe.mov

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1266.0
* `npm ls react-native`: react-native@0.63.2

Also specify:

1. Device/emulator/simulator & OS version: Android Pixel 3 XL (version 11); iPhone 11 (version 14.7.1)

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.
The only needed to reproduce the issue is
```
<CalendarProvider date={Date()}>
        <ExpandableCalendar hideKnob={true} />
</CalendarProvider>
```
or

```
<CalendarProvider date={Date()}>
        <WeekCalendar />
</CalendarProvider>
```

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by arul36** [comment]
In OnScroll - WeeklyCalendar/Presenter. The argument should be newPage instead of Page is my understanding.
--  
onScroll = ({context, updateState, x, page, items, width}: any) => {
   ...

    if (this._shouldUpdateState(page, newPage)) {
      invoke(context, 'setDate', items[newPage], updateSources.WEEK_SCROLL);
      **const data = this._getItemsForPage(_newPage_, items); //this line**
      updateState(data, newPage);
    }
  };

**Comment by KalpakD** [comment]
> ## Description
> Swiping twice in one direction on ExpandedCalendar in closed position and on WeeklyCalendar causes the calendar to reset to the original week after the second swipe.
> 
> ## Expected Behavior
> Swipe left twice, or right twice. You should now see the week that is 2 weeks previous/after from the week that you originally swiped from.
> 
> ## Observed Behavior
> You quickly see the week that is 2 weeks previous/after from the week that you originally swiped from, but then the calendar refresh to the original week that you started from
> 
> Note: This doesn't happen when you tap on the left/right header arrows. This only happens when swiping.
> 
>  Screen.Recording.2021-09-09.at.9.24.34.PM.mov 
> ## Environment
> Please run these commands in the project folder and fill in their results:
> 
> * `npm ls react-native-calendars`: react-native-calendars@1.1266.0
> * `npm ls react-native`: react-native@0.63.2
> 
> Also specify:
> 
> 1. Device/emulator/simulator & OS version: Android Pixel 3 XL (version 11); iPhone 11 (version 14.7.1)
> 
> ## Reproducible Demo
> Please provide a minimized reproducible demonstration of the problem you're reporting.
> The only needed to reproduce the issue is
> 
> ```
> <CalendarProvider date={Date()}>
>         <ExpandableCalendar hideKnob={true} />
> </CalendarProvider>
> ```
> 
> or
> 
> ```
> <CalendarProvider date={Date()}>
>         <WeekCalendar />
> </CalendarProvider>
> ```
> 
> Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.
> 
> ## Screenshots
> Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

I am also facing same issue swiping weeks not working properly

**Comment by Mako-L** [comment]
I am also facing same issue.

**Comment by Inbal-Tish** [comment]
@Mako-L We're on it. Will have the fix on the next release.
