### ISSUE TITLE
use_native_modules! skipped the react-native dependency 'react-native-calendars'. No podspec file was found.

### ISSUE THREAD

**Issue by jenipharachel** [wix/react-native-calendars#1629]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I created a fork of this repo to customise the package to use it in one of my projects. It is installed and can be used in android. But when I do pod install, I receive the below error.

`use_native_modules! skipped the react-native dependency 'react-native-calendars'. No podspec file was found.`

Hence, I'm not able to run my forked package in iOS. Any help will be appreciated.

## Expected Behavior

What action did you perform, and what did you expect to happen?

`yarn add https://github.com/xxxxxx/react-native-calendars.git`
`pod install`

Expected pod install to run completely with no issues.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
[!] use_native_modules! skipped the react-native dependency 'react-native-calendars'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary
    podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The
    react-native-webview podspec is a good example of a package.json driven
    podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it
    manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Device/emulator/simulator & OS version: iPhone 12 simulator

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by riamon-v** [comment]
Following this
