### ISSUE TITLE
Can't run the example project

### ISSUE THREAD

**Issue by omer-to** [wix/react-native-calendars#1632]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I'm not able to install pods, and run the project following the [Try it out](https://github.com/wix/react-native-calendars#try-it-out) section.

## Expected Behavior
I ran the following commands in sequence:
```bash
yarn # install dependencies
npx pod-install ios # also tried cd ios && pod install
```

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:
```bash
➜  react-native-calendars git:(master) ✗ npx pod-install ios
npx: installed 1 in 0.786s
Scanning for pods...
1.10.2
> pod install
Auto-linking React Native module for target `CalendarsExample`: ReactNativeNavigation
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
```
![image](https://user-images.githubusercontent.com/63205993/134425433-03a0acef-0ca1-4e79-93c5-da06ba232470.png)

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Device/emulator/simulator & OS version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by sflahave** [comment]
@omer-to - I ran into the same issue and was able to get around it by removing this line in `./ios/Podfile`:

```
source 'https://github.com/CocoaPods/Specs.git'
```

Then, run this command from the project root: 
```
npm run pod-install
```
Finally, run 
```
npm run ios
```

![simulator_screenshot_F0FD4F6A-B615-4715-A54A-6FFCC022937B](https://user-images.githubusercontent.com/1036645/140594033-bc2bd667-533c-472d-be63-b2eab3f52ae6.png)
