### ISSUE TITLE
How to open/close ExpandableCalendar of react-native-calendars programmatically?

### ISSUE THREAD

**Issue by xionxiao** [wix/react-native-calendars#1634]
I want to open/close ExpandableCalendar programmatically. I found there's only an ```initialPosition``` prop. It's not working when changing ```initialPosition```. So I tried to use ref and call ```setPosition()``` function of ExpandableCalendar

```typescript
export const MyScreen = () => {

    const ref = useRef<ExpandableCalendar>()

    return (
        <CalendarProvider date={new Date()}>
            <ExpandableCalendar ref={ref} />
        </CalendarProvider>
    )
}
```

when I use this code, the ```ref.current.contentRef``` is always ```undefined```

## My Question is
* How to get the ```ref``` of ExpandableCalendar? 
   It seems the ```asCalendarConsumer``` saves the ref as contentRef:
  ```typescript
  function asCalendarConsumer(WrappedComponent: React.ComponentType<any>): React.ComponentClass {
  
    class CalendarConsumer extends Component {
      contentRef: any;
  
      saveRef = (r: Ref<React.Component<any>>) => {
        this.contentRef = r;
      };
  
      render() {
        return (
          <CalendarContext.Consumer>
            {context => <WrappedComponent ref={this.contentRef} context={context} {...this.props} />}
          </CalendarContext.Consumer>
        );
      }
    }
  
    hoistNonReactStatic(CalendarConsumer, WrappedComponent);
  
    return CalendarConsumer;
  }
  
  export default asCalendarConsumer;
  ```
  ```typescript
  export default asCalendarConsumer(ExpandableCalendar);
  ```

* Is there a way to open ExpandableCalendar programmatically? Does the setPosition() function work or there's another way to do this. I found an issue #1362 is in progress.

## My Environment is

* `react-native-calendars@1.1266.0`:
* `react-native@0.64.2`:

**Comment by cmorbitzer** [comment]
If #1674 is merged, this will work:
```js
const calendar = ref.current?.contentRef;
calendar?.bounceToPosition(
  calendar.state.position === ExpandableCalendar.positions.OPEN
    ? calendar.closedHeight
    : calendar.openHeight
);
```
but it's real dirty and relies heavily on internals. #1362 would be a better solution

**Comment by mrpmohiburrahman** [comment]
> If #1674 is merged, this will work:
> 
> ```js
> const calendar = ref.current?.contentRef;
> calendar?.bounceToPosition(
>   calendar.state.position === ExpandableCalendar.positions.OPEN
>     ? calendar.closedHeight
>     : calendar.openHeight
> );
> ```
> 
> but it's real dirty and relies heavily on internals. #1362 would be a better solution

In my case it's not working.
It says ref for ExpandableCalendar does not exists.
Is there any other way? or How so solve this?
Here is my code snippet

```const ref = useRef<ExpandableCalendar>();
  useEffect(() => {
    const calendar = ref.current?.contentRef;
    setTimeout(() => {
      calendar?.bounceToPosition(
        calendar.state.position === ExpandableCalendar.positions.OPEN ? calendar.closedHeight : calendar.openHeight
      );
    }, 500);
  }, []);

  return (
    <Animated.View entering={FadeIn.delay(100)}>
      {/* https://github.com/wix/react-native-calendars/issues/2046#issuecomment-1295467711 */}
      <CalendarProvider date={new Date()}>
        <ExpandableCalendar ref={ref} firstDay={1} markedDates={marked.current} />
      </CalendarProvider>
    </Animated.View>
  );```
