### ISSUE TITLE
Drag&Drop feature

### ISSUE THREAD

**Issue by rcrvano** [wix/react-native-calendars#1642]
Hello! 

Do you plan to implement drag&drop feature for agenda?

**Comment by IrisHCI** [comment]
Hi there! We would be highly interested in a drag 'n drop feature in the agenda too! :-)

**Comment by silviosampaio** [comment]
Yes... should be good for TimelineList also...

**Comment by Shahzaib114** [comment]
there should be drag and drop feature

**Comment by nhemgomia** [comment]
Is there a Drag and Drop feature already?
