### ISSUE TITLE
jest shows error: TypeError: Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by TyrealGray** [wix/react-native-calendars#165]
## Description
When using jest to run snapshot, an error message shows up "jest shows error: TypeError: Cannot read property 'clone' of undefined"

## Expected Behavior

No error in test suites.

**Comment by TyrealGray** [comment]
fixed error by using `jest.mock`
```
jest.mock('react-native-calendars', ()=> {
	return {
            Calendar:()=> null,
	};
});
```

**Comment by hari3110** [comment]
Hi @TyrealGray, where should i add above code?
I am having same error in android only in production mode in development its working fine.

**Comment by TyrealGray** [comment]
@hari3110 adding at a common init function in jest should be enough.

**Comment by TyrealGray** [comment]
@hari3110 wait, are you saying you are not using jest to unit test your component but still have this error? I don't have any problem in using it.

**Comment by hari3110** [comment]
@TyrealGray Can you guess what can be problem here?

![processed](https://user-images.githubusercontent.com/58428834/80584050-c2d3a380-8a2e-11ea-873d-533219a49d1f.jpeg)

**Comment by TyrealGray** [comment]
@hari3110 Sorry, I have no idea what's could be wrong. I haven't done react-native for a long time.

**Comment by hari3110** [comment]
Np! Thanx :)

**Comment by amirhosein5858** [comment]
i use this and works for me:
`
jest.mock('react-native-calendars', () => {
  return {
    Calendar: () => null,
    LocaleConfig: {
      locales: {}
    }
  };
});
`
