### ISSUE TITLE
Same background color in numbers of calendar and week header

### ISSUE THREAD

**Issue by Phector27** [wix/react-native-calendars#1658]
Hi! 

First, I hope you a nice day to all.

## Description

How to get same background in numbers of calendar and week header

## Expected Behavior

Could put the same background color on week days and numbers but different on months.

## Screenshots

Actually I only can(know) change the background color of week row:

![actual](https://user-images.githubusercontent.com/65594529/137297417-d622a0b2-962d-4b6f-9138-a8a932c5bb62.png)

But I need some like this:

![objetivo](https://user-images.githubusercontent.com/65594529/137297454-5f1f8086-299e-4b6e-b2f5-3951cc18d184.png)

Last image I got it with a absolute position  of View component, but when I make scroll, the absolute position of view dont move (obviusly).

How could I change only the background of the week days and numbers of calendar like last screenshoot?

Here my <CalendartList /> code:

```
      <CalendarList
        firstDay={1}
        markedDates={selectedDays}
        onDayPress={_onDayPress}
        pastScrollRange={1}
        futureScrollRange={1}
        scrollEnabled={true}
        showScrollIndicator={false}
        theme={{
          backgroundColor: '#FF7066', // Not change nothing
          calendarBackground: 'transparent', // If change it, change all calendar bg
          textSectionTitleColor: '#FFF',
          selectedDayBackgroundColor: 'transparent',
          selectedDayTextColor: '#FFF',
          todayTextColor: '#FFF',
          todayBackgroundColor: '#FF7066',
          dayTextColor: 'gray', //Disabled days
          dotColor: '#FF7066',
          selectedDotColor: '#FFF',
          monthTextColor: '#FFF',
          textDayFontWeight: '300',
          textMonthFontWeight: 'bold',
          textDayHeaderFontWeight: '300',
          'stylesheet.calendar.header': {
            header: {
              flexDirection: 'row',
              justifyContent: 'flex-start',
              alignItems: 'center',
            },
            week: {
              marginTop: 20,
              flexDirection: 'row',
              justifyContent: 'space-between',
              backgroundColor: 'rgba(125,125,125,0.25)', //Here I can change only the background week days
            },
          },
          textDayFontSize: 14,
          textMonthFontSize: 16,
          textDayHeaderFontSize: 14,
        }}
      >
```

Thanks!!

**Comment by Phector27** [comment]
Hi again. Any solution?

**Comment by glushkina1** [comment]
Hi again. Any solution?

Thanks!!

**Comment by Phector27** [comment]
Nothing guys? Im trying all to make this changes but impossible

**Comment by cmerick** [comment]
As far as i got it should be marked like this ['stylesheet.calendar.header'] and it doesn't has the option for header, only week and if you want to change de color of the main header you code headerStyle out of the theme like 

`headerStyle={{
              backgroundColor: 'black',
            }}
            theme={{
              ['stylesheet.calendar.header']: {
                week: {
                  marginTop: 20,
                  flexDirection: 'row',
                  justifyContent: 'space-between',
                  backgroundColor: 'rgba(125,125,125,0.25)', //Here I can change only the background week days
                },
              },...`
             
             probably it has to be with markingType: 'custom' and the week color will overlap the headerStyle.

**Comment by mjroeleveld** [comment]
```
        theme={{
          calendarBackground: 'green',
          stylesheet: {
            calendar: {
              main: {
                container: {
                  backgroundColor: 'green',
                },
              },
            },
          },
        }}
```

**Comment by george-eucare** [comment]
Hi again. Any solution?

Thanks!!
