### ISSUE TITLE
It cannot view past item with Agenda,can I use DESC mode?

### ISSUE THREAD

**Issue by RogerWenXin** [wix/react-native-calendars#1663]
I want scroll up to show past in Agenda, can I do this?
I mean Items sorted by date with DESC mode, I need this in a hurry， I hope u give me a work-around

**Comment by RogerWenXin** [comment]
I just modified the src code, build an version that accord with my need, I can give you the code, u r welcome.  And you should install that github vesion, and copy my code, and import from my code folder. 
------------------------------------------------------------------
发件人：Burane ***@***.***>
发送时间：2021年10月26日(星期二) 20:45
收件人：wix/react-native-calendars ***@***.***>
抄　送：Roger ***@***.***>; Author ***@***.***>
主　题：Re: [wix/react-native-calendars] It cannot view past item with Agenda,can I use DESC mode? (Issue #1663)

same for me cannot scroll to a date past the selected date
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RogerWenXin** [comment]
link: https://pan.baidu.com/s/1PrD-6H6qFaK5QeGcfHbKZA code: disw copy the code to download

**Comment by cederom** [comment]
+1 for scrolling back agenda items.. but last release is from 2018 and I realised this project may be dead :-(
