### ISSUE TITLE
Agenda 'selected' property is defined as boolean in AgendaProps but the code tries to parse it as a date?

### ISSUE THREAD

**Issue by jeffthompson1971** [wix/react-native-calendars#1664]
## Description
Agenda 'selected' property is defined as boolean in AgendaProps but the code tries to parse it as a date?  Which is it?  Seems it should be a date but why not change the props definition then.  My IDE flags as type error.  Can you fix the type in the next patch please? Or it has a comment to change to selectedDay maybe just knock that out?  Would be much appreciated if not too much trouble.   Also any plan to make this typescript?  

## Expected Behavior

Expect consistency.   Is it a boolean or a Date?  I would even just like an answer to that.   Is the 'selected' how you intitialize what date is shown first or what is the purpose of it as a boolean?

## Observed Behavior
You can see the Props expect boolean:

export type AgendaProps = CalendarListProps & ReservationListProps & {
  /** the list of items that have to be displayed in agenda. If you want to render item as empty date
   the value of date key has to be an empty array []. If there exists no value for date key it is
   considered that the date in question is not yet loaded */
  items: ReservationsType;
  /** callback that gets called when items for a certain month should be loaded (month became visible) */
  loadItemsForMonth?: (data: any) => DateData;
  /** callback that fires when the calendar is opened or closed */
  onCalendarToggled?: (enabled: boolean) => void;
  /** callback that gets called on day press */
  onDayPress?: (data: DateData) => void;
  /** callback that gets called when day changes while scrolling agenda list */
  onDayChange?: (data: any) => void;
  /** specify how agenda knob should look like */
  renderKnob?: () => JSX.Element;
  /** initially selected day */
  **selected: boolean, //TODO: Should be renamed 'selectedDay'**
  /** Hide knob button. Default = false */
  hideKnob: boolean,
  /** When `true` and `hideKnob` prop is `false`, the knob will always be visible and the user will be able to drag the knob up and close the calendar. Default = false */
  showClosingKnob: boolean
}

But in the Agenda index.js it's being parsed as a Date? 
componentDidUpdate(prevProps: AgendaProps) {
    **if (this.props.selected && !sameDate(parseDate(this.props.selected), parseDate(prevProps.selected))) {**
      this.setState({selectedDay: parseDate(this.props.selected)});
    } else if (!prevProps.items) {
      this.loadReservations(this.props);
    }
  }

**Comment by JB712** [comment]
Just in case anyone would have se same question: it is wrong defined. I need a date with 'YYYY-mm-dd' format.
