### ISSUE TITLE
Calendar stuck in blank screen

### ISSUE THREAD

**Issue by kstamboni** [wix/react-native-calendars#1667]
## Description

I see this behavior when the user move fastly to edges of screen (top or bottom), the calendar doesn't load until another scrolling action. Any solution to avoiding it?

## Expected Behavior

Calendar month should render.

## Observed Behavior

It frozen in blank screen until another scrolling.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1268.0
* `npm ls react-native`: react-native@0.66.1 

Also specify:

1. Device/emulator/simulator & OS version: 
Lenovo A6020a40
Android 5.1.1

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

I used an instance like this:

` <CalendarList
        markingType={'custom'}
        onDayPress={dateObject => console.log(dateObject)}
        markedDates={{}}
        minDate={undefined}
        maxDate={new Date()}
        pastScrollRange={60}
        futureScrollRange={0}
        scrollEnabled={true}
        calendarHeight={300}
        showScrollIndicator={true}
        theme={{
          textDayFontSize: 16,
          textMonthFontSize: 16,
          textDayHeaderFontSize: 16,
          'stylesheet.calendar.header': {
            header: {
              justifyContent: 'flex-start',
              paddingLeft: 12,
            },
            week: {
              marginTop: 20,
              marginBottom: 7,
              flexDirection: 'row',
              justifyContent: 'space-around',
            },
          },
          'stylesheet.calendar-list.main': {
            calendar: {
              paddingLeft: 0,
              paddingRight: 0,
              width: '100%',
            },
          },
          'stylesheet.calendar.main': {
            week: {
              marginTop: 2,
              marginBottom: 2,
              flexDirection: 'row',
              justifyContent: 'space-around',
            },
          },
        }}
      />`

Scroll before the month name label showing up until the edge of screen.

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

https://user-images.githubusercontent.com/6832833/138965315-6c43a363-54af-4427-9e1a-c6c104ba3f5e.mp4
(bug starts at 0:30)

Thank you!

**Comment by HTaiNguyen** [comment]
Did you manage to fix this issue ? I got the same problem

**Comment by dngconsulting** [comment]
Same pb here

**Comment by denistea** [comment]
Hi, adding `removeClippedSubviews={false}` on the CalendarList component seems to fix the problem

**Comment by onlybenyang** [comment]
fix it with adding scrollToMonth('1999-01-01') and scrollToMonth('2999-01-01') actions in onLayout of CalendarList
