### ISSUE TITLE
Is there a way to display the month and move to next week in Agenda component?

### ISSUE THREAD

**Issue by jeffthompson1971** [wix/react-native-calendars#1668]
## Description

I'm using just the Agenda component.   There is no way I can see to either display the month OR be able to move to the next week (i.e left/right arrows to move to previous or next week)  Is there some way to use Agenda but give users ability to scroll to next week without having to pull down the calendar list and pick a day?  Also when you do pull down the calendar list and choose a day, the month is not displayed so there is no way to know what month you are even on.   Is there a way to show the month at all times?

## Screenshots
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2018750/139267470-f82093e0-df43-4534-8093-e8b09597ff88.png">

**Comment by rajesh-rt** [comment]
Is there any call back to check if the month is changes?
