### ISSUE TITLE
CalendarList scrollToIndex out of range 

### ISSUE THREAD

**Issue by mahantesh-maningol** [wix/react-native-calendars#1677]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

CalendarList pastScrollRange assigning calculated value to 1, getting the error scrollToIndex out of range: requested index 1 is out of 0 to 0 whereas if we set value to directly 1(Manually) then not getting the error 

Initial useState 
 const [showPrevMonth, setShowPrevMonth] = useState<boolean>(true)

Value calculating by 
useEffect(() => {
    setShowPrevMonth(
      moment(today).month() + 1 === moment(startDateToBeShown).month() + 1
        ? false
        : true,
    )
  }, [startDateToBeShown])

Passing the result as like this
<CalendarList
          ref={calendarRef}
          current={today}
          calendarHeight="auto"
          theme={calTheme}
          firstDay={1}
          dayComponent={generateDayComponent}
          monthFormat={'MMMM'}
          hideExtraDays={true}
          markedDates={formattedMergedDays}
          futureScrollRange={showNextMonth ? 1 : 0}
          pastScrollRange={showPrevMonth ? 1 : 0}
          maxDate={endDateToBeShown}
          scrollEnabled={true}
        />

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

Getting the bellow error

```
scrollToIndex out of range: requested index 1 is out of 0 to 0 
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Device/emulator/simulator & OS version:
Using IOS Simulator
<img width="458" alt="Screenshot 2021-11-07 at 9 39 17 AM" src="https://user-images.githubusercontent.com/90369311/140714821-5824758a-6f28-4fc1-a7b4-ecec489ec5c6.png">

**Comment by entttom** [comment]
@mahantesh-maningol did you solve the problem?
