### ISSUE TITLE
PrettyFormatPluginError: Invalid string lengthRangeError: Invalid string length in latest version

### ISSUE THREAD

**Issue by saikirannani123** [wix/react-native-calendars#1678]
## Description

When I'm trying to run the jest to jest coverage the test cases are getting failed in my current project. After few cross check I can confirm that the error is happening because of using the latest version of this library (1.1268.0). 

 I remember using this library from the past 2 months but this is the very first time this error in jest is occurring.  After few  more observations I can see that the library has been updated 2 days ago related to Eslint errors. Not sure if that might be the reason. So I downgraded (make a static) version to 1.1262.0. After reinstalling node modules and running the jest cases the all the test cases are happened to pass. 

 I strongly believe this might be because of latest version changes. Please check this issue to make the package.json to ^1.1262.0 instead of using the static 1.1262 so we can keep our code or changes updated to the latest versions of the library.

## Expected Behavior

All the test cases are happened to pass successfully without any issues/errors

## Observed Behavior

Test cases/Test suits are getting failed continuously.

```
PrettyFormatPluginError: Invalid string lengthRangeError: Invalid string length
7431      at printObjectProperties (node_modules/jest-snapshot/node_modules/pretty-format/build/collections.js:172:47)
```

## Environment
* `Android`:
* `iOS`:
* `jest`
* `npm ls react-native-calendars`:
* `npm ls react-native`:

## Screenshots
<img width="823" alt="Screenshot 2021-11-08 at 11 56 42 PM" src="https://user-images.githubusercontent.com/27265601/140798512-a9741179-7f40-4850-901a-ff9096ab76d4.png">

<img width="350" alt="Screenshot 2021-11-09 at 12 06 37 AM" src="https://user-images.githubusercontent.com/27265601/140798573-1dff70c6-0e28-490b-9d8d-6aa80be9552b.png">

**the above 2 screenshots are related to package.json file and jest coverage in terminal while we are getting the error.** 

<img width="465" alt="Screenshot 2021-11-08 at 11 59 12 PM" src="https://user-images.githubusercontent.com/27265601/140798684-2def1e67-c3f2-495f-9f69-17d6c080a284.png">

<img width="701" alt="Screenshot 2021-11-09 at 12 08 06 AM" src="https://user-images.githubusercontent.com/27265601/140798781-d419e65a-e76d-4704-8316-ec0d2aea48d7.png">

**the above 2 screenshots are related to package.json file and jest coverage in terminal where we don't get the jest failure error after changing the react-native-calendars version to 1.1262.0 static version..** 

Note: Currently we have a workaround to make it work by just keeping the static version. But in order to keep our project or others who are using this library to update, I'm not sure if it is suggested to use the static hardcoded version instead of dynamic.

**Comment by MarJaysonSanAgustin** [comment]
You can mock external/package dependencies using jest now.
e.g.
`jest.mock('react-native-calendars');`
