### ISSUE TITLE
CalendarList onScrollEndDrag not firing - scroll jump on paging

### ISSUE THREAD

**Issue by mfbx9da4** [wix/react-native-calendars#1690]
Slowly dragging to the next month in calendar list can cause it to jump or snap to the next month why might that be?https://user-images.githubusercontent.com/1690659/142847024-94138076-d9e3-4f50-b310-5e9fba9d84f9.MOV

**Comment by mfbx9da4** [comment]
I've realized the reason it's jumping is because I set the the current date on visible months change like so

```
onVisibleMonthsChange={months => {
            const [month] = months
              setCurrentDate(dayjs(month.dateString).startOf('month').toDate())
          }}
```

**Comment by mfbx9da4** [comment]
Is there anyway to know if the user is still dragging?

**Comment by mfbx9da4** [comment]
The `onScrollEndDrag` event handler is not firing

**Comment by mit4dev** [comment]
Having the same issue on v1.1278.0, any solutions?

**Comment by mfbx9da4** [comment]
You can fork and add the listener to the underlying flat list yourself
