### ISSUE TITLE
Theme prop Don't work in CalendarProvider

### ISSUE THREAD

**Issue by Michael-Irizarry** [wix/react-native-calendars#1692]
Hi, the theme prop of  CalendarProvider don't work.

**Comment by Longshoez** [comment]
It also doesnt work on Calendar and CalendarList

**Comment by personalnadir** [comment]
@Longshoez I had a similar issue. It seems that changes to the theme prop do not cause the component to refresh. Manually refreshing the app caused changes to the theme prop to appear.

**Comment by KubilayKerim** [comment]
Manually refreshing the app does nothing in my case it just does not work
