### ISSUE TITLE
undefined is not and object (evaluating '_props[registrationName]')

### ISSUE THREAD

**Issue by manrashid** [wix/react-native-calendars#17]
On android with RN0.43.4. Just trying out the example.
I was using exactly the same code as the example in AgendaScreen. When I press the date on top of the agenda list, the above error shown. 

I've found that only when I touch the Text area the error will occur. Try avoid the text when touching the date and there will be NO error.

Probably related to this http://stackoverflow.com/questions/43674781/undefined-is-not-and-object-evaluating-propsregistrationname

**Comment by dongawli** [comment]
@tautvilas : I am too facing this issue on Android Emulator - https://hub.mangoapps.com/sf/ODcxMTlfMTMyNzAwMA
Can you please help us how to resolve this?

**Comment by tautvilas** [comment]
I will try to look at this problem today

**Comment by tautvilas** [comment]
I tried adding the stackoverflow suggested workaround. Check if that fixes the problem for you in version v1.2.14 (I did not test with RN43 and in RN44 I could not reproduce this bug)

**Comment by dongawli** [comment]
Thank you. 

Yes, issue is resolved now.
