### ISSUE TITLE
Change size of the date marker according to the dayContainer

### ISSUE THREAD

**Issue by neerajpk02** [wix/react-native-calendars#1703]
My calendar have custom styles applied like grid view for date component. I wanted to resize the marked dates with marking type custom style. I am able to change the border and colours but when i change the size, it overlaps the other date. 

Is there any way we can have the custom marker that fits the day container ? 

![Simulator Screen Shot - iPhone 11 - 2021-12-09 at 14 32 33](https://user-images.githubusercontent.com/87416192/145367627-9c077ce7-612f-4dcb-99df-b3fcb7f22efb.png)

**Comment by kaputadali** [comment]
did you try going to the node modure under src folder in style.js and change ??
export const todayButtonFontSize = 14;
