### ISSUE TITLE
Unable to resolve module ../component-updater

### ISSUE THREAD

**Issue by RimApp** [wix/react-native-calendars#1710]
Hi all !
Can someone help me please?

## Description
I can no longer build my react native project on my android device.
I got the error : Unable to resolve module ../component-updater

## Expected Behavior
I did :
./gradlew clean
remove package-lock.json and node_modules
npm cache clean
and finally npm install

## Observed Behavior
```
error: Error: Unable to resolve module ../component-updater from C:\Users\Sami\Documents\Previsy\Previsy\node_modules\react-native-calendars\src\calendar\index.js:

None of these files exist:
  * node_modules\react-native-calendars\src\component-updater(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-calendars\src\component-updater\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import invoke from 'lodash/invoke';
  2 | import PropTypes from 'prop-types';
  3 | import XDate from 'xdate';
  4 | import memoize from 'memoize-one';
    at ModuleResolver.resolveDependency (C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:211:15):15)    at DependencyGraph.resolveDependency (C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)        
    at Object.resolve (C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Sami\Documents\Previsy\Previsy\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
 react-native-calendars@1.1271.0
* `npm ls react-native`:
 @react-native-community/cli@5.0.1
│ └── react-native@0.64.3 deduped
├─┬ @react-native-community/masked-view@0.1.11
│ └── react-native@0.64.3 deduped
├─┬ @react-native-picker/picker@1.16.8
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/bottom-tabs@5.11.15
│ ├─┬ @react-navigation/native@3.8.4 invalid: "^5.0.5" from node_modules/@react-navigation/bottom-tabs, "^5.0.5" from node_modules/@react-navigation/drawer, "^5.0.5" from node_modules/@react-navigation/stack
│ │ └─┬ react-native-safe-area-view@0.14.9
│ │   └── react-native@0.64.3 deduped
│ ├─┬ react-native-iphone-x-helper@1.3.1
│ │ └── react-native@0.64.3 deduped
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/drawer@5.12.9
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/stack@5.14.9
│ └── react-native@0.64.3 deduped
├─┬ native-base@2.15.2
│ ├─┬ @codler/react-native-keyboard-aware-scroll-view@1.0.1
│ │ └── react-native@0.64.3 deduped
│ ├─┬ jest-react-native@18.0.0
│ │ └── react-native@0.64.3 deduped
│ ├─┬ native-base-shoutem-theme@0.3.1
│ │ └── react-native@0.64.3 deduped
│ └── react-native@0.64.3 deduped
├─┬ react-native-action-button@2.8.5
│ └── react-native@0.64.3 deduped
├─┬ react-native-animate-loading-button@1.0.4 (git+ssh://git@github.com/RimApp/react-native-animate-loading-button.git#f3ae7222fe15a8124547fab19ce53a8a770a1a1a)
│ └── react-native@0.64.3 deduped
├─┬ react-native-circular-progress@1.3.7
│ └── react-native@0.64.3 deduped
├─┬ react-native-color-palette@2.2.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-country-picker-modal@2.0.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-elements@3.4.2
│ ├─┬ react-native-ratings@8.0.4
│ │ └── react-native@0.64.3 deduped
│ └─┬ react-native-size-matters@0.3.1
│   └── react-native@0.64.3 deduped
├─┬ react-native-fast-image@8.5.11
│ └── react-native@0.64.3 deduped
├─┬ react-native-google-places-autocomplete@2.4.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-iap@5.2.14
│ └── react-native@0.64.3 deduped
├─┬ react-native-image-crop-picker@0.37.2
│ └── react-native@0.64.3 deduped
├─┬ react-native-keyboard-accessory@0.1.16
│ └── react-native@0.64.3 deduped
├─┬ react-native-keyboard-aware-scroll-view@0.9.5
│ └── react-native@0.64.3 deduped
├─┬ react-native-localize@2.1.6
│ └── react-native@0.64.3 deduped
├─┬ react-native-modal@11.10.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-reanimated@2.3.0
│ ├─┬ react-native-screens@3.10.1
│ │ └── react-native@0.64.3 deduped
│ └── react-native@0.64.3 deduped
├─┬ react-native-responsive-screen@1.4.2
│ └── react-native@0.64.3 deduped
├─┬ react-native-safe-area-context@3.3.2
│ └── react-native@0.64.3 deduped
├─┬ react-native-screens@2.18.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-snap-carousel@3.9.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-svg@12.1.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-swipe-list-view@3.2.9
│ └── react-native@0.64.3 deduped
├─┬ react-native-user-avatar@1.0.7
│ └── react-native@0.64.3 deduped
├─┬ react-native-week-view@0.5.0
│ └── react-native@0.64.3 deduped
├── react-native@0.64.3
├─┬ react-navigation@4.4.4
│ └── react-native@0.64.3 deduped
└─┬ react-router-native@5.2.1
  └── react-native@0.64.3 deduped
1. Device/emulator/simulator & OS version:
Android device : Galaxy A12

**Comment by hoanganhle1996** [comment]
Did you solve it yet ?

**Comment by VirtualDOMinic** [comment]
This won't be of much help, but one thing that worked for my colleague just now was using v 1.1266.0 . Can't vouch for other versions, but another, newer, one might also work:

1. `"react-native-calendars": "1.1266.0"` in `package.json`
2. remove package-lock and node_modules
3. npm i
4. success

Sorry for brief nature of this reply -- I've got a busy morning!

**Comment by RimApp** [comment]
@hoanganhle1996  I cloned my repo in a previous version. I can no longer reproduce
@VirtualDOMinic Thank you for the tip ! If I reproduce I will try this solution

**Comment by owenadley** [comment]
@RimApp what did you do to fix the issue?

**Comment by RimApp** [comment]
> @RimApp what did you do to fix the issue?

I just use a previous version of my app, so a previous version of `react-native-calendars` and clean the node module (
remove `package-lock.json` and `node_modules` folder
and finally `npm i`.

If still not working try these:

1. use previous version of react-native-calendars
2. `cd android`
3. `.\gradlew clean`
4. `cd ..`
5. `Remove-Item package-lock.json , node_modules -Force -Recurse`
6. `npm cache clean --force`
7. `npm i`

and in two differents terminal, run :
`react-native start --reset-cache`
`npx react-native run-android`
