### ISSUE TITLE
Warning: Failed prop type: Invalid prop `current` of type `object` supplied to `CalendarListItem`, expected `string`

### ISSUE THREAD

**Issue by musa-c** [wix/react-native-calendars#1724]
Agenda warning!
I am getting two kinds of errors. one is related to 'CanlendarList' and the other is related to 'CalendarListItem' but I couldn't figure out where the problem is. I would be glad if you help.

```
1. Warning:
Warning: Failed prop type: Invalid prop `current` of type `object` supplied to `CalendarListItem`, expected `string`
2. Warning:
Failed prop type: Invalid prop `current` of type `object` supplied to `CalendarList`, expected `string`.

```

` 
import React, { useEffect, useState } from 'react'
import { View, Text, TouchableOpacity } from 'react-native'
import {Calendar, Agenda, LocaleConfig} from 'react-native-calendars';
import {Card} from "react-native-paper"; 
`

const Agenta = () => {

    const [items, setItems] = useState({});
    const loadItems = (day) => {
        setTimeout(() => {
          for (let i = -15; i < 85; i++) {
            const time = day.timestamp + i * 24 * 60 * 60 * 1000;
            const strTime = timeToString(time);
            if (!items[strTime]) {
              items[strTime] = [];
              const numItems = Math.floor(Math.random() * 3 + 1);
              for (let j = 0; j < numItems; j++) {
                items[strTime].push({
                  name: 'Item for ' + strTime + ' #' + j,
                  height: Math.max(50, Math.floor(Math.random() * 150)),
                });
              }
            }
          }
          const newItems = {};
          Object.keys(items).forEach((key) => {
            newItems[key] = items[key];
          });
          setItems(newItems);
        }, 1000);
      };

![ss0](https://user-images.githubusercontent.com/69965176/146598172-1be5eb87-d8fb-4053-af35-b4a825834220.png)

![ss1](https://user-images.githubusercontent.com/69965176/146598229-26f25f18-494d-4288-bfdb-c94ce2de9130.png)

## Environment

* `npm ls react-native-calendars`:  react-native-calendars@1.1274.0
* `npm ls react-native`: react-native@0.63.2

I'm using EXPO

**Comment by softwarebyjims** [comment]
Same, I am having the same issue

**Comment by flexa-david** [comment]
Also experiencing this issue after updating packages

**Comment by EnesEmreDemir** [comment]
I am having the same issue. Can't use agenda in my project.

**Comment by jdaniel-ap** [comment]
Same here, I can use but has this error. Idk how to fixed.

**Comment by irakli-g** [comment]
I'm experiencing same issue but I still can use the calendar despite this warning.

**Comment by Bhupendra1728** [comment]
i also experiencing the same issue it shows the same warning on the initial load.

**Comment by PetromirDev** [comment]
Non expo have the same issue

**Comment by alperkilickaya** [comment]
I have the same issue while using only Agenda. Agenda works as expected.

**Comment by PetromirDev** [comment]
Has anyone found a solution?

**Comment by betomoedano** [comment]
same error :(

**Comment by jasselmar** [comment]
Same

**Comment by koryrichardson** [comment]
Also getting this warning

**Comment by keensoen** [comment]
Updating the package to latest version solve the problem for me.

**Comment by jdaniel-ap** [comment]
> Updating the package to latest version solve the problem for me.

Doesn't work for me.

**Comment by jdaniel-ap** [comment]
> Updating the package to latest version solve the problem for me.

Same here.

**Comment by musa-c** [comment]
> Paketi en son sürüme güncellemek benim için sorunu çözüyor.

problem solved thanks
