### ISSUE TITLE
Swiping is too difficult to change months in Calendar

### ISSUE THREAD

**Issue by ahkaneti** [wix/react-native-calendars#1729]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Hi! I'm trying to build a calendar component but I can only swipe after clicking a day. Swiping is too difficult. When I add a gesture handler myself it's movement is intercepted by the Calendar.

## Expected Behavior

What action did you perform, and what did you expect to happen?

I wanted to just swipe anywhere and get the month to change but if I’m not clicking a day, the month won't change. 

## Observed Behavior

What actually happened when you performed the above actions?

Nothing on clicking to the sides and only changes when I press a day and then swipe.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1269.0

Also specify:

1. Device/emulator/simulator & OS version: iPhone 13, last OS.

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by yairopro** [comment]
I confirm that the `Calendar` component is hard to swipe **on android**. On iOS, it's much easier.

https://user-images.githubusercontent.com/8110568/150860046-08b22a34-ba79-469d-9c12-ea198670c425.mp4

**Comment by yairopro** [comment]
no stale
