### ISSUE TITLE
Agenda example does not work with error msg: Invalid undefined 'height' of type 

### ISSUE THREAD

**Issue by shahehe** [wix/react-native-calendars#173]
Try to run the demo Agenda component and got the error message:

Invalid undefined 'height' of type 'string' supplied to 'StyleSheet header' , expected 'number'
StyleSheet header : {
  "overflow": "hidden",
  "justifyContent": "flex-end",
  "position": "absolute",
  "height": "100%",
  "widht": "100%",
}

**Comment by tautvilas** [comment]
Hi do you experience same problem if you try running example with latest react-native-calendars code?

**Comment by tautvilas** [comment]
closing because no input from user

**Comment by eashevchenko** [comment]
I have same problem with Agenda component. I m using react-native version 0.41.2. How can i fix this ?
