### ISSUE TITLE
Does this library work with the Web version ？

### ISSUE THREAD

**Issue by pxim** [wix/react-native-calendars#1733]
## Description

Does this library work with the Web version ？

**Comment by yairopro** [comment]
Almost.
Since react-scripts removes the `propTypes` fields from third party components in the production build, it cannot be shipped though it works locally  like a charm.

**Comment by sirshad01** [comment]
Any chance web support is coming soon?

**Comment by yairopro** [comment]
No stale

**Comment by yairopro** [comment]
No stale

**Comment by TNAJanssen** [comment]
This is not completely finished and should not be stale. There are still issues on the web version.
