### ISSUE TITLE
Timeline format24h wrong format

### ISSUE THREAD

**Issue by busyxiang** [wix/react-native-calendars#1738]
## Description

Timeline component display wrong format when `format24h={false}`, for example its displaying **10:06A** instead of **10:06AM**

## Expected Behavior

Expect to output the correct format

## Screenshots
<img width="223" alt="Screenshot 2021-12-29 at 5 38 40 PM" src="https://user-images.githubusercontent.com/19426419/147648469-368796fb-b3b7-4761-8b68-7c034b9a52d6.png">

**Comment by bn1ck** [comment]
This problem continues to exist. Can it be fixed

**Comment by CalebLuster** [comment]
> This problem continues to exist. Can it be fixed. It shows A when the time is in the PM. This is a bit misleading <img alt="image" width="406" src="https://user-images.githubusercontent.com/10984779/210689866-7e705827-a538-4b77-9e78-be7eed09da16.png">

Hello I know this is old but did you find a solution to this?
