### ISSUE TITLE
Customize Agenda CalendarList Height and Orientation

### ISSUE THREAD

**Issue by pchen03** [wix/react-native-calendars#1749]
Is there a prop in the agenda component to customize the CalendarList to make it horizontal, and/or give it a custom height? If not, would it be possible to hide the CalendarList in the Agenda?

**Comment by Klemminn** [comment]
I agree, it would be wonderful if horizontal Calendar list in Agenda would work and / or custom maximum height of the collapsible 👍

**Comment by nived-cv** [comment]
Hi is there a way to hide the calendarlist in agenda ?
