### ISSUE TITLE
WeekCalendar!  How to scroll to future & past weeks with a button press

### ISSUE THREAD

**Issue by fractalscape13** [wix/react-native-calendars#1769]
With the 'WeekCalendar' component you can swipe to future and past weeks.  How can I make custom arrow buttons programmatically scroll to future and past weeks when pressed?  The monthly view calendar has these buttons built in, but I can't figure out how to do it with 'WeekCalendar'.  

I have 'WeekCalendar' wrapped in 'CalendarProvider' and have been experimenting with all the props and haven't found a solution yet.

**Comment by riyas145** [comment]
I think there is no option pls update if u found anything

**Comment by Inbal-Tish** [comment]
@fractalscape13 Hi. Try using the `ExpandableCalendar` component with 'initialPosition' = closed (default), 'disablePan' = true, 'hideKnob' = true. Let me know if that works for you.

**Comment by fractalscape13** [comment]
@Inbal-Tish thank you for the response!!! i will try in the next few days and let you know how it goes

**Comment by Inbal-Tish** [comment]
@fractalscape13 initialPosition={closed} will keep it closed and the disablePan will prevent from opening it

**Comment by fractalscape13** [comment]
@Inbal-Tish i still don't understand.  i am using the ExpandableCalendar with the three props you mentioned and I am seeing a full month view.  The props don't seem to make any visual difference.  I don't understand what they're supposed to do and I don't see an example of the ExpandableCalendar showing a weekly view anywhere.  Please help.
