### ISSUE TITLE
Agenda loader icon and background

### ISSUE THREAD

**Issue by AliMonam** [wix/react-native-calendars#1775]
Is there any way to modify color of the loader area and change the loader icon in the Agenda? I am using the dark mode theme and that is not compatible with my design.
![agenda](https://user-images.githubusercontent.com/19654690/152220518-902225f0-0271-4c6b-a342-fe0c86b499d5.jpg)

**Comment by goxr3plus** [comment]
Did you solve? I see you just closed...
