### ISSUE TITLE
Getting error on fast scroll to past months. undefined is not an object (evaluating 'val.getTime')

### ISSUE THREAD

**Issue by gurmundi7** [wix/react-native-calendars#178]
I'm getting this error: undefined is not an object (evaluating 'val.getTime'), when I scroll fast to end point to past months. This works fine if scroll slowly. Its happening only for android devices but on both simulator and device. Here is my code and error screenshot:

`
            
            <CalendarList 

            onVisibleMonthsChange={(months) => {console.log('now these months are visible', months);}}
        
            pastScrollRange={1}
            
            futureScrollRange={0}
            
            scrollEnabled={true}

            markingType={'interactive'}

            markedDates={this.markedDates()}

            current={new Date()} // also tried putting static date '2017-09-18'

            minDate={'2017-01-01'}

            maxDate={new Date()} // also tried putting static date '2017-09-18'

            firstDay={0}
            
            onDayPress={(day) => {
                    alert(day.dateString)
                }
            }}
          />`

and screenshot is:

![screenshot_1505733686](https://user-images.githubusercontent.com/3081327/30539768-a0c93670-9c91-11e7-9edd-3ec2e5d2b1aa.png)

**Comment by nico2che** [comment]
I got the same error with `futureScrollRange={0}`, `futureScrollRange` cannot be 0
I think the 
```
<FlatList
        initialListSize={this.pastScrollRange * this.futureScrollRange + 1}
        [...]
/>
```
in [CalendarList/index.js](https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.js#L160) require `pastScrollRange` and `futureScrollRange` != 0

**Comment by tautvilas** [comment]
Thanks for report, this should be sovlved in 1.14.1
