### ISSUE TITLE
feature: instead of dots have a render method?

### ISSUE THREAD

**Issue by Crare** [wix/react-native-calendars#1784]
## Description
Hi, I would like to use different shapes in the calendar. Specifically custom icons etc. So a render-method for rendering the dot would be useful. Not sure if this is already possible. I can't really see it is.

The problem is that the dots can get too similar color and they are hard to identify when the dots are so small.

render-method for rendering the dot-item would be awesome.

If there is already a way. Could I get an example how it could be done?

**Comment by Crare** [comment]
ok I found a way.
using the dayComponent-method: https://github.com/wix/react-native-calendars#overriding-day-component

using  the marking-prop, I can get existing data of dots etc.
```
dayComponent={({date, state, marking}) => {
    return (
      <View>
        <Text style={{textAlign: 'center', color: state === 'disabled' ? 'gray' : 'black'}}>{date.day}</Text>
      </View>
    );
  }}
```

**Comment by algate** [comment]
@Crare :
How to resolve the selected date state
