### ISSUE TITLE
Exclude specific day on ExpandableCalendar week calendar?

### ISSUE THREAD

**Issue by xbaldiq** [wix/react-native-calendars#1785]
## Description

Can we hide showing saturday and sunday on ExpandableCalendar? i want only showing Monday to Friday only

![Screen Shot 2022-02-09 at 10 09 24](https://user-images.githubusercontent.com/20633818/153114651-1ade587c-bd98-4ece-a661-7db054f3e918.png)

**Comment by OPEN-9** [comment]
brother, Is there a solution
