### ISSUE TITLE
Calendar not showing dates before December 2017.

### ISSUE THREAD

**Issue by srjkmrpro** [wix/react-native-calendars#1786]
Hello there i am facing an issue while using this library to get the dates before december 2017.

It's look like there is a limit there but i want to implement my custom limits for the end and start date too.
![WhatsApp Image 2022-02-09 at 11 34 11 AM](https://user-images.githubusercontent.com/67652445/153131732-967df5bf-2c09-4380-a8c0-76d9a5d8464b.jpeg)

**Comment by sylfel** [comment]
it's not a bug
it's a feature 
https://github.com/wix/react-native-calendars/blob/e070a0a71adbd0d85a13c9989d01a4adf5ca6304/src/calendar-list/index.tsx#L25 

https://wix.github.io/react-native-calendars/docs/CalendarList#pastscrollrange

**Comment by srjkmrpro** [comment]
@sylfel  Thanks for the help.

**Comment by worldlee78** [comment]
Is there a way to go past that date? When I change the default, the CalendarList doesn't seem to like it very much.

**Comment by Inbal-Tish** [comment]
@worldlee78 `pastScrollRange` and `futureScrollRange` are set to 50 by default. You can pass them a larger number if you need
