### ISSUE TITLE
Cant scroll CalendarList inside BottomSheet in Android 

### ISSUE THREAD

**Issue by statnyk** [wix/react-native-calendars#1788]
## Description

Hi, i am using CalendarList inside the BottomSheetModal, in iOS works well but in android i can't scroll 

```javascript
"@gorhom/bottom-sheet": "4.1.5",
"react-native-calendars": "^1.1277.0",
```

## Expected Behavior

Hi, i am using CalendarList inside the BottomSheetModal, in iOS works well but in android i can't scroll because react-native-calendars using flatList from 'react-native', i changed import of the FlatList from 'react-native to 'react-native-gesture-handler' and it works well. How can i fix that without changing code in node modules?

## Environment

Emulator Pixel XL 4/ Android

**Comment by zagoorland** [comment]
i have the same problem currently!

**Comment by zorinpavel** [comment]
Did you solve the problem?

**Comment by erickcrus** [comment]
Same here!

**Comment by bangerang** [comment]
Same

**Comment by mvolonnino** [comment]
> This solution works for me:
> 
> ```
> import { CalendarList } from 'react-native-calendars';
> import { FlatList } from 'react-native-gesture-handler';
> (...)
> <CalendarList style={styles.calendarList}
>             calendarWidth={width - 30}
>             calendarHeight={350}
>             onDayPress={onDaySelect}
>             scrollEnabled={true}
>             markedDates={markedDates}
>             customComponent={FlatList} />             // add FlatList from react-native-gesture-handler
> (...)
> ```

How do this work for you? `customComponent` is not a prop that `CalendarList` accepts?

**Comment by erickcrus** [comment]
> > This solution works for me:
> > ```
> > import { CalendarList } from 'react-native-calendars';
> > import { FlatList } from 'react-native-gesture-handler';
> > (...)
> > <CalendarList style={styles.calendarList}
> >             calendarWidth={width - 30}
> >             calendarHeight={350}
> >             onDayPress={onDaySelect}
> >             scrollEnabled={true}
> >             markedDates={markedDates}
> >             customComponent={FlatList} />             // add FlatList from react-native-gesture-handler
> > (...)
> > ```
> 
> @erickcrus - How do this work for you? `customComponent` is not a prop that `CalendarList` accepts?

1 - I added the property `customComponent` to interface at `node_modules/react-native-calendars/src/calendar-list/index.d.ts`; 
2 - Then, in file `node_modules/react-native-calendars/src/calendar-list/index.js` at line 45, I added `customComponent` after `onEndReached` prop;
3 -  Finally, in same file `node_modules/react-native-calendars/src/calendar-list/index.js` at line 186 i added `const ListComponent = customComponent ?? FlatList;`, and replace `FlatList` component by `ListComponent` const.

I'll commit these changes and update the response once I'm done.

**Comment by Shervanator** [comment]
Yeah can confirm this is still an issue when using CalendarList inside a component that takes advantage of `react-native-gesture-handler` e.g. BottomSheet.

@erickcrus's fix also works!

**Comment by rameev17** [comment]
i solved the problem like this just Render the CalendarList component inside BottomSheetFlastList

**Comment by rameev17** [comment]
<BottomSheetFlatList
      data={[0]}
      renderItem={() => (
        <CalendarList
          customHeader={(date) => (
            <CustomHeader
              month={date.month.toString('MMMM')}
              year={date.month.getFullYear()}
            />
          )}
          pastScrollRange={0}
          futureScrollRange={3}
          scrollEnabled={true}
          showScrollIndicator={false}
          markingType={'custom'}
          dayComponent={(date, item, marking) =>
            CustomDayComponent(date, item, marking)
          }
          markedDates={tempDates.markedDates}
          firstDay={1}
          calendarStyle={styles.container}
          dayTextFontSize={moderateScale(50)}
          minDate={
            new Date(new Date().setDate(new Date().getDate() + 1))
              .toISOString()
              .split('T')[0]
          }
          maxDate={new Date(tempDates.maxDate).toISOString().split('T')[0]}
          disableAllTouchEventsForDisabledDays={true}
          hideDayNames={true}
          theme={{
            textDayFontSize: moderateScale(15),
            textMonthFontSize: moderateScale(14),
            textDayFontFamily: FONTS.Inter_600SemiBold,
            textMonthFontFamily: FONTS.Inter_600SemiBold,
            dayTextColor: 'black',
            todayTextColor: '#d9e1e8',
            textDisabledColor: '#d9e1e8'
          }}
        />
      )}
    />

> i solved the problem like this just Render the CalendarList component inside BottomSheetFlastList

**Comment by MarceloPrado** [comment]
You might want to try https://github.com/marceloPrado/flash-calendar - it has first party support for bottom sheet: https://marceloprado.github.io/flash-calendar/fundamentals/usage#bottom-sheet

**Comment by bouakram** [comment]
dose any one find a solution my package version are: 
"@gorhom/bottom-sheet": "^4.6.0",
"react-native-calendars": "^1.1305.0",

please any one can help !!.

i think that FlatList is not supported inside gorhom/bottom-sheet in android devices it should replaced by BottomSheetFlatList but i have no idea on how to solve it and i cant use @erickcrus solution bcs the version is changed the code is not the same !

**Comment by zdinidz** [comment]
I solving by add props to bottomsheet

`        
<BottomSheet
enableContentPanningGesture={false}
>...
</BottomSheet>
`
