### ISSUE TITLE
When I select the date the background circle is not appearing for the selected date.

### ISSUE THREAD

**Issue by edwardconcertcare** [wix/react-native-calendars#179]
## Description

I integrated the react-native-calendars in our react native project and I ran the project to 10.3 simulator . The calendar did loaded properly.  But, When I select the date the background circle is not appearing.  But, the selected date is printed in the log. I want to set the selected date to the calendar manually to. I have a button in our app called "Yesterday". When I hit that I want to set the yesterday's selected in the calendar. 

I have implemented the calendar like this.

            <Calendar
                        style={{marginTop: 20, backgroundColor: 'white'}}
                        selected={['2017-09-20','2017-09-21',]}
                        theme={{
                                calendarBackground: '#333248',
                                textSectionTitleColor: '#D0D7DF',
                                dayTextColor: '#546572',
                                todayTextColor: '#543BEA',
                                monthTextColor: '#6C7A86',
                                arrowColor: '#543BEA',
                                selectedDayBackgroundColor: 'red',
                                selectedDayTextColor: 'green',
                            }}
                        onDayPress={(day) => {
                            console.log('previous selected day : ', this.state.selectedDate)
                            console.log('selected day', day);
                            this.setState({
                                selectedDate: day
                            })
                            
                        }}
                        />
## Expected Behavior

When I select a date in the calendar. That should be selected with the background circle. That should appear.  I want to set the selected date manually as props to the calendar when I hit the button in the app.

## Observed Behavior

The background circle is not appearing here on the selected date. But, the selected date log is printing properly.

## Environment

Please run these commands in the project folder and fill in their results:

Versions: 
react-native-calendars@1.6.2
react-native@0.44.0

Also specify:
1. Xcode 8.3.2
2. Simulator 10.3

![screen shot 2017-09-19 at 12 27 04 pm](https://user-images.githubusercontent.com/17903326/30579388-254180fc-9d36-11e7-83e9-51a3e25a6a9b.png)

**Comment by tautvilas** [comment]
hi, please use markedDates property, selected property has been depreciated

**Comment by kalraneeraj24550** [comment]
@tautvilas  sir, my selected date is appreaing sqaure not circle , how to resolve this .

getPeriod(startTimestamp, endTimestamp) {
        const period = {}
        let currentTimestamp = startTimestamp
        while (currentTimestamp < endTimestamp) {
            const dateString = this.getDateString(currentTimestamp)
            period[dateString] = {
                color: '#0071f8',
                startingDay: currentTimestamp === startTimestamp,
            }
            currentTimestamp += 24 * 60 * 60 * 1000
        }
        const dateString = this.getDateString(endTimestamp)
        period[dateString] = {
            color: '#0071f8',
            textColor: 'white',
            endingDay: true,
            marked: true
        }
        return period
    }



    setDay(dayObj) {

        const _selectedDay = moment(dayObj.dateString).format(_format);
        console.log(dayObj.dateString)

        count++

            if (count === 1) {
                this.setState({
                    firstDay: dayObj.day,
                    firstMonth: dayObj.month,
                    firstYear: dayObj.year
                })
            }

            else if (count === 2) {
                this.setState({
                    secondday: dayObj.day,
                    secondMonth: dayObj.month,
                    secondYear: dayObj.year
                })
                count = 0
            }
        this.setState({
            todayDate: dayObj.dateString
        })
        const { start, end } = this.state
        const {
            dateString, day, month, year,
        } = dayObj
        let selected = true;
        const timestamp = new Date(year, month - 1, day).getTime()
        const newDayObj = { ...dayObj, timestamp }
        const startIsEmpty = _isEmpty(start)

        if (startIsEmpty || !startIsEmpty && !_isEmpty(end)) {
            const period = {
                [dateString]: {
                    color: '#0071f8',
                    endingDay: true,
                    startingDay: true,
                    marked: true
                    
                },

            }
            this.setState({ start: newDayObj, period, end: {} })
        } else {
            // if end date is older than start date switch
            const { timestamp: savedTimestamp } = start
            if (savedTimestamp > timestamp) {
                const period = this.getPeriod(timestamp, savedTimestamp)
                this.setState({ start: newDayObj, end: start, period })
            } else {
                const period = this.getPeriod(savedTimestamp, timestamp)
                this.setState({ end: newDayObj, start, period })
            }
        }
    }


 <Calendar
                        onDayPress={this.setDay.bind(this)}
                        markingType='period'
                        markedDates={period}
                        minDate={this.state.todayDate}
                        theme={{
                            calendarBackground: white,
                            textSectionTitleColor: '#D0D7DF',
                            dayTextColor: '#546572',
                            todayTextColor: '#543BEA',
                            monthTextColor: '#6C7A86',
                            arrowColor: '#543BEA',
                            selectedDayBackgroundColor: 'red',
                            selectedDayTextColor: 'green',

                        }}

              
                    />
