### ISSUE TITLE
`Agenda` list Items incorrectly rendering on update

### ISSUE THREAD

**Issue by JacobJaffe** [wix/react-native-calendars#1791]
Hello -- I think I found a bug in the `AgendaList` due to the current key extraction.

When I navigate back in the agenda, e.g. from a Monday to Sunday, and if both of those days have arrays of events, the FlatList isn't rendering the correct item. Instead, an item previously rendered gets used. I'm pretty sure this is because of the string coercion  of the indices used in the current key extraction: 

https://github.com/wix/react-native-calendars/blob/74bc7fe05ed3883d3d8cbd56e3cd5a565543c385/src/agenda/reservation-list/index.tsx#L261:
```tsx
  keyExtractor = (_item: DayAgenda, index: number) => String(index);
 ```
 
 this seems to me like a pretty good example of the index-key anti pattern described here:
 https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318
 
 This seems straightforward to fix, by at least exposing a `keyExtractor` prop to the `AgendaList`.
 
 I'll put together a minimal reproduction of this when I get the time.

**Comment by eladgel** [comment]
Easiest way to reproduce is to load the agenda example and add 
                **showOnlySelectedDayItems={true}** 
![simulator_screenshot_5889124F-7497-4F95-A40D-075BA774E0B9](https://user-images.githubusercontent.com/412137/154015683-dc1a5bec-0f58-45c6-b91c-1f8fe3e8a228.png)


![simulator_screenshot_EA40B60B-A98F-4FF0-924D-B0FEFE694DE0](https://user-images.githubusercontent.com/412137/154015551-89a9ca87-ee1f-4891-a3b8-8db88d0a40e0.png)
tent.com/412137/154015529-6b320f7f-d6de-4ba2-a8b5-86beab226083.png)

**Comment by eladgel** [comment]
@Inbal-Tish

**Comment by eladgel** [comment]
@JacobJaffe I've added this pr in the meantime:
https://github.com/wix/react-native-calendars/pull/1792

**Comment by JacobJaffe** [comment]
Hi @eladgel ! Thank you for the reproduction. I've opened a new PR that addresses this + other issues with the `Agenda` not accepting generic items at: #1794.

**Comment by Inbal-Tish** [comment]
@eladgel @JacobJaffe Hi guys. Thank you for opening the issue and PRs - much appreciated! I added a fix to move things faster. You can follow this #1795

**Comment by DonovanVA** [comment]
^Hi there I have found a potential solution to this issue: can check #1890

**Comment by zeentan22** [comment]
Hi, may I ask how u managed to only show the items for that particular day that was pressed. Currently, items from other days appear in my app which is not what I desire. I would appreciate greatly if you are able to help me. Thanks!

**Comment by DonovanVA** [comment]
Dear Zeen,
        Regarding your issue above, check
.../agenda/reservation-list/index.js, in that file, search for the line of
code where ...
} else {
for (let i = 0; i < 31; i++) {
const res = this.getReservationsForDay(iterator, props);

if (res) {
reservations = reservations.concat(res);
}
iterator.addDays(1);
}
}
change it to
} else {
const res = this.getReservationsForDay(iterator, props);
if (res) {
reservations = res;
}
iterator.addDays(1);
}

This will render the reservations not in a list of 31 days, but just the
item itself on that day. Hope this helps!
Sincerely,
      Donovan Ng

**Comment by minaairsupport** [comment]
I am still facing the same issue, anyone could find a walk around to it

**Comment by zeentan22** [comment]
Hi minaairsupport,

DonovanVA solution is correct and helps me solve the issue.

Just change the last code snippet to this and it should work.

`if (sameDate(newSelectedDate, prevState.selectedDay)) {
            this.setState({ reservations: [] }, () => this.updateReservations(this.props));
}`

**Comment by minaairsupport** [comment]
Thanks, @zeentan22 I wish they could release this fix instead of making a walk around 
@Inbal-Tish  if you don't mind could you merge this fix so we could have it in next release

**Comment by Inbal-Tish** [comment]
@minaairsupport Hi. I'm not sure I understand what fix we are talking about. If you need a custom `keyExtractor` pass it to the `reservationsKeyExtractor` prop. This will return the item and the index as a parameter, much like the `keyExtractor` prop: 
```
reservationsKeyExtractor={(item, index) => {
          return `${item?.reservation?.day}${index}`;
        }}
```

**Comment by minaairsupport** [comment]
Hi @Inbal-Tish expose reservationsKeyExtractor is a walk-around to fixing the incorrect view for the list. 
I wish this fixed by the library itself by doing the right checks.

like this one 

`if (sameDate(newSelectedDate, prevState.selectedDay)) { this.setState({ reservations: [] }, () => this.updateReservations(this.props)); } `

**Comment by Inbal-Tish** [comment]
@minaairsupport Hi. Care to submit a PR on this?

**Comment by Delocy** [comment]
Guys i have this issue but im using agenda instead of flat list, how can i fix it?

**Comment by kyle-helping-hand** [comment]
> I think I figure it out we need to override `reservationsKeyExtractor` to get the right id from the data
> 
> ```
>  <Agenda
>         items={selectedDates}
>         renderItem={renderItem}
>         showOnlySelectedDayItems={true}
>   reservationsKeyExtractor={(item) => {
>           console.log('item', item);
>           return item?.reservation?.id; ---> replace with proper id name 
>         }}
>         
>         />
> ```

This worked for me!

**Comment by gkasireddy202** [comment]
> if (sameDate(newSelectedDate, prevState.selectedDay)) { this.setState({ reservations: [] }, () => this.updateReservations(this.props)); }

Please where i add above lines of code?
