### ISSUE TITLE
WeekCalendar can't override flatlist scroll props i.e. can't lock to one week

### ISSUE THREAD

**Issue by ejkkan** [wix/react-native-calendars#1796]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Today you cant pass scroll enabling/disabling props to weekcalendar
Disabled scoll for Weekcalendar. Effectily lock it into one week.

## Expected Behavior

pass a parameter to override "scrollEnabled" for FlatList for example

## Observed Behavior

Not plausbile to do

## Environment

all

Also specify:

1. Android & IOS

## Reproducible Demo

Any project

**Comment by Inbal-Tish** [comment]
@ejkkan Hi. Which version of Calendars are you using?

**Comment by jantilk** [comment]
Doesn't work for me also, version 1.1286.0

This is still scrollable horizontally:
`<WeekCalendar scrollEnabled={false} />`

**Comment by Inbal-Tish** [comment]
Try passing in `scrollViewProps` prop. Like `scrollViewProps={{scrollEnabled: false}}`
