### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by felixus95** [wix/react-native-calendars#18]
Please review your readme. There are a ton of typos and missing brackets.
Your product is really appreciated though ;)

**Comment by tautvilas** [comment]
Thx, I would really appreciate if you could submit a pull request with the issues you found :)

**Comment by bmoreira10** [comment]
https://github.com/wix/react-native-calendars/compare/master...bmoreira10:patch-1 I fixed some

**Comment by tautvilas** [comment]
@bmoreira10 thanks!
