### ISSUE TITLE
dateutils.js and interface.js throwing constant errors

### ISSUE THREAD

**Issue by CrypticMindz** [wix/react-native-calendars#1802]
When importing and using Agenda, "d.toString" is undefined (undefined is not an object)(in Interface.js)
When importing and using CalendarList "days[0].clone" is undefined (undefined is not an object)(in dateutils.js)

I freshly installed react-native-calendars (yarn add react-native-calendars). It will throw those named error right away. I tried installing earlier versions with no success.

I simply imported: import {Agenda} from "react-native-calendars";
and used "Agenda". 
Same with CalendarList:
import {CalendarList} from "react-native-calendars";

```
TypeError: undefined is not an object (evaluating 'd.toString')
```

Packages:
```
"@react-native-firebase/app": "^14.5.0",
    "@react-native-firebase/auth": "^14.5.0",
    "@react-native-firebase/firestore": "^14.5.0",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/material-bottom-tabs": "^6.1.1",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "react": "17.0.2",
    "react-native": "0.67.2",
    "react-native-calendars": "^1.1278.0",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-pager-view": "^5.4.11",
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.11.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "yarn": "^1.22.17"
```

**Comment by hbendel** [comment]
I have the same problem too
TypeError: undefined is not an object (evaluating 'd.toString')

**Comment by CrypticMindz** [comment]
It is actually solved by setting "selected" to a date. It seems, that it is not optional.

**Comment by juanmarques** [comment]
I'm getting the same with ExpandableCalendar

**Comment by 1ErikaMarques** [comment]
I'm getting the same with ExpandableCalendar, but the selected is not available for it

**Comment by CrypticMindz** [comment]
> I'm getting the same with ExpandableCalendar, but the selected is not available for it

I have never worked with ExpandableCalendar, but trying it out, it seems that Expandable Calendar needs to be wrapped by "CalendarProvider". That worked for me.

**Comment by shamilovtim** [comment]
@Inbal-Tish same problem. I believe there were some very breaking changes in the past handful of releases. I am unable to use the more recent versions of the Agenda, it's broken.

**Comment by Inbal-Tish** [comment]
@CrypticMindz  @shamilovtim Thank you for reporting this bug. This PR should fix the issue: https://github.com/wix/react-native-calendars/pull/1818. We will release the fix as soon as possible. Sorry for the inconvenience.

**Comment by mein-beer-hu** [comment]
Hi @Inbal-Tish I see the fix is now merged. Any updates on when we can expect newer version to be released?

**Comment by Inbal-Tish** [comment]
@mein-beer-hu We are releasing a new version every two weeks.

**Comment by shamilovtim** [comment]
Hey @Inbal-Tish unfortunately it looks like there are still breaking changes and crashes. `1.1277.0` works fine, but I get the following error on `1.1278.0` or later:
<img width="404" alt="Screen Shot 2022-03-12 at 6 13 30 PM" src="https://user-images.githubusercontent.com/3495974/158038338-8445345f-553d-4e9f-a3ae-a8ec814ed6a5.png">

**Comment by Inbal-Tish** [comment]
@shamilovtim Hi. Can you check version '1.1280.0' and tell me if your issue persists, please?
