### ISSUE TITLE
The calendar is not aligned in iPhone 12 and iPhone 13

### ISSUE THREAD

**Issue by DLachaiseKZ** [wix/react-native-calendars#1804]
## Description
Hello!
We used that library about a year ago in our app.
In recent time we have received complaints about the calendar view.
We don't know why, in iPhone 12 and 13, the calendar is not aligned and the user sees part of the following month.
_(See the video in observed behavior)_
We hope you can help us.
Thanks

## Expected Behavior

https://user-images.githubusercontent.com/74252142/155398889-4e01930d-3712-4559-95ae-e75301ee6ef5.mov

## Observed Behavior

https://user-images.githubusercontent.com/74252142/155398958-eaeda1b3-13c1-44eb-bf02-30ea0f86274e.mov

## Environment

 **react-native-calendars@1.1278.0**
 **react-native@0.63.4** 

## Device/emulator/simulator & OS version:

In _Expected behavior_ : iPhone 11 Pro/ iOS 14.5 
In _Observed behavior_ : iPhone 12 Pro/ iOS 14.5 

We tested it in others devices too:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/74252142/155404897-c20d490c-1a72-480a-943c-2ac0171e0ef2.png">

**Comment by Inbal-Tish** [comment]
@DLachaiseKZ Hi. Can you please add a snippet of your code including the container's?

**Comment by Inbal-Tish** [comment]
@DLachaiseKZ Can you please add a snippet and not an image so I can copy your code to debug?

**Comment by DLachaiseKZ** [comment]
> @DLachaiseKZ Can you please add a snippet and not an image so I can copy your code to debug?

  <Modal
      title={"My Calendar"}
      animationType="fade"
      transparent={true}
      onCancel={onCancel}
      topButtonLabel={"Today"}
      buttonLabel={"SELECT"}
      haveBothButtons={true}
      onPressButton={handleDone}
      onPressTopButton={onPressTopButton}
      isVisible={isCalendarVisible}
      isFloating={true}
    >
      <View>
        {isCalendarVisible ? (
          <CalendarList
            scrollTimeout={isUndefined}
            onVisibleMonthsChange={() => {
              clearTimeout(CalendarList.scrollTimeout);
              CalendarList.scrollTimeout = setTimeout(() => 200);
            }}
            ref={calendarRef}
            hideArrows={true}
            horizontal={true}
            pagingEnabled={true}
            calendarWidth={calendarWidth}
            current={visibleMonthMoment.format("YYYY-MM-DD")}
            onDayPress={handleChange}
            maxDate={maxDate ? moment(maxDate).format("YYYY-MM-DD") : null}
            minDate={minDate ? moment(minDate).format("YYYY-MM-DD") : null}
            markedDates={{
              [selectedMoment.format("YYYY-MM-DD")]: {
                selected: true,
                selectedColor: CALL_TO_ACTION,
              },
            }}
            theme={{
              todayTextColor: CALL_TO_ACTION,
              arrowColor: "#000000",
            }}
            todayColor
          ></CalendarList>
        ) : null}
      </View>
    </Modal>

**Comment by Inbal-Tish** [comment]
@DLachaiseKZ Hi. Did you check your `calendarWidth` prop? Try remove it or change its value

**Comment by chococrypto** [comment]
i have the same issue, How do you fix it ?
