### ISSUE TITLE
TimelineList Event Bug

### ISSUE THREAD

**Issue by imdkbj** [wix/react-native-calendars#1813]
## Description
Issue with TimelineList events

## Expected Behavior
TimeLine should show the events are per JSON data but its is only considering the time from the json where as date is considering  today only.
No effect of passing date in the timelineProps

## Observed Behavior
Timeline not populating data of json for respective date

What actually happened when you performed the above actions?
Nothing populated

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:react-native-calendars@1.1278.0 
* `npm ls react-native`:react-native@0.66.0

Also specify:

1. Device/emulator/simulator & OS version: General Issue

Also: When date is passed, Timeline should not be scrollable horizontally.

event data

```js
const EVENTS = [
    {
        id: 1,
        start: `2022-03-31 13:20:00`,
        end: `2022-03-31 15:00:00`,
        title: 'Merge Request to React Native Calendars',
        summary: 'Merge Timeline Calendar to React Native Calendars'
    },
    {
        id: 2,
        start: `2022-03-31 13:15:00`,
        end: `2022-03-31 14:30:00`,
        title: 'Meeting A',
        // summary: 'Summary for meeting A',
        color: '#e6add8'
    }]


<TimelineList
                    events={{ "2022-03-02": EVENTS }}
                  //  events={{ "2022-03-31": EVENTS }}//nothing will populate
                    timelineProps={{
                        format24h: false,
                        onBackgroundLongPress: createNewEvent,
                        scrollToFirst: true,
                        start: openingHour,
                        end: closingHour,
                        overlapEventsSpacing: 8,
                        // date: "2022-03-31" //no effect
                    }}
                    showNowIndicator
                    scrollToNow
                    scrollToFirst
                    initialTime={INITIAL_TIME}

**Comment by bosheski** [comment]
Are there any fixes for this?

**Comment by fukemy** [comment]
facing same issues? Why no one care about it?

**Comment by fukemy** [comment]
![Screen Shot 2022-07-18 at 10 59 11](https://user-images.githubusercontent.com/8202437/179443362-ab819ebd-a138-46a6-acd1-0f5597cfd04a.png)
i got this error when test your code

**Comment by fukemy** [comment]
when pass EVENTS to event props it's working normally, so whats happened to me?

**Comment by fukemy** [comment]
![Screen Shot 2022-07-18 at 11 14 53](https://user-images.githubusercontent.com/8202437/179444536-4e42cefb-834b-4bac-98f9-c02b45ee09e8.png)
i saw the events props accepted array, how can u passed JSON OBJECt with out cause error?
