### ISSUE TITLE
Calendar is flashing white when scrolling with month name

### ISSUE THREAD

**Issue by haveamission** [wix/react-native-calendars#1815]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Calendar is flashing white when scrolling with month name

## Expected Behavior

Calendar would keep same background color

## Observed Behavior

Calendar is flashing white when scrolling with month name

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Latest version of react-native-calendars, Expo 44

Also specify:

React Native Web

https://user-images.githubusercontent.com/10475533/156680289-edb1ecd0-f601-40b5-89a0-ec4e88fafa51.mov

**Comment by Inbal-Tish** [comment]
@haveamission Hi. Please add a code snippet.
