### ISSUE TITLE
When the marker type is "period", the same days of the selected period in another month are hidden.

### ISSUE THREAD

**Issue by spaquis** [wix/react-native-calendars#1816]
Hi

## Description

When the marker type is "period", the same days of the selected period in another month are hidden.

## Expected Behavior

The days of the other month must be displayed

## Observed Behavior

The days of the other month are hidden

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  react-native-calendars@1.1276.0
* `npm ls react-native`: react-native@0.67.2

Also specify:

1. Device/emulator/simulator & OS version: Iphone 13 Pro

## Reproducible Demo

```
<Calendar
          monthFormat={"MMMM yyyy"}
          hideExtraDays={true}
          firstDay={1}
          disableAllTouchEventsForDisabledDays={true}
          enableSwipeMonths={true}
          markingType={"period"}
          markedDates={{
            "2022-03-09": { color: "#F5823C", startingDay: true },
            "2022-03-10": { color: "#F5823C", endingDay: true },
          }}
          style={{
            borderRadius: 15,
            marginTop: 10,
          }}
          theme={{
            backgroundColor: "#0C0C0D",
            calendarBackground: "#0C0C0D",
            textSectionTitleColor: "#EEECF1",
            textSectionTitleDisabledColor: "#d9e1e8",
            selectedDayBackgroundColor: "#00adf5",
            selectedDayTextColor: "#ffffff",
            todayTextColor: colorUtil.SECONDARY,
            dayTextColor: "#7A7585",
            textDisabledColor: "#d9e1e8",
            // dotColor: "#00adf5",
            selectedDotColor: "#ffffff",
            arrowColor: colorUtil.SECONDARY,
            disabledArrowColor: "#d9e1e8",
            monthTextColor: colorUtil.WHITE,
            indicatorColor: "blue",
            // textDayFontFamily: "monospace",
            // textMonthFontFamily: "monospace",
            // textDayHeaderFontFamily: "monospace",
            textDayFontWeight: "300",
            textMonthFontWeight: "bold",
            textDayHeaderFontWeight: "300",
            textDayFontSize: 15,
            textMonthFontSize: 15,
            textDayHeaderFontSize: 15,
          }}
        />
```

## Screenshots

<img width="292" alt="image" src="https://user-images.githubusercontent.com/27917715/156934020-e4c2646b-19ee-4107-b4a3-a21f313c67dc.png">
<img width="294" alt="image" src="https://user-images.githubusercontent.com/27917715/156934028-ca934fac-10fa-4ecf-a158-30cee89cf2e7.png">

Thanks in advance

**Comment by Inbal-Tish** [comment]
@spaquis Hi. Is this issue still relevant? What version are you working with?

**Comment by spaquis** [comment]
Hi @Inbal-Tish ,
Yes it's still relevant. 
I'm using this version : `1.1276.0`

Thank for your help.

**Comment by Inbal-Tish** [comment]
@spaquis I run your code snippet and I couldn't find the issue. I'm running the latest version, can you please check on `1.1280.0`? See my video:

https://user-images.githubusercontent.com/33805983/160999336-cf8f1b02-39e5-4d01-92f3-f3eb86c920e9.mov

**Comment by spaquis** [comment]
Hi @Inbal-Tish ,
I tried with the new version, the problem seems to be solved.
Thanks for your help
