### ISSUE TITLE
How to use KeyExtractor to fix updating items bug in Agenda? 

### ISSUE THREAD

**Issue by prabir-vora** [wix/react-native-calendars#1819]
Can someone post an example of how to use the keyExtractor with Agenda? I am facing the same issue with updating the items in Agenda and incorrect items displaying. I am hoping using keyExtractor fixes it so if someone can guide me on how to use or post an example that would be very helpful.

I am trying to provide the keyExtractor as an argument into <Agenda>. The function has 2 arguments, (item and index). In my case item is only a string and not the actual item I am passing into the `items` prop. In this case, what do I do?

**Comment by jsp3536** [comment]
You should be able to use reservationsKeyExtractor but it is missing from the static propTypes on line 82.  https://github.com/wix/react-native-calendars/blob/v1.1279.0/src/agenda/reservation-list/index.tsx
