### ISSUE TITLE
customDay component is not rendered in v1.1279.0

### ISSUE THREAD

**Issue by emilioschepis** [wix/react-native-calendars#1823]
## Description

The latest version of the library (1.1279.0) introduced a bug where the `customDay` in calendars is unused.
I have identified the problem and will open a PR in a few minutes, using this issue as reference.

## Expected Behavior

Passing the `customDay` prop to a `Calendar` component renders the custom day.

## Observed Behavior

Passing the `customDay` prop to a `Calendar` component renders the default period day provided by this library.

## Environment

N/A

## Reproducible Demo

Reproducible in the example project provided by this library.

**Comment by tapz** [comment]
`dayComponent` component does not work either.

**Comment by HrideyReact** [comment]
dayComponent prop is not working

**Comment by MaxLmqr** [comment]
Same issue here, manually applying the linked commit solved it. 

The structure of the date props changed, it is now a simple string instead of the object that it used to be. Is there a way to keep the previous structure of the object ? I see in the typing that date has the following type : `(string & DateData) | undefined`.

**Comment by goxr3plus** [comment]
My gosh   this is a breaking change just found out today , good i checked before sending my app to production .

Please release a new updated with the fix ...

**Comment by davlf** [comment]
use the version 1.403.0

**Comment by goxr3plus** [comment]
@davlf  Where did you found that version i can't find on npm or anywhere let me know :)

**Comment by davlf** [comment]
Check this link [1.403.0](https://www.npmjs.com/package/react-native-calendars/v/1.403.0)

**Comment by Inbal-Tish** [comment]
@emilioschepis Thank you for reporting this bug, breaking changes should not have been introduced in a minor version and it will be fixed ASAP. Please follow this #1834 PR for the fix, I will release it in the next version.

**Comment by goxr3plus** [comment]
> > @davlf Where did you found that version i can't find on npm or anywhere let me know :)
> 
> Check this link [1.403.0](https://www.npmjs.com/package/react-native-calendars/v/1.403.0)

Use a version published 2 years ago :) lol?

**Comment by Inbal-Tish** [comment]
@goxr3plus @davlf  You can use the new version 1.1280.0

**Comment by goxr3plus** [comment]
Thanks a lot darling :)
