### ISSUE TITLE
Incompatibility between showSixWeeks and firstDay

### ISSUE THREAD

**Issue by ilaloov** [wix/react-native-calendars#1829]
## Description

`showSixWeeks` does not have effect when `firstDay` is set to 1 (week starts from Monday)

## Expected Behavior

With `showSixWeeks` set to true and `firstDay` set to 1, each month should be shown with six weeks and the week should start from Monday

## Observed Behavior

When `showSixWeeks` is set to true and `firstDay` is set to 1, some months are displayed with 6 weeks while others with 7. Using either `showSixWeeks` or `firstDay` independently works as expected. Tried with both `hideExtraDays` set to true and false and the behavior is identical

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.1279.0
* `npm ls react-native`: react-native@0.64.3

Device/emulator/simulator & OS version:

- Physical device with iOS 15.3.1
- Physical device with Android 10

## Reproducible Demo

```
import { View, StyleSheet } from 'react-native';
import { Calendar } from 'react-native-calendars';

export const ConfigureProduct = () => {
  return (
    <View>
      <Calendar firstDay={1} showSixWeeks={true} />
    </View>
  );
};

const styles = StyleSheet.create({});
```

## Screenshots

<p float="left">
<img src="https://user-images.githubusercontent.com/86879180/158253294-99716ac6-0349-45fa-b7e1-833788020163.PNG" width="200">
<img src="https://user-images.githubusercontent.com/86879180/158253366-b558ecb6-ec0f-4e9e-a593-1877beec1cce.PNG" width="200">
</p>

**Comment by fdagpigj** [comment]
This bug is still present. Please re-open. The showSixWeeks feature is effectively useless because of it.

**Comment by sasweb** [comment]
Please re-open.

**Comment by hector-del-rio** [comment]
This is still an issue!
