### ISSUE TITLE
Did this lib support date range selection?

### ISSUE THREAD

**Issue by sonnguyenit** [wix/react-native-calendars#183]
I am newer for RN, my project use this lib and i have a question:
Did this lib support date range selection like: https://github.com/stephy/CalendarPicker
and if it had, how to use?
see this gif:
https://github.com/stephy/CalendarPicker/raw/master/assets/react-native-calendar-picker-green-color-date-range.gif

Thank you.

**Comment by tautvilas** [comment]
Hi, you can implement such range selection with this component using intercative marking type. However you have to calculate the range to be marked yourself. Example: user presses on day 4 and on day 10 so you have to also set days in-between as marked.

**Comment by sonnguyenit** [comment]
thanks for your reply.
But i use `markedDates`  dynamic from state, update when use tab on calendar: 
```onDayPress(day) {
      let markedDates = this.state.markedDates;
        markedDates[day.dateString] = [{startingDay: true, color: '#1270BA'}];
        this.setState({
          markedDates: markedDates
        }
}```
but the calendar not update UI immediately, i must tab on arrow to next month and tab back to show the UI updated.

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/react-native-date-range-picker

**Comment by GunturThunder** [comment]
https://www.npmjs.com/package/react-native-calendar-picker prefer use this
