### ISSUE TITLE
Week View

### ISSUE THREAD

**Issue by Reacators** [wix/react-native-calendars#1832]
## Description

Hi all, this is a great package! I have created a week view on top of the timeline component and wanted to see if this would be helpful to anyone? I have added a boolean prop to the timeline to show either day or week view.

Suggestions are welcome on improving the week view. I am fairly new to programming and am not too clued up, so please bear with me.

The only problem I am facing is lining up the grids, I am not sure if I should change the styling of the calendar or the grids themselves, suggestions would be very helpful.

## Screenshots

![Screenshot_1647548329 2](https://user-images.githubusercontent.com/84666919/158891898-83041c90-e7cc-444c-bad1-5416fbcd0a5b.png)

**Comment by bosheski** [comment]
Could you share your code for this? I'm facing the same issue

**Comment by Reacators** [comment]
> Could you share your code for this? I'm facing the same issue

Hi Bosheski, apologies for the late reply. I will be requesting a merge by next week.

**Comment by syahirdev** [comment]
Hi, do we have any updates for this?

**Comment by kabitacode** [comment]
Helli, how do you make a timeline like that?

Thank you

**Comment by andrewjedi** [comment]
Was this ever shared?
