### ISSUE TITLE
When pressing a random day on the calendar, it shows the events for that day but after a few seconds, the agenda and the calendar go back to the present day.

### ISSUE THREAD

**Issue by danielfgmatos** [wix/react-native-calendars#1837]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I'm using Agenda and I'm trying to show event's when pressing a specific day on the calendar.

## Expected Behavior

When clicking on the day it was supposed to show daily events and keep the app there until the user press another button/functionality

## Observed Behavior

When pressing the day on the calendar, it shows what's supposed to show but after a few seconds, the agenda and the calendar go back to the present day.

Also specify:

1. Device/emulator/simulator & OS version: Android 11

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.
![untitled](https://user-images.githubusercontent.com/83652446/159916322-32646adf-55a5-4296-99a9-c0018e7e2046.gif)

**Comment by webdevmario** [comment]
I'm able to reproduce this issue on iOS. I was trying to see if [#1795](https://github.com/wix/react-native-calendars/pull/1795) was resolved and came across this.

**Comment by DiogoRio** [comment]
I'm having the exact same problem on Android. On top of that clicking a data takes an incredible amount of time (>1.5s).
I also only have data for 4 days, and as you can see, the rendered item is very basic. This is making this component completly unusable for me.
![Peek 2022-03-24 17-51](https://user-images.githubusercontent.com/38264424/159979853-7401df7d-06bf-4315-bfe3-69cecdaae8ef.gif)

**Comment by Inbal-Tish** [comment]
@webdevmario What version are you working with?

**Comment by webdevmario** [comment]
@Inbal-Tish I was on 1.1277.0 when I realized I had that key issue where some calendar entries would not update appropriately when tapping between days in the Agenda component. I updated to 1.1280.0 and then came across this issue.

**Comment by joaobsantos** [comment]
Hi guys, I'm having the same problem, any ideia whats going on? How can I help?

**Comment by Inbal-Tish** [comment]
@danielfgmatos Hi. Thank you for reporting the bug. Please follow this PR for a bug fix: #1847
