### ISSUE TITLE
The library has not supported for Appium yet.  Will it be next release or is there any roadmap?

### ISSUE THREAD

**Issue by wwjo** [wix/react-native-calendars#1838]
**## (1) Description**

When an app's date function has used this library to develop a date picker, the app has used a test automation (TA) tool, called Appium.  **However, the date values using the library can't be selected in above TA tool as other self-developed functions** and thus the library has not supported for Appium yet.  As this library seems popular and will attract more people to use if supported Appium, 
_(a) Would like to know whether it will be supported the Appium in next release? or 
(b) Is there any roadmap to support the Appium?_

**## (2) Expected Behavior**

Using a 3rd-party tool, it is expected that the date values in the calendar, such as today (9 Jan 2022), **can be selected** for their values of day (9), month and year (Jan 2022), as other self-developed codes (like **yellow rectangle around a "Done" button **).

**## (3) Observed Behavior**

In the same 3rd-party tool, it is observed that the date values in the calendar **can't be selected** as above expected (i.e. ** no rectangle around the day, month and year **).      

![image](https://user-images.githubusercontent.com/102337846/160157215-45285974-6c31-49ac-9d21-4cd090bc7ac5.png)

**## (4) Environment**

Both **Android** & **iOS** devices

_## (5) Reproducible Demo_

N/A

**_## (6) Screenshots_**

In the **Appium**, the **value in the calendar can't be selected** and **the value of the "text" attribute is empty**. 
![image](https://user-images.githubusercontent.com/102337846/160155709-2af0bba9-85d0-4419-ac9e-b1ecdb4f0b07.png)

**Comment by wwjo** [comment]
May I know whether a previous fix in the release (1.12.72.0), dated 14 Dec 2021, about "Day - fix accessibility label localization" (PR #1694). (https://github.com/wix/react-native-calendars/pull/1694), 
![image](https://user-images.githubusercontent.com/102337846/160772877-95c22907-53e5-4010-8bf4-829ceddca951.png)

can also be referred to add an accessibility label for the selected date value in the calendar to support like accessibility check or test automation?

**Comment by MummanaSubramanya** [comment]
@wwjo Any update? were you able to automate?
