### ISSUE TITLE
selected day background color and text color not changing on press

### ISSUE THREAD

**Issue by cgrady3** [wix/react-native-calendars#1840]
## Description

doing calendar with multi dot marking. selectedDayBackgroundColor and selectedDayTextColor not changing on day press 

no error messages

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1276.0
* `npm ls react-native`: react-native@0.64.3

Also specify:

1. Device/emulator/simulator & OS version:
 working on expo go

**Comment by Inbal-Tish** [comment]
@cgrady3 Hi. Please add a snippet of your code and try new version to see if fixed.

**Comment by Joseph-LouisLagrange** [comment]
I also encountered this problem, I directly used `<Calendar/>`,but it can display but cannot select the day number

**Comment by Nadeemkhan122** [comment]
hi also facing this issue.

**Comment by DejiAwoniyi** [comment]
Also facing this issue. has it been solved?

**Comment by FaysalBsata** [comment]
i have to switch libraries because of this issue

**Comment by Nziranziza** [comment]
I am also having the same issue!

**Comment by Inbal-Tish** [comment]
@cgrady3 @Joseph-LouisLagrange @Nadeemkhan122 @DejiAwoniyi  @Nziranziza  Can someone please provide a code snippet so I can have an example to work with? I need to see what you're doing to give an answer/solution.

**Comment by Inbal-Tish** [comment]
@cgrady3 If you're passing these keys in the `theme` component you should know that it's not dynamic. The `theme` prop is passed once to the stylesheet and is not updated by a state change. In your case, where you want to change the SELECTED day background and text, I'll will suggest using the `markedDates` prop. To the selected date you can pass `selectedColor` and `selectedTextColor` which will change dynamically as the selected date changes. For example: 
`
  const [selected, setSelected] = useState(INITIAL_DATE);
  const [bgColor, setBgColor] = useState('blue');
  const [textColor, setTextColor] = useState('red');

  const onDayPress = useCallback((day) => {
    setSelected(day.dateString);
    setBgColor('orange');
    setTextColor('black');
  }, []);

const markedDates = useMemo(() => {
    return {
      [selected]: {
        selected: true,
        disableTouchEvent: true,
        selectedColor: bgColor,
        selectedTextColor: textColor
      },
      ['2022-07-22']: {
        dotColor: 'red',
        marked: true
      }
    };
  }, [selected]);`

**Comment by WhiteClouds2009** [comment]
@Inbal-Tish  just simple used, and it cannot show the selected 
`<Calendar />`

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish just simple used, and it cannot show the selected `<Calendar />`

Of course not, the selected date is controlled by the user, meaning you need to mark it if you want.
