### ISSUE TITLE
AgendaList onScrollToIndexFailed error

### ISSUE THREAD

**Issue by KrisLau** [wix/react-native-calendars#1842]
## Description
Reopening #1578 with some additional info
Getting this error wherever I display the Agenda list. The call stack seems to point to the `scrollToSection` method in `AgendaList`. Doesn't seem to be causing any particular problems other than the error popping up. It seems to be occurring for me whenever I click on a date on the expandable calendar
![image](https://user-images.githubusercontent.com/46275463/125990153-fe4ff405-b68e-44a6-bf2a-c0aa1a36c74d.png)

Additional info:
It seems to be occurring for me whenever I click on a date on the expandable calendar but only when it is collapsed and the date is decently far away.
![image](https://user-images.githubusercontent.com/46275463/160631983-8fe60c9b-8509-4ced-abf1-cf47b7557ea1.png)
![image](https://user-images.githubusercontent.com/46275463/160631694-376caef3-568f-4b2f-be7f-f45c8e7314fb.png)

## Expected Behavior
Display `AgendaList` without error

## Observed Behavior
`AgendaList` error is displayed. Actual error message in this code block:
```
onScrollToIndexFailed info:  {"averageItemLength": 0, "highestMeasuredFrameIndex": 0, "index": 3}
```

## Environment
* `npm ls react-native-calendars`: 
react-native-calendars@1.1264.0
* `npm ls react-native`:
```
+-- @react-native-async-storage/async-storage@1.15.5
| `-- react-native@0.64.2 deduped
+-- @react-native-clipboard/clipboard@1.8.2
| `-- react-native@0.64.2 deduped
+-- @react-native-community/geolocation@2.0.2
| `-- react-native@0.64.2 deduped
+-- @react-native-community/masked-view@0.1.11
| `-- react-native@0.64.2 deduped
+-- @react-native-firebase/app@12.1.0
| `-- react-native@0.64.2 deduped
+-- @react-native-google-signin/google-signin@6.0.1
| `-- react-native@0.64.2 deduped
+-- @react-native-picker/picker@1.16.3
| `-- react-native@0.64.2 deduped
+-- @react-navigation/bottom-tabs@5.11.11
| +-- react-native-iphone-x-helper@1.3.1
| | `-- react-native@0.64.2 deduped
| `-- react-native@0.64.2 deduped
+-- @react-navigation/native@5.9.4
| `-- react-native@0.64.2 deduped
+-- @react-navigation/stack@5.14.5
| `-- react-native@0.64.2 deduped
+-- @storybook/addon-ondevice-actions@5.3.23
| `-- react-native@0.64.2 deduped
+-- @storybook/addon-ondevice-knobs@5.3.25
| +-- @emotion/native@10.0.27
| | `-- react-native@0.64.2 deduped
| +-- react-native-modal-datetime-picker@7.6.1
| | `-- react-native-modal@11.10.0
| |   `-- react-native@0.64.2 deduped
| `-- react-native@0.64.2 deduped
+-- @storybook/react-native@5.3.25
| `-- react-native@0.64.2 deduped
+-- react-native-autolink@4.0.0
| `-- react-native@0.64.2 deduped
+-- react-native-confirmation-code-field@7.1.0
| `-- react-native@0.64.2 deduped
+-- react-native-dev-menu@4.0.2
| `-- react-native@0.64.2 deduped
+-- react-native-draggable-flatlist@2.6.2
| `-- react-native@0.64.2 deduped
+-- react-native-elements@3.4.2
| +-- react-native-ratings@8.0.4
| | `-- react-native@0.64.2 deduped
| `-- react-native-size-matters@0.3.1
|   `-- react-native@0.64.2 deduped
+-- react-native-fbsdk-next@4.3.0
| `-- react-native@0.64.2 deduped
+-- react-native-google-places-autocomplete@2.2.0
| `-- react-native@0.64.2 deduped
+-- react-native-image-picker@4.0.4
| `-- react-native@0.64.2 deduped
+-- react-native-keyboard-aware-scroll-view@0.9.4
| `-- react-native@0.64.2 deduped
+-- react-native-linear-gradient@2.5.6
| `-- react-native@0.64.2 deduped
+-- react-native-maps@0.28.0
| `-- react-native@0.64.2 deduped
+-- react-native-pager-view@5.2.1
| `-- react-native@0.64.2 deduped
+-- react-native-reanimated@2.2.0
| `-- react-native@0.64.2 deduped
+-- react-native-safe-area-context@3.2.0
| `-- react-native@0.64.2 deduped
+-- react-native-screens@3.4.0
| `-- react-native@0.64.2 deduped
+-- react-native-tab-view@3.0.1
| `-- react-native@0.64.2 deduped
+-- react-native-url-preview@1.1.9
| `-- react-native@0.64.2 deduped
+-- react-native-webview@11.6.5
| `-- react-native@0.64.2 deduped
`-- react-native@0.64.2
  `-- @react-native-community/cli@5.0.1
    `-- react-native@0.64.2 deduped
```

Also specify:

1. Emulator & OS version:
- Pixel 3a API 30 (Android 11.0)

## Reproducible Demo
I can't seem to repro it in a snack but here's the one I created which basically has the same code: 
https://snack.expo.dev/Mc43D8SeT

## Screenshots
![image](https://user-images.githubusercontent.com/46275463/125991959-af2221de-cd8d-45f2-abe9-e078ff843f88.png)
![image](https://user-images.githubusercontent.com/46275463/125990153-fe4ff405-b68e-44a6-bf2a-c0aa1a36c74d.png)
Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by RaphaelSparK** [comment]
I have the same problem. Any sugestion?

**Comment by KrisLau** [comment]
> I have the same problem. Any sugestion?

No idea I'm guessing I need to do something with `onDateChanged` but I have no idea what because I already have all the events loaded in so I'm not sure.

**Comment by Chatharaju** [comment]
Having same issue. Any solutions yet?

**Comment by KrisLau** [comment]
@Chatharaju Nope no idea

**Comment by KrisLau** [comment]
@Chatharaju https://github.com/wix/react-native-calendars/issues/1862#issuecomment-1150711027

**Comment by KrisLau** [comment]
@Chatharaju @RaphaelSparK https://github.com/wix/react-native-calendars/issues/1862#issuecomment-1150711027

**Comment by jack114jack** [comment]
I used the `windowSize` prop to resolve this issue
```jsx
<AgendaList
  sections={items}
  renderItem={renderItem}
  sectionStyle={styles.stickyDate}
  windowSize={100}
/>
```

**Comment by Bengejd** [comment]
I think this can be fixed (along with a myriad of AgendaList performance issues) by opting into the beta-infinite scroll list for Agenda List instead. 

All you have to do is do add the following to your `AgendaList` props:

```
        infiniteListProps={{
          itemHeight: 61.0, // The height of the agendaItem without padding. Defaults to 80 I believe
          titleHeight: 36, // The height of the section (date) title without padding.
          visibleIndicesChangedDebounce: 250,
        }}
```
You might have to play around with your values for the itemHeight & titleHeight to get them to render properly, but every problem that I've had with the AgendaList originally, has been solved by moving to use the infinite scroll version. I don't know why it isn't used by default, because it works 10x better, with 10x less bugs.

**Comment by mversteeg3** [comment]
@Bengejd's solution worked for me, but caused a "pull to refresh" to stop working for me.  I found that you can wrap the AgendaList in a ScrollView with a Refresh Control to alleviate. 

`
<ScrollView
        refreshControl={
          <RefreshControl
            refreshing={isFetching || isLoading}
            onRefresh={refetch}
          />
        }
      >
<AgendaList 
... />
`

Thanks for the solution, made my day!

**Comment by KrisLau** [comment]
@Bengejd Extremely late but this worked for me! The only problem I seem to be running into is a `No layout available for index: 3` when i delete a bunch of events from my db. The data I'm passing to the list is an observable (watermelonDB / rxjs).
