### ISSUE TITLE
Missing handler to onTodayPress from CalendarProvider

### ISSUE THREAD

**Issue by msolanogithub** [wix/react-native-calendars#1844]
## Description
Is there one way to handle and/or know when today button was press, from CalendarProvider `showTodayButton` prop?.
I don't found documentation about this

**Comment by Inbal-Tish** [comment]
@msolanogithub Hi. At the moment there is no callback for the Today button's press, but I will add one in the upcoming weeks. Thanks for reporting!

**Comment by Inbal-Tish** [comment]
@msolanogithub Hi. You can use 'onDateChange' callback and check the 'updateSource' param. Example:
`onDateChanged = (date, updateSource) => {
    if (updateSource === 'todayPress') {...}
  };`
