### ISSUE TITLE
Doubt Agenda - shows with the calendar open

### ISSUE THREAD

**Issue by rhyannc** [wix/react-native-calendars#1863]
## Description

Is there any way to open the first screen with the (schedule) it already shows with the calendar open to select the day, instead of having to drag Knob?

**Comment by EnginYilmaz** [comment]
I am not sure what you mean but. "selected"  property sets the first day of the selected date in agend. For example;
<Agenda
selected={this.state.yourselectedday}
...

**Comment by aaronbesson** [comment]
i think he's asking how to make the calendar open on the agenda by default.
