### ISSUE TITLE
Theme Type need  more typing for Advanced Styling 

### ISSUE THREAD

**Issue by peanut-lover** [wix/react-native-calendars#1864]
## Description

> Object literal may only specify known properties, and ''stylesheet.calendar-list.main'' does not exist in type 'Theme'

when i create `Theme` type data for [Advanced styling](https://github.com/wix/react-native-calendars#advanced-styling),  meet the above type error. 

maybe need to add `stylesheet.calendar.header` in `Theme` typescript.

need to like this typing in [here](https://github.com/wix/react-native-calendars/blob/master/src/types.ts#L89-L92)

```javascript
export interface Theme {
    ...
    'stylesheet.calendar-list.main'?: {
        calendar: StyleProp<ViewStyle>;
    };
}
```

as well as other styles(`stylesheet.calendar.main`, `stylesheet.calendar.header`)

alternatively, my solution is like this

```javascript
// https://github.com/wix/react-native-calendars#advanced-styling
const calendarTheme: Theme | Record<string, unknown> = {
    [STYLE_CALENDAR_LIST_MAIN_ID]: {
        calendar: {
            paddingLeft: 0,
            paddingRight: 0,
        },
    },
   ....
};
```

**Comment by katshaze** [comment]
This is also an issue for me. Is there any progress on this?

**Comment by jeremyking248** [comment]
The issue is still present. Have to disable typescript to use advanced styles.

And if the advanced styles were typed, my IDE could list the available styling options! Instead, I must look manually through various `style.ts` files in the source code.

**Comment by Denys-Oleksiienko** [comment]
The problem is still there. I temporarily fixed it like this:

```
import { Calendar } from 'react-native-calendars';
import { Theme } from 'react-native-calendars/src/types';

type ExtendedTheme = Theme & {
  'stylesheet.calendar.header': {
    dayHeader: {
      marginTop: number;
      marginBottom: number;
      textAlign: string;
      fontSize: number;
      fontWeight: string;
      color: string;
    };
  };
};

<Calendar
  {...props}
  enableSwipeMonths
  firstDay={1}
  theme={
    {
      selectedDayBackgroundColor: theme.colors.blue[400],
      selectedDayTextColor: theme.colors.white[400],
      textMonthFontWeight: 'bold',
      textDayFontSize: 16,
      'stylesheet.calendar.header': {
        dayHeader: {
          marginTop: 2,
          marginBottom: 6,
          textAlign: 'center',
          fontSize: 16,
          color: theme.colors.grey['100'],
        },
      },
    } as ExtendedTheme
  }
/>
```
