### ISSUE TITLE
Timeline Resource View

### ISSUE THREAD

**Issue by alvaro-lw** [wix/react-native-calendars#1868]
Hi, is there a possible way to achieve a resource view for the Timeline component ? 

Something similar to this this: 

<img width="1119" alt="resource_view" src="https://user-images.githubusercontent.com/100701768/163516407-ee93bd6e-3ad1-4e6e-9ae3-5ca62cf2dcad.png">

**Comment by fukemy** [comment]
hi did u found any solution?
