### ISSUE TITLE
Invisible Past Calendars in <CalendarList />

### ISSUE THREAD

**Issue by dk0r** [wix/react-native-calendars#187]
## Description
When using the `<CalendarList/>` [example code](https://github.com/wix/react-native-calendars#calendarlist), scrolling to the past results in blank/empty spots where past calendars should be. These 'invisible calendars' are annotated in the graphic below. They're also shown in the following gif: [https://i.imgur.com/Z8eNbtk.gif](https://i.imgur.com/Z8eNbtk.gif)

![Invisible Past Calendars](https://i.imgur.com/mENwT50.png "Invisible Past Calendars")

## Expected Behavior
Upon scrolling to the past, I expect to see past calendars (not blank-spots). Per the docs, we should see 50 past calendars by default (or however many are set via the `pastScrollingRange` prop).

## Observed Behavior
In the following gif, `<CalendarList/>` is being scrolled to past and future. Blank-spots can be seen appearing where past months (August 2017, July 2017, June 2017, etc...) should be: [https://i.imgur.com/Z8eNbtk.gif](https://i.imgur.com/Z8eNbtk.gif)

Explicitly setting the `pastScrollRange={....}` prop does not alleviate this issue and only limits the number of blank-spots which are present.

## Environment
* `react-native-calendars@1.6.2`
* `react-native@0.48.3`
* `Emulated Pixel XL on android@8.0.0`

## Reproducible Demo
See the official use case example: [https://github.com/wix/react-native-calendars#calendarlist](https://github.com/wix/react-native-calendars#calendarlist)

**Comment by tautvilas** [comment]
Do you get invisible calendars in official example too? If not, what kind of navigation solution are you using in your app? What is the containing element for CalendarsList?

**Comment by dk0r** [comment]
**Issue closed**: After struggling to debug this issue, I decided to revert my project to a previous commit and have yet to incur 'invisible months'. Will reopen this issue if it occurs again and I can isolate the cause.


> > @tautvilas Do you get invisible calendars in official example too?
> 
> My bad, I should have checked that. I ran the [official example](https://github.com/wix/react-native-calendars/tree/master/example) and also init'd a new react-native project (grabbing react-native-calendars from npm). In both cases, `<CalendarList />` worked properly and visibly displayed all past calendars.
> 
> > @tautvilas If not, what kind of navigation solution are you using in your app?
> 
> I'm using `<TabNavigator/>` from `react-navigation@1.0.0-beta.13`
> 
> > @tautvilas What is the containing element for CalendarsList?
> 
> ```
> <TabNavigator> (from react-navigation@1.0.0-beta.13)
>    <DrawerLayout> (from react-native-drawer-layout@1.3.2)
>       <View> (a custom component with several other imports)
>          <CalendarList> (from react-native-calendars@1.6.3)
> ```
>

**Comment by SpongeBobSun** [comment]
Just solved a similar issue.

For those who suffered the same issue, please check whether your animation is blocking the main thread, which will result in the scrollview stop rendering. Try to put your animation block in `InteractionManager.runAfterInteractions`

**Comment by jsaguiar** [comment]
I am also getting this issue, without any animation! But I am struggling to reproduce the bug in a new project.

**Comment by jsaguiar** [comment]
I just upgraded to RN 52 and it got fixed!

**Comment by abrantes01** [comment]
Mhhhm.. Facing the same issue with react-native 0.52.2

**Comment by waisbek** [comment]
Same issue here... Does anyone have the solution?

**Comment by jsaguiar** [comment]
@waisbek take a look to your animations, specify Infinite loops.

> When an animation is running, it can prevent VirtualizedList components from rendering more rows. If you need to run a long or looping animation while the user is scrolling through a list, you can use isInteraction: false in your animation's config to prevent this issue.
https://facebook.github.io/react-native/docs/animations.html

**Comment by anoopmm** [comment]
same issue here

**Comment by tiagodprovenzano** [comment]
Was suffering from the same error, in my case an activityIndicator animation was preventing the component from rendering.
