### ISSUE TITLE
How do I start the day of the week from Monday?

### ISSUE THREAD

**Issue by LastSpirit** [wix/react-native-calendars#1876]
Now the day of the week starts on Sunday

How do I start the day of the week from Monday?

**Comment by mlizandier** [comment]
Pass the prop `firstDay={1}`. I guess by default it is at 0.

**Comment by cwtaras** [comment]
I've came across with the same problem in Agenda component. I've added firstDay=1, and didn't change the order of the short day names. But now, date of days are incorrect. Today is 1st of September Thursday but It looks like Friday in weekly view. How can i solve this?

**Comment by suyash-kale** [comment]
Pass the prop `weekStartsOn={1}`
