### ISSUE TITLE
How to scroll years (same user can change month) using calendar view?

### ISSUE THREAD

**Issue by tusharprajapati8888** [wix/react-native-calendars#1879]
I have used a calendar for birthday selection.
There is a left and right swipe and button arrow for month change.

But how can users change years using UI?

There is a key to set the default date in the calendar, 
Like I'm passing the default 3-04-1990 date for the calendar,
But When users open the calendar and want to select the birthday 3-04-2000.

Now users need to require to click the right arrow to change months till the user will reach 1990 to the 2000 year,

So I want your suggestion on how the user can change years like months?

I'm not able to find a proper solution in the document and reported the issue. So I have created this issue,
You can solve this issue.

Thanks in advance.

**Comment by LukasMod** [comment]
Here is working solution with customHeader :
https://github.com/wix/react-native-calendars/issues/1630

And here are docs for customHeader (github readme is missing that prop): 
https://wix.github.io/react-native-calendars/docs/Calendar#customheader
