### ISSUE TITLE
Agenda Theme does not dynamically update

### ISSUE THREAD

**Issue by gjyoungjr** [wix/react-native-calendars#1884]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

The theme for the Agenda component works fine, when the values are static. However, when you want to dynamically change the theme, it does not work. For example, if you are trying to implement a dark theme feature in your application, the agenda theme does not change. It needs a whole reload of the application for the agenda to pick up on the change. 

## Expected Behavior
On changing the background color dynamically, I expected to see the changes in the UI. 

## Observed Behavior
What happened is that it does not dynamically change, it only works if it has static values. 

If there's an error message, please paste the *full terminal output and error message* in this code block:

No error messages. 

## Environment

 "react-native-calendars": "^1.1284.0",
 "react-native": "0.64.3",

Also specify:

Expo running on iPhone XS

## Reproducible Demo

To reproduce this issue, simply give background color or any properties in the theme styling a dynamic state variable, and have the state changes. You will realize the agenda component does not pick up on state changes and update theme styling as it should. 

## Screenshots

No available screenshots for the issue as it's not really proper proofing if i provide screenshots.

**Comment by gopidon** [comment]
Yes! this is a bug

**Comment by danyzor** [comment]
For anyone still facing this issue, I struggled to make the agenda comply to dark/light mode in the app. I found a workaround:

So when I open the Agenda, i have a loading screen with react-native-lottie which runs until i get the data. Something like:

```
useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, [darkMode]);

const [loading, setLoading] = useState(true);
const [darkMode, setDarkMode] =  useMMKVStorage('darkmode', storage, true);

if (loading)
     return <LoadingAnimation/>

return <Agenda ...props/>
```

By forcing a state change and a re-render(with useEffect) when the theme changes, you will achieve dynamic theming for the agenda.

**Comment by dipanjanpanja6** [comment]
I React if you change the key of the component then its gonna re-render that component, because key is the identifier of the component key change component change. use this:

 ```javascript
 <Calendar key={dark ? 'dark-calender' : 'light-calender'} />
```
