### ISSUE TITLE
Agenda Component - when navigate back tot the AgendaScreen the top calendar is flickering

### ISSUE THREAD

**Issue by airimia1995** [wix/react-native-calendars#1903]
## Description
Using navigation stack from react-navigation, when traveling back tot the screen where the AgendaComponent is displayed the top calendar is flickering

## Expected Behavior
If the component is already rendered the calendar should not flicker

## Observed Behavior
The calendar is flickering every time you access the page

## Environment

* react-native-calendars: react-native-calendars@1.1284.0
* react-native: react-native@0.66.4
* Ios 15.5 device
* react-navigation: 6.1.1,
https://user-images.githubusercontent.com/25641812/174054505-3b57d0d2-500e-439b-8b3d-e9496b61f2ab.mov

**Comment by Sunhat** [comment]
+1

**Comment by Uzef1997** [comment]
+1
