### ISSUE TITLE
Weekends Style CalendarList

### ISSUE THREAD

**Issue by limaho** [wix/react-native-calendars#1906]
## Description

Hi community, is there any way to change style of weekends `(saturday and sunday)` of `CalendarList` without create a new `DayComponent`?

I am trying to follow examples but I could not make it work.

Thanks

**Comment by adnankarim** [comment]
if you have found the solution let me know.
As far as i have discovered there is no prop to directly do that 
but you can pass sat and sun dates of particular month to " markedDates" prop them with custom style. 
 To particular month based on current month or onMonthchange prop
https://stackoverflow.com/questions/20898661/how-to-get-saturdays-and-sundays-dates-of-a-month-javascript

**Comment by Desintegrator** [comment]
True programmers just close the issues, not fix it
