### ISSUE TITLE
Android Agenda Performance

### ISSUE THREAD

**Issue by Ainias** [wix/react-native-calendars#1907]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

The performance under Android is very bad up to a point where opening the agenda needs more than 5-10 seconds every time. 

## Expected Behavior

Opening/Closing the agenda should be much faster

## Observed Behavior

Opening/Closing the agenda is slow 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.22.0
* `npm ls react-native`: 0.67.4

Also specify:

1. Device/emulator/simulator & OS version: Emulator (Android 9 and above) and Real device (Android 9)

## Reproducible Demo

I'm working on a minimalistic reproducible demo, but in the meantime, if anybody has an idea, feel free to comment

**Comment by rohanvasishth** [comment]
I am experiencing the same issue both on simulator and on device.

**Comment by andrelramos** [comment]
+1

**Comment by erennyuksell** [comment]
+1

**Comment by minaairsupport** [comment]
+1

**Comment by Ainias** [comment]
It's still a problem

**Comment by TahanyAljemzawy** [comment]
I am facing the same issue :"(
is there any solution?

**Comment by detinho** [comment]
Hii all, anyone else facing the same issue? Are you using the latest version of the lib?

**Comment by glitchkyle** [comment]
Also facing the same issue. Works perfectly fine, however, on iOS.

**Comment by renesoaresse** [comment]
+1
