### ISSUE TITLE
Current month's calendar not displaying.

### ISSUE THREAD

**Issue by chapeljuice** [wix/react-native-calendars#192]
## Description

My calendars are displaying the incorrect default dates. Am I doing something wrong?

## Expected Behavior

When I open the calendar it should display the current month & year (September 2017 right now).

## Observed Behavior

_Whether or not_ I include the "current" parameter on the component, it's still just displaying July 2013 instead of September 2017. 

Here's my markup:
```
let todaysDate = Moment().format('L')
<CalendarList
  onDayPress={(day) => this.onDayPress(day)}
  style={styles.calendar}
  current={todaysDate}
  markedDates={{[this.state.selected ? this.state.selected : this.state.ciDate]: {selected: true}}}
/>
```

Screenshot of result:
<img width="410" alt="screen shot 2017-09-28 at 8 35 42 am" src="https://user-images.githubusercontent.com/862642/30975829-163ccea6-a428-11e7-8f7b-d3e586f5802d.png">

## Environment

```
"react": "^16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-calendars": "^1.6.2",
```

**Comment by chapeljuice** [comment]
Just as a follow up, if I add the following parameter on the component:
```
pastScrollRange={24}
```
It then displays September 2015 by default, and I cannot scroll before that.

**Comment by tautvilas** [comment]
Hi, apparently RN 44 FlatList does not have initialScrollIndex property which this calendar is using. You can either downgrade react-native-calendars to 1.5.9 version or upgrade you RN version for calendars-list to work

**Comment by chapeljuice** [comment]
Thanks so much for the reply! I ended up trying to upgrade RN but it was too much of a hassle so I downgraded react-native-calendars and it worked great.

Thanks again!
