### ISSUE TITLE
react-native-Web Failed to compile: You may need an additional loader to handle the result of theses loaders

### ISSUE THREAD

**Issue by Nestoro** [wix/react-native-calendars#1928]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

In react-native-web I can not use this calendar. If I try to compile, I get am obscure error:.

## Expected Behavior

It should compile :)

## Observed Behavior

```
Failed to compile.

Module parse failed: Unexpected token (2:7)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export {default as Calendar} from './calendar';
> export type {CalendarProps} from './calendar';
| export {default as CalendarList} from './calendar-list';
| export type {CalendarListProps} from './calendar-list';
ERROR in ./node_modules/react-native-calendars/src/index.ts 2:7
Module parse failed: Unexpected token (2:7)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export {default as Calendar} from './calendar';
> export type {CalendarProps} from './calendar';
| export {default as CalendarList} from './calendar-list';
| export type {CalendarListProps} from './calendar-list';

webpack compiled with 1 error
```

## Environment

- "react-native": "0.69.1"
- "react-native-calendars": "^1.1285.0"
- "react-native-web": "^0.18.4"

Web

## Screenshots

This is my babel.config.js:

```
module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
    plugins: [
        [
            'module-resolver',
            {
                root: ['./src'],
                extensions: ['.js', '.ts', '.tsx', '.ios.js', '.android.js'],
            },
        ],
        '@babel/plugin-transform-runtime',
    ],
    env: {
        production: {
            plugins: ['transform-remove-console'],
        },
    },
};
```

I have no separate webpack config.

## Additional information:

This issue seems to be related: https://github.com/wix/react-native-calendars/issues/1116

**Comment by sujayjaju** [comment]
@Nestoro In case it helps, adding ".ts" support to babel config fixed it for me.

```js
const babelLoaderConfiguration = {
  test: [/\.js$/, /\.jsx$/, /\.ts$/],
  include: [
...
    path.resolve(rootDirectory, 'node_modules/react-native-calendars'),
...
```

**Comment by mwkthang** [comment]
Hi @sujayjaju, my babel.config.js file looks like this. So, how can I do that, could you please help me?

```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-typescript',
  ],
};
```

**Comment by sujayjaju** [comment]
@mwkthang 

The code needs to be added in webpack config under babelLoaderConfiguration

**Comment by vaibhav-neosoft** [comment]
Hi @sujayjaju i am facing the same issue 
my webpack.config.js 
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-typescript'
  ],
  plugins: [
    ['module-resolver', {
      alias: {
        '^react-native$': 'react-native-web',
        'react-native/Libraries/Image/AssetRegistry$': 'react-native-web/dist/modules/AssetRegistry',
      },
    }],
    ['@babel/plugin-syntax-jsx'],
    ['@babel/plugin-proposal-class-properties'],
  ]
}
my rollup.config
import alias from '@rollup/plugin-alias';
import jsx from 'acorn-jsx';
import url from '@rollup/plugin-url';
import path, { resolve } from 'path';
import typescript from 'rollup-plugin-typescript2';
import json from '@rollup/plugin-json';
import pkg from './package.json';
import nodeResolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import babel from '@rollup/plugin-babel';
import peerDepsExternal from 'rollup-plugin-peer-deps-external';

export default {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true,
    },
    {
      file: pkg.module,
      format: 'esm',
      sourcemap: true,
    },
  ],
  external: [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.peerDependencies || {}),
    'react-native-web',
    'react-dom','react','react-native-calendars'
    ],
  plugins: [
    json(),
    nodeResolve({
      include: ['node_modules/react-native/**', 'node_modules/react/**','node_modules/react-native-svg/**',
      'node_modules/react-native-web/**',
      path.resolve(__dirname, './node_modules/react-native-calendars')
    ],
      //exclude: 'node_modules/react-native/**',
      jsnext: true,
      extensions: ['.ts','.tsx', '.jsx', '.js']
  }),
 
    typescript({ tsconfig: "./tsconfig.json" }),

    babel({
      test: [/\.js$/, /\.jsx$/, /\.ts$/],
      extensions: [".js", ".ts", ".jsx", ".tsx"],
      include: [
        path.resolve(__dirname, './node_modules/react-native-calendars'),
      ],

  }
  ),
  commonjs({ include: /node_modules/}),
  ]
 
};


where i should add this ?? please help

thanks
