### ISSUE TITLE
<CalendarList /> component is not working properly when Hermes is enabled

### ISSUE THREAD

**Issue by Yandamuri** [wix/react-native-calendars#1934]
## Description

Usually when calendar is rendered for the first time `onVisibleMonthsChange` function is called once with today's date . But This function is called three times with an empty array or wrong date when `Hermes` is enabled.

## Expected Behavior

`onVisibleMonthsChange` function should be called once with today's date.

## Observed Behavior

`onVisibleMonthsChange` function is called three times like follows,

1.First time called with today's date(Which is accurate)
2.Second time called with an empty array
3.Third time called with wrong date

## Environment

* `npm ls react-native-calendars`:  `1.1285.0` and `1.1254.0`
* `npm ls react-native`: 0.63, 0.66, 0.67

Also specify:

1. Device/emulator/simulator & OS version: `Honor 9N, Android 9 and iPhone SE iOS 15.2`

## Reproducible Demo

Please find the reproducible demo here - https://github.com/Yandamuri/react-native-calendars-test.git

This is how my code looks like

`CalendarList` implementation

        <View style={{height: 420}}>
              <CalendarList
                  current={this.state.currentDate}
                  firstDay={0}
                  horizontal={true}
                  hideArrows={false}
                  pagingEnabled={true}
                  calendarWidth={windowWidth}
                  calendarHeight={420}
                  onVisibleMonthsChange={months => this.onSwipeMonths(months)}
              />
       </View>

`onVisibleMonthsChange` function implementation,

     onSwipeMonths(months) {
           let { month, year, day } = months[0] ;
           let currentDate = moment(`${year}/${month}/${day}`).format('YYYY-MM-DD');
           this.setState({ currentDate });
     }

  As I mentioned above `onVisibleMonthsChange` is called three times. When it's called second time with an empty array getting following error,

  
![WhatsApp Image 2022-07-14 at 4 36 00 PM](https://user-images.githubusercontent.com/31983789/178970121-7cb4d3e6-3e40-4a65-8849-7572faa155e1.jpeg)

below is the error from metro bundle,

<img width="400" alt="Screenshot 2022-07-14 at 4 37 01 PM" src="https://user-images.githubusercontent.com/31983789/178970236-b481f67f-9eb9-4d7f-a8d2-17561ad728b1.png">

Note: This is happening in both debug mode and release mode. But surprisingly working as expected when `remote debugger` is enabled. But issue appears when `remote debugger` is disabled.

If the `Hermes` is disabled then everything works as expected in both debug and release mode.

**Comment by hugows** [comment]
@Yandamuri Any news on this?

**Comment by Yandamuri** [comment]
I haven't checked it recently. I just disabled Hermes engine
