### ISSUE TITLE
Selected day changed when scrolling WeekCalendar

### ISSUE THREAD

**Issue by serhiimahdiuk** [wix/react-native-calendars#1937]
## Description

Hi folks, i have a little problem with WeekCalendar in `src/expandableCalendar/WeekCalendar/new.js`
When i scroll to next week current date is changed in context and i can't control it, so i created little patch with new prop for disabling onPageChange method manually.

```diff
diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
index e4ecda2..cca2c34 100644
--- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
+++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
@@ -3,6 +3,7 @@ import { CalendarListProps } from '../../calendar-list';
 export interface WeekCalendarProps extends CalendarListProps {
     /** whether to have shadow/elevation for the calendar */
     allowShadow?: boolean;
+    disableOnPageChange?: boolean
 }
 declare const WeekCalendar: (props: WeekCalendarProps) => JSX.Element;
 export default WeekCalendar;
diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
index 83839b4..8224fc4 100644
--- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
+++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
@@ -13,7 +13,7 @@ import { UpdateSources } from '../commons';
 import { sameWeek } from '../../dateutils';
 const NUMBER_OF_PAGES = 50;
 const WeekCalendar = (props) => {
-    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, testID } = props;
+    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, testID, disableOnPageChange = false } = props;
     const context = useContext(CalendarContext);
     const { date, updateSource } = context;
     const style = useRef(styleConstructor(theme));
@@ -40,7 +40,7 @@ const WeekCalendar = (props) => {
         props.onDayPress?.(dateData);
     }, [props.onDayPress]);
     const onPageChange = useCallback((pageIndex, _prevPage, { scrolledByUser }) => {
-        if (scrolledByUser) {
+        if (scrolledByUser && !disableOnPageChange) {
             context?.setDate(items[pageIndex], UpdateSources.WEEK_SCROLL);
         }
     }, [items]);
```

## Expected Behavior

I want mark only selected date and save until changed by onDayPress method

## Observed Behavior

When i scroll week calendar selected day changed to first day for current displayed week

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.1285.0
* `npm ls react-native`: 0.69.1

Also specify:

1. Device/emulator/simulator & OS version: tested with iOS simulator iPhone 12 Pro Max (15.4)

## Screenshots

before patch:

https://user-images.githubusercontent.com/65591882/179208976-feee2982-59e4-40bc-8638-6a3535a9727e.mov

after patch:

https://user-images.githubusercontent.com/65591882/179208942-db7b670b-cf9a-4ce7-b2ab-856b10b8b11f.mov

**Comment by serhiimahdiuk** [comment]
@JTechnologiesAU @SamuelCastr0 
Sorry for the late message I guess now this issue may not be relevant but here is a patch for the latest 
`"react-native-calendars": "^1.1301.0"`

```diff
diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
index 9598926..b53284e 100644
--- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
+++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
@@ -3,6 +3,7 @@ import { CalendarListProps } from '../../calendar-list';
 export interface WeekCalendarProps extends CalendarListProps {
     /** whether to have shadow/elevation for the calendar */
     allowShadow?: boolean;
+    disableOnPageChange?: boolean
 }
 declare const WeekCalendar: (props: WeekCalendarProps) => React.JSX.Element;
 export default WeekCalendar;
diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
index b7e3a65..83b7fc0 100644
--- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
+++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
@@ -14,7 +14,7 @@ import { sameWeek } from '../../dateutils';
 const NUMBER_OF_PAGES = 50;
 const DEFAULT_PAGE_HEIGHT = 48;
 const WeekCalendar = (props) => {
-    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, calendarHeight = DEFAULT_PAGE_HEIGHT, testID } = props;
+    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, calendarHeight = DEFAULT_PAGE_HEIGHT, testID, disableOnPageChange = false } = props;
     const context = useContext(CalendarContext);
     const { date, updateSource } = context;
     const style = useRef(styleConstructor(theme));
@@ -41,10 +41,10 @@ const WeekCalendar = (props) => {
         props.onDayPress?.(dateData);
     }, [props.onDayPress]);
     const onPageChange = useCallback((pageIndex, _prevPage, { scrolledByUser }) => {
-        if (scrolledByUser) {
+        if (scrolledByUser && !disableOnPageChange) {
             context?.setDate(items[pageIndex], UpdateSources.WEEK_SCROLL);
         }
-    }, [items]);
+    }, [items, disableOnPageChange]);
     const reloadPages = useCallback(pageIndex => {
         const date = items[pageIndex];
         setItems(getDatesArray(date, firstDay, NUMBER_OF_PAGES));
```

filename - `react-native-calendars+1.1301.0.patch`

What I did in file `react-native-calendars/src/expandableCalendar/WeekCalendar/new.js`
- Added new property to WeekCalendar component - `disableOnPageChange`
- Set it `false` as default
- Used inside onPageChange function as a condition value

`<WeekCalendar disableOnPageChange={true}/>` - will prevent changing date on page change

**Comment by serhiimahdiuk** [comment]
if it's helpful I can create PR, but I see that this is not a common problem so ...

**Comment by JTechnologiesAU** [comment]
Hi @serhiimahdiuk,
I ended up going custom to resolve this while I work on other areas of my project. I would love to see if it's accepted as a PR considering how well you've identified the problem and articulated the solution. I would consider using this library again if it was accepted.

**Comment by tinBilicCoreline** [comment]
> if it's helpful I can create PR, but I see that this is not a common problem so ...

it is, + 1

**Comment by hariharank6** [comment]
> it is, + 1

> +2

**Comment by hariharank6** [comment]
> Hi @serhiimahdiuk, I ended up going custom to resolve this while I work on other areas of my project. I would love to see if it's accepted as a PR considering how well you've identified the problem and articulated the solution. I would consider using this library again if it was accepted.

+1 - I'm planning to switch to other packages just because of this issue.

**Comment by elie-chaaban** [comment]
The issue i m having is if I have minDate set to today and swipe left, the first day of the previous week is selected and it's a big issue for me.

**Comment by IrisHCI** [comment]
I am encountering the same issue, the patch would be very useful @serhiimahdiuk, please consider creating a PR :-)

**Comment by jerone** [comment]
We want to use this component in our app, as it's one of the most feature-full components out there. 
But this issue is holding us back.

@Inbal-Tish Would you please have a look at this issue and potential PR's (#2348).

**Comment by audn** [comment]
My workaround is adding `selectedDayBackgroundColor` and `selectedDayTextColor` to `theme`, then applying styles to the date using `marked`.

## Before

https://github.com/wix/react-native-calendars/assets/21041399/d7da5576-abca-4d26-b52a-484af1b1ebfe



## After

https://github.com/wix/react-native-calendars/assets/21041399/053857b4-8342-4841-9c4f-ba57805e829c




```tsx
<CalendarProvider date={date}>
  <WeekCalendar
    date={date}
    onDayPress={(d) => {
      setDate(d.dateString);
    }}
    firstDay={1}
    markingType="custom"
    theme={{
      selectedDayBackgroundColor: 'transparent', // add this
      selectedDayTextColor: "white" // add this
    }}
    markedDates={marked}
  />
</CalendarProvider>;

```

The style in `customStyle` will overwrite the `theme` styles.
```tsx
const marked: { [key: string]: MarkingProps } = useMemo(() => {
  return {
    [today.toISOString().split('T')[0]!]: {
      selected: true,
      type: 'custom',
      customStyles: {
        container: {},
        text: {},
      },
    },

    [date]: {
      selected: true,
      type: 'custom',
      customStyles: {
        container: {},
        text: {},
      },
    },
  };
}, [date, today]);
```

**Comment by jkronk** [comment]
> if it's helpful I can create PR, but I see that this is not a common problem so ...

Still running into this today

**Comment by TadasSipavicius** [comment]
> @JTechnologiesAU @SamuelCastr0 Sorry for the late message I guess now this issue may not be relevant but here is a patch for the latest `"react-native-calendars": "^1.1301.0"`
> 
> ```diff
> diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
> index 9598926..b53284e 100644
> --- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
> +++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.d.ts
> @@ -3,6 +3,7 @@ import { CalendarListProps } from '../../calendar-list';
>  export interface WeekCalendarProps extends CalendarListProps {
>      /** whether to have shadow/elevation for the calendar */
>      allowShadow?: boolean;
> +    disableOnPageChange?: boolean
>  }
>  declare const WeekCalendar: (props: WeekCalendarProps) => React.JSX.Element;
>  export default WeekCalendar;
> diff --git a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
> index b7e3a65..83b7fc0 100644
> --- a/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
> +++ b/node_modules/react-native-calendars/src/expandableCalendar/WeekCalendar/new.js
> @@ -14,7 +14,7 @@ import { sameWeek } from '../../dateutils';
>  const NUMBER_OF_PAGES = 50;
>  const DEFAULT_PAGE_HEIGHT = 48;
>  const WeekCalendar = (props) => {
> -    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, calendarHeight = DEFAULT_PAGE_HEIGHT, testID } = props;
> +    const { current, firstDay = 0, markedDates, allowShadow = true, hideDayNames, theme, calendarWidth, calendarHeight = DEFAULT_PAGE_HEIGHT, testID, disableOnPageChange = false } = props;
>      const context = useContext(CalendarContext);
>      const { date, updateSource } = context;
>      const style = useRef(styleConstructor(theme));
> @@ -41,10 +41,10 @@ const WeekCalendar = (props) => {
>          props.onDayPress?.(dateData);
>      }, [props.onDayPress]);
>      const onPageChange = useCallback((pageIndex, _prevPage, { scrolledByUser }) => {
> -        if (scrolledByUser) {
> +        if (scrolledByUser && !disableOnPageChange) {
>              context?.setDate(items[pageIndex], UpdateSources.WEEK_SCROLL);
>          }
> -    }, [items]);
> +    }, [items, disableOnPageChange]);
>      const reloadPages = useCallback(pageIndex => {
>          const date = items[pageIndex];
>          setItems(getDatesArray(date, firstDay, NUMBER_OF_PAGES));
> ```
> 
> filename - `react-native-calendars+1.1301.0.patch`
> 
> What I did in file `react-native-calendars/src/expandableCalendar/WeekCalendar/new.js`
> 
> * Added new property to WeekCalendar component - `disableOnPageChange`
> * Set it `false` as default
> * Used inside onPageChange function as a condition value
> 
> `<WeekCalendar disableOnPageChange={true}/>` - will prevent changing date on page change

Approve this solution please. I had to do it inside node modules to fix this issue ....

**Comment by ssomarii** [comment]
Hi)
If somebody still have this issue - I just searched for solution for exact the same case and found that this feature was added in [1.1311.0](https://github.com/wix/react-native-calendars/releases/tag/1.1311.0) release two days ago  
So it's possible to swipe Week calendar (and another types of calendar) and save current date selected.

``` js
<CalendarProvider
     disableAutoDaySelection={[
        ExpandableCalendar.navigationTypes.WEEK_SCROLL,
      ]}
/>
```

**Comment by JoshWhiteTTD** [comment]
> Hi) If somebody still have this issue - I just searched for solution for exact the same case and found that this feature was added in [1.1311.0](https://github.com/wix/react-native-calendars/releases/tag/1.1311.0) release two days ago So it's possible to swipe Week calendar (and another types of calendar) and save current date selected.
> 
> <CalendarProvider
>      disableAutoDaySelection={[
>         ExpandableCalendar.navigationTypes.WEEK_SCROLL,
>       ]}
> />

In case anyone else is struggling with the same issue...

I am making use of `CalendarProvider`'s `onDateChanged` prop. This still fires if `disableAutoDaySelection` is true for your event type.
Not sure if this is intended behavior, or a bug @talhauzair-28?
I did this to solve it:

```tsx
<CalendarProvider
  disableAutoDaySelection={[ExpandableCalendar.navigationTypes.WEEK_SCROLL]}
  onDateChanged={(date, updateSource) => {
    if (updateSource === UpdateSources.WEEK_SCROLL) {
      return;
    }
    // custom date changed handler...
    //onDateChanged(date);
  }}
/>;

```
