### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by anisimoves** [wix/react-native-calendars#1945]
Hello!
Library works well, but I have some styling issues.
I can't find in documentation any extended information about styling calendar and it's items.
![Simulator Screen Shot - iPhone 13 - 2022-07-22 at 13 52 12](https://user-images.githubusercontent.com/100140768/180425063-59e19eb5-b1d4-4890-9d20-142b7f45bec2.png)

How I can add horizontal borders between days (black lines) and remove spacing between first and other items (red arrows)?

My renderItem function (I am using react native tailwind for styling):

```
  let renderItem = reservation => {
    return (
      <TouchableOpacity
        style={[t.bgWhite, t.roundedLg, t.mT2, t.p3, t.mR4, t.mB0]}
        onPress={() => console.log(reservation.name)}>
        <Text style={[]}>{reservation.name}</Text>
      </TouchableOpacity>
    );
  };
```

**Comment by matysanchez** [comment]
Did you solve this? I am looking for the same solution
