### ISSUE TITLE
Increase the size of the calendar view over the agenda

### ISSUE THREAD

**Issue by ArthurSimoess** [wix/react-native-calendars#1948]
Hello guys, its possible to increase the size of the calendar view over the agenda? Now the calendar show only seven days but i want to show at least fourteen days without me having to click in the button to open it.  Below is the picture of my component with only seven days show:

![Screenshot_20220722-152058_Expo Go](https://user-images.githubusercontent.com/84386289/180500681-8de0a6fa-dcfd-4b77-88e6-6360bd2e46bc.jpg)

**Comment by aaronbesson** [comment]
I tried using calendarOffset but it didnt work

calendarOffset(): number;
