### ISSUE TITLE
`CalendarProvider` date prop not changing `AgendaList` date

### ISSUE THREAD

**Issue by KrisLau** [wix/react-native-calendars#1958]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I'm trying to get the date prop to work for my react-native-calendar and the date didn't change for the initial render and even when I call the `setState` in the `onDayPress`. Also pressing the today button doesn't seem to work either? in the picture I hardcode the date prop but i usually have the `selectedDay` state there. Just did that to test

## Expected Behavior
Clicking on a date in the `ExpandableCalendar` should scroll to selected date in `AgendaList`

## Observed Behavior
it only changes the date in the ExpandableCalendar but not in the AgendaList.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: `react-native-calendars@1.1286.0`
* `npm ls react-native`: 
```
├─┬ @notifee/react-native@5.4.1
│ └── react-native@0.64.3 deduped
├─┬ @react-native-async-storage/async-storage@1.17.6
│ └── react-native@0.64.3 deduped
├─┬ @react-native-clipboard/clipboard@1.10.0
│ └── react-native@0.64.3 deduped
├─┬ @react-native-community/geolocation@2.1.0
│ └── react-native@0.64.3 deduped
├─┬ @react-native-community/hooks@2.8.1
│ └── react-native@0.64.3 deduped
├─┬ @react-native-community/netinfo@8.3.1
│ └── react-native@0.64.3 deduped
├─┬ @react-native-firebase/app@14.11.0
│ └── react-native@0.64.3 deduped
├─┬ @react-native-google-signin/google-signin@7.2.2
│ └── react-native@0.64.3 deduped
├─┬ @react-native-masked-view/masked-view@0.2.7
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/bottom-tabs@6.3.1
│ ├─┬ @react-navigation/elements@1.3.3
│ │ └── react-native@0.64.3 deduped
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/native@6.0.10
│ └── react-native@0.64.3 deduped
├─┬ @react-navigation/stack@6.2.1
│ └── react-native@0.64.3 deduped
├─┬ @rneui/base@4.0.0-rc.4
│ ├─┬ react-native-ratings@8.1.0
│ │ └── react-native@0.64.3 deduped
│ └─┬ react-native-size-matters@0.4.0
│   └── react-native@0.64.3 deduped
├─┬ @sentry/react-native@3.4.3
│ └── react-native@0.64.3 deduped
├─┬ react-native-audio-recorder-player@3.5.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-autolink@4.0.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-calendars@1.1286.0
│ └─┬ recyclerlistview@3.0.5
│   └── react-native@0.64.3 deduped
├─┬ react-native-document-picker@8.1.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-draggable-flatlist@3.1.2
│ └── react-native@0.64.3 deduped
├─┬ react-native-dropdown-picker@5.4.2
│ └── react-native@0.64.3 deduped
├─┬ react-native-error-boundary@1.1.13
│ └── react-native@0.64.3 deduped
├─┬ react-native-fbsdk-next@8.0.5
│ └── react-native@0.64.3 deduped
├─┬ react-native-get-random-values@1.8.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-google-places-autocomplete@2.4.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-image-picker@4.8.4
│ └── react-native@0.64.3 deduped
├─┬ react-native-keyboard-aware-scroll-view@0.9.5
│ ├─┬ react-native-iphone-x-helper@1.3.1
│ │ └── react-native@0.64.3 deduped
│ └── react-native@0.64.3 deduped
├─┬ react-native-linear-gradient@2.5.6
│ └── react-native@0.64.3 deduped
├─┬ react-native-maps@0.31.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-pager-view@5.4.11
│ └── react-native@0.64.3 deduped
├─┬ react-native-pell-rich-editor@1.8.8
│ └── react-native@0.64.3 deduped
├─┬ react-native-reanimated@2.8.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-safe-area-context@4.2.5 invalid: "^3.1.9" from node_modules/@rneui/base
│ └── react-native@0.64.3 deduped
├─┬ react-native-screens@3.9.0
│ └── react-native@0.64.3 deduped
├─┬ react-native-tab-view@3.1.1
│ └── react-native@0.64.3 deduped
├─┬ react-native-track-player@2.1.3
│ └── react-native@0.64.3 deduped
├─┬ react-native-url-preview@1.1.9
│ └── react-native@0.64.3 deduped
├─┬ react-native-webview@11.21.1
│ └── react-native@0.64.3 deduped
└─┬ react-native@0.64.3
  └─┬ @react-native-community/cli@5.0.1
    └── react-native@0.64.3 deduped
```

Also specify:

1. Device/emulator/simulator & OS version: iPhone 11 (13.6)

## Reproducible Demo

```
function ExpandableCalendarAgenda(props) {
  ...
  return (
    <CalendarProvider
      date={selectedDay}
      showTodayButton={true}
      disabledOpacity={0.6}
      todayBottomMargin={16}
      onDateChanged={date => setSelectedDay(date)}
      theme={{
        todayButtonTextColor: Colors.WHITE,
      }}
      todayButtonStyle={styles.todayButton}>
      {props.currentScreen === 'UserSchedule' && (
        <ExpandableCalendar
          theme={getTheme()}
          pastScrollRange={60}
          futureScrollRange={60}
          displayLoadingIndicator={true}
          disableAllTouchEventsForDisabledDays
          markedDates={getMarkedDates(eventOccurrencesFormatted)}
          minDate={format(sub(new Date(), {years: 4}), 'yyyy-MM-dd')}
          maxDate={format(add(new Date(), {years: 4}), 'yyyy-MM-dd')}
          onDayPress={({dateString}) => {
            setSelectedDay(dateString);
          }}
          calendarStyle={styles.calendar}
          style={{paddingTop: insets.top - 10}}
        />
      )}
      <AgendaList
        markToday={false}
        windowSize={5}
        scrollToNextEvent
        initialNumToRender={7}
        maxToRenderPerBatch={5}
        onEndReachedThreshold={0.1}
        removeClippedSubviews={false}
        updateCellsBatchingPeriod={30}
        sections={eventOccurrencesFormatted}
        renderItem={({item}) => (
          <EventListItem
            currentScreen={props.currentScreen}
            roles={props?.roles ?? []}
            item={item}
          />
        )}
        contentContainerStyle={{paddingBottom: 80}}
        sectionStyle={styles.section}
      />
    </CalendarProvider>
  );
}
```

## Screenshots

![image](https://user-images.githubusercontent.com/46275463/182713973-aa98f76d-391d-472c-a40d-e9418dd8181f.png)

**Comment by KrisLau** [comment]
@Inbal-Tish Related to #1862

**Comment by Inbal-Tish** [comment]
@KrisLau Hi. Please remove all `selectedDay` logic from `CalendarProvider` props (`date` and `onDateChanged`) and from `ExpandableCalendar`'s `onDayPress` prop. The ExpandableCalendar and its context provider are managing the selection of the date internaly. You should only provide the INITIAL date to the provider's `date` prop.

**Comment by KrisLau** [comment]
@Inbal-Tish I just tried that and it still seems to stay on the same date. I feel like the selectedDay logic was working for me until I updated the package a while back but the problem is I have no idea when it stopped working since I only noticed the error recently

**Comment by Inbal-Tish** [comment]
@KrisLau Did you try running our demo app to see if your bug reproduces there? I can't seem to do that or I'm not sure what the bug is - can you add a video maybe?

**Comment by KrisLau** [comment]
@Inbal-Tish Sorry for the super late reply! here's a video of my problem:

https://user-images.githubusercontent.com/46275463/191371294-a94b0ff8-edf6-40a7-bdfe-493a893635ef.mp4

**Comment by KrisLau** [comment]
@Inbal-Tish Link to a comment I made awhile back with more info about the performance issue: 

- https://github.com/wix/react-native-calendars/issues/1088#issuecomment-1068202765

**Comment by jslok** [comment]
I believe I am having the same issue. Selecting a date on the expanded calendar has no effect on the AgendaList. Seems to be an issue if the date is farther than the rendered window.

**Comment by KrisLau** [comment]
@Inbal-Tish Also getting `Excessive pending callbacks` and I noticed the expandableCalendar has an issue where if you expand it all the way, wait for a second, and try swipe it close, it refuses to move. The only way to close it is by pulling it down a little and then back up without lifting my finger.
