### ISSUE TITLE
Agenda component don't work with markingType period ?

### ISSUE THREAD

**Issue by th3conc3pt3ur** [wix/react-native-calendars#1959]
I use an **Agenda** component for displaying my event. Some of them have more than one day duration that i wanted to display with the period functionnality like this :
![image](https://user-images.githubusercontent.com/1927030/182860027-5e9188e6-bffd-4494-8586-d00de594790d.png)

Is this feature available with the **Agenda** component ? I've try adding this props to agenda without success :
```
markingType={'period'}
markedDates={{
    '2022-08-20': {textColor: 'green'},
    '2022-08-22': {startingDay: true, color: 'green'},
    '2022-08-23': {endingDay: true,color: 'green'},
}}
```
nothing display on the agenda : 
![image](https://user-images.githubusercontent.com/1927030/182861126-53354da0-a5b7-4790-91bf-37301ee69410.png)

**Comment by AliMonam** [comment]
After updating to the latest version (1.1286.0) markingType does not work anymore on Agenda. It worked perfectly for "multi-dot" before this version. Any clue?

**Comment by AliMonam** [comment]
I updated to 1.1287.0, and still have the same issue.

**Comment by contactsimonwilson** [comment]
Can confirm that downgrading from1.1287.0 to 1.1285.0 fixes the issue with dots on the agenda (at least in our use case)

**Comment by nickdebaise** [comment]
+1

**Comment by AliMonam** [comment]
The same issue on 1.1288, Is there any solution for this bug?

**Comment by Saikedo** [comment]
Are there any plans to fix this ? Agenda styles are still broken.

**Comment by 99Jannis99** [comment]
Are this Problem still not fixed?
