### ISSUE TITLE
Agenda: cannot click on last two dates on header

### ISSUE THREAD

**Issue by syntaxarray** [wix/react-native-calendars#1960]
## Description

So I add the Agenda Component and did as the example code has guided me, I however run into a major problem. When I enter the Calendar and look at the Agenda header, I click on all the days available on top but the last two are not pressable. The only time they work is when you expand the header to have a full months calendar view.

Please note that this only happens on IOS and not on Android. Works well with Android.

## Environment

1. calendar version: "react-native-calendars": "1.1286.0"
2. react-native version:   "react-native": "0.64.2"

## Reproducible Demo
`return (

    <View style={tailwind('w-full h-full z-50')}>
      <Agenda
        testID={testIDs.agenda.CONTAINER}
        items={items}
        selected={new Date().toISOString()}
        enableCalendarScrolling
        showClosingKnob={true}
        renderItem={renderItem}
        renderEmptyData={renderEmptyDate}
        rowHasChanged={rowHasChanged}
        onRefresh={onRefresh}
        showOnlySelectedDayItems
        theme={{
          calendarBackground: '#021827',
          selectedDayBackgroundColor: '#E0D2BC',
          selectedDayTextColor: '#000000',
          monthTextColor: 'white',
          todayTextColor: 'white',
          textDisabledColor: '#888888',
          dayTextColor: 'white',
          agendaKnobColor: '#DCDCDC',
        }}
      />
      <TouchableOpacity
        style={tailwind('absolute bottom-10 right-8 bg-darkmode-light p-3 rounded z-40')}
        onPress={gotToWeekCalendar}
      >
        <Text style={tailwind('text-white font-semibold')}>Week View</Text>
      </TouchableOpacity>
    </View>
  );`

## Screenshots
![Simulator Screen Shot - iPhone 13 - 2022-08-05 at 11 40 44](https://user-images.githubusercontent.com/110665936/183051695-add01505-a871-44dd-a407-fcfb1995997a.png)

**Comment by azharkhan1** [comment]
Please provide the complete code snippet including the imports and functions used in the Agenda component

**Comment by syntaxarray** [comment]
> Please provide the complete code snippet including the imports and functions used in the Agenda component

`import React, { useEffect, useMemo, useState } from 'react';
import { Text, View, TouchableOpacity, Platform } from 'react-native';
import { Agenda, AgendaEntry } from 'react-native-calendars';
import { useNavigation } from '@react-navigation/native';
import { useSelector } from 'react-redux';
import _ from 'lodash';

import {
  getAllCalendarOrders,
  getAllOrders,
  ordersSelector,
  useAppDispatch,
} from '../../../reducers';
import { useTheme } from '../../../theme';
import { OrderCalendarProps } from '../../../types';
import testIDs from './testIDs';

export const CalendarScreen: React.FC = () => {
  const dispatch = useAppDispatch();
  const [items, setItems] = useState<OrderCalendarProps>({});
  const navigation = useNavigation();
  const { tailwind } = useTheme();

  const { calendarOrders } = useSelector(ordersSelector);

  useEffect(() => {
    dispatch(getAllCalendarOrders());
  }, [dispatch]);

  useMemo(() => {
    if (_.isEmpty(calendarOrders)) {
      return;
    }
    const itemData: OrderCalendarProps = {};

    _.forEach(calendarOrders, (order) => {
      const takenTime: string = order.installationTime.replace(/ .*/, '');
      if (!itemData[takenTime]) {
        itemData[takenTime] = [];
      }
      itemData[takenTime].push({
        orderId: order.id,
        date: takenTime,
        customer: order.customer,
        total: order.total,
        installationTime: order.installationTime,
      });
    });

    setItems(itemData);
  }, [calendarOrders]);

  const orderInfo = (id: number) => {
    navigation.navigate('OrderInfo', { id });
  };

  const renderItem = (reservation: AgendaEntry, isFirst: boolean) => {
    const fontSize = isFirst ? 16 : 14;
    const color = isFirst ? 'black' : '#43515c';

    const onOrderPress = () => orderInfo(reservation.orderId);

    return (
      <TouchableOpacity
        style={tailwind('bg-white rounded-lg h-24 mr-4 mt-4 p-1 pl-2')}
        onPress={onOrderPress}
      >
        <Text style={{ fontSize, color }}>ID: {reservation.orderId}</Text>
        <Text style={{ fontSize, color }}>Date/Time: {reservation.installationTime}</Text>
        <Text style={{ fontSize, color }}>Customer: {reservation.customer}</Text>
        <Text style={{ fontSize, color }}>Total: {reservation.total}</Text>
      </TouchableOpacity>
    );
  };

  const renderEmptyDate = () => {
    return (
      <View style={tailwind('flex flex-grow text-center justify-center items-center')}>
        <Text style={tailwind('text-center font-bold text-base')}>No orders on this date!</Text>
      </View>
    );
  };

  const rowHasChanged = (r1: AgendaEntry, r2: AgendaEntry) => {
    return r1.date !== r2.date;
  };

  const gotToWeekCalendar = () => navigation.navigate('WeekCalendar');
  const onRefresh = () => dispatch(getAllOrders());
  return (
    <View style={tailwind('w-full h-full z-50')}>
      <Agenda
        testID={testIDs.agenda.CONTAINER}
        items={items}
        selected={new Date().toISOString()}
        enableCalendarScrolling
        showClosingKnob={true}
        renderItem={renderItem}
        renderEmptyData={renderEmptyDate}
        rowHasChanged={rowHasChanged}
        onRefresh={onRefresh}
        showOnlySelectedDayItems
        theme={{
          calendarBackground: '#021827',
          selectedDayBackgroundColor: '#E0D2BC',
          selectedDayTextColor: '#000000',
          monthTextColor: 'white',
          todayTextColor: 'white',
          textDisabledColor: '#888888',
          dayTextColor: 'white',
          agendaKnobColor: '#DCDCDC',
        }}
      />
      <TouchableOpacity
        style={tailwind('absolute bottom-10 right-8 bg-darkmode-light p-3 rounded z-40')}
        onPress={gotToWeekCalendar}
      >
        <Text style={tailwind('text-white font-semibold')}>Week View</Text>
      </TouchableOpacity>
    </View>
  );
};
`
