### ISSUE TITLE
dayComponent too many renders

### ISSUE THREAD

**Issue by GuvenEREN-404** [wix/react-native-calendars#1964]
## Description

the dayComponent renders every month when first clicked ,and when ı click on any day , it renders as much as the day of that month.

if anyone has encounterd such a bug, can you share solutions?

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:"^1.1280.0",
* `npm ls react-native`:"0.65.1",

**Comment by azharkhan1** [comment]
Please provide some code snippet for reproduceable code

**Comment by GuvenEREN-404** [comment]
here is the code i wrote for daycomponent

dayComponent={({ date, state, marking, theme }) => {
    
              const isDay = bookingDays.find((item) => moment(item.date).format("YYYY-MM-DD") === date?.dateString)
              
              return (
                <TouchableOpacity onPress={() => 
                onDayPress(date?.dateString) 
                }
                disabled={moment(date?.dateString).isBefore(moment().format("YYYY/MM/DD"))?true:false} >
                  <View
                    style={{
                      ...styles.calendarDayContainer,
                      borderWidth:selectedDate.date===date?.dateString? 3 : 1,
                      borderColor:
                      moment(date.dateString).isBefore(moment().format("YYYY/MM/DD"))?"lightgrey"
                      :isDay?.dailyCondition==="CLOSED"? "#E2558D": "#8858B5",
                      backgroundColor:
                      moment(date.dateString).isBefore(moment().format("YYYY/MM/DD"))?"lightgrey":
                      isDay?.dailyCondition==="CLOSED"
                      ? "#E2558D"
                        : isDay?.dailyPrice?  "#A585C9"

                       
                        : "#fff",
                    }}
                  >
                    <Text
                      style={{
                        ...styles.calendarDayText,
                        color:
                        moment(date.dateString).isBefore(moment().format("YYYY/MM/DD"))?"white":
                        isDay?.dailyPrice || isDay?.dailyCondition==="CLOSED"
                          ? "#fff"
                          : "#8858B5",
                      }}
                    >
                      {date?.day}
                    </Text>
                  </View>
                  
                </TouchableOpacity>
              );
            }}
