### ISSUE TITLE
Can't set time zone problem

### ISSUE THREAD

**Issue by OPEN-9** [wix/react-native-calendars#1992]
The user base is global, and the calendar selector has no time zone, making it difficult to distinguish between the dates the user currently selects

![image](https://user-images.githubusercontent.com/42791280/185153864-7c6a2f82-ad61-4c39-8a6f-de99117066ea.png)

**Comment by OPEN-9** [comment]
<Calendar timezone="Asia/Shanghai" />




Your support for this feature is highly required

**Comment by mehdi-developer** [comment]
Definitely need this feature .

**Comment by charlestbell** [comment]
+1 for timezone support. When I click on a date, the day object returned in the callback, is actually a day behind because of this limitation.

**Comment by charlestbell** [comment]
Hope this helps someone:
```  
 onDayPress={day => {
            const offsetInMiliseconds = new Date().getTimezoneOffset() * 60 * 1000; // Get timezone offset
            const currentDateWithTimezoneApplied = day.timestamp + offsetInMilliseconds
            // Do stuff
          }}
```
