### ISSUE TITLE
agenda attributes not working

### ISSUE THREAD

**Issue by rijanfdo** [wix/react-native-calendars#1993]
I am trying to use the props of the agenda ,which is not working as expected.
                <Agenda
                   minDate="2022-08-10"
                   maxDate="2022-10-10"
                   pastScrollRange={1}
                   futureScrollRange={2}
                   theme={{
                     selectedDayBackgroundColor: 'violet',
                   }}
                />

"dependencies": {
    "react": "18.0.0",
    "react-native": "0.69.4",
    "react-native-calendars": "^1.1288.0"
  }

I am expecting it to show only the date limit which i mentioned.But it is showing the months from the past year too.But the same code is working fine in the previous version,which is 1.1287.0.

Does anybody facing the same issue.Can anyone help me sort this out ?

**Comment by Saikedo** [comment]
Are there any plans to fix this ? Agenda styles are still broken.
