### ISSUE TITLE
isDateNotinRange is not a function

### ISSUE THREAD

**Issue by dougfer** [wix/react-native-calendars#1997]
## Description

Not sure what it seems to be the problem. Every time I try to render the Calendar component, it shows an internal error: 

> TypeError: isDateNotInRange is not a function. (In 'isDateNotInRange(day, minDate, maxDate)', 'isDateNotInRange' is undefined)

![image](https://user-images.githubusercontent.com/72472248/186037347-8f1041bf-79f1-479c-9696-955773031eba.png)

Tried to delete and reinstall package lock and node_modules but nothing seems to work.

Anyone else having this problem?

Component in repo: https://github.com/dougfer/rentx/blob/main/src/components/Calendar/Calendar.tsx

Dependencies:

`"dependencies": {
    "@expo-google-fonts/archivo": "^0.2.2",
    "@expo-google-fonts/inter": "^0.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@types/styled-components": "^5.1.25",
    "@types/styled-components-react-native": "^5.1.3",
    "axios": "^0.27.2",
    "expo": "~45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-font": "~10.1.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-calendars": "^1.1287.0",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-svg": "12.3.0",
    "react-native-web": "0.17.7",
    "styled-components": "^5.3.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/react-native-calendars": "^1.1264.3",
    "react-native-svg-transformer": "^1.0.0",
    "typescript": "~4.3.5"
  },`

**Comment by tsalama** [comment]
Also seeing an intermittent error on calendar open: `TypeError - undefined is not an object (evaluating 'this[0][methodName]')` coming from xdate

**Comment by dougfer** [comment]
I'm not sure why but I solved by excluding package.lock and installing dependencies with yarn instead of npm.
