### ISSUE TITLE
Compatibility with react-native-web

### ISSUE THREAD

**Issue by peggyrayzis** [wix/react-native-calendars#2]
Hey there! 🙋 This calendar module looks awesome. We would like to use it in our `react-native-web` project but are running into an issue because of the `.ios` and `.android` file extensions for some of the assets. My suggestion is to provide a default for these assets so our Webpack build can resolve them.

The files that are giving us trouble are:

- `src/calendar/img/previous.png`
- `src/calendar/img/next.png`
- `src/agenda/style.js`

If you add these files, then we should be good to go! The only question now is whether we use iOS or Android styling as the default for the web - what do you all think? 

cc @kkemple

**Comment by tautvilas** [comment]
Hi, thanks for reporting this. I set IOS files as defaults for v1.2.2. Android and iOS design differ just a tiny bit.

**Comment by peggyrayzis** [comment]
@tautvilas I think we need to reopen this issue. Just tried the new release and it's still failing at `src/calendar/img/next.png` and `src/calendar/img/previous.png`. AFAIK, Webpack can't resolve images dynamically @2x or @3x like React Native can - currently the default is set at `next@2x.png` and `previous@2x.png`.

Looks like someone opened up a similar issue w/ Webpack, but it was never resolved (https://github.com/webpack/webpack/issues/3516). I'm going to follow up with Webpack to see if we can get some more info.

**Comment by tautvilas** [comment]
I will try adding asset versions without `@` maybe they will be interpreted the same way as `@1x`

**Comment by peggyrayzis** [comment]
Yeah, that's definitely a good solution for the short term. I think this may be a broader issue beyond this project - ideally, we would like our Webpack config to be able to resolve image paths to the appropriate scale just like in React Native. I know it's possible because [Haul](https://github.com/callstack-io/haul) does it. It's probably going to take a custom resolver though.

Once we have this all figured out, would you like me to add a section to the README on how to integrate with `react-native-web`?

**Comment by tautvilas** [comment]
hey tried adding images without extension. Check if it works. If we manage to get it working with react-native-web you can prepare WEB-HOWTO.md file in pull request and I will merge it to readme or add a link to it in main readme.

**Comment by peggyrayzis** [comment]
Thanks for making that change! The build runs without errors and the calendar renders! 🎉 Only problem now is that the arrows don't show up because `tintColor` (how the arrow images are filled) is a React Native only property with no plans to be supported in RNW in the future (https://github.com/necolas/react-native-web/issues/362). 😭 

Idk the best way to work around this. Changing the arrow to a SVG isn't an ideal solution because it introduces native dependencies into the project. Same with an icon library. The only thing I can think of to keep this pure JS is to have the header accept a prop for left & right arrow components that can override the default `arrowImage` for web users. What do you think?

**Comment by tautvilas** [comment]
I see that I can identify the web platform by `Platform.OS === 'web'`. This way I will be able to add style exception that tint would not be applied in case of web. Will update you when it's done

**Comment by peggyrayzis** [comment]
Awesome, thanks for being so accommodating! ❤️

**Comment by tautvilas** [comment]
Added `tintColor` ignore for web platform, check if that works out for you

**Comment by tautvilas** [comment]
Hi! Thanks for PR it is really nice to see this component working on web too. I will look at your PR when I have time, does not look like there should be problems to merge it. Just since we are not using react-native-web it is possible that one day we will again introduce something non-compatible. Also what do you think of chanching `leftArro` `rightArrow` params to single param `renderArrow` that gets rendering function as param. Because we have similar convention for other components override e.g. `renderKnob`

```javascript
function renderArrow(direction) {
   if (direction === 'left') { return (<LeftArrow />) } else return (<RightArrow />);
}```

**Comment by kkemple** [comment]
yeah i love the method over two props, will update now!

**Comment by kkemple** [comment]
i updated the PR, however the import syntax change is breaking the build, i imagine its missing a babel plugin for that, i will investigate in a bit.

**Comment by kkemple** [comment]
> Just since we are not using react-native-web it is possible that one day we will again introduce something non-compatible. 

We understand that and would be monitoring and adding support as needed. We are looking to use this across a number of UIs so we have no problem investing some help. :smile:

**Comment by tautvilas** [comment]
Ok, merged the PR and closing this issue for now, plz create new issues if you notice something wrong with RN-web compatibility.

**Comment by kkemple** [comment]
Will do! Thanks so much!

**Comment by necolas** [comment]
FWIW, `tintColor` will be supported in `react-native-web@0.8.0`

**Comment by kopax-polyconseil** [comment]
Does this work with react native web out of the box ?
