### ISSUE TITLE
Can't change the flatlist backgroundColor of Agenda with calendarBackground in theme

### ISSUE THREAD

**Issue by Jinho1011** [wix/react-native-calendars#2000]
## Description
- `renderCalendarList` in agenda does not pass theme to CalendarList, because `extractCalendarListProps` does not extract theme from props. Due to this problem, even though calendarBackground is set, the backgroundColor of CalendarList inside Agenda cannot be changed.

## Expected Behavior
- extractCalendarListProps should extract theme from props.

**Comment by kyleder** [comment]
I'm seeing this same behavior after upgrading to RN 0.68.2 (was previously on 0.61.5).

**Comment by Jinho1011** [comment]
downgrade to 1.1286.0 fixed this

**Comment by JSimai** [comment]
> 

I'm using RN 0.64.3, and downgrading to version 1.1286.0 of react-native-calendars didn't fix the issue for me. The latest version of RNC also broke other theme attributes. With this setup, just the background colour isn't working.
![Screen Shot 2022-08-25 at 7 32 42 pm](https://user-images.githubusercontent.com/67139031/186629878-15cd8522-0b6e-40d2-b1c0-220b2c5f29f6.png)

**Comment by tsalama** [comment]
Same issue here after updating to RN 0.68. Also the CalendarList theme isn't honored.

**Comment by dpdenton** [comment]
Looking at https://github.com/wix/react-native-calendars/blob/master/src/agenda/style.ts#L56 adding the below worked for me (the    

```
<Agenda
    theme={{
      'stylesheet.agenda.main': {
        reservations: {
          backgroundColor: 'red',
        },
      }}
     ...
 />
```

**Comment by wallacerenan** [comment]
```jsx
<Agenda
        showClosingKnob
        renderItem={RenderItem}
        items={{
          '2022-11-28': [
            {
              name: 'Renan',
              day: new Date().toISOString().split('T')[0],
              height: 50,
            },
          ],
        }}
        theme={{
          reservationsBackgroundColor: '#fff',
        }}
      />
```

reservationsBackgroundColor is not typed, use this.

**Comment by pridemusvaire** [comment]
I have posted a PR for this , [PR here](https://github.com/wix/react-native-calendars/pull/2411)
