### ISSUE TITLE
How to style Timeline event card?

### ISSUE THREAD

**Issue by syahirdev** [wix/react-native-calendars#2014]
How can I implement style to the event card, like the background color or text color of the content itself? For now, I'm limited to only being able to change the background color set on the TimelineList events.

For example, color: "#dbeafe"
```
let eventMap = activities.map((activity) => ( {
        id: activity._id,
        start: activity.plannedFrom,
        end: activity.plannedTo,
        title: activity.customer,
        summary: activity.customType,
        color: "#dbeafe"
      } ));
      setEvents(groupBy(eventMap, e => CalendarUtils.getCalendarDateString(e.start)));
```
![image](https://user-images.githubusercontent.com/67471898/187897739-0c0e1e7c-b151-41a5-b2cc-1014eb217ff2.png)

**Comment by ciaoamigoschat** [comment]
news?

**Comment by devphilipcesar** [comment]
any news on this?

**Comment by jerone** [comment]
Looks possible with this [undocumented](https://github.com/wix/react-native-calendars/issues/2145) property: https://github.com/wix/react-native-calendars/blob/da9b1bd702e1221002d6e30aaf888e350b627b6a/src/timeline-list/index.tsx#L35

Haven't tried it yet. Maybe someone can confirm.

**Comment by PierreBertholom** [comment]
You can customize the appearance of event cards in the TimelineList by defining a custom style and passing it to the timelineProps. Here's an example:
```js
const customEventStyles = {
  eventTitle: {
    color: 'red',
    fontSize: 16,
    fontWeight: 'bold',
  },
  eventSummary: {
    fontSize: 14, 
    color: 'black',
  },
  eventTimes: {
    fontSize: 14,
    color: 'gray',
  },
};
```
And then pass it in your timelineprops:
```js
  const timelineProps = {
    format24h: true,
    start: 0,
    end: 24,
    unavailableHours: [
      { start: 0, end: 6 },
      { start: 22, end: 24 },
    ],
    overlapEventsSpacing: 8,
    rightEdgeSpacing: 24,
    onEventPress: handleEventPress,
    styles: customEventStyles,
  };
```
As for the color of the event you can use the color property in your TimelineEventProps[].

You can find more details on the event block [here](https://github.com/wix/react-native-calendars/blob/da9b1bd702e1221002d6e30aaf888e350b627b6a/src/timeline/EventBlock.tsx)
