### ISSUE TITLE
Agenda not rendering marks and custom colors

### ISSUE THREAD

**Issue by andrelramos** [wix/react-native-calendars#2017]
## Description

Marks and custom colors not rendering in last release version ([1.1288.2](https://github.com/wix/react-native-calendars/releases/tag/1.1288.2)).

The last version working with custom colors was [1.1287.0](https://github.com/wix/react-native-calendars/releases/tag/v1.1287) and working with marks was [1.1285.0](https://github.com/wix/react-native-calendars/releases/tag/v1.1285.0).

## Expected Behavior

Show day marks on Agenda's calendar and custom color for today and selected day

## Observed Behavior

The Agenda is ignoring these parameters and rendering like default Agenda

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.1288.2
* `npm ls react-native`: react-native@0.64.3
* `npm ls expo`:expo@44.0.6

Also specify:

1. Device/emulator/simulator & OS version: iPhone 8 Plus emulator (iOS 15.5)

## Reproducible Demo

Code to reproduce:
```
<Agenda 
        items={{
          "2022-09-06": [
            {
              "day": "2022-09-06",
              "height": 75,
              "name": "2661",
            },
          ]
        }}
        markingType={"multi-dot"}
        markedDates={{
          "2022-09-06": {
            "dots": [
              {
                "color": "grey",
                "key": "Waiting",
              },
              {
                "color": "green",
                "key": "Confirmed",
              }
            ]
          }
        }}
        theme={{
          selectedDayBackgroundColor: Colors.purple,
          todayTextColor: Colors.purple,
        }}
        loadItemsForMonth={loadItems}
        renderItem={renderItem}
        renderEmptyDate={() => <NothingToShowText>Nenhum agendamento disponível</NothingToShowText>}
      />
``` 

## Screenshots

The code above using version [1.1285.0](https://github.com/wix/react-native-calendars/releases/tag/v1.1285.0): 

https://user-images.githubusercontent.com/10236206/188246927-045354c9-3020-4d7e-a82c-f0d912ff0c68.mov

Using version [1.1288.2](https://github.com/wix/react-native-calendars/releases/tag/1.1288.2):

https://user-images.githubusercontent.com/10236206/188246991-bd28accd-1c52-4098-a42a-a16c3c0de04f.mov

**Comment by Saikedo** [comment]
Facing the same issue. I used to provide a theme to agenda like this

```
const agendaTheme: Theme = useMemo(() => {
        return {
            calendarBackground: COLORS.darkPurple,
            backgroundColor: COLORS.black,
            monthTextColor: COLORS.white,
            textDayFontFamily: FONT_STYLES.Poppins_500,
            textDisabledColor: applyTransparency('#7D6D83', 0.4),
            dayTextColor: applyTransparency(COLORS.lighterGray, 0.6),
            selectedDayTextColor: COLORS.white,
            todayTextColor: COLORS.calendarTodayColor,
        };
    }, []);
```

And now, almost none of the colors are being applied.

I also had `markingType={'custom'}` and then I was providing `markedDates` and it seems like that one has no effect on latest version either.

**Comment by andrelramos** [comment]
related issues 

https://github.com/wix/react-native-calendars/issues/1993
https://github.com/wix/react-native-calendars/issues/1959

**Comment by Saikedo** [comment]
Are there any plans to fix this ? Agenda styles are still broken.
