### ISSUE TITLE
How to change date locale to shamsi/persian 

### ISSUE THREAD

**Issue by 1mehdifaraji** [wix/react-native-calendars#2025]
## Description

Right now the calendar date timezone locale is gregorian , but I want to change timezone to locale to middle east country date locale like turkey or iran .

## Expected Behavior

I provided ```fa``` which is locale for farsi/persian iranian shamsi calendar according to [List of locale names](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) like this :

```
import { LocaleConfig } from "react-native-calendars";

LocaleConfig.locales["fa"] = {
  monthNames: [
    "فروردین",
    "اردیبهشت",
    "خرداد",
    "تیر",
    "مرداد",
    "شهریور",
    "مهر",
    "آبان",
    "آذر",
    "دی",
    "بهمن",
    "اسفند",
  ],
  monthNamesShort: [
    "فروردین",
    "اردیبهشت",
    "خرداد",
    "تیر",
    "مرداد",
    "شهریور",
    "مهر",
    "آبان",
    "آذر",
    "دی",
    "بهمن",
    "اسفند",
  ],
  dayNames: [
    "شنبه",
    "یکشنبه",
    "دوشنبه",
    "سه شنبه",
    "چهارشنبه",
    "پنجشنبه",
    "جمعه",
  ],
  dayNamesShort: [
    "شنبه",
    "یکشنبه",
    "دوشنبه",
    "سه شنبه",
    "چهارشنبه",
    "پنجشنبه",
    "جمعه",
  ],
  today: "شنبه",
};
LocaleConfig.defaultLocale = "fa";
```

## Observed Behavior

<img width="390" alt="Screen Shot 1401-06-17 at 20 20 50" src="https://user-images.githubusercontent.com/63982703/189167904-27adc983-a624-4ecb-a6d9-1514b8703958.png">

But timezone doesn't change . Basically I want the calendar format to be persian like this : 

<img width="197" alt="Screen Shot 1401-06-17 at 20 09 12" src="https://user-images.githubusercontent.com/63982703/189165426-d940638c-d923-413a-96e0-42b5265c1f26.png">

<img width="237" alt="Screen Shot 1401-06-17 at 20 10 09" src="https://user-images.githubusercontent.com/63982703/189165569-e5082fb0-e84a-413e-affb-1f3e3255ba06.png">

**Comment by farzanm14** [comment]
Could you let me know if you found any proper solution?  @1mehdifaraji

**Comment by 1mehdifaraji** [comment]
@farzanm14 I couldn't find a way to fix the problem. Issue still exists.
