### ISSUE TITLE
 in Agenda firstDay is not propagated to CalendarList

### ISSUE THREAD

**Issue by linaia** [wix/react-native-calendars#2029]
## Description

We noticed that the header and Calendar are not in sync when firstDay is set to 1 (start on Monday)

![Capture d’écran 2022-09-15 à 16 58 27](https://user-images.githubusercontent.com/56269035/190438273-f072bbe3-79ed-4259-b784-b779fa7907a7.png)

When you scroll down, it starts on Sunday : 

![Capture d’écran 2022-09-15 à 17 00 10](https://user-images.githubusercontent.com/56269035/190438309-1965f900-89d5-4d4e-82dd-025da2b15c2e.png)

## Expected Behavior

Same firstDay should be displayed.

## Observed Behavior

Looking into agenda code, we can see that calendarListProps is empty despite firstDay is available in props

````
renderCalendarList() {
        const { markedDates, items } = this.props;
        const shouldHideExtraDays = this.state.calendarScrollable ? this.props.hideExtraDays : false;
        const calendarListProps = extractComponentProps(CalendarList, this.props);
        console.log("DEBUG calendarListProps", calendarListProps, this.props);
        return (<CalendarList {...calendarListProps} ref={this.calendar} current={getCalendarDateString(this.currentMonth.toString())} markedDates={this.generateMarkings(this.state.selectedDay, markedDates, items)} calendarWidth={this.viewWidth} scrollEnabled={this.state.calendarScrollable} hideExtraDays={shouldHideExtraDays} onLayout={this.onCalendarListLayout} onDayPress={this.onDayPress} onVisibleMonthsChange={this.onVisibleMonthsChange}/>);
    }
````

````
DEBUG calendarListProps {} {"firstDay": 1, "items": ....
````

If we force the props firstDay, it works fine

````
return (<CalendarList {...calendarListProps} firstDay={this.props.firstDay} 
````

So the problem is in extractComponentProps or in CalendarList props.... :  

`````
export function extractComponentProps(component, props, ignoreProps) {
    const componentPropTypes = component.propTypes;
    console.log("DEBUG componentPropTypes", componentPropTypes, props);    
`````

Result : no firstDay in componentPropTypes
````
DEBUG componentPropTypes {"date": [Function bound checkType], "item": [Function bound checkType], "renderDay": [Function bound checkType], "renderEmptyDate": [Function bound checkType], "renderItem": [Function bound checkType], "rowHasChanged": [Function bound checkType], "theme": [Function bound checkType]}
 {"items": ....
````

Why ?  we can see that the extends on props of CalendarList seems not working well ....

````
export interface CalendarListProps extends CalendarProps
````

As firstDay in visible in CalendarProps but not in CalendarListProps 

````
export interface CalendarProps extends CalendarHeaderProps, DayProps {
    /** Specify theme properties to override specific styles for calendar parts */
    theme?: Theme;
    /** If firstDay=1 week starts from Monday. Note that dayNames and dayNamesShort should still start from Sunday */
    firstDay?: number;
`````

Question : does "component.propTypes" get the propTypes defined in interface or get the old way of propTypes in a Component (https://reactjs.org/docs/typechecking-with-proptypes.html) ?

Now it is your turn .... @yuvalsho can you please have a look ?

## Environment

"expo": "^46.0.10",
"react-native": "0.69.5",
"react-native-calendars": "^1.1288.3",

**Comment by Inbal-Tish** [comment]
@linaia Hi. Thank you for reporting the issue. This issue was already fixed. Please update Calendar verstion

**Comment by igorschlum** [comment]
@linaia , could you test and close the issu if it is fixed? Best
