### ISSUE TITLE
RTL Bug

### ISSUE THREAD

**Issue by elie-chaaban** [wix/react-native-calendars#2031]
## Description

When I switch to RTL, the period marking is not working

## Expected Behavior

The Radius should be inverted 

![WhatsApp Image 2022-09-17 at 9 40 22 AM](https://user-images.githubusercontent.com/29852821/190844203-55c9a92e-70bd-48cb-bd7a-2490a295e234.jpeg)

**Comment by imdkbj** [comment]
Hi Can u pls share the complete code so that i may able to assist you.

**Comment by elie-chaaban** [comment]
There s no specific issue, only the selection is not inverted when rtl

**Comment by imdkbj** [comment]
> There s no specific issue, only the selection is not inverted when rtl

Ya, I understand your issue. Well ,working for me so that i asked if u will able to share then i might be able to fix that.

**Comment by elie-chaaban** [comment]
Can you share how did you do it?

**Comment by elie-chaaban** [comment]
const calendarTheme = {
    overflow: "visible",
    textMonthFontFamily: Fonts.semiBold,
    monthTextColor: theme.base,
    textDisabledColor: theme.lightGrey,
    todayTextColor: theme.base,
    "stylesheet.calendar.main": {
      week: {
        marginTop: 7,
        marginBottom: 7,
        flexDirection: i18n.isRTL ? "row-reverse" : "row",
        justifyContent: "space-around",
      },
    },
    "stylesheet.calendar-list.main": {
      staticHeader: {
        paddingHorizontal: 0,
      },
      calendar: {
        paddingLeft: 0,
        paddingRight: 0,
      },
    },
    "stylesheet.calendar.header": {
      header: {
        flexDirection: i18n.isRTL ? "row-reverse" : "row",
        justifyContent: "space-between",
        alignItems: "center",
        height: 45,
        backgroundColor: theme.backgroundColor,
        color: theme.base,
      },
      week: {
        marginTop: 0,
        flexDirection: i18n.isRTL ? "row-reverse" : "row",
        justifyContent: "space-around",
        backgroundColor: theme.backgroundColor,
      },
      dayHeader: {
        fontSize: 12,
        color: theme.darkGrey,
        textTransform: "uppercase",
      },
    },
  };

**Comment by elie-chaaban** [comment]
<CalendarList
      markingType='period'
      current={fromDate}
      pastScrollRange={2}
      futureScrollRange={4}
      markedDates={selectedDays}
      onDayPress={onDayPress}
      theme={calendarTheme}
    />

**Comment by imdkbj** [comment]
> selectedDays

I asked to complete code, pardon me if not interested (selectedDays is must required)

**Comment by elie-chaaban** [comment]
const setupStartMarker = (day) => {
    let markedDates = {
      [day.dateString]: {
        startingDay: true,
        endingDay: true,
        color: markColor,
        textColor: markTextColor,
      },
    };
    setFromDateSelected(true);
    setToDateSelected(false);
    setFromDate(day.dateString);
    setSelectedDays(markedDates);
  };

**Comment by elie-chaaban** [comment]
const setupMarkedDates = (pFromDate, pToDate, markedDates) => {
    let mFromDate = new moment(pFromDate, "YYYY-MM-DD").locale("en");
    let mToDate = new moment(pToDate, "YYYY-MM-DD").locale("en");

    let range = mToDate.diff(mFromDate, "days");
    if (range >= 0) {
      if (range == 0) {
        markedDates = {
          [pToDate]: {
            startingDay: true,
            endingDay: true,
            color: markColor,
            textColor: markTextColor,
          },
        };
      } else {
        for (var i = 0; i < range; i++) {
          let tempDate = mFromDate.add(24, "hours").format("yyyy-MM-DD");
          markedDates[fromDate] = {
            ...markedDates[fromDate],
            endingDay: false,
            color: markColor,
            textColor: markTextColor,
          };
          if (i < range - 1) {
            markedDates[tempDate] = {
              color: theme.lighter,
              textColor: markTextColor,
            };
          } else {
            markedDates[tempDate] = {
              endingDay: true,
              color: markColor,
              textColor: markTextColor,
              customContainerStyle: {
                alignItems: "flex-start",
              },
            };
          }
        }
      }
    }
    return [markedDates, range];
  };

**Comment by elie-chaaban** [comment]
const onDayPress = (day) => {
    if (!fromDateSelected || (fromDateSelected && toDateSelected)) {
      setupStartMarker(day);
      if (onFail) onFail();
    } else if (!toDateSelected) {
      let markedDates = Object.assign({}, selectedDays);
      let [mMarkedDates, range] = setupMarkedDates(
        fromDate,
        day.dateString,
        markedDates
      );
      if (range >= 0) {
        setSelectedDays(mMarkedDates);
        setFromDateSelected(true);
        setToDateSelected(true);
        if (onSuccess) onSuccess(fromDate, day.dateString);
      } else {
        setupStartMarker(day);
        if (onFail) onFail();
      }
    }
  };

  const setupInitialRange = () => {
    if (!initialRange) return;
    let [fromDate, toDate] = initialRange;
    let markedDates = {
      [fromDate]: {
        startingDay: true,
        color: markColor,
        textColor: markTextColor,
      },
    };
    let [mMarkedDates, range] = setupMarkedDates(fromDate, toDate, markedDates);
    setSelectedDays(mMarkedDates);
    setFromDate(fromDate);
  };


  useEffect(() => {
    setupInitialRange();
  }, []);

**Comment by elie-chaaban** [comment]
it is already being filled, otherwise we do not see the selection, all i am asking is to invert the radius. selection is all good

**Comment by imdkbj** [comment]
Pls always format codes so that it will be readable and share code all in once (or some codesandbox link) not like text message. 

U can make below changed and check

```js
const formatDate = (dt) => moment(dt).locale('en').format("YYYY-MM-DD")
const holidayPeriodColor = "green"
const _today = moment()
const _selected = { start: formatDate(_today.add(1, "days")), end: formatDate(_today.add(1, "days")), leave_days: 2 }


const [selectedDates, setSelectedDates] = useState(_selected)
```


```js
const generateDaysBetween = () => {
    if (!(selectedDates.start && selectedDates?.end)) return null
    let dates = {}
    let dt = moment(selectedDates.start)
    while (dt < moment(selectedDates.end)) {
        dates[formatDate(dt)] = {
            color: holidayPeriodColor
        }
        dt.add(1, "days")
    }
    return dates
}
```

```js
const markedDates = useMemo(() => {
    if (selectedDates?.start && selectedDates.start === selectedDates.end) {
        return {
            [selectedDates.start]: {
                color: 'rgb(255,193,7)',
                startingDay: true,
                endingDay: true,
                selection: true,
                customContainerStyle: {
                    borderRadius: 10
                }
            }
        }
    }

    return {
        ...generateDaysBetween(),
        [selectedDates.start]: {
            color: 'rgb(255,193,7)',
            startingDay: true,
            selection: true,
            customContainerStyle: {
                borderRadius: 10
            }
        },
        [selectedDates.end]: {
            color: 'rgb(255,193,7)',
            endingDay: true,
            selection: true,
            customContainerStyle: {
                borderRadius: 10
            }
        },
    }
}, [selectedDates])

```

```js
 const handleDayPress = ({ dateString }) => {
        if (selectedDates.start && !selectedDates.end) {
            const start = Math.min(new Date(dateString), new Date(selectedDates.start))
            const end = Math.max(new Date(dateString), new Date(selectedDates.start))
            setSelectedDates({
                start: formatDate(start),
                end: formatDate(end),
                leave_days: moment(end).diff(moment(start), "days") + 1
            })
        } else {
            setSelectedDates({ start: dateString })
        }
    }
```

add below to theme
``` js
'stylesheet.day.basic': {
    selected: {
        backgroundColor: holidayPeriodColor,
        borderRadius: 10
    }
}
```

**Comment by elie-chaaban** [comment]
I will check and get back to you, thanks

**Comment by igorschlum** [comment]
@elie-chaaban I would be interested to know if the issu is fixed too.
