### ISSUE TITLE
March 26, 2023 select bug

### ISSUE THREAD

**Issue by AliAzzam91** [wix/react-native-calendars#2034]
## Description

I'm facing a problem with selecting the date March 26, 2023 in the calendar. It wasn't fixed in version 1.1289.0, now instead of March 26, it shows March 25.

## Expected Behavior

March 26, 2023 should be selected when pressed.

## Observed Behavior

March 25, 2023 is selected instead when selecting March 26, 2023

## Environment

* `npm ls react-native-calendars`: 1.1289.0
* `npm ls react-native`: 0.66.4

Also specify:

Android emulator

## Screenshots

![Screenshot_1663591975](https://user-images.githubusercontent.com/97559252/191024714-31e6ac02-cfd8-475f-9758-f5aebdd12748.png)

**Comment by 0had0** [comment]
@AliAzzam91 hello have you solved this?
