### ISSUE TITLE
Change date color in Agenda items

### ISSUE THREAD

**Issue by codefromrvk** [wix/react-native-calendars#2039]
## Description

I am not able  to change the default date color in the agenda items. I want to change the marked date in the image.

I could not find the CSS property to change the date color.

## Environment
 React native 0.69

![image](https://user-images.githubusercontent.com/72021268/191765103-810e3df9-6d3c-43a9-9191-c04dad77f6ad.png)

**Comment by codefromrvk** [comment]
Tried using ``` agendaDayTextColor: 'gray',
            agendaDayNumColor: 'gray',
            agendaTodayColor: 'gray',```. Neither of them worked

**Comment by haider260** [comment]
Any update on this?

**Comment by codefromrvk** [comment]
> Any update on this?

Ended up using   ` renderDay={(day, item) => ( )}` . Changed only day using this and kept the item as it is.

**Comment by rabiaah** [comment]
I'm facing the same issue in the new library  "node_modules/react-native-calendars": {
      "version": "1.1289.0",

**The only place I've found this color is in:**

node_modules/react-native-calendars/src/style.js

export const textLinkColor = '#00BBF2';

![image](https://user-images.githubusercontent.com/21026029/193418103-c5b9ddf6-ca2f-4bd4-8dbb-adf2b3c82c94.png)

Then it been used in the below places in same file:

export const todayTextColor = textLinkColor;
export const agendaTodayColor = textLinkColor;
export const todayButtonTextColor = textLinkColor;

But even trying to change in the Agenda of my class, it keeps loading the blue color.

**Comment by rabiaah** [comment]
**Temporary fix is as below:**

![image](https://user-images.githubusercontent.com/21026029/193419698-fe339658-be59-4cf9-98a4-c7b363df0e4a.png)

Add "theme" in line 110 and line 131 as showed in the above screenshot.
