### ISSUE TITLE
Azerbaijan has invaded Armenia

### ISSUE THREAD

**Issue by AlbertArakelyan** [wix/react-native-calendars#2040]
## Description

All the world stands with Ukraine, the same is going on in Armenia Azerbaijan killed hundreds of soldiers and civilians in 3 days, bombed 3 cities and one of them is a resort city Jermuk. Azarbaijan keeps us under tension after the latest war and keeps killing and invading our soverign territory.

## Expected Behavior

The world will see this injustice and maybe will come with loud annoucements (I hope)

## Observed Behavior

Actually I don't expect something big from the world, but at least it will be in front of other people eyes.

## Environment

Only environment is humanity.

**Comment by GuvenEREN-404** [comment]
How quickly do you forget what you did in 1994?
Also this is irrelevant

**Comment by aligoren** [comment]
Did aliens commit the Khojaly massacre in 1992? Armenia has occupied Azerbaijani lands. The world does not care about Armenia or Azerbaijan.

The world is using you like a toy such as Azerbaijan. You are too stupid to understand that. Do you think your own country is the most innocent country in the world? Is Azerbaijan arbitrarily attacking? If the Armenian army had not attacked Azerbaijanthanks to the USA, there would never have been a war.

I'm sorry, but Pelosi's fake tears won't save you. They don't want.
