### ISSUE TITLE
Scrolling causes spinner to spin infinitely in the Agenda component

### ISSUE THREAD

**Issue by efkan** [wix/react-native-calendars#2044]
## Description

Sometimes the Agenda component's spinner spins non-stop. To clarify, I added only 3 days to Agenda and the issue re-occurred. 

## Expected Behavior

After showing the spinner for a short while, the spinner should be stopped.

## Observed Behavior

I added a short video to demo the issue:

https://user-images.githubusercontent.com/6974198/192284370-4ea3fe80-0698-4ea3-8f7d-8254ffa8d747.mov

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1284.0
* `npm ls react-native`: react-native@0.69.3

Also, specify:

1. Device/emulator/simulator & OS version:  real iPhone XS (iOS 15.7.0) / iPhone 11 (iOS 16.0) (real device & simulator) / iPhone 14 Pro Max (iOS 16.0) simulator 

## Reproducible Demo

It causes an issue on Expo simulators as well:
 
https://snack.expo.dev/@efkan/hazardous-donut?platform=ios

```Javascript
import React, {Component} from 'react';
import {Agenda, DateData, AgendaSchedule} from 'react-native-calendars';
import moment from 'moment';

interface State {
  items?: AgendaSchedule;
}

const dayCount = 30;
const minDate = moment().format('YYYY-MM-DD');
const maxDate = moment().add(dayCount, 'days').format('YYYY-MM-DD');

export default class AgendaScreen extends Component<State> {
  state: State = {
    items: undefined
  };

  render() {
    return (
      <Agenda
            items={this.state.items}
            markingType={'custom'}
            loadItemsForMonth={this.loadItems}
            rowHasChanged={(r1: any, r2: any) => r1.id !== r2.id && r1.startTime !== r2.startTime}
            firstDay={1}
            refreshing={false}
            showScrollIndicator={true}
          />
    );
  }

  loadItems = (day: DateData) => {
    const agendaItems = {};
    const oneDayInMS = 60 * 60 * 1000;

    for (let i = 0; i < 3; i++) {
      const time = day.timestamp + i * 24 * oneDayInMS;
      const agendaDate = new Date(time).toISOString().split('T')[0];
      
      agendaItems[agendaDate] = [];  
    }

    this.setState({
      items: agendaItems
    });
  }
}
```

**Comment by macasfaj** [comment]
@efkan one question, how did you set background colors in markers list? Not calendar, I mean the list of appointments. Thanks!
