### ISSUE TITLE
Colors mixing when using alpha/transparency 

### ISSUE THREAD

**Issue by Rafael-Ramblas** [wix/react-native-calendars#205]
## Description

In Calendar markingType set to interactive, i cant use colors with alpha in the edges (startingDay and endingDay) because the colors stand on top of each other and makes a darker color that i want. The dates between the edges are afected too.

## Expected Behavior

![captura de tela de 2017-10-16 20-09-46](https://user-images.githubusercontent.com/19700568/31637561-ff9af080-b2ad-11e7-8db4-7a69929fa012.png)

## Observed Behavior

![captura de tela de 2017-10-16 19-53-00](https://user-images.githubusercontent.com/19700568/31637517-d66e70ec-b2ad-11e7-98c9-8004d0655a0d.png)

It's something related to the fillers in src / calendar / interactive / index.js.
Their styles are overlapping causing the issue. Stuck in here, i tried many things in the file, but without sucess.

Phone/emulator/simulator & version: Android Studio AVD API 26

**Comment by tautvilas** [comment]
hi, sorry but currently this is the way day coloring is implemented, there is no easy way to have transparent color

**Comment by Rafael-Ramblas** [comment]
Ok, i'm gonna see if i can solve the problem. Great lib btw and thx for the project.
