### ISSUE TITLE
Selected Date Background Color

### ISSUE THREAD

**Issue by NajeebUllah161** [wix/react-native-calendars#2052]
Selected Date doesn't have a background color on iPhone 10x.

I didn't try on other iphones but i guess this is general issue with iOS side,
Kindly see this.

**Comment by Bushuo** [comment]
I guess this works as expected.
The days do not get selected by press automatically.

To achieve that functionality I added this code
```tsx
const [selectedDay, setSelectedDay] = React.useState(new Date().toISOString().slice(0, 10))

return <Calendar
  markedDates={{
    [selectedDay]: { selected: true },
  }}
  onDayPress={(day) => {
    setSelectedDay(day.dateString)
  }}
/>
```

**Comment by harika-nammi** [comment]
Hi @Bushuo, 
I am using state variable for selected day. When I select date in previous month or next month the calendar goes back to present month again. If i am using the state variable getting this issue. 

My code:-
```
const [selectedDate, setSelectedDate] = useState("");
return(
  <Calendar
                initialDate={moment(new Date()).format()}
                onDayPress={day => {
                    setSelectedDate(day.dateString)
                }}
                markedDates={{
                    [selectedDate]: { selected: true, selectedColor: "yellow", selectedTextColor: "black" },
                }}>
)
```

Screenshot:-


https://user-images.githubusercontent.com/113165469/195515207-25b2b6a1-aeab-4f0a-967d-a46c46849cf9.mov

**Comment by harika-nammi** [comment]
Sorry, i will remove the initialDate prop. Now it's working fine for me.
