### ISSUE TITLE
when add hideExtraDays prop to hide next month days but next month in not show hideble data .

### ISSUE THREAD

**Issue by Gaurang-786** [wix/react-native-calendars#2054]
## Description

when add hideExtraDays prop to hide next month days but next month in not show hideble data .

## Expected Behavior

i will hideExtraDays and next moth will be start on first date of the month

## Observed Behavior

example :
i have octobar month last week date is  31 , 1 ,2,3,4,5,6, so in there hide 1 to  date.

but next november month is start with 1 date but its start on 7 date 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Device/emulator/simulator & OS version:

## Reproducible Demo

<CalendarProvider
            date={today}
            onDateChanged={(val, item) => onDateChanged(val, item)}
            showTodayButton

            todayButtonStyle={{height: wp(10)}}
            disabledOpacity={0.6}
            theme={{todayButtonTextColor: colors.blue}}>
            <ExpandableCalendar
              allowShadow={true}
              minDate={today}
              allowSelectionOutOfRange={false}
              firstDay={1}
              pastScrollRange={50}
              futureScrollRange={50}
              calendarStyle={styles.calendar}
              theme={getTheme()}
              hideExtraDays={true}

              onDayPress={(val, item) => onDayChange(val, 'day')}
              // disableAllTouchEventsForDisabledDays
              markedDates={MarkedData}
              markingType={'dot'}
            />
</CalendarProvider>

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.
![Screenshot 2022-10-03 at 12 33 00 PM](https://user-images.githubusercontent.com/98010969/193519563-22e7dd3c-4ef7-4a77-951d-22637ab9005a.png)

![Screenshot 2022-10-03 at 12 33 09 PM](https://user-images.githubusercontent.com/98010969/193519574-8336ba26-1f0f-49b2-9dd9-b8155fdc7342.png)

**Comment by soniaalabed** [comment]
@Gaurang-786 were you able to find a solution?
