### ISSUE TITLE
The very first render of CalendarList

### ISSUE THREAD

**Issue by andreyxdd** [wix/react-native-calendars#2059]
## Description

The very first render of CalendarList is a datestring (today's date). Looking at the implementation of CalendarList, I do not really see why this string appears first. So what parameters allow avoiding it?

## Expected Behavior

Some kind of loader (or nothing) is expected before the calendar shows up.

## Observed Behavior

In the clip below, you can note that the date string appears first (when the bottom sheet is opened) and only then the calendar appears.

## Environment

* `npm ls react-native-calendars`:
red-green@1.0.0 C:\Users\andre\Documents\Web-projects\red-green-mobile\red-green 
`-- react-native-calendars@1.1289.0 

* `npm ls react-native`:
red-green@1.0.0 C:\Users\andre\Documents\Web-projects\red-green-mobile\red-green
`-- react-native@0.64.3

Device/emulator/simulator & OS version: iOS Expo Simulator, Expo ~44.0.0

## Reproducible Demo

Code:
```
import { add, eachDayOfInterval, format } from 'date-fns';
import React from 'react';
import { CalendarList, CalendarProps } from 'react-native-calendars';
import { RFValue } from 'react-native-responsive-fontsize';
import colors from '../../../styles/colors';
import layout from '../../../utils/layout';
import { formatDate as formatUTC } from '../../../utils';

// ---
const MIN_PLAN_DURATION = 7; // in days
const MAX_PLAN_DURATION = MIN_PLAN_DURATION * 6; // in days

const getMinDate = (startDate?: number, endDate?: number) => {
  if (startDate && endDate) return format(add(new Date(), { years: 4 }), 'yyyy-M-dd'); // so it's invisible

  if (startDate) return format(add(startDate, { days: MIN_PLAN_DURATION + 1 }), 'yyyy-M-dd');

  return format(new Date(), 'yyyy-M-dd');
};

const getMaxDate = (startDate?: number) => {
  if (startDate) return format(add(new Date(), { days: MAX_PLAN_DURATION + 1 }), 'yyyy-M-dd');

  return format(add(new Date(), { years: 5 }), 'yyyy-M-dd'); // so it's invisible
};
// --

const calendarTheme = {
  monthTextColor: colors.blue.primary,
  dayTextColor: colors.blue.primary,
  textMonthFontSize: RFValue(16, layout.window.height),
  selectedDayTextColor: colors.grey.primary,
};

type IMarkedDates = CalendarProps['markedDates'];

export type IDatesPicker = {
  startDate?: number;
  setStartDate: React.Dispatch<React.SetStateAction<number | undefined>>;
  endDate?: number;
  setEndDate: React.Dispatch<React.SetStateAction<number | undefined>>;
}

function DatesPicker({
  startDate, setStartDate, endDate, setEndDate,
}: IDatesPicker ) {
  const markedDates = React.useMemo(() => {
    const todayMark = { [format(new Date(), 'yyyy-M-dd')]: { disabled: true } };

    if (startDate && endDate) {
      const newMarkedDates: IMarkedDates = {
        [formatUTC(startDate, 'yyyy-M-dd')]: { startingDay: true, color: colors.GREEN.primary },
        [formatUTC(endDate, 'yyyy-M-dd')]: { endingDay: true, color: colors.GREEN.primary },
      };

      eachDayOfInterval({
        start: add(startDate, { days: 2 }),
        end: endDate,
      })
        .forEach((d) => {
          const key = formatUTC(d, 'yyyy-M-dd');
          newMarkedDates[key] = { selected: true, color: colors.grey.light };
        });

      return { ...newMarkedDates, ...todayMark };
    }

    return todayMark;
  }, [startDate, endDate]);

  return (
    <CalendarList
      onDayPress={(day) => {
        if (!startDate) setStartDate(day.timestamp);
        if (startDate && !endDate) setEndDate(day.timestamp);
      }}
      theme={calendarTheme}
      minDate={getMinDate(startDate, endDate)}
      maxDate={getMaxDate(startDate)}
      pastScrollRange={0}
      futureScrollRange={10}
      markingType="period"
      markedDates={{ ...markedDates }}
    />
  );
}

export default DatesPicker;
```

## Screenshots

https://user-images.githubusercontent.com/20891090/194968093-d390af0b-258c-4275-aeab-ea250d78b2f1.mp4

**Comment by ukcasso** [comment]
@andreyxdd
I have same issue.
I think it happened after version 1.128x.0 update.

you have to downgrade package 1.1270.0 version.

**Comment by andreyxdd** [comment]
@ukcasso 
Thanks. At least some kind of workaround

**Comment by mittalkamal29** [comment]
@andreyxdd @ukcasso is there any other solution for same?

**Comment by urkin-dev** [comment]
Still same issue. Downgrade to 1.1270.0 helps but it still needs fix

**Comment by nitin-jotwani-fc** [comment]
Facing same issue. Downgrading didn't help. Still facing.

**Comment by cam-shaw** [comment]
You can apply this patch to hide the issue where the calendar shows the label before the theme is applied. Not sure what's the root cause here because the example project works fine. Will report back if I work out of the issue .

https://gist.github.com/cam-shaw/b5823b758f8612cf3037ab46390e4116

**Comment by urkin-dev** [comment]
> You can apply this patch to hide the issue where the calendar shows the label before the theme is applied. Will report back if I work out of the issue .
> 
> https://gist.github.com/cam-shaw/b5823b758f8612cf3037ab46390e4116

**Comment by theyanniss23002** [comment]
@andreyxdd Hello! Can you please tell me which bottom sheet did you use?

**Comment by hernanif1** [comment]
It is still a problem

**Comment by Letty** [comment]
Can someone please reopen this issue? @Inbal-Tish It would be nice to have the option to use `dateString` but not as the default. Everytime you use the component, it is visually too different from your Calendar and App styling.
https://github.com/wix/react-native-calendars/commit/c4fa3ecdc5aeb4eaa17fec2cdb0b8ca260451b4e

**Comment by faljabi** [comment]
any solution for this? I am facing the same issue

**Comment by faljabi** [comment]
I solved it by setting dayTextColor: calendarRendered ? theme.colors.onBackground : 'transparent'

and calendarRendered is set to true onLayout :)
