### ISSUE TITLE
How to show markedDates fetched from backend

### ISSUE THREAD

**Issue by Fiyaz6772** [wix/react-native-calendars#2065]
## Description

we need to give markedDates as follow: markedDates={{
    '2012-05-25': {endingDay: true, color: '#50cebb', textColor: 'white'}
  }}
I'm not sure how to add these date string fetched from database because the key of the object can not be a variable

## Expected Behavior

It should be a simple way to add disabled dates fetched from database

## Observed Behavior

**Comment by Harikasai999** [comment]
Hi @Fiyaz6772, can you try this. 

if array should be like this:-
`array = ["2022-10-24", "2022-10-25", "2022-10-26"]`
Implementing in code:-
 ```
const [marked, setMarked] = useState(null);
    useEffect(() => {
        var formattedDates = []
       // dynamicArray fetching from database
        dynamicArray.map((res, key) => {
            formattedDates.push(res)
        })
        var obj = formattedDates.reduce((c, v) => Object.assign(c, { [v]: { disabled: true, disableTouchEvent: true, } }), {});
        setMarked(obj)
         }, [])
         
          <Calendar
               markedDates={marked}/>
```

**Comment by Fiyaz6772** [comment]
> Hi @Fiyaz6772, can you try this.
> 
> if array should be like this:- `array = ["2022-10-24", "2022-10-25", "2022-10-26"]` Implementing in code:-
> 
> ```
> const [marked, setMarked] = useState(null);
>    useEffect(() => {
>        var formattedDates = []
>       // dynamicArray fetching from database
>        dynamicArray.map((res, key) => {
>            formattedDates.push(res)
>        })
>        var obj = formattedDates.reduce((c, v) => Object.assign(c, { [v]: { disabled: true, disableTouchEvent: true, } }), {});
>        setMarked(obj)
>         }, [])
>         
>          <Calendar
>               markedDates={marked}/>
> ```

Surely I'll try this. Thank you so much
