### ISSUE TITLE
Agenda component renders selected day not once but each month on the same day (blue background), also never deselects

### ISSUE THREAD

**Issue by EKoetsjarjan** [wix/react-native-calendars#2069]
## Description

Agenda component renders selected day each month (blue background)

## Expected Behavior

Should only render the month of the selected day

## Environment

Introduced version 1.1290 version tagged 1.1289 was oke.

* `yarn ios`:
* `yarn start`:

Also specify:

1. Device/emulator/simulator & OS version:

## Reproducible Demo

build and run the agenda example
* `yarn ios`:
* `yarn start`:

go to agenda , scroll down and see the selected day repeat each time on the same day number.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

## Screenshots
<img width="344" alt="image" src="https://user-images.githubusercontent.com/17911862/197785589-4bd61c79-c0e2-43ea-9759-aa2b99a80ee0.png">

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

**Comment by chunghn** [comment]
Hello @EKoetsjarjan, How do you fix it? I still encounter it in 1.1291

**Comment by gerwim** [comment]
A workaround would be to to apply the change with the [patch-package](https://www.npmjs.com/package/patch-package) package.

1. Follow the [set-up instructions](https://www.npmjs.com/package/patch-package)
2. Create the folder `patches` (same level as your `package.json`)
3. Create a file `react-native-calendars+1.1291.0.patch` inside said folder, with the following contents:
```
@@ -0,0 +1,13 @@
diff --git a/node_modules/react-native-calendars/src/day-state-manager.js b/node_modules/react-native-calendars/src/day-state-manager.js
index 3610e19..ed41421 100644
--- a/node_modules/react-native-calendars/src/day-state-manager.js
+++ b/node_modules/react-native-calendars/src/day-state-manager.js
@@ -3,7 +3,7 @@ const { toMarkingFormat } = require('./interface');
 export function getState(day, current, props) {
     const { minDate, maxDate, disabledByDefault, context } = props;
     let state = '';
-    if ((context?.date ?? toMarkingFormat(current)) === toMarkingFormat(day)) {
+    if (context?.date === toMarkingFormat(day)) {
         state = 'selected';
     }
     else if (isToday(day)) {
```

Run `yarn install` (or `npm install`) and you should see in your console output:
```
patch-package 6.5.0
Applying patches...
react-native-calendars@1.1291.0 ✔
```

**Comment by EKoetsjarjan** [comment]
hello @chunghn , I had also to remove "^" inside package.json to point to an exact version
from 
"react-native-calendars": "^1.1289.0",
to
"react-native-calendars": "1.1289.0",

 otherwise  yarn will automatically upgrade to 1.1290 version in the background without the lock file
 I think this should solve the issue

**Comment by chunghn** [comment]
@EKoetsjarjan Thank you. I downgraded to `1.1284`, I also read issue #2064 .
