### ISSUE TITLE
Theme prop don't work in CalendarProvider

### ISSUE THREAD

**Issue by viniciusz42** [wix/react-native-calendars#2072]
## Description

I'm using CalendarProvider alongside with ExpandableCalendar and TimelineList, as [exemplified](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/timelineCalendarScreen.tsx)

However when trying to style the screen, the `Theme` prop don't work

There was an issue, but it was closed without any solution [here](https://github.com/wix/react-native-calendars/issues/1692)

## Expected Behavior

Theme prop should work

## Environment

react-native-calendars@1.1290.0
react-native@0.66.4

**Comment by mshafex** [comment]
Had a similar issue
you should pass 

```
theme={{
  //@ts-ignore
  'stylesheet.day.basic': {
      base: {
        borderColor:'white\
      },
    },
  }}
```
instead of passing a nested object
```
theme={{
  stylesheet: {
    day: {
      basic: {
       borderColor:'white'
      },
    },
  },
}}
```

the documentation is misleading 
also you should check the `style.js` file of the component you are trying to override the style for
