### ISSUE TITLE
expandable calendar last row is cut by knob section

### ISSUE THREAD

**Issue by frankA10019** [wix/react-native-calendars#2077]
## Description

expandable calendar last row is cut by knob section and show sixWeeks doesn't work.

## Expected Behavior

expandable calendar last row can display perfect and show six rows.

## Observed Behavior

expandable calendar last row is cut and only show five rows.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 0.1291.0
* `npm ls react-native`:0.68.2

Also specify:

1. Device/emulator/simulator & OS version: simulator

## Reproducible Demo

<CalendarProvider date={'2022-12-02'}>
        <ExpandableCalendar
          hideDayNames={false}
          firstDay={0}
          hideKnob={false}
          closeOnDayPress={false}
          hideExtraDays={false}
          showSixWeeks={true}
          markingType={'multi-dot'}
          markedDates={{
            '2022-11-30': {
              dots: [vacation, massage, workout],
              selected: true,
              selectedColor: 'red',
            },
            '2022-11-29': { dots: [massage, workout], disabled: true },
          }}
        />

## Screenshots

![Simulator Screen Shot - iPhone 13 - 2022-11-02 at 15 22 17](https://user-images.githubusercontent.com/105480239/199426115-513d6298-210f-4d64-85da-b468498fc661.png)

**Comment by frankA10019** [comment]
After I rebuild my project, the last row display fine. It still show five row in the calendar.
![simulator_screenshot_B0E28965-832D-4EB0-95E8-863D161D1D88](https://user-images.githubusercontent.com/105480239/199427491-7053fc35-3694-493d-a3bd-07e7e8f436a3.png)

**Comment by fexxdev** [comment]
This aint complete. This bug its still here with the latest version too :)
