### ISSUE TITLE
how to use custom header in expandable calendar

### ISSUE THREAD

**Issue by frankA10019** [wix/react-native-calendars#2079]
## Description

I want to use custom header in expandable calendar. I use customHeader parameter but it doesn't show.
It seems this parameter only works on Calendar.

```
const calendarHeader = (props) => {
    return (
      <View>
        <Text>2022-02-3</Text>
      </View>
    );
  };
```

## Expected Behavior

show the correct header.

## Observed Behavior

show the default header.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.1280.0
* `npm ls react-native`: 0.68.2

Also specify:

1. Device/emulator/simulator & OS version: simulator

**Comment by soniaalabed** [comment]
this worked for my case:
const renderCustomHeader = (date) => <CalendarHeader date={date} />;

<CalendarProvider
        date={initialDate}
        showTodayButton={false}
      >
        <ExpandableCalendar
          testID={testIDs.expandableCalendar.CONTAINER}
          renderHeader={renderCustomHeader}
          renderArrow={renderArrow}
/>
</CalendarProvider>

**Comment by MarcHbb** [comment]
@frankA10019 Have you manage to solve this ? I have the same issue

**Comment by vingrad** [comment]
> CalendarProvider



> this worked for my case:
> 
> ```
> const renderCustomHeader = (date) => <CalendarHeader date={date} />;
> 
> <CalendarProvider
>         date={initialDate}
>         showTodayButton={false}
>       >
>         <ExpandableCalendar
>           testID={testIDs.expandableCalendar.CONTAINER}
>           renderHeader={renderCustomHeader}
>           renderArrow={renderArrow}
> />
> </CalendarProvider>
> ```

Are you sure that it works with a CalendarProvider ? I don't see any change in the header.

**Comment by soniaalabed** [comment]
> > this worked for my case:
> > ```
> > const renderCustomHeader = (date) => <CalendarHeader date={date} />;
> > 
> > <CalendarProvider
> >         date={initialDate}
> >         showTodayButton={false}
> >       >
> >         <ExpandableCalendar
> >           testID={testIDs.expandableCalendar.CONTAINER}
> >           renderHeader={renderCustomHeader}
> >           renderArrow={renderArrow}
> > />
> > </CalendarProvider>
> > ```
> 
> Are you sure that it works with a ExpandableCalendar ? I don't see any change in the header.

@vingrad yes I'm using this in my project and it is working as expected
