### ISSUE TITLE
Agenda: hideKnob doesn't work properly

### ISSUE THREAD

**Issue by anlumo** [wix/react-native-calendars#208]
## Description

Agenda has a prop called “hideKnob” that doesn't do what you'd expect.

## Expected Behavior

Knob removed from the view and space is used for the remaining views.

## Observed Behavior

The know gets removed, but in its place is a blank space that doesn't do anything.

## Environment

* `npm ls react-native-calendars`:
`└── react-native-calendars@1.7.1`
* `npm ls react-native`:
`└── react-native@0.49.3`

Phone/emulator/simulator & version:

Reproduced with expo, iOS simulators and on iPhone (iOS11).

## Reproducible Demo

It's probably the easiest to add `hideKnob={true}` to the props in the Agenda example.

Looking though the code, there's this line:
`<View style={{height: agendaHeight + KNOB_HEIGHT}} onLayout={this.onScrollPadLayout} />`

This always adds the `KNOB_HEIGHT`, no matter whether the knob exists or not. This constant is also not changeable from the outside. Same with `HEADER_HEIGHT`, which should be reduced when there's no knob.

**Comment by tautvilas** [comment]
Hi, I guess this works as expected, because the knob is not visibile anymore, right? Could you add a screenshot explaining what should be fixed? thx
