### ISSUE TITLE
How can i catch the date changes on timelineList

### ISSUE THREAD

**Issue by on29-dev** [wix/react-native-calendars#2083]
## Description

I want to catch an event(onDateChanged) during swiping timelineList.
I give props `onDateChanged` on `<CalendarProvider>` wrapping the timelineList.
But it can't catch any event when I swipe the timelineList horizontally(to change the date)

Is it bug?
How can i catch the date changes on timelineList?

```
 <CalendarProvider
        date={dayjs().format('YYYY-MM-DD')}
        onDateChanged={(date, us) => {
        // it doesn't work 😕
          console.log('onDateChanged', date); 
          console.log('onDateChanged', us);
        }}
        showTodayButton
        disabledOpacity={0.6}
      >
```

## Expected Behavior

When I swipe a timelinelist horizontally, `CalendarProvider` can catch the change date.

Also specify:

1. Device/emulator/simulator & OS version: iPhon 13 simulator / iOS 15.2

## Screenshots

![Simulator Screen Recording - iPhone 13 - 2022-11-08 at 16 44 45](https://user-images.githubusercontent.com/11909001/200504382-1b6761e3-625c-4e8c-8ed0-e47a0eeb2b79.gif)

Screenshots or gifs of the issue and the suggested fix will help us
 move faster with the review process.

**Comment by R-D-P** [comment]
did you find any solution to this? I am having the same problem. 
OnDateChange only seems to get called when clicking on the left and right arrows.
