### ISSUE TITLE
Calendar always selecting default day.

### ISSUE THREAD

**Issue by algarcia-vector** [wix/react-native-calendars#2085]
I am using the Calendar component and the default day it's always selected.

like for example today is 8 of november, and in the calendar this day is always marked. 
![prueba](https://user-images.githubusercontent.com/80910100/200727229-e5df8759-4bbe-4d73-b859-fbb3697b9b4d.png)

How can I unmark the default day, so in the calendar it only appear the one that I clicked?

Thanks in advance. 

I am using the latest version of this library.

**Comment by JSimai** [comment]
Same as #2073 and #2064 and #2069

**Comment by JSimai** [comment]
[This](https://github.com/wix/react-native-calendars/issues/2073#issuecomment-1297949986) solution worked for me. Others say to downgrade to older versions. Check out those other issues.

**Comment by algarcia-vector** [comment]
Thanks you, it fixed my problem :D
