### ISSUE TITLE
Remove today from marked days

### ISSUE THREAD

**Issue by waelbenmustapha** [wix/react-native-calendars#2091]
the default behavior shows today with a blue background same as marked dates , i want to remove the blue background from the current day , how can i achieve that ? i tried everything but couldn't find a way

**Comment by TomCorvus** [comment]
Try to encapsulate your calendar element inside `CalendarProvider` like this :
```
import { CalendarList, CalendarProvider } from 'react-native-calendars';

<CalendarProvider date={today}>
  <CalendarList
    key={key}
    theme={globalVariables.calendar}
    onDayPress={(day: any) => onDayPressHandler(day)}
    monthFormat="MMM yyyy"
    firstDay={1}
    markingType={markingType}
    markedDates={selectedPeriod}
  />
</CalendarProvider>
```

and set `today` in this format "YYYY-MM-DD". It will highlight only today date or set an empty string if you don't need this highlight.

**Comment by TomCorvus** [comment]
Try to encapsulate your calendar element inside `CalendarProvider` like this :
```
import { CalendarList, CalendarProvider } from 'react-native-calendars';

<CalendarProvider date="">
  <CalendarList
    key={key}
    theme={globalVariables.calendar}
    onDayPress={(day: any) => onDayPressHandler(day)}
    monthFormat="MMM yyyy"
    firstDay={1}
    markingType={markingType}
    markedDates={selectedPeriod}
  />
</CalendarProvider>
```

and set an empty string for date prop if you don't need this highlight.

**Comment by BojDom** [comment]
> Try to encapsulate your calendar element inside `CalendarProvider` like this :
> 
> ```
> import { CalendarList, CalendarProvider } from 'react-native-calendars';
> 
> <CalendarProvider date="">
>   <CalendarList
>     key={key}
>     theme={globalVariables.calendar}
>     onDayPress={(day: any) => onDayPressHandler(day)}
>     monthFormat="MMM yyyy"
>     firstDay={1}
>     markingType={markingType}
>     markedDates={selectedPeriod}
>   />
> </CalendarProvider>
> ```
> 
> and set an empty string for date prop if you don't need this highlight.

How about Calendar component?

**Comment by migsandia-1984** [comment]
> the default behavior shows today with a blue background same as marked dates , i want to remove the blue background from the current day , how can i achieve that ? i tried everything but couldn't find a way

I have the same problem.

**Comment by TomCorvus** [comment]
@BojDom If you replace CalendarList into Calendar in my example, is it not working?

**Comment by waelbenmustapha** [comment]
What i did was creating a custom  dayComponent like this

```
dayComponent={(e) => (
          <TouchableOpacity
            disabled={e.state === "disabled"}
            onPress={() => {
              changeOneDay(e.date.dateString);
            }}
          >
            <View
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                padding: 5,
                height: 32,
                width: 32,
                backgroundColor: e.marking?.selected ? Colors.PRIMARY : "white",
                borderRadius: 99,
                textAlign: "center",
              }}
            >
              <Text
                style={{
                  includeFontPadding: false,
                  fontSize: 14,
                  color:
                    e.state === "disabled"
                      ? "grey"
                      : e.marking?.selected
                      ? "white"
                      : "black",
                }}
              >
                {e.date.day}
              </Text>
            </View>
          </TouchableOpacity>
        )}
```
having full control over the disabled selected and all behaviors , but @TomCorvus  solution looks cleaner

**Comment by Seojun-Park** [comment]
@TomCorvus 

It seems doesn't work on `<Calendar />` component.
Is there any other way to remove hightlight?

```tsx
 <CalendarProvider date="">
            <Calendar
              style={styles.calendarContainer}
              theme={calendarStyle}
              firstDay={1}
              onDayPress={handleSelectDate}
              markedDates={selectedDates}
              monthFormat="MMMM"
             ...
            />
</CalendarProvider>
```


<details><summary>Screen shot</summary>
![IMG_9115](https://user-images.githubusercontent.com/47709344/201943943-69a4f514-d08f-4bfd-9413-f9f38e1f8438.PNG)
</details>

**Comment by mshafex** [comment]
Same issue in Calendar component
```
     <Calendar
        initialDate=""
        date=""
        markingType="custom"
        markedDates={reservedDates}
        renderHeader={date => <Text>{moment(new Date(date)).format('YYYY MMMM')}</Text>}
        enableSwipeMonths
      />
```
I also tried wrraping it in `CalendarProvider` but its the same issue

**Comment by TomCorvus** [comment]
It is little bit shitty, but add a `context` prop on your Calendar component as an object with empty date, like this:
```
    <Calendar
        initialDate=""
        context={{ date: '' }}
        markingType="custom"
        markedDates={reservedDates}
        renderHeader={date => <Text>{moment(new Date(date)).format('YYYY MMMM')}</Text>}
        enableSwipeMonths
      />
```

From what I've seen in the source code, the Calendar component doesn't retrieve Calendar context.

**Comment by mshafex** [comment]
Still not working @TomCorvus 
```
import React, { useContext } from 'react';
import { Calendar, CalendarContext } from 'react-native-calendars';

  const context = useContext(CalendarContext);

   <CalendarProvider  date="">
        <Calendar
          initialDate=""
          context={context}
          markingType="custom"
          displayLoadingIndicator={isGetReservedDatesLoading}
          markedDates={reservedDates}
          onMonthChange={month => {
            getReservedDatesMutate({
              listing_id: listing.id,
              start_date: month.timestamp,
              end_date: moment(month.timestamp).endOf('month').unix() * 1000,
            });
          }}
          renderHeader={date => <Text>{moment(new Date(date)).format('YYYY MMMM')}</Text>}
          enableSwipeMonths
          hideExtraDays
        />
      </CalendarProvider>
```
another note that today is 16 of the month it shows 16 of every month marked this way

![Screenshot_2022-11-16-11-17-25-348-edit_debug](https://user-images.githubusercontent.com/46707426/202125715-9b426826-bfb5-43c4-aa34-e287330749aa.jpg)

**Comment by mshafex** [comment]
Thanks @Seojun-Park passing  `context={{ date : '' }}`     works :pray:

**Comment by TomCorvus** [comment]
Sorry guys, I forgot to say in my example that `CalendarProvider` must be at the root of the app like others providers. My bad.

For example, in your App.js

```
import { CalendarContext } from 'react-native-calendars';

<CalendarProvider date="">
   <App />
</CalendarProvider>

```

And in your App component :

```
import React, { useContext } from 'react';
import { Calendar } from 'react-native-calendars';

const context = useContext(CalendarContext);

<Calendar
        initialDate=""
        context={context}
        markingType="custom"
        markedDates={reservedDates}
        renderHeader={date => <Text>{moment(new Date(date)).format('YYYY MMMM')}</Text>}
        enableSwipeMonths
/>
```

Context is necessarily an empty object if you declare it before the provider.

@Seojun-Park 's solution works too but less clean for me.

**Comment by Seojun-Park** [comment]
@TomCorvus 

Thanks!
It works as expected

**Comment by csillagkrisztian** [comment]
The Agenda component, has the same issue, yet the context fix doesn't seem to work for the Agenda component

**Comment by namikinn** [comment]
@TomCorvus 

Is context no longer needed in the new version?
When I pass context, it gets highlighted.

new version
https://snack.expo.dev/@nnaoi/calendars113110

old version
https://snack.expo.dev/@nnaoi/calendars113100
