### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by adriantombu** [wix/react-native-calendars#210]
## Description
I'm unable to use this package in React Native, I only have a fatal error screen (see below)

## Expected Behavior
Display the CalendarList properly

## Observed Behavior
Big red error screen

![simulator screen shot - iphone 6 - 2017-10-24 at 16 16 12](https://user-images.githubusercontent.com/383297/31948358-05d87042-b8d7-11e7-90ca-3ce84285fc13.png)

## Environment

* `npm ls react-native-calendars`: 1.7.1
* `npm ls react-native`: 0.42.3
* iOs simulator on the last Xcode version 

## Reproducible Demo
On top `import { CalendarList } from 'react-native-calendars'`
And on my render function, the dead simple `<CalendarList />`

Thanks for the help !

**Comment by tautvilas** [comment]
hey, this comonent does not support such old version of RN that does not have FlatList implementatino

**Comment by tautvilas** [comment]
you can try 1.5.9 version of this lib, it does not use FlatList

**Comment by adriantombu** [comment]
We are on the process of upgrading the app to the latest version of RN, but it'll take some time as you could guess. I'll try the 1.5.9 in the meanwhile, thanks for your answer !
