### ISSUE TITLE
TypeError: context.setDate is not a function

### ISSUE THREAD

**Issue by ErionTp** [wix/react-native-calendars#2100]
I've installed the latest version and I'm trying to use the `WeekCalendar`.

`<WeekCalendar
          allowShadow={false}
          current="2022-11-21"
          onDayPress={(value: any) => console.log(value)}
        />`

When I try to scroll to the next or previous week it throws this error:

`TypeError: context.setDate is not a function. (In 'context.setDate(items[pageIndex], _commons.UpdateSources.WEEK_SCROLL)', 'context.setDate' is undefined)`

**Comment by JanmyLo** [comment]
https://github.com/wix/react-native-calendars/issues/2046#issuecomment-1295467711

wrapped Weekcalendar with CalendarProvider
