### ISSUE TITLE
Current Date/ Today date is highlighted in every month in Agenda.

### ISSUE THREAD

**Issue by flloyddsouza** [wix/react-native-calendars#2104]
I have setup a agenda Diary with records from local DB.
I can see the current date highlighted in every month which should not be the case.

## Expected Behavior
I feel that current date and selected date should have different UI or color,  seprating the selected and the current date.

##What action did you perform, and what did you expect to happen?
Used Agenda component with minimal setup

## Observed Behavior
The  current date in every month is highlighted. I am passing the "Today" date as selected date and tried without passing today date, the results are the same.

## Environment
react native: 0.70.4

* `npm ls react-native-calendars`:   react-native-calendars@1.1291.1
* `npm ls react-native`:
├─┬ @react-native-async-storage/async-storage@1.17.10
│ └── react-native@0.70.4 deduped
├─┬ @react-native-community/netinfo@9.3.6
│ └── react-native@0.70.4 deduped
├─┬ @react-native-toolkit/triangle@0.0.1
│ └── react-native@0.70.4 deduped
├─┬ @react-navigation/bottom-tabs@6.4.0
│ ├─┬ @react-navigation/elements@1.3.6
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ @react-navigation/elements@1.3.4
│ └── react-native@0.70.4 deduped
├─┬ @react-navigation/native-stack@6.9.1
│ ├─┬ @react-navigation/elements@1.3.6
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ @react-navigation/native@6.0.13
│ └── react-native@0.70.4 deduped
├─┬ @react-navigation/stack@6.3.3
│ ├─┬ @react-navigation/elements@1.3.6
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ lottie-react-native@5.1.4
│ ├─┬ react-native-safe-modules@1.0.3
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ react-native-blob-util@0.16.3
│ └── react-native@0.70.4 deduped
├─┬ react-native-calendars@1.1291.1
│ └─┬ recyclerlistview@3.0.5
│   └── react-native@0.70.4 deduped
├─┬ react-native-dialog@9.3.0
│ └── react-native@0.70.4 deduped
├─┬ react-native-document-picker@8.1.2
│ └── react-native@0.70.4 deduped
├─┬ react-native-elements@3.4.2
│ ├─┬ react-native-ratings@8.0.4
│ │ └── react-native@0.70.4 deduped
│ └─┬ react-native-size-matters@0.3.1
│   └── react-native@0.70.4 deduped
├─┬ react-native-fs@2.20.0
│ └── react-native@0.70.4 deduped
├─┬ react-native-gesture-handler@2.8.0
│ └── react-native@0.70.4 deduped
├─┬ react-native-image-picker@4.10.0
│ └── react-native@0.70.4 deduped
├─┬ react-native-image-viewing@0.2.2
│ └── react-native@0.70.4 deduped
├─┬ react-native-maps@1.3.2
│ └── react-native@0.70.4 deduped
├─┬ react-native-paper-dates@0.9.2
│ └── react-native@0.70.4 deduped
├─┬ react-native-paper@4.12.5
│ ├─┬ react-native-iphone-x-helper@1.3.1
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ react-native-phone-input@1.3.4
│ ├─┬ @react-native-picker/picker@2.4.8
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ react-native-phone-number-input@2.1.0
│ ├─┬ react-native-country-picker-modal@2.0.0
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ react-native-render-html@6.3.4
│ ├─┬ @jsamr/react-native-li@2.3.1
│ │ └── react-native@0.70.4 deduped
│ ├─┬ @native-html/transient-render-engine@11.2.3
│ │ └── react-native@0.70.4 deduped
│ └── react-native@0.70.4 deduped
├─┬ react-native-safe-area-context@3.4.1
│ └── react-native@0.70.4 deduped
├─┬ react-native-screens@3.18.2
│ └── react-native@0.70.4 deduped
├─┬ react-native-splash-screen@3.3.0
│ └── react-native@0.70.4 deduped
├─┬ react-native-sqlite-storage@6.0.1
│ └── react-native@0.70.4 deduped
├─┬ react-native-webview@11.23.1
│ └── react-native@0.70.4 deduped
├── react-native@0.70.4
└─┬ react-redux@8.0.4
  └── react-native@0.70.4 deduped

1. Device/emulator/simulator & OS version:  All Devices,  iOS 16.1, Android 10

## Screenshots

Screenshots or gifs of the issue and the suggested fix will help us move faster with the review process.

![IMG_3596](https://user-images.githubusercontent.com/31607520/203661048-af9ab860-78b9-4672-8a63-70a41acc9ab1.jpg)

![IMG_3597](https://user-images.githubusercontent.com/31607520/203661075-3ba6954d-c144-4dbd-a7d6-5562940513b3.jpg)

**Comment by flloyddsouza** [comment]
Wrap Agenda with CalendarProvider
<CalendarProvider date="">
  <Agends
     ....
     ....
     ....>
  </Agenda>
</CalendarProvider >

**Comment by pixelsomatic** [comment]
I have the same issue

**Comment by Ziltosh** [comment]
Same here.

**Comment by ribasxteam** [comment]
I'm using an older version, but put a ```context={{date: new Date().toISOString()}}``` in the ```<Calendar />``` tag solved the problem for me.

```tsx
<Calendar
    markedDates={markedDates}
    theme={{
        textDayFontSize: 14,
    }}
    onDayPress={onDayPress}
    maxDate={maxDate}
    allowSelectionOutOfRange={false}
    context={{date: new Date().toISOString()}}
/>
```

This bug happens because of this line here:
https://github.com/wix/react-native-calendars/blob/077cd1318b23d8856b62c9d531031c2a4d2ec47d/src/day-state-manager.ts#L9

It first tries to use the date context value. If undefined, use the current month against the current day. The "bug" happens because the current is not the current month (present time) but the current month being rendered. I don't know if this behavior is intended but you can debug this line here: https://github.com/wix/react-native-calendars/blob/eb335ebe2cf27cda6506093154c7ab3227c6d37e/src/calendar/index.tsx#L209

To see why this is happening.
