### ISSUE TITLE
"showSixWeeks" show only 5 weeks sometimes

### ISSUE THREAD

**Issue by Darkilen** [wix/react-native-calendars#2106]
## Description

The "showSixWeeks" parameter show only 5 lines/weeks for February 2026 (with week starting by Sunday). It's an exception because this particular month start with a Sunday and count exactly 28 days (4 weeks exactly) and then the parameter add another week => We now have 5 weeks instead of 6 weeks.

## Expected Behavior

I expect to see 6 weeks if I go on February which starts on the first day of the week.

## Observed Behavior

I see only 5 lines/weeks.

## Environment

I'm running the example application with the last master commit (https://github.com/wix/react-native-calendars/tree/9ccaf67ec5b18c99b2489239311214bbf2fa74af)

Also specify:

1. Device/emulator/simulator & OS version: Android emulator

## Reproducible Demo

I'm running the example application with the last master commit.

**Comment by Darkilen** [comment]
Still relevant.

**Comment by abduls-ht** [comment]
showSixWeeks = true is showing 7 weeks for month which already have 6 weeks. For e.g. Jan 2023. And for April 2023 it's showing only 5 weeks.

**Comment by SSead** [comment]
Same issue here.

**Comment by ng-ha** [comment]
Same issue here.  Need help!!

**Comment by ng-ha** [comment]
@Darkilen Did you find the solution?

**Comment by Darkilen** [comment]
I didn't use this parameter in the end, I don't have any solutions.
