### ISSUE TITLE
Disable Horizontal scroll in TimelineList

### ISSUE THREAD

**Issue by Darkilen** [wix/react-native-calendars#2108]
## Description

Reopen for https://github.com/wix/react-native-calendars/issues/1808.
`Timeline` component don't handle displaying multiple day simultaneously with the props `numberOfDays=2`. We need a way to disable scrolling on `TimelineList` component or a way to handle more than 1 day in `Timeline` component.

## Expected Behavior

I want to display a Timeline for only 2 days. It's not possible for now.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1291.1
* `npm ls react-native`: react-native@0.68.3

**Comment by invisibleved** [comment]
Somebody here ??

**Comment by ciaoamigoschat** [comment]
news?
