### ISSUE TITLE
Agenda no longer rerenders when items changes

### ISSUE THREAD

**Issue by DianaKoenraadt** [wix/react-native-calendars#2112]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Usage <Agenda items={items} .... />
When items object changes, the Agenda no longer rerenders. This used to work fine.

## Expected Behavior

Go back to previous behavior, rerender when items array changes.

## Observed Behavior

Does not rerender but it should.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 
 
react-native-calendars@1.1292.0

* `npm ls react-native`:

├─┬ @react-native-async-storage/async-storage@1.17.11
│ └── react-native@0.70.6 deduped
├─┬ @react-native-community/masked-view@0.1.11
│ └── react-native@0.70.6 deduped
├─┬ @react-native-community/netinfo@9.3.7
│ └── react-native@0.70.6 deduped
├─┬ @react-native-picker/picker@2.4.8
│ └── react-native@0.70.6 deduped
├─┬ react-native-app-link@1.0.1
│ └── react-native@0.70.6 deduped
├─┬ react-native-calendars@1.1292.0
│ └─┬ recyclerlistview@3.0.5
│   └── react-native@0.70.6 deduped
├─┬ react-native-gesture-handler@2.8.0
│ └── react-native@0.70.6 deduped
├─┬ react-native-get-random-values@1.8.0
│ └── react-native@0.70.6 deduped
├─┬ react-native-paper@4.12.5
│ ├─┬ react-native-iphone-x-helper@1.3.1
│ │ └── react-native@0.70.6 deduped
│ └── react-native@0.70.6 deduped
├─┬ react-native-phone-number-input@2.1.0
│ ├─┬ react-native-country-picker-modal@2.0.0
│ │ └── react-native@0.70.6 deduped
│ └── react-native@0.70.6 deduped
├─┬ react-native-picker-select@8.0.4
│ └─┬ @react-native-picker/picker@1.16.8
│   └── react-native@0.70.6 deduped
├─┬ react-native-pin-view@3.0.3
│ └── react-native@0.70.6 deduped
├─┬ react-native-reanimated@2.13.0
│ └── react-native@0.70.6 deduped
├─┬ react-native-safe-area-context@4.4.1
│ └── react-native@0.70.6 deduped
├─┬ react-native-super-grid@5.0.0
│ └── react-native@0.70.6 deduped
├─┬ react-native-svg@13.6.0
│ └── react-native@0.70.6 deduped
├─┬ react-native-webview@11.25.0
│ └── react-native@0.70.6 deduped
├── react-native@0.70.6
├─┬ react-navigation-material-bottom-tabs@2.3.5
│ └── react-native@0.70.6 deduped
├─┬ react-navigation-stack@2.10.4
│ └── react-native@0.70.6 deduped
├─┬ react-navigation@4.4.4
│ ├─┬ @react-navigation/native@3.8.4
│ │ └─┬ react-native-safe-area-view@0.14.9
│ │   └── react-native@0.70.6 deduped
│ └── react-native@0.70.6 deduped
└─┬ react-redux@8.0.5
  └── react-native@0.70.6 deduped 

Also specify:

Android apk

## Reproducible Demo

Not available

## Screenshots

Not available

**Comment by francesco-clementi-92** [comment]
#1855

**Comment by ali27001** [comment]
This is a big problem that prevents the use of the library. Has there been an update yet?

**Comment by vokecodes** [comment]
Use key prop to force re-render

```
const [agendaKey, setAgendaKey] = useState(0); // <-- Add a key state
setAgendaKey(prevKey => prevKey + 1); // <-- Update key to force re-render

<Agenda 
    key={agendaKey} 
 // other props
 />
```

**Comment by GreenFella** [comment]
> > Use key prop to force re-render
> > ```
> > const [agendaKey, setAgendaKey] = useState(0); // <-- Add a key state
> > setAgendaKey(prevKey => prevKey + 1); // <-- Update key to force re-render
> > 
> > <Agenda 
> >     key={agendaKey} 
> >  // other props
> >  />
> > ```
> 
> This will re render the whole component every time there is a new item. I strongly won’t suggest this solution.

I see you commenting about this issue on many issues, did you manage to find a fix yet? (that doesn't involve re-rendering the whole component?)
I am having the same issue and don't understand why it has not been fixed since it is such an important part of the library...

**Comment by GreenFella** [comment]
> > Use key prop to force re-render
> > ```
> > const [agendaKey, setAgendaKey] = useState(0); // <-- Add a key state
> > setAgendaKey(prevKey => prevKey + 1); // <-- Update key to force re-render
> > 
> > <Agenda 
> >     key={agendaKey} 
> >  // other props
> >  />
> > ```
> 
> This will re render the whole component every time there is a new item. I strongly won’t suggest this solution.

This fixed the issue for me: https://github.com/wix/react-native-calendars/issues/1589#issuecomment-995414073

**Comment by francesco-clementi-92** [comment]
#2189 When this merge will be released you just need to specify the rowHasChanged prop and it will update the component
