### ISSUE TITLE
Disable touch event for past dates

### ISSUE THREAD

**Issue by harika-nammi** [wix/react-native-calendars#2113]
## Description

Hi Everyone, i am using this calendar module. How to disable touch event for past dates. 

## Expected Behavior

Touch event is disabled for past dates.

## Observed Behavior

Touch event is enabled.

## Environment

* `npm ls react-native-calendars`:1.1289.0
* `npm ls react-native`:0.66.2

Also specify:

1. Device/emulator/simulator & OS version: All versions

## Screenshots

https://user-images.githubusercontent.com/113165469/205560838-d8d1cd9e-e7b0-452a-9798-5ec802021d2d.mov

**Comment by mansi-acquaintsoft** [comment]
![image](https://user-images.githubusercontent.com/119397479/205821463-305f02a5-dbd3-4299-aad4-06946a724611.png)
@harika-nammi , add this line

**Comment by harika-nammi** [comment]
Thank you @mansi-acquaintsoft, it's working fine.
