### ISSUE TITLE
With Agenda, the month in loadItemsForMonth's param is not consistent

### ISSUE THREAD

**Issue by SpaceSimon** [wix/react-native-calendars#2115]
## Description

The month in the param of loadItemsForMonth is not always correct: it seems when loading it is Javascript's month (starting at 0), and when clicking a day or scrolling it is normal (starting at 1).

```
        <Agenda
          items={userItems}
          loadItemsForMonth={month => console.log(month)}
          renderItem={renderItem}
          rowHasChanged={rowHasChanged}
          firstDay={1}
          showWeekNumbers={true}
        />
```

## Expected Behavior

The month should always be based on the same system (either Javascript's or normal).

## Observed Behavior

When loading the page, loadItemsForMonth's param contains the month '11' (I suppose it's 'Javascript's December'):

```
dateString: "2022-11-07"
day: 7
month: 11
timestamp: 1667779200000
year: 2022
```

When clicking a day or scrolling, this month is '12':

```
dateString: "2022-12-07"
day: 7
month: 12
timestamp: 1670371200000
year: 2022
```

## Environment

RN 0.63.5
RNC 1.403.0

**Comment by itajenglish** [comment]
Has there been any update on this issue? I'm also experiencing the same thing.

**Comment by chasingwatts** [comment]
This appears to still be an issue.  Nothing?
