### ISSUE TITLE
AgendaList with same style as Agenda

### ISSUE THREAD

**Issue by mariovillamizar** [wix/react-native-calendars#2116]
Hey guys, my goal is to create a screen with an Agenda that has header with the same behavior of the WeeklyCalendar.
So I have read trough the issues here and I found that I can use the AgendaList component with the WeeklyCalendar, and in fact there is an example in the master branch I took as reference. The screen is looking like this:

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-10 at 10 38 13](https://user-images.githubusercontent.com/10704258/206863122-529c6b07-1f88-4560-9899-02ec2f913f31.png)

However I need to have the same style as the Agenda componente, where the visible days are at left side instead of having it a top side like the AgendaList component:

> ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-10 at 10 38 13](https://user-images.githubusercontent.com/10704258/206863651-9d2b683c-c059-487f-8ba7-07f8f07704e8.png)
> 
> ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-10 at 10 51 12](https://user-images.githubusercontent.com/10704258/206864602-3e05efc8-78fc-46f7-96b5-1f549c4109eb.png)

Another option I was considering is to use the Agenda component and take off the header/calendar part and replace it with the WeeklyCalendar, but I have not found the way and even I don't know if that's possible.

Could you help me please? Thank you in advance.

**Comment by AryanTiwari6** [comment]
Same issue!

**Comment by alfianlensundev** [comment]
i have same issue, has anyone fix it?
