### ISSUE TITLE
Select dates between dates

### ISSUE THREAD

**Issue by justdan0227** [wix/react-native-calendars#2122]
Newbie Period Question. How do I select 2 days and have the calendar show all dates between the two marked?  Can I just specify start and end or do I have to provide all of the days between for MarkedDates

**Comment by charleston10** [comment]
![image](https://user-images.githubusercontent.com/3097207/208965523-361ee384-7c1b-44d1-89de-e42f633b58d3.png)

**Comment by justdan0227** [comment]
So I finally used the logic that on a long press I store a start date, and then on a second long press on another date I save the end date.  Then I calculate the says between the two markings each day and then reset the state variable with the new marked dates.  

not sure if that's the way to do it but it does work?
