### ISSUE TITLE
First Month in Agenda Not Displaying Correctly

### ISSUE THREAD

**Issue by jde8aa** [wix/react-native-calendars#2124]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

In my example, the current month is December.  Scrolling through the items and days in December works as expected.  However, if I go back to November then the calendar does not display the dates of the current week correctly.  This issue seems to be occurring with the first month of the Calendar List, regardless of what the first month actually is.

## Expected Behavior

Click a day in the most-recent completed month.  I expect the "selected day" to scroll normally through the month and be visible.

## Observed Behavior

On iOS simulator the upper row just shows "December 2022" instead of showing me the dates of the week of November that I am on.  On a real iOS device, it just shows white space.  On a real Android device, the incorrect week is displayed and not vertically centered correctly.

Although my example points to November as being the problem month, if I increment "pastScrollRange" then November begins working correctly and October fails to display correctly.

If there's an error message, please paste the *full terminal output and error message* in this code block:

There are no error messages.

## Environment

Please run these commands in the project folder and fill in their results:

* `react-native-calendars@1.1292.0`:
* `react-native@0.68.5`:

Also specify:

1. Device/emulator/simulator & OS version: iPhone 14 Pro Max simulator, iPhone 13 (real device), Motorola moto x4 (real device)

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

I can provide code if needed, but there is nothing special happening.  I am essentially using the Agenda demo on the main github page, just styled differently.

## Screenshots

Here's a gif if that helps.  I start off in December, scroll back to November to show the breaking functionality, and then scroll forward to January to show the correct functionality: 
![ezgif-5-7592cfe706](https://user-images.githubusercontent.com/17089037/208570778-bddd02fb-8880-4107-b080-bc8149b63296.gif)

The normal look when on 12/1 where the week is correct:
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-19 at 21 44 08](https://user-images.githubusercontent.com/17089037/208569800-da58a83f-4372-4520-a56d-7ebcd0cd7c6a.png)

If I scroll up a single day to 11/30 -- the week breaks:
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-19 at 21 44 20](https://user-images.githubusercontent.com/17089037/208569839-998d4524-6595-4dcf-9591-3e07c66c2c2b.png)

If I scroll forward to 1/1 (the month after 12/1) -- the week looks fine:
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-19 at 21 45 37](https://user-images.githubusercontent.com/17089037/208569886-a68e126b-9607-45a9-b907-33a7b2f629bc.png)

**Comment by jde8aa** [comment]
I set "pastScrollRange" to 0 to get rid of November, and now the issue happens with December.  So it seems to just be happening with the first month in the Calendar List.

**Comment by rodrigosjr** [comment]
Problema antigo, até hoje não foi corrigido.
