### ISSUE TITLE
Some date available to mark?

### ISSUE THREAD

**Issue by charleston10** [wix/react-native-calendars#2127]
Is there a possibility to leave some data available to mark?

not by date range

Ex.: 2022-12-21, 2022-12-24, 2022-12-25
days: 21, 24, 25

in this case the user can only mark these dates and the others are disabled

![image](https://user-images.githubusercontent.com/3097207/208969342-9882e276-b229-4b1f-84a1-bdfb9694c735.png)

**Comment by charleston10** [comment]
Or.... is there any blacklist date?

**Comment by charleston10** [comment]
I had the idea of adding a custom view to the component

![image](https://user-images.githubusercontent.com/3097207/208979054-4fdeb65a-1d16-4b3f-be6f-c6fc2bd8865b.png)

In the implementation below, I add the component with the enabled attribute where I check if the date coming from the calendar is contained within a whitelist array

![image](https://user-images.githubusercontent.com/3097207/208979264-023262bc-5711-41e7-94f5-1942e10a8be5.png)

Check white list

My whitelist
`const whiteListDate = [new Date('2022-12-21'), new Date('2022-12-23'), new Date('2022-12-25')];`

![image](https://user-images.githubusercontent.com/3097207/208979462-60c06481-27c8-4e4e-9320-45a239757916.png)

```
import { Text, TouchableOpacity, View } from 'react-native';
import React from 'react';
import { DateData, DayState } from 'react-native-calendars/src/types';

interface CalendarDayComponentProps {
  dateData: (string & DateData) | undefined;
  state: DayState | undefined;
  listener: Function;
  enabled: boolean;
}

export const CalendarDayComponent = ({ dateData, state, enabled, listener }: CalendarDayComponentProps) => {
  const onTapSelectDay = () => {
    if (enabled) {
      if (listener) listener(dateData);
    }
  };

  const styleCircle = {
    height: 30,
    width: 50,
    borderRadius: 50 / 2,
    backgroundColor: '#0784C7',
  };

  return (
    <TouchableOpacity onPress={onTapSelectDay}>
      <View style={enabled && styleCircle}>
        <Text
          style={{
            textAlign: 'center',
            color: state === 'disabled' || !enabled ? '#bebebe' : 'white',
            fontWeight: state === 'disabled' || enabled ? 'normal' : 'normal',
            fontSize: 22,
          }}>
          {dateData?.day}
        </Text>
      </View>
    </TouchableOpacity>
  );
};
```

**Comment by charleston10** [comment]
I had an idea to add a customizable component where I can control the date selection attributes
Where do I create a whitelist to leave active for selection only the dates that are on that list

![image](https://user-images.githubusercontent.com/3097207/208981110-6a74de67-8cfe-42a0-8569-b07046f5e54f.png)

```
import { Text, TouchableOpacity, View } from 'react-native';
import React from 'react';
import { DateData, DayState } from 'react-native-calendars/src/types';

interface CalendarDayComponentProps {
  dateData: (string & DateData) | undefined;
  state: DayState | undefined;
  listener: Function;
  enabled: boolean;
}

export const CalendarDayComponent = ({ dateData, state, enabled, listener }: CalendarDayComponentProps) => {
  const onTapSelectDay = () => {
    if (enabled) {
      if (listener) listener(dateData);
    }
  };

  const styleCircle = {
    height: 30,
    width: 50,
    borderRadius: 50 / 2,
    backgroundColor: state === 'selected' ? '#0784C7' : '#aeaeae',
  };

  return (
    <TouchableOpacity onPress={onTapSelectDay}>
      <View style={enabled && styleCircle}>
        <Text
          style={{
            textAlign: 'center',
            color: state === 'disabled' || !enabled ? '#bebebe' : 'white',
            fontWeight: state === 'disabled' || enabled ? 'normal' : 'normal',
            fontSize: 22,
          }}>
          {dateData?.day}
        </Text>
      </View>
    </TouchableOpacity>
  );
};
```

My whitelist

`const whiteListDate = [new Date('2022-12-21'), new Date('2022-12-23'), new Date('2022-12-25')];`

In the implementation below, I add the component with the enabled attribute
where I check if the date coming from the calendar is contained within a whitelist array

```
const isDateEnabled = (date: DateData): boolean => {
    let dateCalendar = new Date(date.dateString).toISOString().split('T')[0];

    let result = whiteListDate.find((item) => {
      let dateWhiteList = new Date(item).toISOString().split('T')[0];

      return dateWhiteList === dateCalendar;
    });

    return result !== undefined;
  };
```

**Comment by Keshu92** [comment]
I had an idea to add a customizable component where I can control the date selection attributes?
