### ISSUE TITLE
Issues with Agenda when used in web.

### ISSUE THREAD

**Issue by Saikedo** [wix/react-native-calendars#2128]
## Description

There are couple of issues with the Agenda component when it is used in web environment.

1. Knob is not responding to mouse clicks. It might be problematic to add drag support for this but at least we should make the click work.
2. Day names and dates are not aligned if the calendar width is large.
3. Calendar above the agenda scrolls to incorrect positions when I switch pages. Sometimes it ends up displaying a wrong week and sometimes it totally breaks and does not correctly show the date numbers.

## Expected Behavior

1. Clicking on the knob should expand the calendar.
2. Day names should always be on top of the day numbers.
3. The calendar above the agenda should not scroll and change when we go to a different page and come back.

## Environment

react-native-calendars@1.1292.0
react-native@0.68.5
react-native-web@0.17.7
Tested in google chrome.

## Reproducible Demo

Here is a reproducible demo for the issues. Please make sure to use the expanded web window to test some of these issues.
https://snack.expo.dev/4YbfX_dRkN

## Screenshots

![image](https://user-images.githubusercontent.com/19657054/208978860-9a12d4c3-16fd-4782-a1f6-84204d283ce8.png)

**Comment by WofWca** [comment]
Related #1733
