### ISSUE TITLE
Cannot read properties of undefined (reading 'scrollTo')

### ISSUE THREAD

**Issue by Saravananb123** [wix/react-native-calendars#2131]
We have Installed react-native-calendars@1.220.0 . 

Cannot read properties of undefined (reading 'scrollTo')

![image](https://user-images.githubusercontent.com/110403069/209795830-8499ad12-672a-4536-ad59-d4287d08fd06.png)

**Comment by adnanmukri** [comment]
Did you find any solution for this?
