### ISSUE TITLE
Feature Request: Birthdate Picker (includes design mockup)

### ISSUE THREAD

**Issue by patreu22** [wix/react-native-calendars#214]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

It would be great to have a nice Birthdatepicker. I also added a 3-steps-mockup how to get a nice user experience, but I don't know how to really implement it by myself.

## Expected Behavior

Step 1:  
![image](https://user-images.githubusercontent.com/11362357/32048567-310b9072-ba4a-11e7-97fd-05ce410a2944.png)

Step 2:  
![image](https://user-images.githubusercontent.com/11362357/32048627-6fdc7e7e-ba4a-11e7-9d86-98b602e75e48.png)

Step 3:  
![image](https://user-images.githubusercontent.com/11362357/32048639-78e0b45e-ba4a-11e7-957e-072ffa3aaf8c.png)

**Comment by tautvilas** [comment]
this product is out of scope for this project
