### ISSUE TITLE
Agenda: empty dates have dots in calendar view

### ISSUE THREAD

**Issue by JacobFrericks** [wix/react-native-calendars#215]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

In the Agenda screen of the example, empty dates include a dot in the Calendar drop down screen.

## Expected Behavior

No dot should appear (as shown in the demo gifs)

## Observed Behavior

The dot appears

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: -- react-native-calendars@1.8.1 (note, I tried it on v1.6.2 as well)
* `npm ls react-native`: -- react-native@0.48.4

Also specify:

1. Phone/emulator/simulator & version: Pixel 2 XL - Android v8.0 and iPad mini

## Reproducible Demo
See Agenda example (no changes)

![dotissue](https://user-images.githubusercontent.com/5521414/32121403-23b3ec2a-bb22-11e7-8ef8-74ab019e78dd.png)

**Comment by FarhounYoussef** [comment]
I had the same issue.
downgrade to react-native-calendars@1.7.1 solve the problem for me

**Comment by JacobFrericks** [comment]
@FarhounYoussef 
I still have this issue when downgrading to 1.7.1... and I'm wondering if this is a "cache" issue. How did you downgrade?

I downgraded just by removing node_modules and running `npm install`, then `npm start` to start the expo server again. Did you do anything different?

**Comment by JacobFrericks** [comment]
Yup, it's working again! Thanks!
