### ISSUE TITLE
Scroll only in the selected day [Agenda component]

### ISSUE THREAD

**Issue by bcostabatista** [wix/react-native-calendars#216]
## Description

Avoid infinite scroll through Agenda Component

## Expected Behavior

Show items only for the selected day and scroll only inside the selected day

## Observed Behavior

It scrolls many days ahead

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.5.8
* `npm ls react-native`: react-native@0.44.3

Also specify:

1. Phone/emulator/simulator & version: IOS 10.3

**Comment by habeebrahmanpt** [comment]
You got the solution for Avoid infinite scroll through Agenda Component
