### ISSUE TITLE
Issue with already selected dates, and scrolling to previous months.

### ISSUE THREAD

**Issue by chapeljuice** [wix/react-native-calendars#217]
## Description

After I select a date (which is saved as `this.state.checkInDate` in my app), when I close the calendar and open it back up, the current month that opens up is my checkInDate (which is great).

However, I cannot scroll past (previous) to that at all.

I would like to set the checkInDate as the "current" date (to open the calendar at that date), but then to be able to scroll back to todays date.

Is there a way to do make that happen that I'm not seeing?

Here's my markup:
```
let todaysDate = Moment().format('L')
<CalendarList
  onDayPress={(day) => this.onDayPress(day)}
  style={styles.calendar}
  current={this.state.checkInDate ? this.state.checkInDate : todaysDate}
  pastScrollRange={0}
  minDate={todaysDate}
  maxDate={maxDate}
  futureScrollRange={24}
  markedDates={this.markedDates()}
  markingType="interactive"
/>
```

## Environment

```
"react": "^16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-calendars": "^1.5.9",
```

**Comment by tautvilas** [comment]
Hi, is this duplicate of #80  ?

**Comment by chapeljuice** [comment]
Hrmmm, yeah I guess it seems like it is. Bummer there's no solution yet. I'll close this and comment on #80
