### ISSUE TITLE
Invariant Violation: Changing onViewableItemsChanged on the fly is not supported

### ISSUE THREAD

**Issue by JCMais** [wix/react-native-calendars#218]
`Invariant Violation: Changing onViewableItemsChanged on the fly is not supported`

When using with react-native 0.50

This is because the bind of `this.onViewableItemsChanged` on `calendar-list/index.js` is being made on the render method, generating a new function for every render call.

**Comment by dantranv** [comment]
Still have this error even with latest code form master branch: Invariant Violation: Changing onViewableItemsChanged on the fly is not supported

**Comment by tautvilas** [comment]
@JCMais could you check?

**Comment by JCMais** [comment]
@tautvilas I'm not using the agenda, so I'm afraid that I cannot.


@dantranv is it the same error?

Can you post the stacktrace?

**Comment by dantranv** [comment]
@JCMais 
Sure.

This error is located at:
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in FlatList (at index.js:156)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in CalendarList (at index.js:344)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at createAnimatedComponent.js:134)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AnimatedComponent (at index.js:343)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at createAnimatedComponent.js:134)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AnimatedComponent (at index.js:342)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at index.js:338)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AgendaView (at AgendaScreen.js:529)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AgendaScreen.js:528)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AgendaScreen.js:527)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AgendaScreen.js:237)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AgendaScreen.js:232)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AgendaDayScreen (at navigationStore.js:277)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Wrapped (at SceneView.js:32)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in SceneView (at CardStack.js:399)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at CardStack.js:398)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at CardStack.js:397)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at createAnimatedComponent.js:134)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AnimatedComponent (at Card.js:26)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Card (at PointerEventsContainer.js:55)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Container (at CardStack.js:440)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at CardStack.js:370)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at CardStack.js:369)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in CardStack (at CardStackTransitioner.js:103)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at Transitioner.js:187)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Transitioner (at CardStackTransitioner.js:55)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in CardStackTransitioner (at StackNavigator.js:48)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Unknown (at createNavigator.js:48)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Navigator (at createNavigationContainer.js:205)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in NavigationContainer (at Router.js:31)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in App (at Router.js:52)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Router (at Main.js:56)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in Main (at App.js:16)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at App.js:15)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in App (at renderApplication.js:35)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AppContainer.js:102)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in RCTView (at View.js:113)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in View (at AppContainer.js:122)
11-07 20:37:23.671  8399  8441 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)
11-07 20:37:23.889  8399  8441 W ReactNativeJS: Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

**Comment by JCMais** [comment]
@dantranv Looks like the files is not the most recent one, are you using the version `1.9.1`?

Can you paste here your `node_modules/react-native-calendars/src/calendar-list/index.js` file?

**Comment by dantranv** [comment]
import React, {Component} from 'react';
import {
  FlatList, Platform
} from 'react-native';
import PropTypes from 'prop-types';
import XDate from 'xdate';

import {xdateToData, parseDate} from '../interface';
import styleConstructor from './style';
import dateutils from '../dateutils';
import Calendar from '../calendar';
import CalendarListItem from './item';

const calendarHeight = 360;
class CalendarList extends Component {
  static propTypes = {
    ...Calendar.propTypes,

    // Max amount of months allowed to scroll to the past. Default = 50
    pastScrollRange: PropTypes.number,

    // Max amount of months allowed to scroll to the future. Default = 50
    futureScrollRange: PropTypes.number,

    // Enable or disable scrolling of calendar list
    scrollEnabled: PropTypes.bool,
  };

  constructor(props) {
    super(props);
    this.pastScrollRange = props.pastScrollRange === undefined ? 50 : props.pastScrollRange;
    this.futureScrollRange = props.futureScrollRange === undefined ? 50 : props.futureScrollRange;
    this.style = styleConstructor(props.theme);
    const rows = [];
    const texts = [];
    const date = parseDate(props.current) || XDate();
    for (let i = 0; i <= this.pastScrollRange + this.futureScrollRange; i++) {
      const text = date.clone().addMonths(i - this.pastScrollRange).toString('MMM yyyy');
      rows.push(text);
      texts.push(text);
    }
    rows[this.pastScrollRange] = date;
    rows[this.pastScrollRange + 1] = date.clone().addMonths(1, true);
    if (this.pastScrollRange) {
      rows[this.pastScrollRange - 1] = date.clone().addMonths(-1, true);
    } else {
      rows[this.pastScrollRange + 2] = date.clone().addMonths(2, true);
    }
    this.state = {
      rows,
      texts,
      openDate: date,
      initialized: false
    };
    this.lastScrollPosition = -1000;
    
    this.onViewableItemsChangedBound = this.onViewableItemsChanged.bind(this);
    this.renderCalendarBound = this.renderCalendar.bind(this);
  }

  scrollToDay(d, offset, animated) {
    const day = parseDate(d);
    const diffMonths = Math.round(this.state.openDate.clone().setDate(1).diffMonths(day.clone().setDate(1)));
    let scrollAmount = (calendarHeight * this.pastScrollRange) + (diffMonths * calendarHeight) + (offset || 0);
    let week = 0;
    const days = dateutils.page(day, this.props.firstDay);
    for (let i = 0; i < days.length; i++) {
      week = Math.floor(i / 7);
      if (dateutils.sameDate(days[i], day)) {
        scrollAmount += 46 * week;
        break;
      }
    }
    this.listView.scrollToOffset({offset: scrollAmount, animated});
  }

  scrollToMonth(m) {
    const month = parseDate(m);
    const scrollTo = month || this.state.openDate;
    let diffMonths = this.state.openDate.diffMonths(scrollTo);
    diffMonths = diffMonths < 0 ? Math.ceil(diffMonths) : Math.floor(diffMonths);
    const scrollAmount = (calendarHeight * this.pastScrollRange) + (diffMonths * calendarHeight);
    //console.log(month, this.state.openDate);
    //console.log(scrollAmount, diffMonths);
    this.listView.scrollToOffset({offset: scrollAmount, animated: false});
  }

  componentWillReceiveProps(props) {
    const current = parseDate(this.props.current);
    const nextCurrent = parseDate(props.current);
    if (nextCurrent && current && nextCurrent.getTime() !== current.getTime()) {
      this.scrollToMonth(nextCurrent);
    }

    const rowclone = this.state.rows;
    const newrows = [];
    for (let i = 0; i < rowclone.length; i++) {
      let val = this.state.texts[i];
      if (rowclone[i].getTime) {
        val = rowclone[i].clone();
        val.propbump = rowclone[i].propbump ? rowclone[i].propbump + 1 : 1;
      }
      newrows.push(val);
    }
    this.setState({
      rows: newrows
    });
  }

  onViewableItemsChanged({viewableItems}) {
    function rowIsCloseToViewable(index, distance) {
      for (let i = 0; i < viewableItems.length; i++) {
        if (Math.abs(index - parseInt(viewableItems[i].index)) <= distance) {
          return true;
        }
      }
      return false;
    }

    const rowclone = this.state.rows;
    const newrows = [];
    const visibleMonths = [];
    for (let i = 0; i < rowclone.length; i++) {
      let val = rowclone[i];
      const rowShouldBeRendered = rowIsCloseToViewable(i, 1);
      if (rowShouldBeRendered && !rowclone[i].getTime) {
        val = this.state.openDate.clone().addMonths(i - this.pastScrollRange, true);
      } else if (!rowShouldBeRendered) {
        val = this.state.texts[i];
      }
      newrows.push(val);
      if (rowIsCloseToViewable(i, 0)) {
        visibleMonths.push(xdateToData(val));
      }
    }
    if (this.props.onVisibleMonthsChange) {
      this.props.onVisibleMonthsChange(visibleMonths);
    }
    this.setState({
      rows: newrows
    });
  }

  renderCalendar({item}) {
    return (<CalendarListItem item={item} calendarHeight={calendarHeight} {...this.props} />);
  }

  getItemLayout(data, index) {
    return {length: calendarHeight, offset: calendarHeight * index, index};
  }

  getMonthIndex(month) {
    let diffMonths = this.state.openDate.diffMonths(month) + this.pastScrollRange;
    return diffMonths;
  }

  render() {
    return (
      <FlatList
        ref={(c) => this.listView = c}
        //scrollEventThrottle={1000}
        style={[this.style.container, this.props.style]}
        initialListSize={this.pastScrollRange * this.futureScrollRange + 1}
        data={this.state.rows}
        //snapToAlignment='start'
        //snapToInterval={calendarHeight}
        removeClippedSubviews={Platform.OS === 'android' ? false : true}
        pageSize={1}
        onViewableItemsChanged={this.onViewableItemsChangedBound}
        renderItem={this.renderCalendarBound}
        showsVerticalScrollIndicator={false}
        scrollEnabled={this.props.scrollingEnabled !== undefined ? this.props.scrollingEnabled : true}
        keyExtractor={(item, index) => index}
        initialScrollIndex={this.state.openDate ? this.getMonthIndex(this.state.openDate) : false}
        getItemLayout={this.getItemLayout}
      />
    );
  }
}

export default CalendarList;

**Comment by dantranv** [comment]
I think I use the most recent from master branch.
[index.zip](https://github.com/wix/react-native-calendars/files/1450238/index.zip)

**Comment by dantranv** [comment]
Hi @JCMais,

is there any update on this? I still see this error.

**Comment by JCMais** [comment]
Hi, sorry @dantranv , I currently am not having time to look into it. 

If anyone can grab this and investigate it's welcome to do so.

**Comment by slorber** [comment]
I can confirm I had this bug with 1.9 on Expo SDK23 and don't have this with 1.11

**Comment by vigneshprabhu20** [comment]
I get this error consistently after upgrading to RN 0.51.0


ExceptionsManager.js:73 Unhandled JS Exception: Invariant Violation: Changing onViewableItemsChanged on the fly is not supported

This error is located at:
    in FlatList (at createAnimatedComponent.js:134)
    in AnimatedComponent (at OutletDetails.js:400)
    in BVLinearGradient (at index.ios.js:72)
    in LinearGradient (at OutletDetails.js:869)
    in OutletDetails (created by inject-OutletDetails-with-outletDetailsStore-outletDetailsStateStore-popupStore-restaurantRatingsStore-restaurantRatingsStateStore-menuAnalysisStore-menuAnalysisStateStore-oosStore-oosStateStore-cancellationsStore-cancellationsStateStore-confirmationsStore-confirmationsStateStore-metricGuideStateStore-popoverStore-trendsOptionsStore-internetConnectivityStore)
    in inject-OutletDetails-with-outletDetailsStore-outletDetailsStateStore-popupStore-restaurantRatingsStore-restaurantRatingsStateStore-menuAnalysisStore-menuAnalysisStateStore-oosStore-oosStateStore-cancellationsStore-cancellationsStateStore-confirmationsStore-confirmationsStateStore-metricGuideStateStore-popoverStore-trendsOptionsStore-internetConnectivityStore (at OutletDetailsScreen.js:12)
    in RCTView (at View.js:112)
    in View (at OutletDetailsScreen.js:10)
    in OutletDetailsScreen (at Navigation.js:83)
    in MobxRnnProvider (at Navigation.js:82)
    in _class2 (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

**Comment by slorber** [comment]
@vigneshprabhu20 please include your react-native-calendars lib version when reporting otherwise nobody can't do anything for you

**Comment by dantranv** [comment]
@vigneshprabhu20 You should revert to 0.49.1 for now.

**Comment by vigneshprabhu20** [comment]
> @vigneshprabhu20 please include your react-native-calendars lib version when reporting otherwise nobody can't do anything for you
> 
> Are you at least sure it's related to this lib? because your stacktrace does not mention the lib

Yes, agree with you its not related to react-native-calendars lib,

**Comment by MustafaZouari** [comment]
iam using hooks,,is there a solution for this
