### ISSUE TITLE
CalendarList refreshcontrol does not work

### ISSUE THREAD

**Issue by Thodor12** [wix/react-native-calendars#2191]
## Description

React-native provides a pull to refresh functionality through the RefreshControl.
The CalendarList component allows you to use these properties as it uses a ScrollView, however these properties don't actually seem to work.
At first glance this doesn't seem like a huge problem because it's more meant to be an "infinite scroll" solution, however my use-case specifically wants to only see 1 month prior and 2 months in the future, more is not needed, so a refresh control is more logical to have.

## Expected Behavior

When scrolling all the way to the top in the CalendarList I'd expect to see the `onRefresh` being fired.

## Observed Behavior

`onRefresh` does not fire.

## Environment

- react-native-calendars@1.1294.0
- react-native@0.71.3

Tested on Android 12

## Reproducible Demo
https://snack.expo.dev/@thodor12/calendarlist-refreshcontrol

**Comment by afx-nicolas** [comment]
Maybe it's a little bit late but I've found a way to implement pull to refresh, you can use the `NewCalendarList` component and pass the `RefreshControl` by `scrollViewProps` and the rest of the props by `calendarProps`, this component has some limitations but you can achieve the pull to refresh.

```ts
<NewCalendarList
  calendarProps={calendarProps}
  scrollViewProps={{
    refreshControl: (
      <RefreshControl
        refreshing={refreshing}
        onRefresh={handleRefresh}
        enabled
      />
    ),
  }}
/>
```
