### ISSUE TITLE
how to edit startingDay,  endingDay style in period type

### ISSUE THREAD

**Issue by student513** [wix/react-native-calendars#2203]
I want to change the style when starting day and ending day are selected as the following image.

<img width="245" alt="스크린샷 2023-04-04 오후 9 54 51" src="https://user-images.githubusercontent.com/50268619/229798187-6b0eb116-3432-44c1-8114-bc0b1edd6e74.png">

However, the following code could not produce the results I wanted. 

<img width="171" alt="스크린샷 2023-04-04 오후 10 04 57" src="https://user-images.githubusercontent.com/50268619/229800684-4334afa8-f445-433f-a787-99c42e0e9910.png">

I want border-radius to be applied to all four corners of the indicated date. However, the rendered results are applied only to the top left and bottom left. How should I fix it?

**Comment by MursiDirect** [comment]
@student513  I wonder if you found a solution for this, I want to do the same
