### ISSUE TITLE
CalendarList: ScrollToMonth not executing when scrolling to the maximum pastScrollRange

### ISSUE THREAD

**Issue by pandu-supriyono** [wix/react-native-calendars#2205]
Hi, thanks for the lib.

## Description

When having set the `pastScrollRange` prop and using the exposed `scrollToMonth` callback (for example a button higher up in the tree), I can scroll at most to one month _after_ the minimum month specified in `pastScrollRange`. That is, the month `n + 1` where `n` is the month that corresponds with `pastScrollRange`. 

## Expected Behavior

I expect to be able to scroll up to and including the month specified in `pastScrollRange`. I.e. if the initial viewable month is April and I set `pastScrollRange` to 2, I should be able to scroll down to February and not earlier.

## Observed Behavior

There is no change in the currently viewed month. I.e. If `pastScrollRange` is set to 2 and the (initial) viewable month is April 2023, calling `scrollToMonth` with `2023-02` results in the viewable month remaining in April.

I believe that is because [`scrollAmount` is always computed to be 0 if the target month corresponds with the month in `pastScrollRange`](https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/index.tsx#L181). As such, the method to scroll to the offset is not executed because it is conditionally executed when `scrollAmount` is not equal to `0`.

## Environment

* `react-native-calendars@1.1294.0`
* `react-native@0.68.5`

## Possible solutions

We have patched our app with the following changes in order to achieve the expected behaviour:

```tsx
const scrollToMonth = useCallback((date: XDate | string) => {
  const scrollTo = parseDate(date);
  const diffMonths = Math.round(initialDate?.current?.clone().setDate(1).diffMonths(scrollTo?.clone().setDate(1)));
  const scrollAmount = calendarSize * pastScrollRange + diffMonths * calendarSize;

  const minScrollAmount = pastScrollRange * calendarSize + calendarSize * -1;
  const maxScrollAmount = futureScrollRange * calendarSize + calendarSize;

  if (scrollAmount >= minScrollAmount && scrollAmount <= maxScrollAmount) {
    // @ts-expect-error
    list?.current?.scrollToOffset({offset: scrollAmount, animated: animateScroll});
  }
}, [calendarSize]);
```

The diff:

```diff
@@ -180,7 +180,10 @@ const CalendarList = (props: CalendarListProps & ContextProp, ref: any) => {
     const diffMonths = Math.round(initialDate?.current?.clone().setDate(1).diffMonths(scrollTo?.clone().setDate(1)));
     const scrollAmount = calendarSize * pastScrollRange + diffMonths * calendarSize;
 
-    if (scrollAmount !== 0) {
+    const minScrollAmount = pastScrollRange * calendarSize + calendarSize * -1;
+    const maxScrollAmount = futureScrollRange * calendarSize + calendarSize;
+
+    if (scrollAmount >= minScrollAmount && scrollAmount <= maxScrollAmount) {
       // @ts-expect-error
       list?.current?.scrollToOffset({offset: scrollAmount, animated: animateScroll});
     }
```

**Comment by sleekLancelot** [comment]
This bug is still present till date, I tried using your hack but it didn't work for me. The codebase has changed a lot since this post.
Has anyone been able to solve this?

**Comment by akramloginext** [comment]
Any solution for this bug?

**Comment by sleekLancelot** [comment]
we need this issue reopened as it hasn't been resolved.
