### ISSUE TITLE
disable date range

### ISSUE THREAD

**Issue by pvinis** [wix/react-native-calendars#225]
## Description

i would like to be able to say that every date before today, should be disabled. there is the disabledByDefault, and disabled on the markeddate, but i want basically to have disabled everything before date X, and enabled after date X, inclusive.

## Expected Behavior

to have a prop like disabledRange or disabledBefore.

## Observed Behavior

i think there is nothing like that.

**Comment by jaruyot** [comment]
@pvinis Have you tried minDate and maxDate props? The dates before minDate and after maxDate will be disabled. Or perhaps you want to disable a range of dates in between?

**Comment by pvinis** [comment]
oh oops. i didnt even notice, and i read the readme. sorry. thank you for your answer. closing this now :)
