### ISSUE TITLE
Know when Knob has been clicked

### ISSUE THREAD

**Issue by wuno** [wix/react-native-calendars#226]
## Description

When the knob is clicked to open the calendar month view I want to know. Is there a way to keep track of the knob being triggered? I cant override it because it appears to be wrapped in a TouchableOpacity already. 

## Expected Behavior

I looked to see if there was a prop I could tie into. It appears there is not. I cant find a way to know if the knob has been clicked.

## Observed Behavior

The calendar month view pops up from Agenda view. when the knob is clicked. But I need a way to know thats happened so I can deal with some other thing in the app. 

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.5.8 

react-native@0.44.0 

Ios 11 iphone x

## Reproducible Demo

So this is me calling the Agenda View. I just want to know when the knob is clicked to activate the calendar month view. 

```
<Agenda
                    onDayPress={(date) => { this.getMonth(date.month); }}
                    onDayChange={(date) => { this.getMonth(date.month); }}
                    items={this.state.days}
                    loadItemsForMonth={this.loadItems}
                    selected={this.props.selectedDate}
                    renderItem={this.renderItem}
                    rowHasChanged={this.constructor.rowHasChanged}
                    renderEmptyDate={this.constructor.renderEmptyDate}
                    theme={{
                        dotColor: GlobalVariables.secondaryColor,
                        selectedDayBackgroundColor: GlobalVariables.secondaryColor,
                        todayTextColor: GlobalVariables.secondaryColor,
                        agendaTodayColor: GlobalVariables.secondaryColor,
                    }}
                />

```

**Comment by dborstelmann** [comment]
#227

**Comment by tautvilas** [comment]
Hey, please use onCalendarToggled
