### ISSUE TITLE
CalendarProvider triggers PageScroll and changes week

### ISSUE THREAD

**Issue by JuliaSzymanskaFirmao** [wix/react-native-calendars#2265]
## Description

I use CalendarProvider with ExpandableCalendar and TimelineList. 
## Expected Behavior

When I enter into the screen with calendar it should open at today date (specified by currentDate). 

## Observed Behavior

Sometimes, the CalendarProvider triggers the "pageScroll" action and reverts to the previous week, despite setting the date property correctly (my currentDate variable remains today). How can I prevent it from going back a week?

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1299.0
* `npm ls react-native`: react-native@0.68.2

Also specify:

1. Device/emulator/simulator & OS version:
Device & emulator & simulator - Android 13 (on other version also)

## Reproducible Demo

```JavaScript
const [currentDate, setCurrentDate] = React.useState<string>(getDate());
  <CalendarProvider
            date={currentDate}
            onDateChanged={onDateChanged}
            onMonthChange={onMonthChange}
            showTodayButton
            timelineLeftInset={55}
        >
            <ExpandableCalendar
                firstDay={1}
                date={currentDate}
                markedDates={eventEntries.marked}
                animateScroll
            />
            <TimelineList
              events={groupEventsByDay(eventEntries.timeEntries)}
              timelineProps={{
                  format24h: true,
                  start: 0,
                  end: 24,
                  overlapEventsSpacing: 6,
                  rightEdgeSpacing: 8,
                  renderEvent: (event) => {
                      return <CalendarEvent event={event} handleOnPress={handleOnEventPress} />;
                  },
              }}
              showNowIndicator
              scrollToNow
          />
/>
```

## Screenshots
![Github](https://github.com/wix/react-native-calendars/assets/93980698/028fd703-601a-4543-a514-4403548d0cd6)

**Comment by pavelpashkovsky** [comment]
Hey, try adding some key to make CalendarProvider rerender itself on each update. For some reason it doesn't do this.
`<CalendarProvider
        key={new Date().getTime()}`

**Comment by JuliaSzymanskaFirmao** [comment]
The problem was solved after downloading the latest version of the library 1.1307.0
