### ISSUE TITLE
How to prevent CalendarList from re-rendering every item?

### ISSUE THREAD

**Issue by stevengoldberg** [wix/react-native-calendars#2275]
## Description

When I update app state, my CalendarList re-renders every item in the grid, even though all but one should be the same as the previous render.

## Expected Behavior

Usecase: at the top level, my app has a tab navigator with a Calendar tab and a Camera tab. In the Calendar tab, it displays an infinitely scrollable CalendarList using `react-native-calendars`. The app state maintains an object with date strings as keys and sorted arrays of images as values. The calendar's parent view passes it a memoized object containing the last image for each date via context:

```
const latestImagesByDateString = useMemo(
    () => mapLatestImagesByDateString(imagesByDateString),
    [imagesByDateString]
)

// ...

<ImageContext.Provider value={latestImagesByDateString}>
    <Stack.Screen
        name="CalendarView"
        component={CalendarView}
                            
    />
</ImageContext.Provider>
```

The CalendarView renders a component for each date, which may have an image:

```
const getDayComponent = useCallback(
    ({ date, state }) => (
        <CalendarDayView
            imageUri={latestImagesByDateString[date.dateString]?.uri}
            imageId={latestImagesByDateString[date.dateString]?.id}
            isToday={state === 'today'}
            dateString={date.dateString}
            day={date.day}
         />
     ),
     [latestImagesByDateString]
)

// ...

return (
   <CalendarList
       dayComponent={getDayComponent}
   />
)
```

The Calendar tab has a stack navigator which renders a detail view for a given day when it gets pressed. This is all working as intended.

However, if I navigate to the Camera tab, the user can take a photo, which they can then save or discard. If they save the photo, I update app state with the new photo, then navigate back to the Calendar tab's detail view for that day, showing the new photo.

## Observed Behavior

The above also works as intended, **except**: when I save the photo and navigate to the appropriate detail view, the Calendar will re-render every date in its grid before the detail view gets displayed. This causes a long delay between pressing the "Save photo" button and the detail view being rendered onscreen. When a user saves a new photo, all of the dayComponents except one should be the same as on the previous render. How can I prevent that from happening?

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1298.0
* `npm ls react-native`: react-native@0.71.8

Also specify:

1. Device/emulator/simulator & OS version: iPhone 14 OS 16.5.1

**Comment by baesumin** [comment]
+1
