### ISSUE TITLE
custom marking is not enhanced automatically with selected day anymore

### ISSUE THREAD

**Issue by slorber** [wix/react-native-calendars#229]
https://github.com/wix/react-native-calendars/commit/db53a62923e0368d2ef81e88e819710a7e222be5

This commit is a regression for my app that needs both custom marking + ability to highlight the selected day: we should be able to do both imho

For me it makes sense (at least in normal/day marking) that you add dynamically the {selected: true} to the props marking, because there's no other way the user can do that as selectedDay is in inner component state.

**Comment by tautvilas** [comment]
Fixed in 1.10.0

**Comment by slorber** [comment]
thanks it seems to work
