### ISSUE TITLE
Calendar List just show title when current date reach the end of month

### ISSUE THREAD

**Issue by gosu4991** [wix/react-native-calendars#2299]
Hi, I use Agenda for my app and get a problem is that: when the current date is reaching of the end of month it's will only show a title, but another day is normal.
see my picture below

*date is not end of month
![calendar_normal](https://github.com/wix/react-native-calendars/assets/87606753/bd271ed5-d1ee-4120-b6cd-00b6adcad26e)

*date is end of month
![calendar_bug](https://github.com/wix/react-native-calendars/assets/87606753/1117bb41-bd07-4402-9418-2c6fd8a6dfe5)

when I scroll down it will become normal. 
how can I fix it ?.
Thanks

**Comment by Bengejd** [comment]
I was experiencing this as well, until I realized that I was scrolling on the `parent view` and not the `CalendarList`. Once I made sure that the parent could not scroll, the issue went away and it properly renders & loads the dates as expected.

**Comment by gosu4991** [comment]
> I was experiencing this as well, until I realized that I was scrolling on the `parent view` and not the `CalendarList`. Once I made sure that the parent could not scroll, the issue went away and it properly renders & loads the dates as expected.

Hi, I tried to use the example from this library and set current date is '2023-07-31' and I get this bug, can you give me some idea to fix it. Thanks

**Comment by stovein** [comment]
this seems to the problem we are having @oguzydz

**Comment by juspeeh** [comment]
I noticed the same issue. When `selected` property for `Agenda` is set to the last day of the month the next month will not render anything but the date as title in `YYYY-MM-DD` format. Scrolling further down will indeed render the next month. I don't have any another scrollable elements in the screen.

**Comment by juspeeh** [comment]
I was running version `1.1279.0` and updating to the latest `1.1300.0` seemed to solve the issue for me.

**Comment by gosu4991** [comment]
issue is resolve

**Comment by sleekLancelot** [comment]
This bug still exists on `"react-native-calendars": "^1.1307.0",`

**Comment by kiratot** [comment]
We're using "react-native-calendars": "1.1303.0" in production and the issue is not happening for iOS, maybe the newer updates introduced the same bug or something else did. I'll check when I have some time

**Comment by sleekLancelot** [comment]
> We're using "react-native-calendars": "1.1303.0" in production and the issue is not happening for iOS, maybe the newer updates introduced the same bug or something else did. I'll check when I have some time

Thanks
