### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by BTLundy97** [wix/react-native-calendars#230]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I implemented Agenda, but I keep getting an invalid date error.
1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
I implemented Agenda almost exactly as it was implemented in the example screens, and expected to have a scrolling Agenda component very similar to the one 
What action did you perform, and what did you expect to happen?

## Observed Behavior
I got an error
What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:
![image-1](https://user-images.githubusercontent.com/31375895/32612374-c0961c06-c52d-11e7-8154-dc82d188798e.jpg)

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by BTLundy97** [comment]
Just realized I forgot to post a snippet of the code. Here you go. Keep in mind that this is a group project, so I won't be able to make changes to anything that doesn't directly involve the Agenda component. By the way, I am using Expo 2.0.4.1010430 on an iPhone 6s.


import React, { Component } from 'react';
import {
    StyleSheet, Text, View, Image, Dimensions,
    TouchableOpacity, AppRegistry, Alert, ScrollView
} from 'react-native';
import {Calendar, CalendarList, Agenda} from 'react-native-calendars'
import { StackNavigator } from 'react-navigation';
import { Constants,} from 'expo';

var screenWidth = Dimensions.get('window').width;
var screenHeight = Dimensions.get('window').height;

export default class PlannerScreen extends React.Component {
	constructor(props) {
		super(props);
		
		this.loadItems = this.loadItems.bind(this)
		this.renderItem = this.loadItems.bind(this)
		this.renderEmptyDate=this.renderEmptyDate.bind(this)
		this.rowHasChanged=this.rowHasChanged.bind(this)
		this.state = {
		items: {}
		};
		
	}
    static navigationOptions = {
        title: 'Planner',
        headerLeft: null,
        headerStyle: {
            paddingTop: Constants.statusBarHeight,
            height: 60 + Constants.statusBarHeight,
            backgroundColor: '#99ccff'
        },
    };

	loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
        if (!this.state.items[strTime]) {
          this.state.items[strTime] = [];
          const numItems = Math.floor(Math.random() * 5);
          for (let j = 0; j < numItems; j++) {
            this.state.items[strTime].push({
              name: 'Item for ' + strTime,
              height: Math.max(50, Math.floor(Math.random() * 150))
            });
          }
        }
      }
      //console.log(this.state.items);
      const newItems = {};
      Object.keys(this.state.items).forEach(key => {newItems[key] = this.state.items[key];});
      this.setState({
        items: newItems
      });
    }, 1000);
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }
   renderItem(item) {
    return (
      <View style={[styles.item, {height: item.height}]}><Text>{item.name}</Text></View>
    );
  }

 renderEmptyDate() {
    return (
      <View style={styles.emptyDate}></View>
    );
  }

rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split('T')[0];
  }
    render() {
		
        const { navigate } = this.props.navigation;
        return (
            <View style={styles.container}>
					<Agenda
						items={this.state.items}
						loadItemsForMonth={this.loadItems}
						markedDates={{[this.state.selected]: {selected: true}}}
						renderItem={this.renderItem}
						renderEmptyDate={this.renderEmptyDate}
						rowHasChanged={this.rowHasChanged}
						markingType={'interactive'}
						theme={{calendarBackground: 'white', agendaTodayColor: '#e6eeff', agendaKnobColor: '#99ccff'}}
						renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
						minDate={'2013-11-09'}
						maxDate={'2012-11-09'}

					/>
                <View style={styles.aMenu}>
                    <View style={styles.bMenu}>
                        <TouchableOpacity onPress={() => navigate('Inventory')}>
                            <Image source={require('./Assets/clipboard.png')} style={styles.mButtons} />
                        </TouchableOpacity>
                    </View>
                    <View style={styles.bMenu}>
                        <TouchableOpacity onPress={() => navigate('Recipes', { input: "" })}>
                            <Image source={require('./Assets/book.png')} style={styles.mButtons} />
                        </TouchableOpacity>
                    </View>
                    <View style={styles.bMenu}>
                        <TouchableOpacity>
                            <Image source={require('./Assets/aCalendar.png')} style={styles.mButtons} />
                        </TouchableOpacity>
                    </View>
                    <View style={styles.bMenu}>
                        <TouchableOpacity onPress={() => navigate('Settings')}>
                            <Image source={require('./Assets/settings.png')} style={styles.mButtons} />
                        </TouchableOpacity>
                    </View>
                </View>
            </View>
        );
    }
}


const styles = StyleSheet.create({

    top: {
        flex: 1,
        backgroundColor: '#e6eeff',
        alignItems: 'flex-start',
    },

    aMenu: {
        height: screenHeight * 0.10,
        width: screenWidth,
        flexDirection: 'row',
        backgroundColor: '#F5FCFF',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
    },

    bMenu: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#F5FCFF',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
    },

    mButtons: {
        width: screenWidth * 0.25,
        height: screenHeight * 0.10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FF9E24',
    },
    
	calendar: {
		borderTopWidth: 1,
		paddingTop: 0,
		borderBottomWidth: 1,
		borderColor: '#eee',
        height: screenHeight- (60+ Constants.statusBarHeight) - (screenHeight*.10),
        width: screenWidth
	},
	text: {
		textAlign: 'center',
		borderColor: '#bbb',
		padding: 10,
		backgroundColor: '#eee'
	},
	container: {
		flex: 1,
		backgroundColor: 'gray',
		height: screenHeight- (60+ Constants.statusBarHeight) - (screenHeight*.10),
        width: screenWidth
	},
	item: {
    backgroundColor: 'white',
    flex: 1,
    borderRadius: 5,
    padding: 10,
    marginRight: 10,
    marginTop: 17
  },
  emptyDate: {
    height: 60,
    flex:1,
    paddingTop: 30
}

});

**Comment by tautvilas** [comment]
It's because of this...

this.renderItem = this.loadItems.bind(this)

**Comment by BTLundy97** [comment]
Thanks
