### ISSUE TITLE
Not able to select past date. 

### ISSUE THREAD

**Issue by KalpeshVenturit** [wix/react-native-calendars#231]
## Description
I'm trying to add selected date in markedDates with selected=true. It works perfect for dates after Today's date. But, it does not select previous dates.

## Expected Behavior
User can able to select any date.

## Observed Behavior
for older dates, it just blinked and not showing selected circle.

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.9.2
* `npm ls react-native`: react-native@0.38.0

**Comment by tautvilas** [comment]
hey, please add code snippet to reproduce

**Comment by KalpeshVenturit** [comment]
@tautvilas Thanks for looking in to this but it seems Date format issue. I was using "yyyy-MM-d". When i changed it to "yyyy-MM-dd". I didn't realised this when i reported the issue because unfortunately it was 10th :) . So its not like previous date but selecting single digit date :) 

It would be great if you add support for as much as date formats.
