### ISSUE TITLE
Overlapping marked dates

### ISSUE THREAD

**Issue by sebastianjung** [wix/react-native-calendars#2314]
## Description
Not sure if a bug report or a feature request. I think it's similar to [this](https://github.com/wix/react-native-calendars/issues/2291)

I want the calendar to behave similar to this:
![image](https://github.com/wix/react-native-calendars/assets/17472892/0ca5ebc2-952e-4530-a46f-74c31ba10e00)

this is the closest i can get:
![photo1692708700](https://github.com/wix/react-native-calendars/assets/17472892/b344fdc6-7097-4934-b9d6-db7c91153635)

What properties would i need to give the MarkedDates to have such behaviour?

I probably have to use a custom day component via dayComponent prop?

Appreaciate your help.

**Comment by fmujjwalmanandhar** [comment]
You can achieve above implementation by using markedDates as follow:

markingType="period"
markedDates= {"2023-09-11": {"color": "#4E6CFF", "marked": false, "startingDay": true, "textColor": "#FFFFFF"}, "2023-09-12": {"color": "#F1F4FF", "marked": false, "textColor": "#4E6CFF"}, "2023-09-13": {"color": "#F1F4FF", "marked": false, "textColor": "#4E6CFF"}, "2023-09-14": {"color": "#F1F4FF", "marked": false, "textColor": "#4E6CFF"}, "2023-09-15": {"color": "#4E6CFF", "endingDay": true, "marked": false, "textColor": "#FFFFFF"}}

let me know if there's something

**Comment by sebastianjung** [comment]
@fmujjwalmanandhar 

Thank you for helping me out!

It seems your code does not what i want. Have a look at what your example produces:
![image](https://github.com/wix/react-native-calendars/assets/17472892/0658ff03-f136-4bf4-808b-df088e85449d)

What i actually need is the marking in the middle (light blue) to have rounded borders as well so that the dark blue would "sit" behind it (see my first image in this thread).

Am I doing something wrong here?

**Comment by fmujjwalmanandhar** [comment]
What do you mean by rounder borders in the middle (light blue)
Isn't above implementation same as described in the thread.
https://user-images.githubusercontent.com/17472892/262354948-0ca5ebc2-952e-4530-a46f-74c31ba10e00.png

**Comment by sebastianjung** [comment]
Sorry for making this so confusing.

What i currently have is this:
![image](https://github.com/wix/react-native-calendars/assets/17472892/d5a605b1-cd9c-4ade-8cea-4ba8530b2965)


What i need is this:
![image](https://github.com/wix/react-native-calendars/assets/17472892/9178dc70-fe71-483f-bbde-f494842157b6)

So basically be able to give day 5 and day 6 a second color (background) which sits behind the red color.

I hope this makes things clear. 

Appreciate your help 🙏

**Comment by sebastianjung** [comment]
So i was able to fix this by changing the libraries code to the following:

```js
// react-native-calendars/src/calendar/day/period/index.js

...
const fillerStyles = useMemo(() => {
  const leftFillerStyle = { backgroundColor: undefined };
  const rightFillerStyle = { backgroundColor: undefined };
  let fillerStyle = {};
  const start = markingStyle.startingDay;
  const end = markingStyle.endingDay;
  if (start && !end) {
      rightFillerStyle.backgroundColor = markingStyle.startingDay?.backgroundColor;
      leftFillerStyle.backgroundColor = marking.fillerColor;
  }
  else if (end && !start) {
      leftFillerStyle.backgroundColor = markingStyle.endingDay?.backgroundColor;
      rightFillerStyle.backgroundColor = marking.fillerColor;
  }
  else if (markingStyle.day) {
      leftFillerStyle.backgroundColor = markingStyle.day?.backgroundColor;
      rightFillerStyle.backgroundColor = markingStyle.day?.backgroundColor;
      fillerStyle = { backgroundColor: markingStyle.day?.backgroundColor };
  }
  return { leftFillerStyle, rightFillerStyle, fillerStyle };
 }, [marking]);
 ...

```

Note that i added lines
`leftFillerStyle.backgroundColor = marking.fillerColor;`
and 
`rightFillerStyle.backgroundColor = marking.fillerColor;`

Through this markedDates basically allow for another property called fillerColor which acts as a background behind the starting- or endday marking.

Is this something you want to add to the library or should I just implement it myself (via custom day component prop)?
