### ISSUE TITLE
Daylight savings duplicates date display in some regions

### ISSUE THREAD

**Issue by systemride** [wix/react-native-calendars#2321]
On September 3, 2023 the timezone of `America/Santiago` (Santiago Chile) adjusted their daylight savings at midnight. At the start of DST, the clocks go forward one hour at midnight. This effectively means that 24:00 (end of day) of the day before DST becomes 01:00 of the DST day. So, an entire hour is skipped.

Given that, on September 3rd, when DST was supposed to start:

- Midnight at the end of September 2nd (24:00) instantly became 01:00 on September 3rd.
- Therefore, the entire hour from 00:00 to 00:59 on September 3rd never occurred in local time!

How this comes into play is that when generating a list of dates to display for the calendar month, all times are set to Midnight by default. If you are in the Santiago timezone and you create a new date for midnight, September 3rd, this date doesn't exist. This ends up creating two September 2nd dates as you'll see below.

![calendar](https://github.com/wix/react-native-calendars/assets/1361/867e4ceb-b7fd-4f78-af59-45463f59e13f)

If you log the `_date` on [this line here](https://github.com/wix/react-native-calendars/blob/0f503e0560082780ead2dec1f9ee7b70902eba1c/src/calendar/day/index.tsx#L72) you will see:
```
2023-09-03T03:00:00.000Z
```

However, once you call `_date?.getDate()` like it does below, then you will get `2` because of what I explained above.

I have verified this in the latest version `1.1301.0`.

Also, [there are a handful of timezones/countries](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country) that have daylight savings time take place at midnight.

Perhaps this is a bug with xdate, but one possible workaround would be to set the times to 12 noon by default instead of midnight.

**Comment by systemride** [comment]
Closing, looks like this is actually a hermes issue:
https://github.com/facebook/hermes/issues/1121

**Comment by antoniopro7** [comment]
Did anyone find a solution or workaround? I'm having the same issue
