### ISSUE TITLE
Show only 1 week dates as a row

### ISSUE THREAD

**Issue by udayasri** [wix/react-native-calendars#235]
Hi , 
Is there any way to show only Agenda header ( dates as a row ) without agenda items . I wanted to show the dates as a row , not the full calendar. 

Thanks in advanced.

**Comment by tautvilas** [comment]
Hi, currently, no, this is duplicate request of #84

**Comment by ihsanktmr** [comment]
I have temporary solution check my comment here https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538
