### ISSUE TITLE
Calendar is calling 'loadItemsForMonth' twice when month is changed

### ISSUE THREAD

**Issue by nichesoftgh04** [wix/react-native-calendars#237]
## Description
I am using Agenda of calendar. When i am on 1st of some month and then i click on the 30th of the previous month the function 'loadItemsForMonth' is called twice first time with clicked date of the previous month(30 here) and second time with today's date in last month and after this call spinner keeps rotating.

## Expected Behavior
It should not show continuously rotating spinner while data is given.  

In both calls to 'loadItemsForMonth' though i am returning either empty array if it is empty or data but yet it keeps waiting as mentioned in documentation that it waits if data is not available for selected data.
Note: It's only happening when selecting dates at the start of the month(1,2,3) and at the end of the previous month(30, 31 etc).

**Comment by sondoan1204** [comment]
me too

**Comment by tautvilas** [comment]
It's true that loadItems work flaky in this situation, however you should merge results of both loads to same object and pass this items object with complete loaded data to agenda, this way you would not have infinite spinner. Also please check this thread. #24

**Comment by nichesoftgh04** [comment]
@tautvilas Is it fixed? I am facing issue: content is only visible when user selects date otherwise it shows 'no item'. `
<Agenda
            items={this.getTripObjects()}
            loadItemsForMonth={this.loadItems.bind(this)}
            onDayPress={this.onDayPress.bind(this)}
            renderEmptyDate={this.renderEmptyDate.bind(this)}
            selected={moment().format('YYYY-MM-DD')}
            renderItem={this.renderItem.bind(this)}
            rowHasChanged={this.rowHasChanged.bind(this)}
            scrollEnabled={true}
            markedDates={(this.props.tripDetails) ? this.dataToMarkDates(this.props.tripDetails.result) : {}}
          />
`
This is my agenda code. getTripsObjects function returns an object for whole month according to data. Is there any flaw in implementation? I am also using your temp. solution you suggested for stopping spinner.

**Comment by tautvilas** [comment]
Hi, could you provide a more comprehensive code example? I recommend that you would check agenda example in calendars demo project

**Comment by tautvilas** [comment]
closing due inactivity

**Comment by ManishAhire** [comment]
Same issue

**Comment by claudiozam** [comment]
Same issue

**Comment by Arslan106** [comment]
same issue

**Comment by gkasireddy202** [comment]
same issue
