### ISSUE TITLE
calendarlist rendering issue

### ISSUE THREAD

**Issue by smallmachines-hyunho** [wix/react-native-calendars#2394]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

i'm having rendering problem for calendarlist, it doesn't appear before i slide the calendarlist.
please help me to solve this problem.

<CalendarList
                style={{marginTop: 0,
                    width: Dimensions.get('window').width,
                    alignSelf: 'center',}}
                
                theme={{todayTextColor: 'red',
                    textDayFontSize: 16,
                    textDayFontWeight: 'bold',
                    textMonthFontSize: 18,
                    textMonthFontWeight: 'bold',
                    textSectionTitleColor: 'rgba(138, 138, 138, 1)',
                    // dayTextAtIndex1: { color: 'red' }
                }}

                markingType={"period"}
                markedDates={markedSelectedDates}
                onDayPress={onDayPress}
                onVisibleMonthsChange={(months) => {console.log('보고 있는 달력 월', months);}}
                monthFormat={"yyyy년 MM월"}
                pastScrollRange={12}
                futureScrollRange={1}
                scrollEnabled={true}
                horizontal={true}
                pagingEnabled={true}
                hideArrows={false}
                renderArrow={renderArrow}
                // disabledDaysIndexes={[0]}
                hideExtraDays={false}

            />

## Environment

im doing it with react native.

## Screenshots

![image](https://github.com/wix/react-native-calendars/assets/153584201/703ec4e4-3213-487e-b4c2-e7785f6ea823)
![image](https://github.com/wix/react-native-calendars/assets/153584201/068c48cf-6bd6-4643-b5bc-58ed63001cf7)

**Comment by smallmachines-hyunho** [comment]
solved. it was because of current={} props. thanks

**Comment by menadeth** [comment]
> solved. it was because of current={} props. thanks

i also use this resolve the same issue with you thanks
