### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nickitatkach** [wix/react-native-calendars#240]
Hello.

Do you plan to add Typescript support?

**Comment by tautvilas** [comment]
Hi, currently Typescript support is not in our plans

**Comment by DavidNorena** [comment]
why not ? a lot of people uses now typescript :(

**Comment by RafaelKr** [comment]
I also would like to have typescript support. It's really common to use typescript.

**Comment by DavidNorena** [comment]
@RafaelKr @nickitatkach, there you have it [@types/react-native-calendars](https://www.npmjs.com/package/@types/react-native-calendars)

**Comment by chubecode** [comment]
> @RafaelKr @nickitatkach, there you have it [@types/react-native-calendars](https://www.npmjs.com/package/@types/react-native-calendars)

Hi bro, I got crash issue after install it..
Do you meet it before? If so can you share me how to fix it ? Thanks

`java.lang.ClassNotFoundException: Didn't find class "xxx.xx.MainApplication" on path: DexPathList`
