### ISSUE TITLE
Docs: How to livesync when developing locally?

### ISSUE THREAD

**Issue by pavloko** [wix/react-native-calendars#242]
I was wondering how do main contributors to this library develop locally?

I searched documentation and couldn't find a clear way how to setup a development workflow.

What I'd like to have:
1. I run an example app in examples folder.
2. I make changes to the code in src, for example `calendars.js`. 
3. I get the changes synced in the emulator.

What I've tried/have in mind:
1. `npm link, npm link react-native-elements` --> doesn't work with React Native.
2. making changes in `example/node_modules`. Not ideal if you're making lots of changes in different files.
3. Another option might be setting up storybook.

Thanks and I really appreciate your input on these.

**Comment by tautvilas** [comment]
Hi, previously I used yarn link, but it stopped working after RN upgrade. Currently I am just copy-pasting sources manually to example node_modules. I'm also interested what would be the easiest solution to livesync while developing.

**Comment by pavloko** [comment]
Hi @tautvilas. I think right now the best option is to use [Haul](https://github.com/callstack/haul) in the example project that way `yarn link` will work. This is happening because Metro bundler [doesn't support symlinks.](https://github.com/facebook/metro-bundler/issues/1)
