### ISSUE TITLE
Expandable calendar always shows the first day auto selected

### ISSUE THREAD

**Issue by fahimshah36** [wix/react-native-calendars#2442]
Expandable calendar always shows the first day of week or first day of month auto selected. How can I turn it off?
I need to scroll the calendar.
Any way to patch package and change it? Any insights will be helpful, thanks

**Comment by poinch** [comment]
Same problem for me, any suggestion to remove default selected day in the exapandable calendar?

**Comment by zkteco-home** [comment]
what's your expection?
      <CalendarProvider
        date={selectedDate}
        onDateChanged={onDateChanged}
 

     
        
      >
        <ExpandableCalendar

>
</CalendarProvider>

you can set date to show your date

**Comment by fahimshah36** [comment]
> what's your expection? <CalendarProvider date={selectedDate} onDateChanged={onDateChanged}
> 
> ```
>   >
>     <ExpandableCalendar
> ```
> 
> > 
> 
> you can set date to show your date

Yes, but when I swipe to the previous week or the next week, the first day of the week is auto selected.

**Comment by Mr-unick** [comment]
try to use WeekCalendar instead of ExpandableCalendar ,
and use this patch mehtod
https://github.com/wix/react-native-calendars/issues/1937

**Comment by TarekMunshi** [comment]
> Expandable calendar always shows the first day of week or first day of month auto selected. How can I turn it off? I need to scroll the calendar. Any way to patch package and change it? Any insights will be helpful, thanks

accha accha

**Comment by fahimshah36** [comment]
Okay, so I have managed to get a solution for this. If anyone else has a better solution please comment below.
So using  patch-package>react-native-calendars.
3 files needed modifications. These are-
**node_modules\react-native-calendars\src\expandableCalendar\WeekCalendar\index.js
node_modules\react-native-calendars\src\expandableCalendar\week.js
node_modules\react-native-calendars\src\day-state-manager.js**

On WeekCalendar\index.js, 
 I took a useState which saves the selected date on press- 
`    const [selectedDay, setSelectedDay] = useState(date);
`then, look for _onDayPress, inside which I did- setSelectedDay(value.dateString). SO the _onDayPress function now looks like this- 
```
const _onDayPress = useCallback((value) => {
        setSelectedDay(value.dateString)
        if (onDayPress) {
            onDayPress(value);
        }
        else {
            setDate?.(value.dateString, UpdateSources.DAY_PRESS);
        }
    }, [onDayPress]);
```
Then , I passes the selectedDay as prop to Week inside of renderItem, so renderItem now looks like this- 
```
 const renderItem = useCallback(({ item }) => {
        const currentContext = sameWeek(date, item, firstDay) ? context : undefined;
        const markings = getCurrentWeekMarkings(item, markedDates);
        return (<Week {...others} selectedDay={selectedDay} markedDates={markings} current={item} firstDay={firstDay} style={weekStyle} context={currentContext} onDayPress={_onDayPress} numberOfDays={numberOfDays} timelineLeftInset={timelineLeftInset}/>);
    }, [firstDay, _onDayPress, context, date, markedDates]);
```

Next, on week.js, pass down the selectedDay from props to getState function. Search for getState on the <Day...> component. 
`state={getState(day, currXdate, props, disableDaySelection,selectedDay)}`

And finally, on day-state-manager.js, I compared the day prop and selectedDay prop and removed the first day of week from SELECTED state. you can replace the code with this- 
```
const { isToday, isDateNotInRange, sameMonth } = require('./dateutils');
const { toMarkingFormat } = require('./interface');
function convertDateString(dateString) {
    const date = new Date(dateString);
    
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    
    return `${year}-${month}-${day}`;
}

export function getState(day, current, props, disableDaySelection) {
    const { minDate, maxDate, disabledByDefault, context,selectedDay } = props;
    let state = '';
        if(!disableDaySelection && ((context?.date ?? toMarkingFormat(current)) === toMarkingFormat(day)) && 
        convertDateString(day)===selectedDay && day.getDay() === 0){
        state = 'selected';

        }
    
    else if (!disableDaySelection && ((context?.date ?? toMarkingFormat(current)) === toMarkingFormat(day)) 
    && day.getDay() !== 0
) {
    
        state = 'selected';
    }
    else if (isToday(day)) {
        state = 'today';
    }
    else if (disabledByDefault) {
        state = 'disabled';
    }
    else if (isDateNotInRange(day, minDate, maxDate)) {
        state = 'disabled';
    }
    else if (!sameMonth(day, current)) {
        state = 'disabled';
    }
    return state;
}
```

**Comment by poinch** [comment]
I've tried your solution but unfortunatly the default day remain selected.
Do you mind to share your code so i can compare it whit mine?

**Comment by poinch** [comment]
I've actually made it to work as you but unfortunatly this is not my problem, thank you anyway
