### ISSUE TITLE
selecting multiple dates

### ISSUE THREAD

**Issue by tc0087** [wix/react-native-calendars#245]
I am trying to select multiple dates on the Calendar component.  My date object is updating in state but the Calendar is not updating to reflect the selected days. Is it possible to select multiple dates on the Calendar component and have the Calendar update to reflect those selections? Thanks!

**State**

```
this.state = {
    dates: {}
}
```

**Function**

```
  selectDate(day){
    let selectedDate = day.dateString;
    if(this.state.dates[selectedDate]){
      const newDates = this.state.dates;
      delete newDates[selectedDate]
      this.setState({dates: newDates})
    } else {
       const newDates = this.state.dates;
       newDates[selectedDate] = [
          {selected: true, startingDay: true, color: '#d6b161'},
          {selected: true, endingDay: true, color: '#d6b161'},
        ]
       this.setState({dates: newDates})
    }
  }
```

**Calendar component**

```
 <Calendar
         onDayPress={(day) => {this.props.selectDate(day)}}
         markedDates={this.props.state.dates}
         markingType={'interactive'}
   />
```

**Comment by andrewazevedo** [comment]
Did you solve it? I have the same problem. Thanks!

**Comment by ynsgnr** [comment]
Switching from markingType={'interactive'} to markingType={'period'} migth solve the issue. And i think 'interactive' marking type is no longer exists

**Comment by sandaruwan-eng** [comment]
try this one

import * as React from 'react';
import {View, StyleSheet} from 'react-native';
import {Calendar} from 'react-native-calendars';

export default class CustomeDateRangePicker extends React.Component {
  state = {
    markedDates: {},
    isStartDatePicked: false,
    isEndDatePicked: false,
    startDate: '',
  };

  onDayPress = day => {
    console.log('date list ', this.state.markedDates, '\n\n');
    let markedDates = this.state.markedDates;
    if (markedDates[day.dateString]) {
      const newDates = markedDates;
      delete newDates[day.dateString];
      this.setState({
        markedDates: markedDates,
        isStartDatePicked: false,
        isEndDatePicked: true,
        startDate: day.dateString,
      });
    } else {
      markedDates[day.dateString] = {
        startingDay: false,
        color: '#00B0BF',
        textColor: '#FFFFFF',
      };
      this.setState({
        markedDates: markedDates,
        isStartDatePicked: false,
        isEndDatePicked: true,
        startDate: day.dateString,
      });
    }
  };

  render() {
    return (
      <View style={styles.container}>
        <Calendar
          minDate={Date()}
          current={'2021-08-10'}
          monthFormat={'MMMM yyyy'}
          markedDates={this.state.markedDates}
          markingType="period"
          hideExtraDays={true}
          hideDayNames={false}
          enableSwipeMonths={true}
          onDayPress={this.onDayPress}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
});
