### ISSUE TITLE
event select day marked not working in Calendar

### ISSUE THREAD

**Issue by phamxuantu** [wix/react-native-calendars#247]
i set some days marked = true and Calendar displayed dot below day.
i touch in day then Calendar display blue circle around day.
but i touch in days marked Calendar not display  blue circle around day marked.
How to fix it?

**Comment by tautvilas** [comment]
hi, could you add a code snippet demonstrating the problem?

**Comment by phamxuantu** [comment]
this is my code: 
```
constructor(props) {
    super(props);
    this.state = {};
    this.onDayPress = this.onDayPress.bind(this);
  }

  render() {
    return (
      <Calendar
        onDayPress={this.onDayPress}
        style={styles.calendar}
        hideExtraDays
        markedDates={{ 
          [this.state.selected]: { selected: true },
          '2017-11-25' : {marked: true}
      }}
      />
    );
  }

  onDayPress(day) {
    this.setState({
      selected: day.dateString
    });
  }
```

**Comment by phamxuantu** [comment]
I touch the other day 25-11-2017 Calendar display normal blue circle, when i touch on 25-11-2017 no event occurred

**Comment by tautvilas** [comment]
That's because when you press on 25 your marking becomes:

```
markedDates={{ 
          '2017-11-25': { selected: true },
          '2017-11-25' : {marked: true}
      }}
```

The second key overrides first. You have to merge

**Comment by phamxuantu** [comment]
thanks very much!!!
