### ISSUE TITLE
Formating view with larger text

### ISSUE THREAD

**Issue by samin** [wix/react-native-calendars#249]
When iOS settings are changed for larger texts, it makes the calendar unreadable.

![image](https://user-images.githubusercontent.com/263049/33235929-ca4a8402-d22b-11e7-851f-a2897a3ca910.png)

![image](https://user-images.githubusercontent.com/263049/33235911-5c3c86ea-d22b-11e7-9bf7-41bf0bfdec22.png)

## Suggestion

Add `allowFontScaling={false}` prop to all `<Text />` components

## Environment

react-native-calendars@1.14.2
react-native@0.47

**Comment by tautvilas** [comment]
Hi, that’s a good suggestion. PRs are welcome :(
