### ISSUE TITLE
unable to resolve dependency tree when npm install

### ISSUE THREAD

**Issue by saaspeter** [wix/react-native-calendars#2495]
## Description

1-2 sentences describing the problem you're having or the feature you'd like to request.
       When I execute 'npm install', error like this: 

       npm ERR! While resolving: react-native-calendars@1.22.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16 || ^17" from @welldone-software/why-did-you-render@6.2.3
npm ERR! node_modules/@welldone-software/why-did-you-render
npm ERR!   dev @welldone-software/why-did-you-render@"^6.0.3" from the root project

## Expected Behavior
install no error

What action did you perform, and what did you expect to happen?

then I changed 'why-did-you-render' version to "^7.0.1", then this error disappear, but another similar error comes:
dev react@"18.2.0" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from react-recipes@1.5.0

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
npm ERR! peer react@"^16 || ^17" from @welldone-software/why-did-you-render@6.2.3
npm ERR!   peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from react-recipes@1.5.0
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Device/emulator/simulator & OS version:

## Reproducible Demo

just git clone the project and execute npm install

## Screenshots

Should I upgrade react-recipes version too? or use any other solution?
Thanks

**Comment by jacob30** [comment]
I think it fails due to the fact that react-native 0.74 does not support react 18.3.1 at the current moment.

https://github.com/facebook/react-native/pull/44325

**Comment by saaspeter** [comment]
@jacob30 , thank you helping,  I will wait for that ticket, then have a try again. So I close the issue for this moment.

**Comment by LeXuanKhanh** [comment]
> facebook/react-native#44325

try to run `npm install --force`
