### ISSUE TITLE
please tell me how to re-render data in Agenda when i update the data

### ISSUE THREAD

**Issue by hoangtubatu123** [wix/react-native-calendars#250]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by FabianEhringer** [comment]
+1 Same problem here
# Description
All my agenda items are stored in the current state of my component. When I update the state using
`this.setState({ items: newItems })` the agenda does not re-render.
# Expected Behavior
When the new state is set, the whole agenda component should re-render and display my new/changed items.
# Observed Behavior
Nothing happens. The agenda does not re-render. Even when I force it with `this.forceUpdate()`
# Environment
- react-native-calendars@1.14.2
- expo@22.0.4
- react-native@0.49.3
- iOS Simulator (iOS 11.1)

**Comment by MIt9** [comment]
Hi. You would to try update it like this
`
<Agenda
                    items={JSON.parse(JSON.stringify(this.state.items))}
                    loadItemsForMonth={this._loadItems}
                    renderItem={this._renderItem}
                    renderEmptyDate={this._renderEmptyDate}
                    rowHasChanged={this._rowHasChanged}
                />
`

**Comment by FabianEhringer** [comment]
I found my problem. The reason my agenda didn't update was the `_rowHasChanged` function.

`_rowHasChanged = (r1, r2) => r1.id !== r2.id;`
==> 
`_rowHasChanged = (r1, r2) => r1 !== r2;`

I didn't realise what the function was doing. I thought it would be necessary for the list view in my agenda to keep track when I'm scrolling. But it when I update my items, eg. change the title of an event, the IDs are still the same and the agenda thinks nothing has changed.

**Comment by arled** [comment]
Why was this closed? Did anyone figure out the issue?

**Comment by arled** [comment]
I got this working using redux. I have a Reset to initial state reducer:
```
    case RESET_AGENDA:
      return {
        ...initialState,
      };
```
