### ISSUE TITLE
Calendar does not re-render view when new marked dates are supplied

### ISSUE THREAD

**Issue by meurling** [wix/react-native-calendars#251]
## Description

Hello! when I press on a date the calendar does not re-render with my new marked date. I know that you must create a new object of the `markedDates` prop, but doesn't redux do that automatically? 
**CODE:**
```
<Calendar
                            current={calendarDate}
                            minDate={today}
                            maxDate={maxDate}
                            firstDay={1}
                            onDayPress={(day) => setCalendarDate(day.dateString)}
                            markedDates={{
                                calendarDate: {selected: true, marked: true}
                            }}
                        />
```
Where `calendarDate` is the date that gets updated through redux on `onDayPress`
How do I fix this? :)

**Comment by tautvilas** [comment]
Hi, you have to create new markedDates object with newly selected day. I don't see what setCalendarDate is doing so it's hard to tell what is missing.

**Comment by hosembafer** [comment]
Same issue... any updates here?

**Comment by noumantahir** [comment]
In calendar list, if I update marked dates for other months, the later months does not render at all....
