### ISSUE TITLE
Change the theme dynamically using state object

### ISSUE THREAD

**Issue by NelsonPetitos** [wix/react-native-calendars#252]
## Problem description

I want some properties of my calendar theme to change (specially the " selectedDayBackgroundColor") according to state object

## Expected Behavior

<Calendar
    theme={{
        ...
        monthTextColor: '#fff',
        selectedDayBackgroundColor:  this.state.selectedColor,
        ...
      }}
/>

##And further in a component function

onDayPress(day) {
    if(condition){
        this.setState({
            selectedColor: "blue",
        })
    }else{
        this.setState({
            selectedColor: "red",
        })
    }
}

**Comment by tautvilas** [comment]
Hi, currently there are no plans to have dynamic theme

**Comment by tautvilas** [comment]
you can use marking to have dynamic background colors of selected days.

**Comment by NelsonPetitos** [comment]
ok let me try it
