### ISSUE TITLE
The height does not auto wrap content in Android

### ISSUE THREAD

**Issue by nguyenhoanglam** [wix/react-native-calendars#254]
Calendar's height automatically fill all the container's height, not wrap its content height. Need a fix!

**Comment by angardi** [comment]
In my case Calendar height is not tall enough to display months with 6 weeks. Use December 2017 to replicate the issue. This is on Android, I have not tried on iOS

**Comment by tautvilas** [comment]
hey, you can customize calendar height via props. but currently it the height can be only fixed.
