### ISSUE TITLE
Remove month name and year from the top of calendar

### ISSUE THREAD

**Issue by pranay414** [wix/react-native-calendars#256]
Hi, 
Is there any way to remove month name and year from the top calendar.
<img width="358" alt="screen shot 2017-12-01 at 2 40 29 am" src="https://user-images.githubusercontent.com/16045021/33455149-2fa1b4c4-d641-11e7-8568-cd1bd2dd686a.png">
How to remove **December 2017** from calendar?

**Comment by tautvilas** [comment]
Hi, currently no.

**Comment by alvinmatias69** [comment]
Hi, I found a workaround on this. You can override style for mohtText according to the documentation. Just add this inside the `theme` props.
`'stylesheet.calendar.header': {
    monthText: {
        height: 0
     }
}`
