### ISSUE TITLE
Close agenda calendar list without relying on clicking the dates

### ISSUE THREAD

**Issue by gvimlan95** [wix/react-native-calendars#257]
Hey,

Is there a way to close the agenda calendar list without clicking the dates? Maybe could add a button at the bottom of the calendar to close it?

Thank you

**Comment by tautvilas** [comment]
at the moment you can try call agenda.chooseDay(selectedDay) to close the calendar.

**Comment by gugakatsi** [comment]
@tautvilas pops up 'undefined is not object (evaluating props.theme).
