### ISSUE TITLE
selectedDayBackgroundColor not work

### ISSUE THREAD

**Issue by herarya** [wix/react-native-calendars#26]
i install version v1.2.15 
selectedDayBackgroundColor not work
my current date ={'2017-05-24
<img width="369" alt="screen shot 2017-05-24 at 5 13 27 pm" src="https://cloud.githubusercontent.com/assets/5027291/26398650/5661dbe4-40a4-11e7-89ce-609a10137d53.png">
'}
<CalendarList 
        current={this.state.currentDate} 
        onDayPress={(day) => {console.log('selected day', day)}}
        onMonthChange={(month) => {console.log('month changed', month)}}
        pastScrollRange={24} 
        futureScrollRange={24} 
        theme={{
            calendarBackground: '#333248',
            textSectionTitleColor: 'white',
            dayTextColor: 'white',
            todayTextColor: 'white',
            selectedDayTextColor: 'green',
            monthTextColor: 'white',
            selectedDayBackgroundColor: 'green'
          }}
        />

**Comment by tautvilas** [comment]
Hi, you are using API wrong. `current` specifies initially visible month. If you want to display selected dates you have to specify `selected` property. Check out the examples here:

https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js

**Comment by herarya** [comment]
@tautvilas thanks bro
