### ISSUE TITLE
Can't set background colour of selected days

### ISSUE THREAD

**Issue by hannigand** [wix/react-native-calendars#264]
## Description

I am trying to apply background colors to a number of consecutive dates.

## Expected Behavior

I expect my dates to appear like this, with a block background color:

<img width="170" alt="screen shot 2017-12-07 at 16 27 04" src="https://user-images.githubusercontent.com/5614282/33725929-8a656d04-db6b-11e7-8f15-e0828101cc70.png">

## Observed Behavior

No background colour is being applied on any of the dates

![screen shot 2017-12-07 at 16 28 11](https://user-images.githubusercontent.com/5614282/33725971-a4308ae8-db6b-11e7-80ed-d1701d114845.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  1.11.0
* `npm ls react-native`: 0.45.1

Also specify:

Running on iOS Simulator and iPhone 6 - iOS 10

## Reproducible Demo

```
<Calendar
  style={{ paddingTop: 5, flex: 1 }}
  hideExtraDays
  current={'2017-12-07'}
  maxDate={'2017-12-07'}
  firstDay={1}
  hideArrows={false}
  theme={{
    arrowColor: '#33a8e2',
    todayTextColor: '#33a8e2',
  }}
  markedDates={{
    '2017-12-01': { startingDay: true, color: 'green' },
    '2017-12-02': {color: 'green' },
    '2017-12-03': { color: 'green', endingDay: true },
  }}
  markingType={'interactive'}
  onDayPress={day => {
    // omitted 
  }}
/>
```

I've also tried with:
```
markedDates={{
  '2017-12-01': { periods: [{ textColor: 'green' }] },
  '2017-12-02': { periods: [{ startingDay: true, color: 'green' }] },
  '2017-12-03': {
    periods: [{ endingDay: true, color: 'green', textColor: 'gray' }],
  },
  '2017-12-04': {
    disabled: true,
    periods: [
      { startingDay: true, color: 'green' },
      { endingDay: true, color: 'green' },
    ],
  },
}}
```

**Comment by tautvilas** [comment]
hey marking type name now is not 'interactive' but 'period'. changing markingType prop will fix your problem

**Comment by hannigand** [comment]
I apologise, it was listed in the README but I completely missed it. Thanks for your speedy response.
