### ISSUE TITLE
Trigger selected: true onPress

### ISSUE THREAD

**Issue by Cre3z** [wix/react-native-calendars#266]
Hi, 

I am relatively new to RN so I am trying out things as I go along. I enjoy using your extension, but I am struggling to find more information on how to implement certain things. 

1) In your demos you click on a day and the day's becomes selected (background color gets added), how do I do this?
2) Also how do I make current date (today) always selected? 

The outcome I would like to achieve is:
1) When an user lands on the screen today must always be selected in blue. 
2) When an user clicks on any other day that day must have a background color of red. 

Thank you in Advance!

I am running on Android 7.1 / Expo
"expo": "^22.0.2",
"react-native": "^0.49.5",
"react-native-calendars": "^1.14.2",

**Comment by tojinwandalaohu** [comment]
about Q1, you can find from react-native-calendars/example/src/screens/calendars.js.
`constructor(props) {
    super(props);
this.state = {};
    this.onDayPress = this.onDayPress.bind(this);
  }
<Calendar
          onDayPress={this.onDayPress}
          style={styles.calendar}
          hideExtraDays
          markedDates={{[this.state.selected]: {selected: true}}}
        />`

**Comment by Cre3z** [comment]
thanks @tojinwandalaohu for your response. I see the code you are referring to, but I currently have data that is place inside my markedDates prop. I am pulling json and marking in dates on the calendar. 

I am trying to figure out a way to still keep my data and have the effect of the example you gave.
