### ISSUE TITLE
How to handle months with 5/6 weeks?

### ISSUE THREAD

**Issue by sibelius** [wix/react-native-calendars#270]
![image](https://user-images.githubusercontent.com/2005841/33886012-424ad332-df2c-11e7-8fb0-caa3a9be471d.png)

**Comment by tautvilas** [comment]
The problem arises with custom bigger fonts. I suggest creating PR for calendar-list to allow customization calendar height. Currently it is a const:` calendarHeight = 360;`

**Comment by sibelius** [comment]
you can reproduce using this branch https://github.com/entria/react-native-calendars/tree/specific/gapp

**Comment by suomimar** [comment]
Master branch works great, but this other branch gives me the error. 
ENOENT: no such file or directory, uv_chdir

**Comment by tautvilas** [comment]
now it is possible to provide custom bigger calendar heights via calendarHeight prop to calendar list

**Comment by stereodenis** [comment]
Why it should be const and not dynamically calculated?

**Comment by ericlifs** [comment]
Why just don't put a `flex: 1` in there instead of hardcoding the month's height?

**Comment by sibelius** [comment]
you need to know the height of each month to scroll to a specific month

My solution is to getItemLayout, as I can calculate the number of weeks for each month, so it can be dynamic - https://facebook.github.io/react-native/docs/flatlist#getitemlayout

**Comment by ericlifs** [comment]
@sibelius do you have an example on how did you do it?

**Comment by ericlifs** [comment]
@sibelius Also the FlatList has a `initialScrollIndex` prop so you can set the initial month and a `scrollToIndex()` function if you want to go to a specific month. I do not know if that's the purpose of hardcoding the month height but it does not make much sense.

**Comment by amitbattan** [comment]
Can anyone let me know, what is the solution for this.
