### ISSUE TITLE
Is it possible to only show one day per day selected? (Agenda) 

### ISSUE THREAD

**Issue by runeogod** [wix/react-native-calendars#272]
Hi everyone, i couldnt find the answer, so  trying to find it here.

Is this possible to only render one day when selected in the agenda? instead of getting : 

13
14
15..

Also is there a way to add an extra feature that would calculate an amount per week? and so display it somewhere on top of the selected day (so between the displayed week on top and the selected day on bottom)

Any tips would be appreciated !

Thans !

**Comment by tautvilas** [comment]
Hi, currently showing only one ay is not supported in agenda. Please create separate ticket for feature request :)

**Comment by runeogod** [comment]
I actually managed doing it , sharing my code here, but its not the best solution : 
**item.fullinfo.start = date of my item.**


in renderItem :
` if (Moment(item.fullinfo.start).format('DD-MM-YYYY') == this.state.currentDay) {
        return (<View>..</View>)`

onDayPress : 

       let month = date.month;
        let day = date.day;

        if(date.month < 10) {
            month = '0'+date.month;
        }
        if(date.day < 10) {
            day = '0'+day.month;
        }
this.setState({
                currentDay: day + '-' + month + '-' + date.year,
            }
        );
