### ISSUE TITLE
Month doesn't change although hideExtraDays set

### ISSUE THREAD

**Issue by webwelten** [wix/react-native-calendars#273]
## Description

I set `hideExtraDays` on a CalendarList, so the days of the preceding and the following month aren't visible. When `current` date is set on today (14 Dec) and I change `current` prop to a date in the first week of the following month (this case: 03 Jan 2018) the calendar doesn't scroll to the new month.

## Expected Behavior

In case `hideExtraDays` is set, `scrollToMonth()` should additionally check if the dates are in different months.

## Observed Behavior

The diff calculation in `scrollToMonth()` is not precise enough.
`diffMonths = diffMonths < 0 ? Math.ceil(diffMonths) : Math.floor(diffMonths);`

For the given time (14 Dec till 03 Jan) it returns something like 0.6 which gets floored to 0.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.15.0 
* `npm ls react-native`: react-native@0.50.0 

1. Phone/emulator/simulator & version:
Simulator, iPad Air, iOS 10.2

**Comment by webwelten** [comment]
Same problem for 7 Jan 2018 and everything where the calculation results in something that can be floored to 0.

**Comment by tautvilas** [comment]
Hi, solved the problem this way:

https://github.com/wix/react-native-calendars/commit/81b0c876651898d96539679e0be07b02a6625ae2
