### ISSUE TITLE
Question theme / function

### ISSUE THREAD

**Issue by runeogod** [wix/react-native-calendars#275]
Hi everyone,

Since this calendar is the most advanced one for RN atm, i'd like to know if it is actually possible to do something like this 

https://cloud.githubusercontent.com/assets/5186464/20325758/ea125e1e-abc0-11e6-9e29-491acbcb0d07.gif

**Source** => https://github.com/WenchaoD/FSCalendar

The way it expand to the month only(when he click on ScopeMonth), and swipe to the left/right to switch month (with prev/next month written in above it)

I didnt find any props for it.

Thanks.

Regards.

**Comment by tautvilas** [comment]
Hi, swiping is not available, but you can dynamically control calendar container height.

**Comment by runeogod** [comment]
@tautvilas thanks for your reply, does the control you talk about is part of the prop available or should i use the style available in the agenda ?

**Comment by tautvilas** [comment]
I'm talking about adding `style={[styles.calendar, {height: 300}]}` to Calendar component. however this is not possible for Agenda or CalendarList yet
