### ISSUE TITLE
mark date

### ISSUE THREAD

**Issue by sangramsam** [wix/react-native-calendars#285]
## Have to put an image instead of a dot.

**Comment by eddiegroves** [comment]
Out of the box dots are just plain styled `<View />` with `backgroundColor` able to be changed.

You would have to implement [your own day component](https://github.com/wix/react-native-calendars/blob/c5a4331c1a5bd029b80a4dce23f012d9318fabd3/README.md#overriding-day-component) to do this, the [basic day component](https://github.com/wix/react-native-calendars/blob/c5a4331c1a5bd029b80a4dce23f012d9318fabd3/src/calendar/day/basic/index.js) would be a starting point.
