### ISSUE TITLE
Highly Expecting a Time based Agenda

### ISSUE THREAD

**Issue by Josh2941** [wix/react-native-calendars#286]
## Description

Expecting a Time based **Agenda** for a day, just like Google Calendar or Apple Calendar when we select a day, since it will be more user friendly and better user experience.

## Expected Behavior

![screenshot_1514526379](https://user-images.githubusercontent.com/34862136/34430321-c94826c2-ec89-11e7-8d68-d92b03304eec.png)

## Observed Behavior

![img_0018](https://user-images.githubusercontent.com/34862136/34430362-3160b92c-ec8a-11e7-852e-3af26ae0054f.jpg)

**Comment by uppercase-army** [comment]
+1

**Comment by tautvilas** [comment]
Hi, currently time based agenda is not in plans for this library.
