### ISSUE TITLE
[FEAUTURE] - Agenda time

### ISSUE THREAD

**Issue by franj0** [wix/react-native-calendars#287]
is there option for agenda to display items per hours in one day? tyvm

**Comment by runeogod** [comment]
Hi, seems not, i tried myself to limit the showing event to the current day only, but seems to have a bug when switch days, maybe have to optimize the 
rowHasChanged={(r1, r2) => {
                        return r2.idplg !== r1.idplg
                    }}

**Comment by tautvilas** [comment]
Hi, no there is no such feature
