### ISSUE TITLE
What version for react-native version 0.40.0?

### ISSUE THREAD

**Issue by xuho** [wix/react-native-calendars#288]

**Comment by eddiegroves** [comment]
The maintainers will know more details, but based on [the history](https://github.com/wix/react-native-calendars/commits/master/package.json) of `package.json`, `react-native` was only [added as a dependency](https://github.com/wix/react-native-calendars/commit/c431d1fee7b1eef530f997bfbc9b7647b098bb00#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R30) at version `0.44.0`, so any 'offical open source' version of the lib for 0.40.0 probably doesn't exist.

**Comment by xuho** [comment]
@eddiegroves: thank you.

**Comment by tautvilas** [comment]
Correct, no official version
