### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ercpereda** [wix/react-native-calendars#29]
There is some kind of documentation besides the README.md file?

**Comment by tautvilas** [comment]
Hello, currently no. What stuff are you missing in the README?

**Comment by ercpereda** [comment]
Hi @tautvilas the README only shows one example per component, that limits the amount of information about how to use the library. I think that a most proper explanation of each component, its props and the structure of the items, will be very helpful, also will avoid most of the questions issues.

**Comment by sibelius** [comment]
related to #39

**Comment by M4FFS** [comment]
(No close pls)
