### ISSUE TITLE
Agenda reservations can't scroll through months

### ISSUE THREAD

**Issue by abeltje1** [wix/react-native-calendars#296]
## Description
The problem I'm experiencing is that when using the Agenda component, one can only scroll through reservations inside a month. When the end/begin of a month is reached, one must use the calendarlist to select a date in the new month, and after that, it's possible to scroll through the month.

Is this intended behavior? It's kinda confusing for users that the scroll suddenly stops working and you need the calendarlist. 

The second problem which makes this even more confusing, is the fact that it's only possible to click on dates of other months through the full view of the calendarlist. In its minimized agenda-version it's impossible to click on a date in another month. This is because of line 147 in calendar.js, where you guys disable a date when it's not in the current month. What is the idea behind this line of code? shouldn't it just be possible to click on a date in another month? 

I can provide a demo, if needed, but it seemed to me that the problems I'm stating aren't actually bugs but choices made by you guys, which is why I assume a demo isn't necessary.

Thanks a lot in advance & keep up the good work

**Comment by tautvilas** [comment]
Hi, I will look into second problem because it might be a regression. Can you add gif/video of first problem?

**Comment by abeltje1** [comment]
Hi,

Thanks a lot! See here:

![react native calendar scroll up bug](https://user-images.githubusercontent.com/11901926/34725951-dccd27e8-f552-11e7-9d29-a6faeff92c8b.gif)

**Comment by tautvilas** [comment]
The first issue that you see at the beginning of the video can be solved by preloading data for more days in the future. If you did that you would be able to scroll down.

**Comment by abeltje1** [comment]
That's completely true. I thought that'd be managed by loadItemsForMonth, but I can implement it myself in onDayChange. Thanks!

**Comment by tautvilas** [comment]
The press on disabled days solved in v1.16.2

**Comment by Arslan106** [comment]
Still same issue unable to scroll up to the pervious month or pervious date or scroll down to the next month
