### ISSUE TITLE
Limit months to show.

### ISSUE THREAD

**Issue by pvsong** [wix/react-native-calendars#3]
Hi, 

How to limit months to show on CalendarList . Like this (5/2017 -> 5/2018)

Thanks.

**Comment by tautvilas** [comment]
Hi, according to your request in version 1.2.4 I added two new parameters to CalendarList:

`pastScrollRange` & `futureScrollRange`. In your specified example `pastScrollRange` would be 0 and `futureScrollRange` would be 12.
