### ISSUE TITLE
 How to block only one day

### ISSUE THREAD

**Issue by vagnerSl** [wix/react-native-calendars#30]
Need to block **only one** date or **multiple dates** !!!! ???

**Comment by tautvilas** [comment]
Hello, could you please be more specific about what you are trying to achieve? thx

**Comment by vagnerSl** [comment]
There is a  minDate and a maxDate limiting my calendar (<Calendar>), but, i need to block only one day between  a range of dates. How can i achieve that? thanks.

**Comment by tautvilas** [comment]
Hi, check #11 , there I propose a way how to do it. Currently there is no better way, but it is something we should definitely improve

**Comment by tautvilas** [comment]
Hey, now you can specify `disabled` prop for day in default marking style, please check the api:

https://github.com/wix/react-native-calendars/#date-marking
