### ISSUE TITLE
day dot styling problem

### ISSUE THREAD

**Issue by StTraft** [wix/react-native-calendars#301]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Only a half of the dot had been shown.

## Expected Behavior
![screen shot 2018-01-15 at 2 54 53 pm](https://user-images.githubusercontent.com/10973864/34930457-64ab2e7a-fa04-11e7-8eec-9c7862fceb86.png)

## Observed Behavior
![screen shot 2018-01-15 at 2 55 24 pm](https://user-images.githubusercontent.com/10973864/34930405-3ec8ca28-fa04-11e7-9e93-9a59c047d006.png)

## Solution
in `src/calendar/day/basic/style.js`, simply change:
```
    base: {
      width: 32,
      height: 32,
      alignItems: 'center'
    },
...
```
to 
```
    base: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 2
    },
...
```
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.14.2
* `npm ls react-native`: 0.45.1

**Comment by tautvilas** [comment]
Hi, i see multidot styling in your images but you describe changes to basic styling. How so?

**Comment by StTraft** [comment]
@tautvilas  My apologies for raising changes before tested. It should be on `day/multi-dot/style.js`. I solved the problem by adding a key `stylesheet.day.basic` containing those changes to my stylesheet. I just take a snap and faked by the word `STYLESHEET_ID`, which make me think that was the only one stylesheet I should get into (I know now that's only a trick for customizing).

**Comment by StTraft** [comment]
actually I am curious why keep the `basic` while the `multi-dot` should do the same thing?

**Comment by tautvilas** [comment]
Are you using custom font sizes or smth? I can not see this problem in example project
