### ISSUE TITLE
CalendarList is blank on initial load (Android, RN 0.52.0)

### ISSUE THREAD

**Issue by tautvilas** [wix/react-native-calendars#302]

**Comment by benevbright** [comment]
I recorded a video.
https://imgur.com/a/R9Zko

**Comment by tautvilas** [comment]
Is anyone else having problems with RN 0.52.0?

**Comment by nukes88** [comment]
is this fixed? sorry i dont know what that regression tag means

**Comment by benevbright** [comment]
Regression tag means that it had a bug and fixed. But some reason, it appears again on new update.

**Comment by nukes88** [comment]
ok thank you, i think i have to make my own flatlist of calendars for the time being?

**Comment by rjacobskind** [comment]
I've been seeing this issue on ios, RN 0.53.0

**Comment by jarheadstech** [comment]
I am also facing same issue, on first load Calendar does not show any dates, while on any swipe or other event it renders calendars dates.
It working fine in IOS

**Comment by shihao92** [comment]
Hey is there any solution to this issue already? Im facing the issue where by the calendar will not load on IOS and Android, but it loads and shows if there is any interaction like touch or press being applied onto it.

**Comment by tautvilas** [comment]
@shihao92 can you reproduce this problem with example project?

**Comment by shihao92** [comment]
@tautvilas hey i solved this problem with the onload kind of method, when the page loads, i called an action and modify the marked date attributes, and it works...
