### ISSUE TITLE
Selecting specific days in a "row" instead of a range (min/ max)?

### ISSUE THREAD

**Issue by BillyFigueroa** [wix/react-native-calendars#306]
Is there a way to select specific days instead of a range? For example, I am working on an appointment system where a provider may not work Monday and Wednesday. Your components require me to provide a start date and end date for dates I can "click" on or "select"

Is there a way to do this if not can a prop like selectDates=[] be implemented where I pass a list of days I want to be select-able?

Like if I pass an array of

```
[
    "2017-01-19",
    "2017-01-20",
    "2017-01-21",
    "2017-01-23",
]
```

It can work with those days to only allow those instead of it being based on a start and end date (min / max)

**Comment by BillyFigueroa** [comment]
I did notice that there is a way to mimic this behavior. At first I did some custom logic to basically create an array of dates from current day for the next 6 days and then using lodash I did an _.xor(array1, array2) with the actual dates I wanted to show, which would give me the days I wanted to allow to be clicked/ active ones (non disabled)

However I just found a different way to do it. It looks like you can use disableByDefault and instead build an array with your dates that is an object like...

```
   "2018-01-18": { disabled: false},
   "2018-01-19": { disabled: false},
   "2018-01-21": { disabled: false},
```

It would still be nice to have someone give the option to have something like
```
    clickableDates=[
        "2017-01-19",
        "2017-01-20",
        "2017-01-21",
        "2017-01-23",
    ]
```

**Comment by tautvilas** [comment]
At the moment the only way to solve this is how you did it :)

**Comment by BillyFigueroa** [comment]
Ok thanks, I ll stick with this approach but please consider in the future allowing an array of dates you want selected on top of the range you now allow
