### ISSUE TITLE
Question: How to make item span multiple days in Agenda View

### ISSUE THREAD

**Issue by IrfyNaz** [wix/react-native-calendars#311]
Hi, I'm trying to get an item to span across multiple days in the agenda view. Is this possible?

E.g. The item that is shown for just the first, should cover the proceeding dates up until the 6th.
![image](https://user-images.githubusercontent.com/1228983/35194419-30618514-feab-11e7-8207-3bfdc33a9776.png)

**Comment by tautvilas** [comment]
I think it could be technically possible with complicated renderItem implementation you could make some day items 'connect' without having a gap between them

**Comment by kalyanijamunkar10** [comment]
+1
