### ISSUE TITLE
How to initially render at a glance all events of the week with Agenda ? Or call renderItem on all Items of the week at a glance ?

### ISSUE THREAD

**Issue by moussasarr** [wix/react-native-calendars#312]
My agenda initially renders the current day event. I want the first render to show the current week at a glance. 
Initially the Agenda displays the entire week at a glance
My current agenda looks something like this: 

     <Agenda
        items={R.merge(props.emptyDates, props.items)}
        renderItem={renderItem}
        renderEmptyDate={renderEmptyDate}
        rowHasChanged={rowHasChanged}
        theme={theme}
        onDayPress={props.setEmptyDate}
      />

**Comment by tautvilas** [comment]
Hi, I'm not sure I understand your problem. Maybe you could be more specific? Try following the issue template and provide all necessary info
