### ISSUE TITLE
can not switch month when tapping on greyed out  day from another month that is visible in calendar page

### ISSUE THREAD

**Issue by vanhungoz** [wix/react-native-calendars#317]
## Description

i am using Calendar Component with some basic props. but i can't change month when tapping on greyed out day.
i have checked example project but i can't fix my problem.
i'm using  "react-native": "0.52.0",and  "react-native-calendars": "^1.16.1".

**Comment by tautvilas** [comment]
Hi, thanks for report I will try to fix this issue soon

**Comment by vanhungoz** [comment]
thanks for your reply 👍

**Comment by AbdallaMohamed** [comment]
Was trying to implement a week strip and faced the same issue. I could try to work on a PR if you don't mind, @tautvilas ?

![image](https://user-images.githubusercontent.com/10912145/35510015-a333ec66-04f6-11e8-8048-75a6941733c8.png)

**Comment by tautvilas** [comment]
I this I will fix it this week, so no PR needed :)

**Comment by tautvilas** [comment]
This should be resolved in v1.16.2
