### ISSUE TITLE
scrollToMonth not excute, i met this issue, maybe i did wrongly.

### ISSUE THREAD

**Issue by hanweixing** [wix/react-native-calendars#318]
I use this library in one of my components, and when i show this calendar, i find that **the calendar does not scroll to the current date**. I try many times, not work. 
My codes like this below:
`<CalendarList
                        current={this.state.calendarListCurrent}
                        markedDates={{[this.state.calendarListMarkedDates]: {selected: true}}}
                        onDayPress={(day) => this._onSelectedCalendarList(day)}
                    />`
Then i review the source code in _react-native-calendars/src/calendar-list/index.js_.
I find the method named _scrollToMonth_ , and it would be invoked when the method named _componentWillReceiveProps_. But _componentWillReceiveProps_ not work in the begin. 
So, i go to old version in [https://github.com/christopherdro/react-native-calendar](url), and i find that the old version will invoke _scrollToMonth_ in _componentDidMount_  and another layout method anyway.
I wonder, is this difference causing my wrong appearance?
Am i the only one to meet this issue? I don't know. But I have fixed my problem by adding the method _componentDidMount_ .
Maybe this is a Oolong.

**Comment by morfsys** [comment]
Can you share your code how you are scrolling to current month? I am facing the same issue. I tried doing
`componendDidMount(){
           CalendarList.scrollToMonth('April');
}`

I expect it to scroll to April but it doesn't.

**Comment by tautvilas** [comment]
Hi, please be more specific and create an issue according to issue template. Thanks :)
