### ISSUE TITLE
Agenda knob styling

### ISSUE THREAD

**Issue by suyogkc** [wix/react-native-calendars#32]
Is there anyway to override styles of knob of agenda ?

**Comment by tautvilas** [comment]
Currently there is no way, but I propose that `renderKnob` optional property could be added to Agenda. You could do a PR for that

**Comment by kkemple** [comment]
would it also be possible to add `knobTintColor` or some property to alter the color within agenda theme? I would prefer to not have to render the custom component if avoidable (will add support for both in PR though)

**Comment by tautvilas** [comment]
yeah we can have `knobColor` option which would be implemented with tint

**Comment by tautvilas** [comment]
fixed in 1.5.8

**Comment by kkemple** [comment]
oh wow, was just about to get to this! thanks!

**Comment by asmith13194** [comment]
Working on implementing the color change, not exactly sure on what the agreed syntax was.

**Comment by kkemple** [comment]
the theme prop name is `agendaKnobColor` you can find an example here:
https://github.com/wix/react-native-calendars#agenda
