### ISSUE TITLE
How to scroll to a given month in CalendarList?

### ISSUE THREAD

**Issue by morfsys** [wix/react-native-calendars#320]
I am trying to scroll to say April inside a CalendarList. My code looks like this:

`<CalendarList
      ref={(c) => this.calendar = c}
     ... />`

And then I do this inside:
`componentDidMount(){ this.calendar.scrollToMonth('April') }`
 
But it doesn't work and I get the following error:

Cannot read property 'scrollToMonth' of undefined  

Any suggestions as to what am I doing wrong?

**Comment by AbdallaMohamed** [comment]
If you need to call that in `componentDidMount`, you'll need to wrap the call in a `setTimeout`

Check out this snack.
https://snack.expo.io/@abdallamohamed/scrolling-to-a-month-in-react-native-calendars

**Comment by AbdallaMohamed** [comment]
And of course you need to call `scrollToMonth()` with the proper xdate format http://arshaw.com/xdate/

**Comment by morfsys** [comment]
Actually I am calling it in a separate method. I used componentDidMount here for the sake of simplicity.

**Comment by tautvilas** [comment]
can this be closed?
