### ISSUE TITLE
Performance issue with many marked dates

### ISSUE THREAD

**Issue by jarrx** [wix/react-native-calendars#323]
I've noticed that when you have many marked dates (maybe 5 dots per week for a year or two) the calendar becomes quite slow when updating the markedDates with selected: true (when the user selects a date in the calendar).
I'm using object spread when updating markedDates to create a new object every time a new date is selected (since markedDate is supposed to be treated as immutable). Is there any more performant way to solve this?
I've tested this on an iPhone 7 in release mode.

**Comment by tautvilas** [comment]
Are you talking about <Calendar /> component? What marking type do you use?

**Comment by jarrx** [comment]
I'm talking about the Calendar component and using marking type 'multi-dot'.
```
<Calendar
  current={this.props.selectedDate}
  onDayPress={day => this.props.changeSelectedDate(day.dateString)}
  firstDay={1}
  style={calendarStyle}
  markedDates={this.markedDates()}
  markingType='multi-dot'
  showWeekNumbers={this.props.showWeekNumber}
/>
```
Where markedDates() is a function that returns a updated marked dates object. I'm using a function instead of a state since I'm using the same marked dates on more than one calendar in the app, but with different selected dates.
The selectedDate below will update whenever an onDayPress event is triggered in the calendar.
```
const { selectedDate } = this.props;
const markedDates = { ...this.props.markedDates };
if (markedDates.hasOwnProperty(selectedDate)) {
  const prevDots = markedDates[selectedDate].dots;
  const newMarkedDots = { dots: prevDots, selected: true };
  markedDates[selectedDate] = newMarkedDots;
  } else {
    markedDates[selectedDate] = { selected: true };
  }
return markedDates;
```

**Comment by tautvilas** [comment]
Multi-dot marking was implemented by @jaruyot . Need to check if shouldComponentUpdate is implemented properly there. Does it work faster with basic marking? Not sure about your implementation but this.markedDates() should only return dates for selected month and not whole year

**Comment by jarrx** [comment]
My mistake. It returns all marked dates and not just for the selected month. I'm sure thats the problem. Thank you very much for the help!

**Comment by jarrx** [comment]
I've updated the structure so that markedDates contains an object for every month with all dates for that particular month so that the whole year is not being returned from the markedDates() function. However this seems not to solve the performance issue.
When I measure the execution time of the markedDates() function that returns every marked date for the current month, it is around 1.5 ms so that should not be the problem.
@jaruyot maybe you know why it is so slow updating selected date when using multi-dot?

@tautvilas you say that it should only return dates for the selected month, but then the dates that is visible for the next month won't be marked right? Like in the picture. The dates 1, 2, 3 and 4 should be marked in February.
![skarmavbild 2018-01-30 kl 16 54 34](https://user-images.githubusercontent.com/31743687/35576693-ecd26426-05df-11e8-8a56-22a0815e32df.png)

**Comment by tautvilas** [comment]
yes, well your function could return current month +- 10 days from other months. Can you check if performance with basic marking is ok  and this is related to this specific marking type?

**Comment by jarrx** [comment]
I've now tested (release mode on iPhone 7) with the default marking type and as I'm experiencing it, I think it is the same issue as with 'multi-dot'.
When there are no marked dates in the markedDates object, there's no delay in the response when selecting a date. But if I let markedDates contain every day in January, except from weekends, so 23 days, the response when selecting a day is quite delayed and you really get the feeling that the performance is slow.

I did even simplify my previous method this.markedDates() as mush as I could:
```
markedDates() {
    const { selectedDate } = this.props;
    const markedDates = { ...this.props.markedDates };
    markedDates[selectedDate] = { selected: true };
    return markedDates;
  }
```

Well, I tried the same thing but this time only using component level state instead of redux to store markedDates and let the onDayPress modify the state and now it works perfectly smooth.
So for some reason it gets slow when using redux. The only thing that happened in redux before was that the redux state 'selectedDate' got updated when onDayPress was triggered.

**Comment by tautvilas** [comment]
Weird, so probably there is some problem the way you use redux. I use redux with calendars myself and did not notice perf issues with this component.

**Comment by jaruyot** [comment]
@jarrx that's weird, I'm using Redux for selected date as well and have not encountered any performance issue. Is markedDates() called every time componentWillReceiveProps() is called? Have you checked how many times markedDates() is called when selected date changes?

**Comment by jarrx** [comment]
@jaruyot markedDates is only called once when the selected date changes.
The problem seems to be that when selectedDate changes, a modal screen that is not visible and that also use selectedDate, for some reason also gets updated. So this has nothing to do with the calendar component. I'm using React Native Navigation from Wix, but I will try to find an solution there instead. Thank you for the help anyway.
