### ISSUE TITLE
CalendarList - blank space instead of month when scrolling fast

### ISSUE THREAD

**Issue by mharrisweb** [wix/react-native-calendars#325]
## Description

When scrolling from month to month, using the CalendarList, If you scroll quickly the month is displayed in large bold text, with an empty calendar. 

## Expected Behavior

If scrolling quickly through CalendarList. Month appears as blank space.

## Observed Behavior

No error, just blank space instead of month,.

## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.16.1
* `npm ls react-native`: react-native@0.50.3

 Samsung s8 Android V7

## Reproducible Demo

![videotogif_2018 01 31_15 52 55](https://user-images.githubusercontent.com/8245572/35632881-cc336326-069f-11e8-89b3-d570f826e0e5.gif)

**Comment by tautvilas** [comment]
Hi, this is the result of calendars optimization. Calendar days are not rendered until calendar scrolls into view. If you scroll really fast, rendering lags and for a short time you see placeholder that is visible until calendars are loaded (the other alternative would be to have blank calendars until they are rendered)

**Comment by mharrisweb** [comment]
Hi @tautvilas 

So it cant be prevented? Could I use 'onVisibleMonthsChange' to just render the current/ next and previous months?

Also, would I be able to put a loading spinner in instead of the placeholder?

**Comment by tautvilas** [comment]
Currently you can not customize placeholder. This is the place in code that you can change in your fork to display something else:

https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/item.js#L45

**Comment by mharrisweb** [comment]
Can I setup a pull request to add that functionaility?

**Comment by tautvilas** [comment]
Yes

**Comment by Mahdi-Farahani** [comment]
i have this issue how can i fix it? @tautvilas

**Comment by leonardorib** [comment]
I would also like to be able to customize this placeholder.

I'm going to submit a pull request.

**Comment by pfcodes** [comment]
Placeholder much needed

**Comment by MursiDirect** [comment]
Any Solution yet?

**Comment by PauloBarroso85** [comment]
Are you planning to merge the PR soon? 🤔
