### ISSUE TITLE
Clean Object

### ISSUE THREAD

**Issue by mfrknv** [wix/react-native-calendars#328]
When I click on the any day, it putting(loadItems(day)) item object, so there are many value in object, i want when i click onDayPress clean old objects. is that possible?

**Comment by mfrknv** [comment]
I wrote something like this in loadItems(day) function

```
loadItems(day) {
  if (Object.keys(this.state.items).length != 0) {
      Object.keys(this.state.items).forEach(key => delete this.state.items[key]
      );
   }
.
.
.
.
.
}

```

**Comment by tautvilas** [comment]
please open issues according to issue template
