### ISSUE TITLE
How to modify the first Item in a Day using firstItemInDay boolean?

### ISSUE THREAD

**Issue by BillyFigueroa** [wix/react-native-calendars#332]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I would like to know if the first item in a day can be modified in terms of its container height etc. When using renderItem function there is a boolean called firstItemInDay that can check if the item is the first in the day but how do I use this to potentially change the styling on that item?

## Environment

+ iMac with latest iOS
+ "react-native-calendars": "^1.17.0",
+ Expo
+ Simulator (iPhone X) Version 10.0 (SimulatorApp-835.5)

**Comment by tautvilas** [comment]
Hi, so you can use this prop and render a custom component according to it. I don't see there should be a problem?

**Comment by BillyFigueroa** [comment]
So check if the value is true and then return a different component? Any examples on how to modify the "day" component?

**Comment by sumanth234** [comment]
Even i need to return diiferent component to dirrerent dates.Any examples on how to modify the "day" component?
