### ISSUE TITLE
Calendar style issue (not loading properly)

### ISSUE THREAD

**Issue by jciccio** [wix/react-native-calendars#338]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

Default styling doesn't seem to work if I use <Calendar /> but it works if I use <CalendarList />

I added a Calendar as the Readme states but the calendar seems to be half off the screen. When added the Calendar along with CalendarList both have styling. Idem adding just the CalendarList

Adding just the Calendar:
https://ibb.co/h83qRS

Adding both have this result:
https://ibb.co/iqeiD7

* `npm ls react-native-calendars`: react-native-calendars@1.17.0 
* `npm ls react-native`: react-native@0.51.0 

Using Iphone 6s with iOS 11.2.1
And iPhone 7 Simulator with iOS 10.3
Also specify:

**Comment by vincentvella** [comment]
I also seem to be having this issue

**Comment by Atala** [comment]
Encountered the same issue, workaround with the same fix. The calendar component was working fine surrounded by `ScrollView`.
