### ISSUE TITLE
Migrate from XDate to moment.js

### ISSUE THREAD

**Issue by tautvilas** [wix/react-native-calendars#343]
Change underlying date implementation

**Comment by pinguinjkeke** [comment]
Will be PR accepted if I implement this? It 10 PRs almost there, idk how fast they are accepted

**Comment by pinguinjkeke** [comment]
Ok, it makes sense.
What about to use some linting tools? Do you like eslint airbnb preset?

**Comment by tautvilas** [comment]
The lint is configured use npm run lint command

**Comment by davidgoli** [comment]
I would strongly discourage this switchover. Moment.js, while popular, is infamously bloated (particularly due to its locales) and would be forcing adoption of an enormous dependency on end users. XDate is 3k gzipped, moment is 16.4k gzipped, and moment-with-locales is a whopping 66.3k gzipped!

**Comment by davidgoli** [comment]
Alternatives I would propose instead:

https://date-fns.org/
https://github.com/moment/luxon

Even better, providing props to consumers so we can provide our own date library or implementation without taking on another dependency!

**Comment by tautvilas** [comment]
@davidgoli thanks for update. I am also not sure if moment.js will bring more benefits so I am not sure about this refactor. I want to use date library that has immutable date objects, AFAIK neither XDate or Moment.js support this. This leads to various weird bugs.

Either way react-native-calendars exposes date objects that are time-library agnostic, so we can refactor anytime when good alternative lib appears.

**Comment by davidgoli** [comment]
@tautvilas both date-fns and luxon use immutable objects, for what it's worth.

**Comment by julioxavierr** [comment]
@tautvilas I like the idea of using `date-fns` and would love to contribute. Can I?

**Comment by maxaggedon** [comment]
@julioxavierr did you start working on something ?

XDate is licensed under both GPL-2.0 and MIT, there is no clear indication that the user can choose between those two. Therefore one could argue that GPL restrictions apply regarding distribution. Which would mean that any app using react-native-calendars should be distributed under GPL license as well.

**Comment by julioxavierr** [comment]
> @julioxavierr did you start working on something ?
> 
> XDate is licensed under both GPL-2.0 and MIT, there is no clear indication that the user can choose between those two. Therefore one could argue that GPL restrictions apply regarding distribution. Which would mean that any app using `react-native-calendars` should be distributed under GPL license as well.

@maxaggedon I did not. Back then I meant to contribute with a PR but didn't move forward since it didn't seem to be a priority for the project.

**Comment by maxaggedon** [comment]
Thanks for the quick reply @julioxavierr! I have made the switch from xdate to luxon on a fork. It is a quick and dirty switch as we needed to work around the licensing issue swiftly. Also it is partial as we only use `CalendarList` and did not have the time to cover all components.

If anyone is interested in continuing this, the branch is here : https://github.com/maxaggedon/react-native-calendars/tree/replace-xdate-with-luxon

Quick note though : luxon does not work well with Hermes for now as it relies on Intl api...

**Comment by Thodor12** [comment]
Even though this has become slightly stale, I would recommend another alternative: [date-io](https://github.com/dmtrKovalenko/date-io)

date-io is a plain wrapper over other date management libraries, it only requires you to import the [generic logic](https://www.npmjs.com/package/@date-io/core), and the user is responsible for providing an implementation (like date-fns, moment, luxon, etc).
This means you don't have to worry about licensing since date-io itself is licensed as MIT, specific licensing restrictions fall under the end user depending on their specific library.

date-io it's documentation also states it's helpful that library authors re-export the specific library bindings themselves (to require specific versioning), this way you can also choose to exclude specific libraries that do not work on react-native (like @maxaggedon mentioned, luxon)

**Comment by angelo-hub** [comment]
guess for the calendar this will have to be done on a fork for hermes support, shame since hermes has been default now for 2 years on android
