### ISSUE TITLE
trying to style day element

### ISSUE THREAD

**Issue by dhcmega** [wix/react-native-calendars#345]
Hi
Can any one please tell me how to style the day element, it has a marginTop: 32 that creates space between my 2 first events in Agenda.

I have this code:
```
const calendarStyles = StyleSheet.create({
  day: {
    width: 63,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 5,
  },
});
```

And I have this, but it's not working, it's being ignored:
```
        <Agenda
          items={this.state.items}
          style={calendarStyles} // HERE
          selected={new Date()}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
        />
```

Thanks!

**Comment by Raesta** [comment]
HI @dhcmega,

here is how I proceeded to put my custom style:
![image](https://user-images.githubusercontent.com/4834347/38298830-c9546490-37f8-11e8-8f4b-666b81d8bee0.png)

hoping it would help you !

Best regards,
Rémy 'Raesta' Mulet.
