### ISSUE TITLE
Agenda not scrolling through all dates

### ISSUE THREAD

**Issue by gogoku** [wix/react-native-calendars#347]
## Description

Not Scrolling all dates in the calendar in agenda view

## Expected Behavior

Scroll through all the dates

## Observed Behavior

Skips dates which donot have entries in item , when scrolling future, Does not scroll backwards if no entries are made for previous day

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.17.0
* `npm ls react-native`: react-native@0.51.0

**Comment by tautvilas** [comment]
The empty dates should have an empty array as value in order not to be skipped

**Comment by gogoku** [comment]
I had implemented the same loadItems function in the example,
 I have also noticed the behavior where it does not scroll backwards, is this a behavior intended to do and can i avoid it ?
