### ISSUE TITLE
Dates not showing in header on Agenda on initial load

### ISSUE THREAD

**Issue by edeere** [wix/react-native-calendars#350]
## Description
I am able to drag down the header and once I select a date, the header shows up. 

![screen recording 2018-02-18 at 08 29 pm](https://user-images.githubusercontent.com/16907570/36360532-877c8600-14ea-11e8-9a18-11d7d55b411b.gif)

## Environment
react-native-calendars@1.17.0 
react-native@0.53.0 
iPhone 6 - iOS 11.0

**Comment by lucasrlt** [comment]
Hi, I had the exact same problem ! Do you use react-navigation in your app ?

**Comment by dlucidone** [comment]
I'm not using react native i'm using react-native-router-flux and in 7/10 times the dates doesn't show up and after scrolling they do?Is there any solution to this?
