### ISSUE TITLE
Dates incorrect in Agenda header when setting pastScrollRange={0}

### ISSUE THREAD

**Issue by Bosseskompis** [wix/react-native-calendars#352]
## Description

If pastScrollRange is set to zero, the header will default to displaying the last date of the month instead of the actual selected date. Example:

![tvblwcq](https://user-images.githubusercontent.com/15824123/36406219-8c986706-15f5-11e8-8e5a-ef733471125b.png)

## Environment
react-native-calendars@1.17.1
react-native@0.52.2
Pixel - Android 6.0

**Comment by tautvilas** [comment]
Unfortunately currently I can only recommend not using pastScrollRange=0 in Agenda. I checked out this problem but can not think about an easy fix at the moment.

**Comment by tautvilas** [comment]
This should be solved in 1.19.2
