### ISSUE TITLE
LocaleConfig SyntaxError.

### ISSUE THREAD

**Issue by velho-oscar** [wix/react-native-calendars#353]
## Description

I've been trying to translate my month names, days, etc in Polish. I've followed instructions in this repo.

## Expected Behavior

I wanted to have polish strings in Calendar in my application.

## Observed Behavior

What actually happened when you performed the above actions?
The application won't run now. If I comment translate section and use default locales (english) then I can see the Calendar.  To check if I haven't made any typo - I've copied and paste french translations (from the tutorial here) but it gives me the same error as well. I haven't forgot about importing dependencies. 
The problem is within this lane: 
```
error: bundling failed: SyntaxError in (...) : Unexpected token (14:14)

LocaleConfig.locales['pl'] = { (...)
```
And it points on the dot between LocaleConfig and locales.

Here's screenshot from the phone (somehow I wasn't able to copy error message): [picture](https://imgur.com/a/xTh9j).
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:
[These commands results](https://imgur.com/c1dQ6Qi)

Also specify:

I'm using my own phone - Lenovo K6 Note with 7.0 Android. (Computer is too weak to run emulator freely)

## Reproducible Demo

There's my code: [click](https://codeshare.io/2KwRJN)

**Comment by EyMaddis** [comment]
This is a bug in your code, not this project.

You need to place the code *outside* of the `class .... { }`-Block.
