### ISSUE TITLE
How to use Custom Buttons to Change Months ?

### ISSUE THREAD

**Issue by kckunal2612** [wix/react-native-calendars#354]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I would like to use a custom view to create the PREVIOUS and NEXT Buttons to change month. However, I do not see any info. in the docs which can guide me on how to change month from custom button.

I am creating a layout somewhat like the one shown below - 

![calendar_poc](https://user-images.githubusercontent.com/4411464/36422199-183c7bd8-1661-11e8-9efd-f0d579c78987.png)

**Comment by tautvilas** [comment]
The only way to customize arrows at the moment is via renderArrow prop
