### ISSUE TITLE
CalendarList shows only 3 months if first days of months are marked selected

### ISSUE THREAD

**Issue by ashumilov** [wix/react-native-calendars#357]
## Description

In CalendarList I use `onVisibleMonthsChange` in order to dynamically mark the first days of visible months as `selected`. When I scroll CalendarList forward/backward I see that only 3 months (actual one and two surrounding, at the moment: January, February, and March) are shown, for others there is only short heading (like 'Dec 2017') and empty space instead of days. 

## Expected Behavior

I expect all days are shown with first days of visible months marked as `selected` while scrolling.

## Observed Behavior

Only 3 months are fully shown while scrolling.

## Environment

* `npm ls react-native-calendars`:
MyDays@0.1.0 /Users/sunnytigra/work/MyDays
└── react-native-calendars@1.17.2

* `npm ls react-native`:
MyDays@0.1.0 /Users/sunnytigra/work/MyDays
└── react-native@0.52.0

* iPhone SE, IOS 11.2.5
* iPhone Simulator SDK 11.2

## Reproducible Demo
```javascript
import React from 'react';
import _ from 'lodash'
import moment from 'moment'
import {CalendarList} from 'react-native-calendars';

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    onVisibleMonthsChange = (dates) => {
        const days = _.map(dates, d => moment(d.dateString).startOf('month').format("YYYY-MM-DD"))
        const markedDates = _.reduce(days, (ds, d) => {
            return {...ds, ...{[d]: {selected: true}}}
        }, {})
        this.setState({markedDates})
    }

    render () {
        return (
            <CalendarList
                onVisibleMonthsChange={this.onVisibleMonthsChange}
                markedDates={this.state.markedDates}
            />
        )
    }
}
```
## Screenshot
![simulator screen shot - iphone se - 2018-02-21 at 18 21 18](https://user-images.githubusercontent.com/7141722/36492441-d3c61b46-1735-11e8-8ea4-6337af4832c6.png)

**Comment by ashumilov** [comment]
Solved by myself. It seems all about immutable.  The merge of `markedDates` should be changed (also put `markedDates: {}` into `this.state` in `constructor`:
```javascript
        const newDates = _.reduce(days, (ds, d) => {
            if (this.state.markedDates[d])
                return {...ds}
            else
                return {...ds, ...{[d]: {selected: true}}}
        }, {})
        if (!_.size(newDates))
            return
        const markedDates = {...this.state.markedDates, ...newDates}
```
If `newDates` is empty do nothing. Without this check won't work. Not sure I understand why merging `markedDates` with `{}` spoil it.

**Comment by mharrisweb** [comment]
Hi @ashumilov, 

I can only get 3 months to display also, here is my code below - I use moment to select the dates between a range. Any ideas how I can get more than 3 months to show?

```
loadItems(dates) {
        const { events } = this.props;

        const dateIndex = dates.length;

        const startDate = moment([
            dates[0].year,
            dates[0].month,
            dates[0].day
        ]).startOf("month"),
        endDate = moment([
            dates[dateIndex - 1].year,
            dates[dateIndex - 1].month,
            dates[dateIndex - 1].day
        ]).endOf("month");

        const dateRange = moment().range(startDate, endDate),
            newEvents = Object.keys(events).reduce((output, dateString) => {
                dateRange.contains(moment(dateString).toDate()) &&
                    (output[dateString] = events[dateString]);
                return output;
            }, {});

        console.log();

        this.setState({
            markedDates: { ...newEvents, ...events }
        });
    }
        <CalendarList
                style={styles.calendar}
                markingType={"multi-dot"}
                onVisibleMonthsChange={this.loadItems}
                onDayPress={this.onDayPress}
                markedDates={events}
                pastScrollRange={0}
                futureScrollRange={6}
                scrollEnabled={true}
                showScrollIndicator={true}
            />
 
```
