### ISSUE TITLE
[Android]The calendar alway return to selected Date when i slide calendar

### ISSUE THREAD

**Issue by zerotalk** [wix/react-native-calendars#36]
I try use react-native-calendars in my android-device, but the component occured a PR in my android-device.

1.I selected 2017-5-24 in the calendar
2.I try slide up or slide down and want to select other Date
3.but the calendar alway return to 2017-5-24

![untitled](https://cloud.githubusercontent.com/assets/11973919/26517248/640395ec-42c7-11e7-9602-cddcd23da1f2.gif)

Devices Version: Android4.3/Android 5.1.1
"react": "15.4.2",
"react-native": "^0.41.2",
"react-native-calendars": "^1.2.17",

**Comment by tautvilas** [comment]
Thx for bug report. Can you show a snippet of code how `<CalendarList />` looks in your code?

**Comment by HouseShine** [comment]
Sorry for my statements, it mean react-native-calendars have a problem in my android app.

CODE:

![pic1](https://cloud.githubusercontent.com/assets/11973919/26611642/1169f0e2-45e2-11e7-9d04-47bb3afcb597.png)

AgendaView = react-native-calendars/example/src/screens/agenda.js
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js

**Comment by leerman** [comment]
@HouseShine, I had same problem, but it disappeared when I upgraded to react-native 0.44

**Comment by HouseShine** [comment]
Thanks for @leerman @tautvilas . It fine when I upgraded to react-native 0.43.2
