### ISSUE TITLE
Cannot find how to style the currently selected day background in the Agenda

### ISSUE THREAD

**Issue by chapeljuice** [wix/react-native-calendars#360]
Where does it explain how to change the color of this bright blue circle around the "22" on the `<Agenda />` component?

<img width="357" alt="screen shot 2018-02-22 at 3 04 09 pm" src="https://user-images.githubusercontent.com/862642/36569224-c02cd758-17e1-11e8-8f73-b717533b1d3f.png">

**Comment by tautvilas** [comment]
I think you can change it by setting selectedDayBackgroundColor in the theme.

**Comment by chapeljuice** [comment]
That worked, thank you!
