### ISSUE TITLE
Week view for Calendar component?

### ISSUE THREAD

**Issue by ZeerakHameem** [wix/react-native-calendars#361]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Is there a way to use the Calendar component to show only weekview? Like in the Agenda component?

**Comment by tautvilas** [comment]
not at the moment

**Comment by trancanh2202** [comment]
"not at the moment" => and it is done ??
Irresponsible answer

**Comment by ihsanktmr** [comment]
You may try my temporary solution https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538
