### ISSUE TITLE
Months are Not Rendering at CalendarList

### ISSUE THREAD

**Issue by rjacobskind** [wix/react-native-calendars#362]
I have a CalendarList, for which I have set the `futureScrollRange={0}`, and `pastScrollRange` set to the default of 50. However, the past months never render past April 2017.

## Expected Behavior
When I scroll to past months, I expect to see 50 past months render.

## Observed Behavior
When I scroll to past months, I am only able to see past months up to April 2017.

## Environment
react-native-calendars@1.17.2 
react-native@0.53.3
react-navigation@1.0.0-beta.15
iPhone 6 Simulator

**Comment by chiformihai** [comment]
same problem:
react-native-calendars@1.17.2
react-native@0.51.0
react-navigation@1.0.0-beta.27

**Comment by tautvilas** [comment]
@rjacobskind could you check if you can reproduce same problem in example project? If not maybe you can find what is different in your project and post your code snippet here?

**Comment by RuairiOliver** [comment]
Yeah same happens for me. If you remove initialScrollIndex from calendar-list/index.js and set initialNumToRender to a high number you'll see all of your dates then. 

I've seen this with lists before, usually I scroll to the index I need after the component mounts

**Comment by anoopmm** [comment]
@rjacobskind could you able to solve this? same issue here

**Comment by rjacobskind** [comment]
@anoopmm Unfortunately I wasn't able to solve this, so I opted for the `Calendar` component instead.

**Comment by anoopmm** [comment]
@rjacobskind in my case problem is with tab navigator. inside tab navigator it doesn't works but out side it works well.

**Comment by nathsimpson** [comment]
Sorry, but that solution is not helpful at all. Has anyone done research into why the bug is appearing when the component is being created inside a tab navigator?

**Comment by nathsimpson** [comment]
I had a similar issue happen to me recently in an expo project. I solved it by updating the Expo SDK to the latest versions :)
