### ISSUE TITLE
Agenda's Selected Day hidden [pastScrollRange=0]

### ISSUE THREAD

**Issue by jovanxua** [wix/react-native-calendars#363]
## Description
Using Agenda, when below props are set, the selected day is hidden on press

minDate={'2018-02-11'}
maxDate={'2018-02-25'}
pastScrollRange={0}
futureScrollRange={0}

## Expected Behavior

When a day is pressed, the selected day should be scrolledToIndex(shown) while displaying the agenda items.

## Observed Behavior

The selected day or sometimes all of the ranged dates is hidden.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.17.2
* `npm ls react-native`: react-native@0.53.3

Also specify:

1. Phone/emulator/simulator & version: Nexus 7, 2012 Tablet, Samsung Tab A

## Reproducible Demo

![1](https://user-images.githubusercontent.com/26292093/36879272-eb586614-1dfd-11e8-8aed-be909b199f30.PNG)
![2](https://user-images.githubusercontent.com/26292093/36879273-eba8bf92-1dfd-11e8-9b77-20d90a29f532.PNG)
![3](https://user-images.githubusercontent.com/26292093/36879339-3241a98c-1dfe-11e8-86a0-c1cb22132956.PNG)
![4](https://user-images.githubusercontent.com/26292093/36879340-337ee0bc-1dfe-11e8-9c9f-6e745237a744.PNG)

**Comment by tautvilas** [comment]
Unfortunately at the moment I can only recommend not using pastScrollRange=0 in Agenda.

**Comment by tautvilas** [comment]
this should be fixed in 1.19.2

**Comment by narender2031** [comment]
@tautvilas  facing a similar issue for the `futureScrollRange={0}`
