### ISSUE TITLE
onPressArrowRight clicked run to previous month

### ISSUE THREAD

**Issue by blackinitial** [wix/react-native-calendars#365]
## Description

i clicked onPressArrowRight, but run to previous mont

## Expected Behavior

this is a bug from library?
## Environment

react-native@0.52.2
react-native-calendars@1.17.3
 
im running in android..

**Comment by xclidongbo** [comment]
me too .

**Comment by sergchernata** [comment]
This happened to me if I copied one of the examples without modifying them. Specifically, overwriting the methods without actually having my own `substractMonth` implemented.

`onPressArrowLeft={substractMonth => substractMonth()}`

**Comment by blackinitial** [comment]
@sergchernata ok, i will implement it.

**Comment by sergchernata** [comment]
@blackinitial you can also just delete those declarations from the Calendar element. That's what I did; I didn't need the overwrite in the first place.

**Comment by tautvilas** [comment]
Can you give example code snippet that demonstrates this problem? thanks

**Comment by blackinitial** [comment]
@tautvilas remove OnPressArrowRight and Left can be fixed to me.
