### ISSUE TITLE
Some instructions on how to use your calendar would be really helpful.

### ISSUE THREAD

**Issue by jacklinton** [wix/react-native-calendars#380]
Never mind. I figured it out on my own. Seriously though, that was a lot of wasted hours. This has been one of the most popular React Native library packages for a long time. It's ready for some decent docs.

**Comment by ajwhite** [comment]
The example projects should serve as some getting started materials.

I agree that some additional documentation would go a long way.

Was there a particular challenge you faced that you'd like to see documented? What concept or implementation held you up the most?

**Comment by jacklinton** [comment]
I had a setup where the standard calendar would load with the current week as marked dates with the period style marking. Also if you click on a day, it will highlight that week instead. I could see my dates object in my props and everything (using react browser utility), but no markings would show. The vague allusions in the readme about marked dates needing to be treated as immutable and having to modify the reference led me down a long and fruitless garden path trying to figure out how to modify the "reference"  (I assume that means the actual calendar instance?) etc etc.  I assume this is all a round about way saying that if you change the marked dates object, you have to use setState to have them show up on the screen? Is that not what you would do anyway? I'm still baffled by all that.

The problem was simply that my date string had the month and day reversed in the object that I was passing to the marked dates prop. I even went as far as creating a ref for calendar in the constructor and then trying to assign the marked dates object to the props of that ref. The whole custom re-rendering logic that this component uses and the little breadcrumbs about how the marked dates worked had me reading through the source code trying to reason it out (which has no comments btw). It made me think that the problem was more complicated than it actually was. I'm still not exactly sure what all that means. I'm using MobX to manage my state, and when the marked dates change the view updates just like you would expect it to since they're based on an observed value. Nothing special needed to be done.

Really all it needed was an error saying the values I was assigning were invalid, but that's a whole other conversation... why wasn't there some kind of error? Why did it just quietly fail?

Once I got the formatting corrected, it works beautifully, including the "clicking on a date" to change the marked week.

**Comment by tautvilas** [comment]
Agree that we need better docs. Everyone is welcome to contribute :) #29 issue is about that
