### ISSUE TITLE
Agenda not rendering

### ISSUE THREAD

**Issue by hszeto** [wix/react-native-calendars#388]
I'm running: react-native 53.0 and react-native-calendars 1.17.4

Agenda is not being rendered. All I have is a blank screen.
```
render(){
  return(
    <Agenda />
  );
}
```

But this works.
```
render(){
  return(
    <CalendarList />
  );
}
```

Any idea what am I doing wrong or missing? My app has been `npm run eject`. Not sure if that matters....

**Comment by jgtorrejon** [comment]
I have the same problem, I set the documentation example in a Screen and doesn't rendered it.

**Comment by LeonardoAbrilBejarano** [comment]
+1

**Comment by jgtorrejon** [comment]
I try the Agenda example, and it works.  

[https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js](Agenda example)

**Comment by hszeto** [comment]
@jgtorrejon which version of react-native-calendars are you using?

**Comment by jgtorrejon** [comment]
The last -> "1.17.4"

**Comment by hszeto** [comment]
I finally got something to render. But it looks weird. 

```
render(){
  return(
      <View >
        <Agenda />
        <CalendarList />
      </View>
  );
}
```

<img width="356" alt="screen shot 2018-03-22 at 12 48 48 am" src="https://user-images.githubusercontent.com/8242082/37790921-10b56d54-2dc5-11e8-8907-c806f8d14b41.png">


Are `Agenda` and `CalendarList` supposed to work together? Nothing is rendered without `CalendarList` after `Agenda`. I also tried putting `CalendarList` before `Agenda`, that didn't work either.

**Comment by MrWangjiahuan** [comment]
How to get back to the current date？

**Comment by jgtorrejon** [comment]
@hszeto i don't know if that is the problem, but try removing the View tag.

**Comment by hszeto** [comment]
@jgtorrejon  I tried with or without View tag... no help...

**Comment by hszeto** [comment]
I final got it working. Need to set a height.

```
render(){
  return(
    <View style={{height: 600}}>
        <Agenda />
    </View>
  );
}
```

**Comment by temitope** [comment]
wow. that took me a couple hours. it was the height the whole time. that should be documented perhaps since it is not required to set height for Calendar to work.

**Comment by RicardoBer** [comment]
Height is not the problem

You put an <Agenda /> and a <CalendarList /> in your view on the comment that you say that it looks weird.

The <Agenta/> component has a CalendarList inside it.

Let just one agenda on your view and remove the height style.

**Comment by Yashnandha** [comment]
<Agenda
                items={agendaData}
                refreshing={false}
                renderItem={calenderDataUI} />

agendaData = {'2022-09-26':[]}

**Comment by limcolin** [comment]
> Height is not the problem
> 
> You put one Agenda and one CalendarList in your view (two diferent components) in the example in the comment that you say that "it looks weird".
> 
> The Agenta component has a CalendarList inside it.
> 
> Let just stay one agenda on your view and remove the height style.

Can confirm height **is** indeed the problem.
Even with one Agenda on its own, nothing is rendered until height is specified.

Thanks for the solution @hszeto

**Comment by pencilcheck** [comment]
I wish there is a way to make example more clear that you need to set height. Was stumbling until I found this thread.

**Comment by pencilcheck** [comment]
> 

That doesn't work unfortunately.

**Comment by albertolabuto** [comment]
If you don't want a fixed height, just set `flex: 1`
> 
> ```
> render(){
>   return(
>     <View style={{ flex: 1 }}>
>         <Agenda />
>     </View>
>   );
> }
> ```

**Comment by RameshTigeen** [comment]
also facing problem like aganada working but it loading only not does not the render the view of calander but i using react native calander aganda example why that is it my problem my code, can you help please

export default function AgandaCalanders() {
  const agandaDayList = {
    "2024-12-20": [
      {
        name: "Meeting 1",
        data: "the list of items that have to be displayed in agenda. If you want to render item as empty date the value of date key has to be an empty array",
      },
    ],
    "2024-12-18": [
      {
        name: "Meeting 2",
        data: "lorem ipsum or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
        height: 80,
      },
    ],
    "2024-12-19": [
      {
        name: "Meeting 3",
        data: "lorem ipsum or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
      },
    ],
    "2024-12-17": [
      {
        name: "Meeting 4",
        data: "lorem ipsum or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
      },
    ],
  };
  return (
    <Agenda
      data={agandaDayList}
      renderItem={(item: any, isFirst: any) => (
        <TouchableOpacity style={styles.item}>
          <Text style={styles.itemText}>{item.name}</Text>
          <Text style={styles.itemText}>{item.data}</Text>
        </TouchableOpacity>
      )}
      onDayPress={(day: Date) => console.log("Selected day", day)}
    />
  );
}

![image](https://github.com/user-attachments/assets/8cf15fc4-95bc-493a-bf29-8df43ade17db)

**Comment by RameshTigeen** [comment]
is it supports only the 2017 year at end of year
