### ISSUE TITLE
Flow and proptypes

### ISSUE THREAD

**Issue by sibelius** [wix/react-native-calendars#39]
What do you think of adding proptypes and flow types for this package?

**Comment by tautvilas** [comment]
Prop types could be nice addition, not sure about flow - did not use it

**Comment by sibelius** [comment]
Flow look like this:

- https://github.com/jwohlfert23/react-native-tag-input/blob/master/index.js
- https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js

**Comment by tautvilas** [comment]
Merged prop types PR #43 do not plan of adding flow types for now
