### ISSUE TITLE
How to use agenda with Google calendar

### ISSUE THREAD

**Issue by udarts** [wix/react-native-calendars#392]
I am trying to use the agenda view and integrate a google calendar into it.
I am able to get the event list from the google calendar, but am unable to add it to the calendar.

Is there a document that deals with this?
Have being trying to go through the agenda code, but didn't manage to get it working.

Please help.

**Comment by ajwhite** [comment]
Provide the events to the `Agenda` through the `items` prop, the Readme shows the required structure of that data. Then you can implement `renderItem` to define the presentation for each calendar event. And if you want the dates to be marked, provide information to the `markedDates` prop as well.

It's up to you, as the developer, to transform the data from Google calendar to satisfy the interfaces required by this library.

**Comment by tautvilas** [comment]
@ajwhite thanks for answering

**Comment by uguryiilmz** [comment]
Did you solve it how to do it? I am really struggling to do that. A sample would have been nice @udarts
