### ISSUE TITLE
How to enable only a few dates in the calendar?

### ISSUE THREAD

**Issue by harrymash2006** [wix/react-native-calendars#395]
Hi, I have a requirement where I need to allow the guest to book for the rooms on the available dates only, so I would like to gray out all the unavailable dates. Is this possible?

**Comment by tautvilas** [comment]
Yes, you can set the unavailable dates as disabled.

**Comment by harrymash2006** [comment]
@tautvilas How can I do that? Can you please advice

**Comment by tautvilas** [comment]
you can use markedDates property and provide which dates are disabled, please check out README.md and run example project

**Comment by harrymash2006** [comment]
yes, I read about marked dates, which variable I need to use to disable date? enabled:false?

**Comment by harrymash2006** [comment]
I am using markeddates to color the selected dates already

**Comment by tautvilas** [comment]
disabled: true

**Comment by whalemare** [comment]
Ok, but how **disable all** except few dates? With `enabled:false` we should have list with all available dates marked as disabled, but we need that by default all be disabled
