### ISSUE TITLE
OnPressArrowRight default callback going to previous month

### ISSUE THREAD

**Issue by AkshitSahani** [wix/react-native-calendars#397]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

If I write the onPressArrowRight function as in the documentation, when i press the right arrow, the calendar goes to the previous month. My onPressArrowRight function is:

onPressArrowRight={addMonth => addMonth()}

## Expected Behavior

I expected the calendar to go to the next month, which is what happens by default (when the right arrow is pressed). 

## Observed Behavior

The moment I try to use the onPressArrowRight function, and I write it exactly as in the documentation, trying to use the default callback, the calendar starts going to the previous month (on each right arrow press).

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:

/Users/AkshitSahani/expo RN projects/my-first-expo-project
└── react-native-calendars@1.17.4 
* `npm ls react-native`:

/Users/AkshitSahani/expo RN projects/my-first-expo-project
└── react-native@0.52.0 

Also specify:

iPhone 7 (running on device via expo)

## Reproducible Demo
-Render calendar in any view according to documentation.
- Provide an onPressArrowRight prop to the calendar as a function exactly as written below: 
          onPressArrowRight={addMonth => addMonth()}
- Reload the screen and press the right arrow. 
- Calendar goes to previous month wherease it should be going to the next month

**Comment by tautvilas** [comment]
please try the newest version I think this was fixed today
