### ISSUE TITLE
calendars current and  markedDates 

### ISSUE THREAD

**Issue by wudashuaige** [wix/react-native-calendars#398]
<Calendar
              // current={this.state.selected}   err
              firstDay={1}
              ref='fr'
              onDayPress={this.onDayPress}
              style={styles.calendar}
              hideExtraDays
            markedDates={{[this.state.selected]: { selected: true, selectedColor: 'orange', marked: true, disableTouchEvent: true },}}
            />

**Comment by wudashuaige** [comment]
current and markedDates   At the same time use  err

**Comment by tautvilas** [comment]
hello please open issue according to template

**Comment by JayricMok** [comment]
1. `npm install moment --save` 
2. `this.state = {
      todayDate: moment(new Date()).format('YYYY-MM-DD')
    }`
3. `markedDates={{
            [this.state.todayDate]: {marked: true, dotColor: '#000', activeOpacity: 1}
          }}`

**Comment by Shafran123** [comment]
How to show dynamic markeddates
