### ISSUE TITLE
Remove header and days, only show the events

### ISSUE THREAD

**Issue by udarts** [wix/react-native-calendars#399]
How can I remove the header (containing days of a week) and only show the events.

This is for example done in the google agenda app on iphone.
In that way there is more space for the events to show.

Cheers,

**Comment by tautvilas** [comment]
Hello, currently you can't do that. You could do a pull request enabling this functionality

**Comment by jarrx** [comment]
You could hide it with

```
          theme={{
            'stylesheet.calendar.header': {
              header: {
                height: 0
              },
              week: {
                height: 0
              }
            }
          }}
```

**Comment by afacar** [comment]
> You could hide it with
> 
> ```
>           theme={{
>             'stylesheet.calendar.header': {
>               header: {
>                 height: 0
>               },
>               week: {
>                 height: 0
>               }
>             }
>           }}
> ```

Is this worked for anyone? I tried and couldn't make it!

**Comment by jonathanatn** [comment]
> > You could hide it with
> > ```
> >           theme={{
> >             'stylesheet.calendar.header': {
> >               header: {
> >                 height: 0
> >               },
> >               week: {
> >                 height: 0
> >               }
> >             }
> >           }}
> > ```
> 
> Is this worked for anyone? I tried and couldn't make it!

@afacar 
It work fine for me. header erase the month name and week erase the name of days.

This is my implementation:
`<CalendarList
                                    // Enable horizontal scrolling, default = false
                                    horizontal={true}
                                    // Enable paging on horizontal, default = false
                                    pagingEnabled={true}
                                    hideExtraDays={false}
                                    onDayPress={day => {
                                          this.changeDate(day.dateString);
                                          console.log('selected day', day);
                                    }}
                                    // Collection of dates that have to be marked. Default = {}
                                    markedDates={{
                                          [this.state.selectedDay]: {
                                                selected: true,
                                                selectedColor: 'blue'
                                          }
                                    }}
                                    firstDay={1}
                                    onVisibleMonthsChange={month => {
                                          console.log(month);
                                    }}
                                    pastScrollRange={12}
                                    // Max amount of months allowed to scroll to the future. Default = 50
                                    futureScrollRange={12}
                                    // Set custom calendarWidth.

                                    calendarWidth={Dimensions.get('window').width}
                                    theme={{
                                          'stylesheet.calendar.header': {
                                                header: {
                                                      height: 0
                                                }
                                                // week: {
                                                //       height: 0
                                                // }
                                          }
                                    }}
                              />`

**Comment by DeltaCap019** [comment]
> How can I remove the header (containing days of a week) and only show the events.
> 
> This is for example done in the google agenda app on iphone.
> In that way there is more space for the events to show.
> 
> Cheers,

You had mentioned the Agenda in your question.

For Agenda, you can add this style to totally remove the header above the event list. 

'stylesheet.agenda.main': {
                header: {
                    height: 0,
                    width: 0,
                },
                knobContainer: {
                    height: 0,
                    width: 0,
                },
                weekdays: {
                    height: 0,
                    width: 0,
                },
                weekday: {
                    height: 0,
                    width: 0,
                },
                reservations: {
                    flex: 1,
                    marginTop: 10,
                    backgroundColor: COLORS.COLOR_F1F1F1,
                },
            },

![Simulator Screen Shot - iPhone 11 - 2020-05-29 at 15 33 02](https://user-images.githubusercontent.com/26134674/83248165-444f5a80-a1c2-11ea-99a8-0102d9be2ff4.png)


In the above Image, the Month dropdown you are seeing is an independent component.

**Comment by imamabdulazis** [comment]
@DeltaCap019 Thank you for your workaround, but on my screen was a duplicate date on week view when using Expandable Calendar with override style on the theme of Calendar.

https://user-images.githubusercontent.com/39134128/185411447-f667ff87-4afb-45ff-8cae-8af154b80d37.mov

**Comment by thongle12** [comment]
@imamabdulazis  for  Expandable Calendar, let's use 'stylesheet.calendar.header' in theme
You need to re-mount your component every time u test it, because the root CalendarProvider won't hot reload when you don't mount
