### ISSUE TITLE
Very small tappable area for right and left calendar arrows making it difficult to change months in iPhone

### ISSUE THREAD

**Issue by feliperaul** [wix/react-native-calendars#401]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Very small clickable area in the calendar right and left arrows, making it difficult to change months in iPhone. 

## Expected Behavior

Using a real device (iPhone), sometimes it takes 4-5 taps to actually hit the default arrows to change the month. 

I know the library supports a custom component for the arrows, but I didn't expect having to write one if I like the default, finding this to be a bug instead of something that I needed to customize. 

## Environment

npm ls react-native
└── react-native-calendars@1.17.4 

npm ls react-native
└── react-native@0.52.0

Also specify:

1. Phone/emulator/simulator & version: iPhone X

**Comment by theohdv** [comment]
Just had a look in the code and it could be solved by adding `hitSlop` prop to the `Touchable` component (https://github.com/wix/react-native-calendars/blob/master/src/calendar/header/index.js#L79). What do you think ?

**Comment by tautvilas** [comment]
solved in 1.18.2

**Comment by feliperaul** [comment]
@theohdv @tautvilas thanks!
