### ISSUE TITLE
Agenda items scrolling doesn't work in Android

### ISSUE THREAD

**Issue by AndrejGajdos** [wix/react-native-calendars#403]
## Description

I use `Agenda` component and cannot scroll list of items in Android. Scrolling works well in iOS.

## Expected Behavior

If I scroll down, I should see other items from the list, but scrolling doesn't work.

## Observed Behavior

I don't see any error messages.

![](https://media.giphy.com/media/SiEpXdSxzj3wTLc5wJ/giphy.gif)

## Environment

* `npm ls react-native-calendars`: *1.17.3*
* `npm ls react-native`: *0.54.2*

Also specify:

1. Phone/emulator/simulator & version: Google Nexus 5X - 8.0 - API 26 - 1080x1920/ Genymotion 2.12.0

## Reproducible Demo

```javascript
<View style={{ flex: 1 }}>
  <ScrollView>
    <View style={styles.container}>
      <Agenda
        ref={(component) => (this.agenda = component)}
        items={formatedCalendar}
        selected={currentDay}
        renderItem={this.renderItem.bind(this)}
        firstDay={1}
        pastScrollRange={3}
        futureScrollRange={3}
        onDayChange={(day) => {
          // Always future.
          const actualDate = moment(day.dateString, 'YYYY-MM-DD');
          const diff = moment.duration(actualDate.diff(this.state.currentDate));
          if (diff.asDays() > 7) {
            // Update currentDate to today.
            this.props.getCalendarDays(actualDate, 7, this.state.filter);
            this.setState({ currentDate: actualDate });
          }
        }}
        onCalendarToggled={(calendarOpened) => {
          this.setState({ calendarOpened });
        }}
        onDayPress={this._onDayPress.bind(this)}
        scrollEnabled
        markedDates={markedDates}
        renderDay={this.renderDay.bind(this)}
        renderEmptyData={this.renderEmptyData.bind(this)}
        rowHasChanged={this.rowHasChanged.bind(this)}
        monthFormat="MMMM"
      />
    </View>
  </ScrollView>
</View>;
```

**Comment by AndrejGajdos** [comment]
The issue that Android doesn't support nested `ScrollViews` and `Agenda` already contains `ScrollView`. If I have time, I will create a PR.

**Comment by subodhpareek18** [comment]
I don't think this issue should be closed. Please create a PR if you find the time but the feature seems important enough to keep this issue open.

**Comment by AndrejGajdos** [comment]
I wanted to achieve a functionality, where you can [pull to refresh](https://facebook.github.io/react-native/docs/refreshcontrol.html) agenda component to refresh the view. RefreshControl needs to be inside `ScrollView or ListView` and `Agenda` already contains `ScrollView`, so my code snippet works for iOS, but in Android I cannot scroll the Agenda.

I created separated components for iOS and Android. Here you can see how it works (I removed parent `ScrollView` and `RefreshControl` for Android component to make `Agenda` scrollable)

![iOS version with RefreshControl in parent ScrollView](https://media.giphy.com/media/5aUIjoU5PFEAEBtnUy/giphy.gif)

If you want to achieve in Android what you see in iOS, you need to implement `RefreshControl` in two places.

1) `RefreshControl` in `ScrollView` in `Agenda` component, I guess somewhere [here](https://github.com/wix/react-native-calendars/blob/383db8893ba7be52b00c918eccdcd8e4a84121c2/src/agenda/index.js#L407)

2) `RefreshControl` for whole view (screen). I tried [PullView](https://github.com/greatbsky/react-native-pull#pullview-demo) component and it works.

```javascript
<View style={{ flex: 1 }}>
        <PullView onPullRelease={this._onRefresh.bind(this)}>
          <View style={styles.container}>
            <Agenda
              ref={component => (this.agenda = component)}
              items={formatedCalendar}
              selected={currentDay}
              renderItem={this.renderItem.bind(this)}
              firstDay={1}
              pastScrollRange={3}
              futureScrollRange={3}
              onDayChange={(day) => {
                // Always future.
                const actualDate = moment(day.dateString, 'YYYY-MM-DD');
                const diff = moment.duration(actualDate.diff(this.state.currentDate));
                if (diff.asDays() > 7) {
                  // Update currentDate to today.
                  this.props.getCalendarDays(actualDate, 7, this.state.filter);
                  this.setState({ currentDate: actualDate });
                }
              }}
              onCalendarToggled={(calendarOpened) => {
                this.setState({ calendarOpened });
              }}
              onDayPress={this._onDayPress.bind(this)}
              scrollEnabled
              markedDates={markedDates}
              renderDay={this.renderDay.bind(this)}
              renderEmptyData={this.renderEmptyData.bind(this)}
              rowHasChanged={this.rowHasChanged.bind(this)}
              monthFormat="MMMM"
            />
          </View>
        </PullView>
      </View>
``` 

![pulling list items doesn't work](https://media.giphy.com/media/6odUmY8nJhvjtvUUDA/giphy.gif)

This is how it works if you implement only 2), so pull to refresh works only if you pull the calendar, but not if you pull the list items. My client is okay with this solution, because Android is not priority, but I am writing this here if someone will come across similar issue.

**Comment by temitope** [comment]
found the issue. very interesting. it had to do with the number of items added to the agenda. wow. didnt expect that. when i had 2 items it wouldnt scroll, added about 3 more and everything scrolled perfectly. this was just on android. head scratcher

**Comment by crisys11** [comment]
+1

**Comment by adamsolomon1986** [comment]
Ok, this is an ugly solution but it solves the issue (hack):

open node_modules/react-native-calendars/calendar-list/index.js

then Add 'nestedScrollEnabled' to the <flatlist> component.

**Comment by nrlnv** [comment]
no solution yet?
