### ISSUE TITLE
Day selected with backgroundImage 

### ISSUE THREAD

**Issue by abdelhakimkotti** [wix/react-native-calendars#427]
Can i add background Image for day  in markedDates for Calendar or Agenda ? 
for example : 
<Calendar  markedDates={{'2018-04-08': { selected: true, image: "image.png" }}}/>
Thanks

**Comment by tautvilas** [comment]
hi, currently no

**Comment by jamessawyer** [comment]
Do you have a plan to add this feature?

**Comment by tautvilas** [comment]
no, but it could be added by you via PR

**Comment by CyrilleFormont** [comment]
Is there any update about this ? @tautvilas
