### ISSUE TITLE
componentWillReceiveProps is deprecated and will be removed in the next major version.

### ISSUE THREAD

**Issue by troyz** [wix/react-native-calendars#428]
Hi,

Thanks for your library, now there is a warning message in the console, the [blog address](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by theohdv** [comment]
Which react-native version are you using ?

**Comment by troyz** [comment]
``` javascript
"react": "16.3.1",
"react-native": "0.55.1",
```

**Comment by mukho** [comment]
componentWillReceiveProps will be removed in the next major version react-native. What about migration to `getDeriveredStateFromProps`?

**Comment by honter36** [comment]
I have the same problem, do you like to help you with the migration?

**Comment by LeoMoreira1** [comment]
same problem here in RN 0.60.5

**Comment by nathsimpson** [comment]
It would be good (an understatement) to have this resolved before the next major version release (of react or react native?). Is anyone working on this?
