### ISSUE TITLE
selectedDayTextColor and selectedDayBackgroundColor props not working

### ISSUE THREAD

**Issue by matthewWatson571** [wix/react-native-calendars#437]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When overriding the selectedDayTextColor or selectedDayBackgroundColor prop I see no change to the text color of the selected day

## Expected Behavior
`[moment().format('YYYY-MM-DD')]: {
            marked: true,
            selectedDayTextColor: '#000000',
            selectedColor: 'rgb(246, 246, 246)',
            selected: true
          }`
-When adding this object to marked dates I expect the text color to be black with grey background. 
-The selectedDayBackgroundColor prop behaves the same, no change when overriding, thus the use of selectedColor (however this proves I'm correctly passing the props in).  

## Observed Behavior

-all props work as intended except selectedDayTextColor and selectedDayBackgroundColor

What actually happened when you performed the above actions?
-the text remained the default white

## Environment

Also specify:

1. Phone/emulator/simulator & version:
iPhone 7 simulator iOS 11.3

## Reproducible Demo

https://snack.expo.io/Skorce6jz

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by tautvilas** [comment]
please use marking documentation, the marking type that you are using only supports selectedColor prop override
