### ISSUE TITLE
Calendar days in CalendarList component works fine in debug mode but seems disabled/grayed out in normal mode

### ISSUE THREAD

**Issue by sumanth234** [wix/react-native-calendars#438]
Still facing the issue on calendarList select date.
Even i am getting the selected dates as invalid date.You can see it at top of header in that dialog

Reference for closed issue : https://github.com/wix/react-native-calendars/issues/404 

![screenshot_1523615269](https://user-images.githubusercontent.com/30984871/38730306-931c96a8-3f33-11e8-9c77-f36b6a71b3ee.png)
![screenshot_1523615235](https://user-images.githubusercontent.com/30984871/38730307-962bb306-3f33-11e8-863d-b0f257b475a6.png)

**Comment by tautvilas** [comment]
please provide code snippet to reproduce
