### ISSUE TITLE
Scroll Throttle too slow for Agenda scrolling 

### ISSUE THREAD

**Issue by jeremyfrancis** [wix/react-native-calendars#441]
When scrolling through the Agenda, the blue circle updates to the scrolled date very slow and when it has to catch up, it tends to spaz out the scroll position. I also have to wait a few seconds for the next Agenda items to show up when scrolling.

I noticed the scroll throttle is set to 1! I changed it to 8 and it runs perfectly. I think this should be changed.

Thanks!

**Comment by tautvilas** [comment]
hi, could you do a pull request with the change?

**Comment by Inbal-Tish** [comment]
@jeremyfrancis Hi. Please see version 1.236.0.
