### ISSUE TITLE
Add a style wrapper for main body

### ISSUE THREAD

**Issue by jamessawyer** [wix/react-native-calendars#442]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request
Add a style wrapper for main body (dayHeader part and days container)。I give my 'header' in 'stylesheet.calendar.header' a backgroundColor, I also give calendar container a padding, I found the header also get the padding, which makes header backgroundColor shorter than the whole container.
## Expected Behavior
Custom styles become more flexiable
What action did you perform, and what did you expect to happen?
I set container padding using percent, like '5%', so I make header width '100% + 5% *2', also make the header 'marginLeft: 5%'. I found it's not a very elegant way, and the result is not perfert.
## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.
d

**Comment by tautvilas** [comment]
please make a normal problem description
