### ISSUE TITLE
Selected Date in Agenda

### ISSUE THREAD

**Issue by gauravg924** [wix/react-native-calendars#448]
How to set the selected date in agenda at run time? Please help me.
For Example - i have  a date picker and when i select a date in the date picker the same date must also get selected in the agenda instead of hard coded.
Any help will be greatly appreciated..

**Comment by microwin168** [comment]
@gauravg924  Maybe you can use a common state between date picker and agenda select day.

**Comment by ArthurInTheShell** [comment]
Selected day is just one of the properties in the Agenda. After you used day picker, change the date format and pass it to Agenda.
