### ISSUE TITLE
Use only js based packages for example

### ISSUE THREAD

**Issue by sibelius** [wix/react-native-calendars#45]
What do you think of refactor the example to use create-react-native-app, and use react-navigation instead of react-native-navigation

I have this error when running the example:

`RCCManager.h file not found`

**Comment by tautvilas** [comment]
I think this probably would be a good move because example module would become easier to maintain

**Comment by jkomyno** [comment]
I'm doing this, PR incoming soon

**Comment by jkomyno** [comment]
@tautvilas done, please review it when you have time

**Comment by tautvilas** [comment]
Currently decided to stick with RNN
