### ISSUE TITLE
Get Month on Scroll

### ISSUE THREAD

**Issue by aditya27dev** [wix/react-native-calendars#452]
I am using this code... I just want to know if we can use onScroll method to get the current visible month?

```
<Agenda
    items={{
        '2018-04-18': [{text: 'item 1 - any js object'}],
        '2018-04-19': [{text: 'item 2 - any js object'}],
        '2018-04-20': [],
        '2018-04-21': [{text: 'item 3 - any js object'},{text: 'any js object'}],
    }}
    renderItem={this.renderItem.bind(this)}
    renderEmptyDate={this.renderEmptyDate.bind(this)}
    rowHasChanged={(r1, r2) => {return r1.text !== r2.text}}
/>
```

**Comment by Monte9** [comment]
This is something I am wondering about as well. I love this library and was able to get up and running pretty quickly. Here is what my current calendar implementation looks like:

<img width="224" alt="screen shot 2018-04-24 at 2 28 00 pm" src="https://user-images.githubusercontent.com/7840686/39215171-c8594b2c-47cb-11e8-83b5-bb804f72d58a.png">

and I am using the `<CalendarList />` component with `horizontal` and `pagingEnabled` props.

Hence in my use case (see screenshot above), I would like to display a unique monthly summary for every month. Hence on scroll I need a callback which returns a `month` string.

Is this currently possible? I cound't find anything on the docs, but please let me know if I missed something.

**Comment by skurgansky-sugarcrm** [comment]
I'm using loadItemsForMonth callback for this but it is triggered twice. For the first time the result is correct. But on the second i get previous month. Looking for solution.

**Comment by ManishAhire** [comment]
> I'm using loadItemsForMonth callback for this but it is triggered twice. For the first time the result is correct. But on the second i get previous month. Looking for solution.

Same issue

**Comment by ManishAhire** [comment]
Any solution..
