### ISSUE TITLE
initialScrollIndex doesn't work on CalendarList in Android

### ISSUE THREAD

**Issue by ErickMaeda** [wix/react-native-calendars#455]
## Description

I'm trying to render 7 months in CalendarList. So the first month to be rendered should be the current(April) one

January, February, March, April, May, June, July

On **iOS** the first item to render is April (Current)
On **Android** the first item to render is January (First)

```javascript
<CalendarList
    current={moment().format('YYYY-MM-DD')}
    onDayPress={(date) => this.onDayPress(date)}
    pastScrollRange={3}
    futureScrollRange={3}
    markedDates={this.state.markedDates}
    markingType={'period'}
/>
```

The initialScrollIndex in CalendarList is not working on Android. I tried in vertical list but had not success, on horizontal way works perfectly.

## Expected Behavior

The initial render should be the current month.

## Observed Behavior

The initial render is the first month.

## Environment

1. Phone/emulator/simulator & version:

Android Device && Simulator version 4.2, 5.0 & 6.0

```json
  "dependencies": {
    "react": "^16.3.1",
    "react-native": "^0.55.2",
    "react-native-calendars": "^1.18.2"
  }
```

**Comment by vagnerSl** [comment]
+1

**Comment by tautvilas** [comment]
Can you reproduce this bug in example project too?

**Comment by craig8two** [comment]
I was experiencing the same issue in Android only, when I reduced the amount of pastScrollRange and futureScrollRange it fixed the issue. Hope that helps to figure out how to fix it. Cheers

**Comment by tautvilas** [comment]
Hello, I have tried this code in calendars example project on android simulator:

` <CalendarList
        current={'2018-05-01'}
        onDayPress={(date) => this.onDayPress(date)}
        pastScrollRange={3}
        futureScrollRange={3}
        // markedDates={this.state.markedDates}
        markingType={'period'}
      />`

React Native 55.4, did not notice any problem with calendars initial index
