### ISSUE TITLE
Accept dayNamesShort repeated

### ISSUE THREAD

**Issue by sibelius** [wix/react-native-calendars#46]
I need to implement this:

![image](https://cloud.githubusercontent.com/assets/2005841/26692269/74deacfe-46d6-11e7-804f-1e62a469245b.png)

Right now it is not possible because of this `key`:
https://github.com/wix/react-native-calendars/blob/master/src/calendar/header/index.js#L83

I will send a pr to use the `index` of `map` instead

**Comment by tautvilas** [comment]
@sibelius I see that you have days with 2 dots marking. Did you implement a custom day component?

**Comment by sibelius** [comment]
not yet, but I will, then I will send a Pr

**Comment by jeveloper** [comment]
@sibelius  Hi , just curious , is this possible , to have 2 or more dots for same day? If so , what data structure should i use

thank you

**Comment by sibelius** [comment]
@jeveloper take a look on this https://github.com/wix/react-native-calendars/pull/212
