### ISSUE TITLE
Misleading documentation regarding `current` props and showLoadingIndicator

### ISSUE THREAD

**Issue by feliperaul** [wix/react-native-calendars#460]
Using version "1.18.2"

## Description

1. Documentation states the following for loading indicator (spinner):

_The loading indicator next to month name will be displayed if <Calendar /> has displayLoadingIndicator property and markedDays collection does not have a value for every day of the month in question. When you load data for days, just set [] or special marking value to all days in markedDates collection._

Problems:
- It mentions `markedDays` and `markedDates` indicating that they are 2 different props, but only markedDates actually exists;
- The code for showing the indicator only runs if the calendar has `current` props, which is not mentioned anywhere in the documentation above. You can confirm this here: https://github.com/wix/react-native-calendars/blob/ba5bdd5d07e22b54276cd52277edeb5ffae5e7af/src/calendar/index.js#L248

- The full code for displaying the loading indicator is:
```
const current = parseDate(this.props.current);
    if (current) {
      const lastMonthOfDay = current.clone().addMonths(1, true).setDate(1).addDays(-1).toString('yyyy-MM-dd');
      if (this.props.displayLoadingIndicator &&
          !(this.props.markedDates && this.props.markedDates[lastMonthOfDay])) {
        indicator = true;
      }
    }
```
As you can see, the indicator will appear with that condition resolves to true, which will only happen if this.props.markedDates[lastMonthOfDay] is false. So it would be better to clarify this in the docs that setting markedDates to an empty object `{}` like <Calendar markedDates={{}} ...` will do the trick.

But that's not all. As you see from the code above, the indicator will only appear if <Calendar> has `current` props. 

This is what the documentation states about the current props:

> // Initially visible month. Default = Date()
>   current={'2012-03-01'}

As you see, it clearly states that `current` defines the INITIALLY visible month. But in our tests and reading source code, we found out that current actually defines the currently displayed calendar month, by parsing the string in format 'YYYY-MM-DD' provided to current.

I'm saying this because we use a custom function to load months, also explained in the docs:

> // Handler which gets executed when visible month changes in calendar. Default = undefined
>   onMonthChange={(month) => {console.log('month changed', month)}}

So what we had to do was to create a state in our wrapper component to hold the `current` value (a string in YYYY-MM-DD, pass that as props to the component like `<Calendar current={this.state.current}` __and__ update that state on the onMonthChange function callback, otherwise clicking in the arrows would prevent the month from ever changing.

Given all this, I don't know how the lib mantainers want to proceed, if either by updating the docs by making this behavior clearer or if by refactoring some code.

**Comment by arnaudambro** [comment]
it's still not clear how to use this `displayLoadingIndicator` prop... this issue should be open @stale

but the lib is great, I did otherwise with the loading indication.
