### ISSUE TITLE
How to manually reload/refresh the agenda

### ISSUE THREAD

**Issue by LongicornYu** [wix/react-native-calendars#463]
I am dynamically loading notes for each day from firebase into the state then load into the agenda.  The agenda is not refreshing when I change the content in the state. Only when I reload the page, the changes will show.  Is there a way to manually trigger the reload of the agenda? Thanks.

**Comment by LongicornYu** [comment]
In my case, I rendered icons for marked days in the day view and marked periods in the calender view of the agenda dynamically. The data is fetched from firebase database into state then used to render the agenda. I also had a 'mark' buttons rendered for each day in the day view. when clicking on the button for a specific day, it will mark that date. That date should shown as marked in the calendar view and an icon should show up for that day in the day view.  I thought changing the state will make the agenda re-render, but looks like it only re-rendered the calendar view, the day in the calendar is shown as marked. But somehow in the day view, the icon is not shown up.

I later found a workaround. I found that selecting a day from the calendar view will re-render the day view. So I manually called the function in the underlying code that handles the selection of a specific day. I called that function for the day that I marked after clicking the mark button, so that will update the day view for me.

**Comment by gabriel-TheCode** [comment]
Same problem
https://github.com/wix/react-native-calendars/issues/463#issuecomment-389714895

**Comment by onemoredayApp** [comment]
Hi, I've same problem, i've this code:
```
state = { 
        days: {
            '2018-11-26': {selected: true, selectedColor: 'red'},
            '2018-11-27': { selected: true, selectedColor: 'red'},
            '2018-11-28': { selected: true, selectedColor: 'red'},
        }
    }
removeDay = (date) => {
        var newDate = this.state.days;
        if(newDate[date].selected) {
            newDate[date].selected = false;
        } else {
            newDate[date].selected = true;
        }
        this.setState({ days: newDate })
        console.log(this.state.days)
    }
<Calendar
                                markedDates={
                                    this.state.days
                                }
                                onDayPress={(day)=>{ this.removeDay(day.dateString)}}
                                markingType={'multi-dot'}
                                minDate={'2018-11-26'}
                                maxDate={'2018-11-28'}
                            />
```

The code works well but the calendar not update on click!

**Comment by budo60** [comment]
reset items {} and call loadItems() worked for me too, im wondering if there is a possibility to re-render only one day of agenda and not all of them, if anyone got an idea this possibilty would be great

**Comment by luisiacc** [comment]
Is there and update from this ?, i got the same issue, reset items and call loadItems does not work for me

**Comment by luandiego7** [comment]
@luisiacc , when i call loadItems(), i get errror.
loadItems needs parameter day.. 
how can i solve? can you help me?
![Captura de Tela 2021-05-26 às 17 20 33](https://user-images.githubusercontent.com/30122229/119725792-c494b400-be46-11eb-97f8-2385b4fdd799.png)

**Comment by luandiego7** [comment]
@luisiacc , when i call loadItems(), i get errror.
loadItems needs parameter day..
how can i solve? can you help me?

my code: 

import React, {useState, useEffect} from 'react';
import {Container} from './styles';
import {StyleSheet, View, Text} from 'react-native';

import {Agenda} from 'react-native-calendars';
import Api from '../../Api';
import {colors, fonts} from '../../styles';

const timeToString = (time) => {
    const date = new Date(time);
    return date.toISOString().split('T')[0];
}

const agendamento = () => {
    const [loading, setLoading]           = useState(false);
    const [agendamentos, setAgendamentos] = useState({});
    var hoje = new Date();
    var d    = hoje.getDate();
    var m    = hoje.getMonth() + 1;
    var y    = hoje.getFullYear();
    d        = d < 10 ? '0'+d : d;
    m        = m < 10 ? '0'+m : m;
    hoje     = `${y}-${m}-${d}`;

    useEffect( () => {
        getAgendamentos();
    }, []);

    useEffect(() => {
        if (agendamentos === null) {
            loadItems();
        }
    }, [agendamentos])

    const reloadAgenda = async () => {
       setAgendamentos(null);
    }

    const getAgendamentos = async () => {
        setLoading(true);
        var data = await Api.getAgendamentos();
        setAgendamentos(data.agendamentos);
        setLoading(false);
    }

    const rowHasChanged = (r1, r2) => {
        return r1.id !== r2.id;
    }

    const renderEmptyDate = () => {
        return (
            <View style={itemStyle.emptyDate}>
                <Text></Text>
            </View>
        );
    }

    const loadItems = (day) => {
        for (let i = -15; i < 85; i++) {
            const time    = day.timestamp + i * 24 * 60 * 60 * 1000;
            const strTime = timeToString(time);
            if (!agendamentos[strTime]) {
                agendamentos[strTime] = [];
            }
        }
        const newItems = {};
        Object.keys(agendamentos).forEach(key => {
            newItems[key] = agendamentos[key];
        });
        setAgendamentos(newItems);
    };

    const renderItem = (dia) => {
        return (
            <View style={itemStyle.item}>
                <View>
                    <Text
                        style={{
                            color: '#48506B',
                            fontFamily: fonts.primaryRegular,
                            marginBottom: 10,
                        }}
                    >
                        {dia.fk_manutencao_preventiva == null ? dia.get_chamado.descricao : dia.get_manutencao_preventiva.descricao}
                    </Text>
                    <Text style={{ color: '#9B9B9B', fontFamily: fonts.primaryRegular }}>
                        {'08:00'}
                    </Text>
                </View>

                {/*<View styleName="horizontal h-start">{labels}</View>*/}
            </View>
        );
    }

    const itemStyle = StyleSheet.create({
        item: {
            backgroundColor: 'white',
            flex: 1,
            borderRadius: 5,
            padding: 10,
            marginRight: 10,
            marginTop: 17
        },
        emptyDate: {
            height: 15,
            flex: 1,
            paddingTop: 30,
            paddingLeft:15
        }
    });

    return (
        <Container>
            <Agenda
                items={agendamentos}
                loadItemsForMonth={loadItems}
                selected={hoje}
                renderItem={renderItem}
                renderEmptyDate={renderEmptyDate}
                rowHasChanged={rowHasChanged}
                refreshing={loading}
                onRefresh={ () => reloadAgenda() }
                theme={{
                    dotColor: colors.primaryLight,
                    selectedDayBackgroundColor: colors.primaryLight,
                    agendaDayTextColor: colors.primaryLight,
                    agendaDayNumColor: colors.primaryLight,
                    agendaTodayColor: '#4F44B6',
                    backgroundColor: '#F1F1F8',
                }}
            />
        </Container>
    );
}

export default agendamento;

the error: 

![Captura de Tela 2021-05-26 às 17 20 33](https://user-images.githubusercontent.com/30122229/119726529-9663a400-be47-11eb-8611-d395540e4707.png)
