### ISSUE TITLE
How can I integrate with react-native-timeline-listview

### ISSUE THREAD

**Issue by microwin168** [wix/react-native-calendars#465]
In Agenda component  when I select a day,I want to integrate with react-native-timeline-listview
([https://github.com/thegamenicorus/react-native-timeline-listview](https://github.com/thegamenicorus/react-native-timeline-listview))

When I  select a day I need a array of agenda  of selected day .
How can I get the array of select day.

**Comment by shoebmogal** [comment]
Instead of sending all items for a particular date as an array, send it as an array of array.
This way all items of that particular date will be sent to the `renderItem` function.
There you can use any component you want to render it.

**Comment by cylim** [comment]
@shoebmogal Do you know how can I hide the `Reservation List` and use my own component? Instead of getting data from `<Agenda>`, I rather get it from my component state directly, to make the code cleaner.

**Comment by cylim** [comment]
@mharrisweb Sorry, I don't have the solution. What I did in that particular project is to use the Reservation List with my custom component in it.
