### ISSUE TITLE
Agenda View is breaking Android

### ISSUE THREAD

**Issue by Nemesisesq** [wix/react-native-calendars#476]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

when I try to load the adgenda on android this is the error I get
![screenshot_1525663969](https://user-images.githubusercontent.com/3838176/39683877-057aa2ee-5186-11e8-8279-f7982e220eea.png)

undefined is not a function(evaluating '_iterator[typeof Symbol === "function"?Symbol.iterator:"@@iterator"]()')

I have attached a screen shot of expo. I know the problem involves JS engine not being able to support 
"for of" I have tried polyfills but nothing works does anyone have any idea of what to do ?

**Comment by tautvilas** [comment]
Hello, looks like this is not related to calendars library

**Comment by aivarsliepa** [comment]
How is it not related to this library? 
One of the first sentences in README.md is
> The package is both **Android** and **iOS** compatible.

But library contains code that is not compatible with Android.

**Comment by aivarsliepa** [comment]
If anyone stumbles on the same issue.
These polyfills helped for me https://github.com/facebook/react-native/issues/15902#issuecomment-375521246

**Comment by jackbillstrom** [comment]
I saw this, which worked out smoothly.

https://github.com/facebook/react-native/issues/20902#issuecomment-431177779

> I upgraded to 0.57.2 from 0.55.4 and the only thing that worked for me was to add babel-polyfill.
> 
> > npm i --save-dev babel-polyfill
> 
> then in my index.js:
> 
> > import 'babel-polyfill';
> 
> I did not try what @dungps suggested.
