### ISSUE TITLE
copied code https://github.com/rghorbani/react-native-general-calendars

### ISSUE THREAD

**Issue by sibelius** [wix/react-native-calendars#479]
https://github.com/rghorbani/react-native-general-calendars just copied this code and changed license

https://github.com/rghorbani/react-native-general-calendars/blob/master/LICENSE

**Comment by tautvilas** [comment]
Thanks, what to do, can we report it somehow?

**Comment by tautvilas** [comment]
Thanks for reporting @sibelius I will keep in touch with the author of this new library
