### ISSUE TITLE
Calendar List not showing inside react-navigation StackNavigator

### ISSUE THREAD

**Issue by winsaz** [wix/react-native-calendars#48]
Hi, I'm trying to create a CalendarList after I click on a button. So, I decided to navigate the view to FilterDateScreen.js using StackNavigator react-navigation and show a CalendarList.

Here is my Code inside FilterDateScreen.js

`<CalendarList
                    onVisibleMonthsChange={(months) => {console.log('now these months are visible', months);}}
                    pastScrollRange={50}
                    futureScrollRange={50}
                    scrollEnabled
/>`

It shows nothing inside FilterDateScreen until I scroll it a bit. I have test it without using any react-navigation StackNavigator and it works fine (no scroll is needed). What am i missing?

**Comment by watadarkstar** [comment]
I have the same issue 👍  Also doesn't work in a `TabNavigator` using `react-navigation`. Commenting to follow.

**Comment by sibelius** [comment]
This is problem with ListView and FlatList on React Native

**Comment by watadarkstar** [comment]
@sibelius can you please link to a PR or issue that this is related to in `react-native`

**Comment by winsaz** [comment]
Hi, according to what @sibelius said about ListView problems, I have solved it by modifying the library itself.

You need to add options
`initialListSize={20}
removeClippedSubviews={false}`
to 
`<ListView />`

This will solve the problem.

**Comment by watadarkstar** [comment]
@winsaz This works but be careful with ` removeClippedSubviews={false}` as it might effect performance (see [this](https://facebook.github.io/react-native/docs/listview.html#removeclippedsubviews)) . Nonetheless thank you for the fix 👍

**Comment by tautvilas** [comment]
I'm not sure if this will help but did you try adding flex:1 to element containing CalendarList?

**Comment by winsaz** [comment]
@tautvilas i have tried adding flex like this
`<View style={{ flex: 1 }}> <CalendarList /> </View>`

and it didnt work
or did u mean by anything else?

**Comment by watadarkstar** [comment]
@tautvilas @winsaz I also tried that and it didn't work.

**Comment by tautvilas** [comment]
Hey, I actually never tried this lib with react-navigation, I will look into it when I get some time, but people who have more experience with react-navigation could help better @sibelius

**Comment by sibelius** [comment]
this is the issue https://github.com/facebook/react-native/issues/1831

it is not a problem with this package, we can close this

**Comment by tautvilas** [comment]
thx @sibelius
