### ISSUE TITLE
bug: Agenda header is scrolling to wrong position when minimized

### ISSUE THREAD

**Issue by paolord** [wix/react-native-calendars#485]
## Description

Supplied Agenda view with selected date prop and the header is scrolled to either the wrong week or an empty space between months in the calendarlist

## Expected Behavior

In the default/minimized state, the header should be scrolled to the correct week containing either the current date or selected date

## Observed Behavior

It's displaying either an empty space or the wrong week

![bug](https://user-images.githubusercontent.com/1720393/40046380-727bcbc2-585f-11e8-88e2-2910d4617a91.png)

possibly similar to https://github.com/wix/react-native-calendars/issues/480

**Comment by Inbal-Tish** [comment]
@paolord Is this issue still relevant?

**Comment by MuhammedRafi** [comment]
@Inbal-Tish Yes ,this is still there

**Comment by Inbal-Tish** [comment]
Please see comment on PR #486
