### ISSUE TITLE
Agenda in ios

### ISSUE THREAD

**Issue by AbdelkarimGhaouri** [wix/react-native-calendars#487]
![32e89cfa-5bc0-492f-9b8e-719b55abdebf](https://user-images.githubusercontent.com/38378058/40074658-b8548b02-5869-11e8-8779-63b3f89a4879.jpg)

Hello

Please, I do not see the same results of the calendar code props

Thank you

**Comment by nikolal** [comment]
I am getting the same issue

**Comment by simon-study** [comment]
What is ios version have this issue?
