### ISSUE TITLE
Help needed in renderArrow prop

### ISSUE THREAD

**Issue by ZeerakHameem** [wix/react-native-calendars#488]
Hi, I need to know how to use 'direction' prop to render left & right arrows in Calendar. I tried finding it in the examples and issues.
The same image is rendered for left and right arrows. I am unable to understand how to use the direction parameter to render specific arrow (left / right).
Thanks in advance.

**Comment by ZeerakHameem** [comment]
Nevermind, i found a way. Leaving this for anyone in future.
renderArrow ={(direction) => { direction === 'left' ? this.renderLeftArrow : this.renderRightArrow }

**Comment by JayricMok** [comment]
I try your solution, but it not work
