### ISSUE TITLE
Adding Image in selected Day

### ISSUE THREAD

**Issue by SaurabhBrst** [wix/react-native-calendars#489]
I wan't to distinguish the selected dates on the basis of day or night for which i need to show image or textual representation in calendar.

![screenshot_20180516-020918](https://user-images.githubusercontent.com/35626666/40103683-f118cd02-590b-11e8-9ebc-91918ec73813.jpg)

I need any prop to add image on selected day or show any mark by which anyone can easily understand that the dates are selected for day or for night. 

Please Help

**Comment by LongicornYu** [comment]
how did you add that day and night icon?

**Comment by SaurabhBrst** [comment]
The image i have attached is a design which i have to implement on calendar but not able to add icons on selected dates.
