### ISSUE TITLE
CalendarList not showing MarkedDates

### ISSUE THREAD

**Issue by craigcoles** [wix/react-native-calendars#49]
Using some sample data to pass into the CalendarList component, yet the dates are not marked.

### Component Render

```js
<CalendarList   
  onDayPress={(day) => { console.log('selected day', day) }}
  markedDates={{
    '2017-05-24': { selected: true, marked: true },
    '2017-05-25': { marked: true },
    '2017-05-26': { disabled: true },
  }}
/>
```

### Screenshot

![screen shot 2017-06-05 at 15 21 33](https://cloud.githubusercontent.com/assets/996430/26787701/e013a4b4-4a02-11e7-9580-11642162f8c8.png)

**Comment by tautvilas** [comment]
Hi, that's weird. Tried to put your code in example/src/screens/calendarsList.js and it worked OK

![screen shot 2017-06-05 at 17 44 30](https://cloud.githubusercontent.com/assets/1044090/26788671/aeaddad4-4a16-11e7-9b58-85a0979f0130.png)

**Comment by craigcoles** [comment]
@tautvilas That is weird! Let me see if I can do some more digging

**Comment by craigcoles** [comment]
@tautvilas I was running `v1.2.11`, updated to latest (`v1.2.21`) and all is sorted! Apologies, I should of checked this first before opening an issue 👍
