### ISSUE TITLE
Agenda - Memory Leak / Maximum update depth

### ISSUE THREAD

**Issue by marcocesarato** [wix/react-native-calendars#496]
## Description
HI, I've a memory leak and after some time a Maximum update depth error on agenda. I've tried set the renderItem as the empty item but nothing is changed. If i put an empty array on items nothing change. What the problem is? How to Solve It?

## Environment
"react-native-calendars": "^1.19.3":
"react-native": "0.55.4":

### Without Agenda
![Screen1](https://i.imgur.com/1b6fDWp.png)
https://imgur.com/1b6fDWp\
### With Agenda
![Screen2](https://i.imgur.com/ajobioe.png)
https://imgur.com/ajobioe

## Example
This is my code:

```js
rowHasChanged(r1, r2) {
		return r1.date_start !== r2.date_start;
	}
renderEmptyDate() {
		return (
			<Container style={AgendaStyle.empty}>
				<Icon style={AgendaStyle.icon_empty} name="ios-moon-outline" size={20} color="#000"/>
				<Text>No activities</Text>
			</Container>
		);
	}
	render() {
		return (
				<Container>
        <Agenda
						selected={this.state.today}
						items={this.state.dataItems}
						renderItem={this.renderEmptyDate}
						renderEmptyDate={this.renderEmptyDate}
						rowHasChanged={this.rowHasChanged}
						style={{width: this.state.dims.width, overflow: 'visible'}}
						firstDay={1}
						pastScrollRange={1}
						futureScrollRange={4}
						hideKnob={Platform.OS === 'windows'} // Bugged on windows
						theme={{
							dotColor: '#F00',
							agendaKnobColor: '#F00',
							selectedDayBackgroundColor: '#F00',
							todayTextColor: '#F00',
							agendaTodayColor: '#F00',
						}}
					/>
        </Container>);
}
```

**Comment by veedeo** [comment]
Hey any progress on this? Did you find the root cause of the problem?

**Comment by Seanmclem** [comment]
still get this problem with the Agenda examples

**Comment by darnell-siten** [comment]
@marcocesarato seems like agenda stopped working. I am getting: 
<img width="416" alt="Screen Shot 2021-06-23 at 9 19 09 PM" src="https://user-images.githubusercontent.com/58380652/123202003-a8e1f500-d468-11eb-9188-78269242fce9.png">

From the example.

**Comment by sam3k** [comment]
I am getting this issue on a functional component with an Agenda. Any tips?

**Comment by Heroyrr** [comment]
I still getting same error. Can anyone pls tell me
