### ISSUE TITLE
i18n for months and week days

### ISSUE THREAD

**Issue by sifrenette** [wix/react-native-calendars#5]
Currently there is no way to change the locale for months and weekdays. Defaults are in english.

Possible solutions suggestions: 

Add a monthNamesHash (or only monthNames) prop that would map the english months to user defined ones. (ex.: { 'January': 'Janvier', 'February': 'Février', ... }). Same thing for weekdays (ex.: { 'Sun': 'Dim', 'Mon': 'Lun', ...}). Then use those hash in CalendarHeader.

Or

Add a locale prop to the calendar component. (ex.: 'en' | 'fr' | 'de' , default: 'en'), add supported locales to XDate configuration, then use the locale when formatting the months and weekdays in CalendarHeader. [Example](https://gist.github.com/arshaw/1221376)

**Comment by tautvilas** [comment]
Good idea. Maybe I would just prefer structure of language hashes with arrays of values. e.g.:

```{'en': {months: ['January', 'Febuary']... , days: ['Sun', 'Mon']...```

But maybe somebody knows if there is a source for these translation in somewhere in github? So we could import another library with localized month/weekday names and just add it to XDate config.

**Comment by tautvilas** [comment]
After merging #7 pull request now you can to set custom date locale. Just import `Xdate` in your your app that uses calendars and setup locale like this:

```javascript
import XDate from 'xdate';

XDate.locales['fr'] = {
  monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  monthNamesShort: ['Janv.','Févr.','Mars','Avril','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
  dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
  dayNamesShort: ['Dim.','Lun.','Mar.','Mer.','Jeu.','Ven.','Sam.']
};

XDate.defaultLocale = 'fr';

**Comment by tautvilas** [comment]
Syntax has changed to:

```javascript

import {LocaleConfig} from 'react-native-calendars';

LocaleConfig.locales['fr'] = {
  monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  monthNamesShort: ['Janv.','Févr.','Mars','Avril','Mai','Juin','Juil.','Août','Sept.','Oct.','Nov.','Déc.'],
  dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
  dayNamesShort: ['Dim.','Lun.','Mar.','Mer.','Jeu.','Ven.','Sam.']
};

LocaleConfig.defaultLocale = 'fr';

```
