### ISSUE TITLE
How to use combination of markingType?

### ISSUE THREAD

**Issue by gokulpkurup94** [wix/react-native-calendars#502]

**Comment by Yiling-J** [comment]
Same question, I need to use dot and period together, dot indicate selectable date and period are selected ones.

**Comment by SDushan** [comment]
![screenshot 25](https://user-images.githubusercontent.com/10815317/42420910-ad072d6c-82ea-11e8-9595-d8d4986bd687.png)
Same here, need to use both dot & period in the same calendar.

**Comment by amorettimarcelo** [comment]
anyone?

**Comment by orlov-vo** [comment]
https://github.com/wix/react-native-calendars/pull/632

I think the PR can help you in the question
