### ISSUE TITLE
render events day hours 

### ISSUE THREAD

**Issue by AbdelkarimGhaouri** [wix/react-native-calendars#503]
how to render Day ? 
Events : Start: ' 28-5-2018 12:00:00 ', End: ' 28-5-2018 13:00:00 '
![a6f4fdce-9e5a-4d0c-a3f4-93feed785454](https://user-images.githubusercontent.com/38378058/40619040-173b8594-6283-11e8-9717-0d12ee0334e1.jpg)

**Comment by jojonarte** [comment]
@ReactDevBeginner  did you manage to do it?

**Comment by ReactDevBeginner** [comment]
@jojonarte No, I have not found a solution, do you have an idea?

**Comment by Tebrynn** [comment]
Anyone got a solution for this request? I'd like to render events by day and hour
