### ISSUE TITLE
Add renderArrow to CalendarList

### ISSUE THREAD

**Issue by g00dnatur3** [wix/react-native-calendars#505]
Somebody please add this line of code

`renderArrow={this.props.renderArrow === undefined ? undefined : this.props.renderArrow}`

to file

`https://github.com/wix/react-native-calendars/blob/master/src/calendar-list/item.js`

at line number `27`

Thank You Very Much!

**Comment by g00dnatur3** [comment]
Actually please add these lines

```renderArrow={this.props.renderArrow === undefined ? undefined : this.props.renderArrow}
          onPressArrowLeft={this.props.onPressArrowLeft === undefined ? undefined : this.props.onPressArrowLeft}
          onPressArrowRight={this.props.onPressArrowRight === undefined ? undefined : this.props.onPressArrowRight}```

This should do the trick and allow full customization of the left and right arrows in . the calendar list.

Many thanks for the developers for making this code well organized and easy to read.

Cheers!

**Comment by olfek** [comment]
@Inbal-Tish This issue can be closed.

**Comment by mensurlatifi** [comment]
How can I add arrows to Calendar List
@g00dnatur3

**Comment by zagoa** [comment]
Now you can use the props `renderArrow={true}`.

**Comment by mensurlatifi** [comment]
@zagoa  
    "react-native-calendars": "^1.213.0",
I have this version installed and in the CalendarList when I call renderArrow={true} it throws a warning saying it expects a function at renderArrow, not a boolean value.

**Comment by huynhnhatthiep** [comment]
Now you can use renderArrow with syntax as below:
renderArrow={(direction) => direction === 'left' ? (<IconLeft>) : (< IconRight/>)}
