### ISSUE TITLE
make calendar collapsible

### ISSUE THREAD

**Issue by begoat** [wix/react-native-calendars#508]
## Description
I want to control whether the Calendar Component is **collapsed** just like Agenda(show only one week instead of one month, and there is a button to show the full view of it when collapsed). But It seems that we are not given such API.

## Environment

Please run these commands in the project folder and fill in their results:

* `react-native-calendars@1.19.3`
* `react-native@0.53.0`

Thanks in advance :)

**Comment by ProductiveNYC** [comment]
+1

**Comment by ConnorGutman** [comment]
+1

**Comment by ronniegong** [comment]
+1

**Comment by SofiaChuquin** [comment]
+1

**Comment by pinpong** [comment]
+1

**Comment by rexlow** [comment]
Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between view. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).

[The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)

**Comment by Wbqqqq** [comment]
+1

**Comment by hieupaul** [comment]
+1

**Comment by trungtransg** [comment]
+1

**Comment by trancanh2202** [comment]
Hi rexlow, Can you share me this code. I need it. Please help me.

![screen shot 2018-10-16 at 11 54 52 am](https://user-images.githubusercontent.com/42834870/46993624-563dd000-d13a-11e8-9ed4-d0e3ba5167a9.png)
![screen shot 2018-10-16 at 11 55 00 am](https://user-images.githubusercontent.com/42834870/46993625-563dd000-d13a-11e8-8d75-ba9ed4be7c7f.png)

**Comment by trancanh2202** [comment]
+1

**Comment by isaaclem** [comment]
Hi @rexlow, wondering if you have already solved the problem and possibly sharing the code with us?

**Comment by kelvininnovator** [comment]
I'd also like to see or hear this code, would be really useful.

**Comment by fgagneten** [comment]
+1

**Comment by ismailkhan89** [comment]
I want to have some thing like this 
![image](https://user-images.githubusercontent.com/47290526/53632175-103f5f80-3c36-11e9-8c9a-4825916ffb05.png)

Full month view in agenda. don't want to use scroller. if somebody has done this kind work kindly share it.

**Comment by ihsanktmr** [comment]
It is possible to make a weekly view but as i commented in the another issues it is temporary solution please check out my comment. 

[https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538](url)

**Comment by ihsanktmr** [comment]
I explained it here https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538

**Comment by okay00** [comment]
> Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between views. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).
> 
> [The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)

please share with me this code

**Comment by Vikash-algo** [comment]
Hi @okay00 did you get the code???

**Comment by Vikash-algo** [comment]
> Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between views. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).
> 
> [The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)

Hi can you please share that code with me i need this on urjent basis.

**Comment by Vikash-algo** [comment]
> > Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between views. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).
> > [The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)
> 
> please share with me this code

did you get the code?

**Comment by okay00** [comment]
> > > Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between views. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).
> > > [The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)
> > 
> > 
> > please share with me this code
> 
> did you get the code?

no bro

**Comment by Vikash-algo** [comment]
> > > > Hey guys seeing there's no sign of development of this issue, I took up the challenge and made a calendar component with collapsible week view. Scrolling has been buttery smooth in both views but I have some issue with switching between views. Hopefully, someone can have a look in my [SO issue](https://stackoverflow.com/questions/51115843/how-to-efficiently-render-different-views-in-flatlist).
> > > > [The link to working demo](https://drive.google.com/file/d/1cYlLad6z6kLxz36m7i0-rXdaNzBEL6tY/view)
> > > 
> > > 
> > > please share with me this code
> > 
> > 
> > did you get the code?
> 
> no bro

Do you have developed such feature in any app bro because i need it on urjent basis. Week and month view calendars . Any help ?. Thanks.

**Comment by okay00** [comment]
@Vikash-algo  i am develop month and week view calendar using moment package , please try..
