### ISSUE TITLE
Feature request: mark contiguous periods with just range bounds

### ISSUE THREAD

**Issue by boguscoder** [wix/react-native-calendars#509]
## Description

It looks like to mark contiguous period user needs to pass every single date in range into markedDates

## Expected Behavior

It would be much more convenient if its enough to pass only start/end dates, right now it looks weird

## Observed Behavior

![screen shot 2018-06-03 at 1 17 08 pm](https://user-images.githubusercontent.com/16169159/40890840-3f316318-6731-11e8-9589-20373592b7de.png)

**Comment by tututututututu** [comment]
+1

**Comment by rueda10** [comment]
+1
