### ISSUE TITLE
Disable days before today

### ISSUE THREAD

**Issue by lucasgdev** [wix/react-native-calendars#51]
There is a simple away to disable days before the current day?
Ex.: Disable all days before today

Or there is a milestone to implement that?  Thanks.

**Comment by sibelius** [comment]
use maxDate https://github.com/wix/react-native-calendars/blob/master/src/calendar/index.js#L34

**Comment by tautvilas** [comment]
I think minDate would be more appropriate ;)

**Comment by lucasgdev** [comment]
Thanks guys. Makes totally sense. :)
