### ISSUE TITLE
Can i add the event to my local calendar?

### ISSUE THREAD

**Issue by ycman0307** [wix/react-native-calendars#510]
I would like to add event to my local calendar which is sync with google account. Can i do that?

**Comment by apppro123** [comment]
How can i synchronize this calendar with the native calendar on the device (ios/google...)?

Is the best possibility to do it with react-native-calendar-events plugin or are there other opportunities?

Thanks for every response!

**Comment by trancanh2202** [comment]
Nobody can solve it ? I meet the same problem.

**Comment by apppro123** [comment]
I made it with react-native-calendar-events. Just wrote a function to change the dates to the right format for react-native-calendars.

**Comment by trancanh2202** [comment]
Hi apppro123, Can you share me the code or file. Please...

**Comment by apppro123** [comment]
if you can understand it ;)

let finalEvents = {};
    let finalDayEvents = [];
    for (i = 0; i < events.length; i++) {
        let e = events[i];
        let startDate1 = e.Start;
        let endDate = e.End;
        let title = e.Title;
        let allDay = e.AllDay;
        let color = e.Color;

        let DurationInDays = Moment(endDate).diff(Moment(startDate1), "days");
        if(allDay == true){
            let startDateFormat1 = Moment(startDate1).format("YYYY-MM-DD");
            if(finalEvents[startDateFormat1]){
                let number = finalEvents[startDateFormat1].Number;
                let multiEvent = finalEvents[startDateFormat1].Event;
                multiEvent.push({key: (multiEvent[(multiEvent.length -1).toString()].key + 1).toString(), EventText: title, EventColor: color});
                finalEvents[startDateFormat1] = {Event: multiEvent, Number: (Number(number) + 1).toString()};
            }else{
                finalEvents[startDateFormat1] = {Event: [{key: "0", EventText: title, EventColor: color}], 
                    Number: "1"};
            }
            
        }else{
            for(j = 0; j <= DurationInDays; j++){
                let startDateFormat = Moment(startDate1).add(j, "days").format("YYYY-MM-DD");
                if(finalEvents[startDateFormat]){
                    let number = finalEvents[startDateFormat].Number;
                    let multiEvent = finalEvents[startDateFormat].Event;
                    multiEvent.push({key: (multiEvent[(multiEvent.length -1).toString()].key + 1).toString(), EventText: title}); 
                } else {
                    finalEvents[startDateFormat] = {Event: [{key: "0", EventText: title}], 
                        Number: "1"};
                
            }
        }
    }
}
