### ISSUE TITLE
[Agenda] Feature: scroll up and auto fetch data for those days

### ISSUE THREAD

**Issue by fzyzcjy** [wix/react-native-calendars#516]
Currently, when the user scrolls down, the component will automatically call the callbacks to fetch the data of 2018.2, 2018.3 and so on (Suppose today is 2018.1.1). However, when scrolling up, the system will not load any events, such as those in 2017.12.31. Therefore, I would appreciate it if the same behavior could be added when scrolling up.
Thank you very much! The library is wonderful!

**Comment by amieczko** [comment]
*bump* This would be a very useful feature. A response from the devs as to whether this will be implemented would be fantastic

**Comment by freshedgarT** [comment]
I would also find this extremely useful.

**Comment by fzyzcjy** [comment]
Oh it has been 2 years! 👀

**Comment by fzyzcjy** [comment]
Not stale (?)

**Comment by raaannzzz** [comment]
It's still not working @fzyzcjy
