### ISSUE TITLE
Agenda expand month range.

### ISSUE THREAD

**Issue by Symous** [wix/react-native-calendars#52]
Hi.awesome lib!
Is there any way to enable us to define the range of the agenda when it expand ? just like only showing one year. Thanks. :-)

**Comment by tautvilas** [comment]
Hi there are `pastScrollRange` and `futureScrollRange` paramas available to `CalendarList`. Would behaviour of these parameters work for you if they were also available for Agenda?

**Comment by Symous** [comment]
@tautvilas , these 2 props pastScrollRange & futureScrollRange are not worked with Agenda.

**Comment by tautvilas** [comment]
Hey, you're right I need to add these options to agenda

**Comment by Symous** [comment]
@tautvilas PR #54
