### ISSUE TITLE
[Bug] Agenda sometimes open calendar and cannot close

### ISSUE THREAD

**Issue by ckdanny** [wix/react-native-calendars#520]
## Expected Behavior

knob is hide and will never show up
```
<Agenda
    ref={(agenda) => {
            this.agenda = agenda;
        }}
    items={this.state.items}
    loadItemsForMonth={this.loadItems}
    renderItem={this.renderItem}
    renderEmptyDate={this.renderEmptyDate}
    rowHasChanged={this.rowHasChanged}
    minDate={this.state.min_day}
    pastScrollRange={1}
    futureScrollRange={1}
    hideKnob={true}
    renderKnob={() => {return (<View />);}}
/>

```

## Observed Behavior

Sometimes, when rendering agenda (e.g. fast switching render), the calendar will display and overlay the agenda. I cannot close it manually.  

![image](https://user-images.githubusercontent.com/11786201/41211539-9084b122-6d6a-11e8-9112-68a574911728.png)

## Environment

bmsMobileCloudEditing@0.0.1
└── react-native-calendars@1.19.3 

bmsMobileCloudEditing@0.0.1
└── react-native@0.55.3

**Comment by ckdanny** [comment]
I found that when pressing the system time (e.g. 11:26 AM), it will trigger the panel expand

**Comment by ckdanny** [comment]
How do I disable the expand CalendarList?

**Comment by ckdanny** [comment]
Solution is found. The reason is the agend/index.js 
```
<Animated.ScrollView
        
          ref={c => this.scrollPad = c}
          overScrollMode='never'
          showsHorizontalScrollIndicator={false}
          showsVerticalScrollIndicator={false}
          style={scrollPadStyle}
          scrollEventThrottle={1}
          onTouchStart={this.onTouchStart}
          onTouchEnd={this.onTouchEnd}
          onScrollBeginDrag={this.onStartDrag}
          onScrollEndDrag={this.onSnapAfterDrag}
          onScroll={Animated.event(
            [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
            { useNativeDriver: true },
          )}
        >
```
Missing the property `scrollsToTop={false}`.

**Comment by tautvilas** [comment]
added fix to master

**Comment by ahtesham-shah** [comment]
> Solution is found. The reason is the agend/index.js
> 
> ```
> <Animated.ScrollView
>         
>           ref={c => this.scrollPad = c}
>           overScrollMode='never'
>           showsHorizontalScrollIndicator={false}
>           showsVerticalScrollIndicator={false}
>           style={scrollPadStyle}
>           scrollEventThrottle={1}
>           onTouchStart={this.onTouchStart}
>           onTouchEnd={this.onTouchEnd}
>           onScrollBeginDrag={this.onStartDrag}
>           onScrollEndDrag={this.onSnapAfterDrag}
>           onScroll={Animated.event(
>             [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
>             { useNativeDriver: true },
>           )}
>         >
> ```
> 
> Missing the property `scrollsToTop={false}`.

please explain in brief what to do I am not getting it
