### ISSUE TITLE
[FEAUTURE] - Is this component support swipe for agenda

### ISSUE THREAD

**Issue by franj0** [wix/react-native-calendars#524]
## Description

After day is selected, can we swipe for next/previous week instead of scrolling agenda to the bottom to get next/previous week?

## Expected Behavior

So instead arrow add functions to swipe week

https://raw.githubusercontent.com/BugiDev/react-native-calendar-strip/master/example/gifs/squential.gif 
http://o7bkcj7d7.bkt.clouddn.com/calendar-strip.MP4

## Observed Behavior

I didn't find in documentation support for this feature.

Sry for bad eng, thank you.

Kind regards

**Comment by trancanh2202** [comment]
+1

**Comment by anilkumar1505** [comment]
I need to swipe left and right  for agenad Agenda
