### ISSUE TITLE
Mark dates automatically 

### ISSUE THREAD

**Issue by Descartess** [wix/react-native-calendars#53]
I want to be able to select a start date and end date and then all the dates in between are marked automatically.
 I am thinking if we could be able to pass a prop to the calendar component to allow such behaviour or is the functionality currently implemented. 
Thanks and Keep up the good work.

**Comment by tautvilas** [comment]
hi, currently calendar does not provide such functionality. you have to calculate which dates have to be marked yourself and pass day marking info to calendar

**Comment by Descartess** [comment]
Can i try and work on a pull request that tries to address this

**Comment by tautvilas** [comment]
Hi, what would be API for addressing this? I am not sure if we should include such functionality to this lib. This lib is concerned about graphical representation and its up to developer who uses the lib to decide how his marking logic works.
