### ISSUE TITLE
Error: bundling failed

### ISSUE THREAD

**Issue by aclaussen1** [wix/react-native-calendars#535]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I am trying to include this library in my project. So far I have included it in my package.json file and run npm install. All seems good. But simply adding an import statement for the library:

`import { Calendar, CalendarList, Agenda } from 'react-native-calendars';`

causes the red failure screen on device and I see the following error in my console:

error: bundling failed: Error: While trying to resolve module `react-native-calendars` from file `/Users/Alex/Documents/workspace/mobile/src/screens/CalendarView.js`, the package `/Users/Alex/Documents/workspace/mobile/node_modules/react-native-calendars/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/Alex/Documents/workspace/mobile/node_modules/react-native-calendars/src/index.js`. Indeed, none of these files exist:

  * `/Users/Alex/Documents/workspace/mobile/node_modules/react-native-calendars/src/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/Alex/Documents/workspace/mobile/node_modules/react-native-calendars/src/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/Alex/Documents/workspace/mobile/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:103:15)
    at DependencyGraph.resolveDependency (/Users/Alex/Documents/workspace/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/Alex/Documents/workspace/mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/Alex/Documents/workspace/mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/Alex/Documents/workspace/mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/Alex/Documents/workspace/mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/Alex/Documents/workspace/mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
    at <anonymous>

## Expected Behavior

Was expecting this to run error free as the only code I have included thus far is the import statement.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
StandardNotes@2.2.11 /Users/Alex/Documents/workspace/mobile
└── react-native-calendars@1.19.3 

* `npm ls react-native`:
StandardNotes@2.2.11 /Users/Alex/Documents/workspace/mobile
└── react-native@0.55.4 

Also specify:

1. Phone/emulator/simulator & version:

ios, running on device,  xcode

**Comment by aclaussen1** [comment]
got help with this

https://stackoverflow.com/questions/51068105/react-native-bundling-failed

**Comment by reactnative94** [comment]
@aclaussen1 were you able to solve it. I did followed the steps mentioned in the link you provided but its still not working for me.
Removed node modules . Installed it again with --update-binary but still getting the same error.
