### ISSUE TITLE
paging with vertical scrolled CalendarList

### ISSUE THREAD

**Issue by Bickson** [wix/react-native-calendars#537]
[QUESTION]
is there a way to page per month with vertical scroll in CalenderList?

## Description
paging with vertical scrolled CalendarList

## Expected Behavior

to page per month

## Observed Behavior

month not align center when scrolling with paging

![untitled](https://user-images.githubusercontent.com/946680/42034507-8df9dfb2-7ae0-11e8-8c52-d26792ee4623.png)

**Comment by reubn** [comment]
This is still a problem - snapping points do not line up with months - making the CalendarList unuseable

**Comment by YukiSato-zz** [comment]
I'm in a straight line to the same problem.
In the horizontal direction, the calendar is precisely centered.
However, in the vertical direction, it does not scroll to the expected position.
I expect the calendar to be centered, like the default calendar in iOS.
I am very keen to have this problem solved for me.

Please comment if you are aware of this issue.
I would like to discuss it.

![new](https://user-images.githubusercontent.com/3048396/82722336-cf32df80-9d00-11ea-95b4-bef8f5605451.gif)

**Comment by Dovydastc** [comment]
Same problem, any workarounds?

**Comment by Dovydastc** [comment]
Fixed with paging enabled and fixed height in style prop. Height must be the same as single calendar month page height. In my case it was 360px

` <CalendarList
        style={{
          height: 360
        }}
  scrollEnabled={true}
pagingEnabled={true}
        horizontal={false}
 />`

**Comment by Maciejw52** [comment]
To build on the comment by @Dovydastc , for a horizontal scrolling calendar for any width device, first, get the window width via:

`import { Dimensions } from 'react-native';`
`export const windowWidth = Dimensions.get('window').width;`

Then set both the width (in style) and the calendarWidth to variable windowWidth:

`<CalendarList style={{ width: windowWidth }} calendarWidth={ windowWidth } scrollEnabled={true} pagingEnabled={true} horizontal={false} />`

Any change to either should be replicated for both. Similar solution for vertical scrolling calendar.

**Comment by sanjayTDF** [comment]
@Dovydastc, @Maciejw52, your both solution not work
