### ISSUE TITLE
Full List is not showing in Agenda View if the current date has no items

### ISSUE THREAD

**Issue by vineethgeorge03** [wix/react-native-calendars#538]
## Description

In agenda , suppose if the week is given below
SUN  MON TUE WED THU FRI SAT
1         2          3      4       5     6     7
 and my Agenda Items are suppose 
const agendaItems = {
    '2018-06-01':{item:'item1'},
    '2018-06-02':{item:'item2},
    '2018-06-03': {item:'item3},
    '2018-06-05': {item:'item4'},
    '2018-06-06': {item:'item5'},
    '2018-06-07': {item:'item6'},
}

and suppose my current Date is 2018-06-04
when I open my agenda View it shows no data, the scrollView is empty ,
Only if i click on any date in the week for which i have data , then the scroll View shows the full 
list 
## Expected Behavior

when I open my agenda View it should show all the items for the current week ,

## Observed Behavior

when I open my agenda View it shows no data, the scrollView is empty ,
Only if i click on any date in the week for which i have data , then  the scroll View shows the full 
list 

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
no errors
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:1.19.3
* `npm ls react-native`: 0.55.4

Also specify:

1. Phone/emulator/simulator & version:  API 23 

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by Plaoo** [comment]
Same problem

**Comment by dl-husky73** [comment]
same problem here.  Any updates?

**Comment by chenei** [comment]
Do you still have a problem?

**Comment by Chibuzor44** [comment]
@vineethgeorge03 did you ever get a solution to this issue? I am having the same problem.
