### ISSUE TITLE
<Agenda /> call double loadItemsForMonth

### ISSUE THREAD

**Issue by silasrm** [wix/react-native-calendars#541]
## Description
When load <Agenda />, my loadItemsForMonth call my api to get event list from month (today is 2018-07-02, event lists is of July, 2018). But, after load, <Agenda /> call again loadItemsForMonth but passing a date from before month, in this case 2018-06-02.

## Expected Behavior

<Agenda /> call one time loadItemsForMonth when load. After this, only call loadItemsForMonth when user interact with its components.

## Environment

I'm using Expo (v. 55.0.4) with react-native-calendars (^1.19.3).

**Comment by jjercx** [comment]
+1

**Comment by silasrm** [comment]
This cause change of the CalendarList component and the date is change to 1 month before: https://github.com/wix/react-native-calendars/blob/master/src/agenda/index.js#L394-L396

**Comment by silasrm** [comment]
Hi guys,

I'm solving in my app controlling when loadItemsForMonth after first time. After first time, my api request is blocked. To load more events, I'm using onDayPress to load events data, if hasn't exists in memory/redux store.
