### ISSUE TITLE
onDayPress not highlighting day

### ISSUE THREAD

**Issue by GiacomoK** [wix/react-native-calendars#542]
## Description

onDayPress not highlighting day. If I click on a day, the day is not highlighted

## Expected Behavior

Selected day should be highlighted (blue background for example)

## Observed Behavior

onDayPress is called but day is not highlighted

## Environment

react-native-calendars@1.19.3  
react-native@0.55.4

## Reproducible Demo

This is the code of the calendar:
```
<Calendar
      current = {(this.state.booking_date) || this.state.min_date}
      minDate={this.state.min_date}
      maxDate={this.state.max_date}
      onDayPress={(day) => this.onChangeDate(day)}
      monthFormat={'MMMM yyyy'}
      onMonthChange={(month) => {log('month changed', month)}}
      hideExtraDays={true}
      firstDay={1}
 />
```
I get the same behaviour even if I take off onDayPress function or If I copy example code.

**Comment by pelmered** [comment]
Same for me...
Changing the relevant  theme properties does not help neither.

**Comment by Return-1** [comment]
same

**Comment by lucidlemon** [comment]
can confirm this

**Comment by mihai-ro** [comment]
Any updates on this topic? I am facing the same problem. Found out that removing markedDates somehow allows the selected day to be highlighted properly. Could not figure out what is the actual issue.

**Comment by herarya** [comment]
+1 , onDayPress not work backgroundColor selected

**Comment by brayanL** [comment]
@herarya thanks I don't why this is not on documentation.

**Comment by chenei** [comment]
Do you still have a problem?
