### ISSUE TITLE
Display days considering event time

### ISSUE THREAD

**Issue by rafaelcamaram** [wix/react-native-calendars#545]
## Description

I would like to know if it's possible to display the "Day" in the same way that it's displayed on the native iOS calendar component (Image attached); with the "times" of each day.

<img width="316" alt="screen shot 2018-07-04 at 11 03 18" src="https://user-images.githubusercontent.com/9087886/42281530-2befb4c4-7f7a-11e8-8bd0-7c65221c8993.png">

**Comment by yashlinmaistry** [comment]
Hi, 

Have you been able to get this to work?

**Comment by mayurssoni2456** [comment]
I have a similar requirement. I am planning to build custom renderDay for this. 
If someone has achieved building this please share.

**Comment by saiemsaeed** [comment]
@rafaelcamaram i have implemented this feature. Please checkout PR #1021

**Comment by chenei** [comment]
Do you still have a problem?
