### ISSUE TITLE
Calendar onDayPress: which type is the day variable

### ISSUE THREAD

**Issue by giacomok** [wix/react-native-calendars#547]
Hi,  
I need to simulate the Calendar onDayPress event, but I do not know which type is the "day" variable.

I tried to check the code but I did not figured out.

**Comment by GiacomoK** [comment]
I founded, is this function:

    function xdateToData(xdate) {
        const dateString = xdate.toString('yyyy-MM-dd');
            return {
                year: xdate.getFullYear(),
                month: xdate.getMonth() + 1,
                day: xdate.getDate(),
                timestamp: XDate(dateString, true).getTime(),
                dateString: dateString
            };
    }
