### ISSUE TITLE
Any plan for providing gesture?

### ISSUE THREAD

**Issue by Symous** [wix/react-native-calendars#55]
Is there any plan for providing gesture support ? such as swipe down to expand the agenda ?

**Comment by tautvilas** [comment]
it's something we were thinking about a lot (swipe down was an original idea). However smooth swipe probably can be implemented only using native solutions. A good library for that task would be https://github.com/wix/react-native-interactable. However I want that this lib by default would be not requiring native dependencies. So Maybe dragging can be optional feature and you would not have to link native libs if you want to use tappable knob. Also it would be interesting to se JS-only swipeable solution and how performant it is.

**Comment by tautvilas** [comment]
I see know that you meant gesture and what I meant is dragging knob to expand agenda. Maybe implementing guesture would be easy? What do you suggest?

**Comment by Symous** [comment]
@tautvilas it's possible to implement guesture without linking native libs. just like a Drawer(Side Bar).I will try to achieve this and pull a request later since I'm not familiar with gesture of React Native now. :-)

**Comment by Louis345** [comment]
This sounds really awesome.

**Comment by tautvilas** [comment]
Solved by #85
