### ISSUE TITLE
Unable to have refresh indicator appear upon 'pulling' Agenda down.

### ISSUE THREAD

**Issue by eustacezheng** [wix/react-native-calendars#550]
## Description

Hi there, I am currently using the default <Agenda /> control as follows:

```
`<Agenda
                        onRefresh = {() => {
                            console.log('Refreshing...')
                            this.setState({refeshing : true})
                        }}

                        refreshing = {this.state.refreshing}
                        refreshControl = {null}

                        pastScrollRange={1}
                        futureScrollRange = {3}

                        // the list of items that have to be displayed in agenda. If you want to render item as empty date
                        // the value of date key kas to be an empty array []. If there exists no value for date key it is
                        // considered that the date in question is not yet loaded
                        items={this.state.items}

                        // callback that gets called when items for a certain month should be loaded (month became visible)
                        loadItemsForMonth={this.loadItems.bind(this)}

                        // specify how each item should be rendered in agenda
                        renderItem={this.renderItem.bind(this)}

                        // specify how empty date content with no items should be rendered
                        renderEmptyDate={this.renderEmptyDate.bind(this)}

                        // specify your item comparison function for increased performance
                        rowHasChanged={this.rowHasChanged.bind(this)}

                        // callback that gets called on day press
                        onDayPress={(day) => { console.log('day pressed') }}

                        // callback that gets called when day changes while scrolling agenda list
                        onDayChange={(day) => { console.log('day changed') }}
                    />
            </View>`
```

I may not be utilising it properly, however, I am unable to get the default refreshControl to appear when I pull the Agenda control downward. Could someone assist me in seeing how do I get refreshControl to work? There are no console messages appearing. 

Ultimately, I am hoping to have it appear, and only after my data has been pulled from an API, for the state of refreshing to be 'false' to remove it. 

## Expected Behavior

By 'pulling' the Agenda portion, it should have a RefreshControl appearing to fetch data from an API.

## Observed Behavior

Nothing happens. A simple pull on the list yields no reaction whatsoever.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: Version 1.19.4

Also specify:

1. Phone/emulator/simulator & version:

iPhone 8 plus simulator.

**Comment by tautvilas** [comment]
@gaboelnuevo could you help with this one? thx

**Comment by eustacezheng** [comment]
Hello all,

My sincere apologies. It is apparently working perfectly after I ran a 'Yarn Upgrade' on the package. Interestingly, the version number remains exactly the same @ 1.19.4, and I did not additional stuff but it works now. 

Thank you for looking into this! 👍
