### ISSUE TITLE
Collapse Agenda with Android back button/ Show Collapase knob

### ISSUE THREAD

**Issue by veedeo** [wix/react-native-calendars#555]
1. When Agenda is expanded the drag knob is hidden, is it possible to show it, to be able to collapse calendars without selecting.
2. Is it possible to collapse Agenda calendars programatically to use with Android back button.
Because now its not intuitive, and pressing back button closes the Screen

**Comment by trungtransg** [comment]
it should be to have this feature. In addition, it should have a previous/next (week, month) on top for easily selection.

**Comment by trungtransg** [comment]
Hi there, I found an workaround solution to collapse the agenda when it is expanded. You can implement as below:
- add a close icon to calendars list
- add a ref on Agenda JSX
- call this method when press on close icon this.agenda._chooseDayFromCalendar(selectedDate)

Hope it help for all.

**Comment by jeffreyho92** [comment]
> Hi there, I found an workaround solution to collapse the agenda when it is expanded. You can implement as below:
> 
> * add a close icon to calendars list
> * add a ref on Agenda JSX
> * call this method when press on close icon this.agenda._chooseDayFromCalendar(selectedDate)
> 
> Hope it help for all.

this.agenda.chooseDay(this.agenda.state.selectedDay);
This is work for me

**Comment by musadiq-jinbade** [comment]
how can we close calendar if it is open in react native calendar(Agenda)

**Comment by jeffreyho92** [comment]
> how can we close calendar if it is open in react native calendar(Agenda)

```
<Agenda
  onCalendarToggled={(calendarOpened) => {this.setState({calendarOpened})}}
/>
```
```
if(this.state.calendarOpened){
  this._Agenda.chooseDay(this._Agenda.state.selectedDay);
}else{
  this.props.navigation.goBack();
}
```

**Comment by Inbal-Tish** [comment]
@veedeo Please see comment on PR  #655
