### ISSUE TITLE
[BUG] R-N Windows 10 - Agenda use only two days.

### ISSUE THREAD

**Issue by paulbx81** [wix/react-native-calendars#556]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I just update react-native-calendars for my Windows 10 app and now my agenda can use only two days : 

![agenda](https://user-images.githubusercontent.com/40029591/42506034-f35d5f46-8440-11e8-8cd2-3bafdd81808d.PNG)

![agenda2](https://user-images.githubusercontent.com/40029591/42506038-f5ed11a2-8440-11e8-845e-40db3f3ecd2c.PNG)

## Expected Behavior

Agenda should use all the days of the week on windows 10 like android and iOS.

## Observed Behavior

no error in console or yellow box.

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars : 1.19.4
react-native: 0.55.4

Also specify:

This app is for Windows 10 tablet

## Reproducible Demo

i just use simple "< Agenda / >" component.

**Comment by paulbx81** [comment]
@tautvilas

**Comment by tautvilas** [comment]
hey, I'm not sure we support react-native for windows. Currently I don't have a way to reproduce this
