### ISSUE TITLE
Display dots in custom markingType

### ISSUE THREAD

**Issue by slecorvaisier** [wix/react-native-calendars#569]
## Description

in order to add a border to some dates, I switched `markingType` to `custom`. However, I still need the dots to be displayed when the day has `marked: true`. 

I tried to bring them back by modifying the day `customStyle` or the calendar theme via `stylesheet.day.single`, but nothing seems to do the job.

Is there any way to display the dots while working with a custom style ?

<img width="108" alt="screen shot 2018-07-23 at 15 58 03" src="https://user-images.githubusercontent.com/16785211/43081505-516233f4-8e92-11e8-8150-b7d88e23ae8e.png">

```jsx
'2018-07-16': {
  customStyles: {
    container: {
      borderWidth: 2,
      borderColor: 'black',
      backgroundColor: 'green',
      justifyContent: 'center',
    },
    text: {
      marginTop: 0,
    },
  },
  selected: true,
  marked: true,
 },
 '2018-07-17': { selected: true, selectedColor: 'green', marked: true },
```

**Comment by vanessaleo** [comment]
Hi, have you got any news about it?

**Comment by ODINA101** [comment]
same :(

**Comment by slecorvaisier** [comment]
Hi all, it's been a while but here is what I found:
Unfortunatelly the dots cannot be displayed in the `custom` mode. There is simply no code to handle it in its file:
https://github.com/wix/react-native-calendars/blob/master/src/calendar/day/custom/index.js

For anyone willing to do his own implementation, a good start can be found in the `basic` mode:
https://github.com/wix/react-native-calendars/blob/55df6f1bde62cb25327648c25d6cd5d0e228684c/src/calendar/day/basic/index.js#L55

**Comment by quanru** [comment]
+1

**Comment by Maddumage** [comment]
Same issue here...

**Comment by geetesh-gupta** [comment]
Same issue here... Please add this ability asap.

**Comment by monspo1** [comment]
Hi guys, 

I am currently working on displaying dots in the custom mode (unoptimized yet, but shows dots at least). I plan to push to my forked repo within weeks.

![Screen Shot 2019-12-28 at 12 17 38 AM](https://user-images.githubusercontent.com/10152090/71539248-83be0600-2907-11ea-9dc3-96a44037ea15.png)

Also, I'm also adding a feature of selectively displaying a limit number when there are lots of dots (but still can choose to display all dots under the selected day). In this image below, for example, when there are 8 dots, a developer can choose to display all dots or show the text 3+ (3 is chosen number) like, `multiDotLimit={{ limit: 3, type: 'number'}}`,

This is currently done in the basic mode. The original idea of this feature is from the [fork](https://github.com/wix/react-native-calendars/issues/523) by @peteroid (Thanks for your fork which is great!!)
![Screen Shot 2019-12-28 at 12 17 31 AM](https://user-images.githubusercontent.com/10152090/71539250-86b8f680-2907-11ea-916b-bd0f59e146bf.png)

**Comment by marcelochb** [comment]
> Hi guys,
> 
> I recently started to understand the entire codes & currently work on displaying dots in the custom mode for the purpose of my own project (I'm still learning so the code is not optimized yet, but it works to show dots).
> ![Screen Shot 2019-12-28 at 12 17 38 AM](https://user-images.githubusercontent.com/10152090/71539248-83be0600-2907-11ea-9dc3-96a44037ea15.png)
> 
> This is one of my objects in the markedDates while others files also are edited.
> ![Screen Shot 2019-12-28 at 12 47 23 AM](https://user-images.githubusercontent.com/10152090/71539547-a520f100-290b-11ea-8296-520e36c79d2d.png)
> 
> I plan to push to my forked repo within a couple of weeks.
> 
> Also, I'm also planning to add a feature of selectively displaying a limit number when there are lots of dots (but still can choose to display all dots under the selected day). In this image below, for example, when there are 8 dots, a developer can choose to display all dots or show the text 3+. 3 is the chosen limit number with `multiDotLimit={{ limit: 3, type: 'number'}}`
> 
> This is currently done in the basic mode. The original idea of this feature is from the [fork](https://github.com/wix/react-native-calendars/issues/523) by @peteroid (Thanks for your fork which is great!!)
> ![Screen Shot 2019-12-28 at 12 17 31 AM](https://user-images.githubusercontent.com/10152090/71539250-86b8f680-2907-11ea-916b-bd0f59e146bf.png)

Hi, do you know when it will be working? (dots in custom markingType)

thanks.

**Comment by gcrev93** [comment]
Has there been any updates on the dots?

**Comment by imhashir** [comment]
Any updates on this issue? Need this for my use case.

**Comment by apsampaio** [comment]
+1

**Comment by theneekz** [comment]
Would love to use custom with multi-dots!

**Comment by trung2nghin** [comment]
Any updates on this issue?

**Comment by Enhmunh-E** [comment]
You can use dayComponent props to customize dots and items. Something Like This
`dayComponent={({date, state, marking}) => {
        return (
          <>
            <View
              style={[
                marking?.customStyles?.container,
                styles.defaultCalendarItem,
                // marking?.customContainerStyle,
              ]}>
              <Text
                style={[marking?.customStyles?.text, marking?.customTextStyle]}>
                {date?.day}
              </Text>
            </View>
            <Drop />
          </>
        );
      }}`
