### ISSUE TITLE
Agenda onDayPress Not Responsive Sometimes on Android

### ISSUE THREAD

**Issue by kevinzhangftw** [wix/react-native-calendars#571]
## Description

On Android in agenda, if you select a different day where onDayPress is called, it is not responsive. or should i say intermittently responsive. It is super slow and sometimes doesnt even work. 

## Expected Behavior

onDayPress for android should behave like how it is like iOS 

## Observed Behavior

I did a console log and it actually doesn even register!

there are no error messages. 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: "react-native-calendars": "^1.19.4",
* `npm ls react-native`: "~0.55.2",

Also specify:

1. Phone/emulator/simulator & version: yarn start on expo android app

## Reproducible Demo

Just do a blank agenda app and select a different day 

```
<Agenda
        items={jobitems}
        selected={this.state.selectedDay}
        renderItem={item => this.renderJobItem(item, onJobItemPressed)}
        renderEmptyDate={this.renderEmpty}
        renderEmptyData = {this.renderEmpty}
        rowHasChanged={this.rowHasChanged}
        //HERE: on android this does not get called
        onDayPress={(day)=>{
          console.log('day pressed')
        }}
        hideKnob={false}
      />
```

**Comment by qasimalbaqali** [comment]
Experiencing this as well. I have to press multiple times for it to work, and sometimes I need to restart the whole app for it to work. It would work for a little bit and then stop responding to clicks. 

```
"react-native": "0.55.1",
"react-native-calendars": "^1.19.4"
```

**Comment by kevinzhangftw** [comment]
Thanks! This was very helpful, really hope documentation would have explain this. To future ppl here, the fix for android is to implement onDayLongPress as well

```
     <Agenda
        items={jobitems}
        selected={this.state.selectedDay}
        renderItem={item => this.renderJobItem(item, onJobItemPressed)}
        renderEmptyDate={this.renderEmpty}
        renderEmptyData = {this.renderEmpty}
        rowHasChanged={this.rowHasChanged}
        onDayPress={ day =>{
          this.handleOnDayPressed(day)
        }}
        onDayLongPress={ day =>{
          this.handleOnDayPressed(day)
        }}
        hideKnob={true}
      />
```

**Comment by spiraltrip** [comment]
This is really helpful, I wasted so many days trying to figure this out. Thanks guys for your contributions.
