### ISSUE TITLE
Vertical CalendarList doesn't scroll when inside ScrollView

### ISSUE THREAD

**Issue by nitish1099** [wix/react-native-calendars#574]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I'm not able to scroll within the CalendarList when inside another ScrollView.

## Expected Behavior

Calendar to scroll vertically inside the scrollview

## Observed Behavior

Calendar freezes and doesn't scroll

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

`<View style={{flex: 1}}>
            <Card title="SELECT DATE" subText="You can select more than one date. Maximum 5 dates." conentStyle={{ height: 400, padding:0 }}>
              <View style={styles.selectedDateContainer}>
                <Text style={styles.selectedDay}>{moment(this.props.selectedDay).format('DD MMM, YYYY')}</Text>
                <View style={styles.shadow} /> 
              </View>
              <CalendarList
        style={{height: 500}}
         onVisibleMonthsChange={(months) => {console.log('now these months are visible', months);}}
         pastScrollRange={0}
         futureScrollRange={2}
         calendarHeight={500}
         minDate={this.props.minDate || mom}
         markedDates={this.props.markedDates}
         onDayPress={(day) => this.onDateChange(day)}
         scrollEnabled={true}
      />
            </Card>
            <Card title="SELECT TIME" subText="Please choose the time for the delivery." conentStyle={{ height: 400, padding:0 }}>
              <TouchableWithoutFeedback onPress={this.onEditTimePress.bind(this)}>
                <View style={styles.selectedTimeContainer}>
                  <Text style={styles.selectedTime}>{this.props.selectedSlot}</Text>
                </View>
              </TouchableWithoutFeedback>
            </Card>
          </View>`

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by HeberHerrera** [comment]
Any solution???

**Comment by biller-aivy** [comment]
@nitish1099 can you reopen pls?

**Comment by theyanniss23002** [comment]
this problem is relevant. i also face vertical calendar issue when using bottom sheet from gorhom/react-native-bottom-sheet

**Comment by Jigs6720** [comment]
@theyanniss23002 facing same issue. any solutions

**Comment by theyanniss23002** [comment]
@Jigs6720 Hi, i fixed it by updating react-native and react to the latest version. And I use a native modal window import {Modal} from 'react-native' with animationType="slide" and presentationStyle="formSheet" attributes
