### ISSUE TITLE
Calendar shows some extra days when hideExtraDays is true

### ISSUE THREAD

**Issue by SilencerWeb** [wix/react-native-calendars#575]
## Description
Calendar shows some extra days when `hideExtraDays` is `true`.
![image](https://user-images.githubusercontent.com/20713191/43199610-fb5dadb2-902b-11e8-8677-4aab3d25e8f9.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: ~0.55.2
* `npm ls react-native`: ^1.19.4

Also specify:

1. Phone/emulator/simulator & version: simulator v10.0 

## Reproducible Demo
It is in your example, I just removed `current`, `minDate`, `maxDate`:
```jsx
<Calendar
  // Handler which gets executed on day press. Default = undefined
  onDayPress={(day) => {console.log('selected day', day)}}
  // Handler which gets executed on day long press. Default = undefined
  onDayLongPress={(day) => {console.log('selected day', day)}}
  // Month format in calendar title. Formatting values: http://arshaw.com/xdate/#Formatting
  monthFormat={'yyyy MM'}
  // Handler which gets executed when visible month changes in calendar. Default = undefined
  onMonthChange={(month) => {console.log('month changed', month)}}
  // Hide month navigation arrows. Default = false
  hideArrows={true}
  // Replace default arrows with custom ones (direction can be 'left' or 'right')
  renderArrow={(direction) => (<Arrow />)}
  // Do not show days of other months in month page. Default = false
  hideExtraDays={true}
  // If hideArrows=false and hideExtraDays=false do not switch month when tapping on greyed out
  // day from another month that is visible in calendar page. Default = false
  disableMonthChange={true}
  // If firstDay=1 week starts from Monday. Note that dayNames and dayNamesShort should still start from Sunday.
  firstDay={1}
  // Hide day names. Default = false
  hideDayNames={true}
  // Show week numbers to the left. Default = false
  showWeekNumbers={true}
  // Handler which gets executed when press arrow icon left. It receive a callback can go back month
  onPressArrowLeft={substractMonth => substractMonth()}
  // Handler which gets executed when press arrow icon left. It receive a callback can go next month
  onPressArrowRight={addMonth => addMonth()}
/>
```

**Comment by lucidlemon** [comment]
what extra days are you talking about? extra days would be 30th of june in grey etc. - this are nore visible, as expected.

or are you talking about the grey numbers on the left side? these are calendar weeks

**Comment by lucidlemon** [comment]
set `showWeekNumbers={false}` and the grey numbers on the left side will be gone. weeks are numbered 1-52 for each year. many businesses work in calendar weeks instead of days since it makes more sense.

**Comment by alfredCabe** [comment]
How can you do to select which day of the week did NOT seem like Monday and Friday?
@lucidlemon
