### ISSUE TITLE
Add an option to change selectedDotColor when markingType is simple

### ISSUE THREAD

**Issue by SilencerWeb** [wix/react-native-calendars#576]
## Description
Add an option to change `selectedDotColor` when `markingType` is `simple` like when `markingType` is `multi-dot`. Now we can only change `dotColor`, but `selectedDotColor` is always white.

That's how you did it when `markingType` is `multi-dot` - https://github.com/wix/react-native-calendars/blob/master/src/calendar/day/multi-dot/index.js#L53

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.19.4
* `npm ls react-native`: ~0.55.2

**Comment by danielkhaleb** [comment]
same problem

Environment:
npm ls react-native-calendars: ^1.300.0
npm ls react-native: 0.62.2
