### ISSUE TITLE
Adding a single Icon to a date row in Agenda

### ISSUE THREAD

**Issue by Louis345** [wix/react-native-calendars#58]
Hello,

I really appreciate this plugin. It's  really amazing. I am just having trouble with adding a plus Icon using the Agenda component.  I would like to have a plus Icon rendered once per day. As of now, I am able to get the Icon to display, but the problem is that it displays a plus Icon for every appointment. I know it's in a loop and I  probably could get it to work with a bit of logic, but I was wondering if there might be a simpler way of achieving this. Hopefully, I am clear, but I have added . a picture on what I am trying to acheive.

https://blog-setmore.storage.googleapis.com/android_wheely.gif
![android_wheely](https://user-images.githubusercontent.com/5923270/27015145-79520fea-4ed5-11e7-90f6-b049321b52d1.gif)

**Comment by tautvilas** [comment]
hi, are you trying to add the icon inside `renderDay` or `renderItem`?

**Comment by Louis345** [comment]
Hello, I am trying to display "+ Add New" one time per day. I was trying to render it using the  renderItem function.

**Comment by tautvilas** [comment]
added `firstItemInDay` indicator to renderDay callback

**Comment by Louis345** [comment]
@tautvilas  Thank you so much. Can you give me a small example or code snippet on how I would implement this in my project. 

I really appreciate the help.

**Comment by tautvilas** [comment]
prop `renderItem` example for Agenda:

`renderItem={(item, firstItemInDay) => {firstItemInDay ? return (<ItemAndPlus /> :  return <Item />);}}`

**Comment by imamurasyoutarou** [comment]
Good afternoon
Japanese

I want you to show me this code.
Please
