### ISSUE TITLE
How do I know the current month when horizontal scroll on CalendarList 

### ISSUE THREAD

**Issue by Wbqqqq** [wix/react-native-calendars#580]
ATT，I can't find any callback 😢

**Comment by RafaelKr** [comment]
You can also add `calendarParams` and `calendarListParams`. So just add the `onVisibleMonthsChange` parameter.

**Comment by RafaelKr** [comment]
The docs are saying
```
<CalendarList
  // Enable horizontal scrolling, default = false
  horizontal={true}
  // Enable paging on horizontal, default = false
  pagingEnabled={true}
  // Set custom calendarWidth.
  calendarWidth={320}
  ...calendarListParams
  ...calendarParams
/>
```

the last two lines mean you can pass all parameters for CalendarList and Calendar. CalendarList has the following line
```
// Callback which gets executed when visible months change in scroll view. Default = undefined
  onVisibleMonthsChange={(months) => {console.log('now these months are visible', months);}}
``` 

not that hard, right?

But there seems to be a bug: https://github.com/wix/react-native-calendars/issues/526

**Comment by Wbqqqq** [comment]
thanks , oba. 😂

**Comment by Wbqqqq** [comment]
thanks，oba.  😂 @RafaelKr
