### ISSUE TITLE
Automation testing with Appium

### ISSUE THREAD

**Issue by harish-coditas** [wix/react-native-calendars#582]
How do I test the calendar with Appium? I tried passing the accessibilityId to the component but it does not recognise it.

**Comment by pavermakov** [comment]
@harish-coditas have you resolved your issue?

**Comment by wwjo** [comment]
> How do I test the calendar with Appium? I tried passing the accessibilityId to the component but it does not recognise it.

@harish-coditas Hi Harish, have you recognised it in the Appium?

**Comment by EsackNaz** [comment]
@harish-coditas Hi Harish, Have you resolved this issue?
