### ISSUE TITLE
Numbers of sides getting cropped to 1 digit

### ISSUE THREAD

**Issue by SanchitB23** [wix/react-native-calendars#585]
## Description

Side panel of agenda is getting cropped

## Expected Behavior

Agenda showing 2 digit numbers in 2 digit dates
## Observed Behavior

Side numbers getting cropped into 1 digit

``` cloned example from the repo
```
## Environment

Phone: android 8.0

## Reproducible Demo
![whatsapp image 2018-08-01 at 12 12 18](https://user-images.githubusercontent.com/24359070/43505580-ffa6a618-9584-11e8-9db0-aea6839c9d36.jpeg)

**Comment by visshaljagtap** [comment]
Facing same issue. @tautvilas @noamco can you please help us to solve this issue?

**Comment by yuri-swift** [comment]
Facing same issue.

We had a user that occurred on a terminal with OS version 6.0.1.
However, the simulator can not reproduce it.

Ask for help.
