### ISSUE TITLE
No accessibility id in android

### ISSUE THREAD

**Issue by harish-coditas** [wix/react-native-calendars#586]
I see in the last commit you guys have added test ids for ios but what about android. Are you guys going to add that also

**Comment by realsilversurfer** [comment]
Hello, I am experiencing same issue. I can get accessibility id(testid) on ios through appium inspector without issue but cant locate days in calendar with content desc, is there some progress with this problem?

**Comment by stephenj24** [comment]
Is the accessibility ids available on Android now?
