### ISSUE TITLE
[Agenda] Cannot Scroll back up to view events after selecting future date in Calendar List 

### ISSUE THREAD

**Issue by amieczko** [wix/react-native-calendars#588]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When I select a date on the Calendar List in the Agenda, I cannot scroll up to previous events. 

## Expected Behavior

For example today was the 6th of August and I selected the 16th of August in the Calendar List, I would not be able to scroll up in the Agenda to view the events on the 6th. 

## Observed Behavior

Currently I cannot scroll up to see these prior events. I have to go back through the calendar list and select (following the example above) the 6th of August to see all the events between the 6th and the 16th. 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

Phone: Samsung Galaxy S9+
Version: Latest  Master version.

**Comment by pie6k** [comment]
I've got the same issue

**Comment by mcabs3** [comment]
I also see this issue.

**Comment by gugakatsi** [comment]
@amieczko currently agenda doesn't support scrolling up , select date is the limit.

**Comment by amieczko** [comment]
@gugakatsi this is not true. If you scroll down 30 days or so then it locks you in. For example, if I select December 1st and scroll to January 30th, I am only able to scroll back up to January 1st.

**Comment by gugakatsi** [comment]
@amieczko yeap just tested out , same behavior here.

**Comment by wanderson-rocha-almeida** [comment]
Any predictions for adding the scroll back up after selecting a future date?

**Comment by verkhohliad** [comment]
Any updates?
