### ISSUE TITLE
How to set the CalendarToggled to false when I click back button?

### ISSUE THREAD

**Issue by phalonX** [wix/react-native-calendars#589]
This happens using Agenda when I toggled the Calendar and i want to go back to the main view without choosing the date, just by using the back button... Thanks

**Comment by yikkok-yong** [comment]
You can called the **chooseDay()** function in your BackHandler.

`<Agenda 
    ref={agenda => {this.agenda = agenda}}
    ...
/>`

And somewhere in your code, let's say the BackHandler's event listener
add this line
`
this.agenda.chooseDay(new Date(), boolean);
`

There is a props called onCalendarToggle, where you can get the calendar toggle status.
You may need additional condition to prevent your back button quit the screen.

**Comment by ZhixiangWangCR7** [comment]
@yikkok-yong  Thank you for your help, but I am not using Agenda, but a horizontal CalendarList, can not call the chooseDay () function, what should I do?

**Comment by andregufc** [comment]
When you scroll to some date in the next month and click in the back button, does it scroll back to the correct date?
In my case it doesn't =/
