### ISSUE TITLE
RenderItem's callback having an issue.

### ISSUE THREAD

**Issue by Louis345** [wix/react-native-calendars#59]
This is a reference to #58.

I am using the prop  renderItem={(item, firstItemInDay) => {return (<View />);}}

The callback works, but the problem is that it cuts on the first Item near the date.

My code is this:
renderItem(item,firstItemInDay) {
    if(firstItemInDay){
      return(
      <View></View>
       )
    }
    return (
      <TouchableOpacity style={[styles.item, {height: item.height}]}>
      <View style={styles.icon}>
      <Icon name="check-circle" size={0} style={styles.Icon} color="blue"/>
      <Text style={styles.time}>{item.start} - {item.end}</Text>
      </View>
      <View>
      <Text style={styles.name}>{item.full_name}</Text>
      </View>
      </TouchableOpacity>
    );

  }

Just returning an empty view hides an item that is next to the date.
<img width="320" alt="screen shot 2017-06-12 at 7 16 54 pm" src="https://user-images.githubusercontent.com/5923270/27059321-dccd0c9a-4fa3-11e7-9e1a-f1c9185178ee.png">

On my screenshot,  next to the date 8Thu there should be another appointment, but for some reason it does not display when using the callback. Am I doing something incorrect?

Thanks

**Comment by tautvilas** [comment]
Hi, I see that

```
if(firstItemInDay){
return(

)
}
```

return empty, so that might be the problem. It should return the view for first item

**Comment by Louis345** [comment]
I totally understand now how the callback works.
