### ISSUE TITLE
Agenda not showing all the days of month

### ISSUE THREAD

**Issue by harman-brar** [wix/react-native-calendars#591]
## Description

Agenda dropdown calendar only showing three weeks, effectively dumping the remaining days of each month.

## Expected Behavior

All days should be visible.

## Environment

* `npm ls react-native-calendars`: `-- react-native-calendars@1.19.4
* `npm ls react-native`: `-- react-native@0.55.4

1. Phone/emulator/simulator & version: Samsung Galaxy Note 8, V 8.0

## Reproducible Demo

From example/src/screens/agenda.js:

`<Agenda

      items={this.state.items}

      loadItemsForMonth={this.loadItems.bind(this)}

      selected={'2017-05-16'}

      renderItem={this.renderItem.bind(this)}

      renderEmptyDate={this.renderEmptyDate.bind(this)}

      rowHasChanged={this.rowHasChanged.bind(this)}

      // markingType={'period'}

      // markedDates={{

      //    '2017-05-08': {textColor: '#666'},

      //    '2017-05-09': {textColor: '#666'},

      //    '2017-05-14': {startingDay: true, endingDay: true, color: 'blue'},

      //    '2017-05-21': {startingDay: true, color: 'blue'},

      //    '2017-05-22': {endingDay: true, color: 'gray'},

      //    '2017-05-24': {startingDay: true, color: 'gray'},

      //    '2017-05-25': {color: 'gray'},

      //    '2017-05-26': {endingDay: true, color: 'gray'}}}

      // monthFormat={'yyyy'}

      // theme={{calendarBackground: 'red', agendaKnobColor: 'green'}}

      //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}

    />`

![20180811_195823](https://user-images.githubusercontent.com/21147463/43998058-9fa65ee6-9da1-11e8-8c30-babd97a9b1cb.jpg)

**Comment by mauriciord** [comment]
@harman-brar did you find a solution ?

**Comment by harman-brar** [comment]
```
const markedDays = [
     ...
    ];

    let newDaysObject = {};

    markedDays.forEach((day) => {
      newDaysObject = {
        ...newDaysObject,
        [day]: {
          marked: true
        }
      };
    });
```

**Comment by SmirnovM91** [comment]
+1

**Comment by harman-brar** [comment]
Nope, opted to use the standard calendar with heavy customization. Sorry!

**Comment by wasuaje** [comment]
I'm unable to see the month
![image](https://user-images.githubusercontent.com/4673741/85174214-4d749a00-b24b-11ea-9a4f-cf6dfaabd542.png)

And if I expand it

![image](https://user-images.githubusercontent.com/4673741/85174254-62e9c400-b24b-11ea-83b5-0d0d3c3de59c.png)


Any clue?

Code:

import React, { Component } from 'react';
import { Alert, StyleSheet, Text, View, TouchableOpacity, RCTAnimation } from 'react-native';
import { Agenda } from 'react-native-calendars';
import moment from 'moment/min/moment-with-locales.js';

const testIDs = {
    menu: {
        CONTAINER: 'menu',
        CALENDARS: 'calendars_btn',
        CALENDAR_LIST: 'calendar_list_btn',
        HORIZONTAL_LIST: 'horizontal_list_btn',
        AGENDA: 'agenda_btn',
        EXPANDABLE_CALENDAR: 'expandable_calendar_btn',
        WEEK_CALENDAR: 'week_calendar_btn'
    },
    calendars: {
        CONTAINER: 'calendars',
        FIRST: 'first_calendar',
        LAST: 'last_calendar'
    },
    calendarList: { CONTAINER: 'calendarList' },
    horizontalList: { CONTAINER: 'horizontalList' },
    agenda: {
        CONTAINER: 'agenda',
        ITEM: 'item'
    },
    expandableCalendar: { CONTAINER: 'expandableCalendar' },
    weekCalendar: { CONTAINER: 'weekCalendar' }
};

const getCurrentMonth = (date) => {
    return moment(date).format('YYYY-MM-DD');
};

const items = {
    '2020-06-17': [{ name: 'item 1 - any js object'}],
    '2020-06-18': [{ name: 'item 2 - any js object', height: 80}],
    '2020-06-19': [],
    '2020-06-20': [{ name: 'item 3 - any js object'}, { name: 'any js object'}]
}


export default class AgendaScreen extends Component {
    constructor(props) {
        super(props);

        this.state = {
            items: {}
        };
    }

    render() {
        return (
            <Agenda
                testID={testIDs.agenda.CONTAINER}
                items={this.state.items}
                loadItemsForMonth={this.loadItems.bind(this)}
                selected={getCurrentMonth()}
                renderItem={this.renderItem.bind(this)}
                renderEmptyDate={this.renderEmptyDate.bind(this)}
                rowHasChanged={this.rowHasChanged.bind(this)}
                disabledByDefault={false}
                // Max amount of months allowed to scroll to the past. Default = 50
                pastScrollRange={2}
                // Max amount of months allowed to scroll to the future. Default = 50
                futureScrollRange={10}
                markedDates={{
                    '2020-06-16': { selected: true, marked: true },
                    '2020-06-17': { marked: true },
                    '2020-06-19': { disabled: true }
                }}

            // markingType={'period'}
            // markedDates={{
            //    '2017-05-08': {textColor: '#43515c'},
            //    '2017-05-09': {textColor: '#43515c'},
            //    '2017-05-14': {startingDay: true, endingDay: true, color: 'blue'},
            //    '2017-05-21': {startingDay: true, color: 'blue'},
            //    '2017-05-22': {endingDay: true, color: 'gray'},
            //    '2017-05-24': {startingDay: true, color: 'gray'},
            //    '2017-05-25': {color: 'gray'},
            //    '2017-05-26': {endingDay: true, color: 'gray'}}}
            // monthFormat={'yyyy'}
            // theme={{calendarBackground: 'red', agendaKnobColor: 'green'}}
            //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
            // hideExtraDays={false}
            />
        );
    }

    loadItems(day) {
        setTimeout(() => {
            for (let i = -15; i < 85; i++) {
                const time = day.timestamp + i * 24 * 60 * 60 * 1000;
                const strTime = this.timeToString(time);
                if (!this.state.items[strTime]) {
                    this.state.items[strTime] = [];
                    const numItems = Math.floor(Math.random() * 3 + 1);
                    for (let j = 0; j < numItems; j++) {
                        this.state.items[strTime].push({
                            name: 'Item for ' + strTime + ' #' + j,
                            height: Math.max(50, Math.floor(Math.random() * 150))
                        });
                    }
                }
            }
            const newItems = {};
            Object.keys(this.state.items).forEach(key => { newItems[key] = this.state.items[key]; });
            this.setState({
                items: newItems
            });
        }, 1000);
    }

    renderItem(item) {
        return (
            <TouchableOpacity
                testID={testIDs.agenda.ITEM}
                style={[styles.item, { height: item.height }]}
                onPress={() => Alert.alert(item.name)}
            >
                <Text>{item.name}</Text>
            </TouchableOpacity>
        );
    }

    renderEmptyDate() {
        return (
            <View style={styles.emptyDate}>
                <Text>This is empty date!</Text>
            </View>
        );
    }

    rowHasChanged(r1, r2) {
        return r1.name !== r2.name;
    }

    timeToString(time) {
        const date = new Date(time);
        return date.toISOString().split('T')[0];
    }
}

const styles = StyleSheet.create({
    item: {
        backgroundColor: 'white',
        flex: 1,
        borderRadius: 5,
        padding: 10,
        marginRight: 10,
        marginTop: 17
    },
    emptyDate: {
        height: 15,
        flex: 1,
        paddingTop: 30
    }
});
