### ISSUE TITLE
TypeError: (nextProps.selected || []).reduce is not a function

### ISSUE THREAD

**Issue by rjoydip-zz** [wix/react-native-calendars#593]
## Description

I am setting the date like this

```js
selected={this.state.selectedDay}
    onDayPress={(day) => this.setState({
   selectedDay: dayjs(new Date(day.dateString)).format('YYYY-MM-DD')
})}
```

## Expected Behavior

Should work when the select date on the calendar and it would highlight the date.

## Observed Behavior

I am getting an error after selecting a date by `onDayPress`.

```
TypeError: (nextProps.selected || []).reduce is not a function
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  `react-native-calendars@1.19.3`
* `npm ls react-native`: `react-native@0.56.0`

Also, specify:

1. Phone/emulator/simulator & version: `iPhone 6 - iOS 11.0`

## Reproducible Demo

![simulator screen shot - iphone 6 - 2018-08-14 at 19 38 58](https://user-images.githubusercontent.com/15318294/44097313-165e529a-9ffb-11e8-8c55-bcca432faf58.png)

**Comment by rjoydip** [comment]
After I reinvestigate again. I saw this issue is showing when the state changed.

```js
onDayPress={(day) => this.setState({
    selectedDay: dayjs(new Date(day.dateString)).format('YYYY-MM-DD')
})}
```
