### ISSUE TITLE
Calendar opens slower in android

### ISSUE THREAD

**Issue by debugpai** [wix/react-native-calendars#598]
## Description
Calendar is opening really slowly in android. We're resorting to wrapping it in a view with an `onLayout` handler and showing a loader for the calendar which is giving a really bad experience for our users

## Expected Behavior
Calendar should open without any delay 

## Observed Behavior
Calendar takes 1-2 seconds to open. This only happens on android devices

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
└── react-native-calendars@1.19.4
* `npm ls react-native`:
└── react-native@0.55.4

Also specify:

1. Phone/emulator/simulator & version:
Simulator - Nexus 5X

## Reproducible Demo
```js
<CalendarList
    disableMonthChange={true}
    pastScrollRange={0}
    futureScrollRange={6}
    scrollEnabled={false}
    horizontal={true}
    pagingEnabled={true}
    showScrollIndicator={true}
    markedDates={...}
    onDayPress={x => x}
    onDayLongPress={x => x}
  />
```

To show the loader we can wrap it in 
```js
<View onLayout={e => this.setState({ layout: e.nativeEvent.layout })}>
    {this.state.layout ? <CalendarList {...params} /> : <ActivityIndicator />}
</View>
```

**Comment by debugpai** [comment]
I'm trying to debug the problem using `react-native-slowlog` and its the `renderWeek` function in `src/calendar/index.js` that is taking so long to render. It takes anywhere between 17ms to 25ms to render and it causing `Calendar.render` to load at >100ms

**Comment by RafaelKr** [comment]
I can confirm this leads to a significant increased performance on my Samsung Galaxy S7. Thanks!

**Comment by debugpai** [comment]
*bump* can someone please look at this? I updated a comment on the PR

**Comment by tautvilas** [comment]
updated PR with my comment

**Comment by kuangyliang** [comment]
Does not work, it is still very slow

**Comment by AkioUnity** [comment]
Yet. very slow. Please check these issues and let us know

**Comment by maxammann** [comment]
If I switch to the tab which renders the calendarlist the first time, then the frame rate drops significantly. Is there a workaround?

**Comment by carloslibardo** [comment]
I'm facing the same issue

**Comment by mleister97** [comment]
CalendarList is still very slow!

**Comment by KrisLau** [comment]
Slow for me as well. I'm using the ExpandableCalendarAgenda which was provided in the example app and it takes about 5 -7 seconds to render the screen.

**Comment by agNishith** [comment]
Any update on this? I'm also facing the same issue when I tried to render a calendar after hiding it. It takes a 1-2 second delay to re-render.

**Comment by qbunia** [comment]
Its really slow for me too.

**Comment by KrisLau** [comment]
@agNishith @qbunia Not sure about you guys but mine speeds up on a physical device. Only slow on emulator so I'm ignoring it haha

**Comment by qbunia** [comment]
Ive tested it on physical device using Redmi 7.

**Comment by pycraft114** [comment]
any news about this?

**Comment by KrisLau** [comment]
@pycraft114 It looks like they have it in their tasks for anyone to pick up. The tasks they have up are here: https://github.com/wix/react-native-calendars/projects/5#card-59835416

**Comment by KrisLau** [comment]
@pycraft114 It looks like they have it in their tasks for anyone to pick up. The tasks they have up are here: https://github.com/wix/react-native-calendars/projects/5#card-59835416
