### ISSUE TITLE
Make calendar timezone configurable when generating dates

### ISSUE THREAD

**Issue by rlugge** [wix/react-native-calendars#599]
## Description

I'm working on an app where the user may be manipulating times and dates in another time zone than the user is actually currently in.  E. G. I may currently be in California, but the business I'm managing is in Texas, or New York.

It would be convenient if the timestamp produced by the calendar tag when the user touches a date were based on a configurable timezone, rather than the user's timezone.

## Expected Behavior

If I configure the calendar as <Calendar ... timezone = { 'America/Los_Angelas'}>, when the user clicks on a date, the returned object has a timestamp set to midnight on that date in the indicated timezone.

## Observed Behavior

If I configure the calendar as <Calendar ... timezone = { 'America/Los_Angelas'}>, when the user clicks on a date, the returned object has a timestamp set to midnight on that date in the user's current timezone.

**Comment by rlugge** [comment]
Actually, I realized after the fact that while the timestamp is not timezone aware, the date string can be easily converted via moment into a timezone aware time -- so this was a case of me not seeing all the tools available to me that I was already using.

**Comment by mehdi-developer** [comment]
Can you please share the code on how did you implemented timezone ?
