### ISSUE TITLE
set font family in theme

### ISSUE THREAD

**Issue by sifrenette** [wix/react-native-calendars#6]
There's no way to set a custom font family for the text in the calendars. Maybe add a fontFamily attribute in the theme prop that will be applied to every text styles?

I'm creating a lot of issues... I can make a pull request if you want. Just let me know how you want to implement it.

**Comment by tautvilas** [comment]
Hey are you using react-native-web? Because in iOS and Android the correct UX pattern is to use default system font.

**Comment by tautvilas** [comment]
You can make a pull request, that adding `fontFamily` prop to `theme` would change calendar font. Just make sure that by default `fontFamily` is not set (like it is right now) so that it would be default android/ios system font

**Comment by tautvilas** [comment]
fixed with #66
