### ISSUE TITLE
How horizontal calendars control addMonth via buttons

### ISSUE THREAD

**Issue by ZhixiangWangCR7** [wix/react-native-calendars#602]
This is a horizontal calendar, I want to jump back to the current month from other months by returning to the Today button, but I don't know how to achieve it.
![2018-08-22 2 31 51](https://user-images.githubusercontent.com/41480432/44446747-9f7d1200-a618-11e8-87a6-21767eea7f97.png)

**Comment by yikkok-yong** [comment]
Hi,

you may want to take a look the solution I described here #589 
For your case, you just implement the solution to your **Today Button**.

**Comment by ZhixiangWangCR7** [comment]
@yikkok-yong  Thank you for your help, but I am not using Agenda, but a horizontal CalendarList, can not call the chooseDay () function, what should I do?

**Comment by ZhixiangWangCR7** [comment]
@yikkok-yong Thank you for your help, I have found a solution.

**Comment by ZhixiangWangCR7** [comment]
我是通过动态修改current的值实现的，current={this.state.dateString}，然后通过返回今天按钮的onPress事件，修改dateString的值，就能跳到你想到的日期了

在 2018-08-30 10:24:40，"hubin920218" <notifications@github.com> 写道：


@ZhixiangWangCR7 你好我想请问下你找到的解决方案是什么,因为我目前也遇到这样类似的问题,希望可以用日期选择器控制calendarlist 跳转到指定位置

**Comment by sharma-archu** [comment]
I am facing same issue, did you find out the solution?
Please help. I awant current button to move to current month.
