### ISSUE TITLE
Fill Gap from Period StartingDay and EndingDay

### ISSUE THREAD

**Issue by amorettimarcelo** [wix/react-native-calendars#610]
Hey there, 
So, I am trying to create periods dynamically based on users preferences, I managed to create and insert into the calendar the starting and ending date. I was hoping that react-native-calendars would do the heavy lifting and fill all the dates between starting and ending date.
Is it an known bug? Or maybe a feature that isn't implemented yet? Did anyone managed a workarround?
## Expected Behavior

Based on the starting and ending date, react native calendars should fill the dates in between.
## Observed Behavior

What actually happened when you performed the above actions?

![captura de tela 2018-08-29 as 09 31 59](https://user-images.githubusercontent.com/39268766/44787777-7277b480-ab6e-11e8-87f3-36cd1edc2f02.png)

Running on Iphone 6 simulator
react-native: 0.56.0
react-native-calendars: 1.20.0

**Comment by akuma06** [comment]
Duplicate of #509

**Comment by brentkirkland** [comment]
Maybe this will help someone a little more than the code example above.

```js
import React from 'react'
import _isEmpty from 'lodash/isEmpty'
import { Calendar } from 'react-native-calendars'

export default class CalendarWithPeriodFill extends React.Component {
  state = {
    start: {},
    end: {}, 
    period: {},
  }

  getDateString(timestamp) {
    const date = new Date(timestamp)
    const year = date.getFullYear()
    const month = date.getMonth() + 1
    const day = date.getDate()

    let dateString = `${year}-`
    if (month < 10) {
      dateString += `0${month}-`
    } else {
      dateString += `${month}-`
    }
    if (day < 10) {
      dateString += `0${day}`
    } else {
      dateString += day
    }

    return dateString
  }

  getPeriod(startTimestamp, endTimestamp) {
    const period = {}
    let currentTimestamp = startTimestamp
    while (currentTimestamp < endTimestamp) {
      const dateString = this.getDateString(currentTimestamp)
      period[dateString] = {
        color: 'green',
        startingDay: currentTimestamp === startTimestamp,
      }
      currentTimestamp += 24 * 60 * 60 * 1000
    }
    const dateString = this.getDateString(endTimestamp)
    period[dateString] = {
      color: 'green',
      endingDay: true,
    }
    return period
  }

  setDay(dayObj) {
    const { start, end } = this.state
    const {
      dateString, day, month, year,
    } = dayObj
    // timestamp returned by day is in 12:00AM UTC 0, want local 12:00AM
    const timestamp = new Date(year, month - 1, day).getTime()
    const newDayObj = { ...dayObj, timestamp }
    // if there is no start day, add start. or if there is already a end and start date, restart
    const startIsEmpty = _isEmpty(start)
    if (startIsEmpty || !startIsEmpty && !_isEmpty(end)) {
      const period = {
        [dateString]: {
          color: 'green',
          endingDay: true,
          startingDay: true,
        },
      }
      this.setState({ start: newDayObj, period, end: {} })
    } else {
      // if end date is older than start date switch
      const { timestamp: savedTimestamp } = start
      if (savedTimestamp > timestamp) {
        const period = this.getPeriod(timestamp, savedTimestamp)
        this.setState({ start: newDayObj, end: start, period })
      } else {
        const period = this.getPeriod(savedTimestamp, timestamp)
        this.setState({ end: newDayObj, start, period })
      }
    }
  }

  render() {
    const { period } = this.state
    return (
      <Calendar
        onDayPress={this.setDay.bind(this)}
        markingType='period'
        markedDates={period}
      />
    )
  }
}
```

**Comment by darylk31** [comment]
just building on top of seco35's solution, granted you already have the onDayPress to return a start date and end date, here is my solution.

```
import moment from 'moment';

createDateRange(startDate, endDate) {
    const dateRange = {
      [startDate]: { selected: true, startingDay: true, color: 'green' },
      [endDate]: { selected: true, endingDay: true, color: 'green' },
    };
    if (startDate && endDate) {
      let start = moment(startDate).startOf('day').add(1, 'days');
      const end = moment(endDate).startOf('day');
      while (end.isAfter(start)) {
        Object.assign(dateRange, { [start.format('YYYY-MM-DD')]: { selected: true, color: 'green' } });
        start = start.add(1, 'days');
      }
    }
    return dateRange;
  }

```
Slightly cleaner method using moment.

**Comment by kalraneeraj24550** [comment]
@brentkirkland  sir, your code works for me fine, but the selected date comes in square background not circle .can you plz help me. how to make it circle

**Comment by nervouscat** [comment]
@kalraneeraj24550 had the same issue, to fix this, make sure you change the format of the startDate and endDate::

`createDateRange(startDate, endDate) {
  **startDate = moment(startDate).format('YYYY-MM-DD');
  endDate = moment(endDate).format('YYYY-MM-DD');**
    const dateRange = {
      [startDate]: { selected: true, startingDay: true, color: 'green' },
      [endDate]: { selected: true, endingDay: true, color: 'green' },
    };
    if (startDate && endDate) {
      let start = moment(startDate).startOf('day').add(1, 'days');
      const end = moment(endDate).startOf('day');
      while (end.isAfter(start)) {
        Object.assign(dateRange, { [start.format('YYYY-MM-DD')]: { selected: true, color: 'green' } });
        start = start.add(1, 'days');
      }
    }
    return dateRange;
  }`

**Comment by auseika** [comment]
@nervouscat I have a strong feeling that this solution will not work in different timezones.

**Comment by YosefLehrer** [comment]
Hey @darylk31 , do you perhaps have the implementation for onDayPress to return a start date and an end date? I'm trying to get it in a functional component using moment and without lodash and I would love to see how you've done it.

**Comment by erikadelao-dev** [comment]
@YosefLehrer I have the same question, were you able to firgue this out?

**Comment by cotrimelias** [comment]
I made this helper function to convert a start and end date into a valid Period range. Just throw it into your /utils.tsx
**You need date-fns installed. I highly recommend anyone working with calendars to use date-fns**

Installation: `npm i date-fns`

```typescript
export const getCalendarPeriod = (
  startDate: Date,
  endDate: Date,
  color: string = "#00ACF5",
  textColor: string = "white",
  marked: boolean = false,
  dotColor: string = "red",
) => {
  const duration =
    intervalToDuration({
      start: startDate,
      end: endDate,
    }).days ?? 0;
  const markedDates: MarkedDates = {};
  markedDates[getCalendarDateString(startDate)] = {
    startingDay: true,
    color,
    textColor,
    marked,
    dotColor,
  };
  for (let i = 2; i <= duration; i++) {
    markedDates[
      getCalendarDateString(
        add(startDate, {
          days: i,
        }),
      )
    ] = {
      color,
      textColor,
      marked,
      dotColor,
    };
  }
  markedDates[getCalendarDateString(endDate)] = {
    endingDay: true,
    color,
    textColor,
    marked,
    dotColor,
  };
  return markedDates;
};
```

**Usage:**
```typescript
<CalendarProvider date={initialDay}>
    <Calendar
      markingType="period"
      date={initialDay}
      onDayPress={(day) => setInitialDay(day.dateString)}
      markedDates={getCalendarPeriod(
        getCalendarDateString(initialDay),
        add(initialDay, { days: 7 }),
      )}
    />
</CalendarProvider>
```
