### ISSUE TITLE
make calendar collapsible

### ISSUE THREAD

**Issue by ZhixiangWangCR7** [wix/react-native-calendars#612]
Is there a way to make the calendar component collapse like an agenda (showing only one week instead of one month, and having a button showing its full view when folded)? like this:
![ea125e1e-abc0-11e6-9e29-491acbcb0d07](https://user-images.githubusercontent.com/41480432/44826307-f4d0a900-ac40-11e8-8dd3-e246a26ae071.gif)

**Comment by tiaaaa123** [comment]
I want this so much!

**Comment by trancanh2202** [comment]
Someone can do it ?

**Comment by danna88** [comment]
any progress?

**Comment by ihsanktmr** [comment]
see my comment 

[https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538](url)

**Comment by ihsanktmr** [comment]
I explained it here

[https://github.com/wix/react-native-calendars/issues/998](url)

**Comment by chenei** [comment]
Do you still have a problem?
