### ISSUE TITLE
State doesnt properly update

### ISSUE THREAD

**Issue by diickens** [wix/react-native-calendars#613]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Hello together I'm actually building a note app where you can add some notes to a specific date in calendar.

I'm using the wix-agenda component for the calendar. When clicking on the the grey checkbox I update the state of the item to be checked, but the state doesnt get the update. When I save my file in editor again (using Hotload) the component gets updated and the checkbox appears as yellow. Anyone

## Expected Behavior

Checkboxes should get updated on click

## Observed Behavior

The checkboxes get updated on hotload save

## Environment

Please run these commands in the project folder and fill in their results:

* `react-native-calendars@1.20.0`: 

Also specify:

1. IPhone 8 Plus

## Reproducible Demo

`import React, { Component } from 'react';
import { Text } from 'react-native';
import { connect } from 'react-redux';
import { Container, Header, Left, Button, Icon, Body, Title, Right } from 'native-base';
import { DrawerActions } from 'react-navigation';
import { GiftedChat } from 'react-native-gifted-chat';

import { loadMessages, sendMessage, updateMessage } from '../actions/index.js';

class ChatScreenSingle extends Component {
  constructor(props) {
    super(props);
    this.state = { messages: [],
      chat: {
        email: '',
        password: ''
    } };
    this.onSend = this.onSend.bind(this);
  }
  componentWillMount() {
    this.setState({
      messages: [
        {
          _id: 1,
          text: 'Hello developer',
          createdAt: new Date(Date.UTC(2016, 7, 30, 17, 20, 0)),
          user: {
            _id: 2,
            name: 'React Native',
            avatar: 'https://facebook.github.io/react/img/logo_og.png',
          },
        },
      ],
    });
  }
  onSend(messages = []) {
    this.setState((previousState) => {
      return {
        messages: GiftedChat.append(previousState.messages, messages),
      };
    });
  }
  render() {
    return (
      <Container>
            <Header>
            <Left>
            <Button transparent onPress={() => this.props.navigation.dispatch(DrawerActions.toggleDrawer())}>
              <Icon name='ios-menu' />
            </Button>
            </Left>
            <Body>
                <Title> Chat </Title>
            </Body>
            <Right>
                <Button transparent>
                <Text> </Text>
                </Button>
            </Right>
            </Header>
      <GiftedChat
        messages={this.state.messages}
        onSend={this.onSend.bind(this)}
        user={{
          _id: 1,
        }}
      />
        </Container>
    );
  }
}

const mapStateToProps = ({ chat }) => {
  //const { email, password, error, loading } = chat;

  return { email, password, error, loading };
};

export default connect(mapStateToProps, {
  loadMessages, updateMessage, sendMessage
})(ChatScreenSingle);`

**Comment by iswanj** [comment]
I also get this issue. To debug this issue, I put a `console.log` inside `renderItem` of `Agenda` component and it never called. Also, they are using `FlatList` component behind the scene and didn't use `extraData` props so I have added it but the issue is still there.

**Comment by iswanj** [comment]
@diickens there is a method call `rowHasChanged` in `Agenda` component it solved my issue.

**Comment by diickens** [comment]
@iswanj will test this ASAP. Thanks anyway 👍  :)
