### ISSUE TITLE
Agenda in IOS - undefined is not an object (evaluating 'days[0].clone')

### ISSUE THREAD

**Issue by Martinchit** [wix/react-native-calendars#614]
Agenda is only working in simulator with debug mode.

This error appears when using my iphone in debug mode. And in release mode both simulator and iphone dun work.

Any ideas what is going on?

**Comment by heshanlk** [comment]
I had the same issue and the date format should be YYYY-MM-DD to fix the issues, so all the dates you feed into the Calendar component should follow that pattern.

**Comment by hugpeter** [comment]
I'm having the same issue, for some reason it works fine while in remote debug mode, but as soon as i turn it off, the same error shows.

**Comment by pascal-canuel** [comment]
> I'm having the same issue, for some reason it works fine while in remote debug mode, but as soon as i turn it off, the same error shows.

same for me

**Comment by prancky** [comment]
> > I'm having the same issue, for some reason it works fine while in remote debug mode, but as soon as i turn it off, the same error shows.
> 
> same for me
any solution???

**Comment by prancky** [comment]
> I'm having the same issue, for some reason it works fine while in remote debug mode, but as soon as i turn it off, the same error shows.

any solution ?

**Comment by ThalKod** [comment]
@prancky 
Had the same issue, i fixed it by makings sure that i provide the correct date format to the selected props, Format should be `YYYY-MM-DD`
```js
import { Agenda } from 'react-native-calendars';
 ...

<Agenda
  ...
  selected={moment().format("YYYY-MM-DD")} 
  ...   
 />
```

**Comment by siyasiyasiya** [comment]
> @prancky Had the same issue, i fixed it by makings sure that i provide the correct date format to the `selected` props, Format should be `YYYY-MM-DD`, Any date that you feed to the `Agenda` components should have this format.
> 
> ```js
> import { Agenda } from 'react-native-calendars';
>  ...
> 
> <Agenda
>   ...
>   selected={moment().format("YYYY-MM-DD")} 
>   ...   
>  />
> ```

I am doing this but I am still getting the error
