### ISSUE TITLE
Add testID prop for calendar days

### ISSUE THREAD

**Issue by erickrmattos** [wix/react-native-calendars#617]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I want to use automatization testing with this component, but the days on the calendar don't have the testID properly setup to distinguished today or available/disabled dates.

## Expected Behavior

I would expect to have specific testID for some dates like today, available or disabled dates, so I could select then on automatization testing framework like wix/detox.

## Observed Behavior

I can't properly distinguish the calendar days with testIDs

## Relevant PR

- Merged: #577 

- Opened for this issue: #616

**Comment by erickrmattos** [comment]
I was able to do the same thing creating a custom DayComponent.

**Comment by realsilversurfer** [comment]
its working for you on Android or only on iOS?
