### ISSUE TITLE
Using with Animated View causes lag in Agenda

### ISSUE THREAD

**Issue by ghmendonca** [wix/react-native-calendars#629]
## Description

When using with animated view that causes the Agenda component to scroll down, it scrolls but very lag, around 30 fps.

## Expected Behavior

Scroll down without lagging.

## Observed Behavior

I want to have a View above the Agenda but this View will be collapsiable, so this View when shown make the Agenda to scroll a little down (60 pixels) and when hidden scroll back up. For this animation I am using [https://github.com/oblador/react-native-collapsible](https://github.com/oblador/react-native-collapsible)

## Environment

Please run these commands in the project folder and fill in their results:

My app was created by `create-react-native-app`

* `react-native-calendars@1.20.0`:
* `expo@27.1.1`:

I am running my app an iPhone 10 - iOS version 11.4.1

## Reproducible Demo

The image showing the fps drop: [https://imgur.com/q6zUoK2](https://imgur.com/q6zUoK2)

**Comment by chenei** [comment]
Do you still have a problem?
