### ISSUE TITLE
CalendarList load items for month not working with redux

### ISSUE THREAD

**Issue by mharrisweb** [wix/react-native-calendars#630]
CalendarList doesnt render using `loadItems(dates)`

## Expected Behavior

Populate `CalendarList` with events inbetween `dates` param. I am creating my data in my events reducer:

            const newItems = {};

            for (let i = 0; i < 180; i++) {
                const time = moment().utc() + i * 24 * 60 * 60 * 1000;

                const strTime = timeToString(time);

                if (events[strTime]) {
                    newItems[strTime] = { ...events[strTime] };
                } else {
                    newItems[strTime] = {};
                }
            }
            return {
                ...newItems
            };

I call this from  `componentDidMount`, in my month component:

        const {   componentDidMount() {
        const {
            credentials: { year, group, id },
            fetchEvents
        } = this.props;
        const Id = id || group;
        fetchEvents(Id);
    }

I then mark the relevant dates as selected using the `loadItems` param:

```
 loadItems(dates) {
        const { events } = this.props;
        const moment = extendMoment(Moment);
        const lastItemIndex = dates.length;

        const startDate = moment(dates[0].timestamp).startOf("month"),
            endDate = moment(dates[lastItemIndex - 1]).endOf("month");

        const dateRange = moment().range(startDate, endDate);

        newEvents = Object.keys(events).reduce((output, dateString) => {
            if (dateRange.contains(moment(dateString).toDate())) {
                output[dateString] = events[dateString];

                if (!helpers.emptyObject(output[dateString])) {
                    output[dateString].selected = true;
                }
            }

            return output;
        }, {});

        this.setState({
            markedDates: { ...newEvents, ...this.state.markedDates }
        });
    }
```

@tautvilas any ideas? Really stuck on this.

Link to repo:

https://bitbucket.org/matthisco/ejected-calendar/src/7953011ab44b08f60307d051655d8dcb3035a889/?at=feature%2FChunk_event_data

## Observed Behavior

Month does not render:

![10](https://user-images.githubusercontent.com/8245572/45479925-b0183800-b73f-11e8-9e77-eeac044bac30.png)

## Environment

* react-native-calendars@1.19.4
* react-native@0.55.4

**Comment by caiorios** [comment]
Hi, I am having a similar issue. In my case, I am trying to update markers using this.setState() when onVisibleMonthsChange is fired. After some research, I found out that if I do any this.setState() inside onVisibleMonthsChange function, it only shows 3 months on calendar. Going to past or future outputs the same as your picture.

Here is an example code to reproduce the issue:

```
export default class CalendarTest extends Component {
  state = {
    test: 1
  };

  updateMarkers(dates) {
    this.setState({ test: 2 });
  }

  render() {
    return (
      <CalendarList onVisibleMonthsChange={this.updateMarkers.bind(this)} />
    );
  }
}
```

Did I miss something?

**Comment by imshreyansh** [comment]
Thanks Brother @caiorios 
and thanks for raising the issue @mharrisweb
