### ISSUE TITLE
How can I scroll infinity item without data?

### ISSUE THREAD

**Issue by minhchienwikipedia** [wix/react-native-calendars#634]
How can I scroll infinity item without data? For now, I need scroll infinity item like the scroll months.
Can anyone help me resolve my issue?

**Comment by tautvilas** [comment]
could you please clarify the question?

**Comment by minhchienwikipedia** [comment]
I mean I want scroll passed day infinity like month scroll. Like Google calendar

**Comment by minhchienwikipedia** [comment]
@tautvilas Can you help me?

**Comment by OrelExia** [comment]
I don't understand your issue are you using calendar or agenda ?

**Comment by MrHazimAli** [comment]
I think what @minhchienwikipedia meant is that how do we modify agenda component to act like google calendar which can scroll down to next item on user own agenda without having restricted to month.

something like this : 
https://media.idownloadblog.com/wp-content/uploads/2017/12/Google-Calendar-iPHone-X.png

@tautvilas @OrelExia

**Comment by andregufc** [comment]
Create an empty array for each day in your loaded interval.
