### ISSUE TITLE
Can't  change height of calendar to fullScreen

### ISSUE THREAD

**Issue by angelos3lex** [wix/react-native-calendars#638]
## Description

Can't stretch calendar to full Screen

If i add:
```
<Calendar
        style={{height:100}}
...
```
i get:
![height100calendar](https://user-images.githubusercontent.com/18629179/45801395-81a8d880-bcbc-11e8-897f-f4d35255f0f6.png)

So the calendar is not resized to fit its height. So if i add:
```
<Calendar
        style={{height:"100%"}}
...
```
![height100percent](https://user-images.githubusercontent.com/18629179/45801418-879eb980-bcbc-11e8-8a79-938df6f2f280.png)

Calendar will have it's fixed height, and won't stretch to full screen.
So, my question is, is there any way of stretching Calendar to fullScreen mode?
## Environment
Android tested only

**Comment by Akhoy** [comment]
You need to override the `stylesheet.day.basic` theme like so:
```js
<Calendar theme={{
    'stylesheet.day.basic':{
      'base':{
        width:30,
        height:100
      }
    }
}} />
```
It is hard-coded as 32 X 32 here: https://github.com/wix/react-native-calendars/blob/master/src/calendar/day/basic/style.js#L9

**Comment by Ahmed-Imam** [comment]
calendarHeight={100}

**Comment by HuuPhuc-HPIT** [comment]
> It is hard-coded as 32 X 32 here
When dot transformed then we have to handle how you?

**Comment by sperardt** [comment]
Having same issue with height. But my problem is it doesn't get smaller which is causing issues with small smartphones. Tried to override stylesheet.day.basic as @Akhoy suggested but it didn't work for me. Any other idea on how it can be solved?

**Comment by mqwerty** [comment]
> Having same issue with height. But my problem is it doesn't get smaller which is causing issues with small smartphones. Tried to override stylesheet.day.basic as @Akhoy suggested but it didn't work for me. Any other idea on how it can be solved?

Perhaps you need to use a different key: `stylesheet.day.period`, `stylesheet.day.dot`, etc...

**Comment by Ranjan-Adarsh** [comment]
> Having same issue with height. But my problem is it doesn't get smaller which is causing issues with small smartphones. Tried to override stylesheet.day.basic as @Akhoy suggested but it didn't work for me. Any other idea on how it can be solved?

Did you find any solution for this? I am also having the same issue on smaller screens.

**Comment by sperardt** [comment]
@Ranjan-Adarsh I had to override the following styles: stylesheet.calendar.header and  stylesheet.day.period

On these two styles file, I played with their styles until I founded the ones I wanted to override. For example, on _stylesheet.calendar.header_ I overrode _header, monthText, arrowImage, dayHeader_.
