### ISSUE TITLE
How to setup a range of dates to show as selected

### ISSUE THREAD

**Issue by kcfgl** [wix/react-native-calendars#64]
I must be missing something super simple.  But using the example, when I set the markedDates like this:
```
markedDates={{
           '2012-05-21': [{startingDay: true, color: 'blue', selected: true}],
           '2012-05-24': [{endingDay: true, color: 'blue', selected: true}]
}}
```
Why aren't all the days from 5/21 - 5/24 selected and colored in Blue?  When I run this all i see is are two days marked.

<img width="348" alt="screen shot 2017-06-19 at 4 44 28 pm" src="https://user-images.githubusercontent.com/19731815/27305185-9d90ebe4-550e-11e7-8f79-68e1aa90a8de.png">

Thanks again for this component, I think its going to be what i need.

**Comment by kcfgl** [comment]
Update: I didn't set the markedDates to 'interactive.'

But the middle dates still do not fill in.  Does this mean I would have to supply all the dates in a date range to have them all filled in?  Is there any easier way to do this, especially if someone wants to select a range that spans many months.

Thanks again.

**Comment by tautvilas** [comment]
Hi, yes, currently you have to mark each day and do the day range calculations inside your app

**Comment by kcfgl** [comment]
@tautvilas Rats. But totally understandable.  I know this is outside the scope of your component, but I'm sure you're very familiar with the options to do the ranges.  I think moment.range OR d3-time. From a performance standpoint, would you suggest either (or something different?). No worries if you dont have time to respond.

**Comment by tautvilas** [comment]
Yes there were several requests to do this range calculation logic in this component, but currently I think it makes sense not to do it here. I want this component to stay date-library agnostic. You can choose any date library you want and use it your project. I think moment.js is a pretty good lib to use these days.

**Comment by kcfgl** [comment]
@tautvilas Thanks for being so responsive. You've done a great job with this and I appreciate it! Went with moment.js and its working great.

**Comment by tautvilas** [comment]
Thanks for your support :)

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/react-native-date-range-picker
