### ISSUE TITLE
onDayPress Is NOT WORKING

### ISSUE THREAD

**Issue by Ash-faq** [wix/react-native-calendars#644]
## Description
When iam using the Agenda from react-native-calendars onDayPress is not working 
and it works for some of the dates

1. samsung galaxy tab A :

**Comment by ManigandanRaamanathan** [comment]
> can someone help on this issue

Could please explain further

**Comment by matthewphiong** [comment]
@Ash-faq Try disabling remote JS debugging.

**Comment by Ash-faq** [comment]
@matthewphiong even disabling remote JS debugging same issue,

**Comment by bemaverick** [comment]
@Ash-faq  i have the same problem
my remote JS debugging is disabled

```
  onDayPress={() => {
            alert()
 }}
```
nothing happened

**Comment by tolik85** [comment]
> @Ash-faq Try disabling remote JS debugging.

It works, but what if you do need to debug your application?

**Comment by blatde91** [comment]
> > @Ash-faq Try disabling remote JS debugging.
> 
> It works, but what if you do need to debug your application?

Yeah maybe that's a little bit of an oversight. Just blew a whole morning trying to figure out what was going on. It was working, turned on debugging to start, y'know, debugging, then it stopped working.
