### ISSUE TITLE
DotColor not changed

### ISSUE THREAD

**Issue by abdymm** [wix/react-native-calendars#647]
## Description

I just add a dotColor object on markDates, but it doesn't changed

## Expected Behavior

here's my markDates Object:
` markedDates={{
                "2018-10-24": {
                  selected: true,
                  marked: true,
                  dotColor: "green"
                },
                "2018-10-25": { marked: true, dotColor: "red" },
                "2018-10-26": { marked: true },
                "2018-10-27": { disabled: true, activeOpacity: 0 }
              }}`
on 2018-10-25 should be have red dot color.

## Observed Behavior

what actually happened is the dot color still in default color (blue)

<img width="325" alt="screen shot 2018-10-04 at 7 35 39 am" src="https://user-images.githubusercontent.com/1695466/46446792-8b483b00-c7a8-11e8-933e-70665718c7bf.png">

i just paste from your example code *Calendar with marked dates and hidden arrows*
when i run in my code the result like i said.

**Comment by abdymm** [comment]
can anyone help? @tautvilas

**Comment by Muhammad-Azhr** [comment]
const activities_type = {
        viewing: { key: 'viewing', color: '#0d75da', selectedDotColor: '#0d75da' },
        meeting: { key: 'meeting', color: '#ff8e42', selectedDotColor: '#ff8e42' },
        task: { key: 'task', color: '#00b545', selectedDotColor: '#00b545' },
        arrival: { key: 'arrival', color: '#00b0b3', selectedDotColor: '#00b0b3' },
        departure: { key: 'departure', color: '#1c5050', selectedDotColor: '#1c5050' },
   }

markedDates={
   {
      '2018-11-20': { dots: [arrival, departure, meeting] },
      '2018-11-22': { dots: [meeting, departure] },
      '2018-11-23': { dots: [arrival, departure], },
      '2018-11-04': { dots: [arrival, task], }
   }}

**Comment by chenei** [comment]
Do you still have a problem?
