### ISSUE TITLE
Custom day view have margins around.

### ISSUE THREAD

**Issue by agruchala** [wix/react-native-calendars#651]
I'm trying to make calendar custom day view in my app. I want to day views take all available horizontal width and height evenly.

I tried to use `flex: 1` on container, but calendar is always putting some spacing between elements.

This is my JSX for day view:

```
<View style={Styles.container}>
    <Text style={Styles.dayText}>1</Text>
    <View style={Styles.reportedHoursBox}>
        <Text style={Styles.hoursText}>8h</Text>
    </View>
</View>
```
I have tried to change calendar theme by changing some day view properties by changing `stylesheet.day.single`, there is a width and height in base, It didn't work. 

I'm aiming for grid view with day view borders, like excel sheet. Someone can tell me what props and styles I have to change to make layout without margins? Container view have border line around, and this is how I know it has spacing between day views.

**Comment by 7laria** [comment]
same issue.

**Comment by 7laria** [comment]
solved:
react-native-calendars/src/calendar/style.js
`   week: {
      // marginTop: 7,
      // marginBottom: 7,
      flexDirection: 'row',
      justifyContent: 'space-around'
    },`

my component is:
`<TouchableOpacity
                onPress={() => {
                    this.selectDate(date)
                }}
                disabled={!Object.keys(this.state.markedDays).includes(date.dateString)}
                style={{ width: 50, height: 50, borderColor: 'grey', borderWidth: 1, margin: 0, backgroundColor: backgroundColor, alignItems: 'center', justifyContent: 'center' }}>
                <Text style={{ color: labelColor }}>{date.day + ''}</Text>
            </TouchableOpacity>
`

**Comment by chenei** [comment]
Do you still have a problem?

**Comment by darron1217** [comment]
@chenei  How can I customize week container style?

**Comment by 7laria** [comment]
@darron1217 you can add theme prop to your calendar component and style week like this: 
`theme={{
    week: {
      marginTop: 5,
      flexDirection: 'row',
      justifyContent: 'space-between'
}}`

**Comment by darron1217** [comment]
@7laria After some inspection, the code below worked for me.
Thank you for the hint 👍 
```
theme={{
  'stylesheet.calendar.main': {
    week: {
      marginTop: 3,
      marginBottom: 3,
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
  },
}}
```

**Comment by theneekz** [comment]
Solved my issue: I've patched my node_modules with the changes from this PR https://github.com/wix/react-native-calendars/pull/1612

**Comment by MobileMon** [comment]
none of these solutions work for me......

**Comment by GalkinAlexeyAndreevich** [comment]
weekVerticalMargin:0,

**Comment by deidalopez** [comment]
you can pass `weekVerticalMargin: 0` through the `theme` prop in `CalendarList`
