### ISSUE TITLE
Calender in Agenda not resizing correctly

### ISSUE THREAD

**Issue by WazzupTom** [wix/react-native-calendars#652]
## Description

The calender doesn't resize correctly, when I load in the agenda on Android it displays the dates incorrectly after resizing visibly multiple times.

![image](https://user-images.githubusercontent.com/41295339/46794833-067d9400-cd49-11e8-84e0-6c0df9e39cb8.png)

Is there any way to fix this?

## Expected Behavior

I'd like it to show the dates properly right when it loads. It does display the dates properly after scrolling through the agenda.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.21.0
* `npm ls react-native`: 0.57.1

Also specify:

1. Phone/emulator/simulator & version: Android API 27

**Comment by Tracklous** [comment]
Hi @WazzupTom , If you are using pastScrollRange and futureScroll range in `<Agenda .../>` then try to put '1' at-least in the pastScrollRange property. eg: `pastScrollRange = {1}`

**Comment by WazzupTom** [comment]
Hi,

We weren't using the properties pastScrollRange or futureScrollRange, however when I implement them the calender still exhibits the same behavior. This only happens on older and slower devices.

Is there any work around for this? Could I manually call for a refresh of the calender? Thanks for your help.

**Comment by dmarkowski** [comment]
![image](https://user-images.githubusercontent.com/6513155/52794712-a5f0c180-3070-11e9-8dd5-6900768b8f68.png)

Hi, I have a similar problem after update RN from 0.51.0 to 0.58.3.

As a workaround, I am triggering onDateChange method every time when the component will receive new props.

`
export default class AgendaScreen extends Component<Props, {}> {
	agenda: any;

	componentWillReceiveProps(newProps: Props) {
		if(this.agenda) {
			this.agenda.onDayChange(newProps.selectedDate.format("YYYY-MM-DD"));
		}
	}

	render() {
		const today = moment().format("YYYY-MM-DD");
		const dateBefore = moment().add(-28, "days").format("YYYY-MM-DD");
		return (
			<View style={{height: 700, backgroundColor: "white"}}>
				<AgendaWithoutList
					ref={a => this.agenda = a}
`

**Comment by otaviogaiao** [comment]
Has a solution for this been found? I'm experiencing the same thing when I'm on the last month of the calendar.

**Comment by HaswinVidanage** [comment]
+1
