### ISSUE TITLE
Is this repo maintained anymore? Lot's of issues, many without a response

### ISSUE THREAD

**Issue by imdadahad** [wix/react-native-calendars#657]

**Comment by sibelius** [comment]
It is

Last commit was 21 days ago

Feel free to answer issues and review pull requests

**Comment by imdadahad** [comment]
Okay, just out of curiosity is this library suitable for allowing a user to select a single date? This seems more applicable for being able to view a calendar and events within.

**Comment by dlimx** [comment]
There's libraries like [react-native-modal-datetime-picker](https://github.com/mmazzarolo/react-native-modal-datetime-picker) and [react-native-datepicker](https://www.npmjs.com/package/react-native-datepicker) which should be much more suitable for selecting a single date
