### ISSUE TITLE
Any plan to make Calendar hideable like Agenda?

### ISSUE THREAD

**Issue by isaaclem** [wix/react-native-calendars#663]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Wondering if there is any plan to make Calendar component hideable/collapsed to just show just Month and left right button? Something like Agenda where User has the option to show entire Calendar or just showing Month of calendar?

**Comment by JustinRohweller** [comment]
Hey man, just a comment that I found the solution for this, which would have saved me some trouble had I seen it in the docs.
You can hide the calendar by having the prop:
`theme={{
            "stylesheet.calendar.main": {
              monthView: { height: 0 },
              container: { height: 60 }
            }
          }}`
