### ISSUE TITLE
 Calendar is returned wrong month

### ISSUE THREAD

**Issue by jeancabral** [wix/react-native-calendars#665]
## Description

When I select one Day in Calendar is returned wrong month. example: if i select one day in october the date return is november.

"react-native": "0.56.0"
"react-native-calendars": "^1.21.0",

**Comment by websitedesignanddeveloper** [comment]
How did you solve it? I'm also getting same error. Selected date having one month ahead.

**Comment by shiva-zessta** [comment]
I am getting same issue, How did you solved this issue @jeancabral
