### ISSUE TITLE
[BUG] Agenda jumping days when scroll

### ISSUE THREAD

**Issue by victorsilent** [wix/react-native-calendars#667]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Scroll reservation-list jumps some days

## Expected Behavior

When scroll and hit next selected day, the reservation scroll and fixes at the top of current selected day

## Observed Behavior

When scroll and hit next selected day the agenda cuts the previous day and sometimes jumps two or three next selected days.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.21.0
* `npm ls react-native`: 0.55.2

Also specify:

1. Phone/emulator/simulator & version: Xiaomi 5A Android 7.0 and Android Studio simulators

## Reproducible Demo

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8001358/47867461-55ff2f00-dde0-11e8-8b17-056329aea983.gif)

**Comment by gugakatsi** [comment]
@victorsilent hi , can you share your loaditemFormonth ? pseudo code at least.

**Comment by iquabius** [comment]
I had this bug as well and the only way I found to get around it is to set dates without events to an empty array.  Which are then handled by the `renderEmptyDate` function.
