### ISSUE TITLE
Dots and period marking type

### ISSUE THREAD

**Issue by roman-huliak** [wix/react-native-calendars#669]
Hi,
is possible to make marking independent days in marking type "period"?

Preview what i mean:
![simulator screen shot - iphone 6 - 2018-11-03 at 11 17 07](https://user-images.githubusercontent.com/7287207/47950958-9c789900-df5a-11e8-92a1-c37cd9dc231e.png)

Now i've done with marking of period of dates as group ( markingType={'period'} ) but now i need to set mark to specific days.
How can i do this?

**Comment by 000xuandu** [comment]
I, like you, are looking for the answer

**Comment by Vibinreji** [comment]
Hi,Anyone got solution for this issue?

**Comment by chenei** [comment]
Do you still have a problem?
