### ISSUE TITLE
Agenda loadItemsForMonth on scroll uses previous month

### ISSUE THREAD

**Issue by dlimx** [wix/react-native-calendars#674]
## Description

When scrolling the main `Agenda` and `CalendarList` views, `loadItemsForMonth` seems to be using the previous month rather than the current month.

On initial load and on clicking into a date from `CalendarList` views, the month is correct. On scrolling to the next month in Agenda, it begins to use the previous month.

## Expected Behavior

The correct month should be used for the scroll events.

## Observed Behavior

On iOS, the initial load and clicking on a date in `CalendarList` work, while scrolling breaks the month.

On Android, the initial load seems to re-call `loadItemsForMonth` on a `componentDidMount`, triggering it twice with a second 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.21.0
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version: iPhone X + iPhone X Simulator, 12.1 - Android Emulator Pixel 

## Reproducible Demo

![nov-05-2018 15-41-07](https://user-images.githubusercontent.com/16586511/48025471-83661880-e111-11e8-97f9-f6edb7bdd97a.gif)

![nov-05-2018 15-45-49](https://user-images.githubusercontent.com/16586511/48025606-eb1c6380-e111-11e8-8bd6-d2533b33ffae.gif)

**Comment by dlimx** [comment]
I believe this is due to `loadItemsForMonths` being called by `onVisibleMonthChange`.

The 0th index is always taken which leads to it usually being the previous month. I'll submit a PR in a bit after some testing - I believe using the 1st index if it exists fixes this issue.

**Comment by victorsilent** [comment]
I'm facing some problems to render the list when I have many items, on your example the list scroll works correctly, can you post your code on codesandbox?

**Comment by williamquintas** [comment]
So, I was facing a problem that is related. I use this to fetch more data of other months. What I discovered is that even when the agenda in the top is minified if I scroll the list, the loadItemsForMonth is triggered. So I verify in the loadItemsForMonth if the bar is maximized and only in this case I fetch more data.
For load more data when scrolling the list, I use the onDayChange.
```
<Agenda
  onCalendarToggled={flag => this.setState({ locked: flag })}
  items={items}
  onDayPress={this._dayChange}
  onDayChange={this._dayChange}
  loadItemsForMonth={(day) => {
    if (this.state.locked) {
      this._dayChange(day);
    }
  }}
  //ANOTHER PROPERTIES
/>
```
```
_dayChange = (day) => {
  const { year, month, dateString } = day;
     if (parseInt(moment(this.state.currentMonth, 'MMMM YYYY').format('MM'), 10) !== parseInt(month, 10)) {
        this.setState({ currentMonth: moment(dateString).format('MMMM YYYY') });
        //FETCH MORE DATA
     }
}
```

**Comment by marllonfrizzo** [comment]
I just sent a PR that help to solve this problem. #746

**Comment by chenei** [comment]
Do you still have a problem?

**Comment by gerahrios** [comment]
How do you manage to create this part?
I can't load my items that way, could someone help me or guide me?
![Captura de pantalla 2020-08-05 a la(s) 11 48 47](https://user-images.githubusercontent.com/43283646/89446422-be93e200-d711-11ea-808a-ab9dd41e0fea.png)

**Comment by monizb** [comment]
How did you manage to achieve backward scrolling on the agenda? Mine still doesn't want to do that

**Comment by rabiaah** [comment]
Issue still there, The console log keep printing wrong MONTH!
