### ISSUE TITLE
Agenda Week view slides left and right

### ISSUE THREAD

**Issue by TrustTheBoy** [wix/react-native-calendars#676]
## Description

Agenda Can you consider adding a left and right slide?

## Expected Behavior

When displaying the week view, swipe your finger left or right to switch

## Observed Behavior

Actually can't slide down to show `CalendarList`

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:react-native-calendars@1.21.0
* `npm ls react-native`:react-native for all version

Also specify:

1. Phone/emulator/simulator & version:
iphone all for ios 12.1

## Reproducible Demo

Gif demo：
![qq20181106-155847-hd](https://user-images.githubusercontent.com/20201085/48050455-e8d30b80-e1dc-11e8-8b38-b54a62ffb883.gif)

**Comment by anilkumar1505** [comment]
Currently i  am not able to swipe left and right in Agendaview

**Comment by shouhuori** [comment]
@TrustTheBoy  农历是自己实现的么？

**Comment by shouhuori** [comment]
@TrustTheBoy  How to support lunar？

**Comment by chenei** [comment]
Old issue.
