### ISSUE TITLE
Agenda won't scroll past more than 2 weeks of empty dates.

### ISSUE THREAD

**Issue by jeneve** [wix/react-native-calendars#678]
## Description

The agenda component won't scroll past more that 2 weeks of empty dates, is there a configuration that can change this?

## Expected Behavior

I should be able to scroll through the calendar past empty dates

## Observed Behavior

I can't scroll past if there are more than 2 weeks worth of empty dates in between 2 non-empty dates. 

![not_scrolling_past](https://user-images.githubusercontent.com/13407954/48283618-0c8b9100-e42b-11e8-97c6-ddf57f1ac448.gif)

if I return an empty `<Text />` tag from the `renderEmptyDate` function prop, it is fixed but adds big whitespaces to the agenda view, which is undesired. attempting to set style `height:0` on the text tag or to return a view instead reverts it to the above result (can't scroll past.)

![scrolls_with_spaces](https://user-images.githubusercontent.com/13407954/48283912-f205e780-e42b-11e8-9c76-9f32e41f80b8.gif)

Thanks so much for looking this over, if there is a configuration or workaround I'd love to learn of it!

**Comment by dlimx** [comment]
So this component doesn't really scroll past the current date if there's no new data, and nothing to render. It could use an `onEndReached` prop to support infinite forward scrolling.

We've been just loading 2 months of data at a time and ensuring that all dates get rendered so that even empty months still can be scrolled through.

**Comment by lucamir** [comment]
> So this component doesn't really scroll past the current date if there's no new data, and nothing to render. It could use an `onEndReached` prop to support infinite forward scrolling.
> 
> We've been just loading 2 months of data at a time and ensuring that all dates get rendered so that even empty months still can be scrolled through.

I have the same problem.
So for support the infinite scroll i need use the prop **onEndReached** for generate empty date, right?

**Comment by lucamir** [comment]
> So this component doesn't really scroll past the current date if there's no new data, and nothing to render. It could use an `onEndReached` prop to support infinite forward scrolling.
> 
> We've been just loading 2 months of data at a time and ensuring that all dates get rendered so that even empty months still can be scrolled through.

I have the same problem.
It seems that, this component does not provide a onEndReached prop. 
So how can i support the infinite scroll.
Any solution?

**Comment by HaswinVidanage** [comment]
Any fix for this ?

**Comment by chenei** [comment]
Still have this problem?
