### ISSUE TITLE
Is this package still under support or no longer supported ? 

### ISSUE THREAD

**Issue by MuhammadUmairghufran** [wix/react-native-calendars#680]

**Comment by tautvilas** [comment]
@ethanshar

**Comment by sibelius** [comment]
@tautvilas you should add more contributors, so we can keep this package up to date

**Comment by dlimx** [comment]
Are you guys taking apps for contributors/etc.?

Lots of PRs with no comments that look fine, we've been using private forks but we'd glad come back to master if some of those fixes/enhancements get merged in!

**Comment by tautvilas** [comment]
@goldenhammer

**Comment by chenei** [comment]
We try to keep maintain the library.
