### ISSUE TITLE
Is there way to select year directly in this component?

### ISSUE THREAD

**Issue by panda919** [wix/react-native-calendars#685]
## Description

It is necessary to select year directly in this component.
https://github.com/wix/react-native-calendars/issues/37
this idea is perfect solution for me..
But since this pull request isn't merge yet.
So i can not install.
it is not good to integrated manually, I want more better solution.
pls help me

**Comment by termitavee** [comment]
I had the same problem and manage to solve with an absolute transparent button:
`
    <Calendar ... />
    <TouchableOpacity
        style={{    
            position: 'absolute',
            top: 0,
            left: Dimensions.get('window').width / 2 - 130,
            height: 50,
            width: 220,
        }}
        onPress={() => this.setState({ showYearPicker: !showYearPicker })}
    />
`
