### ISSUE TITLE
Period Marking not working for 2+ days interval

### ISSUE THREAD

**Issue by aFaneca** [wix/react-native-calendars#688]
## Description

I just started using this component today, but the implementation doesn't seem to work the way the demo/examples/docs show.

## Expected Behavior
I was expecting that the days from 2018-12-10 to 2018-12-15 would be filled up with the color green, including the days in between.

## Observed Behavior

The reality is that both days get filled up with the color green, but nothing happens to the days in between.
Here's an illustrative image of the issue:
![screenshot_2018-11-26-14-59-01-766_com frontoffice](https://user-images.githubusercontent.com/14138443/49022211-357e8680-f18c-11e8-816e-3841fd8dafd2.png)

## Environment
* "react-native": "0.57.4",
* "react-native-calendars": "^1.21.0"
* Tested on: Redmi Note 4 (Android 7.0)

## Reproducible Demo

This is the code of my calendar:

> <Calendar
>               // Collection of dates that have to be colored in a special way. Default = {}
>                         markedDates={{
>                             "2018-12-10": { startingDay: true, color: "green" },
>                             "2018-12-15": { endingDay: true, color: "green" }
>                         }}
>                         // Date marking style [simple/period/multi-dot/custom]. Default = 'simple'
>                         markingType='period'
>             />

**Comment by nikhilhundare** [comment]
You need to specify all the dates that you want to be marked.Mention all the dates in between that interval as `selected : true, endingDay: false, startingDay: false, color: "green"`

**Comment by aFaneca** [comment]
> You need to specify all the dates that you want to be marked.Mention all the dates in between that interval as `selected : true, endingDay: false, startingDay: false, color: "green"`

Thanks for the reply. I understand that now. I guess this can be closed at this moment...

**Comment by ArkadySladkoff** [comment]
borderRadius for startingDay and endingDay not display after changing period as on image above

**Comment by kempoo** [comment]
> `borderRadius` for `startingDay` and `endingDay` not display after changing period as on image above
> 
> Fixed with snippet in index.js
> 
> ```
> if (flags.startingDay && !flags.endingDay) {
>         leftFillerStyle = {
>           backgroundColor: this.theme.calendarBackground,
>         };
>         rightFillerStyle = {
>           backgroundColor: flags.startingDay.color
>         };
>         containerStyle.push({
>           backgroundColor: flags.startingDay.color,
>           **borderRadius: 17**
>         });
>       } else if (flags.endingDay && !flags.startingDay) {
>         rightFillerStyle = {
>           backgroundColor: this.theme.calendarBackground,
>         };
>         leftFillerStyle = {
>           backgroundColor: flags.endingDay.color
>         };
>         containerStyle.push({
>           backgroundColor: flags.endingDay.color,
>           **borderRadius: 17**
>         });
>       } else if (flags.day) {
>         if (flags.day.color !== undefined) {
>           leftFillerStyle = {backgroundColor: flags.day.color};
>           rightFillerStyle = {backgroundColor: flags.day.color};
>           fillerStyle = {backgroundColor: flags.day.color};
>         }
>       }
> ```

could you please provide a repo with example?

**Comment by aFaneca** [comment]
yes seems like it.
