### ISSUE TITLE
showing date for empty item in agenda

### ISSUE THREAD

**Issue by VeeramHirekhan** [wix/react-native-calendars#691]
## Description
I have code here that when there is no item in an emptyDate nothing appears except for a gray line across the screen. I need help getting to make the date show with nothing in the text, not just one date but all dates that are empty. What i do understand is that if I declare a date in the item, then the empty date will appear but if not then nothing appears at all.

I have posted below my entire code to help me figure out how to render an empty date.

## Reproducible Demo

import React, { Component } from 'react'
import { Text, View, StyleSheet, StatusBar, SafeAreaView } from 'react-native'
import { Calendar, CalendarList, Agenda } from 'react-native-calendars'
import { Icon, Header } from 'react-native-elements'
import { createStackNavigator, createAppContainer } from "react-navigation"
import { Appbar } from 'react-native-paper'

export default class Schedule extends Component {

    openDrawer() {
        this.props.navigation.openDrawer();
        StatusBar.setHidden(true, "slide");
    }

    /*static navigationOptions = {
        title: 'Schedule',
        headerLeft: (
            <Icon name='menu' onPress={() => this.props.navigation.openDrawer()}/>
          ),
    };*/
    static navigatorStyle = {
      tabBarHidden: true
    };
    

  render() {
    return (
      <View style={styles.container}>
        <Header backgroundColor='#1DAEEB'
        leftComponent={{ icon: 'menu', color: '#FFFFFF', onPress:() => this.openDrawer(),}}
        centerComponent={{ text: 'Schedule', style: { color: '#FFFFFF', fontSize: 20, fontFamily: 'open-sans',} }}/>
        <Agenda
            // the list of items that have to be displayed in agenda. If you want to render item as empty date
            // the value of date key kas to be an empty array []. If there exists no value for date key it is
            // considered that the date in question is not yet loaded
            
            items={
                {'2018-11-20': [],
                '2018-11-1' :[],
                  '2018-11-21': [],
                  '2018-11-22': [{text: 'item 1 - any js object'}],
                '2018-11-23': [{text: 'item 2 - any js object'}],
                '2018-11-24': [],
                '2018-11-25': [{text: 'item 3 - any js object'},{text: 'any js object'}],
                '2018-11-27': [{text:'item 4 - any js object'}],
                '2018-12-1' :[],
                }}
            // specify how each item should be rendered in agenda
            renderItem={this.renderItem}
            // specify how empty date content with no items should be rendered
            renderEmptyDate={this.renderEmptyDate}

            renderEmptyData={this.renderEmptyDate}
            // specify your item comparison function for increased performance
            rowHasChanged={(r1, r2) => {return r1.text !== r2.text}}

            />
      </View>
    )
  }

  renderItem = (item, firstItemInDay) => {
    return (
      <View style={[styles.item]}>
        <Text>7pm - 12am</Text>
        <Text>Dishwasher</Text>
        <Text>Mama Mia's</Text>
      </View>
    );
  };

  renderEmptyDate = () => {
    return (
      <View style={styles.emptyDate}><Text>Test</Text></View>
    );
  };
}

/*const ScheduleNavigator = createStackNavigator({
    Schedule: {
      screen: Schedule
    }
  }, {
    // Default config for all screens
    title: 'Schedule',
    initialRouteName: 'Schedule'
  })

export default createAppContainer(ScheduleNavigator);*/

const styles = StyleSheet.create({
    headerText: {
      fontSize: 20,
      fontFamily: 'myriad-pro-condensed',
    },
    container: {
      flex: 1,
    },
    item: {
      backgroundColor: 'white',
      flex: 1,
      flexDirection: 'column',
      borderRadius: 5,
      padding: 10,
      marginRight: 10,
      marginTop: 17
    },
    emptyDate: {
      marginTop: 45,
      marginRight: 10,
      borderTopWidth: 2,
      borderTopColor: '#dddddd',
      height: 5,
    }  
})

**Comment by mauricekenji** [comment]
### My use case
In the Agenda view, I want to show the calendar date in an "EmptyDate" container that corresponds to the current date position. I.e. date on left (renderDay) matches date in EmptyDate container. Then onPress, I want to carry the date params over to the next screen to "Create a new event."

Just a heads up: I'm almost certain a more sound solution is out there, and I too await to see the cleaner code. But this might help you get unstuck at the moment.

### My current solution

**Code for Agenda component**
`<Agenda 
...
          renderEmptyDate={this.renderEmptyDate.bind(this)}
...
/>`

**Code for renderEmptyDate**
`  renderEmptyDate = foo => {
    const emptyDate = new Date(foo).toISOString().split('T')[0];

    return (
      <TouchableOpacity
        style={styles.emptyDate}
        onPress={async () => {
          await this.setState(
            { emptyDate },
            console.log(this.state.emptyDate),
          );
          console.log(foo, emptyDate, this.state.emptyDate);
        }}
      >
        <Text style={{ color: 'gray', paddingBottom: 4 }}>
          {emptyDate}
        </Text>
        <Text>Your container message here.</Text>
      </TouchableOpacity>
`

**Comment by rickcha** [comment]
Please take a look. I had the same problem and now it shows after this.

https://github.com/wix/react-native-calendars/pull/633/commits/d61e55c5b2be5dc1a73ca2c4b6ba22315b99c4d9

**Comment by efl7a** [comment]
Thanks @rickcha! This worked for me.
