### ISSUE TITLE
Agenda view scrolls to wrong date

### ISSUE THREAD

**Issue by uypao** [wix/react-native-calendars#693]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When selecting a date from a previous month, agenda view scrolls to the wrong date

## Expected Behavior

It should scroll to the correct date

## Observed Behavior

It seems like it is only happening when scrolling on Agenda view for more than one month and going back to the previous month using the calendar list

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.21.0
* `npm ls react-native`: 0.55.4

## Reproducible Demo

![calendar](https://user-images.githubusercontent.com/12945504/49331970-ef01a100-f56a-11e8-8e3d-12ca1a2a8394.gif)

**Comment by jGrossy** [comment]
same issue

**Comment by ManigandanRaamanathan** [comment]
Any update on this issue?

**Comment by dekameron22** [comment]
+1

**Comment by ciao666** [comment]
I think it's about offsets
