### ISSUE TITLE
(Calendar) is it possible trigger `substractMonth` & `addMonth` on demand ?

### ISSUE THREAD

**Issue by a-eid** [wix/react-native-calendars#696]
is it possible trigger `substractMonth` & `addMonth` for Calendar  on demand ? 
if not, would a PR be considered ?

**Comment by HWBN1** [comment]
You can use `currnet`
`  
// Initially visible month. Default = Date()
  current={'2012-03-01'}
`

**Comment by HWBN1** [comment]
You can use `current`

`  // Initially visible month. Default = Date()
  current={'2012-03-01'} `

**Comment by a-eid** [comment]
@HWBN1 the basic idea is that I want to style the arrow my self ( design required to do so ). 

could you include some snippets of how I might be able to do that?
