### ISSUE TITLE
How can I add button into calendar ?

### ISSUE THREAD

**Issue by huynguyen2903** [wix/react-native-calendars#698]
I want to add button into calendar like the picture (Button: "OK" & "Cancel"). Can you show me the way to do this, please ?
<img width="272" alt="screen shot 2018-12-05 at 6 42 25 pm" src="https://user-images.githubusercontent.com/40721082/49511461-d3293280-f8bd-11e8-82f9-27b67ad7eb4b.png">

**Comment by isoftpage22** [comment]
Hi I am looking for the answer, DO you have any solution ?
