### ISSUE TITLE
Publish examples to Expo

### ISSUE THREAD

**Issue by slorber** [wix/react-native-calendars#70]
Hi,

This lib is plain JS and does not require linking, so it's compatible with Expo/CRNA client.

It would be really nice to publish a CRNA app including this lib examples to Expo, this way users would be able to test the library features without having to install anything.

**Comment by sibelius** [comment]
https://github.com/brentvatne/react-native-calendars-example

**Comment by slorber** [comment]
Thanks I've opened a readme PR: https://github.com/wix/react-native-calendars/pull/71

It seems @brentvatne already did the job :) However when running the examples on Expo I got some crashes, don't know if this is related to Expo or this lib
