### ISSUE TITLE
How to limit calendar for One year. ex only 2019 calender

### ISSUE THREAD

**Issue by Rananjaya** [wix/react-native-calendars#701]
How to limit calendar for one year. ex - only 2019 calendar

**Comment by Rananjaya** [comment]
any ideas

**Comment by uddiefia** [comment]
there is a way for that but not the best solution try this. it worked for me 
first, u have to  create a state for month_change  inside the constructor 

```
constructor(props) {
super(props);
 this.state = {
           month_change: ""
            }
 }
```


then inside willMountfunction set currentdate 
```
componentWillMount() {
        this.getmonth();
}
```

getmonth function  
```
getmonth = async () => {
  try {
      var today = await new Date().getMonth() + 1;
      today=await parseInt(today,10);
     today=JSON.stringify(today);
     await this.setState({
      month_change:today
      })
  } catch (error) {
      console.log(error);
    }
  }
```

finally u have add conditional render 

inside the return 
```
{this.state.month_change == 1 || this.state.month_change == 2 ||
this.state.month_change == 3 ||
this.state.month_change == 4||
this.state.month_change == 5||
this.state.month_change == 6||
this.state.month_change == 7||
this.state.month_change == 8||
this.state.month_change == 9||
this.state.month_change == 10 ||
this.state.month_change == 11 &&
<Calendar
......  /> }
{this.state.month_change == 12 &&
<Calendar
current={'2019-12-01'}
......  /> }

```
u can change current={'2019-12-01'}  as u want  and plz make sure edit  onMonthChange inside the calendar 

```
onMonthChange={(month) => {
                  this.setState({ month_change: month.month });
                }}

```
and make sure ur phone date is set to 2019/../..  then this will work properly

**Comment by uddiefia** [comment]
> Having same issue here, at the moment I am setting a maximum and minimum date so it gets greyed out in other years

https://github.com/wix/react-native-calendars/issues/701#issuecomment-448485502
