### ISSUE TITLE
Functionality to specify available dates

### ISSUE THREAD

**Issue by hjaintech** [wix/react-native-calendars#704]
## Description
I need a way to give the calendar a list of dates which should be enabled/selectable and all other dates should be disabled. 
For example I have to show only 25th December 2018 and 26th December 2018 as enabled/selectable and rest all dates should not be selectable.

Is it possible currently ?

**Comment by SCasarotto** [comment]
You can see this was added here: https://github.com/wix/react-native-calendars/pull/67

All you need to do is `disabledByDefault={true}` and then:

```
markedDates={{
  '2018-12-25': { disabled: false },
  '2018-12-26': { disabled: false },
}}
```
