### ISSUE TITLE
How to change the color of Saturday and Sunday？

### ISSUE THREAD

**Issue by Rananjaya** [wix/react-native-calendars#714]
How to change the color of Saturday and Sunday？

**Comment by brlocky** [comment]
`initializeMarkedDates() {

        let markedDates = {}

        // Create an array with all days from _startDate to _endDate
        let currentDate = moment(_startDate)
        let endDate = moment(_endDate)
        while (currentDate <= endDate) {
            const day = currentDate.day()
            const isWeekend = (day === 6) || (day === 0)
            const currentDateFormatted = currentDate.format('YYYY-MM-DD')

            let markup = {}
            if (_today === currentDateFormatted) {
                markup.selected = true
            }

            if (isWeekend) {
                markup.disabled = true
            }

            markup.dots = []
            markedDates[currentDateFormatted] = markup

            currentDate = moment(currentDate).add(1, 'days')
        }

        this.setState({
            originalMarkedDates: markedDates,
        })
    }`

**Comment by himanshug16** [comment]
Hi @Rananjaya  have you got it working ?

**Comment by chenei** [comment]
Check this function:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L18

You can call it like this:
`getDisabledDates('2012-05-01', '2012-05-30', [0, 6])`
