### ISSUE TITLE
Agenda does not show well

### ISSUE THREAD

**Issue by Jeison12** [wix/react-native-calendars#715]
![screenshot_2019-01-08-22-47-23](https://user-images.githubusercontent.com/26725495/50875846-2ba98f00-1398-11e9-9f08-47ca2c68e4e5.png)

when entering the agenda it is normal, enter the details of an item and then go back and the days in the calendar are no longer displayed well

**Comment by bonlemuel** [comment]
Hi @Jeison12 ,

Try this one:

`theme={{
   'stylesheet.calendar.header': {
      monthText: {
      marginTop: 5,
      fontWeight: '200',
    }
  }  
}}`

You need to less some margin on the header (in case you've modified it).

**Comment by kailashvele** [comment]
Also, this happens on Android and not on iOS for me. Not able to understand the cause of the issue. It appears the calendar list is by default open and it later closed to just show current week in doing so its miscalculating. Also when you initially land the selected date circle is little cut on the bottom as it leaves space on top.

**Comment by jordan-tpz** [comment]
@kailashvele same for me

**Comment by onosol** [comment]
Happening on iOS for me.

**Comment by ariefwidiatmoko** [comment]
Same for me, It happens after reload screen because need to update render item

**Comment by Deepindera** [comment]
still happens
