### ISSUE TITLE
Day is disabled but still can be selected

### ISSUE THREAD

**Issue by vcalvello** [wix/react-native-calendars#72]
Marking some dates as disabled display them correctly but selectables.
Is that the intended behavior?

**Comment by tautvilas** [comment]
Hi, could you be more specific? It is up to you how you handle onDayPress. Marking day as disabled does not stop you from receiving day press events on these dates if that is what you mean

**Comment by vcalvello** [comment]
Yep, I would have expected they were not clickable if disabled, like a button. I think that's the most common scenario. Otherwise, how can achieve that behavior?

**Comment by MyGuySi** [comment]
I just ran into this issue too. My guess is we'll need to cross reference the selected date against some kind of lookup to determine if the day is disabled, not the friendliest way though. I'd suggest either disabling onDayPress events for disabled dates or something in the return value for that event that says whether it's disabled or not
