### ISSUE TITLE
Date with Multiple events doesn't update correctly

### ISSUE THREAD

**Issue by egeola** [wix/react-native-calendars#720]
## Description

I have multiple events per date. But when I delete one event in the array of events it only removes the last element.  Only when I click to another date( that triggers loadItems) and come back to the date, it resolves. 

I expect for the right event in a list of events for a date to be removed. 

## Environment
"react-native-calendars": "^1.21.0",

##Code
`       loadItems(day) {
         setTimeout(() => {
           for (let i = -15; i < 85; i++) {
             const time = day.timestamp + i * 24 * 60 * 60 * 1000;
             const strTime = this.timeToString(time);
             this.state.dataOOTD[strTime] = this.state.dataSource[strTime] || [];
           }

           const newItems = {};
           Object.keys(this.state.dataOOTD).forEach(key => {newItems[key] = this.state.dataOOTD[key];});
           this.setState({
             dataOOTD: newItems
           });
         }, 1000);
       }

  renderItem(item) {
    if (item.photo) {
      return (

        <View style = {styles.lineimage} >
          <TouchableOpacity onPress={() => this.showDetails(item)} underlayColor='#dddddd'>
            <Image style= {{height: 400}} source= {{uri:item.photo}} resizeMode = "contain"/>
          </TouchableOpacity>
        </View>
      );
    }
    return (
        <View style = {styles.lineimage}/>
      );
}

  renderEmptyDate() {
    return (
      <View style={styles.emptyDate}></View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.event_id !== r2.event_id;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split('T')[0];
  }

 render() {
    const startDate = moment().format()
    if (!this.state.loading){
        return (
          <Agenda
            items={this.state.dataOOTD}
            loadItemsForMonth={this.loadItems.bind(this)}
            minDate={moment().subtract(14, 'months').format()}
            selected={startDate}
            pastScrollRange={1}
            futureScrollRange={18}
            renderItem={this.renderItem.bind(this)}
            renderEmptyDate={this.renderEmptyDate.bind(this)}
            rowHasChanged={this.rowHasChanged.bind(this)}
            //monthFormat={'yyyy'}
            theme={{
              backgroundColor: 'white',
              agendaKnobColor: '#FFD4A2',
              dotColor: '#F99B00',
              selectedDotColor: '#FFFFFF',
              selectedDayBackgroundColor:'#9363BF',
              todayTextColor:'#9363BF',

            }}
            //renderDay={(day, item) => (<Text>{day ? day.day.toString() + day.month.toString()  : 'item'}</Text>)}
          />

        );
    }
    else{
      return (<View></View>);
    }

  }
`

**Comment by Trazmor** [comment]
Same problem
