### ISSUE TITLE
[Question] What If I just want to update `day` component whenever I need ?

### ISSUE THREAD

**Issue by jaydeep987** [wix/react-native-calendars#722]
## Description

I am using `CalendarList` for my app, and I use *custom* `dayComponent` for some purpose.
At first view I want to show normal day component (only date number). Then meanwhile I call api and wait for response. After response, I re-render my component, and so I add some more info in `dayComponent`. 
In short, I want to update (rerender) `dayComponent` when my component re-renders.

I found this code in `calendar/index.js`:

```
  componentWillReceiveProps(nextProps) {
    const current= parseDate(nextProps.current);
    if (current && current.toString('yyyy MM') !== this.state.currentMonth.toString('yyyy MM')) {
      this.setState({
        currentMonth: current.clone()
      });
    }
  }
```

Due to this, whole calendar does not rerender just because dates are same.

What if I just want to re-render `dayComponent` ?
Any Idea?

**Comment by anhkhoi** [comment]
The same question for me, how to re-render dayComponent? Thanks for any helps!!!

**Comment by HaswinVidanage** [comment]
Same here , I want to show the selected date in another colour.

**Comment by mickey-ichi** [comment]
@jaydeep987  @anhkhoi @HaswinVidanage **Please using `onPress={() => onPress(date)}` it work fine like this **
<img width="703" alt="Screen Shot 2019-08-12 at 12 52 18 AM" src="https://user-images.githubusercontent.com/13127169/62837607-880cbe00-bc9b-11e9-9559-bcbceca80130.png">

**Comment by pankaj1433** [comment]
Any Update on this issue. I'm unable to update dayComponent on props change.

**Comment by pankaj1433** [comment]
Changing reference of markedDates re-renders the dayComponent. With react hooks you can achieve this. Just watch the props that is supposed to re-render the dayComponent using useEffect.

I did this by:
`
    const [markedDates, setmarkedDates] = useState([]);
    useEffect(() => {
        const markedDates = { [moment().format('YYYY-MM-DD')]: { marked: true } };
        setmarkedDates(markedDates);
    }, [watcherFromProps]);

 <Calendar
 markedDates={Object.assign({}, markedDates)}
{...otherProps}  />
`

NOTE: It's a work around and not an appropriate solution.

**Comment by codingkapoor** [comment]
@pankaj1433  It doesn't work when you are trying to update the markedDates using setMarkedDates on month change!

**Comment by nikbelikov** [comment]
Same shit. Any hope for an answer here?

**Comment by Maddumage** [comment]
I used hooks and update state when day press. It just worked but it will re-render all day components and bu have a delay to show selected day with color. :(  Any other solutions? Please help

**Comment by teo029** [comment]
Same problem. When changing `markedDates`, all `dayComponent`s re-render and the selected day is shown with delay (mostly on Android). I am also using `useCallback` on the `dayComponent`, as recommended.

> I used hooks and update state when day press. It just worked but it will re-render all day components and but have a delay to show selected day with color. :( Any other solutions? Please help

**Comment by johhansantana** [comment]
It's been more than a year for this. At this moment we can assume it will not be fixed but as a workaround, you might be able to get away with unmounting and mounting the Calendar component with a loading state of some sort.

if `loading` hides `Calendar` show `Calendar` after some milliseconds. 

This method can be called when you press on a day and it should rerender everything, unfortunately, I can't seem to only rerender the day selected...

**Comment by tututututututu** [comment]
CalendarList  and use dayComponent  has the same question
