### ISSUE TITLE
Agenda doesn't working on specific iOS simulator (iPhone X)

### ISSUE THREAD

**Issue by GuillaumeRZ** [wix/react-native-calendars#724]
Hello,

Agenda component is not working properly on iPhone X simulator. But works well with everything else (5S, 6, XS Max). We tried on differents simulators, and real devices.

The EXACT same code is working well on everything, except iPhone X. There is a gif to understand :

![bug_react_native 1](https://user-images.githubusercontent.com/16371978/51612748-60821e00-1f22-11e9-925c-675a6941576f.gif)

I tried to change parent components but nothing happened (and like I said, it is working with other simulators). Is this possible that it is a pure bug, coming from screen height calculation ?

This is the `agendaComponent` and its styles associated :

```
<Agenda
        style={styles.agenda}
        theme={agendaTheme}
        items={this.state.placesAvailableItems}
        minDate={new Date()}
        firstDay={1}
        pastScrollRange={0}
        futureScrollRange={4}
        renderItem={item => (
          <View>
            <Text style={styles.eventTitle}>{item.title}</Text>
            <ValidButton
              text="Réserver la place"
              onPress={() => this.props.postReservation(item.reservationID)}
            />
          </View>
        )}
        renderEmptyData={() => (
          <View style={styles.noEventContainer}>
            <VanillaText
              style={styles.noEvent}
              centered
              text="Aucune place n'est disponible à cette date."
            />
          </View>
        )}
        markingType="custom"
        markedDates={this.state.placesAvailableMarkedDates}
        rowHasChanged={(r1, r2) => r1.text !== r2.text}
/>

const styles = StyleSheet.create({
  agenda: {
    width: "100%",
    marginTop: 25,
  },
  eventTitle: {
    paddingTop: 15,
    paddingBottom: 5,
  },
  noEventContainer: {
    flex: 1,
    alignItems: "center",
  },
});
```

This component is wrapped in a `parentComponentScreen` like that : 

```
<View style={styles.container}>
    <CategoryTitle text="Réserver une place :" />
    <View style={styles.agendaContainer}>
        <VanillaText centered text="2 places disponibles" />

        <ParkingAskerAskPlaceAgenda
            placesAvailable={this.state.placesAvailable}
            postReservation={this.postReservation}
        />
    </View>
</View>

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  agendaContainer: {
    flex: 1,
  },
});
```

Thank you for you quick help !

**Comment by mbardauskas** [comment]
Can you please try and create a minimal implementation to reproduce this behaviour? This repo contains the example project and I can't seem to be able to reproduce the bug in it.
Thanks

**Comment by GuillaumeRZ** [comment]
I am pretty new in mobile devlopment. Do you want a repository with minimal implementation or does it exist an online tool (like CodeSandBox) to run React-Native, Expo and iOS simulator ?

**Comment by GuillaumeRZ** [comment]
This issue can be close, I was using wrong parents views.

**Comment by mbardauskas** [comment]
Thanks for the update :-)
