### ISSUE TITLE
Marking Dates 

### ISSUE THREAD

**Issue by abn0rmal-d0ct0r** [wix/react-native-calendars#725]
## Description

Hello,
The dates that I mark are retrieved from a server. It is then made into an Object before assigning it to the Calendar.
Although the dates in 2018 ia marked, the ones in 2019 are not. 
Any suggestion as to why this happens?

Code: 
```
 .then((response) => response.json())
 .then((response) => {
       this.setState({ datesList: response.ActivityList })

       this.state.datesList.forEach(myFunction);
       function myFunction(value) {
           dates.push(new Date(value).getFullYear() + "-" + (new Date(value).getMonth() + 1) + "-" + new Date(value).getDate());
         }

        dates.forEach(myFunction);
        function myFunction(value) {
              datessss.push(new Date(value).getFullYear() + "-" + (new Date(value).getMonth() + 1) + "-" + new Date(value).getDate());
         }

         var obj = datessss.reduce((c, day) =>
               Object.assign(c, { [day]: { marked: true, dotColor: 'green' }} ), {});
               this.setState({ dottedDate: obj });
        .
        .
        .
   });
}

<Calendar
    current={this.state.currentDate}
    markingType={'simple'}
    markedDates={this.state.dottedDate}
    style={{
        borderWidth: 1,
        borderColor: 'gray',
        height: 350
    }}
    theme={{
        .
        .
        .
        .
     }}
     .
     .
     .
     />
```

## Expected Behavior

Expected to see all the dates retrieved to be marked.
## Observed Behavior

All retrieved dates except the ones in 2019 are marked

* `react-native-calendars@1.21.0`
* `react-native: 0.55.4`

Phone Used : 
`Samsung Galaxy S6 Edge`

![image](https://user-images.githubusercontent.com/32088497/51672032-82e26d00-1ff0-11e9-95e9-0e3a0f3e887e.png)
![image](https://user-images.githubusercontent.com/32088497/51672108-a9080d00-1ff0-11e9-8ddb-2b239cb1497d.png)

**Comment by AatiqUrRehman** [comment]
Hi, how do you make it run?
