### ISSUE TITLE
calendar view not refreshing

### ISSUE THREAD

**Issue by apppro123** [wix/react-native-calendars#726]
I have the problem that the calendar view doesnt refresh though my events which i give in markedDates change. I have to mention that i created my own Day component for that. Maybe there is the problem (maybe with ShouldComponentUpdate, the description is not very clear on that) but i dont think so.

Thanks for every response on this!!

**Comment by brlocky** [comment]
Hi, I also had that problem.

The `markedDates` property from Calendar is an object, a complex object. So by simple cloning it like `const newObject = { ...this.state.markedDates }` is not copying it, weird but this case is creating a reference, so because of this the Calendar was not refreshing.
Using JSON parse to enforce the new object creation worked fine.

`let calendarEvents = JSON.parse(JSON.stringify(this.state.originalMarkedDates))`

**Comment by apppro123** [comment]
Thank you for you help!

**Comment by evolquez** [comment]
@brlocky yes I'm using component state, my component re-render every time my state change, but the calendar wasn't.

For now your solution saved my day, I spend few hours trying to figure out what was wrong with my implementation even using object spread properties.

Thanks!

**Comment by umkhan65** [comment]
@brlocky Your solution works great

**Comment by fullstact69** [comment]
I have customized dayComponent. But after I get values from Json, Calendar is not refreshed. How can I fix this?

**Comment by dl-husky73** [comment]
Just want to add here as well.  This solution worked for me, thanks brlocky!  Thx to  archieherbias for sending this solution to my issue!  Great stuff.   

I simply changed my markedDates copy from straight hook copy to your suggestion, let newDates = JSON.parse(JSON.stringify(gMarkedDates)) and then resetting the hook once a parameter modified worked perfectly! Another problem solved! :) That closed the issue for me!

**Comment by vlade2008** [comment]
> I have customized dayComponent. But after I get values from Json, Calendar is not refreshed. How can I fix this?

Just add a `const markedDates = {
    };
    yourArray.forEach((data) => {
      Object.assign(markedDates, {
        [data.date]: {
          selected: your state if selected
        }
      });
    });`
`markedDates={markedDates}`
it will render the daycomponent my friend . I hope it will help you

**Comment by dagan-arbox** [comment]
it doesn't not seem to help me, did all suggestions.
on event, I change markedDates as @brlocky , but nothing change untill any press event on calendar.

**Comment by arunkmoury** [comment]
You can try this `this.setState({markedDates: {}}, function(){
this.setState({markedDates: newMarkedDates})
`
This is working every time anywhere in this plugin for this type of issue
@brlocky is also working fine

**Comment by Nehal-29** [comment]
@brlocky 
Your solution had worked for everyone.
Can you help me where I'm wrong here?

```
let getMarkedDates = () => {
        let dates = {[selectedDate]: {selected: true, disableTouchEvent: true, selectedDotColor: Colors.accent}}
        let markedDates = JSON.parse(JSON.stringify(dates));
        return markedDates
    };

    return(
        <View>
            <Calendar
                minDate={props.minimumDate}
                maxDate={props.maximumDate}
                onDayPress={({dateString}) => {
                    props.selectDate(dateString);
                }}
                disableMonthChange={false}
                firstDay={1}
                current={selectedDate}
                markedDates={getMarkedDates()}
                theme={getTheme()}
                renderHeader={renderCalendarHeader}

            />
        </View>
    );

```

whenever this selectedDate changes I want to re-render my calendar component.

**Comment by zhlee1997** [comment]
> let calendarEvents = JSON.parse(JSON.stringify(this.state.originalMarkedDates))

U are amazing @brlocky

**Comment by arnaudambro** [comment]
> You can try this `this.setState({markedDates: {}}, function(){ this.setState({markedDates: newMarkedDates}) `
> This is working every time anywhere in this plugin for this type of issue
> @brlocky is also working fine

JSON.parse(JSON.stringify()) didn't work for me, this reset and set state is tricky but it worked. Two hours lost on this ! But the lib is still great, thanks !

**Comment by walheredia** [comment]
Hi Guys, is there any way you can proivde an example with code? I've tried with all your sugestions here but it doesn't work.
I really appreciate all your help!

**Comment by arnaudambro** [comment]
```js
this.setState({ markedDatesToShow: {} }, () =>
  this.setState({
    markedDatesToShow: yourNewMarkedDates,
  })
);
```

**Comment by aleksandarbos** [comment]
@chenei can you provide any reasoning why you considered that this issue is supposed to be closed?

**Comment by aleksandarbos** [comment]
https://github.com/wix/react-native-calendars/issues/726#issuecomment-458659037 didn't work for me :/
i'm using `    "react-native-calendars": "^1.1260.0",     "react-native": "~0.63.4",`

I had a weird situation, if a particular date didn't have any entries, it would add the first mark and update the entry right away, showing updates on the calendar. But if a particular date had some entries, it wouldn't show updates unless i'd reopen the screen or force component rerender somehow.

my solution: after spending hours and hours on this, came to definitely not the greatest solution, but does the job. i've forced calendar re-rendering by adding `key={Math.random()}` which is forcing component rerendering now. this might cause some performance issues, but i couldn't find any better way of solving this.

**Comment by mrityunjai01** [comment]
I had similar problems, when I realised that markedDates prop accepted objects of the kind:
```
 markedDates={{
    '2017-10-05': {selected: true},
    '2017-10-06': {selected: true}
  }}
```
whereas I was passing in 
```
 markedDates={{
    '2017-10-5': {selected: true},
    '2017-10-6': {selected: true}
  }}
```
which is not what it wants. (Notice the difference between "05" and "5"

**Comment by 7hourspg** [comment]
import { View, Text, StyleSheet } from 'react-native';
import React, { useState, useEffect } from 'react';
import { Calendar, CalendarList, Agenda } from 'react-native-calendars';

const Calender = () => {
  const [selectedDay, setSelectedDay] = useState();

  return (
    <View style={{ flex: 1, backgroundColor: 'white' }}>
      <Calendar
        style={[styles.calendar, { height: 350 }]}
        onDayPress={(day) => {
          setSelectedDay({ selected: day.dateString });
        }}
        enableSwipeMonths={true}
        markedDates={{
          [selectedDay?.selected]: {
            selected: true,
            disableTouchEvent: true,
            selectedDotColor: 'orange',
          },
        }}
      />
    </View>
  );
};

export default Calender;


// it's working for me try this method
