### ISSUE TITLE
showWeekNumbers shifts dayNames

### ISSUE THREAD

**Issue by damikdk** [wix/react-native-calendars#727]
Thanks for awesome calendars! There is a problem with showWeekNumbers:

## Description

If ``showWeekNumbers={true}``, all dayNames is shifted relative to days in month

```
<Calendar
  style={{
    width,
  }}
  horizontal
  pagingEnabled
  showWeekNumbers
  calendarWidth={width}
  calendarHeight={calendarHeight}
  firstDay={1}
/>
```

## Expected Behavior

It should be level like it is without ``showWeekNumbers``: 

![img_070d4f3ecf73-2](https://user-images.githubusercontent.com/13000756/51985138-385c6700-24ae-11e9-8ffa-9d51161b9e7e.jpeg)

## Observed Behavior

Same code with ``showWeekNumbers={true}``: 

![img_070d4f3ecf73-1](https://user-images.githubusercontent.com/13000756/51985069-0ba84f80-24ae-11e9-82b1-833d9ee8a513.jpeg)

## Environment

Reproduced on iPad, iPhone and Android.

**Comment by damikdk** [comment]
It's really hard to fix this with custom styles

**Comment by damikdk** [comment]
I'll fix it this week, but if there is some advice for me, please let me know

**Comment by chenei** [comment]
Is it sill occur?
