### ISSUE TITLE
How to change the color of Saturday and Sunday？

### ISSUE THREAD

**Issue by dytiz** [wix/react-native-calendars#73]
![image](https://user-images.githubusercontent.com/10192599/27629483-14f56cc4-5c25-11e7-9a80-df2f4c6c19af.png)

**Comment by tautvilas** [comment]
hi, do you mean the day number or day name (e.g. mon, tue, wed) ?

**Comment by dytiz** [comment]
yes , i have solved it

**Comment by ubaycreative** [comment]
hi, @tautvilas how do you do that?

**Comment by tautvilas** [comment]
Hey, currently changing color of only few day titles are not possible. You can only change all day header color

**Comment by ubaycreative** [comment]
Thx for your answer, at least we know it

**Comment by Rananjaya** [comment]
How to change color of sundays

**Comment by bornd1989** [comment]
@harshaSenaratne Thanks very much. i easily solve it. thanks to you~

**Comment by himanshug16** [comment]
> 3\. I will update the iss

 Hi @harshaSenaratne , have you found a way to change the color of a specific type of day(like all sundays) throughout the year (without using the markdates) ?

**Comment by jaisal-crescibit** [comment]
I was able to achieve the desired output by using theme of Calendar. 
Official document sadly doesn't tell much about it 
[Documentation](https://wix.github.io/react-native-calendars/docs/Components/Calendar#theme).

Code sample:

```
theme={
   {
     "stylesheet.calendar.header": {
          dayTextAtIndex0: {color: "red"},      <--- Mon
           ...
          dayTextAtIndex6: {color: "green"},      <--- Sun
       }								
   }
}
```
