### ISSUE TITLE
Warning: ReservationListItem.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.

### ISSUE THREAD

**Issue by mauricioscotton** [wix/react-native-calendars#730]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I'm having a weird behaviour when just displaying information on the Agenda.
Every item rendered in the Agenda, even when I just use a <Text> element shows this error:
_Warning: ReservationListItem.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false._
![image](https://user-images.githubusercontent.com/34411735/52205499-2b08f900-286f-11e9-8584-6b7010704fc0.png)
Every time I scroll this list, it generates hundreds of this warnings..
I would like to know how to get rid of them.. 

## Expected Behavior
No Warnings.

If there's an error message, please paste the *full terminal output and error message* in this code block:

![image](https://user-images.githubusercontent.com/34411735/52205704-d914a300-286f-11e9-8fff-2440f7d09fa9.png)
Sorry, I had to put a Screenshot

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: └─ react-native-calendars@1.22.0
* `npm ls react-native`:└─ react-native@0.57.8

Also specify:
1. Phone/emulator/simulator & version: Emulator: Nexus 5 & Phone: Samsung J5 Prime

## Reproducible Demo
```
export const agendaRenderItem = (item) =>{
    return (
        <View>
            <Text>TESTE</Text>
        </View>
    );
}

export const agendaRenderEmptyDate = (item) =>{
    return (null);
}

export const BookingAgendaScreenView = ($ctrl) => {
    if ($ctrl.state.loading){
        return (<Loading />);
    }
    return (
        <Agenda 
            items={$ctrl.state.agendaItems}            
            renderItem={agendaRenderItem}
            renderEmptyDate={agendaRenderEmptyDate} 
            renderEmptyData={agendaRenderEmptyDate}
            rowHasChanged={$ctrl.agendaRowHasChanged}
        />
    );
}
```
Just attach const BookingAgendaScreenView to any component.

**Comment by dl-husky73** [comment]
I am running into this issue.  How did you resolve as I don't see an update?  Thanks in advance.
