### ISSUE TITLE
Horizontal scroll in Calendarlist calendarWidth

### ISSUE THREAD

**Issue by Jeeva111** [wix/react-native-calendars#732]
Horizontal scroll in Calendarlist but not properly render when i'm set calendarWidth
<CalendarList
  // Enable horizontal scrolling, default = false
  horizontal={true}
  // Enable paging on horizontal, default = false
  pagingEnabled={true}
  // Set custom calendarWidth.
  calendarWidth={300} <= Not rendering properly
/>
![screenshot-2019-02-11_10 00 18 429](https://user-images.githubusercontent.com/25759317/52546304-028b7c80-2de4-11e9-9730-1168406dd019.png)
![screenshot-2019-02-11_10 00 21 831](https://user-images.githubusercontent.com/25759317/52546305-028b7c80-2de4-11e9-946d-a7032bb746ad.png)
![screenshot-2019-02-11_10 00 25 224](https://user-images.githubusercontent.com/25759317/52546306-03241300-2de4-11e9-80d8-cea445ee6cd3.png)

**Comment by damikdk** [comment]
try to add style prop:

```
<CalendarList
  style={{
    width,
    overflow: 'hidden',
  }}
  horizontal={true}
  pagingEnabled={true}
  calendarWidth={width} <= Not rendering properly
/>
```

**Comment by Jeeva111** [comment]
Works Good but i want to display like this
![calendar](https://user-images.githubusercontent.com/25759317/52556767-87da5580-2e13-11e9-803e-c30e3608fe1c.jpg)

**Comment by damikdk** [comment]
Oh, I got it. You want to centred month with paging, but paging or centering doesn't work? Can you give more information (GIF would be nice)

btw, I'm not a contributor in this project, but my experience tells me that if you want exactly the same design (with swipe gestures and fancy animations for both Android/iOS), there is some issues.

**Comment by Jeeva111** [comment]
Everything works good i want that design means center aligned calendar previous and next months red marked area
![new_calendar](https://user-images.githubusercontent.com/25759317/52562698-5b2f3980-2e25-11e9-8515-7bd939ef2bee.jpg)

Original Gif

![ezgif com-optimize](https://user-images.githubusercontent.com/25759317/52562404-6df53e80-2e24-11e9-8fa0-0a5965bfd7d1.gif)

**Comment by 0x01001** [comment]
same issue 
```
<CalendarList
	horizontal
	pagingEnabled
	calendarWidth={screen.width - 20}
```

![1](https://user-images.githubusercontent.com/3379258/68541914-0fbbb300-03d8-11ea-84a5-b6aabc9c4443.png)

**Comment by kubanac95** [comment]
@Jeeva111 have you managed to accomplish this? I have a similar issue I want to tackle

**Comment by renzo-c** [comment]
Hello @Jeeva111 , Did you find a solution for this issue?

I experienced the same difficulty yesterday, but after applying the following styles it worked. However, I was able to do this because my background is always from left to right.

style={{
          width:Dimensions.get('window').width,
          alignSelf: 'center',
        }}
        theme={{
          calendarBackground: "transparent"
        }}

Calendar before:
![calenda_before](https://user-images.githubusercontent.com/28744826/117468074-f1297000-af19-11eb-9628-25922dae1cf8.gif)

Calendar after:
![calendar_after](https://user-images.githubusercontent.com/28744826/117468096-f686ba80-af19-11eb-99db-8a9753ffb0b2.gif)

**Comment by agdambagdam** [comment]
> Everything works good i want that design means center aligned calendar previous and next months exactly red marked area ![new_calendar](https://user-images.githubusercontent.com/25759317/52562698-5b2f3980-2e25-11e9-8515-7bd939ef2bee.jpg)
> 
> Original Gif
> 
> ![ezgif com-optimize](https://user-images.githubusercontent.com/25759317/52562404-6df53e80-2e24-11e9-8fa0-0a5965bfd7d1.gif)



> Everything works good i want that design means center aligned calendar previous and next months exactly red marked area ![new_calendar](https://user-images.githubusercontent.com/25759317/52562698-5b2f3980-2e25-11e9-8515-7bd939ef2bee.jpg)
> 
> Original Gif
> 
> ![ezgif com-optimize](https://user-images.githubusercontent.com/25759317/52562404-6df53e80-2e24-11e9-8fa0-0a5965bfd7d1.gif)

I also want this type of design please help me.
