### ISSUE TITLE
Select item in Agenda

### ISSUE THREAD

**Issue by baiofer** [wix/react-native-calendars#734]
## Description

It is possible, in Agenda, when I have presented all items of one day to select one in order to go to another screen passing this item?

**Comment by Polelo-Monareng** [comment]
Yes @baiofer 
I haven't used this package yet. So I was just going through the props and had the same question.

So to achieve this you use renderItem. Make your renderItem touchable, that way and depending on the navigation you're using you can push a new screen with params being that item.

I haven't tried it yet but 100% sure it will work.
