### ISSUE TITLE
How to update selected date and scroll to newly selected state?

### ISSUE THREAD

**Issue by BigPun86** [wix/react-native-calendars#735]
## Description

I am using the Agenda component and now i would like to change the state "selected" and update the component. Currently changing the selected state does not change anything.

## Expected Behavior

After updating selected state calendar list should jump/scroll to the new selected date. Actually the same behaviour when pressing a date in the calendar.

## Observed Behavior

Nothing happened! When debugging after updating selected state it will jump into render() but Agenda wont be updated...

## Environment

* `react-native-calendars@^1.22.0`:
* `react-native@0.56.0`:

Also specify:

1. Phone/emulator/simulator & version:

- iPhone XR 
- iPhone 7 (Simulator)

**Comment by lucamir** [comment]
I have the same problem. 
I would like to link a day from another screen with a navigation param, and set the agenda **selected** props with that.
it works for the first render, but if i try again with another day the component don't re-render. Any solution?

**Comment by ricardoribas** [comment]
@lucamir @BigPun86  after debugging the library it seems that the `selected` is only consumed when the components renders for the first time. However, you can hack that selected value by adding a $ref to the component and update it yourself. However, there is a method inside the component that makes extra logic (scrolling to be more specific).

**Comment by manodupont** [comment]
Any progress on this ?

**Comment by rdewolff** [comment]
Looking to use that feature too.

**Comment by JosephVasse** [comment]
Hi, currently stuck with the same problem : i'm updating the "selected day" but the Agenda doesn't re-render. Any new ideas ? 
Thanks

**Comment by JosephVasse** [comment]
Ok, i managed to make it work. 

As i'm kind of new to react native this solution might not be the best possible, but it seems to work. 

Here it is : 

in my <Agenda> Component i added a "key" prop. This prop's value is the "selectedDay" prop. 
Each update in the "key" prop triggers an update of the <Agenda> component.

**Comment by raaannzzz** [comment]
Thanks, @JosephVasse this works for me as well

**Comment by FernBurn** [comment]
In case you're using this with React Navigation, to get the date to reset when the screen with the calendar comes into view, you can use

```
useFocusEffect(
    useCallback(() => {
      return () => setKeyValueState(keyValue + "");
    }, [keyValue])
  );
```
