### ISSUE TITLE
CalendarList surrounded by ScrollView 

### ISSUE THREAD

**Issue by erickbank** [wix/react-native-calendars#738]
## Description

Only on Android when the Vertical calendarList is surrounded by a ScrollView and it has a futureScroll bigger than 10 and any value on pastScroll it starts to show blank space instead of the calendar.

## Expected Behavior

CalendarList should bring the pastScroll Months and futureScroll Months right even if inside an ScrollView as it happens on IOS

## Observed Behavior

pastScroll Months aren't showing , just a blank space on it and futureScroll Months  only shows until 10 months and after it shows blank space too.
 
## Environment

* `npm ls react-native-calendars`: react-native-calendars@1.22.0
* `npm ls react-native`: react-native@0.57.8 

## Reproducible Demo

Just surround calendarList inside a ScrollView and put futureScroll props bigger than 10

**Comment by Shedav** [comment]
The same issue

**Comment by theyanniss23002** [comment]
this problem is relevant. i also face vertical calendar issue when using bottom sheet from gorhom/react-native-bottom-sheet
