### ISSUE TITLE
On Android devices September 2018 is shown with 29 days rather than 30

### ISSUE THREAD

**Issue by SteveGreenley** [wix/react-native-calendars#739]
## Description

On Android devices September 2018 is shown with 29 days rather than 30. This is a fundamental issue with the use of 'new Date(year,month,0).getDate()' to find the number of days in a given month. The Javascript engine used by React Native on Android has a bug.

Please note, the problem does not occur when using a Javascript debugger, since that does not use the Javascript engine that is linked into the app.

## Expected Behaviour

In an Android app using CalendarList, display the month of September 2018. It should have 30 days.

## Observed Behaviour

The month of September 2018 is shown with 29 days. The following years also show the wrong number of days for September: 1900, 1906, 1917, 1923, 1928, 1934, 1945, 1951, 1956, 1962, 1973, 1979, 1984, 1990, 2001, 2007, 2012, 2018, 2029, 2035, 2040, 2046, 2057, 2063, 2068, 2074, 2085, 2091, 2096,

There are more but space is limited.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.22.0
* `npm ls react-native`: 0.53.0

Also specify:

1. Phone/emulator/simulator & version: 
Android simulator (Nexus 5X API 23, Android 6.0)
Xiaomi Mi A2, Android Pie
Samsung Galaxy S9

N.B. There is a small possibility that this issue is related to the locale; something like the beginning of Daylight Savings Time. If you have trouble reproducing the issue, please note that I'm using devices in New Zealand where Daylight Savings Time begins on September 30th.

The following code snippet can be used to identify which months are affected:

function totalDaysInMonth(year,month) {
  return [31, (((year%4==0)&&(year%100!=0))||(year%400==0)) ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month]
}

let problem=false
for (var y=0;y<4000;y++) {
  for (var m=0;m<12;m++) {
    d1 = new Date(y,m+1,0).getDate()
    d2 = totalDaysInMonth(y,m)
    if (d1!==d2) {
      console.log('!!! total days calc problem year',y,' month',m)
      problem=true
    }
  }
}
if (!problem) {
  console.log('!!! total days calc no problem')
}

## Reproducible Demo

This problem can be reproduced using the example app that comes with react-native-calendars. Just deploy it to an Android device or simulator.

**Comment by Inbal-Tish** [comment]
Closing together with PR #740
