### ISSUE TITLE
React and React Native Dependencies Set to 0.44

### ISSUE THREAD

**Issue by brettlaforge** [wix/react-native-calendars#74]
I'm creating a new project with the following versions of react and react-native:

react: 16.0.0-alpha.12
react-native: 0.45.1

But this project has dependencies for a specific version of react and react-native:

react: 16.0.0-alpha.6
react-native: 0.44.0

Is there anything that this project uses that is only available in this version of react and react-native? Do you figure I'm safe to use the calendar with a newer version of react and react-native?

Could this be set to:

react: ^16.0.0-alpha.6
react-native: ^0.44.0

**Comment by sibelius** [comment]
I think we can remove

    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0"

from devDependencies

and keep them on peerDeps

**Comment by brettlaforge** [comment]
I think I might still get the warnings in 'npm' until 'react-native-calendars' allows a peer dependency that is equal to or higher than '0.44.0',

I get:
```
npm install
npm WARN react-native-calendars@1.4.0 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-native-calendars@1.4.0 requires a peer of react-native@0.44.0 but none was installed.
```
Even though my project has react and react-native they are just newer versions.

**Comment by forki** [comment]
is 0.44 really needed? can you allow 0.42 and higher?

**Comment by tautvilas** [comment]
I think it should work with higher versions fine, will need to fix packcage.json

**Comment by forki** [comment]
what about 0.42? I'm stuck with that version for now until we find a fix for https://github.com/facebook/react-native/issues/13780

would help me a lot!

**Comment by tautvilas** [comment]
If it does not work with 0.42 it might be issue with RN itself... If you can pin down the problem I can review and merge a PR.

**Comment by forki** [comment]
npm already complains about wrong peer deps...

**Comment by tautvilas** [comment]
removed react peer deps, there should not be any warning anymore
