### ISSUE TITLE
MarkedDates not showing in CalendarList

### ISSUE THREAD

**Issue by udarts** [wix/react-native-calendars#741]
Hi All,

I am having trouble with markedDates in the CalendarList not showing.

I only use the CalendarList component, no other component.

This is what the CalendarList component looks like, when I implement it:

``` javascript
<CalendarList
    horizontal={true}
    pagingEnabled={true}
    pastScrollRange={1}
    markingType={'period'}
    markedDates={{ 
        '2019-02-16': { marked: true },
        '2019-02-17': { marked: true },
        '2019-02-19': { marked: true },
        '2019-02-20': { marked: true },
        '2019-02-21': { marked: true },
        '2019-02-23': { marked: true },
        '2019-02-24': { marked: true }
    }}
    // markedDates={this.state.markedDates}
/>
```

This doesn't show any marked dates, it seems similar as to: https://github.com/wix/react-native-calendars/issues/49#issue-233604431 

But even when trying to add it to the CalendarList directly has no effect.

I am using:

react: 16.7.0
react-native: 0.58.3
react-native-calendars: 1.22.0

Any idea?

**Comment by robertobrogi** [comment]
Hi, any news about that? i have the same problem.... thanks

**Comment by chenei** [comment]
Do you still have a problem?
