### ISSUE TITLE
make some changes in agenda calendar behaviour and style

### ISSUE THREAD

**Issue by adirzoari** [wix/react-native-calendars#742]
Hey,
I want to make some changes in Agenda

1.  to show only the items of select day. when scrolling, it will not show the items on next day, so I need also disable move to other day when scroll.
2. show the items in horizontal.
Im looking to make this example (photo taken from dribbble),
when press on select day it will show the times of this day.
<img width="376" alt="screen shot 2019-02-19 at 23 24 05" src="https://user-images.githubusercontent.com/20258998/53049682-48a9a580-34a0-11e9-9acc-341d9e56318b.png">

**Comment by anastely** [comment]
Are you achieve it?
