### ISSUE TITLE
How to Disable the day of the week. like monday, all monday of month is disable, please help!

### ISSUE THREAD

**Issue by vinsofts-dungntr** [wix/react-native-calendars#751]
How to Disable the day of the week. like monday, all monday of month is disable

**Comment by willianpassarelli** [comment]
use a library MomentJS to find out the day of the week
```
onDayPress={day => {
   const dayWeek = moment(day.dateString).locale('pt-br').format('ddd');
   console.log(dayWeek);
}
```

**Comment by chenei** [comment]
We now support new props:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L75
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/calendars.js#L144
