### ISSUE TITLE
styling weekNumber

### ISSUE THREAD

**Issue by f-it-360** [wix/react-native-calendars#755]
Hello,
is it possible to style the weekNumber (color, size)?

Thanks and best

Qung

**Comment by bkniffler** [comment]
Looking at the code, it seems like it just uses the `Day` component, thus it uses day styles (with `state=disabled` style). 

Ergo, we will have to PR if we want that. Maybe I'll find the time to make this happen (maybe adding `state="weeknumber"`), no promises though.
