### ISSUE TITLE
Show complete month in agenda instead of current week

### ISSUE THREAD

**Issue by ismailkhan89** [wix/react-native-calendars#756]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Want to have Agenda with complete month in strip on top instead of one week can any one help me in this regards. i know there's an option to scroll month but i want to have initially show whole month 

## Expected Behavior

I want to have this kind of screen 
![image](https://user-images.githubusercontent.com/47290526/53623117-ef6b1000-3c1d-11e9-9a09-62be5540fde6.png)

![image](https://user-images.githubusercontent.com/47290526/53631479-6f9c7000-3c34-11e9-91d8-30d622ee08b4.png)

Any one have done it kindly help me in this regards

**Comment by SmirnovM91** [comment]
+1

**Comment by chenei** [comment]
Please check this prop:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js#L173
