### ISSUE TITLE
CalendarList does not update / re-render when changing firstDay

### ISSUE THREAD

**Issue by ferrannp** [wix/react-native-calendars#763]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I have a setting where user can change the first day of the week between: Monday, Sunday and Saturday. For that, I pass the prop `firstDay`.

## Expected Behavior

If the user changes the setting, the calendar to update. I added `componentWillReceiveProps` and I tried to `this.forceUpdate` but no luck.

## Observed Behavior

Calendar does not change the firstDay after the first render, you need to leave the screen / unmount the component and do it again.

I think this problem is similar to https://github.com/wix/react-native-calendars/issues/501.

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars: 1.21.0
react-native: 0.58.6

iPhone X simulator 12.1

## Reproducible Demo

```js
<CalendarList
  ref={c => {
    this.calendarList = c;
  }}
  onDayPress={this._goToDay}
  pastScrollRange={24}
  futureScrollRange={1}
  selected={today}
  markedDates={{
    ...this.state.markedDates,
    [today]: {
      selected: true,
      marked: !!this.state.markedDates[today],
    },
  }}
  firstDay={this.props.firstDay}
/>
```

**Comment by agentmusic** [comment]
+1

**Comment by gerardramospear** [comment]
Same issue here, what does the current calendar screen need to re-render/update?
