### ISSUE TITLE
How to show current month's name in Agenda component

### ISSUE THREAD

**Issue by dani-mp** [wix/react-native-calendars#765]
Is there a way of showing the current month when the component is in Agenda mode? Showing only the week of the currently selected day is not enough to give the proper context to the user, in my opinion.

**Comment by crice88** [comment]
I am assuming you are asking that if I have the week of 3/10 - 3/16 selected, you'd like to see agenda items that extend beyond these dates?

**Comment by danielmartinprieto** [comment]
No, sorry, just re-read my comment and it wasn't clear enough. I meant the name of the month of the selected day.

**Comment by crice88** [comment]
Are you trying to have it render with the header?? I know you could use the `renderDay` prop to create your own 'day' component. Then include the month that way. Haven't found a way to modify the weekly header...

**Comment by danielmartinprieto** [comment]
Yeah, I don't know if as a header, as you can put the whole component within a navigation stack, but definitely I think it lacks a way of showing the current month somewhere, either on the component where you can select a day, or grouping the days in the list, as iOS does in its native calendar.

**Comment by afacar** [comment]
This is exactly what I need too. Is there any solution yet for this?

**Comment by fa16mscs0004** [comment]
I have the same issue ..any progress on this ?

**Comment by afacar** [comment]
I tried a couple of tricks to show only the month in the header but no success yet :< Any help is still appreciated.

**Comment by jordan-tpz** [comment]
Hi,

I've achieved this issue using `onDayPress` and moment.

```
<Text>{this.state.currentMonth}</Text>
<Agenda
 .......
 onDayPress={this.onUpdateSelectedDate}
/>
```

```
onUpdateSelectedDate(date) => {
this.setState({ currentMonth: `${moment(date.dateString).format('MMMM')`
}
```

**Comment by JordanProtin** [comment]
Hi,

I've achieved this issue using `onDayPress` props and [moment](https://momentjs.com/).

```
<Text>{this.state.currentMonth}</Text>
<Agenda
 .......
 onDayPress={this.onUpdateSelectedDate}
/>
```

```
onUpdateSelectedDate(date) => {
  this.setState({ currentMonth: `${moment(date.dateString).format('MMMM')}` })
}
```

**Comment by afacar** [comment]
@JordanProtin Very nice and practical solution. Then, how can you hide the header. It takes a lot of space and not very necessary in my case.

**Comment by JordanProtin** [comment]
@afacar Something like this ?

```
<Agenda
.......
  theme={{
    'stylesheet.calendar.header': {
      header: {
        height: 0
      },
      week: {
        height: 0
      }
    }
  }}
/>
```

**Comment by afacar** [comment]
@JordanProtin I tried but it doesn't hide the header :/

**Comment by jordan-tpz** [comment]
@afacar I see this feature is not implemented.. Currently, you should use this header using agenda component..

**Comment by paulica40** [comment]
how did you put 2 components <Text>{this.state.currentMonth}</Text>
<Agenda
 .......
 onDayPress={this.onUpdateSelectedDate}
/>
in the same return statement?

i've wraped them in <View> still not working

**Comment by erdenayozkanl** [comment]
Hi, just you need to delete monthFormat.

**Comment by snoop24** [comment]
> @afacar Something like this ?
> 
> ```
> <Agenda
>   .......
>   theme={{
>     'stylesheet.calendar.header': {
>       header: {
>         height: 0
>       },
>       week: {
>         height: 0
>       }
>     }
>   }}
> />
> ```

But if the user change month while scrolling, this month state will not change.

**Comment by bilalahmad-greelogix** [comment]
I resolved this problem by calling onDayChange callback of Agenda component. This gives us an object namely "day". The object day contains "month" object that represents current month number.
Code I used

```
<Agenda
    ....
    onDayChange={(day) => {
        setCurrentMonth(day.month);
     }}
/>
```
