### ISSUE TITLE
Change background color of selected dates

### ISSUE THREAD

**Issue by AnchalMulchandani** [wix/react-native-calendars#766]
I want to change the selected Day background color, but in circle form instead of period.

**Comment by mdwatson19** [comment]
if you hold the selected date in state, then onDayPress you can pass the selected day object into that state and then it will show up.

Here's an example:
`constructor(props) {
        super(props);
        this.state = {
          dateSelected: ''
        };
      }

<Calendar
                    onDayPress={(day) => {
                        this.setState({
                            dateSelected:{[day.dateString]:{selected: true, selectedColor: '#466A8F'}}
                        },() => {
                            console.log(this.state.dateSelected)
                        })
                    }}

markedDates={this.state.dateSelected}
`

**Comment by mdwatson19** [comment]
if you hold the selected date in state, then onDayPress you can pass the selected day object into that state and then it will show up.

Here's an example:
```javascript
constructor(props) {
super(props);
this.state = {
dateSelected: ''
};
}


<Calendar
onDayPress={(day) => {
this.setState({
dateSelected:{[day.dateString]:{selected: true, selectedColor: '#466A8F'}}
},() => {
console.log(this.state.dateSelected)
})
}}

//set the state of the day you are selecting. It has to be an object like above because the 'markedDates' property is expecting an object.

markedDates={this.state.dateSelected}

//Pass in the selected date state as seen above. You can customize the properties of the date when you save the state onDayPress.
```

**Comment by sajibsaha4647** [comment]
Thanks you very much
