### ISSUE TITLE
Agenda loadItemsForMonth calls two time and gives wrong date

### ISSUE THREAD

**Issue by ManishAhire** [wix/react-native-calendars#769]
## Description

Following are the issues in my app :- 

1. First time `loadItemsForMonth` calls twice.
2. On scroll month `loadItemsForMonth` gives wrong date.
3. On press date, `loadItemsForMonth` method call. 

## Expected Behavior

1. First time `loadItemsForMonth` call only one time and it should return the exact date.
2. On scroll month `loadItemsForMonth` return exact the date of visible month.
3. On press date, calls only `onDayPress` not `loadItemsForMonth`.

## My Code

```
<Agenda
        items={this.state.items}
        loadItemsForMonth={day => this.loadMonthData(day)}
        onDayPress={day => this.onDatePress(day)}
        renderItem={this.renderItem.bind(this)}
        renderEmptyDate={this.renderEmptyDate.bind(this)}
        rowHasChanged={this.rowHasChanged.bind(this)}
        refreshing={false}
        
/>

loadMonthData(day) {
    console.log("Month date :- ", day);
}

onDatePress(day) {
    console.log("On date press :- ", day);
}
```

**Comment by jhonatansaman** [comment]
any solution?

**Comment by dophlin** [comment]
+1

**Comment by elisson** [comment]
+1
any solution?

**Comment by foxfl** [comment]
+1

**Comment by Plaoo** [comment]
+1

**Comment by fthkrtl** [comment]
same issue

**Comment by ConnectedReasoning** [comment]
Happens to me too. Exactly as described It seems to skip back exactly 60 days

**Comment by GladeyMs** [comment]
+1

**Comment by MrFaisal100** [comment]
did anyone manage to solve this?

**Comment by madhudskumar** [comment]
+1

**Comment by TheEarlyNerd** [comment]
Same issue.

**Comment by TheEarlyNerd** [comment]
So...I tried to debug the error myself. I don't like messing in module code for risk it will break on updates, and I don't understand the issue well enough to send a pull request, but when I add the prop  ```
onVisibleMonthsChange={months => {
        console.log('now these months are visible', months);
      }}
```
it shows that an additional month is being added the the "months" array. Then the `onViewableItemsChanged` is being called for some reason and setting the component state to `months[0]`. I changed the function to select `months[1]` and it appears to work find for now. I don't know why this is happening, but if someone on the core team is going to fix the issue, I hope this will be a lead!

**Comment by snoop24** [comment]
Any solution??

**Comment by FadiAboMsalam** [comment]
Any solution to this ?

**Comment by Arslan106** [comment]
still no solution?

**Comment by meliodev** [comment]
Yep same issue for me

**Comment by hnrazevedo** [comment]
Any news on the case?

**Comment by ViniciusGularte** [comment]
same problem here, any news?

**Comment by yamila-fraiman** [comment]
Same here!

**Comment by johnpanos** [comment]
Also same here...

**Comment by nickdalts** [comment]
Same!

**Comment by JosiasBatista** [comment]
I have the same problem here!

**Comment by merouan95** [comment]
Same !

**Comment by albionaberisha** [comment]
I have the same problem!

**Comment by insidewill** [comment]
Anyone?

**Comment by renatomserra** [comment]
Also facing this

**Comment by wuhao930406** [comment]
me too, Also facing this in latest version

**Comment by AidenPou** [comment]
still same issue in jan 2025
