### ISSUE TITLE
Disable date that outside some range

### ISSUE THREAD

**Issue by hmtri1011** [wix/react-native-calendars#772]
Can I have a way to disable all days that outside (before or after) one or many ranges of date?
For example, I have 
```
const availableDateRange = [
  {
    startDate: '2019-03-18',
    endDate: '2019-04-01'
  },
  {
    startDate: '2019-04-18',
    endDate: '2019-04-28'
  },
  {
    startDate: '2019-05-01',
    endDate: '2019-06-01'
  }
]
```
There has 3 range of date, I want to disable all days outside 3 above range and only allow to select the date that in 1 of 3 range above.
Thanks

**Comment by praveen7557** [comment]
@hmtri1011 Did you find the solution for this?

**Comment by hmtri1011** [comment]
@praveen7557 Yes, I custom base on their API, you can take a look at these link
https://gist.github.com/hmtri1011/e10f21b023d0450015e4c3db1f5ee2bb

**Comment by praveen7557** [comment]
@hmtri1011 Thanks. By any chance, Do you know how to select range like start date and end date using this library?

**Comment by hmtri1011** [comment]
@praveen7557 my custom Calendar has done it for you, you can select start date and select end date, then it will select all dates between selected start date and end date.

**Comment by praveen7557** [comment]
@hmtri1011 Ohh Cool. I will look into it. Thanks.
