### ISSUE TITLE
how can i hide month title ?

### ISSUE THREAD

**Issue by WMMAN** [wix/react-native-calendars#773]
### the only one i see ,so how to hide the title ?

// Month format in calendar title. Formatting values: http://arshaw.com/xdate/#Formatting
  monthFormat={'yyyy MM'}

**Comment by nickjanssen** [comment]
This works for me in the `theme` prop:
```
{
    "stylesheet.calendar.header": {
      header: {
        height: 0,
        opacity: 0
      }
}
```

**Comment by WMMAN** [comment]
> This works for me in the `theme` prop:
> 
> ```
> {
>   "stylesheet.calendar.header": {
>     header: {
>       height: 0,
>       opacity: 0
>     }
>   }
> }
> ```
thanks,it‘s a good way

**Comment by n-fukukawa** [comment]
Try below.
```tsx
<Calendar customHeaderTitle={<></>} />
```
react-native-calendars@1.1306.0
