### ISSUE TITLE
Header of Last month of Agenda not rendering correctly

### ISSUE THREAD

**Issue by otaviogaiao** [wix/react-native-calendars#778]
## Description

I have an Agenda that shows the months of the year.
It works well on iOS, but on Android, whenever I Choose a day of the last month of the year (December), The header doesn't render correctly. I tried to find in the code what could be causing it, but had not success. Also, it happens only in a few devices:

Tested on:

Galaxy S7 - Works correctly
Xiaomi Redmi note 3 - Works correctly
Galaxy s9+ - Doesn't work
Google Pixel 2 XL emulator - Doesn't work

## Expected Behavior

Open a day in the last month of the Agenda, Header should render correclty.

![Simulator Screen Shot - iPhone XR - 2019-03-26 at 13 51 36](https://user-images.githubusercontent.com/3965485/55016852-5c2fbb00-4fce-11e9-9576-07999727e75f.png)

## Observed Behavior

![Screenshot_1553618995](https://user-images.githubusercontent.com/3965485/55016729-18d54c80-4fce-11e9-93d8-2be2d0b9b024.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  react-native-calendars@1.22.0
* `npm ls react-native`: react-native 0.57.1 (Expo SDK 32)

**Comment by Twipped** [comment]
I'm having this problem as well, both in 1.21 and in 1.145. I'm not sure what caused it to start happening, since I noticed it after opening a project I hadn't worked on in a few months. It only happens for the current month, if I scroll the agenda up into the previous month then the correct week gets displayed.

**Comment by budo60** [comment]
Having the same issue , it seems if you are not on the current month but before or after the header is showing the name of the month

**Comment by aik117** [comment]
I have same issue on first and last month of agenda.

**Comment by AliMonam** [comment]
I have the same issue on the first and last month of the agenda.
