### ISSUE TITLE
react-native-calendars library development status

### ISSUE THREAD

**Issue by tautvilas** [wix/react-native-calendars#780]
Hello,

I wanted to update about the maintenance status of this lib. I have left Wix company around November 2018, we have talked with the team about transitioning this library maintenance to other people who still work in Wix however it looks like nobody officially took over this library yet. So currently it is only supported by community, but no PRs are being merged. If anything changes, please close this issue and update maintainers section in Readme. Just wanted to give people heads-up what to expect when contributing.

@goldenhammer @ethanshar @sibelius

**Comment by danielmartinprieto** [comment]
This library is a gem, please, don't let it be lost! Maybe the react-native-community can find a place for it with the new organisation? cc/ @cpojer @rickhanlonii

**Comment by rdewolff** [comment]
Thanks for the heads up @tautvilas. If nothing is done we should fork it and find a new group of maintainer.

**Comment by sibelius** [comment]
@tautvilas let's move to react-native-community?

you can transfer the repo to me, and then I can transfer to react-native-community

**Comment by mauriciord** [comment]
Transfer to @sibelius and let the community work on it. It'll be awesome

**Comment by rdewolff** [comment]
Would be perfect!

**Comment by tautvilas** [comment]
Hey, I guess we need Wix devs to be part of this discussion and check if it is ok with them. I will try to get some input from them. I don't have admin status of this repo now.

**Comment by jgcmarins** [comment]
cc @kelset

**Comment by tautvilas** [comment]
cc @mbardauskas

**Comment by kelset** [comment]
Hang on, please don't move it to react-native-community just 'cause. Let's move it there once there is someone who steps up for maintaining it.

Unless you want to move it there as inactive.

Please @sibelius don't take that kind of initiative about rncomm before asking.

**Comment by rdewolff** [comment]
> Hang on, please don't move it to react-native-community just 'cause. Let's move it there once there is someone who steps up for maintaining it.
> 
> Unless you want to move it there as inactive.
> 
> Please @sibelius don't take that kind of initiative about rncomm before asking.

Well I found their initiative sane and positive for the community.

**Comment by jaburcodes** [comment]
Sibelius initiative is really good for community, thanks for that.

**Comment by ButtersHub** [comment]
Hi, at Wix our UI team has some plans for this lib, we will check internally whether we able response quick enough on issues/PRs of this lib and decide to add maintainers from the community or transfer it to react-native-community, I'll update here soon.

**Comment by kelset** [comment]
@rdewolff @jaburcodes can you tell me why moving it over without having anyone maintaining it and also without first discussing it with the rest of the people in the org would be positive?

We are actively trying to make the community org better and have standards (see [here](https://github.com/react-native-community/meta/issues/1#issuecomment-474891076)) and just adding an extra repo out of the blue without any sort of plan for it is not a good move IMHO.

If you want to step up and maintain it (after @ButtersHub's update) it would be great and yeah we'd totally love to have it in the repo.

**Comment by sibelius** [comment]
Moving a repo from a company github org to a community org is much better for the community.
This allows to add more developers that want to contribute easily to the repo.
More people can be responsible for reviewing issues, pull requests and doing merges.

if you keep a stale repo in a company org, the company needs to keep taking care of it, as an outside collaborator does not know if a specific merge could cause regression on company not OSS version of this project

Having only one maintainer won't work either over time, as developers requirements for some open source packages change over time

What I've been doing in react-native-camera is inviting people that are contributing to the repository to be collaborators to be able to review and merge pull requests when needed, this is working quite well as new developers appears to contribute with more features and bugfixes

**Comment by rickhanlonii** [comment]
@kelset we would need to accept the transfer in order for it to take effect so they would not be able to add it out of the blue. If we have some criteria to accept the transfer, we can handle that after the discussion of whether or not the maintainers are willing to transfer it

Let's let Wix decide on their end and if they recommend transferring it we can work together with the community to find a maintainer 👌

**Comment by chenei** [comment]
Currently we are keep maintain it :)
