### ISSUE TITLE
How do I change a particular day's date color? 

### ISSUE THREAD

**Issue by kaushik618** [wix/react-native-calendars#782]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I wanted to change the date colors of Thursday to blue. 

## Expected Behavior

I'm not sure where exactly to change this style. 

## Observed Behavior
Not able to change. 
## Environment
Mac OS  - Mojave
IOS simulator

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.24.0
* `npm ls react-native`: react-native@0.57.4

Also specify:

1. Phone/emulator/simulator & version: IOS - iphone X

**Comment by slide13** [comment]
You need to read the **Date Marking** section in the description for more details. In the property markedDates, you need to pass an object where you add the necessary marking properties to the dates. So, in your case there will be something like this:

```
markedDates={{
    '2019-04-04': {color: 'blue'},
    '2019-04-11': {color: 'blue'},
    '2019-04-18': {color: 'blue'}
  }}
```
