### ISSUE TITLE
How do I prevent user from selecting certain dates?

### ISSUE THREAD

**Issue by helloitsm3** [wix/react-native-calendars#791]
I would like to allow users to only select 3 months from the current date and disable the user from selecting any dates before the current date and after 3 months.

**Comment by slide13** [comment]
@helloitsm3 

The documentation clearly spelled out what you need in the section "**Basic parameters**".
You need the following parameters:

```
  // Minimum date that can be selected, dates before minDate will be grayed out. Default = undefined
  minDate={'2012-05-10'}
  // Maximum date that can be selected, dates after maxDate will be grayed out. Default = undefined
  maxDate={'2012-05-30'}
```
