### ISSUE TITLE
multiple markings are showing only in debug mode in both androdi & iOS

### ISSUE THREAD

**Issue by prashantvv** [wix/react-native-calendars#794]
Hello, I customize the calendar well but it is showing me multiple markings only in debug mode & not in release mode. Dates with single marking are showing only in which start date and enddate are same, other wise not showing in release mode+ non debug mode. And all dates are dynamically filled out. Setting my data static shows all markings in all modes, but not with dynamic data. Im using multi-period type & I found that in index.js of multi-period, renderPeriods(marking)(),gives me issue somewhere in normal mode bcoz my console/alerts (which i pu ton top of renderPeriods()) wont trigger in this function while triggered fine in debug mode, meaning the render() wont call when data was available
 

My json data is as follows:
{
  "2019-04-01": {
    "periods": [
      
    ]
  },
  "2019-04-02": {
    "periods": [
      
    ]
  },
  "2019-04-03": {
    "periods": [
      
    ]
  },
  "2019-04-04": {
    "periods": [
      
    ]
  },
  "2019-04-05": {
    "periods": [
      
    ]
  },
  "2019-04-06": {
    "periods": [
      
    ]
  },
  "2019-04-07": {
    "periods": [
      
    ]
  },
  "2019-04-08": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "blue",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "red",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "red",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": false,
        "endingDay": true,
        "color": "darkgreen",
        "job_title": "New job for farm hand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-09": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "blue",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "red",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "red",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-10": {
    "periods": [
      
    ]
  },
  "2019-04-11": {
    "periods": [
      
    ]
  },
  "2019-04-12": {
    "periods": [
      
    ]
  },
  "2019-04-13": {
    "periods": [
      
    ]
  },
  "2019-04-14": {
    "periods": [
      
    ]
  },
  "2019-04-15": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": false,
        "endingDay": true,
        "color": "black",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-16": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-17": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-18": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-19": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-20": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "darkorange",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      },
      {
        "startingDay": false,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-21": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-22": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-23": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-24": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-25": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-26": {
    "periods": [
      {
        "startingDay": true,
        "endingDay": true,
        "color": "#008ECC",
        "job_title": "New job for farmhand ",
        "alreadyExists": false
      }
    ]
  },
  "2019-04-27": {
    "periods": [
      
    ]
  },
  "2019-04-28": {
    "periods": [
      
    ]
  },
  "2019-04-29": {
    "periods": [
      
    ]
  },
  "2019-04-30": {
    "periods": [
      
    ]
  }
}

![Simulator Screen Shot - iPhone 6s - 2019-04-19 at 12 29 13](https://user-images.githubusercontent.com/22851097/56411562-d0444280-629e-11e9-8d71-0d983f7ef986.png)
![Simulator Screen Shot - iPhone 6s - 2019-04-19 at 12 28 44](https://user-images.githubusercontent.com/22851097/56411563-d0dcd900-629e-11e9-8db7-55c23016d13b.png)

**Comment by estevanpedro** [comment]
Can you send your code, please, i cant find how to do this.

**Comment by prashantvv** [comment]
Hello, we can clos this. This issue is now resolved. It was not the library problem and was my end problem. Thankx for asking.

**Comment by haseebb** [comment]
how did you fix this? i am facing the same issue, dates are not shown as marked if debug mode is off, in debug mode all dates are shown as marked perfectly

**Comment by prashantvv** [comment]
You have to recheck the data you are passing to the calendar component, the date format that i was passing in the calendar was the the reason for the issue at my end. I was using moment at that time but sometimes moment and date objects do not work well in mobile app and such thing happens.

**Comment by haseebb** [comment]
![image](https://user-images.githubusercontent.com/38561017/86888891-5ce15780-c114-11ea-8d61-c5967e22d754.png)
this is the data that i am passing to the calendar and nothing seems wrong with the format of date it's in yyyy-mm-dd format i can't figure out  what i am doing wrong

**Comment by prashantvv** [comment]
it needs different object composition . As per the repo u need to hv ur data either like this -
 markedDates={{
    '2012-05-16': {selected: true, marked: true, selectedColor: 'blue'},
    '2012-05-17': {marked: true},
    '2012-05-18': {marked: true, dotColor: 'red', activeOpacity: 0},
    '2012-05-19': {disabled: true, disableTouchEvent: true}
  }}

dates should com first or u need to changes the logic inside the calendar component. If its hard from api side then it needs to be updated from frontend.
