### ISSUE TITLE
Example project moved to root?

### ISSUE THREAD

**Issue by friederbluemle** [wix/react-native-calendars#796]
What are the reasons for moving the example project into the root folder (11eeba61758e7e17decea80822a39a5bc4250e60), effectively mixing up the sample code with the library code? The usual setup for basically all React Native libraries is to have the example project(s) **fully contained** (and isolated) in a subfolder (conventionally `example`).

**Comment by GioLogist** [comment]
That threw me a curveball as well, also curious as to the thought process there 🧐
