### ISSUE TITLE
Releases changelog

### ISSUE THREAD

**Issue by filippoitaliano** [wix/react-native-calendars#797]
## Description
Minor releases are very frequent and it's difficult to handle them as patches (as they probably are) in my dependencies workflow. One very useful solution would be to document the changes in a human readable way so I can easily know what I'm upgrading.

I saw #386 but, as I described, the point is a little different. The solution is the same: have a punctual changelog somewhere.

Thanks for your help!

**Comment by filippoitaliano** [comment]
Yeah, 27 new features in 6 days! From version 1.81.0 to 1.108.0. I damn love semver when is barely considered.

**Comment by Inbal-Tish** [comment]
We solved the issue in our CI so there will be fewer releases from now on. We will work on creating a changelog soon to keep you all updated. Apologies for the inconvenience.

**Comment by filippoitaliano** [comment]
I really appreciate, thanks!!
