### ISSUE TITLE
No possible way to go back directly to the current date

### ISSUE THREAD

**Issue by akhilsanker** [wix/react-native-calendars#807]
## Description

If we navigate from current month, either forward or backward, there is no possible option to go back directly to the current date. Needs to navigate back to reach the current month/date.
 
## Expected Behavior

Should have a usability option to get back to the current date.

## Observed Behavior

No usability option to go directly back to the current date.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.82.0
* `npm ls react-native`: 0.59.5

## Reproducible Demo
       const vacation = {key:'vacation', color: 'red', selectedDotColor: 'blue'};
       const massage = {key:'massage', color: 'blue', selectedDotColor: 'blue'};
       const workout = {key:'workout', color: 'green'};

      <Calendar
        markedDates={{
          '2019-05-25': {dots: [vacation, massage, workout], selected: true, selectedColor: 'red'},
          '2019-05-16': {dots: [massage, workout]},
        }}
        markingType={'multi-dot'}
        onDayPress={(day) => this.datePressed(day)}
      />

**Comment by robertalv** [comment]
Honestly was just thinking of how to work this out

**Comment by FatjonRrapaj** [comment]
use the **current** prop.
Like this: 
`
<Calendar
current={this.state.current}
...calendarProps />
`

and create a button wherever you want. On button press, do this:
`this.setState({current:  this.state.current' {/*...you may just enter your current date here...*/'})`
this will re-render the calendar and set it to current date

**Comment by taohnouaccountb** [comment]
If anyone still has this problem, may try this one
```
function calendar(){
    const [current, setCurrent] = useState(new Date().toISOString())
    return (
        <View>
            <Button title={'today'} onPress={()=>setCurrent(new Date().toISOString())} />
            <CalendarList current={current}/>
        </View>
    )
}
```
Be sure to use `new Date().toISOString()` which can give you a new string but `new Date().toISODate()` won't.
