### ISSUE TITLE
onPress handler only for marked days

### ISSUE THREAD

**Issue by abdulmoizlakhani** [wix/react-native-calendars#808]
Only trigger the onPress handler when user click on marked day.
Please guide me if there is any way to do this. I found only onDayPress handler but it worked for all days even they are marked or not.

The only solution I think is adding a new attribute to 
`<Calender />` as 
`<Calender handleOnlyMarkedDays={true} />` 
and this should allow onPress only for marked days.

Please guide me if I am wrong.

**Comment by chenei** [comment]
You can disable dates in markedDates.
You can disabled all the dates by default using this:
https://github.com/wix/react-native-calendars/blob/master/src/calendar/index.js#L77
markedDates will override this prop.

You can also pass this new props:
https://github.com/wix/react-native-calendars/blob/master/src/calendar/index.js#L95
Which disable all touch events.

**Comment by bmitioglov** [comment]
How can I make marked dates blink when I touch them? Similar to not marked dates?
