### ISSUE TITLE
markedDates prop for Agenda

### ISSUE THREAD

**Issue by Bezzanin** [wix/react-native-calendars#81]
Hello,

Awesome Library, but I am really missing the markedDates prop inside the <Agenda /> element.

Something like:

<Agenda
markedDates={
    {'2012-05-20': [{textColor: 'green'}],
     '2012-05-22': [{startingDay: true, color: 'green'}],
     '2012-05-23': [{endingDay: true, color: 'green', textColor: 'gray'}],
     '2012-05-04': [{startingDay: true, color: 'green'}, {endingDay: true, color: 'green'}]
    }}
/>

Could you please add the markedDates props to be rendered similar to <CalendarList /> element like in the example bellow:

https://raw.githubusercontent.com/wix/react-native-calendars/master/demo/calendar-list.gif

**Comment by tautvilas** [comment]
I think this could be added, but this would override the default marking that shows days with items. Another idea is that the api could be that you can pass marking for each day in the same items param of Agenda. what do you say?

**Comment by Bezzanin** [comment]
Well passing the marking in the same items param will be great!

**Comment by smkhalsa** [comment]
@tautvilas Any progress on this?

**Comment by tautvilas** [comment]
This has been solved in 1.6.0
