### ISSUE TITLE
Agenda reloads automatically when keyboard appears (Android)

### ISSUE THREAD

**Issue by ManishAhire** [wix/react-native-calendars#810]
I am using ```Agenda``` Component in my application.  ```Agenda``` is working fine, but I also add ```TextInput``` in my screen.
When I tap on my Text Input, keyboard appears then the Agenda component reloaded automatically and unnecessarily called the ```loadItemsForMonth``` method.

Please help me how to stop the unnecessary call of ```loadItemsForMonth``` method.

**Comment by Ru5habh5hah** [comment]
I'm also seeing this happen too. Any ideas/solutions?

**npm ls react-native-calendars:**
react-native-calendars@1.21.0

**npm ls react-native:**
react-native@0.56.0

**Phone/emulator/simulator & version:**
Android - Nexus_5X_API_28_x86

**Comment by ManishAhire** [comment]
@Ru5habh5hah, Found an alternative solution for this. I commented on the `loadItemsForMonth` method and used the `onDayPress` method.

**Comment by Ru5habh5hah** [comment]
@ManishAhire - Another option that seems to not fire the `loadItemsForMonth` callback from another tab on android is based on #674.

This checks if the  scrollable calendar is visible, if not then loaditems can be called.

```javascript
<Agenda
          onCalendarToggled={this.onCalendarToggled} //sets the showMonth (true/false)
          loadItemsForMonth={day => {
            if (!this.state.showMonth) {
              this.loadItems(day);
            }
          }}
```

**Comment by opvishu2** [comment]
A quick fix, use conditional rendering after keyboard dismiss, e.g.


   {showAgenda && <Agenda
    theme={{ }}
    onDayPress={dateData => { }}
   onDayChange={() => { }
   }}
    items={}
    rowHasChanged={(r1, r2) => { }}
    selected={}
    showClosingKnob={}
    refreshing={}
    onRefresh={}
    keyExtractor={}
    renderItem={}
    renderEmptyData={() => {
      return <></>
    }}
  />}
