### ISSUE TITLE
@slorber missing import

### ISSUE THREAD

**Issue by sipotat** [wix/react-native-calendars#812]
@slorber Great solution!
Only thing that is missing is this import in reservation-list/index.js:
import { parseDate } from '../../interface';

Thank you!

I have a simple way to solve it, though not perfect.
Add a _onRefresh func in react-native-calendars/src/agenda/reservation-list/index.js
```
_onRefresh = () => {
  let h = 0;
  let scrollPosition = 0;
  const selectedDay = this.props.selectedDay.clone();
  const iterator = parseDate(this.props.selectedDay.clone().getTime()-3600*24*10*1000);
  let reservations = [];
  for (let i = 0; i < 10; i++) {
    const res = this.getReservationsForDay(iterator, this.props);
    if (res) {
      reservations = reservations.concat(res);
    }
    iterator.addDays(1);
  }
  scrollPosition = reservations.length;
  for (let i = 10; i < 30; i++) {
    const res = this.getReservationsForDay(iterator, this.props);
    if (res) {
      reservations = reservations.concat(res);
    }
    iterator.addDays(1);
  }
  this.setState({
    reservations
  }, () => {
    setTimeout(() => {
      let h = 0;
      for (let i = 0; i < scrollPosition; i++) {
        h += this.heights[i] || 0;
      }
      this.list.scrollToOffset({offset: h, animated: false});
      this.props.onDayChange(selectedDay, false);
    }, 100);
  });
}
```

And rewite the onRefresh in render()
```
<FlatList
  ...
  onRefresh={this._onRefresh}
```
then add a parmas in onDaychange func in react-native-calendars/src/agenda/index.js
```
onDayChange(day, f=true) {
  ...
  this.calendar.scrollToDay(day, this.calendarOffset(), withAnimation && f); //add f here
 ...
```

It works in the demo. If you want to use in your project, maybe you need change some parmas to fit your project.

_Originally posted by @saigyouyou in https://github.com/wix/react-native-calendars/issues/80#issuecomment-471962683_

**Comment by Inbal-Tish** [comment]
@sipotat Please move this issue to comment on issue #80 and close this one.
