### ISSUE TITLE
Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by lp4298707** [wix/react-native-calendars#820]
import { CalendarList} from 'react-native-calendars';

<CalendarList/>

If I use ' Calendar ' everything is fine, but with ' CalendarList ' it will report ' Cannot Read property ' 2 ' of undefined ' 

"react": "16.3.1",
"react-native": "0.55.4",
"react-native-calendars": "^1.133.0",

**Comment by mgfjxxiexiaolong** [comment]
I got this error, any solution for this ？

**Comment by Hektar90** [comment]
try: https://github.com/wix/react-native-calendars/issues/552#issuecomment-574592329

**Comment by teogomes** [comment]
Addind dayNames[] to the LocalConfig.locales did the job for me
