### ISSUE TITLE
Pls stop making a lot of releases per hour/day 🙏 

### ISSUE THREAD

**Issue by AleksandrZhukov** [wix/react-native-calendars#823]
Guys pls create normal releases with description, changelog etc

**Comment by export-mike** [comment]
nah its cool, they're clearly moving fast and needing to get stuff done over in Wix land. we're second in their priorities, a description can't hurt though.

**Comment by devzhen** [comment]
Guys pls create normal releases with description, changelog etc

**Comment by Inbal-Tish** [comment]
We solved the issue in our CI so there will be fewer releases from now on. We will work on creating a changelog soon to keep you all updated. Apologies for the inconvenience.
