### ISSUE TITLE
Calendar List Horizontal Scroll not loading Calendar before or after 1 month

### ISSUE THREAD

**Issue by ahmad6242** [wix/react-native-calendars#828]
## Description

Calendar is not loading instead only month name is shown. 
I have experienced it in Calendar list Horizontal View. 1 month after and before the current month only placeholder of month name is shown and calendar did not loads. 

## Expected Behavior

I expect the calendar to be loaded for each month.

## Observed Behavior

It did not load 

![Screenshot_1558523252](https://user-images.githubusercontent.com/12858657/58170349-3eb46000-7ca4-11e9-8e99-eade7d130bcb.png)
![Screenshot_1558523257](https://user-images.githubusercontent.com/12858657/58170350-3f4cf680-7ca4-11e9-8507-287ba9797641.png)
![Screenshot_1558523260](https://user-images.githubusercontent.com/12858657/58170351-3f4cf680-7ca4-11e9-9e57-b49f0d39ed8e.png)
![Screenshot_1558523266](https://user-images.githubusercontent.com/12858657/58170352-3f4cf680-7ca4-11e9-9379-529032117ce4.png)
![Screenshot_1558523269](https://user-images.githubusercontent.com/12858657/58170355-3fe58d00-7ca4-11e9-84b8-797339a3b2c4.png)

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:
react-native-calendars@1.110.0:
react-native@0.59.5:

**Comment by atulmy** [comment]
Seems to happening on Android only. On iOS seems to work fine.

**Comment by olfek** [comment]
This was happening to me too, you must be mutating state immediately in `onVisibleMonthsChange` like I was. To fix it, I delayed state mutation in `onVisibleMonthsChange` by 3 seconds.

**Comment by ahmad6242** [comment]
Thank you @olfek , that worked.

**Comment by Maddumage** [comment]
Same problem here and After adding 3seconds delay as @olfek  answer, calendar months render well. :)
