### ISSUE TITLE
Agenda how to displays items in ListView in reverse chronological order 

### ISSUE THREAD

**Issue by naxiaoguang** [wix/react-native-calendars#83]
Agenda how to displays items in ListView in reverse chronological order ;
I want the last data on top .

**Comment by tautvilas** [comment]
Hi could you give more details? Do you want to display items in day in reverse order or days in agenda?

**Comment by naxiaoguang** [comment]
Hi ,  show current-day records above, then pass-day's  below .    each record has unique time ,order by record time .

**Comment by tautvilas** [comment]
can you attach some kind of prototype image explaining your idea? thx

**Comment by tautvilas** [comment]
sorry this feature will not be implemented anytime soon
