### ISSUE TITLE
Support for Accessibility font scaling on iOS

### ISSUE THREAD

**Issue by Simek** [wix/react-native-calendars#831]
## Description

On iOS user can decide about globally Text Size multiplayer using Accessibility setting. 
https://facebook.github.io/react-native/docs/text#allowfontscaling

Currently system font scaling is ignored in `react-native-calendars` library - most of components have property `allowFontScaling={false}` added.

## Expected Behavior

Component text scale with Accessibility setting. 

## Observed Behavior

No changes in Text size when Accessibility scale is used. 

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 326.38 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
```

**Comment by Simek** [comment]
Are there any internal issues when font scaling is turned on or just UI glitches?

I will want to start working on PR for this feature if there are no known contraindications.

**Comment by Inbal-Tish** [comment]
@Simek As far as I can tell there are only UI issues, but it is worth further checking.
