### ISSUE TITLE
Error when compiling for web

### ISSUE THREAD

**Issue by ceribbo** [wix/react-native-calendars#839]
Hello, I'm using the calendar component for my project.
If i run native, the component is correctly compiled and showed, however if i run web `expo start` i get an error:

```./node_modules/react-native-calendars/src/agenda/index.js
SyntaxError: C:\Users\g.ceribelli\Documents\postesocial\node_modules\react-native-calendars\src\agenda\index.js: 
Support for the experimental syntax 'classProperties' isn't currently enabled (26:20):


  25 | export default class AgendaView extends Component {
> 26 |   static propTypes = {
     |                    ^
  27 |     // Specify theme properties to override specific styles for calendar parts. Default = {}
  28 |     theme: PropTypes.object,
  29 | 

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

How can i solve this problem?
I have alerady added plugin-proposal-class-properties both into my webpack.config.js and my babelrc files
Thank you

**Comment by bkniffler** [comment]
This is most probably not an issue with react-native-calendars, but with expo. I'm using calendars fine with my web webpack setup. react-native-calendars needs transpilation (just like most react-native libraries), so I guess expos packager needs to be told to transpile `node_modules/react-native-calendars`. If I was you, I'd close this issue and open a new one in the expo community.

**Comment by BillyFigueroa** [comment]
I have opened this issue with expo

[react-native-calendars not rendering properly](https://github.com/expo/expo/issues/5621)

Maybe you can chime in?

**Comment by bkniffler** [comment]
I guess this issue can be closed

**Comment by arekko** [comment]
@BillyFigueroa  for more information you can check [this](https://medium.com/@ryoldash/customize-webpack-config-of-react-app-created-with-create-react-app-7a78c7849edc) article

**Comment by bkniffler** [comment]
@arekko I'm not sure this applies to @BillyFigueroa, he states he uses `expo web`. `config-overrides.js` and your linked article are related to `create-react-app`.

**Comment by arekko** [comment]
Yes, you right, [this](https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej) one more relevant, especially the part about web.

**Comment by BillyFigueroa** [comment]
@arekko I m not sure this is something I can do with out ejecting my expo app. The way expo creates the app it makes it look like its a single project

**Comment by arekko** [comment]
Try to 

- Install react-app-rewired
- change the package.json
`scripts: {  "web": "SKIP_PREFLIGHT_CHECK=true react-app-rewired start"}`
- create config-overrides.js file on the project root with
const path = require('path');
const webpack = require('webpack');
const { override, addBabelPlugins, babelInclude, removeModuleScopePlugin, addWebpackAlias } = require('customize-cra');

const modulesPath = path.resolve(__dirname, 'node_modules');

const registerGlobals = vars => config => {
  if (!Array.isArray(config.plugins)) config.plugins = [];
  config.plugins.push(new webpack.DefinePlugin(vars));

  const eslintRuleOptions = config.module.rules.filter(
    r => r.use && r.use.some(u => u.options && u.options.useEslintrc !== void 0),
  )[0].use[0].options;
  if (!Array.isArray(eslintRuleOptions.globals)) eslintRuleOptions.globals = [];
  eslintRuleOptions.globals = [...eslintRuleOptions.globals, ...Object.keys(vars)];

  return config;
};

module.exports = override(
  removeModuleScopePlugin(),
  registerGlobals({
    __DEV__: process.env.NODE_ENV === 'development',
  }),
  babelInclude([
    path.resolve('src'),

     path.resolve(modulesPath, "react-native-calendars"),
  ]),
  addBabelPlugins('@babel/plugin-proposal-class-properties'),
);`
`

- rebuild the project

**Comment by BillyFigueroa** [comment]
@arekko thanks...

It looks like `react-app-rewired` was made to modify a project created with create-react-app. A few modules were missing like `react-scripts` and `customize-cra` and I tried to add them but I kept running into other errors

**Comment by bkniffler** [comment]
@BillyFigueroa you shouldn't go further this route, these fixes and advices all only apply to @ceribbo and his issue. Your problem (expander not working, dates not showing) is definitely not related to any build/dependency issues.
