### ISSUE TITLE
Agenda: only implementing the strip? 

### ISSUE THREAD

**Issue by justDanielMata** [wix/react-native-calendars#84]
Hello! 

love the modules, they work great and are easy to implement. I really like the strip from the agenda, and would love to implement something similar, looking at the src, i see that is just a calendar list styled to look like that, is there a way to achieve the same? i just need the strip without the rest of the agenda

**Comment by tautvilas** [comment]
Hi, currently the strip is implemented by using CalendarList component, but setting small height of container. Then calendar list is navigated to correct week by using `scrollToDay` method of CalendarList. It might be good to extract the strip as a separate component and make it reusable. I will consider this.

**Comment by Jacse** [comment]
@tautvilas That would definitely be great. Right now I want to do something similar to the Agenda, but with a regular "day-schedule" filling the whole page (swiping left or right navigates to next/prev day). I would really like to move to this package and use such a strip with expandable capabilities!

**Comment by runeogod** [comment]
@Jacse Did you manage doing it finally?

**Comment by Jacse** [comment]
@runeogod I ended up implementing my own based on FlatList.

**Comment by runeogod** [comment]
@Jacse Could you share it please?

**Comment by johra** [comment]
@Jacse Would like to do the same as you, please share or make a PR if possible :)

**Comment by Jacse** [comment]
@runeogod sorry for not responding! I'm afraid my own `DateStrip` doesn't have the expandable capability and really isn't fit for sharing in any meaningfull way since it is very curled up in my specific project. What I've done is really just a screen-wide FlatList with paginationEnabled with each item being a "row" of 7 dates. In order to make it infinite I've created handlers on `onMomentumScrollEnd` that prepend/append the data.

Hope that makes a little bit of sense.

**Comment by narciero** [comment]
+1 for this!

**Comment by Bound3R** [comment]
HI, maybe you can use `<AgendaList/>`.

**Comment by ihsanktmr** [comment]
could it be similar to this ? https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538

**Comment by rdewolff** [comment]
That package could help : https://github.com/BugiDev/react-native-calendar-strip

**Comment by chenei** [comment]
please take a look at this thread:
https://github.com/wix/react-native-calendars/issues/1113#issuecomment-637439327
if you don't find it suitable, please open a feature request.
