### ISSUE TITLE
Is it not available to use full calendar like buttons such as "month, week, day"?

### ISSUE THREAD

**Issue by railsjack** [wix/react-native-calendars#840]
## Description
I want to use a feature to select "Month view", "Week view", "Day view" like as full calendar.

**Comment by fa16mscs0004** [comment]
Looking for same thing do have found any solution ?

**Comment by railsjack** [comment]
> Looking for same thing do have found any solution ?

Not yet.

**Comment by zerobytes** [comment]
As far as i can see, it is the only calendar feature missing, so far.
Current agenda component is impressive, although not having week/month views, which is common in any app with an agenda, is definitely something to improve
