### ISSUE TITLE
expandable calendar multi dots wont work

### ISSUE THREAD

**Issue by kirhim** [wix/react-native-calendars#844]
Does expandable calendar support multi-dots? I tried but won't work

**Comment by Inbal-Tish** [comment]
Yes (see screenshot). Did you pass `markingType={'multi-dot'}`?
![Simulator Screen Shot - iPhone X - 2019-06-11 at 17 22 30](https://user-images.githubusercontent.com/33805983/59280099-b5be9200-8c6d-11e9-87bc-2362217262b9.png)
