### ISSUE TITLE
Agenda Calendar View Collapsed Bottom cut-off

### ISSUE THREAD

**Issue by moiiiiit** [wix/react-native-calendars#845]
A simple agenda component copied straight from the example is slightly buggy on both emulator and mobile device. The agenda is fully function, and only has a small but annoying visual bug.

## Description

A small part of the calendar dates have been cut off as seen in the demo

## Expected Behavior

Agenda renders just as in the giffys/as it does for everyone else

## Observed Behavior

Dates cut from the bottom

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: -- react-native-calendars@1.185.0
* `npm ls react-native`: `-- react-native@0.57.1

Also specify:

1. Phone/emulator/simulator & version: API 28 Pixel 2, Oneplus 3T Android 9.0

## Reproducible Demo

![image](https://user-images.githubusercontent.com/43913328/59263725-3f1a9800-8c5f-11e9-9277-e7ddcc015c87.png)

![image](https://user-images.githubusercontent.com/43913328/59263750-4e014a80-8c5f-11e9-8ed1-e1d136e92120.png)

**Comment by LucasHimelfarb** [comment]
This question has already been resolved several times. Enter the calendar module-reactive-native ...
src / agenda / index.js ... then search for calendarOffset () ...

-retorno 90 - (este.vistaHeight / 2);

+ return 96 - (this.viewHeight / 2);

**Comment by moiiiiit** [comment]
Thank you so much! I tried to find other posts but couldn't find. Thanks again!

**Comment by pennyandsean** [comment]
Is there a PR for this?

**Comment by carlosroberto555** [comment]
Look a old PR to fix it #615
