### ISSUE TITLE
Failed to load bundle

### ISSUE THREAD

**Issue by ChupikNarik** [wix/react-native-calendars#846]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-calendars` from `/Users/romanfedoruk/projects/tasks-app/tasksApp/src/pages/CreateEditTask/index.js`: Module `react-native-calendars` does not exist in the Haste module map or in these directories: /Users/romanfedoruk/node_modules

I not can delete this component. After delete I have this error again.

**Comment by chenei** [comment]
Still have this issue?
