### ISSUE TITLE
Can I use multiple markingType?

### ISSUE THREAD

**Issue by kirhim** [wix/react-native-calendars#847]
I want to use both `multi-dot` and `custom` so I tried `markingType={'multi-dot', 'custom'}` but this won't work. Is it possible to use both these?

**Comment by fa16mscs0004** [comment]
I am looking for same functionality ..

**Comment by rebirthtobi** [comment]
Me too but I think we will have to leverage on the custom mark since you can style custom mark as you like or using the `dayComponent`

**Comment by chenei** [comment]
Hi,
Currently, we don't support multi marking.
https://github.com/wix/react-native-calendars#date-marking

We do add the option to use Period and Single marking without breaking the API.
