### ISSUE TITLE
Can you make a one week format or two week format for Calendar?

### ISSUE THREAD

**Issue by DanijelBojcic** [wix/react-native-calendars#848]
Hi! Can you make `oneWeekFormat` or `twoWeekFormat` for Calendar?
It would be great for less vertical space.
I saw others requested similar : #612 #567 #508 
Current:
![current](https://user-images.githubusercontent.com/50402950/59349384-ccbabe00-8d19-11e9-9f70-a905a17f921f.png)
Goal:

## `twoWeekFormat`
![goal1](https://user-images.githubusercontent.com/50402950/59349395-d47a6280-8d19-11e9-88ce-44b7145b60bf.png)

## `oneWeekFormat`
![goal2](https://user-images.githubusercontent.com/50402950/59349398-d6dcbc80-8d19-11e9-9426-fe63bd5786df.png)

**Comment by ihsanktmr** [comment]
Yes it is possible, but it is temporary solution please go to my comment below

[https://github.com/wix/react-native-calendars/issues/998#issuecomment-570073538](url)

**Comment by chenei** [comment]
We already have a Week Calendar solution using expandable calendar
