### ISSUE TITLE
CalendarList does not show more than three months

### ISSUE THREAD

**Issue by urmatt** [wix/react-native-calendars#851]
When scrolling horizontally, I only see the previous and next months

**Comment by LucasHimelfarb** [comment]
Provide the code with which you defined the component and its accessories...

**Comment by FranciscoSimaoPerez** [comment]
Do you use setState on onVisibleMonthsChange prop?

**Comment by Jojr** [comment]
I'm facing the same issue.
@FranciscoSimaoPerez Yes, I'm setState on onVisibleMonthsChange.

**Comment by lironsher** [comment]
I hade the same issue when UI is in RTL

**Comment by bneigher** [comment]
Seems that whenever you pass in your own handler for `onVisibleMonthsChange`, only 2 months will render with the days.

**Comment by urmatt** [comment]
I go to flutter )

**Comment by nameEO** [comment]
This works for me, show every months. _WD-40_ for JS!
`onVisibleMonthsChange={(months) => {
                setTimeout(() => {
                  this.setState((state) => {
                    return {
                      months
                    };
                  });
                }, 0);
              }}`
