### ISSUE TITLE
Calendar doesn't update dot color 

### ISSUE THREAD

**Issue by Arun-paramasivam** [wix/react-native-calendars#852]
## Description

Both the dot color and selected color doesn't show up when both values are given. But updating it individually gives the desired result.

the code i used for design:
{selected: true, marked: true, dotColor: 'blue', selectedColor: 'gray'}

## Expected Behavior

it must update calendar with both the selected color and dot color.

## Observed Behavior

selected color is changed to gray whereas the dot color remains as default white color. (what i need is blue).

## Environment

react-native-calendars@1.141.0
 react-native@0.58.6

Also specify:

1. Phone/emulator/simulator & version: Android Device API level: 24 ( 7.0 Nougat)

**Comment by AdrienV** [comment]
Hi, 

Same problem for me, anyone can help for this point please ?
`2019-10-31: {color: "#74ccd4", dotColor: "red", marked: true, selected: true, textColor: "red"}`

Dot shown white :(

Thanks
