### ISSUE TITLE
How can I add new events on Agenda?

### ISSUE THREAD

**Issue by kirhim** [wix/react-native-calendars#855]
I assume that in the `Agenda` feature I can show events like this:

![Screen Shot 2019-06-17 at 10 38 27 AM](https://user-images.githubusercontent.com/23249216/59573125-58529700-90ec-11e9-9bc8-76cdf8ae8bad.png)

But how can I add new events to Agenda? Could anyone share an example code?

Thanks in advance! :)

**Comment by carlosroberto555** [comment]
Like this?

```jsx
<Agenda
    items={{
        '2012-05-22': [{text: 'item 1 - any js object'}],
        '2012-05-23': [{text: 'item 2 - any js object'}],
        '2012-05-24': [],
        '2012-05-25': [{text: 'item 3 - any js object'},{text: 'any js object'}]
    }}
    renderItem={(item) => (
        <MyEventComponent item={item} />
    )}
/>
```

**Comment by LucasHimelfarb** [comment]
Se agrega un nuevo evento al calendario de acuerdo con cómo lo configuré en su proyecto, ¿son los eventos de código fijo como el comentario anterior? ¿Quieres hacerlo dinámicamente?

**Comment by LucasHimelfarb** [comment]
Example, received an array of objects from an API, formatting the attribute that gave me its date, to adjust it in the way required by the agenda

                let onDate = moment(ticket.created.date);
                formatDate = onDate.format('YYYY-MM-DD');
                if(!ticketsWithDate[formatDate]) ticketsWithDate[formatDate] = [ticket];
                else ticketsWithDate[formatDate].push(ticket);



Use moment.js for formatting
