### ISSUE TITLE
Error installing calendar

### ISSUE THREAD

**Issue by IcaroRios** [wix/react-native-calendars#86]
Hi, I tried to install and received the following message:
UNMET PEER DEPENDENCY react@16.0.0-alpha.12
UNMET PEER DEPENDENCY react-native@0.46.1

And these warnings:
react-native-calendars@1.4.0 requires a peer of react@16.0.0-alpha.6 but none was installed.
react-native-calendars@1.4.0 requires a peer of react-native@0.44.0 but none was installed.

Using react-native -version
I saw: 
react-native-cli: 1.2.0
react-native:0.46.1

And in my package.json is:
`"react": "16.0.0-alpha.12",

  "react-native": "0.46.1",`

Please help!

**Comment by tautvilas** [comment]
Hi, but you still get installed the calendars lib and can use it, no?

**Comment by IcaroRios** [comment]
Yes, but, why this error?

**Comment by tautvilas** [comment]
Removed peerDeps from package.json, you should not get error anymore after clean install
