### ISSUE TITLE
Empty dates not being rendered

### ISSUE THREAD

**Issue by GunaShekar02** [wix/react-native-calendars#867]
## Description

renderEmptyDate in Agenda does not render what we mention in empty dates.  Changing renderEmptyData() to renderEmptyDate() as mentioned in one of the issues does not work either. That displays a plain view without the date and day like the marked dates are rendered.

## Expected Behavior

Currently the marked dates are being rendered but nothing is being shown for empty dates.
I would like all the days to be displayed in the agenda irrespective of whether they are marked or not, and show event names on marked dates, just like the demo given in the README.md in the repository.  
Current display:-
![image](https://user-images.githubusercontent.com/43517435/60772220-e4b31100-a110-11e9-91b8-a9365c22bbcf.png)

Expected display:-
![image](https://user-images.githubusercontent.com/43517435/60772231-0ca27480-a111-11e9-8725-2490c3e7f199.png)
Something like this where the dates(10,11,12) which have no events are still being shown.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.194.0 
* `npm ls react-native`:0.59.8

Also specify:

1. Phone/emulator/simulator & version: Expo App, running on Android version 8.0.0

## Reproducible Demo
renderItem(item) {
    return (
      <View><Text>{item.name}</Text></View>
    );
  }
render() {    
    return (
      <Agenda
        items={this.props.events.events}
        selected={'2018-01-01'}
        renderItem={this.renderItem.bind(this)}
        renderEmptyDate={() => {return (<View />);}}
        renderEmptyData={() => {return (<View />);}}
        rowHasChanged={() => {return(r1.name !== r2.name);}}
      />
  );
  }

**Comment by AliLezamaIgrat** [comment]
Hi, not sure if you still have the doubt, but I had the same problem and kind of solved it with the info in this post (https://github.com/wix/react-native-calendars/issues/15)
It look like right now to have your expected display you have to add something to those days, with in the case of the link I'm sharing to you is an empty array, I know it is not the best and either something one should guess, but will display all the days.
Hope it helps you.
