### ISSUE TITLE
Disabling calendar part from agenda components

### ISSUE THREAD

**Issue by 0Shift** [wix/react-native-calendars#868]
is there a way to only display the agenda menu without the calendar at the top of the page?

**Comment by 0Shift** [comment]
bump

**Comment by smakosh** [comment]
Trying to get the same output

**Comment by 0Shift** [comment]
second bump, is it possible?

**Comment by smakosh** [comment]
I used this snippet instead: https://www.bootdey.com/react-native-snippet/11/Event-list but I had to convert it to a functional component & replace ListView with FlatList

**Comment by 0Shift** [comment]
> I used this snippet instead: https://www.bootdey.com/react-native-snippet/11/Event-list but I had to convert it to a functional component & replace ListView with FlatList

ended up doing the same, thanks for the snippet!
