### ISSUE TITLE
By default all days disable and enable just what I want

### ISSUE THREAD

**Issue by ralfting** [wix/react-native-calendars#871]
## Description

I want to be able to disable all days of the calendar and just enable what I need.

## Expected Behavior

When I pass the properties I can config a `disableDays=true` and all days is disabled, but when I put:
```
<Calendar
  disableDays=true
  markedDates={{
    '2012-05-19': {disabled: false, disableTouchEvent: false}
  }}/>
```
I wanna all days are been disabled  except `2012-05-19`;

## Observed Behavior

I can't found any property with that behavior (disable all day)

**Comment by FakeBounce** [comment]
You use the wrong parameter. Use `disabledByDefault` instead:

```
<Calendar
  disabledByDefault
  markedDates={{
    '2012-05-19': {disabled: false, disableTouchEvent: false}
  }}/>
```

**Comment by ralfting** [comment]
Thanks you @FakeBounce , that's great! @FakeBouncem I haven't found in the doc
