### ISSUE TITLE
Not able to select dates if date passed in is separated by slashes.

### ISSUE THREAD

**Issue by macitege** [wix/react-native-calendars#875]
## Description

`selectedDayBackgroundColor` and `selectedDayTextColor` props are not working as expected if the marked date is passed in, separated by slashes (YYYY/MM/DD) instead of dashes (YYYY-MM-DD).

## Expected Behavior

I use `YYYY/MM/DD` date format and I passed in the date information to `markedDates` prop in that format, and I have expected to see the dates that I had passed in to be selected on the calendar with the color and background color I have specified with `selectedDayBackgroundColor` and `selectedDayTextColor`.

## Observed Behavior

I was no longer able to select any date on the calendar. When I change the date format to be separated by dashes, it worked.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.192.0 
* `npm ls expo`:  expo@32.0.6 
* `npm ls react-native`: react-native@0.57.1  invalid

Also specify:

1. Phone/emulator/simulator & version: iPhone X - Simulator Version 10.2.1

## Code
This works:
```
          <Calendar
            current={this.state.details.date}
            minDate={Date()}
            monthFormat={'MMMM yyyy'}
            onDayPress={(day: any) => {
              this.setState({
                details: {
                  ...this.state.details,
                  date: format(day.dateString, 'YYYY-MM-DD'),
                },
              })
            }}
            markedDates={{
              [this.state.details.date]: {
                selected: true,
                disableTouchEvent: true,
              },
            }}
            theme={{
              dayTextColor: BLUE,
              textDayFontWeight: 'bold',
              textDisabledFontWeight: 'normal',
              todayTextColor: 'white',
              todayBackgroundColor: DARK_BLUE_PASTEL,
              monthTextColor: 'black',
              textMonthFontSize: 24,
              textMonthFontWeight: 'bold',
              arrowColor: 'black',
              selectedDayBackgroundColor: PRIMARY_BUTTON,
              selectedDayTextColor: PRIMARY_BUTTON_TEXT,
            }}
```
This doesn't work (Notice the difference on the date formats passed to the `format` function `onDayPress`): 
```
          <Calendar
            current={this.state.details.date}
            minDate={Date()}
            monthFormat={'MMMM yyyy'}
            onDayPress={(day: any) => {
              this.setState({
                details: {
                  ...this.state.details,
                  date: format(day.dateString, 'YYYY/MM/DD'),
                },
              })
            }}
            markedDates={{
              [this.state.details.date]: {
                selected: true,
                disableTouchEvent: true,
              },
            }}
            theme={{
              dayTextColor: BLUE,
              textDayFontWeight: 'bold',
              textDisabledFontWeight: 'normal',
              todayTextColor: 'white',
              todayBackgroundColor: DARK_BLUE_PASTEL,
              monthTextColor: 'black',
              textMonthFontSize: 24,
              textMonthFontWeight: 'bold',
              arrowColor: 'black',
              selectedDayBackgroundColor: PRIMARY_BUTTON,
              selectedDayTextColor: PRIMARY_BUTTON_TEXT,
            }}
```
**Note:** `format()` is a function from `date-fns` library. It produces a date string with the specified format. In this case, it produces the wanted string. There is no problem with its output.

**Comment by chenei** [comment]
Why you can't just use dashes?
