### ISSUE TITLE
Can't add a floating button above agenda component

### ISSUE THREAD

**Issue by flboissy** [wix/react-native-calendars#878]
## Description
Hi guys i want to add a Floating button above the agenda and i can't achieve this.

## Expected Behavior
 I want to add a floating button above agenda like this: 

![floating button on list](https://user-images.githubusercontent.com/15818437/61303138-4ea17980-a7e7-11e9-937f-6cb931dce0b2.PNG)

## Observed Behavior

Actually i try to add my button into my component like this: 

![actual code](https://user-images.githubusercontent.com/15818437/61303417-c53e7700-a7e7-11e9-9991-593146294320.PNG)

My calendar appear correctly but the button doesn't appear in my view

![floating button on calendar](https://user-images.githubusercontent.com/15818437/61303274-85778f80-a7e7-11e9-880b-1f5439a0340e.PNG)

## Environment

* `npm ls react-native-calendars`:
laruche_app@0.0.1 C:\Users\flbo\Documents\laruche\laruche-app
`-- react-native-calendars@1.196.0

* `npm ls react-native`:
laruche_app@0.0.1 C:\Users\flbo\Documents\laruche\laruche-app
`-- react-native@0.60.3

1. Phone/emulator/simulator & version:
Emulator Nexus 5X API 27
## Reproducible Demo

I can't give you a demo project because it's a professionnal project.
 i will try to reproduce it in a new project as soon as possible.

Sorry for my english and thanks in advance for your help

**Comment by murtinha** [comment]
Any news on this @flboissy ?
Im gonna have to do this as well soon

**Comment by OkkarMin** [comment]
Hello,

I used [react-native-floating-action](https://github.com/santomegonzalo/react-native-floating-action) with react-native-elements and its working fine

```jsx
      <View style={styles.container}>
        <SafeAreaView />
        <Agenda items={this.state.items} />
        <FloatingAction
            actions={actions}
            onPressItem={name => {
                 console.log(`selected button: ${name}`);
             }}
         />
      </View>
```

**Comment by mohhef** [comment]
> Hello,
> 
> I used [react-native-floating-action](https://github.com/santomegonzalo/react-native-floating-action) with react-native-elements and its working fine
> 
> ```js-jsx
>       <View style={styles.container}>
>         <SafeAreaView />
>         <Agenda items={this.state.items} />
>         <FloatingAction
>             actions={actions}
>             onPressItem={name => {
>                  console.log(`selected button: ${name}`);
>              }}
>          />
>       </View>
> ```
> 
> <img alt="Screenshot 2019-08-18 at 19 49 48" width="596" src="https://user-images.githubusercontent.com/24297303/63224057-5f337e00-c1f1-11e9-9e81-87ab6d5d6c73.png">

Can you please show your styles.

**Comment by CharnSrinivas** [comment]
In button style add 

style
{{ ...  position:'absolute' }}

It works for sure :100:
