### ISSUE TITLE
Changing state on onVisibleMonthChange in CalendarList

### ISSUE THREAD

**Issue by FranciscoSimaoPerez** [wix/react-native-calendars#884]
I had an issue that when I used setState on onVisibleMonthsChange the previous and future months would get invisible and only showed the month name and the year.

To fix this problem I added this on index.js of CalendarList:

On **contructor**:
`this.scrollTimeout = undefined;`

On **onViewableItemsChanged**:
Before:
```
if (this.props.onVisibleMonthsChange) {
      this.props.onVisibleMonthsChange(visibleMonths);
}
```
After:
```
if (this.props.onVisibleMonthsChange) {
      clearTimeout(this.scrollTimeout);
      this.scrollTimeout = setTimeout(() => {
          this.props.onVisibleMonthsChange(visibleMonths);
      }, 200);
}
```

I hope this help anyone with the same problem

**Comment by Jojr** [comment]
Thank you! This solve my  problem.

**Comment by scaralfred** [comment]
Thanks!!!

**Comment by sebzinck** [comment]
No need to change the package source code, simply do this
```
InteractionManager.runAfterInteractions(() => {
    this.setState()
})
```

**Comment by TaiPhamDuc** [comment]
> No need to change the package source code, simply do this
> 
> ```
> InteractionManager.runAfterInteractions(() => {
>     this.setState()
> })
> ```

Thanks @sebzinck it works for me
`onVisibleMonthsChange={this.onMonthChange}`
....
  onMonthChange = data => {
    InteractionManager.runAfterInteractions(() => {
      this.setState({
        isLoading: true,
        planList: [],
        markerList: {},
        // Your state
      });
    });
  };

**Comment by jcgb15** [comment]
I also have this problem I tried to use InteractionManager.runAfterInteractions but is it not working for me :(

**Comment by wbijen** [comment]
It would be great if this was included in the example code or be fixed in the source.
