### ISSUE TITLE
maybe A new feature is needed

### ISSUE THREAD

**Issue by naxiaoguang** [wix/react-native-calendars#89]
Missing pull-up load, drop refresh. Maybe pull up refresh, drop load experience better，like wechat's friends circle feature

**Comment by tautvilas** [comment]
Hi, could you upload a gif/video with example of what you mean?

**Comment by naxiaoguang** [comment]
sorry , my english is poor . just I want today item data in top for ever . and past time item data below. [http://i2.kiimg.com/1949/2bbe13c2f0cf77e2.jpg](url)

**Comment by tautvilas** [comment]
sorry this feature is not gonna be implemented for now
