### ISSUE TITLE
Error: Unable to resolve module `lodash.isequal`

### ISSUE THREAD

**Issue by kishansbs** [wix/react-native-calendars#890]
error: bundling failed: Error: Unable to resolve module `lodash.isequal` from `D:\React native project\Smart_Hospital\SH_Patient\node_modules\react-native-calendars\src\calendar\day\period\index.js`: Module `lodash.isequal` does not exist in the Haste module map

 "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-calendars": "^1.190.0",

**Comment by blazevignesh** [comment]
Any solution for this ?? Have you fixed ??

**Comment by mymattcarroll** [comment]
For me, this issue was a React-native packager cache issue.

Was able to fix it by running:

```
expo start --clear
```

**Comment by Ru5habh5hah** [comment]
`npm start -- --reset-cache` worked for me
