### ISSUE TITLE
Automated E2E testing on Android

### ISSUE THREAD

**Issue by realsilversurfer** [wix/react-native-calendars#897]
Hello guys, I am facing problem with locating days through appium inspector by selectors on Android. I tried to do that with accesibilityLabel for Android and with testID for iOS.

Is there some way how to locate elements like on iOS ?

Appium 1.13.0
iPhone X emulator 
Android emulator
![Snímek obrazovky 2019-07-30 v 10 01 56](https://user-images.githubusercontent.com/50847812/62221080-58afa480-b3b1-11e9-8c76-479f3864e74d.png)
<img width="1192" alt="Snímek obrazovky 2019-07-30 v 10 07 39" src="https://user-images.githubusercontent.com/50847812/62221081-58afa480-b3b1-11e9-8277-9e1b8661d665.png">

**Comment by realsilversurfer** [comment]
I did it.

**Comment by pavermakov** [comment]
@realsilversurfer can you please provide your solution? I think I'm facing a similar issue.

**Comment by wwjo** [comment]
> I did it.

@realsilversurfer Hi realsilversurfer, can you share how you did it?

**Comment by wwjo** [comment]
> @realsilversurfer can you please provide your solution? I think I'm facing a similar issue.

@pavermakov Hi pavermakov, do have find the solution?
