### ISSUE TITLE
Dates before "minDate" not graying out. 

### ISSUE THREAD

**Issue by kaushik618** [wix/react-native-calendars#898]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
According to the documentation in the code, the dates before minDate must be grayed out. 

## Expected Behavior

I added the mindate prop and was expecting the dates before mindate to be grayed out. 

## Observed Behavior

The dates did not gray out. 

Also specify:

1. Phone/emulator/simulator & version: Android

**Comment by AliMonam** [comment]
I have the same issue on the Agenda.
