### ISSUE TITLE
Agenda not displaying last date of month in list

### ISSUE THREAD

**Issue by sjt145** [wix/react-native-calendars#899]
Description

I am using Agenda from react-native-calendars library, it works fine with my data but its not displaying the last date of month in list below while I can see all last dates on month in header. 
Here is my render method:

```
render() {
    return (
      <Agenda
        items={this.state.items}
        loadItemsForMonth={(month) => this.datalist(month)}
        renderEmptyData={() => this.renderempty()}
        renderEmptyDate={() => this.renderemptyDate()}
        renderItem={this.renderItem.bind(this)}
        rowHasChanged={this.rowHasChanged.bind(this)}
        theme={{
          agendaKnobColor: '#f2f2f2',
          dotColor: '#185cb3',
          selectedDayBackgroundColor: '#185cb3'
        }}
      />
    );
  }
```

## Expected Behavior

It should display all dates correctly.

## Observed Behavior

![error](https://user-images.githubusercontent.com/42169958/62266095-9d385000-b444-11e9-8a6c-8d1abe05fb1f.png)

Not displaying last Date of any month in list below

## Environment

"react-native": "0.57.8",
"react-native-calendars": "^1.24.0",

**Comment by chenei** [comment]
Do you still need help?
