### ISSUE TITLE
Unable to resolve module `hoist-non-react-statics`...

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [wix/react-native-calendars#900]
![Simulator Screen Shot - iPhone Xʀ - 2019-08-02 at 08 32 32](https://user-images.githubusercontent.com/13596540/62335960-ad156a00-b500-11e9-871a-1ff7c8c6934e.png)

I run `npm install --save hoist-non-react-statics` to solve my problem. Just note that.

**Comment by iiagodias** [comment]
thanks, it helped me.

**Comment by Inbal-Tish** [comment]
Fix on version 1.225.0
