### ISSUE TITLE
Date bug: picks wrong date: -1

### ISSUE THREAD

**Issue by eliaskotov** [wix/react-native-calendars#901]
The picker is picking a wrong date. If I click the 28th, it picks the 27, if I click the 16th, it picks the 15th and so on.

We have 6 iOS and Android phones in the US and all of them are having this bug.

However, this picker is working correctly for a person in Asia both on his phone and on the emulator.

 "react-native-calendars": "^1.204.0",

Please see the video:
https://www.dropbox.com/s/slt0fgwwqf8ohj0/IMG_2869.MOV?dl=0

![Screen Shot 2019-08-05 at 11 25 15 PM](https://user-images.githubusercontent.com/25939867/62511232-4fbb3a80-b7d8-11e9-9849-83c2663addc4.png)

**Comment by akarsh0807** [comment]
the package returns timestamp at UTC 00:00 hrs for that day so if you are in a timezone with a negative offset e.g. EST has -4 hrs so the timestamp would resolve to 8 PM previous day for this either compensate for the device timezone or use the **date string** returned in the response from the package

**Comment by guibas741** [comment]
Facing the same problema, any other solutions?

**Comment by abrahamAlonzo** [comment]
if you define a custom day, instead of pass onPress component you can use the prop date in order to get the correct date.

```
const day = ({ date, children, state, onPress, marking }) => {
  const onClick = () => {
    console.log(date)
  }

  return (
    <TouchableOpacity onPress={onClick} >
      <View style={[styles.dayContainer, marking['selected'] ? { backgroundColor: 'red' } : null]}>
        <Text>{date.day}</Text>
      </View>
    </TouchableOpacity>
    )
  }

**Comment by charlestbell** [comment]
Hope this helps someone:
```  
 onDayPress={day => {
            const offsetInMiliseconds = new Date().getTimezoneOffset() * 60 * 1000; // Get timezone offset
            const currentDateWithTimezoneApplied = day.timestamp + offsetInMilliseconds
            // Do stuff
          }}
```
