### ISSUE TITLE
ExpandableCalendar renderArrow is ignored

### ISSUE THREAD

**Issue by sulagarde** [wix/react-native-calendars#903]
## Description

I use ExpandableCalendar and pass by props my own renderArrow component.
The default arrow image is display instead of my own.

## Expected Behavior

I expected that my arrow is display.

## Observed Behavior

The default arrow is display.

## Fix 
Please can you update the code of ExpandableCalendar/indes.js::renderArrow ? 😁
  ```
renderArrow = (direction) => {
    if (_.isFunction(this.props.renderArrow)) {
      this.props.renderArrow(direction);
// add return here => return this.props.renderArrow(direction);
    }
    return (
      <Image
        source={direction === 'right' ? this.props.rightArrowImageSource : this.props.leftArrowImageSource}
        style={this.style.arrowImage}
      />
    );
  }

```

**Comment by mtieltjes** [comment]
@Inbal-Tish  Got fixed a few days ago: https://github.com/wix/react-native-calendars/pull/1037

**Comment by Inbal-Tish** [comment]
@mtieltjes Thanks!
