### ISSUE TITLE
Pressing a date doesn't select

### ISSUE THREAD

**Issue by collabcoding614** [wix/react-native-calendars#905]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

Just installed a basic calendar. I didn't add anything to it.

1-2 sentences describing the problem you're having or the feature you'd like to request

Pressing on a date should select it

What action did you perform, and what did you expect to happen?

Installed. Imported basic calendar. Added to jsx.
import { Calendar } from "react-native-calendars";
<Calendar />

What actually happened when you performed the above actions?

- When you press on a date nothing happens

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
npm WARN deprecated babel-plugin-module-alias@1.6.0: WARNING: This project has been renamed to babel-plugin-module-resolver. Install babel-plugin-module-resolver for new features
canapp@ /Users/natedeazy/projects/cannabis-app/canapp
└── UNMET DEPENDENCY react-native-calendars@^1.208.0

npm ERR! missing: react-native-calendars@^1.208.0, required by canapp@
* `npm ls react-native`:
npm WARN deprecated babel-plugin-module-alias@1.6.0: WARNING: This project has been renamed to babel-plugin-module-resolver. Install babel-plugin-module-resolver for new features
canapp@ /Users/natedeazy/projects/cannabis-app/canapp
└── (empty)

Also specify:

1. Phone/emulator/simulator & version:

iphone 8 plus and iphone x simulator

## Reproducible Demo

yarn add react-native-calendars
import { Calendar } from "react-native-calendars";
<Calendar />
- Press on a date (NOTHING HAPPENS, NO HIGHLIGHTING OF DATE)

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by minh-dai** [comment]
me too :))) Pressing a date doessn't select

**Comment by jtweaver** [comment]
Also having this issue. It's not that onDayPress isn't registering a press, it's that current={} does nothing. Even when entering tomorrow's date into current (current={'2019-08-21'}), the date does not have any different styling and does not use the styling provided in "selectedDayBackgroundColor" or "selectedDayTextColor" (if provided).

**Comment by collabcoding614** [comment]
This has nothing to do with the programmatic functionality and attaching event handlers. It literally has only to do with the most basic functionality of this calendar. Just using plain react component

<Calendar/>

U see the calendar render and when u press on the dates it doesn't highlight what you press on the way the docs explain it. I don't get it, this is literally the most basic functionality of any calendar of ever? For this most basic operation not to work is not good. Not sure how this calendar component even exists if u cant do the basics

**Comment by nabrams** [comment]
@collabcoding614 any progress on finding a solution? I am having the same issue.

if I insert <Calendar/> I do not see the dot either and even if I save the date on press to the local state and set the current to that date, nothing happens

**Comment by genuinezack** [comment]
Also seeing this - rendering it even in its most basic form of `<Calendar />` just does not appear to work at all on React Native 0.59.x? Clicking on days causes the highlight state but does not cause the "selection dot" to appear.

**Comment by usungsoft** [comment]
@jtweaver thanks for your work. i was also looking for how to deal with it, and seems like that`s the only way we could mark selected dated unless there's no exact props for selected date.

**Comment by astalarico** [comment]
This seems to happen, for me as well, only when using an emulator, currently an android emulator ( Pixel 2). When I debug on an actual android device (Samsung Galaxy S9+) the problem isn't there.

**Comment by Muratoter** [comment]
Try stop remote JS Debugging from developer menu.

**Comment by karanwadhwa** [comment]
you could set a `selectedDay` key in your component state and then add it to your markedDates prop by spreading your markedDates object and adding a new object with key `selectedDay` and value `{selected: true}`. 

```js
this.state = {
  events: {
{"2019-12-15": { /*  blah blah blah  */ }},
{"2019-12-16": { /*  blah blah blah  */ }},
{"2019-12-17": { /*  blah blah blah  */ }}
},
  selectedDay: ""
}
```

```js
<Calendar
onDayPress={day => this.setState({ selectedDate: day.dateString })}
markedDates={{
              ...this.state.events,
              [this.state.selectedDate]: { selected: true }
            }}
/>
```

**Comment by karanwadhwa** [comment]
you could set a `selectedDate` key in your component state and then add it to your markedDates prop by spreading your markedDates object and adding a new object with key of the selectedDate with value `{selected: true}`. 

```js
this.state = {
  events: {
{"2019-12-15": { /*  blah blah blah  */ }},
{"2019-12-16": { /*  blah blah blah  */ }},
{"2019-12-17": { /*  blah blah blah  */ }}
},
  selectedDay: ""
}
```

```js
<Calendar
onDayPress={day => this.setState({ selectedDate: day.dateString })}
markedDates={{
              ...this.state.events,
              [this.state.selectedDate]: { selected: true }
            }}
/>
```
