### ISSUE TITLE
Mark days in between a starting and an ending day

### ISSUE THREAD

**Issue by wmonecke** [wix/react-native-calendars#910]
Hi!

Maybe I am missing something but when selecting a starting day and an ending day, the days in between do not get marked. I thought this would happen automatically.

Do I have to manually indicate the in-between days that have to be marked?

Thank you!

**Comment by zkkg2018** [comment]
I have the same problem

**Comment by OlegPanfyorov** [comment]
Same problem

**Comment by wmonecke** [comment]
I made a custom function that calculates the date inbetween two selected dates!

````
  deriveInBetweenMarkedDaysFromSelectedDays(day, month, year) {
    const { customStartDate } = this.state

    const endingMoment = moment({ day, month: month-1, year });
    const startingMoment = moment({ day: customStartDate.day, month: customStartDate.month-1, year: customStartDate.year });
    const daysBetweenDates = endingMoment.diff(startingMoment, 'days')-1;

    let inBetweenMarkedDays = {};
    for (let i = 1; i <= daysBetweenDates; i++) {
     let nextMoment = moment({ day: customStartDate.day, month: customStartDate.month-1, year: customStartDate.year }).add({ days: `${i}` });
     inBetweenMarkedDays[`${nextMoment.format('YYYY')}-${nextMoment.format('MM')}-${nextMoment.format('DD')}`] = { color: 'rgb(32, 177, 250)', selected: true };
    }

    return inBetweenMarkedDays;
  }
````

**Comment by chenei** [comment]
You do need to specify all the dates in ‘markedDates’

**Comment by Azarians** [comment]
let markedDates = {};

		calendar.events?.map((event, i) => {
		let eventStart = event.start.slice(0,10),
				eventEnd   = event.end.slice(0,10);

		if(eventStart != eventEnd){
			let eventStartPlusOne = eventStart;

			while(eventStartPlusOne != moment(eventEnd).add(1, 'day').format("YYYY-MM-DD")){
				if(markedDates[eventStartPlusOne] && markedDates[eventStartPlusOne].dots.length < 2){
					markedDates[eventStartPlusOne].dots.push({color: "red"});
				}
				else if(!markedDates[eventStartPlusOne]){
					markedDates[eventStartPlusOne] = {dots: [{color: "red"}]};
				}
				eventStartPlusOne = moment(eventStartPlusOne).add(1, 'day').format("YYYY-MM-DD");
			}
		}
		else if(markedDates[eventStart] && markedDates[eventStart].dots.length < 2){
			markedDates[eventStart].dots.push({color: "red"});
		}
		else if(!markedDates[eventStart])
			markedDates[eventStart] = {dots: [{color: "red"}]};
