### ISSUE TITLE
iphone 6 random render header wrong

### ISSUE THREAD

**Issue by trinhak** [wix/react-native-calendars#911]
![Screen Shot 2019-08-27 at 11 11 10 AM](https://user-images.githubusercontent.com/36026361/63740544-ad184800-c8bb-11e9-8195-9ca4b5511af5.png)

when i click calender screen then render header wrong, but it just random, i don't know the rule
Detail:  "react-native-calendars": "^1.141.0"
pls help me??

**Comment by budo60** [comment]
in order to have a proper header, i notice  your calendar list need to have 1 extra month before and one extra month after the list of  month you aim to show
