### ISSUE TITLE
disabledByDefault = true, but still able to trigger event handler onDayPress.

### ISSUE THREAD

**Issue by yaserloz** [wix/react-native-calendars#917]
## Description

I made ``disabledByDefault = {true}``, but when i click on disabled date(``onDayPress``) it still trigger the event handler on the disabled day

## Expected Behavior

when ``disabledByDefault = {true}``, ``onDayPress`` should not trigger un event

## Observed Behavior

still able to trigger the event handler ``onDayPress`` even if disabledByDefault = {true}.

**Comment by shachardevops** [comment]
+1

**Comment by chenei** [comment]
Please check the new disableAllTouchEventsForDisabledDays prop.
