### ISSUE TITLE
Agenda: get new selected date without pressing on new date?

### ISSUE THREAD

**Issue by bethqiang** [wix/react-native-calendars#92]
![wix_calendar_agenda_selected_date_resize](https://user-images.githubusercontent.com/20443660/28122972-5c4991ac-66e5-11e7-8ce5-6283caca9bf7.gif)

In this gif, the 12th is the "selected date." When you scroll down in the second half of the agenda component, the "selected" marker (the circle around the date) moves to the 15th without actually pressing on the 15th. In the component itself, I'm passing a function that changes the selected date on press (which, for demonstration purposes, is then being rendered as text above the agenda). However, when the selected date changes without the press, the date in the state doesn't change, so the state still has the 12th as the date. Is there a way to detect this change and set the state when it does?

**Comment by tautvilas** [comment]
Did you try to use the `onDayChange` property of agenda? It accepts callback that is called when day changes as you scroll agenda

**Comment by bethqiang** [comment]
@tautvilas my bad, I didn't realize that was a property. It works - thanks so much!
