### ISSUE TITLE
How to highlight multiple days? The Documentation seems incorrect. Please help.

### ISSUE THREAD

**Issue by prospkarl** [wix/react-native-calendars#922]
<img width="346" alt="Screen Shot 2019-09-05 at 6 49 33 PM" src="https://user-images.githubusercontent.com/54798409/64335695-f2e8b500-d00d-11e9-8fb4-b10da7d7ea62.png">

**My Code:**

<img width="1032" alt="Screen Shot 2019-09-05 at 6 51 12 PM" src="https://user-images.githubusercontent.com/54798409/64335808-288d9e00-d00e-11e9-8985-d2c86d85bdca.png">

**Comment by atapin** [comment]
@prospkarl there's a disclaimer: 

> !Disclaimer! Make sure that markedDates param is immutable. If you change markedDates object content but the reference to it does not change calendar update will not be triggered.

I think you need to update the state of marked dates this way:

```
let markedDates = {...this.state.markedDates, {key: {customStyles: <...>}}}
this.setState <...>
```

**Comment by prospkarl** [comment]
> @prospkarl there's a disclaimer:
> 
> > !Disclaimer! Make sure that markedDates param is immutable. If you change markedDates object content but the reference to it does not change calendar update will not be triggered.
> 
> I think you need to update the state of marked dates this way:
> 
> ```
> let markedDates = {...this.state.markedDates, {[key]: {customStyles: <...>}}}
> this.setState <...>
> ```

Thanks it worked for me!
