### ISSUE TITLE
is there anyway to export as ical file format and sync with other device?

### ISSUE THREAD

**Issue by yrong** [wix/react-native-calendars#925]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
* `npm ls react-native`:

Also specify:

1. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by bkniffler** [comment]
You didn't even fill the whole template in. 

Anyways, I'm not a maintainer, but I can very clearly tell you that this is out of scope of the project. React-native-calendar is only a UI component.

**Comment by yrong** [comment]
It is ok to keep focused.  But is there any  explanation about data model or some guideline how to handle with data so that we can do more things based on this project?

**Comment by bkniffler** [comment]
react-native-calnedars is completely agnostic to what data model you use, it defines what props it needs (there is even a typesript pacckage) and they are well documented. Again, in my opinion, this is completely out of scope of a ui component. You will need to figure out your own (using something like http://mozilla-comm.github.io/ical.js/). 

As an analogy, asking this kind of questions is like going to someone who hands out free apples from his apple tree and asking for a recipe for a Kielbasa apple & onion skillet. Take the free apples and be watching for recipes somewhere in the bigger community (discord, stackoverflow etc), stop expecting that guy to provide you with recipes when maintaining the apple tree is already a lot of work.
