### ISSUE TITLE
How to display from fetched API to ExpandableCalendar

### ISSUE THREAD

**Issue by SPineapple** [wix/react-native-calendars#927]
In ExpandableCalendar , How the AgendaList actually works with the sections? Does it accept only the same format and structure as ITEMS? 
```
const ITEMS = [
  {title: dates[0], data: [{hour: '12am', duration: '1h', title: 'Ashtanga Yoga'}]},
  {title: dates[1], data: [{hour: '4pm', duration: '1h', title: 'Pilates ABC'}, {hour: '5pm', duration: '1h', title: 'Vinyasa Yoga'}]},
  {title: dates[2], data: [{hour: '1pm', duration: '1h', title: 'Ashtanga Yoga'}, {hour: '2pm', duration: '1h', title: 'Deep Streches'}, {hour: '3pm', duration: '1h', title: 'Private Yoga'}]},
  {title: dates[3], data: [{hour: '12am', duration: '1h', title: 'Ashtanga Yoga'}]},
  {title: dates[4], data: [{}]}
]
```
 Because I don't have a nested array to extract the data, I have an array of objects that has all the dates and data I need, and How do I do that?  
```
const testITEMS = [
{
"dateStart": "2019-09-15",
"dateEnd": "2019-09-15",
"title": "From 10",
"timeStart": "10:00",
"timeEnd": "12:00",
"address": "",
"description": ""
},
{
"dateStart": "2019-09-16",
"dateEnd": "2019-09-16",
"title": "From 10",
"timeStart": "10:00",
"timeEnd": "12:00",
"address": "",
"description": ""
}
]
```
I have tried to tackle ITEMS, but it didn't work out with me?

It would be very much helpful if anyone provided another example of ExpandableCalendar with api request, 
please, thanks.

**Comment by SPineapple** [comment]
Can anyone  please provide another example of ExpandableCalendar, with the usage of fetched data from api request and using `onDateChanged`  `onMonthChange`?

**Comment by georgessaroufim** [comment]
`import React from 'react';
import moment from 'moment';
import { View, SafeAreaView } from 'react-native';
import { Calendar } from 'react-native-calendars';


const _format = 'YYYY-MM-DD'
const _today = moment().format(_format)
const _maxDate = moment().add(15, 'days').format(_format)

const all_dates = [
  '2019-09-23',
  '2019-09-24',
  '2019-09-25',
  '2019-09-26',
  '2019-09-27',
]

export default class App extends React.Component {
  // It is not possible to select some to current day.
  initialState = {
    [_today]: { marked: true },
  }

  constructor() {
    super();

    this.state = {
      _markedDates: this.initialState
    }
  }

  toDateString(day) {
    return moment(day.dateString).format(_format);
  }

  componentWillMount() {
    let obj;
    for (i = 0; i < all_dates.length; i++) {
      obj = Object.assign(this.state._markedDates, { [all_dates[i]]: { marked: true } })
    }
    this.setState({ _markedDates: obj })
  }

  onDaySelect = (day) => {
    const _selectedDay = moment(day.dateString).format(_format);
    console.log(_selectedDay)

    let marked = true;
    let markedDates = {}
    if (this.state._markedDates[_selectedDay]) {
      marked = !this.state._markedDates[_selectedDay].marked;
      markedDates = this.state._markedDates[_selectedDay];
    }

    markedDates = { ...markedDates, ...{ marked } };
    const updatedMarkedDates = { ...this.state._markedDates, ...{ [_selectedDay]: markedDates } }
    this.setState({ _markedDates: updatedMarkedDates });
  }

  render() {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Calendar
          theme={{
            dotColor: 'pink',
          }}

          // we use moment.js to give the minimum and maximum dates.
          minDate={_today}
          maxDate={_maxDate}

          // hideArrows={true}

          onDayPress={this.onDaySelect}
          markedDates={this.state._markedDates}
        />
      </SafeAreaView>
    );
  }
}`

This worked for me !!

**Comment by georgessaroufim** [comment]
`const all_dates = [
  '2019-09-23',
  '2019-09-24',
  '2019-09-25',
  '2019-09-26',
  '2019-09-27',
]

 componentWillMount() {
    let obj;
    for (i = 0; i < all_dates.length; i++) {
      obj = Object.assign(this.state._markedDates, { [all_dates[i]]: { marked: true } })
    }
    this.setState({ _markedDates: obj })
  }
`

**Comment by georgessaroufim** [comment]
import React from 'react';
import moment from 'moment';
import { View, SafeAreaView } from 'react-native';
import { Calendar } from 'react-native-calendars';


const _format = 'YYYY-MM-DD'
const _today = moment().format(_format)
const _maxDate = moment().add(15, 'days').format(_format)

const all_dates = [
  '2019-09-23',
  '2019-09-24',
  '2019-09-25',
  '2019-09-26',
  '2019-09-27',
]

export default class App extends React.Component {
  // It is not possible to select some to current day.
  initialState = {
    [_today]: { marked: true },
  }

  constructor() {
    super();

    this.state = {
      _markedDates: this.initialState
    }
  }

  toDateString(day) {
    return moment(day.dateString).format(_format);
  }

  componentWillMount() {
    let obj;
    for (i = 0; i < all_dates.length; i++) {
      obj = Object.assign(this.state._markedDates, { [all_dates[i]]: { marked: true } })
    }
    this.setState({ _markedDates: obj })
  }

  onDaySelect = (day) => {
    const _selectedDay = moment(day.dateString).format(_format);
    console.log(_selectedDay)

    let marked = true;
    let markedDates = {}
    if (this.state._markedDates[_selectedDay]) {
      marked = !this.state._markedDates[_selectedDay].marked;
      markedDates = this.state._markedDates[_selectedDay];
    }

    markedDates = { ...markedDates, ...{ marked } };
    const updatedMarkedDates = { ...this.state._markedDates, ...{ [_selectedDay]: markedDates } }
    this.setState({ _markedDates: updatedMarkedDates });
  }

  render() {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Calendar
          theme={{
            dotColor: 'pink',
          }}

          // we use moment.js to give the minimum and maximum dates.
          minDate={_today}
          maxDate={_maxDate}

          // hideArrows={true}

          onDayPress={this.onDaySelect}
          markedDates={this.state._markedDates}
        />
      </SafeAreaView>
    );
  }
}

**Comment by georgessaroufim** [comment]
import React from 'react';
import moment from 'moment';
import { View, SafeAreaView } from 'react-native';
import { Calendar } from 'react-native-calendars';


const _format = 'YYYY-MM-DD'
const _today = moment().format(_format)
const _maxDate = moment().add(15, 'days').format(_format)

const all_dates = [
  moment().add(1, 'days').format(_format),
  moment().add(2, 'days').format(_format),
  moment().add(3, 'days').format(_format),
  moment().add(4, 'days').format(_format),
  moment().add(5, 'days').format(_format),
]

export default class App extends React.Component {
  constructor() {
    super();

    this.state = {
      _markedDates: {}
    }
  }

  toDateString(day) {
    return moment(day.dateString).format(_format);
  }

  componentWillMount() {
    let obj;
    for (i = 0; i < all_dates.length; i++) {
      obj = Object.assign(this.state._markedDates, { [all_dates[i]]: { marked: true } })
    }
    this.setState({ _markedDates: obj })
  }

  onDaySelect = (day) => {
    const _selectedDay = moment(day.dateString).format(_format);
    console.log(_selectedDay)

    let marked = true;
    let markedDates = {}
    if (this.state._markedDates[_selectedDay]) {
      marked = !this.state._markedDates[_selectedDay].marked;
      markedDates = this.state._markedDates[_selectedDay];
    }

    markedDates = { ...markedDates, ...{ marked } };
    const updatedMarkedDates = { ...this.state._markedDates, ...{ [_selectedDay]: markedDates } }
    this.setState({ _markedDates: updatedMarkedDates });
  }

  render() {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <Calendar
          theme={{
            dotColor: 'pink',
          }}
          minDate={_today}
          maxDate={_maxDate}

          // hideArrows={true}

          onDayPress={this.onDaySelect}
          markedDates={this.state._markedDates}
        />
      </SafeAreaView>
    );
  }
}

**This worked for me !!**

**Comment by SPineapple** [comment]
Thank you for the response, but I meant for this type of calendar : https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js 

I managed to display the events, except that I want it to display from starting day of event until the end day of event. and I don't know how to do it in this type of calendar.

**Comment by chenei** [comment]
@SPineapple did you manage to do that?

**Comment by SPineapple** [comment]
@chenei I still don't know how to display recurrent event? like from start date until the end of date, as between these dates will show the items in calendar. I hope I have explained my question well. Thanks in advance

**Comment by chenei** [comment]
Did you check our examples? With period markingType?

**Comment by SPineapple** [comment]
But I don't want to mark, I want to display the same item n times between start and end date.. maybe I missed something?

**Comment by chenei** [comment]
Can you upload a design/sketch of what you are trying to achieve?

**Comment by SPineapple** [comment]
@chenei Hi, sorry for the late response. This is how I wanted the to display the items:

Suppose that I have a meeting for 5 days in a row, instead of creating an array of objects like this:

```
const ITEMS = [
  {
    title: dates[0],
    data: [
{ hour: "12am",
 duration: "1h",
 title: "Ashtanga Yoga" }],
  },
  {
    title: dates[1],
    data: [
{ hour: "12am", 
duration: "1h",
 title: "Ashtanga Yoga" }],
  },....]
```

I would just have an extra object that reads the end of meeting like so:

```
const ITEMS = [
  {
    title: dates[0],
    data: [{ hour: "12am", 
duration: "1h", 
title: "Ashtanga Yoga" , 
end_date:'2020-06-11'}],
  }
]
```

and it would render it this way:

<img width="317" alt="Screen Shot 2020-06-09 at 6 49 45 PM" src="https://user-images.githubusercontent.com/18646285/84170508-7d20e680-aa82-11ea-9ce7-bba0721203e6.png">

How can achieve this? Or  maybe there's another concept that would achieve this goal?
