### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by vijayst** [wix/react-native-calendars#93]
The example in the ReadMe.md needs to be updated. I had problems with both onDayPress and selected. Though I could figure out looking at the code, it will be nice if the document is updated for new developers who want to try the calendar. Overall, I found the calendar useful for my project. Thanks.

**Comment by tautvilas** [comment]
Hi, thx for feedback, I would appreciate if you would submit pull request to readme with updates that you have in mind, thx :)

**Comment by vijayst** [comment]
While trying to update the documentation, I found the information that I wanted. 

onDayPress:

> Event handler callbacks are called with calendar objects like this:
> 
> ```
> {
>   day: 1,     // day of month (1-31)
>   month: 1,   // month of year (1-12)
>   year: 2017, // year
>   timestamp,   // UTC timestamp representing 00:00 AM of this date
>   dateString: '2016-05-13' // date formatted as 'YYYY-MM-DD' string
> }
> ```

The selected Prop in the ReadMe is used for `Agenda` and not `Calendar`. I used selected with Calendar. And Calendar accepts an array for the prop, and not a single date string.

I think the documentation is accurate. So, I am closing the issue.
