### ISSUE TITLE
How do I modify Agenda's Markingtype from 'period' to 'number'?

### ISSUE THREAD

**Issue by punreachrany** [wix/react-native-calendars#932]
Instead to a dot below the date, how can I make another number  appear below the date?
I want that number to represent the number of tasks i will be doing on that day.

**Comment by punreachrany** [comment]
![download](https://user-images.githubusercontent.com/54469196/65298672-3e22cc00-dba7-11e9-9b22-5e4e088c8d3f.jpg)

![1_pRdVFYAVRtXuqmp-puKFIQ](https://user-images.githubusercontent.com/54469196/65298675-4418ad00-dba7-11e9-8996-57ba9a487701.gif)

**Comment by Bright24** [comment]
Hi @punreachrany,
You can look at #936 for the solution.
