### ISSUE TITLE
How I am working with calendar horizontal per week?

### ISSUE THREAD

**Issue by christian-de-ornellas** [wix/react-native-calendars#933]
I am development a component and need calendar horizontal per week, The possible?

**Comment by loicboyeldieu** [comment]
You can follow this example: [https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js](expandableCalendar) and remove the AgendaList and you will have an horizontal calendar per week extendable to a grid.

**Comment by christian-de-ornellas** [comment]
> You can follow this example: [expandableCalendar](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendar.js) and remove the AgendaList and you will have an horizontal calendar per week extendable to a grid.

Thank very much!
