### ISSUE TITLE
Custom text below the date instead of a dot.

### ISSUE THREAD

**Issue by Bright24** [wix/react-native-calendars#936]
## Description

Is it possible to display a custom component under the date instead of the dot for markedDates. I essentially want to show how many events are there in a day.
I started out with a custom dateComponent when I realized that I would have to write all the event handlers associated with it. Is there a way to just show a custom text at that place without disturbing any of the other calendar/agenda behaviour?

## Environment
* `npm ls react-native-calendars`: `-- react-native-calendars@1.212.0 
* `npm ls react-native`: `-- react-native@0.59.8 (I'm running an expo project)
*  emulator version: 29.1.12-5839083 on Android 9 (Pie) - API 28

**Comment by Bright24** [comment]
Sorry just found that someone else also asked the same thing. #932

**Comment by Bright24** [comment]
In case somebody is looking for it. Found #703 helpful.
I nevertheless did it with the dayComponent, probably this is way it should be done. 
```
render() {
return  (<Agenda
      ....
      dayComponent={renderDayComponent}
      .....>
   </Agenda>)
}

renderDayComponent = data => <CalendarDayComponent {...data} />;
```
to restore the default behavior of onPress 
```
const CalendarDayComponent => props {
   const { date, marking, state, onPress, itemsData, children } = props;
    onPressed = () => {
        requestAnimationFrame(() => onPress(date));
    }
    let items = '';

    if (marking.marked) {
        items = itemsData[date.dateString].length
    }
return (
        <View style={styles.container}>
            <Text onPress={onPressed} style={{ color: state === 'disabled' ? 'gray' : 'black' }}>
                {children}
            </Text>
            <Text style={styles.itemsCount}>
                {items}
            </Text>
        </View>
    )
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        margin: 12,
    },
    dayItem: {
        textAlign: 'center',
        fontFamily: 'roboto'
    },
    itemsCount: {
        textAlign: 'center',
        fontFamily: 'roboto',
        fontSize: 11,
        color: colors.alert
    }
})

export default CalendarDayComponent;
```

**Comment by drashti4** [comment]
What we supposed to pass in calendardata attribute for props in renderDayComponent?

**Comment by soo9028** [comment]
Thanks. This is just what I needed :)
