### ISSUE TITLE
Agenda show empty before expand it

### ISSUE THREAD

**Issue by devgeeksclub** [wix/react-native-calendars#941]
Agenda show empty before expand it , (this screen shot from IOS simulator)
![Simulator Screen Shot - iPhone X - 2019-09-28 at 15 26 43](https://user-images.githubusercontent.com/50441591/65816482-ba9b5780-e204-11e9-8b97-141bb705e799.png)

it show the empty position as shown in the below picture

![Simulator-Screen-Shot---iPhone-X---2019-09-28-at-15 26 59](https://user-images.githubusercontent.com/50441591/65816481-ba9b5780-e204-11e9-8239-9fc22639bcba.gif)

it should display the current selected day

here is my code

```
<Agenda
      items={items}
      loadItemsForMonth={props.loadItems}
      onCalendarToggled={calendarOpened => {
        console.log('onCalendarToggled', calendarOpened);
      }}

      onDayPress={day => {
        console.log('day pressed');
      }}
      selected={minData}
      minDate={minData}
      renderItem={props.renderItem ? props.renderItem : renderItem}
      rowHasChanged={props.rowHasChanged ? props.rowHasChanged : rowHasChanged}
      pastScrollRange={0}
      futureScrollRange={2}
      scrollEnabled={true}
      renderEmptyData={() => {
        return (
          <View style={styles.emptyData}>
            <Text>
              <FormattedMessage {...messages.noRecords} />
            </Text>
          </View>
        );
      }}

    />
```

Am I missing something?

**Comment by longb1997** [comment]
try to change the version to 1.212.0
I was fixed by 10 minutes ago

**Comment by Inbal-Tish** [comment]
@devgeeksclub Please see @longb1997 comment.
