### ISSUE TITLE
How to prevent collapsing calendar when we select the date in Agenda.

### ISSUE THREAD

**Issue by ppv94** [wix/react-native-calendars#943]
## Description

When I select the date in agenda the calendar collapses and agenda is displayed.
How can I prevent collapsing the calendar when the date is selected. display only the selected date Agenda.

## Expected Behavior

When we select the date the calendar should not collapse and display the Agenda of the selected date only.

## Observed Behavior

When we select the date the calendar collapses and Agenda is shown, And next day Agendas are also shown.

can we do as shown in the below image?
![Screen Shot 2019-09-30 at 12 36 29 PM](https://user-images.githubusercontent.com/28724702/65856348-02de8500-e37f-11e9-9ec7-191c0197b7f7.png)

**Comment by Inbal-Tish** [comment]
@ppv94 You can control the items you pass the Agenda when onDayPress event fires.
