### ISSUE TITLE
[Question] Is a typescript port welcome?

### ISSUE THREAD

**Issue by Grohden** [wix/react-native-calendars#947]
## Description

I've been working for some days now [to port most of this lib sources to typescript](https://github.com/Grohden/react-native-calendars/tree/ts-port). **The port is still a WIP**, there are some weird code at some places that are really hard to understand and annotate, I'm also trying to keep the same behavior (even the [possible useless ones](https://github.com/Grohden/react-native-calendars/blob/82f7be5a2fd69312ad0ed9b99c0ab9975453753c/src/calendar/index.tsx#L62-L126))...

But anyway, before I do more work on the sources I would like to know if the typescript port could be useful for the project.

**Comment by Grohden** [comment]
For the record, I decided to implement the calendars + agenda + date picker from zero: https://github.com/keepfy/keepfy-react-native-calendars

But I'm not very motivated right now, so it will take time for me to implement stuff (maybe when I get my degree at the end of the year?), there's a TODO list so if someone wants to help, it will be welcome - but as I said, it will take time.

**Comment by Inbal-Tish** [comment]
@Grohden Typescript support is not currently in the Agenda. If you like to add it to the project PRs are very welcome.

**Comment by Grohden** [comment]
@chenei it's on the linked repo, it was fully typed, but I remember that something was broken... probably on agenda 🤔.

If someone wishes to fork my fork and merge master and then open a PR here I'm ok with it
