### ISSUE TITLE
Agenda swipe down interaction should either be improved or removed

### ISSUE THREAD

**Issue by shamilovtim** [wix/react-native-calendars#950]
#### Issue Description

Swiping down on the Agenda requires too much force and too much down-velocity and does not correspond with the interactions that the average user is used to having. After enough frustration, the user must resort to tapping on the toggle in order to interact with the monthly view. 

Given these facts, the swipe-down interaction should either be fixed or it can be removed in order to avoid user frustration.

![RPReplay_Final1570146103](https://user-images.githubusercontent.com/3495974/66216216-134e7280-e693-11e9-90e3-f3b824554b2f.gif)

#### Expected Results

A standard down-swipe should be all that is required to display the monthly view.

**Comment by Inbal-Tish** [comment]
Duplication for issue #951
