### ISSUE TITLE
Calendar: current prop causes month arrows to stop working.

### ISSUE THREAD

**Issue by Miyaguisan** [wix/react-native-calendars#961]
## Description

Setting the **_current_** prop on **_Calendar_** prevents the month arrows from working.

## Expected Behavior

1. Able to view the Calendar initially at any given date.
2. Able to move between months.

## Observed Behavior

- Calendar does start at month / year of given date.
- Month arrows do nothing.
- If I remove the **_current_** prop, the calendar works just as expected and I'm able to move between months.

## Environment

react-native-calendars@1.212.0
react-native@0.61.2

iOS Device | iPhone XR | iOS 13
Android Emulator | Pixel | Android 10.0

## Reproducible Demo

- Not at the moment.

**Comment by BrickmanRodrigo** [comment]
I'm having the same issue, when current prop is set, months arrows stop working

**Comment by Inbal-Tish** [comment]
@Miyaguisan I can't reproduce this issue. Can you add more details like a code snippet and a video?

**Comment by IronLady** [comment]
I'm having the same issue too. 
Problem is when we use custom onMonthChange that modifying the state. I think it's related to how the component re-render. 

By using "current" props the arrow won't work, but without "current" props everything is fine. 
```javascript
<Calendar
    current={'2020-03-01'}
    minDate={'2020-03-01'}
    hideExtraDays={true}
    maxDate={'2021-01-01'}
    onMonthChange={(date) => {
        this.setState({
            ...this.state,
            markedDates: this.getDaysInMonth(date.month - 1, date.year)
        })
    }}
    onDayPress={this.onDayPress}
    markedDates={this.state.markedDates}
/>
```

What I am trying to do with this are disable all dates except for the dates I passed in navigation params. 
```javascript
getDaysInMonth(month, year) {
    const { data } = this.props.navigation.state.params;

    let start = moment().month(month).year(year).startOf('month');
    let days = start.daysInMonth();

    let dates = {}
    const disabled = { disabled: true, disableTouchEvent: true }
    for (let index = 1; index <= days; index++) {
        if( data.active_dates && data.active_dates.length > 0 ){
            if( data.active_dates.includes( start.date(index).format("YYYY-MM-DD") ) === false ){
                dates[start.date(index).format("YYYY-MM-DD")] = disabled
            }
        }
    }

    return dates;
}
```
