### ISSUE TITLE
Calendar Showing an extra week

### ISSUE THREAD

**Issue by markkdev** [wix/react-native-calendars#964]
## Description

I'm doing a very basic calendar set up but as its rendering im getting a column of extra days outside of Sunday-Saturday.

## Expected Behavior
It shouldnt be showing an extra week.
What action did you perform, and what did you expect to happen?
 <Calendar

        style={styles.calendar}
        current={selectedDate}
        minDate={todaysDate}
        maxDate={oneYearAhead()}
        onDayPress={(day) => { selectDate(day.dateString) }}
        onDayLongPress={(day) => { console.log('selected day', day) }}
        monthFormat={'MMMM yyyy'}
        onMonthChange={(month) => { console.log('month changed', month) }}
        hideArrows={false}
        markedDates={markedDates}
        hideExtraDays={true}
        disableMonthChange={true}
        hideDayNames={false}
        showWeekNumbers={true}
      />

## Observed Behavior

<img width="311" alt="Screen Shot 2019-10-18 at 12 27 46 PM" src="https://user-images.githubusercontent.com/34495635/67122628-1709eb00-f1a3-11e9-9ab6-b94ef7dce94d.png">

System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-27 | Android TV Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

Phone/emulator/simulator & version:
Android pixel 3a 

but this also happens with iOS

**Comment by rszalski** [comment]
You mean the column with numbers 40/41/42/43/44? These are week numbers and I believe you can hide them using `showWeekNumbers={false}`

**Comment by Inbal-Tish** [comment]
@markkdev As @rszalski was saying, delete this row from your code: `showWeekNumbers={true}`.

**Comment by markkdev** [comment]
Uninstalled and re installed package and this bug went away. Closing this issue.
