### ISSUE TITLE
Date element is masked

### ISSUE THREAD

**Issue by 000xuandu** [wix/react-native-calendars#966]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I am having a dump problem every day the item when using Agenda.
![Screenshot_2019-10-21-15-57-39-83](https://user-images.githubusercontent.com/33916400/67191981-e03f0980-f41c-11e9-9603-372c72cfdce3.png)

It seems that it is covered

## Expected Behavior

I tried changing Agenda's height, but it didn't work.
`
style={{
 height: 600
}}`

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.212.0
* `npm ls react-native`: 0.59.10

**Comment by Inbal-Tish** [comment]
@000xuandu Please check if this issue is relevant, we have a fix for it recently.

**Comment by 000xuandu** [comment]
> @000xuandu Please check if this issue is relevant, we have a fix for it recently.

@Inbal-Tish 
I will check in and notify you as soon as possible.
