### ISSUE TITLE
Disable the touchable opacity effect

### ISSUE THREAD

**Issue by Saad-Bashar** [wix/react-native-calendars#967]
Can I disable the touchable opacity effect when onPress date?

**Comment by Inbal-Tish** [comment]
@Saad-Bashar Pass 'disableTouchEvent' to the date in `MarkedDates`. Example:
`
markedDates={{
            '2012-05-23': {selected: true, marked: true, disableTouchEvent: true},
            '2012-05-24': {selected: true, marked: true},
          }}
`

**Comment by Saad-Bashar** [comment]
Great. Thanks

**Comment by bmitioglov** [comment]
@Inbal-Tish Could you tell pls how can I enable touchable opacity effect on marked dates?
