### ISSUE TITLE
Please add Hide Calendar option in Agenda

### ISSUE THREAD

**Issue by BatAbhi** [wix/react-native-calendars#968]
Needed an option to hide calendar in agenda. When user clicks on knob and the calendar is expanded its quite difficult for user to understand how to close the calendar.

**Comment by musadiq-jinbade** [comment]
any update on this?

**Comment by Inbal-Tish** [comment]
@BatAbhi The Calendar is closed when selecting a date. Do you mean to have another way to close the calendar? "hide" the calendar has a completely different meaning...

**Comment by powerlimit** [comment]
+1 
is it possible to make button that will close calendar without selecting a date?

**Comment by iqorlobanov** [comment]
+1

**Comment by flobady** [comment]
I believe this is a duplicate with:
https://github.com/wix/react-native-calendars/issues/937

**Comment by Inbal-Tish** [comment]
@flobady Yes. It is a duplication of #937. Thanks!
