### ISSUE TITLE
Wrong agenda calendar height when navigating inside StackNavigator

### ISSUE THREAD

**Issue by naxiaoguang** [wix/react-native-calendars#97]
I have two screens in StackNavigator,   launch screen is AgendaScreen . when change to SecondScreen then change back to AgendaScreen  , calendar list height wrong and knob can not drag   <img src="http://chuantu.biz/t5/134/1499944143x1875537697.png" style="width:200px" />

**Comment by darleikroth** [comment]
I got the same issue.

**Comment by overengineered** [comment]
@naxiaoguang @darleikroth it would enable us fix this issue faster if you could create a small sample project where this problem reproduces.

**Comment by tautvilas** [comment]
@naxiaoguang plz verify the fix in 1.5.5
