### ISSUE TITLE
state update is preventing the CalendarList rendering

### ISSUE THREAD

**Issue by Yandamuri** [wix/react-native-calendars#978]
## Description

When month is changed, `onVisibleMonthsChange `is triggered where I am doing the data fetching. Since Data fetching is an asynchronous operation i tried to render a spinner with state update. This is where problem starts. This state update is preventing the CalendarList rendering, Instead rendering only Month and Year. 
## Expected Behavior

Calendar should render as shown below
![jan](https://user-images.githubusercontent.com/31983789/68112862-60369a80-ff18-11e9-8159-88c4f1808854.png)

## Observed Behavior

But it's rendering like this,
![Screenshot_1572861381](https://user-images.githubusercontent.com/31983789/68112935-8eb47580-ff18-11e9-8b89-ef67c01fa994.png)

## Environment

react-native-calendars@1.212.0
react-native@0.59.3

It's happening in both emulator and device.

Please have a look at my code,

     <CalendarList
		ref={ref => this.calendarRef = ref}
		horizontal={true}
		pagingEnabled={true}
		hideArrows={false}
		onPressArrowLeft={() => this.onArrowPress('left')}
		onPressArrowRight={() => this.onArrowPress('right')}
		onVisibleMonthsChange={months => this.onSwipeMonths(months)}
    />

    onSwipeMonths(months) {
                this.setState({loaderflag: true})  // this line causes the above mentioned issue
		let { month, dateString } = months[0];
		if (months.length == 1 && this.state.calendarDate.getMonth() != (month - 1)) {
			let selectedMonth = new Date(dateString);
			this.getCalendarData(selectedMonth);
		}	
	}

**Comment by Xiltyn** [comment]
I'm experiencing the very same issue. Whenever I use `this.setState()` on `onVisibleMonthsChange`, it fails to render months more than 1 apart from the initial one.

**Comment by Yandamuri** [comment]
@Xiltyn Glad to know that there is a solution for this issue. BTW, the link you mentioned above pointing to the same issue. Did you meant to refer any other link?

**Comment by Inbal-Tish** [comment]
@Yandamuri This is the link for the issue with the solution: https://github.com/wix/react-native-calendars/issues/884
