### ISSUE TITLE
can't scroll back if an empty day is present in agenda

### ISSUE THREAD

**Issue by anthonyhumphreys** [wix/react-native-calendars#979]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Using the agenda view, if you scroll forwards in time, it jumps past the empty day but you cannot scroll back in time without tapping the date.

## Expected Behavior

I expect to be able to scroll in both directions

## Observed Behavior
see screen recording

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.212.0
* `npm ls react-native`:  0.61.2

Also specify:

1. Phone/emulator/simulator & version: iPhone 11 Pro on 13.0

**Comment by anthonyhumphreys** [comment]
[Screen Recording 2019-11-04 at 11.33.13.zip](https://github.com/wix/react-native-calendars/files/3803779/Screen.Recording.2019-11-04.at.11.33.13.zip)

**Comment by Inbal-Tish** [comment]
@anthonyhumphreys I can't reproduce this bug in our demo app. Can you add more details like code snippet?

**Comment by jenskuhrjorgensen** [comment]
Hi @Inbal-Tish 
First of all - thanks for this lovely library! 

I've run into the same problems as @anthonyhumphreys  (thanks for providing the video. It helped me verify that you had the exact same problem as I did). 

I've created a [snack](https://snack.expo.io/ByWVQuY78) that reproduces the bug. After setting the `selected` date to a date in the "future" I cannot scroll to the previous dates in the agenda view. Furthermore, when I start scrolling down (to future dates), it almost immediately scrolls all the way to the last item.

**Comment by Inbal-Tish** [comment]
@anthonyhumphreys Please provide 'renderEmptyDate' function for your empty dates and see if the bug persists.

**Comment by jenskuhrjorgensen** [comment]
@Inbal-Tish `renderEmptyDate` is ready to be outcommented in the snack I provided earlier. I've done it  [here](https://snack.expo.io/HJk99vq78) and the bug still persists.

**Comment by uladzislaubasin** [comment]
has someone succeeded in fixing this issue?

**Comment by jenskuhrjorgensen** [comment]
@uladzislaubasin Unfortunately not. It ended up being unable to use the Agenda component for this reason.

**Comment by chenei** [comment]
Hi,
@anthonyhumphreys @jenskuhrjorgensen 
I tried to use the code you uploaded and I found the problem.
When passing items to the Agenda, you must pass a value to each date. for example:
**This is not allowed!**
`
items: {
 "2020-02-18": [{name: meeting}],
"2020-02-20": [{name: other meeting}]
}
`
You must pass _2020-02-19_:
`
items: {
 "2020-02-18": [{name: meeting}],
"2020-02-19": [],
"2020-02-20": [{name: other meeting}]
}
`

**Comment by nes123** [comment]
> Hi, @anthonyhumphreys @jenskuhrjorgensen I tried to use the code you uploaded and I found the problem. When passing items to the Agenda, you must pass a value to each date. for example: **This is not allowed!** `items: { "2020-02-18": [{name: meeting}], "2020-02-20": [{name: other meeting}] }` You must pass _2020-02-19_: `items: { "2020-02-18": [{name: meeting}], "2020-02-19": [], "2020-02-20": [{name: other meeting}] }`

It does not work when you scroll backwards. Just forward.
