### ISSUE TITLE
RenderArrow and RenderKnob on ExpandableCalendar

### ISSUE THREAD

**Issue by i-sbaral** [wix/react-native-calendars#984]
Hi guys, first of all , this is not an issue but a question.

Is it possible to use RenderArrow and RenderKnob on ExpandableCalander? I have been able to use the  arrowImageSource but i want to use my own custom arrow and knob.

**Comment by Yago** [comment]
It doesn't seem to work, even if normally you could do so... 🤔

**Comment by mtieltjes** [comment]
Got a fix for the `renderArrow` override: https://github.com/wix/react-native-calendars/pull/1037

**Comment by Inbal-Tish** [comment]
@i-sbaral Yes, `renderArrow` is now fixed thanks to @mtieltjes. `renderKnob` was never a feature so you're welcome to submit a PR.
