### ISSUE TITLE
Library has not updated based on react native documentation for lifecycle hooks

### ISSUE THREAD

**Issue by aurelhoxha** [wix/react-native-calendars#985]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

I installed the package and I expected no warnings since I just tried to open the calendar.

## Observed Behavior

The warning message came out stating that the component is not using the new lifecycle hooks and need to rename those.

WARN  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.212.0   
* `npm ls react-native`: react-native@0.61.3

Also specify:

1. Phone/emulator/simulator & version: Iphone 11 Simulator 

## Reproducible Demo
Here is a screenshot of the warning.
![Screen Shot 2019-11-12 at 11 22 03 AM](https://user-images.githubusercontent.com/38219629/68663943-c6867300-053f-11ea-902a-5a11d9857387.png)

**Comment by mihairadulescu** [comment]
this might help to get  things  going faster
https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles

**Comment by stephanikoykoy** [comment]
linking this with the newly posted issue #1008
