### ISSUE TITLE
How to change year when calendar is open

### ISSUE THREAD

**Issue by nitheeshnd** [wix/react-native-calendars#988]
Hi all,

I have a feature to add the date of birth. If I want to change the year how can I do that?

**Comment by Inbal-Tish** [comment]
@yoginitheesh Change the `current` prop.

**Comment by sumit-android-haridwar** [comment]
How to do this

**Comment by sumit-android-haridwar** [comment]
i have to change the year

**Comment by sandeepjohsnon** [comment]
how do this in same layout pls, help me
