### ISSUE TITLE
week-view

### ISSUE THREAD

**Issue by ciaoamigoschat** [wix/react-native-calendars#998]
How can I activate the view per week? Is there a way?

**Comment by ihsanktmr** [comment]
Yes there is actually but not good practise.
use this first;
```
 <CalendarProvider>
      <ExpandableCalendar firstDay={1}  />
 </CalendarProvider>
```

and then we need to change internal style of expandable calendar to do this middle-click to `ExpandableCalendar` and you should see class `index.js` of `ExpandableCalendar`
change Knob container height to 0 it should be as following

`const KNOB_CONTAINER_HEIGHT = 0;   //normally its 20`

in the same class `index.js` you should find `renderKnob()` and find the `knobContainer` style file to do this do a middle-click to `knobContainer` not to the `style` 
```
renderKnob() {
    // TODO: turn to TouchableOpacity with onPress that closes it
    return (
      <View style={this.style.knobContainer} pointerEvents={'none'}>
        <View style={this.style.knob} testID={CALENDAR_KNOB}/>
      </View>
    );
  }
```

and go to style.js change `backgroundColor` of `knobContainer` and `knob` to `transparent` it should be as follows;

```
knobContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      height: 24,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent'// normally it is  appStyle.calendarBackground
    },
    knob: {
      width: 40,
      height: 4,
      borderRadius: 3,
      backgroundColor: 'transparent'    //normally it is e8ecf0
    },
```

it should display like in the screenshot below view for weekly display

![temporary solution](https://user-images.githubusercontent.com/26416028/71644702-de77a900-2cdd-11ea-98d4-d4d6bbbb0a5a.png)

**Comment by ihsanktmr** [comment]
https://github.com/wix/react-native-calendars/issues/998

**Comment by ihsanktmr** [comment]
added props `   disablePan={true} //we need this`

**Comment by ciaoamigoschat** [comment]
Thanks for your answer. But I meant it as https://github.com/hoangnm/react-native-week-view.
I have tried react-native-week-view but it works badly and is full of bugs.

**Comment by Inbal-Tish** [comment]
@ciaoamigoschat You can use ExpandableCalendar and disable the pad using `disablePan` prop, and `hideKnob` prop. And you can use our new WeekCalendar component for a minimalist week view.
`react-native-week-view` is completely another product.

**Comment by BigNews31** [comment]
Hello, is it possible to see an implementation of the WeekCalendar component ? 

I have tried to use it, but day numbers do not display well (not aligns with day names).
ihsanktmr solution work well, but i would like to keep the scroll functionality.

Thank you :)

**Comment by Inbal-Tish** [comment]
[https://github.com/wix/react-native-calendars/blob/master/src/expandableCalendar/weekCalendar.js
](mplementationl)

**Comment by farhansamu21** [comment]
Hello, does ExpandableCalendar support all Calendar props? onDayPress seems doesnt work.

**Comment by NickM101** [comment]
How can I make the knob expand/collapse, just like in the agenda component?

**Comment by xegulon** [comment]
This helped me:
```javascript
import React from "react";
import { CalendarProvider, WeekCalendar } from "react-native-calendars";

const WeekAgendaScreen = () => (
  <CalendarProvider date={new Date().toISOString()}>
    <WeekCalendar onDayPress={(day) => console.log(day)} firstDay={1} />
  </CalendarProvider>
);
```

**Comment by gorkemkose** [comment]
Hi, is there a way to override the styling of WeekCalendar component?

**Comment by shanoysinc** [comment]
> usage

how do you style this component?
